### ISSUE TITLE
proxmox_snap cant find vmid

### ISSUE THREAD

**Issue by Tealk** [ansible-collections/community.general#10008]
### Summary

Since the 8.4 update there seem to be problems with the proxmox_snap module, because when creating a snapshot the following error message appears:
`fatal: [AFFiNE -> localhost]: FAILED! => {"changed": false, "msg": "VM with vmid 138 does not exist in cluster"}`

### Issue Type

Bug Report

### Component Name

proxmox_snap

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.18]
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True


```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 9.4.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /root/.ansible.cfg
DEFAULT_HOST_LIST(/root/.ansible.cfg) = ['/root/ansible/production']
DEFAULT_ROLES_PATH(/root/.ansible.cfg) = ['/root/ansible/roles']
INTERPRETER_PYTHON(/root/.ansible.cfg) = auto_silent

```

### OS / Environment

Debian12

### Steps to Reproduce

```yaml (paste below)
- name: Create new container snapshot and keep only the 2 newest snapshots
  community.general.proxmox_snap:
    api_host: "{{ proxmox_uri }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    vmid: "{{ vmid }}"
    state: present
    snapname: "{{ snapname }}"
    retention: 2
  delegate_to: localhost
```

### Expected Results

A snapshot is created

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
