### ISSUE TITLE
nmcli does not attempt to create connection

### ISSUE THREAD

**Issue by UnoSD** [ansible-collections/community.general#10015]
### Summary

```yaml
   - name: Set up network
     community.general.nmcli:
       conn_name: Ethernet
       ifname: enp6s0
       type: ethernet
       method4: manual
       ip4: 192.168.1.2/24
       gw4: 192.168.1.1
       dns4:
         - 1.1.1.1
         - 1.0.0.1
       state: present
       autoconnect: yes
```

results in Error: unknown connection 'Ethernet'

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/uno/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/xxx/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.5.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

Ansible: Arch Linux 
Target: Debian 12

### Steps to Reproduce

```yaml (paste below)
   - name: Set up network
     community.general.nmcli:
       conn_name: Ethernet
       ifname: enp6s0
       type: ethernet
       method4: manual
       ip4: 192.168.1.2/24
       gw4: 192.168.1.1
       dns4:
         - 1.1.1.1
         - 1.0.0.1
       state: present
       autoconnect: yes
```

```
ansible-playbook -i inventory.yaml playbook.yaml
```

### Expected Results

Network interface created

### Actual Results

```console (paste below)
Error: unknown connection 'Ethernet'
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
