### ISSUE TITLE
keycloak_user_rolemapping displays a warning message - 'list' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by danielmatthews84** [ansible-collections/community.general#10067]
### Summary

Running keycloak_user_rolemapping task produces the WARNING message `'list' object has no attribute 'splitlines'`.

Trace:
```
[WARNING]: Failure using method (v2_on_file_diff) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0xffffb0ca5400>):
'list' object has no attribute 'splitlines'
Callback Exception: 
  File "/usr/local/lib/python3.13/site-packages/ansible/executor/task_queue_manager.py", line 461, in send_callback
    method(*new_args, **kwargs)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.13/site-packages/ansible/plugins/callback/default.py", line 231, in v2_on_file_diff
    diff = self._get_diff(result._result['diff'])
   File "/usr/local/lib/python3.13/site-packages/ansible/plugins/callback/__init__.py", line 378, in _get_diff
    before_lines = diff['before'].splitlines(True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
changed: [app-server] => {
    "changed": true,
    "diff": {
        "after": [
            {
                "id": "1e93f740-37cf-4503-9925-e8581166a11f",
                "name": "admin"
            }
        ],
        "before": [
            {
                "clientRole": false,
                "composite": true,
                "containerId": "4820ddcc-9bba-4b22-a2b3-60a7419092b3",
                "description": "${role_default-roles}",
                "id": "9376f041-0f51-490d-a576-d9a29ea6ea32",
                "name": "default-roles-master"
            },
```

The task is configured as follows:
```
  - name: Assign the admin role
    community.general.keycloak_user_rolemapping:
      auth_realm: master
      auth_keycloak_url: "{{ keycloak.url }}"
      auth_username: "{{ keycloak.temp_admin }}"      
      auth_password: "{{ keycloak.temp_admin_pass }}"
      target_username: "{{ keycloak.admin_username }}"
      roles:
        - name: admin
```

It appears that the before/after diffs are lists of dicts, hence why `splitlines` fails.

### Issue Type

Bug Report

### Component Name

community.general.keycloak_user_rolemapping

### Ansible Version

2.18.2

### Community.general Version

10.6.0

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

Run the following task
```yaml (paste below)
- name: Assign the admin role
    community.general.keycloak_user_rolemapping:
      auth_realm: master
      auth_keycloak_url: "{{ keycloak.url }}"
      auth_username: "{{ keycloak.temp_admin }}"      
      auth_password: "{{ keycloak.temp_admin_pass }}"
      target_username: "{{ keycloak.admin_username }}"
      roles:
        - name: admin
```

### Expected Results

No warning should appear.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
