### ISSUE TITLE
The issue type selected is invalid

### ISSUE THREAD

**Issue by jmacedoleite16** [ansible-collections/community.general#10061]
### Summary

When i try to create a issue, with issuetype "Melhoria" i have a error in Jira.
The issue type selected is invalid
Thats my playbook 

---
- name: Criando chamado no jira 
  hosts: localhost
  tasks:
   
   - name: Create an issue
     community.general.jira:
       uri: '{{ server }}'
       username: '{{ user }}'
       password: '{{ pass }}'
       project: anonymous
       validate_certs: False
       assignee: 89502
       operation: create
       summary: New case in jira with Melhoria
       description: create new issue 
       issuetype: Melhoria
     args:
       fields:
         customfield_10389: {"value": "Info2"}
         customfield_10065: "2025-04-02" # start date
         customfield_10066: "2025-04-19" #end date 

All the time i create issuetype with field Epic and Story i can create normaly.
But if i try to Melhoria, or with issutype id of Melhoria, i just cant create...

"msg": "{'issuetype': 'The issue type selected is invalid.'}"

### Issue Type

Bug Report

### Component Name

jira

### Ansible Version

ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/jleite/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/jleite/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```


### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general                       10.5.0
already have try with version 

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Red Hat Enterprise Linux release 9.4

### Steps to Reproduce

```yaml (paste below)
---
- name: Criando chamado no jira 
  hosts: localhost
  tasks:
   
   - name: Create an issue
     community.general.jira:
       uri: '{{ server }}'
       username: '{{ user }}'
       password: '{{ pass }}'
       project: anonymous
       validate_certs: False
       assignee: 89502
       operation: create
       summary: New case in jira with Melhoria
       description: create new issue 
       issuetype: Melhoria
     args:
       fields:
         customfield_10389: {"value": "Info2"}
         customfield_10065: "2025-04-02" # start date
         customfield_10066: "2025-04-19" #end date 
```

### Expected Results

Confirmed change.

### Actual Results

```console (paste below)
"msg": "{'issuetype': 'The issue type selected is invalid.'}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
