### ISSUE TITLE
Incorrect usage of variables in `crypttab` `EXAMPLES`

### ISSUE THREAD

**Issue by sivel** [ansible-collections/community.general#10078]
### Summary

The `EXAMPLES` for `crypttab` show an example of:

```yaml
- name: Add the 'discard' option to any existing options for all devices
  community.general.crypttab:
    name: '{{ item.device }}'
    state: opts_present
    opts: discard
  loop: '{{ ansible_mounts }}'
  when: "'/dev/mapper/luks-' in {{ item.device }}"
```

The jinja2 delimiters should be removed such as:

```diff
-   when: "'/dev/mapper/luks-' in {{ item.device }}"
+   when: "'/dev/mapper/luks-' in item.device" 
```

### Issue Type

Documentation Report

### Component Name

crypttab

### Ansible Version

```console (paste below)
$ ansible --version

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

N/A

### Additional Information

N/A

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
