### ISSUE TITLE
community.keycloak_user module fails with conflict

### ISSUE THREAD

**Issue by Pearmint** [ansible-collections/community.general#10103]
### Summary

When using community.keycloak_user (version 9.5.7) the create user module fails if there is already a user created with the same username. Also the force parameter does not work. 

The returned 409 conflict is interpreted as failure.

### Issue Type

Bug Report

### Component Name

keycloak_user

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.16.0]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general


Collection        Version
----------------- -------
community.general 9.4.0  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
---
- name: Create Testuser
  community.general.keycloak_user:
    auth_keycloak_url: http://localhost:8080/
    auth_username: admin
    auth_password: adminpassword
    auth_realm: master
    realm: admin
    username: testuser
    firstName: Testuser
    lastName: for Testing
    email: testuser@example.com
    enabled: true
    emailVerified: false
    credentials:
      - type: password
        value: "password"
        temporary: false
    state: present
```

### Expected Results

I should succeed without changing anything (if userdata is unchanged).

### Actual Results

```console (paste below)
TASK [keycloak : Create Testuser] ***************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not create user testuser in realm admin: HTTP Error 409: Conflict: {\"errorMessage\":\"User exists with same username\"}"}

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by Pearmint** [comment]
This is still happening. Even with updated Keycloak (26.3.1), updated community.general collection (11.0.0).

**Comment by markus2330** [comment]
Still happening.

**Comment by felixfontein** [comment]
This module is community maintained, meaning that if nobody from the community (which includes you all) creates a PR to fix this, it won't get fixed.

**Comment by markus2330** [comment]
Can you point us to where in the code the problem might be?

**Comment by felixfontein** [comment]
My guess would be that retrieving the existing user (https://github.com/ansible-collections/community.general/blob/main/plugins/modules/keycloak_user.py#L437) doesn't work for some reason. The code called there is in plugins/module_utils/identity/keycloak/keycloak.py.

**Comment by Pearmint** [comment]
Found the issue. Even though the above code creates the user correctly the username of the created user is the email.

Changing it to the following fixes the problem.
 ```
---
- name: Create Testuser
  community.general.keycloak_user:
    auth_keycloak_url: http://localhost:8080/
    auth_username: admin
    auth_password: adminpassword
    auth_realm: master
    realm: admin
    username: testuser@example.com
    firstName: Testuser
    lastName: for Testing
    email: testuser@example.com
    enabled: true
    emailVerified: false
    credentials:
      - type: password
        value: "password"
        temporary: false
    state: present
```
