### ISSUE TITLE
community.general.proxmox: An error occurred: local variable 'identifier' referenced before assignment

### ISSUE THREAD

**Issue by wfjsw** [ansible-collections/community.general#10119]
### Summary

I am trying to define a few containers in my Proxmox cluster with `community.general.proxmox`. Apart from trying `update` and it complains about `parameters are mutually exclusive: clone|ostemplate|update`, I decided to give `force` a go and it fails with `An error occurred: local variable 'identifier' referenced before assignment`.

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.13]
  config file = /workspaces/infra-conf/ansible.cfg
  configured module search path = ['/workspaces/infra-conf/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/py-utils/venvs/ansible-core/lib/python3.9/site-packages/ansible
  ansible collection location = /workspaces/infra-conf/collections:/usr/share/ansible/collections
  executable location = /usr/local/py-utils/bin/ansible
  python version = 3.9.2 (default, Mar 20 2025, 02:07:39) [GCC 10.2.1 20210110] (/usr/local/py-utils/venvs/ansible-core/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/local/py-utils/venvs/ansible-core/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.2  

# /workspaces/infra-conf/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.6.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_HOME(env: ANSIBLE_HOME) = /workspaces/infra-conf
ANSIBLE_PIPELINING(/workspaces/infra-conf/ansible.cfg) = True
CONFIG_FILE() = /workspaces/infra-conf/ansible.cfg
DEFAULT_HOST_LIST(/workspaces/infra-conf/ansible.cfg) = ['/workspaces/infra-conf/hosts.yaml']
```

### OS / Environment

Performed on localhost. Localhost is a devcontainer derived from this config:

```json
{
	"name": "Debian",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/hspaans/devcontainer-features/ansible-lint:1": {},
		"ghcr.io/devcontainers-extra/features/ansible:2": {
			"injections": "proxmoxer requests"
		},
		"ghcr.io/devcontainers/features/terraform:1": {},
		"ghcr.io/devcontainers-extra/features/packer-asdf:2": {}
	},

	"containerEnv": {
	    "ANSIBLE_CONFIG": "${containerWorkspaceFolder}/ansible.cfg",
		"ANSIBLE_HOME": "${containerWorkspaceFolder}",
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"redhat.ansible"
			]
		}
	}
}
```

Server is running Proxmox VE 8.4.1.

### Steps to Reproduce

```yaml (paste below)
- name: Configure project pools
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Initiate Proxmox VE pool
      community.general.proxmox_pool:
        api_host: <redacted>
        api_user: <redacted>
        api_password: <redacted>
        poolid: obsrv
        comment: Observability

    - name: Boot Loki backend instances
      community.general.proxmox:
        vmid: "{{ 2000 + item }}"
        node: <redacted>
        api_host: <redacted>
        api_user: <redacted>
        api_password: <redacted>
        pubkey: "{{ lookup('file', '<redacted>') }}"
        hostname: "loki-backend-{{ item }}"
        ostemplate: local:vztmpl/alpine-3.21-default_20241217_amd64.tar.xz
        cores: 4
        description: |
          Loki backend instance {{ item }}  
          Managed by Ansible
        disk_volume:
          storage: local-zfs
          size: 4
          options:
            mountoptions: lazytime;noatime
        memory: 4096
        swap: 4096
        onboot: true
        pool: obsrv
        searchdomain: obsrv
        timezone: host
        force: true
        netif:
          net0: "name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0,tag=2,firewall=1"
      loop: "{{ range(1, 3) | list }}"
```

### Expected Results

Waht I really want is making Ansible create those CT if they does not exist, and update meta fields (e.g. Comments, CPU / Memory / Network / DNS etc.) otherwise. `update` apparently doesn't want to do that. I suspect `force` will wipe and recreate the CT each time I run the playbook even if nothing changed, but I might just live with that.

### Actual Results

```console (paste below)
TASK [Boot Loki backend instances] ************************************************************************************************************************************************
task path: /workspaces/infra-conf/plays/projects/obsrv.yaml:11
File lookup using /workspaces/infra-conf/plays/projects/../../data/vm_root_authorized_keys as file
Using module file /workspaces/infra-conf/collections/ansible_collections/community/general/plugins/modules/proxmox.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vscode
<127.0.0.1> EXEC /bin/sh -c '/usr/local/py-utils/venvs/ansible-core/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.general.proxmox_payload_s60ly92g/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 1732, in main
  File "/tmp/ansible_community.general.proxmox_payload_s60ly92g/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 784, in run
  File "/tmp/ansible_community.general.proxmox_payload_s60ly92g/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 895, in lxc_present
[DEPRECATION WARNING]: The default value of false for 'update' has been deprecated and will be changed to true in version 11.0.0. This feature will be removed from 
community.general in version 11.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [localhost] (item=1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "<redacted>",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_port": null,
            "api_token_id": null,
            "api_token_secret": null,
            "api_user": "root@pam",
            "clone": null,
            "clone_type": "opportunistic",
            "cores": 4,
            "cpus": null,
            "cpuunits": null,
            "description": "Loki backend instance 1  \nManaged by Ansible\n",
            "disk": null,
            "disk_volume": {
                "host_path": null,
                "options": {
                    "mountoptions": "lazytime;noatime"
                },
                "size": 4,
                "storage": "local-zfs",
                "volume": null
            },
            "features": null,
            "force": true,
            "hookscript": null,
            "hostname": "loki-backend-1",
            "ip_address": null,
            "memory": 4096,
            "mount_volumes": null,
            "mounts": null,
            "nameserver": null,
            "netif": {
                "net0": "name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0,tag=2,firewall=1"
            },
            "node": "<redacted>",
            "onboot": true,
            "ostemplate": "local:vztmpl/alpine-3.21-default_20241217_amd64.tar.xz",
            "ostype": "auto",
            "password": null,
            "pool": "obsrv",
            "pubkey": "<redacted>",
            "purge": false,
            "searchdomain": "obsrv",
            "startup": null,
            "state": "present",
            "storage": "local",
            "swap": 4096,
            "tags": null,
            "timeout": 30,
            "timezone": "host",
            "unprivileged": true,
            "update": null,
            "validate_certs": false,
            "vmid": 2001
        }
    },
    "item": 1,
    "msg": "An error occurred: local variable 'identifier' referenced before assignment"
}
File lookup using /workspaces/infra-conf/plays/projects/../../data/vm_root_authorized_keys as file
Using module file /workspaces/infra-conf/collections/ansible_collections/community/general/plugins/modules/proxmox.py
Pipelining is enabled.
<127.0.0.1> EXEC /bin/sh -c '/usr/local/py-utils/venvs/ansible-core/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.general.proxmox_payload_qiz2gd2g/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 1732, in main
  File "/tmp/ansible_community.general.proxmox_payload_qiz2gd2g/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 784, in run
  File "/tmp/ansible_community.general.proxmox_payload_qiz2gd2g/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 895, in lxc_present
failed: [localhost] (item=2) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "<redacted>",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_port": null,
            "api_token_id": null,
            "api_token_secret": null,
            "api_user": "root@pam",
            "clone": null,
            "clone_type": "opportunistic",
            "cores": 4,
            "cpus": null,
            "cpuunits": null,
            "description": "Loki backend instance 2  \nManaged by Ansible\n",
            "disk": null,
            "disk_volume": {
                "host_path": null,
                "options": {
                    "mountoptions": "lazytime;noatime"
                },
                "size": 4,
                "storage": "local-zfs",
                "volume": null
            },
            "features": null,
            "force": true,
            "hookscript": null,
            "hostname": "loki-backend-2",
            "ip_address": null,
            "memory": 4096,
            "mount_volumes": null,
            "mounts": null,
            "nameserver": null,
            "netif": {
                "net0": "name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0,tag=2,firewall=1"
            },
            "node": "<redacted>",
            "onboot": true,
            "ostemplate": "local:vztmpl/alpine-3.21-default_20241217_amd64.tar.xz",
            "ostype": "auto",
            "password": null,
            "pool": "obsrv",
            "pubkey": "<redacted>",
            "purge": false,
            "searchdomain": "obsrv",
            "startup": null,
            "state": "present",
            "storage": "local",
            "swap": 4096,
            "tags": null,
            "timeout": 30,
            "timezone": "host",
            "unprivileged": true,
            "update": null,
            "validate_certs": false,
            "vmid": 2002
        }
    },
    "item": 2,
    "msg": "An error occurred: local variable 'identifier' referenced before assignment"
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
