### ISSUE TITLE
kdeconfig: unable to pass a value beginning with `-` 

### ISSUE THREAD

**Issue by rmroczk** [ansible-collections/community.general#10127]
### Summary

The following task fails because the kwriteconfig5 command sent to the shell by the module does not properly handle values beginning with a - character.

I can successfully use kwriteconfig5 from command line if I place -- in front of the value but there doesn't seem to be a way to inform the module to end the option list prior to sending the value.

Is there a way to make this work without resorting to using the command module?

```yaml
---
- name: Test me
  hosts: localhost 
  tasks:
  - name: Issue
    community.general.kdeconfig:
      path: /home/bob/.config/plasma-org.kde.plasma.desktop-appletsrc
      values:
        - groups: [Containments, 2, Applets, 38, Configuration, Station]
          key: longitude
          value: '-88.123'
      mode: '0600'
```
```
fatal: [localhost]: FAILED! => changed=false 
  cmd: /usr/bin/kwriteconfig5 --file /home/test/.ansible/tmp/ansible-tmp-1747105216.8291476-113549-85062219413162/tmpxej70zvy/file --key longitude --group Containments --group 2 --group Applets --group 38 --group Configuration --group Station -88.123
  msg: 'kwriteconfig5: Unknown options: 8, 8, ., 1, 2, 3.'
  rc: 1
  stderr: |-
    kwriteconfig5: Unknown options: 8, 8, ., 1, 2, 3.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

### Issue Type

Bug Report

### Component Name

kdeconfig

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.10]
  config file = /home/test/.ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/test/.ansible/collections:/usr/lib/python3/dist-packages
  executable location = /home/test/.local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 10.1.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Kubuntu 24.04.2 LTS

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

I expect values to be prefixed by -- to avoid this issue.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
