### ISSUE TITLE
community.general.sudoers overwriting current permissions

### ISSUE THREAD

**Issue by Raymond-Epitech** [ansible-collections/community.general#10179]
### Summary

When i try to use the sudoers module with an existing name, instead of appending the new rule to the current file, the file is fully overwritten and only the new rule is set.

### Issue Type

Bug Report

### Component Name

sudoers

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.18]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

debian on wsl2 arm64 (surface pro 11)

### Steps to Reproduce

```yaml (paste below)
  - name: Add sudo right to read enery file for xymon usr
    become: true
    become_user: root
    community.general.sudoers:
      name: xymon
      user: xymon
      commands:
        - /bin/cat /sys/class/powercap/intel-rapl/*/energy_uj
```

### Expected Results

I expect the `xymon ALL=NOPASSWD: /bin/cat /sys/class/powercap/intel-rapl/*/energy_uj` line to be appended to the `/etc/sudoers.d/xymon` file.

### Actual Results

The file is overwritten, only 
```
xymon ALL=NOPASSWD: /bin/cat /sys/class/powercap/intel-rapl/*/energy_uj
```
is left.

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
