### ISSUE TITLE
community.general.proxmox_disk not idempotent with iso_image: none

### ISSUE THREAD

**Issue by dirks** [ansible-collections/community.general#10171]
### Summary

When I want to ensure there is no iso/disk in the cdrom drive using `community.general.proxmox_disk` in version 10.7.0 with

```yaml
  disk: ide2
  media: cdrom
  iso_image: none
```
and the targeted vm already has `"ide2": "none:media=cdrom"` in the running configuration, the task always returns `changed`. It does not matter if this is the first run or a consecutive run. In proxmox "Tasks" I see a configure task for the respective vm:

```
update VM 106: -ide2 none,media=cdrom
TASK OK
```

### Issue Type

Bug Report

### Component Name

proxmox_disk

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.6]
  config file = /home/dirk/GEOMAR/projects/ansible/server/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 07:44:25) [GCC 14.2.1 20250207] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.13/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml
- name: Remove iso image from vm cd drive.
  community.general.proxmox_disk:
    api_host: node1
    api_user: root@pam
    api_token_id: token1
    api_token_secret: some-token-data
    vmid: 106
    disk: ide2
    media: cdrom
    iso_image: none
    state: present
```

### Expected Results

The tasks returns `changed: false` if the declared value of the disk matches the one in the running configuration.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
