### ISSUE TITLE
proxmox_kvm: VM not cloned if name exists

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [ansible-collections/community.general#10186]
### Summary

The problem is similar to #6155: when cloning VM an error occurs `Multiple VMs with name VMNAME found, provide vmid instead`.
I am trying to clone VM template from one Proxmox cluster node (`pve0`) to another (`pve11`). VM template is located on CEPH storage, so cloning is possible.

I specify all the VM IDs explicitly: `pve0` `vmid=5000` `name=template` --> `pve11` `vmid=5011` `name=template`

Ansible script:
```yaml
    - name: copy template
      proxmox_kvm:
        api_user:     '{{ proxmox.user }}'
        api_password: '{{ proxmox.pass }}'
        api_host:     pve0

        node:         pve0                  # src node
        vmid:         5000                  # src vmid
        clone:        any-value-for-clone   # src name (any value if vmid specified)

        target:       pve11                 # dst node
        newid:        5011                  # dst vmid
        name:         template              # dst name

        full:         no
```

Actual result:
```
TASK [copy template]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Multiple VMs with name template found, provide vmid instead"}
```

I can not `provide vmid instead`, because `vmid` is already provided.
If I comment param `name` or set `name` to any unique value (`name: 5011` - same as `newid`) module works well - template copied successfully.

This is incorrect, because Proxmox allows VMs with the same name even on the same node, you should not check names when VM IDs provided (and should not check dst names at all).

https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/proxmox.py
```python
    136     def get_vmid(self, name, ignore_missing=False, choose_first_if_multiple=False):
    137         try:
    138             vms = [vm['vmid'] for vm in self.proxmox_api.cluster.resources.get(type='vm') if vm.get('name') == name]
    ...
    147         elif len(vms) > 1 and not choose_first_if_multiple:
    148             self.module.fail_json(msg='Multiple VMs with name %s found, provide vmid instead' % name)

```

`get_vmid()` must not be called when `vmid` is provided, because it does not receive `vmid` as parameter, so it does not know whether it is provided or not.

https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py
```python
   1381     if clone is not None:
   ....
   1389         # Ensure source VM name exists when cloning
   1390         if not vmid:
   1391             module.fail_json(msg='VM with name = %s does not exist in cluster' % clone)
   1392
   1393         # Ensure source VM id exists when cloning
   1394         proxmox.get_vm(vmid)
   1395
   1396         # Ensure the chosen VM name doesn't already exist when cloning
   1397         existing_vmid = proxmox.get_vmid(name, ignore_missing=True)
   1398         if existing_vmid:
   1399             module.exit_json(changed=False, vmid=existing_vmid, msg="VM with name <%s> already exists" % name)
```

Error occurs in `get_vmid()` on line #1397. `Ensure the chosen VM name doesn't already exist when cloning` - there is no need in this check, no any problem if VM with such name exists. And also `vmid` is double checked at line #1390 and #1394, so it can not be not provided at `get_vmid()` call.

Suggested fix:
```diff
--- community.general/plugins/modules/proxmox_kvm.py 2025-05-29 10:49:45.651891557 +0000
+++ community.general/plugins/modules/proxmox_kvm.py 2025-05-29 12:30:22.933813690 +0000
@@ -1421,11 +1421,6 @@
         # Ensure source VM id exists when cloning
         proxmox.get_vm(vmid)

-        # Ensure the chosen VM name doesn't already exist when cloning
-        existing_vmid = proxmox.get_vmid(name, ignore_missing=True)
-        if existing_vmid:
-            module.exit_json(changed=False, vmid=existing_vmid, msg="VM with name <%s> already exists" % name)
-
         # Ensure the chosen VM id doesn't already exist when cloning
         if proxmox.get_vm(newid, ignore_missing=True):
             module.exit_json(changed=False, vmid=vmid, msg="vmid %s with VM name %s already exists" % (newid, name))
```

Workaround for Ansible: clone template with any unique name (`name=newid`) and then update to correct name.

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.17.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

Collection        Version
----------------- -------
community.general 10.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ununtu 24.04

### Steps to Reproduce

```yaml (paste below)
    - name: copy template
      proxmox_kvm:
        api_user:     '{{ proxmox.user }}'
        api_password: '{{ proxmox.pass }}'
        api_host:     pve0
        node:         pve0                  # src node
        vmid:         5000                  # src vmid
        clone:        any-value-for-clone   # src name (any value if vmid specified)
        target:       pve11                 # dst node
        newid:        5011                  # dst vmid
        name:         template              # dst name
        full:         no

```

### Expected Results

Copying of template VM.

### Actual Results

```console (paste below)
Multiple VMs with name VMNAME found, provide vmid instead
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
