### ISSUE TITLE
community.general.proxmox_kvm hangs and times out when starting VM if exitstatus is "Warning"

### ISSUE THREAD

**Issue by it-ankka** [ansible-collections/community.general#10185]
### Summary

When I try to start a VM using proxmox_kvm `state: started` in using the Github main branch, it hangs and times out if the received exitstatus is anything other than "OK". This includes valid exitstatus values such as "Warnings". This warning can be caused by something like `iothreads=1` in disk definition when the current driver does not support it, in which case it is simply ignored and the machine starts normally.

The issue is located in the [api_task_ok function](https://github.com/ansible-collections/community.general/blob/35d736f78b69dfe6537ac74e765047dff6630f98/plugins/module_utils/proxmox.py#L166) in `proxmox.py` called by the [wait_for_task function](https://github.com/ansible-collections/community.general/blob/35d736f78b69dfe6537ac74e765047dff6630f98/plugins/modules/proxmox_kvm.py#L986) which is used in validating the startup of the machine.

It currently only checks for "OK":

```python
def api_task_ok(self, node, taskid):
    try:
        status = self.proxmox_api.nodes(node).tasks(taskid).status.get()
        return status['status'] == 'stopped' and status['exitstatus'] == 'OK'
    except Exception as e:
        self.module.fail_json(msg='Unable to retrieve API task ID from node %s: %s' % (node, e))
```
But it should also accept "Warning" as a valid exitstatus since the VM still starts without issues
```python
def api_task_ok(self, node, taskid):
    try:
        status = self.proxmox_api.nodes(node).tasks(taskid).status.get()
        valid_exitstatus = status['exitstatus'] == 'OK' or status['exitstatus'].startswith('Warning')
        return status['status'] == 'stopped' and valid_exitstatus
    except Exception as e:
        self.module.fail_json(msg='Unable to retrieve API task ID from node %s: %s' % (node, e))
```

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.5]
  config file = /home/cote/Projects/linux-tooling/ansible/ansible.cfg
  configured module search path = ['/home/cote/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cote/Projects/linux-tooling/ansible/.venv/lib64/python3.13/site-packages/ansible
  ansible collection location = /home/cote/Projects/linux-tooling/ansible/collections
  executable location = /home/cote/Projects/linux-tooling/ansible/.venv/bin/ansible
  python version = 3.13.3 (main, Apr 22 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/home/cote/Projects/linux-tooling/ansible/.venv/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/cote/Projects/linux-tooling/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = True
BECOME_ALLOW_SAME_USER(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = ./run/facts
CACHE_PLUGIN_TIMEOUT(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = 604800
CALLBACKS_ENABLED(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = ['ansible.posix.timer']
COLLECTIONS_PATHS(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = ['/home/cote/Projects/linux-tooling/ansible/collections']
CONFIG_FILE() = /home/cote/Projects/linux-tooling/ansible/ansible.cfg
DEFAULT_FORKS(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = 32
DEFAULT_GATHERING(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = ['/home/cote/Projects/linux-tooling/ansible/inventories/pve.yml']
DEFAULT_LOG_PATH(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = /home/cote/Projects/linux-tooling/ansible/run/log/run.log
DEFAULT_NO_TARGET_SYSLOG(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = True
DEFAULT_REMOTE_USER(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = ['/home/cote/Projects/linux-tooling/ansible/roles']
DEFAULT_TIMEOUT(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = 5
DIFF_ALWAYS(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = True
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = False
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/cote/Projects/linux-tooling/ansible/ansible.cfg) = /home/cote/Projects/linux-tooling/ansible/run/retry
```

### OS / Environment

```console
$ uname -a
Linux fedora 6.14.6-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri May  9 19:55:50 UTC 2025 x86_64 GNU/Linux
```

### Steps to Reproduce

```yaml (paste below)
---
- name: Create and start a Proxmox KVM VM
  hosts: proxmox
  gather_facts: false
  vars:
    vm_id: 111
    vm_name: test-vm
    pve_api_user: "root@pam"
    pve_api_password: "pve_password_here"
    pve_node: pve
    pve_storage: local-lvm
    disk_size: 10
  tasks:

    - name: Create the VM which causes a warning
      community.general.proxmox_kvm:
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        api_host: "{{ ansible_host }}"
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        scsihw: "virtio-scsi-pci"
        scsi:
          scsi0: "{{ pve_storage }}:{{ disk_size }},iothread=1" # This causes the warning
        state: present

    - name: Start the VM
      community.general.proxmox_kvm:
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        api_host: "{{ ansible_host }}"
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        state: started

```

### Expected Results

The task should have completed successfully, because the VM started succesfully. Instead it hangs and fails.

### Actual Results

```console (paste below)
$ ansible-playbook playbook.yml -i inventory.yml

PLAY [Create and start a Proxmox KVM VM] *******************************************************************************************************************************

TASK [Create the VM which causes a warning] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='pve', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x78b2588c38d0>, 'Connection to pve timed out. (connect timeout=5)'))
fatal: [proxmox]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "HTTPSConnectionPool(host='pve', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x78b2588c38d0>, 'Connection to pve timed out. (connect timeout=5)'))"}

PLAY RECAP *************************************************************************************************************************************************************
proxmox                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
