### ISSUE TITLE
swapfile creation with filesize and filesystem

### ISSUE THREAD

**Issue by ulvida** [ansible-collections/community.general#10187]
### Summary

Al debian bookworm proxmox c-i images have no longer any swap, I try to configure a swapfile with the following code:
in the role's defaults:
```
cielito_swap_filesize: 1G

cielito_swap_dev: /swapfile

```
in the tasks:
```
- name: Create a file of appropriate size in /
  community.general.filesize:
    path: '{{ cielito_swap_dev }}'
    size: '{{ cielito_swap_filesize }}'
    mode: '600'
    

- name: Format and configure swap filesystem
  community.general.filesystem:
    dev: '{{ cielito_swap_dev }}'
    fstype: swap
    state: present
```
the first task creates the file, the second succeeds with ok, but seems to do nothing. The file is not a swap and nothing added to `/etc/fstab`.

What am I doing wrong or what is wrong?  Thanks in advance for your suggestions.

### Issue Type

Bug Report

### Component Name

filesystem

### Ansible Version

```
$ ansible --version
ansible [core 2.18.3]
  config file = /home/ulvida/devops/adminsys/config/ansible.cfg
  configured module search path = ['/home/ulvida/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ulvida/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ulvida/devops/adminsys/UdelaRInterior
  executable location = /home/ulvida/.local/bin/ansible
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/home/ulvida/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.5
  libyaml = True

```

### Community.general Version

```
$ ansible-galaxy collection list community.general

# /home/ulvida/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.4.0 

# /home/ulvida/devops/adminsys/UdelaRInterior/ansible_collections
Collection        Version
----------------- -------
community.general 9.1.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

debian 12

### Steps to Reproduce

in the role's defaults:

```yaml
cielito_swap_filesize: 1G

cielito_swap_dev: /swapfile

```
in the tasks:
```yaml
- name: Create a file of appropriate size in /
  community.general.filesize:
    path: '{{ cielito_swap_dev }}'
    size: '{{ cielito_swap_filesize }}'
    mode: '600'
    

- name: Format and configure swap filesystem
  community.general.filesystem:
    dev: '{{ cielito_swap_dev }}'
    fstype: swap
    state: present
```

### Expected Results

I expect to have in the configured host:
```
root@alfa:~# swapon --show
NAME      TYPE  SIZE  USED PRIO
/swapfile file 1024M 44,1M   -2
```
and:
```
# cat /etc/fstab | grep swap
/swapfile	none	swap	sw	0	0
```

### Actual Results

On the configured host, the `swapfile` is created (first task ok)
```
root@divino:/# ls -la swapfile 
-rw------- 1 root root 1073741824 may 29 18:30 swapfile
```
but it doesn't become a swap:
```
# swapon --show
```
returns nothing, as well as:
```
# cat /etc/fstab | grep swap
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
