### ISSUE TITLE
Allow to redefine API_BASE in github_key module

### ISSUE THREAD

**Issue by lexlog** [ansible-collections/community.general#10190]
### Summary

Currently github_key module has [API_BASE](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/github_key.py#L108) hardcoded to `api.github.com`.
It prevents to use it on self-hosted (Github Enterprise) instances.

If there is an option to redefine API_BASE, it will allow to use this module in self-hosted Github.

Proposal - add module argument `api_url`, which will be 'https://api.github.com' by default, but will be redefinable to custom url .

### Issue Type

Feature Idea

### Component Name

github_key

### Additional Information

```yaml (paste below)
# For GitHub.com (current behavior)
- name: Authorize key with GitHub
  community.general.github_key:
    name: Access Key for Some Machine
    token: '{{ github_access_token }}'
    pubkey: "{{ ssh_public_key }}"

# For GitHub Enterprise
- name: Authorize key with GitHub Enterprise
  community.general.github_key:
    name: Access Key for Some Machine
    token: '{{ github_enterprise_token }}'
    pubkey: "{{ ssh_public_key }}"
    api_url: 'https://github.company.com/api/v3'
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
