### ISSUE TITLE
community.general.keycloak_authentication module doesn't seem to support basic-flow creation

### ISSUE THREAD

**Issue by nodje** [ansible-collections/community.general#10197]
### Summary

I'm trying to create a simple 2-steps basic-flow, as indicated in the doc [here](https://www.keycloak.org/docs/latest/server_admin/index.html#_detect_existing_user_first_login_flow) for a classic use-case.

In the export dump, it's represented like this:

```
    {
      "id": "18f1f506-929b-4a8d-8f91-47b3ae55c5cd",
      "alias": "Detect existing user first login flow",
      "description": "",
      "providerId": "basic-flow",
      "topLevel": true,
      "builtIn": false,
      "authenticationExecutions": [
        {
          "authenticator": "idp-detect-existing-broker-user",
          "authenticatorFlow": false,
          "requirement": "REQUIRED",
          "priority": 0,
          "autheticatorFlow": false,
          "userSetupAllowed": false
        },
        {
          "authenticator": "idp-auto-link",
          "authenticatorFlow": false,
          "requirement": "REQUIRED",
          "priority": 1,
          "autheticatorFlow": false,
          "userSetupAllowed": false
        }
      ]
    },
```

These "authenticator" values are actual pre-coded possible steps, available within the UI when clicking Add Execution.
I don't see anyway to create them so far with the module that seem dedicated to Authentication Flows.

### Issue Type

Bug Report

### Component Name

community.general.keycloak_authentication module

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.5]
  config file = /home/shared/projects/ldap-keycloak-poc/ansible.cfg
  ansible python module location = /home/shared/projects/ldap-keycloak-poc/.venv/lib/python3.12/site-packages/ansible
  executable location = /home/shared/projects/ldap-keycloak-poc/.venv/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 11.4.0] (/home/shared/projects/ldap-keycloak-poc/.venv/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 10.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

There should be a way to build an Authentication Flow using the pre-coded execution steps.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/keycloak_authentication.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/keycloak_authentication.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Gaetan2907 @eikef @elfelip @mattock @ndclt @thomasbach-dev
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by nodje** [comment]
I was able to create a dedicated flow as desired. I somehow misunderstood how to use this module.

Here's a working example for whoever stumble upon this:

```
  community.general.keycloak_authentication:
    auth_client_id: "admin-cli"
    auth_keycloak_url: "http://localhost:8080"
    auth_password: "password"
    auth_realm: "master"
    auth_username: "admin"
    realm: "master"
    alias: "{{ my_oidc_idp_dedicated_first_login_flow }}"
    providerId: basic-flow
    description: "Detect existing user and automatically link with provider's"
    authenticationExecutions:
      - providerId: "idp-detect-existing-broker-user"
        requirement: "REQUIRED"
      - providerId: "idp-auto-link"
        requirement: "REQUIRED"
    force: false #If true, allows to remove the authentication flow and recreate it. (but Identity Provider using it must be deleted first)
    state: present
```

Maybe this could be added to the module doc as an example of Authentication Flow creation (rather than editing only, which seem to be the only use case illustrated by example)
