### ISSUE TITLE
Cloudflare DNS Module Fails Due to Deprecated API Filtering Parameters

### ISSUE THREAD

**Issue by mojodevopsone** [ansible-collections/community.general#10208]
### Summary

The Cloudflare DNS module is failing due to recent Cloudflare API changes regarding DNS record filtering parameters. The API no longer supports filtering multiple contents with URL parameters.

### Issue Type

Bug Report

### Component Name

cloudflare_dns module

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.17.7]
  config file = /home/mojo-rakib/Desktop/mojo-infra/ansible.cfg
  configured module search path = ['/home/mojo-rakib/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mojo-rakib/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mojo-rakib/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mojo-rakib/.local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

Collection        Version
----------------- -------
community.general 10.7.0 

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

CONFIG_FILE() = /home/mojo-rakib/Desktop/mojo-infra/ansible.cfg
HOST_KEY_CHECKING(/home/mojo-rakib/Desktop/mojo-infra/ansible.cfg) = False

```

### OS / Environment

Ubuntu 24.04 LTS

### Steps to Reproduce

```yaml (paste below)

- name: Setup Cloudflare DNS
  hosts:
    - all
  become: true
  max_fail_percentage: 0
  tasks:  
    - name: "Update DMARC Record"
      community.general.cloudflare_dns:
        zone: "privamta.com"
        record: "_dmarc"
        type: TXT
        solo: true
        state: present
        value: '"v=DMARC1; p=quarantine; rua=mailto:b4a68c1.a@dmarcinput.com,mailto:mailadmin@emaly.net; ruf=mailto:b468c1.f@dmarcinput.com,mailto:mailadmin@emaly.net; fo=1"'
        account_email: "{{ cf_email }}"
        account_api_token: "{{ cf_api_token }}"
      throttle: 1 # One request at a time
```
```bash
ansible-playbook playbook.yml --ask-vault-pass
```

### Expected Results

```console
TASK [Update DMARC Record] *****************************************************
changed: [152.90.59.10]
```

### Actual Results

```console (paste below)
TASK [Update DMARC Record] *****************************************************
fatal: [199.241.136.2]: FAILED! => {"changed": false, "msg": "API bad request; Status: 400; Method: GET: Call: /zones/630cd00910ad4e61941167976251c383/dns_records?type=TXT&name=_dmarc.privamta.com&content=%22v%3DDMARC1%3B+p%3Dquarantine%3B+rua%3Dmailto%3Ab4a0cad068c1.a%40dmarcinput.com%2Cmailto%3Amailadmin%40emaly.net%3B+ruf%3Dmailto%3Ab4a0cad068c1.f%40dmarcinput.com%2Cmailto%3Amailadmin%40emaly.net%3B+fo%3D1%22; Error details: code: 9334, error: Filtering for multiple contents with URL parameter \"content=\\\"v=DMARC1; p=quarantine; rua=mailto:b4a0c8c1.a@dmarcinput.com,mailto:mailadmin@emaly.net; ruf=mailto:b4a0c8c1.f@dmarcinput.com,mailto:mailadmin@emaly.net; fo=1\\\"\" is no longer supported. See <https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#2025-02-21> for more information.; "}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
