### ISSUE TITLE
mssql_script module should support alternate login credentials and script file paths

### ISSUE THREAD

**Issue by zollo** [ansible-collections/community.general#10201]
### Summary

I'd like to see two changes made to this module:

1. Support Alternate Credentials - These credentials would be used if the primary ones fail, module output should reflect which credential was used.

2. Script File Path - As an alternative to the raw script input, we should also support reading a script file path - and this should also check for and remove the presence of a byte order mark - which is known to cause problems with MSSQL server.

### Issue Type

Feature Idea

### Component Name

mssql_script

### Additional Information

```yaml
- name: Run SQL script file with alternate credentials
  community.general.mssql_script:
    login_user: "{{ mssql_login_user }}"
    login_password: "{{ mssql_login_password }}"
    login_user_alt: "{{ mssql_login_user_alt }}"
    login_password_alt: "{{ mssql_login_password_alt }}"
    login_host: "{{ mssql_host }}"
    login_port: "{{ mssql_port }}"
    db: master
    script_path: /path/to/script.sql
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
