### ISSUE TITLE
Inventory iocage - get inventory alias from iocage tags.

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#10206]
### Summary

If implemented, it will enable [inventory aliases](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#inventory-aliases).

For example, given the template *ansible_client*, the easiest and fastest way to create multiple jails is to use the *--count* option

```bash
shell> iocage create --short --count 3 --template ansible_client bpf=1 dhcp=1 vnet=1
a09ce39b successfully created!
7356a325 successfully created!
26c2fa42 successfully created!
```

creates three jails

```bash
shell> iocage list -l
+------+----------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
| JID  |   NAME   | BOOT | STATE | TYPE |     RELEASE     |        IP4         | IP6 |    TEMPLATE    | BASEJAIL |
+======+==========+======+=======+======+=================+====================+=====+================+==========+
| None | 26c2fa42 | off  | down  | jail | 14.2-RELEASE-p3 | DHCP (not running) | -   | ansible_client | no       |
+------+----------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
| None | 7356a325 | off  | down  | jail | 14.2-RELEASE-p3 | DHCP (not running) | -   | ansible_client | no       |
+------+----------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
| None | a09ce39b | off  | down  | jail | 14.2-RELEASE-p3 | DHCP (not running) | -   | ansible_client | no       |
+------+----------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
```

The names are random. Start the jails

```bash
shell> iocage start ALL
No default gateway found for ipv6.
* Starting 26c2fa42
  + Started OK
  + Using devfs_ruleset: 1000 (iocage generated default)
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
  + DHCP Address: 10.1.0.160/24
No default gateway found for ipv6.
* Starting 7356a325
  + Started OK
  + Using devfs_ruleset: 1001 (iocage generated default)
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
  + DHCP Address: 10.1.0.189/24
No default gateway found for ipv6.
* Starting a09ce39b
  + Started OK
  + Using devfs_ruleset: 1002 (iocage generated default)
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
  + DHCP Address: 10.1.0.241/24
Please convert back to a jail before trying to start ansible_client
```

Create the inventory configuration

```yaml
shell> cat hosts/02_iocage.yml
plugin: community.general.iocage
host: 10.1.0.73
user: admin
hooks_results:
  - /var/db/dhclient-hook.address.epair0b
compose:
  ansible_host: (iocage_hooks.0 == '-') | ternary(iocage_ip4, iocage_hooks.0)
```

gives the inventory

```yaml
shell> ansible-inventory -i hosts/02_iocage.yml --list --yaml
all:
  children:
    ungrouped:
      hosts:
        26c2fa42:
          ansible_host: 10.1.0.160
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.160
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '196'
          iocage_release: 14.2-RELEASE-p3
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
        7356a325:
          ansible_host: 10.1.0.189
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.189
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '197'
          iocage_release: 14.2-RELEASE-p3
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
        a09ce39b:
          ansible_host: 10.1.0.241
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.241
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '198'
          iocage_release: 14.2-RELEASE-p3
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
```

The random names are not practical in all use cases.

**This feature request proposes a new option *inventory_hostname_tag* with the description**:

* The name of the tag in the C(iocage properties notes) that contains the jails alias.
* By default, the C(iocage list -l) column C(NAME) is used to name the jail.
* This option requires the notes format C("t1=v1 t2=v2 ...")
* The option O(get_properties) must be enabled.

Note: man iocage says:

  notes="any string"
                     Custom notes for miscellaneous tagging.

For example, add the property notes

```yaml
shell> iocage set notes="alias=srv_1" 26c2fa42
notes: none -> alias=srv_1

shell> iocage set notes="alias=srv_2" 7356a325
notes: none -> alias=srv_2

shell> iocage set notes="alias=srv_3" a09ce39b
notes: none -> alias=srv_3
```

Update the inventory configuration. Get the properties (get_properties: true) and tell the plugin a jail alias is in the tag *alias* (inventory_hostname_tag: alias)

```yaml
shell> cat hosts/02_iocage.yml
plugin: community.general.iocage
host: 10.1.0.73
user: admin
get_properties: true
inventory_hostname_tag: alias
hooks_results:
  - /var/db/dhclient-hook.address.epair0b
compose:
  ansible_host: (iocage_hooks.0 == '-') | ternary(iocage_ip4, iocage_hooks.0)
```

Then, the plugin gets the host's aliases from the tag. The random name is stored in the properties.

```yaml
shell> ansible-inventory -i hosts/02_iocage.yml --list --yaml
all:
  children:
    ungrouped:
      hosts:
        srv_1:
          ansible_host: 10.1.0.160
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.160
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '196'
          iocage_properties:
	    ...
            host_hostname: 26c2fa42
            host_hostuuid: 26c2fa42
	    ...
        srv_2:
          ansible_host: 10.1.0.189
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.189
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '197'
          iocage_properties:
	    ...
            host_hostname: 7356a325
            host_hostuuid: 7356a325
	    ...
        srv_3:
          ansible_host: 10.1.0.241
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.241
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '198'
          iocage_properties:
	    ...
            host_hostname: a09ce39b
            host_hostuuid: a09ce39b
	    ...
```

### Issue Type

Feature Idea

### Component Name

plugins/inventory/iocage.py

### Additional Information

* The utility *iocage* can create jails with the required names

```bash
iocage create --template ansible_client --name srv_1
iocage create --template ansible_client --name srv_2
iocage create --template ansible_client --name srv_3
```

* The proposed option is useful when multiple tags are created across multiple iocage hosts. For example,

```bash
iocage set notes="alias=srv_1 vmm={{ inventory_hostname }} project=e020" 26c2fa42
iocage set notes="alias=srv_2 vmm={{ inventory_hostname }} project=e020" 7356a325
iocage set notes="alias=srv_3 vmm={{ inventory_hostname }} project=e020" a09ce39b
```

JFYI, in this use case, the inventory plugin can compose the dictionary

```yaml
compose:
  iocage_tags: dict(iocage_properties.notes | split | map('split', '='))
```

and the *constructed* plugin creates the groups

```yaml
shell> cat hosts/99_constructed.yml 
plugin: ansible.builtin.constructed
keyed_groups:
  - prefix: vmm
    key: iocage_tags.vmm
  - prefix: project
    key: iocage_tags.project
```

 * With this option, all combinations of inventory alias, hostname, and ansible_host are possible.

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
