### ISSUE TITLE
git_config support for specifying a file (git config -f option)

### ISSUE THREAD

**Issue by kunickiaj** [ansible-collections/community.general#1021]
##### SUMMARY

I'd like to see the git_config module support the -f option in git config to specify an explicit config file to modify.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git_config

##### ADDITIONAL INFORMATION

This is useful for tools that use gitconfig format such as Gerrit for configuration when you don't want to use a template.

```yaml
- name: Add a setting to /var/gerrit/etc/gerrit.config
  community.general.git_config:
    name: container.heapLimit
    scope: file
    file: /var/gerrit/etc/gerrit.config
    value: 8g
```
