### ISSUE TITLE
zfs modules isn't idempotent when setting encryption: "on"

### ISSUE THREAD

**Issue by tomhesse** [ansible-collections/community.general#10226]
### Summary

When using the encryption parameter with the value true or “on”, ZFS uses the standard encryption suite. For the module to be idempotent, `encryption: true/“on”` must be handled like `encryption: aes-256-gcm`. Otherwise the module will fail because the encryption property can only be set at dataset creation. At the time of writing aes-256-gcm is the default encryption suite. 

### Issue Type

Feature Idea

### Component Name

zfs

### Additional Information

```yaml (paste below)
- name: Ensure dataset exists
  community.general.zfs:
    name: tank/dataset
    state: present
    extra_zfs_properties:
      encryption: "on"
      keylocation: file:///etc/zfs/keys/dataset.key
      keyformat: raw
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
