### ISSUE TITLE
Parted does not recognize differences in partition sizes

### ISSUE THREAD

**Issue by Hoeze** [ansible-collections/community.general#10235]
### Summary

Hi, I want to change a volume with 2x 50% partitions to 1x 100% partition.
However, running the parted module does not take any action, even though the first partition does not occupy 100% of the volume.

Is there a way to force re-creation if the partition table does not match what I specify?

### Issue Type

Bug Report

### Component Name

parted

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.1]
  config file = $PROJECT_DIR/ansible/ansible.cfg
  configured module search path = ['$USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/anaconda/envs/terraform/lib/python3.13/site-packages/ansible
  ansible collection location = $PROJECT_DIR/ansible/external/collections
  executable location = /opt/anaconda/envs/terraform/bin/ansible
  python version = 3.13.1 | packaged by conda-forge | (main, Jan 13 2025, 09:53:10) [GCC 13.3.0] (/opt/anaconda/envs/terraform/bin/python3.13)
  jinja version = 3.1.5
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 10.7.0 

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
```

### Steps to Reproduce

```yaml
---
- name: Partition and mount volumes
  hosts: all
  tasks:
    - name: Set partition setup
      set_fact:
        part_setup:
          - device: /dev/vdb
            label: gpt
            partitions:
              - number: 1
                name: data
                part_start: "0%"
                part_end: "50%"
                filesystem: xfs
                mount:
                  - path: /data
                    opts: defaults
          - device: /dev/vdb
            label: gpt
            partitions:
              - number: 2
                name: data
                part_start: "50%"
                part_end: "100%"
                filesystem: xfs
                mount:
                  - path: /data
                    opts: defaults

    - name: Build partition list
      set_fact:
        partition_list: >-
          {{ 
            part_setup 
              | subelements('partitions') 
              | map('combine', {"state": "present"})
              | ansible.utils.remove_keys(['partitions'])
          }}

    - name: debug partition_list
      ansible.builtin.debug:
        var: partition_list

    - name: Create partitions
      become: true
      community.general.parted: "{{ item }}"
      loop: "{{ partition_list | ansible.utils.remove_keys(['mount', 'filesystem']) }}"
      loop_control:
        label: "{{ item.device }}{{ item.number }}"
      register: partition_setup

    - name: Run partprobe after partition changes
      command: partprobe
      when: partition_setup.changed

    - name: Format partition
      become: true
      ansible.builtin.filesystem:
        fstype: "{{ item.filesystem }}"
        dev: "{{ item.device }}{{ item.number }}"
        state: "present"
      loop: "{{ partition_list }}"

    - name: Mount partitions
      become: true
      mount: >-
        {{
          {
            "src": item.0.device ~ (item.0.number | string),
            "state": "mounted",
            "fstype": item.0.filesystem,
          } | combine(item.1)
        }}
      loop: "{{ partition_list | subelements('mount') }}"
      loop_control:
        label: "{{ item.0.device }}{{ item.0.number }} -> {{ item.1.path }}"

        
        
        
        

    - name: Set partition setup
      set_fact:
        part_setup:
          - device: /dev/vdb
            label: gpt
            partitions:
              - number: 1
                name: data
                part_start: "0%"
                part_end: "100%"
                filesystem: xfs
                mount:
                  - path: /data
                    opts: defaults


    - name: Build partition list
      set_fact:
        partition_list: >-
          {{ 
            part_setup 
              | subelements('partitions') 
              | map('combine', {"state": "present"})
              | ansible.utils.remove_keys(['partitions'])
          }}

    - name: debug partition_list
      ansible.builtin.debug:
        var: partition_list

    - name: Create partitions
      become: true
      community.general.parted: "{{ item }}"
      loop: "{{ partition_list | ansible.utils.remove_keys(['mount', 'filesystem']) }}"
      loop_control:
        label: "{{ item.device }}{{ item.number }}"
      register: partition_setup

    - name: Run partprobe after partition changes
      command: partprobe
      when: partition_setup.changed

    - name: Format partition
      become: true
      ansible.builtin.filesystem:
        fstype: "{{ item.filesystem }}"
        dev: "{{ item.device }}{{ item.number }}"
        state: "present"
      loop: "{{ partition_list }}"

    - name: Mount partitions
      become: true
      mount: >-
        {{
          {
            "src": item.0.device ~ (item.0.number | string),
            "state": "mounted",
            "fstype": item.0.filesystem,
          } | combine(item.1)
        }}
      loop: "{{ partition_list | subelements('mount') }}"
      loop_control:
        label: "{{ item.0.device }}{{ item.0.number }} -> {{ item.1.path }}"
        

```

### Expected Results

```console (paste below)
ok: [s3_test_node] => (item=/dev/vdb1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "disk": {
        "dev": "/dev/vdb",
        "logical_block": 512,
        "model": "Virtio Block Device",
        "physical_block": 512,
        "size": 8388608000.0,
        "table": "gpt",
        "unit": "kib"
    },
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/vdb",
            "flags": null,
            "fs_type": null,
            "label": "gpt",
            "name": "data",
            "number": 1,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "resize": false,
            "state": "present",
            "unit": "KiB"
        }
    },
    "item": {
        "device": "/dev/vdb",
        "label": "gpt",
        "name": "data",
        "number": 1,
        "part_end": "100%",
        "part_start": "0%",
        "state": "present"
    },
    "partitions": [
        {
            "begin": 1024.0,
            "end": 8388606976.0,
            "flags": [],
            "fstype": "xfs",
            "name": "data",
            "num": 1,
            "size": 8388605952.0,
            "unit": "kib"
        },
    ],
```

### Actual Results

```console (paste below)
ok: [s3_test_node] => (item=/dev/vdb1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "disk": {
        "dev": "/dev/vdb",
        "logical_block": 512,
        "model": "Virtio Block Device",
        "physical_block": 512,
        "size": 8388608000.0,
        "table": "gpt",
        "unit": "kib"
    },
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/vdb",
            "flags": null,
            "fs_type": null,
            "label": "gpt",
            "name": "data",
            "number": 1,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "resize": false,
            "state": "present",
            "unit": "KiB"
        }
    },
    "item": {
        "device": "/dev/vdb",
        "label": "gpt",
        "name": "data",
        "number": 1,
        "part_end": "100%",
        "part_start": "0%",
        "state": "present"
    },
    "partitions": [
        {
            "begin": 1024.0,
            "end": 4194304000.0,
            "flags": [],
            "fstype": "xfs",
            "name": "data",
            "num": 1,
            "size": 4194302976.0,
            "unit": "kib"
        },
        {
            "begin": 4194304000.0,
            "end": 8388606976.0,
            "flags": [],
            "fstype": "xfs",
            "name": "data2",
            "num": 2,
            "size": 4194302976.0,
            "unit": "kib"
        }
    ],
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
