### ISSUE TITLE
idrac_redfish_config - SetManagerAttributes broken in iDRAC 10

### ISSUE THREAD

**Issue by dupondje** [ansible-collections/community.general#10232]
### Summary

On servers with an iDRAC 10, the SetManagerAttributes command is broken.

This because https://x.x.x.x/redfish/v1/Managers/iDRAC.Embedded.1/Attributes gives a 404 on iDRAC 10.
The attributes are now under the following path:
https://x.x.x.x/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1

This path also seems to work on iDRAC 9, but there the old path also worked.
But since iDRAC 10 only the new path exists.

### Issue Type

Bug Report

### Component Name

idrac_redfish_config

### Ansible Version

```console (paste below)
ansible [core 2.18.6]
  config file = /home/jean-louis/.ansible.cfg
  configured module search path = ['/home/jean-louis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/jean-louis/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 07:44:25) [GCC 14.2.1 20250207] (/usr/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.13/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0 

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Arch - Dell iDRAC10

### Steps to Reproduce

```yaml (paste below)
  community.general.idrac_redfish_config:
   category: Manager
   command: SetManagerAttributes
   resource_id: iDRAC.Embedded.1
   manager_attributes:
    Users.2.AuthenticationProtocol: "SHA"
    Users.2.EmailAddress: ""
    Users.2.Enable: "Enabled"
    Users.2.IpmiLanPrivilege: "Administrator"
    Users.2.IpmiSerialPrivilege: "Administrator"
    Users.2.Password: "{{ idrac_vault.password }}"
    Users.2.PrivacyProtocol: "AES"
    Users.2.Privilege: 511
    Users.2.ProtocolEnable: "Disabled"
    Users.2.Simple2FA: "Disabled"
    Users.2.SolEnable: "Enabled"
    Users.2.UseEmail: "Disabled"
    Users.2.UserName: "root"
   baseuri: "{{ idrac_ip }}"
   username: "{{ user }}"
   password: "calvin"
```

### Expected Results

This works fine on iDRAC 9, broken (gives 404) on iDRAC 10.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
