### ISSUE TITLE
dnf_versionlock: incompatible with dnf5

### ISSUE THREAD

**Issue by ntonnaett** [ansible-collections/community.general#10237]
### Summary

When using the dnf_versionlock module on Fedora 42 it fails due to the "missing" versionlock plugin. With dnf5 versionlock was made part of the main application. There are probably more things to fix to make the module compatible with dnf5.

### Issue Type

Bug Report

### Component Name

dnf_versionlock

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.14]
  config file = /home/xxx/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.10 (main, Apr 22 2025, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```


### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.12/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.6.8  

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.4.0
```


### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CACHE_PLUGIN(/home/xxx/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/xxx/ansible.cfg) = ./cache
CONFIG_FILE() = /home/xxx/ansible.cfg
DEFAULT_HOST_LIST(/home/xxx/ansible.cfg) = ['/home/xxx/ansible/hosts']
EDITOR(env: EDITOR) = vim
RETRY_FILES_ENABLED(/home/xxx/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/xxx/ansible.cfg) = /home/xxx/.ansible-retry
```


### OS / Environment

_No response_

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: clear current versionlocks                                                                                                                                                                                                                                              
  community.general.dnf_versionlock:                                                                                                                                                                                                                                            
    state: clean 
```


### Expected Results

It should remove all versionlocks.

### Actual Results

```console (paste below)
TASK [clear current versionlocks] ***********************************************************************************************************
fatal: [xxxx]: FAILED! => {"changed": false, "msg": "plugin versionlock is required"}
```


### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
