### ISSUE TITLE
Keyring lookup module does not work with linux SecretService

### ISSUE THREAD

**Issue by mpeter50** [ansible-collections/community.general#10243]
### Summary

The keyring lookup module is unable to effectively lookup passwords from the SecretService backend.
After tracking down what is wrong, it seems the problem is with the keyring python module it uses. That module seems to overcomplicate querying the password, for the sake of attempting to fit the query into an unusual service-username based query.

I assume that in the module, password querying would happen here: https://github.com/jaraco/keyring/blob/71dedcbcf21847f358ad0510ea6bff59de1449a2/keyring/backends/SecretService.py#L77
But it has a seemingly useless limitation on the name of the keys, by forcing both words in the string to be interpreted as values: https://github.com/jaraco/keyring/blob/71dedcbcf21847f358ad0510ea6bff59de1449a2/keyring/backend.py#L281

Actually the module tries to be compatible with password managers, like KeePassXC, but this plugin module does not make use of that feature.

With SecretService, queries are based on key-value pairs, possibly multiple of them.
The `secret-tool` command's `lookup` subcommand presents the expected way of operation. Given a string like "key1 value1 key2 value2", it will find the first match that matches the given pairs, and return the password for it.
The proper way to handle this would be to just pass the "service" as a key, and the "username" as a value.

An alternative solution is to make use of the modules [scheme selection](https://github.com/jaraco/keyring/blob/71dedcbcf21847f358ad0510ea6bff59de1449a2/keyring/backend.py#L263C7-L263C23), and expose that as a module argument.

### Issue Type

Bug Report

### Component Name

keyring

### Ansible Version

```console (paste below)
$ ansible --version
2.18.3
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
10.4.0
```

### OS / Environment

openSUSE Leap 15.6

### Steps to Reproduce

1. Set up KeePassXC password manager as the SecretService provider (as I know, there can be only a single one active at a time), and 
2. Select the group in the keepass database which is to be used for serving SecretService requests
3. Create a password item with the username being "username", and the URL being "https://example.com"
4. Run the below tasks in a playbook (but replace Uuid with the UUID of your password entry, visible in the "Properties" page of the item editor menu.

```yaml (paste below)
- name: output secrets to screen (BAD IDEA)
  ansible.builtin.debug:
    msg: "Password: {{ lookup("community.general.keyring", "UserName username URL https://example.com") }}"

- name: output secrets to screen (BAD IDEA)
  ansible.builtin.debug:
    msg: "Password: {{ lookup("community.general.keyring", "Uuid xxxxxxxxxxxxxxxxxxxx") }}"
```

### Expected Results

The right passwords are printed to the terminal

### Actual Results

localhost | FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'community.general.keyring'. Error was a <class 'ansible.errors.AnsibleError'>, original message: servicename: Uuid for user xxxxxxxxxxxxxxxxxxxx not found. servicename: Uuid for user xxxxxxxxxxxxxxxxxxxx not found"
}

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
