### ISSUE TITLE
redhat_subscription fails on RHEL 10 when state is absent

### ISSUE THREAD

**Issue by dvanderveer** [ansible-collections/community.general#10260]
#### Problem
When executed on an RHEL 10.0 system, the `redhat_subscription` module fails when `state` is set to `absent`. The module attempts to execute `/usr/sbin/subscription-manager remove --all`, but this command exits with return code 1 and prints the usage text for `subscription-manager`.

#### Evaluation
The root cause is fairly obvious. There's no `subscription-manager remove` option in RHEL 10, which has simplified registration to a single `register` step and no longer allows attachment or removal of specific subscriptions.

### Issue Type

Bug Report

### Component Name

redhat_subscription

### Ansible Version

```console
ansible [core 2.18.6]
  config file = None
  configured module search path = ['/home/dvanderveer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dvanderveer/community.general/lib/python3.12/site-packages/ansible
  ansible collection location = /home/dvanderveer/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dvanderveer/venvs/community.general/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/home/dvanderveer/venvs/community.general/bin/python3)
  jinja version = 3.1.6
  libyaml = True
```

### Community.general Version

```console
Collection        Version
----------------- -------
community.general 10.7.0
```

### Configuration

```console
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

RHEL 10.0

### Steps to Reproduce

```yaml
---
- hosts: all
  gather_facts: false
  tasks:
    # this step should succeed as long as auto_attach is false; see https://github.com/ansible-collections/community.general/issues/10253
    - name: RHEL register
      community.general.redhat_subscription:
        auto_attach: false
        password: "<password>"
        state: present
        username: "<username>"
    # this step will fail
    - name: RHEL unregister
      community.general.redhat_subscription:
        state: absent
```

### Expected Results

The RHEL 10 system is unregistered.

### Actual Results

```console
<hostname> | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.12"
    },
    "changed": false,
    "cmd": "/usr/sbin/subscription-manager remove --all",
    "msg": "",
    "rc": 1,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "<snip>",
    "stdout_lines": [
        "Usage: subscription-manager MODULE-NAME [MODULE-OPTIONS] [--help]",
        "",
        "Primary Modules: ",
        "",
        "  list           List subscription and product information for this system",
        "  refresh        Pull the latest subscription data from the server",
        "  register       Register this system to the Customer Portal or another subscription management service",
        "  release        Configure which operating system release to use",
        "  status         Show status information for this system",
        "  unregister     Unregister this system from the Customer Portal or another subscription management service",
        "",
        "Other Modules:   ",
        "",
        "  clean          Remove all local system and subscription data without affecting the server",
        "  config         List, set, or remove the configuration parameters in use by this system",
        "  environments   Display the environments available for a user",
        "  facts          View or update the detected system information",
        "  identity       Display the identity certificate for this system or request a new one",
        "  orgs           Display the organizations against which a user can register a system",
        "  plugins        View and configure with 'subscription-manager plugins'",
        "  repo-override  Manage custom content repository settings",
        "  repos          List the repositories which this system is entitled to use",
        "  syspurpose     Convenient module for managing all system purpose settings",
        "  version        Print version information",
        ""
    ]
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
