### ISSUE TITLE
keycloak_client protocol_mappers claim with spaces

### ISSUE THREAD

**Issue by colbacc8** [ansible-collections/community.general#10309]
### Summary

There is a bug in the Keycloak Ansible module keycloak_client when using Ansible version 2.16.

When defining protocol mappers with a claim value that contains a string with spaces, the Keycloak user interface displays the claim value correctly. However, the field does not appear to be properly recognized by Keycloak, which treats the claim value as if it were empty.

the string that I'm trying to define in the protocol mappers claim value field of a keycloak client is:

`rabbitmq_permission="rabbitmq-instance.configure:itserr_vhost/*/* rabbitmq-instance.read:itserr_vhost/*/*"`

the variable is then passed to the protocol mappers of the keycloak_client role module: 

```
protocol_mappers:
   - config: 
      introspection.token.claim": true
      claim.value": "{{ rabbitmq_permission }}"
      userinfo.token.claim": true
      id.token.claim": false
      lightweight.claim": true
      access.token.claim": true
      claim.name": "rabbitmq" #see add_scope_key in rabbitmq service
      jsonType.label": String
      access.tokenResponse.claim": false
    name: "rabbitmq-access-rights"
    protocol: "openid-connect"
    protocolMapper: "oidc-hardcoded-claim-mapper"
    consentRequired: false
```

I found a work around: the user must manually make a minor change to the claim value through the Keycloak UI—such as removing and re-adding a character or a space—and then click Save. After doing this, Keycloak correctly registers the claim value.

### Issue Type

Bug Report

### Component Name

keycloak_client 

### Ansible Version

```console (paste below)
$ ansible --version

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

I expected that the claim value of the protocol mappers are correctly added in the token generated by keycloak when using the keycloak_client. 
At the moment, the claim value field in the token is empty. 

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
