### ISSUE TITLE
archive module reports no change when it changes the zip

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/community.general#1043]
##### SUMMARY

There are some circumstances where the `archive` module will report that the Ansible task has not changed, but the module has correctly changed the contents of the `.zip` file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
archive

##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /home/ec2-user/.ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/env/local/lib/python3.6/dist-packages/ansible
  executable location = /home/ec2-user/env/bin/ansible
  python version = 3.6.12 (default, Aug 31 2020, 18:56:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/ec2-user/.ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/ec2-user/.ansible.cfg) = /dev/shm/ansible/tmp_local/ansible-local-1069740w52z4_
```

##### OS / ENVIRONMENT

Amazon Linux

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  vars:
    zip_dest: "/tmp/zip.zip"
    zip_src: "/tmp/zip_source"
    zip_extracted: "/tmp/zip_extracted"
  tasks:
  - name: reset after previous run
    with_items:
    - "{{ zip_dest }}"
    - "{{ zip_src }}"
    - "{{ zip_extracted }}"
    file:
      state: absent
      path: "{{ item }}"
    
  
  - name: create directory to be zipped up
    file:
      state: directory
      path: "{{ zip_src }}"
      
  - name: create a file to be zipped up
    copy:
      content: "hello"
      dest: "{{ zip_src }}/hello_1.txt"
      
  - name: create zip the first time
    archive:
      path: "{{ zip_src }}"
      dest: "{{ zip_dest }}"
      
  - name: rename the source file
    shell: mv {{ zip_src }}/hello_1.txt {{ zip_src }}/hello_2.txt
    
  - name: zip again with renamed contents
    archive:
      path: "{{ zip_src }}"
      dest: "{{ zip_dest }}"
    register: zip2
    
  - name: create directory to unzip into
    file:
      state: directory
      path: "{{ zip_extracted }}"
    
  - name: unzip to check the change is there
    unarchive:
      src: "{{ zip_dest }}"
      dest: "{{ zip_extracted }}"
    
  - name: check the contents of the zip has changed
    assert:
      that:
      - '"{{ zip_extracted }}/zip_source/hello_2.txt" is exists'
      - '"{{ zip_extracted }}/zip_source/hello_1.txt" is not exists'
    
  - name: check previous task is marked as changed
    assert:
      that:
      - zip2 is changed
      
```

##### EXPECTED RESULTS

The playbook should run without error.

##### ACTUAL RESULTS

The playbook fails because of the final assertion.
The contents of the zip has changed, but the task is not marked as changed.

Note that if you add a trailing slash to the path being zipped up, the expected result is observed in this MWE. (Although I have seen it happen in my full, non-minimal playbook, with the trailing slash.)
