### ISSUE TITLE
gitlab_runner broken with python-gitlab package 2.5.0

### ISSUE THREAD

**Issue by stgrace** [ansible-collections/community.general#1047]
##### SUMMARY
When using the gitlab_runner module with the latest version of python package `python-gitlab`, gitlab_runner fails.

When running the module again with what I had previously installed (python-gitlab==1.7.0), the module works fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gitlab_runner

##### ANSIBLE VERSION

```
ansible 2.9.13
  config file = None
  configured module search path = ['/Users/stefgraces/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/stefgraces/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.7/bin/ansible
  python version = 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION
```paste below
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/tmp/ansible-roles']
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
```

##### OS / ENVIRONMENT

OS: macOS Mojave 10.14.5
GitLab version: 13.4.2

##### STEPS TO REPRODUCE

Use the following task, with the following vars:

```yaml
---
- name: Register runners with API
  gitlab_runner:
    api_url: "{{ gitlab_url }}"
    api_token: "{{ gitlab_private_token }}"
    registration_token: "{{ gitlab_registration_token }}"
    description: "{{ item.key }}"
    tag_list: "{{ item.value.tag_list |default(omit) }}"
    run_untagged: "{{ item.value.run_untagged |default(omit) }}"
    locked: "{{ item.value.locked |default(omit) }}"
    access_level: "{{ item.value.access_level |default(omit) }}"
    maximum_timeout: "{{ item.value.maximum_timeout |default(omit) }}"
    state: "{{ state }}"
  loop: "{{ runners | dict2items}}"
  register: api
  changed_when: no
```

Vars used:
```yaml
  vars:
    runners:
      dome-belgium-nossegem-dev-vsphere-k8s:
        tag_list: [docker]
    gitlab_registration_token: REDACTED
    gitlab_url: https://git.example.com
    gitlab_runner_image_registry_url: ''
    gitlab_private_token: REDACTED
```

##### EXPECTED RESULTS

Expected result: register a runner with the API

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/Users/stefgraces/.ansible/tmp/ansible-tmp-1601976150.059958-67283-136703856582297/AnsiballZ_gitlab_runner.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/stefgraces/.ansible/tmp/ansible-tmp-1601976150.059958-67283-136703856582297/AnsiballZ_gitlab_runner.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/stefgraces/.ansible/tmp/ansible-tmp-1601976150.059958-67283-136703856582297/AnsiballZ_gitlab_runner.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.source_control.gitlab_runner', init_globals=None, run_name='__main__', alter_sys=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/cv/xq3n92qs71d3tgv69zvmlt3c0000gn/T/ansible_gitlab_runner_payload_2el0i7b4/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 392, in <module>
  File "/var/folders/cv/xq3n92qs71d3tgv69zvmlt3c0000gn/T/ansible_gitlab_runner_payload_2el0i7b4/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py", line 357, in main
TypeError: __init__() got an unexpected keyword argument 'email'
failed: [localhost] (item={'key': 'dome-belgium-nossegem-dev-vsphere-k8s', 'value': {'tag_list': ['docker'], 'kubernetes': {'image': 'ubi8/ubi-minimal:8.0-159', 'namespace': 'gitlab-runner', 'privileged': True, 'pull_policy': 'always'}, 'image_pull_secrets': ['secret']}}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "gitlab-runner-1",
        "value": {
            "image_pull_secrets": [
                "gitlab-runner-secret"
            ],
            "kubernetes": {
                "image": "ubi8/ubi-minimal:8.0-159",
                "namespace": "gitlab-runner",
                "privileged": true,
                "pull_policy": "always"
            },
            "tag_list": [
                "docker"
            ]
        }
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/stefgraces/.ansible/tmp/ansible-tmp-1601976150.059958-67283-136703856582297/AnsiballZ_gitlab_runner.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/stefgraces/.ansible/tmp/ansible-tmp-1601976150.059958-67283-136703856582297/AnsiballZ_gitlab_runner.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/stefgraces/.ansible/tmp/ansible-tmp-1601976150.059958-67283-136703856582297/AnsiballZ_gitlab_runner.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.source_control.gitlab_runner', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/cv/xq3n92qs71d3tgv69zvmlt3c0000gn/T/ansible_gitlab_runner_payload_2el0i7b4/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 392, in <module>\n  File \"/var/folders/cv/xq3n92qs71d3tgv69zvmlt3c0000gn/T/ansible_gitlab_runner_payload_2el0i7b4/ansible_gitlab_runner_payload.zip/ansible/modules/source_control/gitlab_runner.py\", line 357, in main\nTypeError: __init__() got an unexpected keyword argument 'email'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
