### ISSUE TITLE
docker_container: do not update label when a label is removed

### ISSUE THREAD

**Issue by neilime** [ansible-collections/community.general#1053]
##### SUMMARY

Removing labels of a running container is not applied

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /ansible/config/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/ansible/config/ansible.cfg) = ['/ansible/config/hosts.yml']
DEFAULT_ROLES_PATH(/ansible/config/ansible.cfg) = ['/etc/ansible/roles']
DEPRECATION_WARNINGS(/ansible/config/ansible.cfg) = False
HOST_KEY_CHECKING(/ansible/config/ansible.cfg) = False
RETRY_FILES_ENABLED(/ansible/config/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Alpine Linux v3.12

##### STEPS TO REPRODUCE
When we start a container with the following playbook

```yaml
  community.general.docker_container:
    state: started
    name: whoami
    image: whoami
    labels: 
       test1: test1
       test2: test2
```
Then we remove the label in the playbook : 

```yaml
  community.general.docker_container:
    state: started
    name: whoami
    image: whoami
    labels: 
       test1: test1
```

##### EXPECTED RESULTS

The container should runs with the new labels config : 

```
       test1: test1
``` 

##### ACTUAL RESULTS

The container is still running and has the old labels : 

```
       test1: test1
       test2: test2
```
