### ISSUE TITLE
nmcli vlan arguments for egress, flags, and ingress aren't used

### ISSUE THREAD

**Issue by jbronn** [ansible-collections/community.general#1086]
##### SUMMARY

The following arguments have no effect on `nmcli` connections of type `vlan`:
* [`flags`](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html#parameter-flags)
* [`ingress`](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html#parameter-ingress)
* [`egress`](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html#parameter-egress)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`nmcli`

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jbronn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jbronn/.local/lib/python3.8/site-packages/ansible
  executable location = /home/jbronn/.local/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ubuntu 20.04, Python 3.8.5.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  become: true
  tasks:
    - nmcli:
        conn_name: home-test
        state: present
        type: vlan
        ifname: enp0s31f6.100
        vlandev: enp0s31f6
        vlanid: 100
        flags: '4'
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
```

##### EXPECTED RESULTS

Running the following playbook, I'd expect the `home-test` connection to have `vlan.flags` be set to 4 (`LOOSE_BINDING`).

##### ACTUAL RESULTS

The connection `vlan.flags` are the default `1` (`REORDER_HEADERS`):

```paste below
$ nmcli con show home-test | grep ^vlan
vlan.parent:                            enp0s31f6
vlan.id:                                100
vlan.flags:                             1 (REORDER_HEADERS)
vlan.ingress-priority-map:              --
vlan.egress-priority-map:               --
```

##### ADDITIONAL NOTES

* It's easy to see in the module source that `vlan.flags`, `vlan.egress`, and `vlan.ingress` aren't used in [`Nmcli.{create,modify}_connection_vlan()`](https://github.com/ansible-collections/community.general/blob/e48083e66b3b2fa0695b6fc71c4fb33247a79a4a/plugins/modules/net_tools/nmcli.py#L1146-L1205).
* I think the type of `flags` should actually be an integer to reflect that `vlan.flags` is actually `uint32` (`NMVlanFlags`) and `egress` / `ingress` should be lists of strings to reflect that they are list of 802.1p priority mappings (see `man nm-settings`).
