### ISSUE TITLE
nmcli: new arguments to ignore automatic dns servers and gateways

### ISSUE THREAD

**Issue by jbronn** [ansible-collections/community.general#1087]
##### SUMMARY

It'd be nice to be able to control whether routes and dns servers from automatic sources are ignored.  This is especially handy if you have multiple DHCP connections and wish to ignore the DNS servers and gateways from the others.  Basically to add the following new arguments:

| `nmcli` module argument | NetworkManager setting |
|-------------------------|------------------------| 
| `dns4_ignore_auto` | `ipv4.ignore-auto-dns` |
| `gw4_ignore_auto` | `ipv4.ignore-auto-routes` |
| `dns6_ignore_auto` | `ipv6.ignore-auto-dns` |
| `gw6_ignore_auto` | `ipv6.ignore-auto-routes` |

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`nmcli`

##### ADDITIONAL INFORMATION

```yaml
- name: 'primary connection'
  nmcli:
    conn_name: primary
    type: ethernet
    ifname: eth0
- name: 'secondary connection'
  nmcli:
    conn_name: secondary
    type: ethernet
    ifname: eth1
    dns4_ignore_auto: true
    dns6_ignore_auto: true
    gw4_ignore_auto: true
    gw6_ignore_auto: true
```

Note: these would be nice to have in implementing this feature:
* The IPv4 and IPv6 methods could be explicitly set (e.g., to `auto`).
* The `Nmcli` connection creation/modification methods modified IP settings consistently across connection types.
