### ISSUE TITLE
nmcli: allow multiple IP addresses

### ISSUE THREAD

**Issue by jbronn** [ansible-collections/community.general#1088]
##### SUMMARY
The `ip4` and `ip6` arguments should be treated as lists, allowing for multiple IP addresses (aliases) per connection.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`nmcli`

##### ADDITIONAL INFORMATION

```yaml
---
- nmcli:
    conn_name: lan
    state: present
    type: ethernet
    ifname: eth0
    ip4:
      - 192.168.1.2/24
      - 192.168.1.3/24
```

Note: these would be nice to have before implementing this feature:
  - `Nmcli` connection creation/modification methods modified IP settings consistently across connection types.
