### ISSUE TITLE
nmcli: cannot modify connection's interface name after creation

### ISSUE THREAD

**Issue by jbronn** [ansible-collections/community.general#1089]
##### SUMMARY
The connection interface name (`ifname` argument) cannot be modified on a connection after creation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`nmcli`

##### ANSIBLE VERSION
```paste below
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jbronn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jbronn/.local/lib/python3.8/site-packages/ansible
  executable location = /home/jbronn/.local/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ubuntu 20.04, Python 3.8.5.

##### STEPS TO REPRODUCE
Create connection using `$vlandev.$vlanid` as the format for the connection interface name:

```yaml
- hosts: all
  tasks:
    - nmcli:
        conn_name: home-test
        autoconnect: false
        state: present
        type: vlan
        ifname: eth0.100
        vlandev: eth0
        vlanid: 100
  vars:
    ansible_python_interpreter: /usr/bin/python3
```

Next try and change the `ifname` to `vlan100`:

```yaml
- hosts: all
  tasks:
    - nmcli:
        conn_name: home-test
        autoconnect: false
        state: present
        type: vlan
        ifname: vlan100
        vlandev: eth0
        vlanid: 100
  vars:
    ansible_python_interpreter: /usr/bin/python3
```

##### EXPECTED RESULTS
Running the second playbook, I'd expect the `home-test` connection to have its `connection.interface-name` setting change to `vlan100`.

##### ACTUAL RESULTS

The existing connection's interface name isn't modified:

```paste below
{"Exists": "Connections already exist and no changes made", "changed": false, "conn_name": "home-test", "state": "present"}
```
