### ISSUE TITLE
Jira transsition issue is not working

### ISSUE THREAD

**Issue by pertoft** [ansible-collections/community.general#109]
##### Jira Transsition issue is not working

The Jira module is outdatred and does not use the correct Jira REST call. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

modules/web_infrastructure/jira.py
community.general/plugins/modules/web_infrastructure/jira.py

##### ANSIBLE VERSION

```paste below
pto:ansible pto$ ansible --version
ansible 2.9.4
  config file = /Users/pto/infrastructure/ansible/ansible.cfg
  configured module search path = ['/Users/pto/infrastructure/ansible/library']
  ansible python module location = /Users/pto/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /Users/pto/Library/Python/3.8/bin/ansible
  python version = 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) [Clang 6.0 (clang-600.0.57)]
pto:ansible pto$
```

##### CONFIGURATION

```paste below
pto:ansible pto$ ansible-config dump --only-changed
CACHE_PLUGIN(/Users/pto/infrastructure/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/pto/infrastructure/ansible/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/Users/pto/infrastructure/ansible/ansible.cfg) = 7200
DEFAULT_GATHERING(/Users/pto/infrastructure/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/pto/infrastructure/ansible/ansible.cfg) = ['/Users/pto/infrastructure/ansible/inventory.yml']
DEFAULT_MODULE_PATH(/Users/pto/infrastructure/ansible/ansible.cfg) = ['/Users/pto/infrastructure/ansible/library']
DEFAULT_ROLES_PATH(/Users/pto/infrastructure/ansible/ansible.cfg) = ['/Users/pto/infrastructure/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/pto/infrastructure/ansible/ansible.cfg) = /Users/pto/.vault
HOST_KEY_CHECKING(/Users/pto/infrastructure/ansible/ansible.cfg) = False
pto:ansible pto$
```

##### OS / ENVIRONMENT

Macos Catalina 10.15.4

##### STEPS TO REPRODUCE

```yaml
# Transition an issue by target status
    - name: Change to Production
      jira:
        uri: 'https://jira.com/'
        username: '{{ jira_username }}'
        password: '{{ jira_password }}'
        project: CMDB
        issue: "ISSUE-111"
        operation: transition
        status: "Change to Production"
        validate_certs: no
      args: 
        fields:        
          comment: "Test"
```

This is incorrect according to latest Jira documentation: https://docs.atlassian.com/software/jira/docs/api/REST/8.5.4/#api/2/issue-doTransition

##### EXPECTED RESULTS

`{
   "update":{
      "comment":[
         {
            "add":{
               "body":"Test"
            }
         }
      ]
   },
   "transition":{
      "id":"5"
   }
}`

##### ACTUAL RESULTS

This results in the REST call:
`{
        "fields": {
            "comment": "Test"
        },
        "transition": {
            "id": "241"
        }
    }`
