### ISSUE TITLE
Couldn't resolve module/action 'community.general.seport'

### ISSUE THREAD

**Issue by 0x412e4e** [ansible-collections/community.general#1092]
#### SUMMARY
I'm unable to use the module `community.general.seport`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 `seport`

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/var/lib/awx/vendor/awx_ansible_collections/ansible_collections']
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS Linux release 8.2.2004 (Core) running AWX.

##### STEPS TO REPRODUCE

Connect to the Ansible AWX/Tower server, which is running on Docker. Run the following command to install the module:
`ansible-galaxy collection install community.general`

Create a playbook which uses the module:

```yaml
- name: nagios-log configure
  hosts: DEV
  remote_user: root
  collections:
  - name: community.general
  tasks:
  
  - name: Configure syslog port exception
    community.general.seport:
      ports: 5544
      proto: tcp
      setype: syslogd_t
      state: present
      reload: yes
```

##### EXPECTED RESULTS

Running the playbook, I would expect the module to recognized and work.

##### ACTUAL RESULTS

```
ERROR! couldn't resolve module/action 'community.general.seport'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/tmp/awx_188_403lrs7j/project/nagios-log.yml': line 27, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  - name: SELinux exception for rsyslog
    ^ here
```
