### ISSUE TITLE
Add client certificate support to maven_artifact

### ISSUE THREAD

**Issue by mdaves93** [ansible-collections/community.general#1123]
##### SUMMARY

Add client certificates to the maven_artifact module.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

maven_artifact
##### ADDITIONAL INFORMATION

It is possible to require a client cert to call private maven repositoy. The current maven_artifact module does not support client certificates. The get_url module does support client_cert and client_key. In the background maven_artifact and get_url use the same fetch_url. Could the client_cert and client_key features could also be added to maven_artifact module?

```yaml
---
- name: Current Maven Artifact
  maven_artifact:
    group_id: com.company
    artifact_id: library-name
    repository_url: 'https://private.repo'
    dest: /tmp/library-name-latest.jar
- name: Suggested addition to Maven Artifact
  maven_artifact:
    group_id: com.company
    artifact_id: library-name
    repository_url: 'https://private.repo'
    dest: /tmp/library-name-latest.jar\
    client_cert: /path/to/client_cert.pem
    client_key: /path/to/client_key.pem
```
