### ISSUE TITLE
Add support for TCP healthcheck for services registered by consul module

### ISSUE THREAD

**Issue by PDmatrix** [ansible-collections/community.general#1128]
##### SUMMARY

Consul provides a TCP check type and this should be part of this module
https://www.consul.io/docs/discovery/checks

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
consul - https://docs.ansible.com/ansible/latest/collections/community/general/consul_module.html

##### ADDITIONAL INFORMATION

Current workaround is: `nc -z -v -w5 127.0.0.1 80`
Old issue - https://github.com/ansible/ansible/issues/25801
And closed PR for this - https://github.com/ansible/ansible/pull/46748

This would look like this:
```yaml
- name: Register nginx with an tcp check
  community.general.consul:
    service_name: nginx
    service_port: 80
    interval: 60s
    tcp: 172.34.12.49:80
```
