### ISSUE TITLE
odbc : [HY010] [unixODBC][Driver Manager]Function sequence error (0) (SQLFetch)

### ISSUE THREAD

**Issue by joshinryz** [ansible-collections/community.general#1137]
##### SUMMARY
Unable to connect to Microsoft SQL Server in order to perform a query. SQL trace shows the authentication succeeding , and data being returned. However, the module fails to parse the results.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
odbc

##### ANSIBLE VERSION

```
ansible 2.10.1
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
Default
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.2 (Ootpa)

##### STEPS TO REPRODUCE
```yaml
    - name: Test select from SQL
      community.general.odbc:
        dsn: "DRIVER={ODBC Driver 17 for SQL Server};Server=server01;Database=main;Trusted_Connection=Yes;"
        query: "select x=1"
```

##### EXPECTED RESULTS
Query is returned.

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dsn": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "params": null,
            "query": "select x=1"
        }
    },
    "msg": "Exception while reading rows: ('HY010', '[HY010] [unixODBC][Driver Manager]Function sequence error (0) (SQLFetch)')"
}
