### ISSUE TITLE
maven_artifact can't fetch from AWS CodeArtifact repositories

### ISSUE THREAD

**Issue by iandelahorne** [ansible-collections/community.general#1171]
##### SUMMARY
[AWS CodeArtifact](https://aws.amazon.com/codeartifact/) is a service from AWS providing managed package repositories (npmjs, pypi, maven/gradle). We'd like to use it to store our Java JAR artifacts published by Gradle, and download them onto our app servers with ansible's `maven_artifact` module.

Using the [AWS instructions](https://docs.aws.amazon.com/codeartifact/latest/ug/maven-mvn.html), authentication to a CodeArtifact repository with Maven is done by first obtaining a time-limited token in the form of a JWT (I've included an example as [a gist](https://gist.github.com/iandelahorne/1bf8d0663f0efb62a0fa6727bbda74e9)) and then using that as the password.

Despite working with Maven and Gradle, this doesn't work with the `maven_artifact` module due to something weird happening when trying to download. Looking at the URLs failing and supplying the tokens manually, I can't understand why this doesn't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /Users/ian/src/ansible-test/ansible.cfg
  configured module search path = ['/Users/ian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ian/src/ansible-test/venv/lib/python3.6/site-packages/ansible
  executable location = /Users/ian/src/ansible-test/venv/bin/ansible
  python version = 3.6.8 (default, Jan  8 2020, 12:58:45) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```
DEFAULT_STDOUT_CALLBACK(/Users/ian/src/ansible-test/ansible.cfg) = yaml
```

##### OS / ENVIRONMENT
This happens both on OSX and Linux (Ubuntu 18.04), ansible 2.9.4 and 2.10.1 with python 3.6.8. The example below is from 2.10.1 with `community.general` installed from 
```
$ ansible-galaxy collection install community.general
```

##### STEPS TO REPRODUCE

To set this up in CodeArtifact, we need to do the following:
1. Create a CodeArtifact domain
1. Create a CodeArtifact repository, maven-central-store, as a maven-central upstream
1. Connect the upstream to maven-central
1. Create a maventest repository
1. Connect the maventest repository to the , maven-central-store 

I've done this all in us-west-2:
```
export AWS_DEFAULT_REGION=us-west-2 
# Create the domain
$ aws codeartifact create-domain --domain maventest

# Create the upstream repository
$ aws codeartifact create-repository --domain maventest --repository maven-central-store

# Connect it the repository to public maven-central
$ aws codeartifact associate-external-connection --domain maventest --repository maven-central-store --external-connection public:maven-central

# Create the maventest repository
aws codeartifact create-repository --domain maventest --repository maventest --upstreams repositoryName=maven-central-store
```

The instructions on the repository instruct us to use `aws` as the username, and the output from `aws codeartifact get-authorization-token` as the password to use it as a maven 

```yaml
---
- name: Test maven_artifact with codeartifact
  hosts: localhost
  vars:
    codeartifact:
      domain: maventest
      region: us-west-2
      repository: maventest
    artifact:
      id: commons-io
      group: commons-io
      version: 2.8.0
  tasks:
    - name: Fetch codeartifact token
      command: "aws codeartifact get-authorization-token --region {{ codeartifact.region }} --domain {{ codeartifact.domain }} --query authorizationToken --output text"
      register: codeartifact_token
      no_log: true
      
    - name: Fetch codeartifact endpoint
      command: "aws codeartifact get-repository-endpoint --region {{ codeartifact.region }} --domain {{ codeartifact.domain }} --repository {{ codeartifact.repository }} --format maven --query repositoryEndpoint --output text"
      register: codeartifact_endpoint
    
    - name: Download commons.io JAR
      community.general.maven_artifact:
        artifact_id: "{{ artifact.id }}"
        dest: /tmp/jar.jar
        group_id: "{{ artifact.group }}"
        repository_url: "{{ codeartifact_endpoint.stdout | trim }}"
        version: "{{ artifact.version }}"
        username: aws
        password: "{{ codeartifact_token.stdout | trim }}"
```

##### EXPECTED RESULTS

Expected result is that `commons-io:commons-io:2.8.0` is downloaded to `/tmp/codeartifact.jar`

I've also checked the above setup using Maven, by 
1. nuking `~/.m2/` directory
1. Creating a `~/.m2/settings.xml` from the configuration in the AWS console
1. Running `mvn` to fetch the JAR:

```
$ mvn dependency:get -Ddest=/tmp -DgroupId=commons-io -DartifactId=commons-io -Dversion=2.8.0 -Dtransitive=false
```
and I can see that `/tmp/commons-io-2.8.0.jar` is downloaded:

```
$ unzip -p /tmp/commons-io-2.8.0.jar META-INF/MANIFEST.MF | grep Bundle
Bundle-Description: The Apache Commons IO library contains utility cla
Bundle-License: https://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-SymbolicName: org.apache.commons.commons-io
Bundle-ManifestVersion: 2
Bundle-DocURL: https://commons.apache.org/proper/commons-io/
Bundle-Vendor: The Apache Software Foundation
Bundle-Name: Apache Commons IO
Bundle-Version: 2.8.0
Created-By: Apache Maven Bundle Plugin
```

##### ACTUAL RESULTS

Result from `ansible-playbook -vvvv playbooks/maventest.yml` (the above playbook)

https://gist.github.com/iandelahorne/9f642e10f2cc4c87c14009ab5972f101

I found other github issues referencing the `AbstractDigestAuthHandler does not support the following scheme: ''Bearer''` error, where they set the headers explicitly. Changing the second step to:
```
    - name: Download commons.io JAR
      community.general.maven_artifact:
        artifact_id: "{{ artifact.id }}"
        dest: /tmp/codeartifact.jar
        group_id: "{{ artifact.group }}"
        repository_url: "{{ codeartifact_endpoint.stdout | trim }}"
        version: "{{ artifact.version }}"
        headers:
          Authorization: "Bearer {{ codeartifact_token.stdout | trim }}"
```

This results in the following output:

https://gist.github.com/iandelahorne/b94e8f7b863dff8220b8ae08f439e9ae

Running Curl with the bearer token in the output and the URL in the error totally works:
```
$ curl -O -L -H "Authorization: Bearer REDACTED " https://maventest-REDACTED.d.codeartifact.us-west-2.amazonaws.com/maven/maventest/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  278k  100  278k    0     0   337k      0 --:--:-- --:--:-- --:--:--  337k
$ unzip -p commons-io-2.8.0.jar META-INF/MANIFEST.MF | grep Bundle
Bundle-Description: The Apache Commons IO library contains utility cla
Bundle-License: https://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-SymbolicName: org.apache.commons.commons-io
Bundle-ManifestVersion: 2
Bundle-DocURL: https://commons.apache.org/proper/commons-io/
Bundle-Vendor: The Apache Software Foundation
Bundle-Name: Apache Commons IO
Bundle-Version: 2.8.0
Created-By: Apache Maven Bundle Plugin
```

**Comment by iandelahorne** [comment]
This is fairly meaty and depends on AWS. I've redacted account numbers and tokens here, but I can provide these over email if needed - email is ian at patreon dot com

**Comment by ansibullbot** [comment]
cc @tumbl3w33d @turb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
It might be helpful to know to the maintainers how `"{{ codeartifact_token.stdout | trim }}"` looks like (not the exact value, but the general form).

**Comment by iandelahorne** [comment]
@felixfontein Absolutely. It's a fairly big JWT (1519 characters base64 encoded). I generated one and then redacted the sections past the first section (up to the first `.`):

```
eyJ2ZXIiOjEsImlzdSI6MTYwMzY0NDQ0MCwiZW5jIjoiQTEyOEdDTSIsInRhZyI6ImJLMm4xaW9xdldkd043cEZPb1BZekEiLCJleHAiOjE2MDM2ODc2NDAsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiNzFURE51NU9MeXowLXo5aCJ9.XXXXXXXXXXXXXXXXXXXXXX.YYYYYYYYYYYYYYYY.ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ.QQQQQQQQQQQQQQQQQQQQQQ
```

**Comment by iandelahorne** [comment]
I also tried using `force_basic_auth: true` and it failed the same way as specifying `headers`:
```
  msg: 'Failed to download artifact commons-io:commons-io:2.8.0 because of HTTP Error 400: Bad Requestfor URL https://maventest-REDACTED.d.codeartifact.us-west-2.amazonaws.com/maven/maventest/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar'
```

```yaml
    - name: Download commons.io JAR
      community.general.maven_artifact:
        artifact_id: "{{ artifact.id }}"
        dest: /tmp/codeartifact.jar
        group_id: "{{ artifact.group }}"
        repository_url: "{{ codeartifact_endpoint.stdout | trim }}"
        version: "{{ artifact.version }}"
        force_basic_auth: true
        username: aws
        password: "{{ codeartifact_token.stdout | trim }}"

```
