### ISSUE TITLE
Token name don't changes via consul_acl

### ISSUE THREAD

**Issue by 4n70w4** [ansible-collections/community.general#1177]
##### SUMMARY
Token name don't changes via consul_acl

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
consul_acl

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /home/albus/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.8/dist-packages/git_acp/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/ansible/ansible.cfg) = ['/home/albus/ansible/hosts.ini']
DEFAULT_LOG_PATH(/home/ansible/ansible.cfg) = /home/albus/ansible/ansible.log
DEFAULT_MODULE_PATH(/home/ansible/ansible.cfg) = ['/usr/local/lib/python3.8/dist-packages/git_acp/modules']
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible/ansible.cfg) = /home/albus/.ansible_pass.txt
DEPRECATION_WARNINGS(/home/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ansible/ansible.cfg) = /usr/bin/python3
```

##### STEPS TO REPRODUCE
First run:

```yaml
  - name: Create an acl with specific token with both key and service rules
    consul_acl:
      mgmt_token: "{{ consul_mgmt_token }}"
      name: Old token
      token: "{{ consul_token }}"
```

Created token with name «Old token»

Second run:

```yaml
  - name: Create an acl with specific token with both key and service rules
    consul_acl:
      mgmt_token: "{{ consul_mgmt_token }}"
      name: New token
      token: "{{ consul_token }}"
```

But token name don't changed to «New token»

##### EXPECTED RESULTS

Change token name.

##### ACTUAL RESULTS
Nothing changed by task

```paste below
TASK [registrator : Create an acl with specific token with both key and service rules] ******************************************************************************************************************
ok: []
```
