### ISSUE TITLE
docker_container exposed_ports is incorrect

### ISSUE THREAD

**Issue by danielo515** [ansible-collections/community.general#1192]
##### SUMMARY
The property exposed_ports is incorrect. According to the examples an my experience the one that should be used is `ports`

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/collections/community/general/docker_container_module.html#parameter-exposed_ports

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /Users/danielo/mega/ansible/ansible.cfg
  configured module search path = ['/Users/danielo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.11/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

I wanted to open a PR to fix it but:

- Don't know where the git repository of the linked docs is
- I don't know which one is the correct one

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by danielo515** [comment]
I linked the exact documentation page. I don't know which file corresponds to that, maybe this: 
!component community.general.docker_container

Can't you extract it from the link?

**Comment by danielo515** [comment]
!component +community/general/docker_container

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`community/general/docker_container`](https://github.com/ansible-collections/community.general/blob/master/community/general/docker_container)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The module is called `docker_container`. You have to specify that under `COMPONENT NAME`.

!component =plugins/modules/cloud/docker/docker_container.py

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cloud/docker/docker_container.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @danihodovic @dariko @dusdanig @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Also I have no idea what you mean by "incorrect". The `exposed_ports` option does exist, and does similar things as the `--expose` option of `docker run`.

**Comment by felixfontein** [comment]
needs_info

**Comment by danielo515** [comment]
Sorry @felixfontein I meant `published_ports`. As you can see, there is single example using `published_ports`. However, using just ports (as on the examples) works as expected.

This is the only example of how to publish ports:

```yml
- name: Restart a container
  community.general.docker_container:
    name: myapplication
    image: someuser/appimage
    state: started
    restart: yes
    links:
     - "myredis:aliasedredis"
    devices:
     - "/dev/sda:/dev/xvda:rwm"
    ports:
     # Publish container port 9000 as host port 8080
     - "8080:9000"
     # Publish container UDP port 9001 as host port 8081 on interface 127.0.0.1
     - "127.0.0.1:8081:9001/udp"
     # Publish container port 9002 as a random host port
     - "9002"
     # Publish container port 9003 as a free host port in range 8000-8100
     # (the host port will be selected by the Docker daemon)
     - "8000-8100:9003"
     # Publish container ports 9010-9020 to host ports 7000-7010
     - "7000-7010:9010-9020"
    env:
        SECRET_KEY: "ssssh"
        # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
        BOOLEAN_KEY: "yes"
```

And it works.
I guess people check examples more than docs.
