### ISSUE TITLE
pacman module lost backwards compatibility

### ISSUE THREAD

**Issue by kinglouie** [ansible-collections/community.general#1195]
##### SUMMARY
I created an arch linux installation playbook around a year ago to setup my dev machine. Today I tried to run than playbook a few times in succession and ran into the issue that the pacman module fails on packages that are already installed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pacman

##### ANSIBLE VERSION
```paste below
2.10.2
```

##### CONFIGURATION
default config 

##### OS / ENVIRONMENT
latest arch linux as of 2020-10-29, with linux-zen kernel
##### STEPS TO REPRODUCE
Run the following pacman command twice
```yaml
- name: install vmware drivers
  pacman:
    name: xf86-input-vmmouse xf86-video-vmware mesa
    state: present
```

##### EXPECTED RESULTS
Pacman module should skip the task if the packages is already installed.

##### ACTUAL RESULTS
Pacman module fails [here](https://github.com/ansible-collections/community.general/blob/25b38d907e4452652ecf08e10665713182f763e9/plugins/modules/packaging/os/pacman.py#L168) with the following output
```paste below
get_name: fail to retrieve package name from pacman output
```

I looked a bit into the source [here](https://github.com/ansible-collections/community.general/blob/25b38d907e4452652ecf08e10665713182f763e9/plugins/modules/packaging/os/pacman.py#L168) and printed out `pacman_output` which contains `xf86-input-vmmouse 13.1.0-5\nxf86-video-vmware 13.3.0-2\nmesa 20.2.1-1\n`

I think the bottom of the issue is that pacman runs the `get_name` function on the three packages at once instead of one package at a time.
When I change the syntax of the pacman command to use a list the issue is gone.
```yaml
- name: install vmware drivers
  pacman:
    name: 
      - xf86-input-vmmouse
      - xf86-video-vmware
      - mesa
    state: present
```
^ this works

Since the syntax which causes the issue used to work fine (and works fine when the package was not present) I think this should be fixed in the module so users are not forced to update their playbooks.
