### ISSUE TITLE
Module `postgresql_query` cannot cope with identifiers

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.general#121]
_Copied from https://github.com/ansible/ansible/issues/58644_
_Initially reported by @cans_

##### SUMMARY

The `postgresql_query` module cannot be used with any query that requires an identifier as an argument. Indeed as per the documentation, the underlying python DB API implementation (psycopg2) require a string containing a indentifier to be "annotated" as a psycopg2.sql.Identifier instance. If not the string is systematically surrounded with quotes. It would be nice to be able to do such thing.

```yaml
- hosts: db
  tasks:
    - name: "Configure foreign data wrapper"
      postgresql_query:
          positional_args:
            - "servername"
            - "hostname.domain.tld"
          query: ALTER SERVER %s OPTIONS (SET host %s)
          # and the required connection parameters 
```
This query is rewritten `ALTER SERVER 'server-name' OPTIONS (SET host 'hostname.domain.tld')` which is invalid and will fail with the error: 
```json
{"msg": "Cannot execute SQL 'ALTER SERVER %s OPTIONS (SET host %s)\n' ['servername', 'hostname.domain.tld']: syntax error at or near \"'servername'\"\nLINE 1: ALTER SERVER 'servername' OPTIONS (SET host 'hostname.doma...\n                     ^\n"}
```

In the end you are better off using the command module to call psql. It is a bit of a pity.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

postgresql_query

This issue may apply to other database modules (though with different manifestations and solutions).

##### ADDITIONAL INFORMATION

```yaml
- hosts: db
  tasks:
    - name: "Configure foreign data wrapper"
      postgresql_query:
          positional_args:
            - "{{ 'servername' | pgidentifier }}"  # Or a variable instead of a literal
            - "hostname.domain.tld"
          query: ALTER SERVER %s OPTIONS (SET host %s)
          # and the required connection parameters 
```
This query would be rewritten `ALTER SERVER "server-name" OPTIONS (SET host 'hostname.domain.tld')` as expected.

I quickly tried to put together a filter plugin that does the above. But the value keeps being turned to a string `"'Identifier('servername')'", which is no better (_cf._ GIST below).

https://gist.github.com/cans/165ecb5042e8c45b6cd5db18227f1c1f
