### ISSUE TITLE
Consumed subscriptions, still listed as available are consumed again

### ISSUE THREAD

**Issue by tomaciazek** [ansible-collections/community.general#1228]
##### SUMMARY

For some subscriptions (instance-based, I believe) `subscription-manager` will still report them as available for `subscription-manager list --available`, but with 'suggested' entitlements to consume equal to 0. This breaks the behavior of this module when either the `pool` option is provided or the `pool_ids` option but without the quantities specified.

NB: To make the module work correctly with the `pool_ids` option, the quantity **must be a text value**, otherwise module will re-subscribe (fortunately not consuming more entitlements) and report `changed: true`. That, I believe, is another bug.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redhat_subscription

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tomasz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### CONFIGURATION

`ansible-config dump --only-changed` returns no output

##### OS / ENVIRONMENT

Tested on RHEL 8.2 and RHEL 7.9

##### STEPS TO REPRODUCE

```yaml
- name: RHEL registration
  hosts: all
  become: true

  tasks:
  - redhat_subscription:
      state: present
      activationkey: "mykey"
      org_id: "myorg"
      pool_ids:
        - 0123456789abcdef0123456789abcdef
```

AND

```yaml
- name: RHEL registration
  hosts: all
  become: true

  tasks:
  - redhat_subscription:
      state: present
      activationkey: "mykey"
      org_id: "myorg"
      pool:  '^Red Hat Enterprise Linux'
```

##### EXPECTED RESULTS

Invoking twice, should show change only the first time. The second time, no changes should be reported and
no new entitlements consumed

##### ACTUAL RESULTS

Invoking the module the second time shows changes and consumes additional entitlements.
