### ISSUE TITLE
DNSMADEEASY TXT record fails on Monitor call

### ISSUE THREAD

**Issue by edperry** [ansible-collections/community.general#1237]
##### SUMMARY
DNS Made easy returns Bad request 
"msg": "https://api.dnsmadeeasy.com/V2.0/monitor/131517074 returned 400, with body: HTTP Error 400: Bad Request"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dnsmadeeasy

##### ANSIBLE VERSION

```paste below
ansible 2.9.10.post0
  config file = /home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/ansible.cfg
  configured module search path = [u'/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/modules', u'/home/eperry/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/eperry/OneDrive/ubuntu-eperry-home/bin/ansible-2.7/lib/ansible
  executable location = /home/eperry/OneDrive/ubuntu-eperry-home/bin/ansible-2.7/bin/ansible
  python version = 2.7.18 (default, Aug  4 2020, 11:16:42) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/ansible.cfg) = fact_cache
DEFAULT_HOST_LIST(/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/ansible.cfg) = [u'/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/inventory']
DEFAULT_MODULE_PATH(/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/ansible.cfg) = [u'/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/modules', u'/home/eperry/.ansible/plugins/module>
DEPRECATION_WARNINGS(/home/eperry/OneDrive/ubuntu-eperry-home/dnsme-dns-automation/ansible.cfg) = False
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False

```

##### OS / ENVIRONMENT

Linux Ubuntu

##### STEPS TO REPRODUCE

```yaml
- name: "Update {{ inventory_hostname }}"
  dnsmadeeasy:
    account_key:    "{{ DNSMADEEASY_APIKEY }}"
    account_secret: "{{ DNSMADEEASY_SECRET }}"
    domain:         "{{ inventory_hostname }}"
    record_type:    "{{ item.type  | upper() }}"
    record_name:    "{{ item.name  | default('', true) | lower() }}"
    record_value:   "{{ item.value | default('', true) | lower() }}"
    record_ttl:     "{{ item.ttl   | default(60, true) }}"
    state:          "{{ item.state | default('present',true) }}"
  with_items: "{{ entries | json_query(query) }}"
  vars:
    query: "[? type=='TXT'|| type=='txt']"

```

##### EXPECTED RESULTS

The DNS TXT record gets created but seems the monitor function fails.

##### ACTUAL RESULTS

```paste below
failed: [corphbc.com] (item={u'type': u'TXT', u'name': u'ed3', u'value': u'THISISme', u'ttl': 600}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "account_key": "XXXXXXXXXXXXXXXXXXXXXXXXX", 
            "account_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "autoFailover": false, 
            "contactList": null, 
            "domain": "XXXXXXXXX.com", 
            "failover": false, 
            "httpFile": null, 
            "httpFqdn": null, 
            "httpQueryString": null, 
            "ip1": null, 
            "ip2": null, 
            "ip3": null, 
            "ip4": null, 
            "ip5": null, 
            "maxEmails": 1, 
            "monitor": false, 
            "port": 80, 
            "protocol": "HTTP", 
            "record_name": "ed3", 
            "record_ttl": 600, 
            "record_type": "TXT", 
            "record_value": "thisisme", 
            "sandbox": false, 
            "sensitivity": "Medium", 
            "state": "present", 
            "systemDescription": "", 
            "validate_certs": true
        }
    }, 
    "item": {
        "name": "ed3", 
        "ttl": 600, 
        "type": "TXT", 
        "value": "THISISme"
    }, 
    "msg": "https://api.dnsmadeeasy.com/V2.0/monitor/131517074 returned 400, with body: HTTP Error 400: Bad Request"
}

```
