### ISSUE TITLE
hashi_vault lookup plugin should allow environment variable vor Username / Password auth

### ISSUE THREAD

**Issue by nwerker** [ansible-collections/community.general#1259]
##### SUMMARY

Other authentication method parameters like token for instance can be passed via certain environment variables. There should be specific environment variables to pass "username", "password" and "mount_point" parameters to allow for cleaner and more flexible calls when using the lookup plugin with instance or userpass authentication.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hashi_vault

##### ADDITIONAL INFORMATION

This would allow for global initializing of the parameters and solve problems of reuising them on each usage of the lookup plugin.

This would be an example of the current state:
```yaml
---
- hosts: webservers
  gather_facts: yes
  environment:
    VAULT_AUTH_METHOD: "ldap"
  vars:
      first_var: "{{lookup('hashi_vault', 'secret=kv/example/example:first_var mount_point=ldap username=user_xyz password=******************')}}"
      second_var: "{{lookup('hashi_vault', 'secret=kv/example/example:second_var mount_point=ldap username=user_xyz password=******************')}}"
      another_var: "{{lookup('hashi_vault', 'secret=kv/example/example:another_var mount_point=ldap username=user_xyz password=******************')}}"
      yet_another_var: "{{lookup('hashi_vault', 'secret=kv/example/example:yet_another_var mount_point=ldap username=user_xyz password=******************)}}"
```

This would be an example of how the usage after implementation:

```yaml
---
- hosts: webservers
  gather_facts: yes
  environment:
    VAULT_USERNAME: "user_xyz"
    VAULT_PASSWORD: "*******************"
    VAULT_AUTH_METHOD: "ldap"
    VAULT_MOUNT_POINT: "ldap"
  vars:
      first_var: "{{lookup('hashi_vault', 'secret=kv/example/example:first_var ')}}"
      second_var: "{{lookup('hashi_vault', 'secret=kv/example/example:second_var')}}"
      another_var: "{{lookup('hashi_vault', 'secret=kv/example/example:another_var')}}"
      yet_another_var: "{{lookup('hashi_vault', 'secret=kv/example/example:yet_another_var)}}"
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/lookup/hashi_vault.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/lookup/hashi_vault.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @briantist
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by briantist** [comment]
Hi @nwerker ! Most of the original env vars in this lookup were meant to re-use or be compatible with the env vars that the vault CLI uses:
https://www.vaultproject.io/docs/commands#environment-variables

We (*ahem* I) have added additional values with the `VAULT_` prefix but I'm starting to think that's a mistake as I don't want to introduce more ambiguities between what's an Ansible value vs. a value recognized by Vault.

So I like this idea but I think I'd prefer to prefix the new env vars with `ANSIBLE_VAULT_` for anything that's not meant to be re-using an existing recognized Vault env var; for things are supposed to be re-using them, we also have to take care with precedence when INI value exist ( see #1261 and #373 ).

The other thing I want to point out is that there are current workarounds for this, if you set Ansible vars with the values you want, which is also made a little easier by the fact that since Ansible 2.10 / CG 0.2.0, you don't have to put all the parameters in a single string, you can pass them actual params.

I'm adding a block here to distinguish between the vars needed before the vars using the lookup.

```yaml
---
- hosts: webservers
  gather_facts: yes
  environment:
    VAULT_AUTH_METHOD: "ldap"
  vars:
    mount_point: "ldap"
    username: "username"
    password: "hunter2"
  tasks:
    - block:
      vars:
        first_var: "{{ lookup('hashi_vault', 'kv/example/example:first_var', mount_point=mount_point, username=username, password=password) }}"
        second_var: "{{ lookup('hashi_vault', 'kv/example/example:second_var', mount_point=mount_point, username=username, password=password) }}"
        another_var: "{{ lookup('hashi_vault', 'kv/example/example:another_var', mount_point=mount_point, username=username, password=password) }}"        
        yet_another_var: "{{ lookup('hashi_vault', 'kv/example/example:yet_another_var', mount_point=mount_point, username=username, password=password) }}"
```

Also while not exactly your point, in your examples, all using the same path but different keys, you can do a single lookup to get the k/v pairs as dict, and get the individual fields on the Ansible side:

```yaml
---
- hosts: webservers
  gather_facts: yes
  environment:
    VAULT_AUTH_METHOD: "ldap"
  vars:
    mount_point: "ldap"
    username: "username"
    password: "hunter2"
  tasks:
    - block:
      vars:
        vals: "{{ lookup('hashi_vault', 'kv/example/example', mount_point=mount_point, username=username, password=password) }}"
        - debug:
             msg: "{{ item.key }}: {{ item.value }}"
           loop: "{{ vals | dict2items }}"
```
