### ISSUE TITLE
Add a 'creates' item to the maven_artifact module

### ISSUE THREAD

**Issue by esend7881** [ansible-collections/community.general#1263]
##### SUMMARY
Please add a `creates` element to the `maven_artifact` module. Similar to how the `shell` module has a creates element which prevents future runs of the `shell` task, I think a `creates` element should be added to `make`.

I'd rather not re-run `maven_artifact`. 

https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/language/maven_artifact.py

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
maven_artifact
https://docs.ansible.com/ansible/latest/collections/community/general/maven_artifact_module.html

##### ADDITIONAL INFORMATION

```yaml
- name: Download YANG-MODELS
  community.general.maven_artifact:
    group_id: "{{group_id}}"
    artifact_id: "{{yang_models_artifact_id}}"
    version: "{{yang_models_version}}"
    repository_url: "{{nexus_maven}}"
    extension: tar.gz
    dest: /tmp/
    creates: /tmp/yang-models.tar.gz
```

Similar to #1262
