### ISSUE TITLE
proxmox lxc - allow update of existing containers

### ISSUE THREAD

**Issue by n0emis** [ansible-collections/community.general#1278]
##### SUMMARY

Allow to update existing containers.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.general.proxmox

##### ADDITIONAL INFORMATION

When managing lxc-containers on proxmox from ansible, it is currently not possible to update these containers, e.g. change the ip-address etc. This would be a really good addition, since it is currently needed to update this at multiple places: the playbook and proxmox itself.

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cloud/misc/rhevm.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/misc/rhevm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Aversiste @TimothyVandenbrande @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Aversiste** [comment]
This is actually harder than it looks as a careless update will destroy and recreate the network devices instead of updating them.

I am working on this problem for `proxmox_kvm`.

**Comment by ansibullbot** [comment]
Files identified in the description:
* `plugins/modules/cloud/misc/proxmox`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* `plugins/modules/proxmox`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Skaronator** [comment]
This seems to be somewhat fixed by #7540. You can now provide a `update: true` flag, but sadly, it's not that simple. You cannot configure `ostemplate` in the same task, which means you have to split it up into 2 tasks, with the only difference being the `ostemplate` and `update` attribute.

I tried reducing duplicated code by using YAML Anchor like so:

```yaml
- name: Create LXC Container (if missing) 
  community.general.proxmox: &container
    # proxmox api
    api_host: "{{ ansible_host }}"
    api_user: root@pam
    api_password: "{{ (admins | combine(users | default({}), recursive=true))['root']['password'] }}"
    node: "{{ ansible_hostname }}"
    # lxc config
    hostname: "{{ item.hostname }}"
    vmid: "{{ item.vmid }}"
    memory: "{{ item.memory }}"
    cpus: "{{ item.cpus }}"
    netif: "{{ item.netif | to_json }}"
    # static stuff
    swap: 0
    password: "{{ lxc_password }}"
    ostemplate: "{{ lxc_template_storage }}:{{ lxc_template_path }}/{{ item.template }}"
    pubkey: "{{ (admins | combine(users | default({}), recursive=true))['root']['sshpubkey'] }}"
  loop: "{{ lxc }}"

- name: Update LXC container
  community.general.proxmox:
    <<: *container
    state: "{{ item.state | default('started') }}"
    ostemplate: null
    update: true
  loop: "{{ lxc }}"
```

But this doesn't work since `ostemplate` is still present, and I can't get rid of it by setting `ostemplate: null`  or leaving it empty (`ostemplate: `).

It would be cool if the module ignored `ostemplate` altogether, and we can just use a single task with the limitation that you cannot update ostemplate.
