### ISSUE TITLE
snap: module should interact with the API, not run a command

### ISSUE THREAD

**Issue by devster31** [ansible-collections/community.general#1323]
##### SUMMARY

Snap exposes a REST API via a local socket (and HTTPS TCP sockets are under consideration).
Instead of running commands, the module should probably interact with the API directly, which would provide more consistent outcomes and a broader range of actions (such as asyncronous execution and configuration management of snaps as described in #666).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`plugins/modules/snap.py`

##### ADDITIONAL INFORMATION

[Official API reference](https://snapcraft.io/docs/snapd-api)

```yaml
- name: stop snap daemon
    snap:
      name: lxd
      daemon:
        active: false
        enabled: false
```
