### ISSUE TITLE
Double quoting value to set in xfconf.py

### ISSUE THREAD

**Issue by danie1k** [ansible-collections/community.general#1328]
##### SUMMARY
Shell command's arg values are double quoted in the following line:

https://github.com/ansible-collections/community.general/blob/d95910963b87e9efba2aed1b527a2f8e4d6ee7ae/plugins/modules/system/xfconf.py#L199

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```
community.general.xfconf
```

Bug has been been added recently, in pull request #693. Affects versions > 0.2.1.

##### ANSIBLE VERSION
*Not relevant.*

##### CONFIGURATION
*Not relevant.*

##### OS / ENVIRONMENT
*Not relevant.*

##### STEPS TO REPRODUCE
In my case it was
```yaml
- community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/Mail
    value: exo-open --launch MailReader
    value_type: string
    state: present
```

But any other `value` containing spaces will give the same effect, because the Python `shlex_quote` function will quote the value:
```
>>> shlex_quote('exo-open --launch MailReader')
"'exo-open --launch MailReader'"
```

So in th end, the Ansible module will try to run the following bash command:
```bash
/usr/bin/xfconf-query --channel xfce4-keyboard-shortcuts --property /commands/custom/Mail \
  --create --type 'string' --set ''exo-open --launch MailReader''
```
instead
```bash
/usr/bin/xfconf-query --channel xfce4-keyboard-shortcuts --property /commands/custom/Mail \
  --create --type string --set 'exo-open --launch MailReader'
```

##### EXPECTED RESULTS
No double quoting, any value should be accepted and properly set by xfconf.

#### ACTUAL RESULTS
```
fatal: [x.x.x.x]: FAILED! => {"changed": false, "msg": "Failed with exception: xfconf-query failed with error (rc=1): Option parsing failed: Unknown option --launch.\n"}
```
