### ISSUE TITLE
osx_defaults integer type check is broken 

### ISSUE THREAD

**Issue by pshirshov** [ansible-collections/community.general#134]
##### SUMMARY

It's not possible to set negative value for using osx_defaults task.

```
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: -1
    state: present
```

It happens because of bad code in https://fossies.org/linux/ansible/lib/ansible/modules/system/osx_defaults.py:

```
       elif data_type in ["int", "integer"]:
          if not str(value).isdigit():
               raise OSXDefaultsException("Invalid integer value: {0}".format(repr(value)))
            return int(value)
```

related: https://github.com/ansible/ansible/issues/68772

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
osx_default

##### ANSIBLE VERSION
2.10
