### ISSUE TITLE
parted: add filesystem type parameter

### ISSUE THREAD

**Issue by rosowiecki** [ansible-collections/community.general#135]
##### SUMMARY
GNU parted allows specifying optional filesystem type, which has effect on some partition labels:
**mkpart** `part-type [fs-type] start end`
Ansible parted module should allow to specify it to override parted defaults

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
parted

##### ADDITIONAL INFORMATION

```yaml
  parted:
    device: /dev/sdb
    number: 1
    part_end: 100%
    state: present
    filesystem: fat
```
