### ISSUE TITLE
pamd module removes comment when inserting a rule before another rule

### ISSUE THREAD

**Issue by JuddTracy-DAS** [ansible-collections/community.general#1394]
##### SUMMARY
When trying to add a new rule before an existing rule the comment that is on the line before the existing rule is removed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION
```paste below
 ansible --version
/home/ansible/.venv/ansible/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
ansible 2.9.11
  config file = /home/ansible/Orlando/ansible.cfg
  configured module search path = [u'/home/ansible/REDACTED/library']
  ansible python module location = /home/ansible/.venv/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/ansible/.venv/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### STEPS TO REPRODUCE
Running the following playbook on a Proxmox 6.2 (debian buster) system.

```yaml
  tasks:
    - name: 'Add PAM rule to stop authentication attempts'
      pamd:
        name: 'common-auth'
        type: 'auth'
        control: '[success=1 default=ignore]'
        module_path: 'pam_unix.so'
        new_type: 'auth'
        new_control: 'required'
        new_module_path: 'pam_tally2.so'
        module_arguments:
          - 'onerr=fail'
          - 'deny={{ NIST_AC_7_Unsuccessful_Attempts }}'
          - 'unlock_time={{ NIST_AC_7_Unlock_Time }}'
          - 'audit'
        state: 'before'
      vars:
        NIST_AC_7_Unsuccessful_Attempts: 3
        NIST_AC_7_Unlock_Time: 90
        NIST_AC_7_Root_Unlock_Time: 900

```

##### EXPECTED RESULTS
I expect the the file /etc/pam.d/common-auth to have the following contents:
```
#
# Updated by Ansible - 2020-11-25T21:32:34.718626
# /etc/pam.d/common-auth - authentication settings common to all services
#
# This file is included from other service-specific PAM config files,
# and should contain a list of the authentication modules that define
# the central authentication scheme for use on the system
# (e.g., /etc/shadow, LDAP, Kerberos, etc.).  The default is to use the
# traditional Unix authentication mechanisms.
#
# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
# To take advantage of this, it is recommended that you configure any
# local modules either before or after the default block, and use
# pam-auth-update to manage selection of other modules.  See
# pam-auth-update(8) for details.

# here are the per-package modules (the "Primary" block)
auth       required pam_tally2.so onerr=fail deny=3 unlock_time=90 audit
auth       [success=1 default=ignore] pam_unix.so nullok_secure
```
##### ACTUAL RESULTS
But instead the comment that was before the rule where the new rule is being added is deleted:
```
#
# Updated by Ansible - 2020-11-25T21:32:34.718626
# /etc/pam.d/common-auth - authentication settings common to all services
#
# This file is included from other service-specific PAM config files,
# and should contain a list of the authentication modules that define
# the central authentication scheme for use on the system
# (e.g., /etc/shadow, LDAP, Kerberos, etc.).  The default is to use the
# traditional Unix authentication mechanisms.
#
# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
# To take advantage of this, it is recommended that you configure any
# local modules either before or after the default block, and use
# pam-auth-update to manage selection of other modules.  See
# pam-auth-update(8) for details.

auth       required pam_tally2.so onerr=fail deny=3 unlock_time=90 audit
auth       [success=1 default=ignore] pam_unix.so nullok_secure
```
