### ISSUE TITLE
proxmox_kvm module does not return сommon and specific return values

### ISSUE THREAD

**Issue by jenoOvchi** [ansible-collections/community.general#1410]
##### SUMMARY
proxmox_kvm module does not return сommon and specific return values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm module

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.10.3
```

##### CONFIGURATION
```paste below
ansible-config dump --only-changed

```

##### OS / ENVIRONMENT
OSX Catalina 10.15.5 (19F101)

##### STEPS TO REPRODUCE
```yaml
  tasks:
    - name: Clone VM
      proxmox_kvm:
        node: "{{ node }}"
        name: "{{ name }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        clone: "{{ clone_vm }}"
        timeout: "300"
        #newid: "{{ vmid }}"
      register: exec_result

    - name: print all returned values
      debug:
        msg: "{{ exec_result }}"
```

##### EXPECTED RESULTS
```paste below
ok: [localhost] => {
    "msg": {
        "backup_file": ...
        "changed": ...
        "diff": ...
        "failed": ...
        "invocation": ...
        "msg": ...
        "rc": ...
        "results": ...
        "skipped": ...
        "stderr": ...
        "stderr_lines": ...
        "stdout": ...
        "stdout_lines": ...
        "devices": ...
        "mac": ...
        "status": ...
        "vmid": ...
    }
}
```

##### ACTUAL RESULTS
```paste below
ok: [localhost] => {
    "msg": {
        "changed": true,
        "deprecations": [
            {
                "collection_name": "community.general",
                "msg": "The proxmox_default_behavior option will change its default value from \"compatibility\" to \"no_defaults\" in community.general 4.0.0. To remove this warning, please specify an explicit value for it now",
                "version": "4.0.0"
            }
        ],
        "failed": false,
        "msg": "VM operator-vm with newid 136 cloned from vm with vmid 135"
    }
}
```

For me is the most critical that it do not return "vmid".
