### ISSUE TITLE
rhn_register: add 'force' option to run even if system already registered

### ISSUE THREAD

**Issue by das-intensity** [ansible-collections/community.general#1454]
##### SUMMARY

Add a 'force' option to rhn_register module, to allow re-registering a system.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

rhn_register

##### ADDITIONAL INFORMATION

rhnks_reg (the command that rhn_register wraps) has a --force option to allow a system to re-register even if it appears to already be registered. While the rhn_register module already uses this when register is called, the code cannot reach that point as it is skipped if the system is already registered.

There are two obvious use-cases for this:
- The host was previously registered, but the registration may have been removed on the server-side
- The host was previously registered with server A, but now should be registered with server B

```yaml

- name: Force-register as user with password to ensure registration is current on server                                             
  community.general.rhn_register:
    state: present
    username: joe_user
    password: somepass
    server_url: https://xmlrpc.my.satellite/XMLRPC
    force: yes

```
