### ISSUE TITLE
xfconf should deprecate facts and not return variant types

### ISSUE THREAD

**Issue by lifeisafractal** [ansible-collections/community.general#1475]
##### SUMMARY

As discussed in #1418 and #1419 xfconf could use some changes to be up to best practices. 

1. Remove (or begin deprecation) of setting facts. From discussion in the links above, modules should not be setting facts, but rather communicating through return values.
1. Remove (or begin deprecation) or returning a variant type. Currently the return type for the value may be either a scalar or a list depending on the type in xfconf. Return values should have one and only one possible type.
1. Implement a new return scheme that has 

I wanted to open this issue first to discuss the design before jumping to a PR. @russoz and @felixfontein may be interested to weigh in on this one. Feel free to assign this issue to me as I'm happy to do the PR once we agree on a design in this issue.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/modules/system/xfconf.py

##### ADDITIONAL INFORMATION

There are a couple things I could see us addressing with a cleaner return format.

1. The type description is always a scalar
1. No variant types for values

###### The type description is always a scalar
___
As far as I can tell, the xfce4 settings only allow arrays of homogeneous types. Because of this, we can always return a scalar value for `value_type` regardless of if the value is an array or scalar. This feels more straight forward to use, and also solves the variant issue for the `value_type` return.

If we like this, I suggest also adopting this for the `value_type` parameter for the same reasons above and for consistency between parameters and return.

###### No variant types for values
___
*Method 1: a return variable tells the type, different variables for the two types*
Pros:
* Is completely explicit about the return type (array vs scalar)

Cons:
* Would require more logic for the end user to determine which variable holds the data they want, or the user assumes the type which makes the `value_format` return of questionable values for the added complexity.

An example of a scalar return
```yaml
value_scalar: "the_value"
value_type: "string"
value_format: "scalar"
```

Example of an array return
```yaml
value_array: ["10", "15"]
value_type: "int"
value_format: "array"
```

*Method 2: Always promote scalar returns to a list with one element, add `value_is_array`*
Pros:
* Only one return value to handle that comes back in a single type: `list of strings`
* Can still distinguish between arrays and scalars if needed

Cons:
* Are there any?

Example of scalar return
```yaml
value: ["the value"]
value_type: "string"
value_is_array: false
```

Example of list return
```yaml
value: ["10", "20", "30"]
value_type: "int"
value_is_array: true
```

Example of single element list return
```yaml
value: ["10"]
value_type: "int"
value_is_array: true
```

I prefer method 2 since it makes usage of the return value more straight forward in the majority of use cases by always putting the return data in one variable. Additionally it still retains the ability to distinguish between an array and scalar if that was needed (although I struggle to find the use case for this...).

###### *Handling deprecation*
There is a follow on question of how to handle the deprecations. There was some discussion about this, but I don't have my head fully wrapped around it. I'd appreciate some input here on how to handle this.

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/system/xfconf.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/xfconf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jbenden
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by russoz** [comment]
@lifeisafractal thanks for putting this together.

A couple of comments there: I am about to raise a PR for a change in ModuleHelper that will make the handling of deprecations slightly easier.

As of the output, I would be veering more towards Method 1, but a bit different:
Scalar return
```yaml
value: "the value"
value_asarray: null
value_type: "string"
is_array: false
```
List return
```yaml
value: null
value_asarray: [10, 20, 30]
value_type: ["int", "int", "int"]
is_array: true
```
Single element list return
```yaml
value: null
value_asarray: [10]
value_type: ["int"]
is_array: true
```
The bottom line is, in any case the user will need to do an `if` for `value_format` or `is_array`, but in M2 as you presented, we need to index `[0]` on the result when it is NOT an array, which is an odd syntax: _"I just told you it is NOT an array, so treat it like one"_.

What do you think of it?
