### ISSUE TITLE
Typo in redfish-utils memory inventory

### ISSUE THREAD

**Issue by jakjablonski** [ansible-collections/community.general#1483]
##### SUMMARY

Redfish utils - get memory module, have a typo in the field name. 
Part Number is missing because the property in get_memory_ineventory() in redfish_utils.py is incorrect.
Change PartNuber to PartNumber.
```
properties = ['SerialNumber', 'MemoryDeviceType', 'PartNuber',
                      'MemoryLocation', 'RankCount', 'CapacityMiB', 'OperatingMemoryModes', 'Status', 'Manufacturer', 'Name']
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_info - category: Systems - command: GetMemoryInventory
\plugins\module_utils\redfish_utils.py
##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/home/elk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
no change
```

##### OS / ENVIRONMENT

ubuntu 20.04

##### STEPS TO REPRODUCE

execute and check fileds in redfish_facts.memory.entries

```yaml
- name: Get memory inventory
      redfish_info:
        category: Systems
        command: GetMemoryInventory
        baseuri: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ pwd }}"
```

##### EXPECTED RESULTS

PartNumber is printed correctly

##### ACTUAL RESULTS

PartNumber is missing in output
