### ISSUE TITLE
general.postgresql_user reporting changes on every run

### ISSUE THREAD

**Issue by davorceman** [ansible-collections/community.general#1497]
##### SUMMARY
```
First time using this module. I created database and user with privileges on that database
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.postgresql_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /.../ansible.cfg
  configured module search path = [u'/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(.../ansible.cfg) = False
```

##### OS / ENVIRONMENT

Amazon Linux 2

##### STEPS TO REPRODUCE

```yaml
- name: Create stock user and grant access to stock database
  community.general.postgresql_user:
    login_host: xxx.eu-central-1.rds.amazonaws.com
    login_user: admin
    login_password: adminpassword
    db: stock
    name: stock
    password: userpassword
    encrypted: yes
    priv: ALL
    expires: infinity
```

##### EXPECTED RESULTS

After second run I expected status ok=1 changed=0
