### ISSUE TITLE
Proxmox inventory keyed_groups

### ISSUE THREAD

**Issue by silviuvulcan** [ansible-collections/community.general#1503]
Would it be possible to add an option for `keyed_groups ` ? Similar to the Hetzner Cloud plugin: https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_inventory.html

This would allow for example to use notes to group hosts into arbitrary groups (I'm thinking prod, dmz, etc.) It would require some standard usage of the notes field maybe semicolon separated sets of label=value.

E.g.

```yaml
keyed_groups:
  - key: notes.ansible_group
    prefix: proxmox
```

What do you think ?

##### COMPONENT NAME
community.general.proxmox
