### ISSUE TITLE
Support GSSAPI authentication for ldap_* module

### ISSUE THREAD

**Issue by wimvanleuven** [ansible-collections/community.general#1523]
##### SUMMARY

Add the attribute `sasl_class` with values `external` (default) or `gssapi` to `community.general/plugins/module_utils/ldap.py`
to select the SASL authentication algorithm for python-ldap when user name and password are not provide. Currently, the ansible modules default to EXTERNAL.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ldap_attr
ldap_attrs
ldap_entry
ldap_passwd
ldap_search

##### ADDITIONAL INFORMATION

Adding the attribute `sasl_class` would allow to switch the default SASL authentication mechanism from `EXTERNAL` to `GSSAPI` which would help windows-based shops to transparently authenticate to Active Directory and use the LDAP modules to query and adjust their AD servers even from non-Windows servers. 

```yaml
- name: admin group must exist
  community.general.ldap_entry:
    dn: CN=my_admin_group,OU=Groups,OU=Global,DC=dir,DC=example,DC=com
    objectClass: group
    server_uri: "{{ ad.url }}"
    sasl_class: gssapi
    state: present
```
