### ISSUE TITLE
datadog_monitor module unable to mute monitor based on a scope and time

### ISSUE THREAD

**Issue by RommelLayco** [ansible-collections/community.general#1535]
##### SUMMARY

The datadog_monitor allows you to mute a monitor based on a scope and timestamp using the silenced parameter. This parameter does not work, as it is ignored by the datadog sdk and just mutes every host managed by the monitor forever.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

datadog_monitor

##### ANSIBLE VERSION

```paste below
2.9.15
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

mac os

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
  
      - datadog_monitor:
          api_key: axxxxxxxxxxxxxxx5
          app_key: cxxxxxxxxxxxa
          name: "My Monitor"
          state: mute
          silenced:
            scope: "host:my-host"
            end: 1608685755

```

##### EXPECTED RESULTS

only the host my-host to be muted till 1608685755

##### ACTUAL RESULTS

all hosts managed by the monitor are muted.

```paste below

```
