### ISSUE TITLE
adopt module from ssh_config role

### ISSUE THREAD

**Issue by jorhett** [ansible-collections/community.general#1562]
##### SUMMARY

There's a very useful role developed by @gaqzi at https://github.com/gaqzi/ansible-ssh-config which appears to be unmaintained. There's a lot of interest visible in Pull Requests and Forks. I'd like to suggest that we either import his role (if he agrees) or make a new one for ssh config management where an active community can keep it going.

I can offer to do the initial integration and bring it up to community standards.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ssh_config

##### ADDITIONAL INFORMATION

Creating all new SSH configuration from templates isn't suitable for all purposes. A module to edit the configuration in line would be very useful. This module would mirror the functionality of the existing *ansible.community.git_config* module, but for ssh obviously ;-) 

```yaml
- name: Add internal-lib.github.com to ssh config
  ssh_config:
    host: internal-lib.github.com
    hostname: github.com
    identity_file: id_rsa.internal-lib
    port: 222
    state: present
```
