### ISSUE TITLE
community.general.udm_user - mail_primary_address does not work

### ISSUE THREAD

**Issue by aperrotta-nli** [ansible-collections/community.general#1564]
##### SUMMARY
adding a user to Univention Server with "community.general.udm_user" only works partially, 
The field primary Email is not filled in.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.general.udm_user

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/arturo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]

```

##### OS / ENVIRONMENT
Univention Server 

##### STEPS TO REPRODUCE
```
- name: Add User to LDAP and set Primary Group - Domain Users
  community.general.udm_user:
    position: "cn={{ basic_groups[1] }},ou={{ company_group }},dc=cloud,dc=local"
    username: "{{ item.username}}"
    firstname: "{{ item.firstname }}"
    lastname: "{{ item.lastname }}"
    organisation: "{{ company_group }}"
    **mail_primary_address: "{{ item.email }}"**
    displayName: "{{ item.username }}"
    password: "{{ default_password }}"
    update_password: on_create
    state: present
  when: item.action == 'add'
  with_items: "{{ users }}"

Playbook:
  hosts: univention.local
  become: true 
  vars:
    role_action: 'create_basic_users'
    company_group: '01'
    department_group: 'team_x'
    users:
      - lastname: Smith
        firstname: Max
        username: msmith
        email: msmith@cloud.local 
        action: add

      - lastname: Doe
        firstname: Peter
        username: pdoe
        email: pdoe@cloud.local 
        action: add
  roles:
    - 3196_manage_univention

```

##### EXPECTED RESULTS
an email address in the mail_primary_address field - on the Univention Dashboard

##### ACTUAL RESULTS
no results
![Univention Management Console](https://user-images.githubusercontent.com/25204737/103364050-02222a80-4abd-11eb-92f7-5f4460d620f5.png)
