### ISSUE TITLE
dnsimple creates fatal error

### ISSUE THREAD

**Issue by tmasterson** [ansible-collections/community.general#1605]
##### SUMMARY

There are several different issues depending on the version of python's dnsimple module and the version of ansible.  I am documenting for ansible 2.9/2.10 and dnsimple 2.1.0. Using dnsimple 1.0.0 and up generates different fatal crashs but they all have them.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnsimple
##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Host: ubuntu 20.04, target: debian 10

##### STEPS TO REPRODUCE

```yaml
---
- name: a record exists
  community.general.dnsimple:
    account_email: "{{ bs_dnsimple_email }}"
    account_api_token: "{{ bs_dnsimple_api_token }}"
    domain: "{{ bs_dnsimple_domain }}"
    record: "{{ inventory_hostname }}"
    type: A
    solo: yes
    value: "{{ bs_external_ipv4 | ipv4('address') }}"
  delegate_to: localhost
  when: bs_dnssimple_create_a

```

##### EXPECTED RESULTS

No fatal errors

##### ACTUAL RESULTS

```paste below
Using module file /home/tom/.ansible/collections/ansible_collections/community/general/plugins/modules/dnsimple.py
Using module file /home/tom/.ansible/collections/ansible_collections/community/general/plugins/modules/dnsimple.py
Using module file /home/tom/.ansible/collections/ansible_collections/community/general/plugins/modules/dnsimple.py
Pipelining is enabled.
Pipelining is enabled.
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: tom
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: tom
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: tom
<localhost> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.general.dnsimple_payload_d8r5k3yn/ansible_community.general.dnsimple_payload.zip/ansible_collections/community/general/plugins/modules/dnsimple.py", line 152, in <module>
ImportError: cannot import name 'DNSimple' from 'dnsimple' (/usr/local/lib/python3.8/dist-packages/dnsimple/__init__.py)
fatal: [master-0]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "account_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "account_email": "ml@akabos.com",
            "domain": "cp.k8s.blueswan.io",
            "priority": null,
            "record": "master-0",
            "record_ids": null,
            "solo": true,
            "state": "present",
            "ttl": 3600,
            "type": "A",
            "value": "74.207.248.38"
        }
    },
    "msg": "Failed to import the required Python library (dnsimple) on precision-M2800's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}
```
This form is not the easiest to use for screen readers and the galaxy comminity site is really unfriendly.
