### ISSUE TITLE
Snap module does not change channel if the snap is already installed

### ISSUE THREAD

**Issue by sean-abbott** [ansible-collections/community.general#1606]
##### SUMMARY
I'm attempting to set the snap channel with ansible on already installed machines, but "tracking" channel (which happens to currently co-incide with the version I'm tracking to track) remains pointed at latest/stable

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
snap

##### ANSIBLE VERSION

```
ansible 2.10.4
  config file = None
  configured module search path = ['/home/sean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sean/.local/pipx/venvs/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/sean/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

##### STEPS TO REPRODUCE

```yaml
- name: install microk8s snap latest
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes
    state: present

- name: install microk8s snap
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes
    channel: 1.20/stable
    state: present
```

##### EXPECTED RESULTS
I expect the tracking channel of the microk8s snap 

##### ACTUAL RESULTS
The tracking channel for the microk8s snap remains set to latest/stable
