### ISSUE TITLE
ldap_attrs - seems to add additional attribute value even when specifying "state: exact" - LDAPserver reports error

### ISSUE THREAD

**Issue by shackled-mystic** [ansible-collections/community.general#1624]
##### SUMMARY
Using community.general.ldap_attrs to update configuration for RHDS11(hosted on RHEL8)
when trying to update some attributes (nsslapd-db-locks in this case), the module throws the error:
```
failed: [XXXX-lxXXXX.BLAH.com] (item={'key': 'nsslapd-db-locks', 'value': '10000'}) => {"ansible_loop_var": "item", "changed": false, "details": "{'desc': 'Object class violation'}", "item": {"key": "nsslapd-db-locks", "value": "10000"}, "msg": "Attribute action failed."}
```
directory error logs show:
```
[12/Jan/2021:11:20:50.263003242 +0000] - ERR - bdb_public_config_set - Error setting instance config attr nsslapd-db-locks to 10000: cannot add a value to single valued attribute nsslapd-db-locks.
```
This seems to suggest the module is trying to add another value for the attribute instead of the intended replace. Here's how the play looks:
```
- name: ## cn=config,cn=ldbm database,cn=plugins,cn=config ##
  community.general.ldap_attrs:
    dn: cn=config,cn=ldbm database,cn=plugins,cn=config
    attributes: "{{ item.key }}={{ item.value }}"
    state: exact
    server_uri: "ldaps://{{ ansible_fqdn }}:{{ bind_port }}/"
    bind_dn: "{{ rhdsops_dirmngr_dn }}"
    bind_pw: "{{ rhdsops_dirmngr_pw }}"
  loop: "{{ rhdsops_ldbm_config|dict2items }}"
```
rhdsops_ldbm_config is defined in the vars section of a role and passed to the module. Excerpt:
```
rhdsops_ldbm_config:
  nsslapd-mode: 600   << no errors here
  nsslapd-lookthroughlimit: 250000   << no errors here
  nsslapd-idlistscanlimit: 4000 << no errors here
  nsslapd-db-locks: "10000"          << this is where the module throws the error -- I've tried with/without quotes
  nsslapd-import-cache-autosize: 0
  nsslapd-cache-autosize: 0
  nsslapd-cache-autosize-split: 40
  nsslapd-import-cachesize: 419430400
  nsslapd-dbcachesize: 536870912
  nsslapd-pagedlookthroughlimit: 0
  nsslapd-pagedidlistscanlimit: 0
  nsslapd-rangelookthroughlimit: 5000
  nsslapd-db-deadlock-policy: 9
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ldap_attrs

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = /Users/shsar2/BLAH-GIT/SHSAR2-DEV/ansible.cfg
  configured module search path = ['/Users/shsar2/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.4/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Dec 10 2020, 10:36:41) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/shsar2/BLAH-GIT/SHSAR2-DEV/ansible.cfg) = ['/Users/shsar2/BLAH-GIT/SHSAR2-DEV/inventory/rhds11_dev.ini']
DEFAULT_PRIVATE_KEY_FILE(/Users/shsar2/BLAH-GIT/SHSAR2-DEV/ansible.cfg) = /Users/shsar2/BLAH-GIT/SHSAR2-DEV/_ssh/id_rsa_Dec20_YEAHYEAH
DEFAULT_REMOTE_USER(/Users/shsar2/BLAH-GIT/SHSAR2-DEV/ansible.cfg) = REMOTE-USER
DEFAULT_ROLES_PATH(/Users/shsar2/BLAH-GIT/SHSAR2-DEV/ansible.cfg) = ['/Users/shsar2/BLAH-GIT/SHSAR2-DEV/roles']
HOST_KEY_CHECKING(/Users/shsar2/BLAH-GIT/SHSAR2-DEV/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.3 (Ootpa)
Linux XXXX-lxXXXX.BLAH.com 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Fri Oct 16 13:36:46 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

LDAP server is RHDS/389:
389-ds-base.x86_64                                 1.4.3.13-1.module+el8dsrv+8334+69a46a2e         

##### STEPS TO REPRODUCE

```
- name: ## cn=config,cn=ldbm database,cn=plugins,cn=config ##
  community.general.ldap_attrs:
    dn: cn=config,cn=ldbm database,cn=plugins,cn=config
    attributes: "{{ item.key }}={{ item.value }}"
    state: exact
    server_uri: "ldaps://{{ ansible_fqdn }}:{{ bind_port }}/"
    bind_dn: "{{ rhdsops_dirmngr_dn }}"
    bind_pw: "{{ rhdsops_dirmngr_pw }}"
  loop: "{{ rhdsops_ldbm_config|dict2items }}"
```

##### EXPECTED RESULTS

 attribute should be set to the exact value specified:
nsslapd-db-locks: 10000

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_community.general.ldap_attrs_payload_lew8yw7z/ansible_community.general.ldap_attrs_payload.zip/ansible_collections/community/general/plugins/modules/ldap_attrs.py", line 310, in main
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 629, in modify_s
    return self.modify_ext_s(dn,modlist,None,None)
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 602, in modify_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 749, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 756, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 329, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib64/python3.6/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib64/python3.6/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
failed: [XXXX-lxXXXX.BLAH.com] (item={'key': 'nsslapd-db-locks', 'value': '10000'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "details": "{'desc': 'Object class violation'}",
    "invocation": {
        "module_args": {
            "attributes": {
                "nsslapd-db-locks": "10000"
            },
            "bind_dn": "cn=XXXX-XXX-XXX",
            "bind_pw": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "dn": "cn=config,cn=ldbm database,cn=plugins,cn=config",
            "ordered": false,
            "server_uri": "ldaps://XXXX-lxXXXX.BLAH.com:6336/",
            "start_tls": false,
            "state": "exact",
            "validate_certs": true
        }
    },
    "item": {
        "key": "nsslapd-db-locks",
        "value": "10000"
    },
    "msg": "Attribute action failed."
}
```

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/net_tools/ldap/ldap_attrs.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/ldap/ldap_attrs.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @drybjed @jtyr @nerzhul @noles
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by drybjed** [comment]
I'm not sure if the `ldap_attrs` module supports the syntax you are trying to use, specifically:
```yaml
- name: ## cn=config,cn=ldbm database,cn=plugins,cn=config ##
  community.general.ldap_attrs:
    dn: cn=config,cn=ldbm database,cn=plugins,cn=config
    attributes: "{{ item.key }}={{ item.value }}"
    state: exact
    server_uri: "ldaps://{{ ansible_fqdn }}:{{ bind_port }}/"
    bind_dn: "{{ rhdsops_dirmngr_dn }}"
    bind_pw: "{{ rhdsops_dirmngr_pw }}"
  loop: "{{ rhdsops_ldbm_config|dict2items }}"
```

Use of `dict2items` here is unnecessary. Instead, you can pass the dictionary directly and it should be processed by the module as expected:
```yaml
- name: ## cn=config,cn=ldbm database,cn=plugins,cn=config ##
  community.general.ldap_attrs:
    dn: cn=config,cn=ldbm database,cn=plugins,cn=config
    attributes: "{{ rhdsops_ldbm_config }}"
    state: exact
    server_uri: "ldaps://{{ ansible_fqdn }}:{{ bind_port }}/"
    bind_dn: "{{ rhdsops_dirmngr_dn }}"
    bind_pw: "{{ rhdsops_dirmngr_pw }}"
```
Can you check if that works?
