### ISSUE TITLE
MSSQL Script

### ISSUE THREAD

**Issue by stobias123** [ansible-collections/community.general#1633]
##### SUMMARY
We have `mssql_db` for creating databases.

I'd like a simple module, similar to `win_shell` and `shell` that allows for arbitrary execution of SQL scripts. There's times when I need to run simple seed or migration scripts as part of ansible deployments.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mssql_script

##### ADDITIONAL INFORMATION
N/A

```yaml
- name: run a simple script to check 
  mssql_script:
    db: mydb
    login_user: user
    login_password: pass
    login_host: foo.bar
    script: "drop table foo"

- name: Seed the db.
  community.general.mssql_script:
    db: mydb
    script: "{{lookup('file', 'seed.sql')}}"

- name: Run Migrations
  community.general.mssql_script:
    db: mydb
    script: "{{lookup('file', item)}}"
  with_fileglob:
    - "/path_to_scripts/*.sql'
```
