### ISSUE TITLE
Make mas more robust to deal with app installs on new Macs more gracefully

### ISSUE THREAD

**Issue by Sergong** [ansible-collections/community.general#1646]
##### SUMMARY

mas currently does not handle installation of Apps from the App Store gracefully when the app has never been installed (such as as is the case typically for a new Mac).
If `mas install [id]` fails, the module should not fail but instead try to use `mas purchase [id]` first. This stands a good chance of succeeding depending to the user's App Store Media & Purchase preferences.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

mas

##### ADDITIONAL INFORMATION

Ideally the module would be used as is today but would handle failures in case of apps never before installed on this Mac, more gracefully by retrying with the mas-cli command `mas purchase [id] `. Alternatively the module could have another option to control how apps are installed as per playbook example below.

```yaml
---
- name: Install Mac Apps from App Store
  hosts: localhost

  vars:
    apps:
      - name: Test
        id: 123456789

  tasks:
    - name: install all apps
      community.general.mas:
        id: "{{ item.id }}"
        state: present
        install_method: purchase # choose from install or purchase
     loop: "{{ apps }}"

```
