### ISSUE TITLE
pacman: ignore packages of a group

### ISSUE THREAD

**Issue by TomZanna** [ansible-collections/community.general#1665]
##### SUMMARY

Implement the option to avoid installing some packages of a group.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

pacman

##### ADDITIONAL INFORMATION

I wrote a playbook for my laptop to configure an Arch install.
However, there are some packages included in a group that I would not like to have installed.

```yaml
- name: Install the DE
  pacman:
    name:
      - plasma
    state: present
    ignore:
      - discover
      - plasma-sdk
      - plasma-thunderbolt

```
