### ISSUE TITLE
redfish_utils.py set_manager_nic IndexError: list index out of range

### ISSUE THREAD

**Issue by lukurde** [ansible-collections/community.general#1692]
##### SUMMARY
Trying to disable DHCP on a fresh HPE iLO and assign a static IP via SetManagerNic throws an out of index error.

This is my task:
```
  - name: Set Manager NIC
    community.general.redfish_config:
      category: Manager
      command: SetManagerNic
      nic_config:
        DHCPv4:
          DHCPEnabled: False
        IPv4StaticAddresses:
          Address: xxx.xxx.xxx.xxx
          Gateway: xxx.xxx.xxx.xxx
          SubnetMask: xxx.xxx.xxx.xxx
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
```

In reality Redfish returns empty list:

```
    "IPv4Addresses": [
        {
            "Address": "xxx.xxx.xxx.xxx",
            "AddressOrigin": "DHCP",
            "Gateway": "xxx.xxx.xxx.xxx",
            "SubnetMask": "xxx.xxx.xxx.xxx"
        }
    ],
    "IPv4StaticAddresses": [],            <-------- here
```

I've hacked around this by commenting out property check and adding try/except:

~/.ansible/collections/ansible_collections/community/general/plugins/module_utils/redfish_utils.py

```
            # type is list
            if isinstance(set_value, list):
                for i in range(len(set_value)):
                    for subprop in payload[property][i].keys():
                        #if subprop not in target_ethernet_current_setting[property][i]:
                        #    return {'ret': False, 'msg': "Sub-property %s in nic_config is invalid" % subprop}
                        sub_set_value = payload[property][i][subprop]
                        try:
                            sub_cur_value = target_ethernet_current_setting[property][i][subprop]
                        except (KeyError, IndexError):
                            sub_cur_value = ''
                        if sub_set_value != sub_cur_value:
                            need_change = True
```

I'm not sure if the check is needed at all. Trying to set invalid property returns error:

```
FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "HTTP Error 400 on PATCH request to 'https://xxx.xxx.xxx.xxx/redfish/v1/Managers/1/EthernetInterfaces/1/', extended message: 'Bad Request'"}
````

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/redfish_utils.py#L2681

and 

https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/redfish_utils.py#L2684

##### ANSIBLE VERSION

```
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lukaszkurdziel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

##### CONFIGURATION
Default. Not related.

##### OS / ENVIRONMENT
Fedora. Not related.

##### STEPS TO REPRODUCE
Try to change DHCP HPE iLO default config to static IP.

##### EXPECTED RESULTS
DHCP disabled, static IP assigned.

##### ACTUAL RESULTS

```
ansible_collections/community/general/plugins/module_utils/redfish_utils.py\", line 2681, in set_manager_nic\nIndexError: list index out of range
```
