### ISSUE TITLE
Support `path` parameter for `homebrew_tap`

### ISSUE THREAD

**Issue by bombsimon** [ansible-collections/community.general#1702]
##### SUMMARY

It would be nice to support multiple installations of `brew` in the `homebrew_tap` task. The main reason for me wanting this is since the current state of a lot of programs on Apple Silicon ARM M1 is somewhat limited and you might want to install an x86 version in `/usr/local` with Rosetta 2 support and a native arm version in `/opt/homebrew`. 

This is currently almost possible, when running the `homebrew` task, you can specify [`path`](https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html#parameter-path). However, if you need to add a tap by using `homebrew_tap`, that's not possible.

In #1660 support was added to search both `/opt/homebrew` and `/usr/local` for `brew` installations, however this means it will always use the first one found even if there's multiple installation on the system.

In the [`improbable-eng/ansible-buildkite-agent` role](https://github.com/improbable-eng/ansible-buildkite-agent/pull/63) I want to pick my `brew` installation when tapping `buildkite-agent` but this is currently not possible.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

`homebrew_tap`

##### ADDITIONAL INFORMATION

Something like this would make sense I think
```yaml
- name: Tap a Homebrew repository with specific path
  community.general.homebrew_tap:
    path: /opt/homebrew/bin
    name: buildkite/buildkite

- name: Install buildkite-agent
  community.general.homebrew:
    path: /opt/homebrew/bin
    name: buildkite-agent
```
