### ISSUE TITLE
nmcli not working on Ubuntu Server 20.04

### ISSUE THREAD

**Issue by CodingSpiderFox** [ansible-collections/community.general#1707]
##### SUMMARY
I try setting a static IP on my servers using the following playbook.

```
- name: Configure hosts
  hosts: servers
  tasks:
    - name: Install needed network manager libs
      become: yes
      ansible.builtin.package:
        name:
          - network-manager
        state: present
    - name: "Configuring eth"
      nmcli:
        conn_name: "System ens18"
        ifname: ens18
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "{{ansible_host}}"
        gw4: "a.b.c.d"
```

My playbook gives the following error
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Namespace NMClient not available
fatal: [node1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (NetworkManager glib API) on node1's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nmcli
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
<EMPTY>
```

##### OS / ENVIRONMENT

Servers: Ubuntu Server 20.04.1

##### STEPS TO REPRODUCE

```yaml
- name: Configure hosts
  hosts: servers
  tasks:
    - name: Install needed network manager libs
      become: yes
      ansible.builtin.package:
        name:
          - network-manager
        state: present
    - name: "Configuring eth"
      nmcli:
        conn_name: "System ens18"
        ifname: ens18
        type: ethernet
        state: present
        autoconnect: yes
        ip4: "{{ansible_host}}"
        gw4: "a.b.c.d"
```
`ansible-playbook -i hosts.yml site.yml --ask-become-pass`

##### EXPECTED RESULTS

IPs are set

##### ACTUAL RESULTS

Error message

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Namespace NMClient not available
fatal: [node1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (NetworkManager glib API) on node1's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/net_tools/nmcli.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/nmcli.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @alcamie101 @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Did you install all [requirements](https://docs.ansible.com/ansible/2.9/modules/nmcli_module.html#requirements) for this module? You seem to be using the nmcli module from Ansible 2.9, not the one from this collection (which only requires the CLI program that you installed).

**Comment by CodingSpiderFox** [comment]
Yes, at least the nmcli.py comments say that under Ubuntu only network-manager is needed

```
tasks:
    - name: Install needed network manager libs
      become: yes
      ansible.builtin.package:
        name:
          - network-manager
        state: present
```
