### ISSUE TITLE
Delete GitLab runner broken

### ISSUE THREAD

**Issue by kerrhome** [ansible-collections/community.general#1714]
**OVERVIEW**

Error states that it requires registration_token be defined.

**SUMMARY**

Following the example on https://docs.ansible.com/ansible/latest/collections/community/general/gitlab_runner_module.html shows
```
- name: "Delete runner"
  community.general.gitlab_runner:
    api_url: https://gitlab.example.com/
    api_token: "{{ access_token }}"
    description: Docker Machine t1
    state: absent
```

gives error:
```
TASK [Delete GitLab Runner] ******************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: registration_token"}
```

**ISSUE TYPE**

Bug Report

**COMPONENT NAME**

gitlab_runner

**ANSIBLE VERSION**

```
ansible 2.10.5
  config file = /home/shannon/.ansible.cfg
  configured module search path = [u'/home/shannon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shannon/.local/lib/python2.7/site-packages/ansible
  executable location = /home/shannon/.local/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

**CONFIGURATION**

```
HOST_KEY_CHECKING(/home/user1/.ansible.cfg) = False
```

**OS / ENVIRONMENT**

Debian Linux 10 Buster
localhost

**STEPS TO REPRO**

```
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
   - name: Delete GitLab Runner
     community.general.gitlab_runner:
       api_url: https://gitlab.example.com/
       api_token: "{{ lookup('env','gitlab_token') }}"
       description: cloudnode1
       state: absent
```
ansible-playbook <playbook>.yml

**EXPECTED RESULTS**

deletes runner

**ACTUAL RESULTS**

```
TASK [Delete GitLab Runner] ******************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: registration_token"}
```
