### ISSUE TITLE
ipa_dnszone HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by dmc5179** [ansible-collections/community.general#1855]
**Summary**

I have a task that looks like:
```
- name: Create DNS Zone
  delegate_to: localhost
  community.general.ipa_dnszone:
    ipa_host: '{{ ipa_host }}'
    ipa_user: '{{ ipa_user }}'
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: 'myzone.{{ base_domain }}'
    validate_certs: '{{ ipa_ssl_enabled }}'
```

This tasks works when run against my IPA server in one lab. When I run it against a RedHat IdM server in another lab it fails with the following message:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dynamicupdate": "false",
            "ipa_host": "ipahostname",
            "ipa_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ipa_port": 443,
            "ipa_prot": "https",
            "ipa_timeout": 10,
            "ipa_user": "ipausername",
            "state": "present",
            "validate_certs": false,
            "zone_name": "myzone.mydomain"
        }
    }
}

MSG:

login: HTTP Error 400: Bad Request
```
I can create the zone using the ipa cli after I run kinit as my user. I'm using the same username and password with kinit and the ipa cli as I am with the ansible task. I can also login to the IdM GUI with my user/password.

I've tried setting my password in ansible to junk but I get the exact  same error message. I've tried using the IdM server's IP address and hostname. I've tried a dot at the end of the hostname. Running out of ideas.

**Issue Type**

Bug Report

**Component Name**

ipa_dnszone

**Ansible Version**

```
ansible 2.9.12
  config file = /home/dan.clark/workspace/openshift4-disconnected/playbooks/ansible.cfg
  configured module search path = ['/home/dan.clark/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

**Configuration**

```
- name: Create DNS Zone
  delegate_to: localhost
  community.general.ipa_dnszone:
    ipa_host: '{{ ipa_host }}'
    ipa_user: '{{ ipa_user }}'
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: 'myzone.{{ base_domain }}'
    dynamicupdate: true
    validate_certs: '{{ ipa_ssl_enabled }}'

```

**OS / Environment**

Server where I am running ansible: 4.18.0-193.el8.x86_64 #1 SMP Fri Mar 27 14:35:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

IPA package versions: ipa-client-4.8.4-7.module+el8.2.0+6047+59605870.x86_64

**Steps To Reproduce**

```paste below
ansible-playbook myplaybook.yaml
```

**Expected Results**

A DNS zone is created or confirmed to be present in the IdM Server

**Actual Results**

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dynamicupdate": "false",
            "ipa_host": "ipahostname",
            "ipa_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ipa_port": 443,
            "ipa_prot": "https",
            "ipa_timeout": 10,
            "ipa_user": "myusername",
            "state": "present",
            "validate_certs": false,
            "zone_name": "myzone.basedomaine"
        }
    }
}

MSG:

login: HTTP Error 400: Bad Request
```
