### ISSUE TITLE
gitlab_user: add support to block user account

### ISSUE THREAD

**Issue by smeeus** [ansible-collections/community.general#187]
##### SUMMARY

The gitlab_user module currently supports only two states; present and absent. The python-gitlab package has the ability to also block a user account. Deleting a user is not always desired as all projects owned by that user will be also permanently removed from GitLab too. It would be nice to add a new state of blocked where the user account is blocked instead of deleted.

Original Ansible issue: https://github.com/ansible/ansible/issues/61754
Original Ansible PR: https://github.com/ansible/ansible/pull/61864
Updated Ansible PR: https://github.com/ansible/ansible/pull/66273

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

- gitlab_user

##### ADDITIONAL INFORMATION

Sample usage:

```yaml
- name: Block user account
  gitlab_user:
    server_url: example.gitlab.com
    api_token:  kFCjRgwa/WriXncb7ews6A
    username: mjeco
    email: ""
    name: ""
    password: ""
    state: blocked
```
