### ISSUE TITLE
read_csv: feature request: ability to read in csv data from var instead of only file path

### ISSUE THREAD

**Issue by t-readyroc** [ansible-collections/community.general#1881]
##### COMPONENT NAME
read_csv

##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = /Users/tburre169/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/virtualenvs/ansible/lib/python3.8/site-packages/ansible
  executable location =~/virtualenvs/ansible/bin/ansible
  python version = 3.8.5 (default, Sep 14 2020, 13:42:18) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### SUMMARY
Have attempted to use the following:

```
new_user_csv: "firstname,lastname,email
  John,Smith,johnsmith@hotmail.com
  Jane,Doe,jane.doe@gmail.com"

- name: Read in New Users CSV
  community.general.read_csv:
    path: "{{ new_user_csv }}"
  register: new_users
``` 

But it looks like the current module can only take a file path to open an external file. It'd be great if I were able to pass in a blob of csv data via a variable if that's something that's at all possible.
