### ISSUE TITLE
Module haproxy times out instead setting HAProxy backends into DRAIN mode followed by MAINT mode

### ISSUE THREAD

**Issue by christianhueserhzdr** [ansible-collections/community.general#1913]
**Summary**

HAProxy allows to set backends into DRAIN mode that waits until the server has no active connections anymore before setting the backends into MAINT mode.

The respective Ansible haproxy module has a state and parameter `drain` that can be used to do this with Ansible.

At the moment and given my setup the module haproxy never enters MAINT mode, times out and fails.

Please note that this has already been reported with a suggested fix here but has been closed during migration to this new repository:

* Issue: https://github.com/ansible/ansible/issues/37591
* Pull Request: https://github.com/ansible/ansible/pull/59156

Reopening it here in the new repository for Ansible collection "community.general".

**Issue Type**

Bug Report

**Component Name**

haproxy

**Ansible Version**

```paste below
ansible 2.10.6
  config file = /home/xxx/yyyy/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/share/virtualenvs/ansible-_MQ25oBn/lib/python3.8/site-packages/ansible
  executable location = /home/xxx/.local/share/virtualenvs/ansible-_MQ25oBn/bin/ansible
  python version = 3.8.0 (default, Oct 28 2019, 16:14:01) [GCC 8.3.0]
```

**Configuration**

```paste below
ANSIBLE_PIPELINING(/home/xxx/yy/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/xxx/yyy/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=5m
COLLECTIONS_PATHS(/home/xxx/yyy/ansible.cfg) = ['/home/xxx/yyy/collections']
DEFAULT_HOST_LIST(/home/xxx/yyy/ansible.cfg) = ['/home/xxx/yyy/inventories/development/hosts']
DEFAULT_REMOTE_PORT(/home/xxx/yyy/ansible.cfg) = 2222
DEFAULT_REMOTE_USER(/home/xxx/yyy/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/xxx/yyy/ansible.cfg) = ['/home/hxxx/yyy/roles']
DEFAULT_SCP_IF_SSH(/home/xxx/yyy/ansible.cfg) = True
INTERPRETER_PYTHON(/home/xxx/yyy/ansible.cfg) = auto
RETRY_FILES_ENABLED(/home/xxx/yyy/ansible.cfg) = False
```

**OS / Environment**

Ubuntu 18.04.5 LTS

**Steps To Reproduce**

The following three cases reproduce the same bug:

1)

```yaml
- name: Drain HAProxy Backends
  community.general.haproxy:
    host: "hostname"
    state: drain
    socket: "/run/haproxy/admin.sock"
    backend: "backend"
    wait: yes
    wait_interval: 5
    wait_retries: 60
- name: Disable HAProxy Backends
  community.general.haproxy:
    host: "hostname"
    state: disabled
    socket: "/run/haproxy/admin.sock"
    backend: "backend"
    drain: yes
    wait: yes
    wait_interval: 5
    wait_retries: 60
```

2)

```yaml
- name: Drain HAProxy Backends
  community.general.haproxy:
    host: "hostname"
    state: drain
    socket: "/run/haproxy/admin.sock"
    backend: "backend"
- name: Disable HAProxy Backends
  community.general.haproxy:
    host: "hostname"
    state: disabled
    socket: "/run/haproxy/admin.sock"
    backend: "backend"
    drain: yes
    wait: yes
    wait_interval: 5
    wait_retries: 60
```

3)

```yaml
- name: Drain and disable HAProxy Backends
  community.general.haproxy:
    host: "hostname"
    state: disabled
    socket: "/run/haproxy/admin.sock"
    backend: "backend"
    drain: yes
    wait: yes
    wait_interval: 5
    wait_retries: 60
```

**Expected Results**

It is expected that Ansible sets the respective HAProxy backends first in DRAIN mode and after that in MAINT mode if the server has no active connections anymore.

**Actual Results**

Ansible module haproxy waits until timeout is reached and fails because mode MAINT is never reached for case 1 mentioned above:

```paste below
TASK [Drain HAProxy Backends] ******************************************************************************************************************************************
changed: {"changed": true, "command": ["set server backend/hostname state drain"], "output": [""], "state_after": [{"scur": "0", "status": "DRAIN", "weight": "1"}], "state_before": [{"scur": "0", "status": "UP", "weight": "1"}]}                                              
                                   
TASK [Disable HAProxy Backends] ******************************************************************************************************************************************
failed: {"changed": false, "msg": "server backend/hostname not status 'MAINT' after 60 retries. Aborting."}
```
