### ISSUE TITLE
Unnecessary warning that password does not exist from htpasswd

### ISSUE THREAD

**Issue by gdubicki** [ansible-collections/community.general#1925]
**Summary**

I am using `htpasswd` module in a code that has two states - enabled when a password is provided and disabled when it's not. In the enabled state it should set a password for the given user in the file, in disabled it should remove it.

This minor issue I have is that when I run my code in the disabled state for the first time, then the target passwd file does not exist and it is fine. But the module complains about it with a WARNING...

**Issue Type**

Bug Report

**Component Name**

htpasswd

**Ansible Version**

```
ansible 2.9.10
  config file = /<redacted>/ansible.cfg
  configured module search path = ['/Users/gdubicki/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.7 (default, Dec 30 2020, 10:13:08) [Clang 12.0.0 (clang-1200.0.32.28)]
```

**Steps To Reproduce**

1. Use this code on a server that DOES NOT have the `/etc/httpd/passwdfile` file (yet):
```
- name: "Put password in the passwd file, if password provided"
  htpasswd:
    state: "{{ 'present' if basic_auth_enabled else 'absent' }}"
    path: /etc/httpd/passwdfile
    name: "foo"
    password: "bar"
    owner: apache
    group: apache
    mode: 0400
```

**Expected Results**

When `basic_auth_enabled` is false we should get this:
```
TASK [foobar : Put password in the passwd file, if password provided] **********************************
ok: [vagrant]
```

**Actual Results**

```
TASK [foobar : Put password in the passwd file, if password provided] **********************************
[WARNING]: /etc/httpd/passwdfile does not exist
ok: [vagrant]
```
