### ISSUE TITLE
 The mode parameter of community.general.nmcli does not take effect for team connection

### ISSUE THREAD

**Issue by 18660155632** [ansible-collections/community.general#1950]
### Summary

I want to create a connection of type team, mode is active-backup. But the setting does not take effect

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```
ansible 2.10.6
python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]

```

### Configuration

```paste below

```

### Steps To Reproduce

```
- name: add team1
      community.general.nmcli:
        type: team
        conn_name: team1
        ip4: 1.1.1.1/24
        gw4: 1.1.1.254
        mode: active-backup
        state: present
```

### Actual Results

```
#nmcli con show team1


team.runner:                            roundrobin


```

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/net_tools/nmcli.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/nmcli.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @alcamie101 @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by omula** [comment]
As far as I can see the mode is not used for configuring teaming devices.
Red Hat [documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configure_a_network_team_using-the_command_line) show that json format can be used to specify the configuration for the team.

I am considering implementing something like the sample below and then use `team_config` in json format in `nmcli.py`. Would you add checking for `team_config` parameters or just let nmcli validate it? What do you think?
```
- name: Add an Team connection with static IP configuration
  community.general.nmcli:
    conn_name: team2
    ifname: team2
    type: team
    ip4: 192.0.2.100/24
    gw4: 192.0.2.1
    state: present
    autoconnect: yes
    team_config:
      runner:
        name: activebackup
        hwaddr_policy: by_active
      link_watch:
        name: ethtool
```
