### ISSUE TITLE
zypper_repository: unable to refresh when using variable in URL, always shown as changed

### ISSUE THREAD

**Issue by dev-zero** [ansible-collections/community.general#1985]
### Summary

When trying to configure a repository with the `$releasevar` inside, Ansible always lists the repository as changed and is unable to refresh since it fails to lookup the repo by URL.
Please note that using the `$releasevar` variable in the URL is nowadays recommended by openSUSE to allow for easier dist-upgrade.

### Issue Type

Bug Report

### Component Name

zypper_repository

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.6
  config file = /home/tiziano/work/ansible/tc/ansible.cfg
  configured module search path = ['/home/tiziano/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tiziano/.local/share/virtualenvs/ansible/lib/python3.9/site-packages/ansible
  executable location = /home/tiziano/.local/share/virtualenvs/ansible/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/tiziano/work/ansible/tc/ansible.cfg) = ['/home/tiziano/work/ansible/tc/collections', '/home/tiziano/.ansible/collections', '/usr/share/ansible/collections']
DEFAULT_HOST_LIST(/home/tiziano/work/ansible/tc/ansible.cfg) = ['/home/tiziano/work/ansible/tc/hosts.ini']
DEFAULT_ROLES_PATH(/home/tiziano/work/ansible/tc/ansible.cfg) = ['/home/tiziano/work/ansible/tc/roles/internal', '/home/tiziano/work/ansible/tc/roles/external']
INTERPRETER_PYTHON(/home/tiziano/work/ansible/tc/ansible.cfg) = /usr/bin/python3
```

### OS / Environment

openSUSE LEAP 15.2

### Steps to Reproduce

```yaml (paste below)
  - name: Configure Packman package repository (ZYPPER)
    zypper_repository:
      name: "Packman-Leap-15"
      repo: "http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/"
      autorefresh: yes
      priority: 90
      state: present
```

### Expected Results

The second time running this on the same host it should be listed as `ok` (respectively it should succeed if I have `auto_import_keys` enabled).

### Actual Results

```console (paste below)
TASK [common : Configure Packman package repository (ZYPPER)] *********************************************************************************************************************************************************************************
changed: [tcpc18.chem.uzh.ch]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
