### ISSUE TITLE
Ansible archive changing file(s) in some way

### ISSUE THREAD

**Issue by jagauthier** [ansible-collections/community.general#1994]
### Summary

Using the 'archival' function in ansible reveals files are changed in some way.
Example:
I've exported a docker image to tar file.
```
md5sum gitlab.tar
a583a3e53d55fbf27881dd6d73f5d8ca gitlab.tar
```
Then, along with many other files, I've created an archive using the ansible archive component.

After extracting the archive to a different directory:
```
md5sum test/gitlab.tar
2e75b6d1b9a60734119d136c8bbc84e5 test/gitlab.tar
```

### Issue Type

Bug Report

### Component Name

archive

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jgauthier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

CentOS 7.8

### Steps to Reproduce

```yaml (paste below)
    - name: Archive everything for transport
      archive:
        path: "{{lookup('env', 'PWD')}}/ansible_*"
        dest: "{{archive_loc}}/ansiblepackages.tar.gz"
```

### Expected Results

I expected the file that I extracted to have the same md5 signature as the one I archived.  This is especially important as it's a docker image export and fails importing due to the hash being different.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
