### ISSUE TITLE
proxmox_kvm: Bug on the returned value

### ISSUE THREAD

**Issue by uriho-ui160** [ansible-collections/community.general#2088]
### Summary

When I run the proxmox_kvm module, I can't get the VMs IDs values

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.19

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu

### Steps to Reproduce

```
  - name: Clone VMs machines
    proxmox_kvm:
        api_host: pve
        name: "{{ item.vm }}"
        node: pve
        #state: present
        clone: Ubuntu_Template
    register: proxmox
    with_items:
      - "{{ myList.list }}"
```

### Expected Results

{
"vmid": 102
"vmid": 103
}

### Actual Results

```
ok: [pve] => {
    "msg": "proxmox returned = {'msg': u'All items completed', 'changed': False, 'results': [{'ansible_loop_var': u'item', 'failed': False, u'changed': False, 'item': {u'name': u'VM1', u'mac': u'AA:BB:CC:DD:EE:FF'}, u'invocation': {u'module_args': {u'force': None, u'smbios': None, u'revert': None, u'numa': None, u'scsihw': None, u'startup': None, u'migrate_speed': None, u'freeze': None, u'full': True, u'keyboard': None, u'skiplock': None, u'watchdog': None, u'serial': None, 
...
}]}"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
