### ISSUE TITLE
lxd_container: add support for remotes with self-signed certificates.

### ISSUE THREAD

**Issue by cquike** [ansible-collections/community.general#2089]
### Summary

I am trying to create a new container using the lxd_container ansible module which uses an image stored in a LXC server. The playbook looks like this:
    - name: Create LXD container
      community.general.lxd_container:
        name: test-container-ansible
        state: started
        source:
          type: image
          server: https://my-lxd-image-server.example.com:8443
          mode: pull
          protocol: lxd
          alias: my-ubuntu-image

However I get the following message:
Get https://my-lxd-image-server.example.com:8443/1.0: x509: certificate signed by unknown authority
This image server is internal to my company and it is not easy to get a non self-signed certificate so it would be useful if there is a parameter that allows to have self-signed certificates. 

### Issue Type

Feature Idea

### Component Name

lxd_container

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cloud/lxd/lxd_container.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/lxd/lxd_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by conloos** [comment]
Hi cquike,

I am currently not using any certificates. But I also didn't see anything in the ansible plugin source code that makes a check here. So I assume this is an lxd issue. I'll do a check on the weekend and get in touch. 


Frank

**Comment by felixfontein** [comment]
The [lxd module_utils code](https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/lxd.py) has its own HTTP handling (instead of using the things provided by Ansible), so adding this is not as simple as for most other modules.

If someone wants to rewrite it to use `fetch_url` from the ["official" url module_utils](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L1690), a `validate_certs` option would be easy to add.

**Comment by conloos** [comment]
Hi Felix,

i will put it in my backlog after finishing the dynamic inventory.

Have a nice weekend

Frank

**Comment by Pandino** [comment]
Hi cquike, 

according to the [LXD API](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-optional-targetmember) you should be able to add a PEM certificate in the `source` dict using the key `certificate`.

**Comment by rnalrd** [comment]
> Hi cquike,
> 
> according to the [LXD API](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-optional-targetmember) you should be able to add a PEM certificate in the `source` dict using the key `certificate`.

Same problem here. I tried this:

```
    - name: Create container {{ containername }} [=>{{lxc_host}}]
      delegate_to: "{{ lxc_host }}"
      community.general.lxd_container:
        name: "{{ containername }}"
        ephemeral: yes
        profiles: myprofile
        ignore_volatile_options: false
        source:
          type: image
          mode: pull
          server: https://k119h.my.domain.com:8443
          alias: custom_image
          certificate: server.pem
```

and I'm getting the error below now, instead of "certificate signed by unknown authority":

"msg": "Invalid remote certificate"
