### ISSUE TITLE
Can't use CreateBiosConfigJob command from idrac_redfish_command module

### ISSUE THREAD

**Issue by pyfontan** [ansible-collections/community.general#2090]
### Summary

I'm trying to create a job for BIOS configuration.

In the documentation example, specified resource_id is System.Embedded.1
https://github.com/ansible-collections/community.general/blob/926c0a71d03a447580b6a034432608c632477059/plugins/modules/remote_management/redfish/idrac_redfish_command.py#L68

When i use this resource, i have an error message : 
> Manager resource System.Embedded.1 not found

explained by:
https://github.com/ansible-collections/community.general/blob/926c0a71d03a447580b6a034432608c632477059/plugins/modules/remote_management/redfish/idrac_redfish_command.py#L201

And of course, if I use iDRAC.embedded.1 which is the actual manager resource ID, task fails with :
> System resource iDRAC.Embedded.1 not found

explained by :
https://github.com/ansible-collections/community.general/blob/926c0a71d03a447580b6a034432608c632477059/plugins/modules/remote_management/redfish/idrac_redfish_command.py#L194

### Issue Type

Bug Report

### Component Name

idrac_redfish_command

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.5
  config file = /home/pyfontan/.ansible.cfg
  configured module search path = ['/home/pyfontan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pyfontan/virtualenv/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/pyfontan/virtualenv/ansible/bin/ansible
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

iDRAC 4.32.20.00 on PowerEdge C6525
or
iDRAC 3.21.26.22 on PowerEdge R740xd

### Steps to Reproduce

```yaml
- name: Create BIOS configuration job (schedule BIOS setting update)
  community.general.idrac_redfish_command:
    category: Systems
    command: CreateBiosConfigJob
    #resource_id: "{{asset_system_resource_name}}"
    #resource_id: "System.Embedded.1"
    resource_id: "iDRAC.Embedded.1"
    baseuri: "{{ asset.manager.ip }}"
    username: "{{ asset.manager.user }}"
    password: "{{ asset.manager.password }}"
 ```

### Expected Results

I expect to have a BIOS Job configuration created.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
