### ISSUE TITLE
add "force" option for vdo modules

### ISSUE THREAD

**Issue by Davidffry** [ansible-collections/community.general#2101]
### Summary

I am trying to create VDO volume but the target partition is in xfs. in command line I use the option --force to create the vdo volume

### Issue Type

Feature Idea

### Component Name

vdo

### Additional Information

```yaml (paste below)
- name: Create 2 TB VDO volume vdo1 on device /dev/md0
  vdo:
    name: vdo1
    state: present
    device: /dev/md0
    logicalsize: 2T
    force: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
