### ISSUE TITLE
Enable no-bin-links for community.general.npm

### ISSUE THREAD

**Issue by skluthe** [ansible-collections/community.general#2128]
### Summary

I'm working on getting a vagrant development environment setup and am running into an issue where npm is having trouble installing on a synced folder. A solution would be to enable a flag to add the --no-bin-links setting to disable symlinking executables but there's no way to set this currently.

### Issue Type

Feature Idea

### Component Name

community.general.npm

### Additional Information

```yaml (paste below)
- name: NPM install for Login Service
  community.general.npm:
    path: "{{ project_root }}"
    links: no
  become_user: vagrant
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
