### ISSUE TITLE
ipa_user field userauthtype takes string instead of list

### ISSUE THREAD

**Issue by justchris1** [ansible-collections/community.general#2173]
### Summary

The ipa_user module has a field for userauthtype, which is currently set to str.  It also lists choices, which all seem to be the valid choices.  However, the field is multiselect in IPA.  With the type str and fixed choices, only one value is permitted with this implementation.  

The solution is easy and just changing the type to list of str seems to work.  That includes in a backwards compatible way (existing playbooks should still work).  However, please validate this.  I will make a simple PR to address.

### Issue Type

Bug Report

### Component Name

ipa_user

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.18
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
(empty)
```

### OS / Environment

Centos 7 controlling a Centos 8 IPA server. (IPA 4.8.7, API version 2.239)

### Steps to Reproduce

The following fails, because userauthtype is set to str, instead of list of str.
```yaml (paste below)
- name: Create newuser1
  community.general.ipa_user:
    name: newuser1
    givenname: New User
    sn: User
    userauthtype: ['otp', 'password']
    ipa_host: IPA_HOST
    ipa_user: USERNAME
    ipa_pass: PASSWORD
```

### Expected Results

The above ansible snippet will succeed without failure.

### Actual Results

```console (paste below)
"msg": "value of userauthtype must be one of: password, radius, otp, pkinit, hardened, got: ['otp', 'password']"
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct
