### ISSUE TITLE
ini_file is thrown off by BOM

### ISSUE THREAD

**Issue by myxal** [ansible-collections/community.general#2189]
### Summary

I noticed that an INI file I'm modifying is getting its first section split up. (I'm setting an option which doesn't already exist.) The software that uses the file does not support duplicate sections, and fails to launch as a result.

After investigation, the cause appears to be the presence of BOM at the beginning of the file, which causes the first section's header to be ignored.
EDIT: Further investigation revealed that the BOM was introduced by modifying the file within Windows Powershell (v5.1) using cmdlets from the [PSIni 3.1.2](https://lipkau.github.io/PsIni/) module. From what I'm reading about Powershell's handling of text files, upgrading to the newer, cross-platform version of powershell should solve the issue for no-explicit encoding set ("Utf8NoBom"), and the old version may be able to dodge the issue by specifying non-UTF encoding, such as ASCII, assuming the content allows for it.

I've only found reference to BOM in issue 26048, where the resolution says BOM files are unsupported in inventories - I think this is fair, but shouldn't BOM files be supported in INI module? In many cases the files which this module is to modify, come from Windows environments.

### Issue Type

Bug Report

### Component Name

ini_file

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.9
  config file = None
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0+ (default, Oct 19 2020, 09:51:18) [GCC 10.2.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Debian 10-based docker container

### Steps to Reproduce

Run the following playbook
```
ansible-playbook test.yaml
```

```yaml (paste below)
---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create starting ini file
    copy:
      # The content below is the following text file with BOM:
      # [section1]
      # var1=aaa
      # var2=bbb
      # [section2]
      # var3=ccc
      content: !!binary |
        77u/W3NlY3Rpb24xXQp2YXIxPWFhYQp2YXIyPWJiYgpbc2VjdGlvbjJdCnZhcjM9Y2NjCg==
      dest: ./sandbox.ini
  - name: Test ini breakage
    ini_file:
      path: ./sandbox.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value | default(omit) }}"
      state: "{{ item.state | default(omit) }}"
    with_items:
    - { section: "section1", option: "var4", value: "0" }

```

### Expected Results

Option _var4_ should be added to _section1_ at the beginning of the file.

### Actual Results

A new _section1_ is created, containing only _var4_
```
[section1]
var1=aaa
var2=bbb
[section2]
var3=ccc
[section1]
var4 = 0
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct
