### ISSUE TITLE
manageiq_provider fails creating AWS provider on python 3 environment with serialization error

### ISSUE THREAD

**Issue by kenchrcum** [ansible-collections/community.general#222]
##### SUMMARY
mangeiq_provider fails creating an AWS provider if executed with python 3. It works without as expected on python 2. Other providers were not tested.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
manageiq_provider

##### ANSIBLE VERSION

```paste below
2.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Doesn't work on python 3 environment. Neither on AWX 10.0.0 nor on local installation in python 3 virtual environment

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - manageiq_provider:
        name: test1234
        type: Amazon
        state: present
        zone: AWS
        provider_region: eu-central-1
        provider:
          hostname: apigateway.eu-central-1.amazonaws.com
          userid: "{{ accesskey }}"
          password: "{{ secretkey }}"
        manageiq_connection:
          url: "{{ manageiqserver }}"
          username: "{{ manageiqsuser }}"
          password: "{{ manageiqpassword }}"

```

##### EXPECTED RESULTS

Successful run

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to update provider test1234: Object of type map is not JSON serializable"}
```
