### ISSUE TITLE
terraform: Add support for multiple variables_file

### ISSUE THREAD

**Issue by m-yosefpor** [ansible-collections/community.general#224]
##### SUMMARY
Add support for multiple variables_file as we can pass multiple var-files in terraform cli:
`terraform  apply -var-file="file-1.tfvars"  -var-file="file-2.tfvars"  -var-file="file-3.tfvars"`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
terraform module

##### ADDITIONAL INFORMATION
In many projects there are multiple variable files which are needed to be passed to terrform, but right now, the terraform module only supports a single file ( type "path"). But it could be ( type "list")

Expected usage:

```yaml
- name: Terraform with multiple variables_file(s)
  terraform:
    project_path: '/home/centos/terraform'
    variables_file: 
      - "/home/terraform/overrides/file-1.tfvars"
      - "/home/terraform/overrides/file-2.tfvars"
      - "/home/terraform/overrides/somepath/file-3.tfvars"
    targets: some-target
```
