### ISSUE TITLE
Redhat_subscription always return changed status

### ISSUE THREAD

**Issue by tinsjourney** [ansible-collections/community.general#226]
##### SUMMARY

Since ansible Version 2.9.5 and PR #66478, redhat_subscription status is always changed even is host is already registered with RHN

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redhat_subscription
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tinsjourney/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Red Hat 8.1

##### STEPS TO REPRODUCE

```yaml
[tinsjourney@labs ~]$ cat redhat_subscription.yaml
- name: Register Host to RHN
  hosts: all
  become: true
  vars:
    ansible_user: root

  tasks:
  - name: Register host to RHN
    redhat_subscription:
      state: present
      username: "my_username"
      password: "my_password"
      pool_ids: 0123456789abcdef0123456789abcdef
```

##### EXPECTED RESULTS

```
[tinsjourney@labs ~]$ ansible-playbook -i rhosp16-registry, redhat_subscription.yaml

PLAY [Register Host to RHN] ************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [rhosp16-registry]

TASK [Register host to RHN] ***********************************************************************************************************
ok: [rhosp16-registry]

PLAY RECAP ****************************************************************************************************************************
rhosp16-registry           : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

```paste below
[tinsjourney@labs ~]$ ansible-playbook -i rhosp16-registry, redhat_subscription.yaml

PLAY [Register Host to RHN] ************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [rhosp16-registry]

TASK [Register host to RHN] ***********************************************************************************************************
changed: [rhosp16-registry]

PLAY RECAP ****************************************************************************************************************************
rhosp16-registry           : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
