### ISSUE TITLE
influxdb_retention_policy module not idempotent

### ISSUE THREAD

**Issue by xabinapal** [ansible-collections/community.general#2281]
### Summary

Module `influxdb_retention_policy` is not idempotent because `duration` and `shard_group_duration` parameters are not correctly checked against the server.

### Issue Type

Bug Report

### Component Name

influxdb_retention_policy

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
```

### OS / Environment

Tested on a fresh Ubuntu 20.04 installation and also on macOS Big Sur 11.2.3.

InfluxDB is running on a Docker container with version 1.8.4 and it's a fresh container with no databases and no retention policies.

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  tasks:
    - community.general.influxdb_database:
        hostname: localhost
        database_name: test

    - community.general.influxdb_retention_policy:
        hostname: localhost
        database_name: test
        policy_name: test_inf
        duration: INF
        shard_group_duration: 1h
        replication: 1

    - community.general.influxdb_retention_policy:
        hostname: localhost
        database_name: test
        policy_name: test_zero
        duration: 0h
        shard_group_duration: 1h
        replication: 1

    - community.general.influxdb_retention_policy:
        hostname: localhost
        database_name: test
        policy_name: test_finite
        duration: 1h
        shard_group_duration: 1h
        replication: 1

    - community.general.influxdb_retention_policy:
        hostname: localhost
        database_name: test
        policy_name: test_full
        duration: 1h0m0s
        shard_group_duration: 1h
        replication: 1

    - community.general.influxdb_retention_policy:
        hostname: localhost
        database_name: test
        policy_name: test_shard_duration
        duration: 1h0m0s
        shard_group_duration: 1h0m0s
        replication: 1
```

### Expected Results

Module `influxdb_retention_policy` should be idempotent, and executing the playbook twice should not show any changes.

### Actual Results

First execution:

```console (paste below)
$ ansible-playbook test.yml
PLAY [localhost] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [community.general.influxdb_database] *********************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=7    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Second execution:

```console (paste below)
$ ansible-playbook test.yml
PLAY [localhost] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [community.general.influxdb_database] *********************************************************************************************
ok: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
ok: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

TASK [community.general.influxdb_retention_policy] *************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
