### ISSUE TITLE
hpiLo_boot force should be exclusive with poweroff

### ISSUE THREAD

**Issue by jhg03a** [ansible-collections/community.general#2283]
### Summary

While using the hpiLo_boot module, I was trying to force the system power off.  I made the mistake of setting both the force argument and the state of poweroff.  The behavior in this case is counter to what I'd expect; rebooting instead of powering off.  The force flag should either throw an error with the state poweroff, or just ignore the force flag in this case.

### Issue Type

Feature Idea

### Component Name

hpilo_boot

### Additional Information

```yaml (paste below)
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    baseuri: iloIP
    username: foo
    password: bar

  tasks:
  - name: Force the system off in case it's stuck in POST
    hpilo_boot:
      host: "{{ baseuri }}"
      login: "{{ username }}"
      password: "{{ password }}"
      state: poweroff
      force: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
