### ISSUE TITLE
docker_swarm invalid join token

### ISSUE THREAD

**Issue by J7mbo** [ansible-collections/community.general#234]
##### ISSUE TYPE
- Bug Report

##### SUMMARY

When joining a swarm with `docker_swarm`, the response is:

>  {"changed": false, "msg": "Can not join the Swarm Cluster: 500 Server Error: Internal Server Error (\"invalid join token\")"}

[Someone else reported this on stackoverflow but never resolved it](https://stackoverflow.com/questions/58232506/docker-swarm-module-join-token-parameter-for-ansible-not-working).

Here are the tasks. **Please note that creating the swarm works. Joining gives the error.**.

```
        # THIS WORKS
        -   name: "Initialise swarm on manager node"
            when: "node_ips[manager_node] == inventory_hostname"
            register: swarm_result
            docker_swarm:
                advertise_addr: "{{ node_ips[manager_node] }}"
                state: "present"

       # THIS FAILS
        -   name: "Join swarm on worker nodes"
            when: "inventory_hostname != node_ips[manager_node]"
            docker_swarm:
                remote_addrs: "{{ node_ips[manager_node] }}"
                advertise_addr: "{{ inventory_hostname }}"
                join_token: swarm_result.swarm_facts.JoinTokens.Worker
                state: "join"
```

##### COMPONENT NAME

`docker_swarm`

##### ANSIBLE VERSION
```
ansible 2.9.7
```

##### OS / ENVIRONMENT
```
MacOS
```

Originally posted here: https://github.com/ansible/ansible/issues/69156.
