### ISSUE TITLE
latest version of lvol needs small g for gigabyte and captial G no longer working

### ISSUE THREAD

**Issue by MalfuncEddie** [ansible-collections/community.general#2360]
### Summary

When trying out the last version every lvol I created that had a capital G does no longer work.

setting the size to lowecase G does work.

eg:
size: "4g" # works
size: "4G" # cannot shrink unless force ....

### Issue Type

Bug Report

### Component Name

lvol

### Ansible Version

```console (paste below)
$ ansible --version
ansible-playbook 2.9.14
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
- name: 4Gb /tmp no longer works (cannot shrink..)
  lvol:
    vg: rootvg
    lv: tmp
    size: "4G"
    resizefs: yes

- name: 4Gb /tmp works 
  lvol:
    vg: rootvg
    lv: tmp
    size: "4g"
    resizefs: yes

```

### Expected Results

according to documentation it should not matter what case you use

The size of the logical volume, according to lvcreate(8) --size, by default in megabytes or optionally with one of [bBsSkKmMgGtTpPeE] units; or according to lvcreate(8) --extents as a percentage of [VG|PVS|FREE]; Float values must begin with a digit. Resizing using percentage values was not supported prior to 2.1.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/system/lvol.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/lvol.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @abulimov @jhoekx @unkaputtbar112 @zigaSRC
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MalfuncEddie** [comment]
https://gist.github.com/MalfuncEddie/a2e75b951d13355cbd585ea432488c4e

**Comment by MalfuncEddie** [comment]
Hi,

Seams the module is now gibibyte/gigabyte aware. Looks like a good Idea but does change existing playbooks since the underlying os utility has no knowledge of gibibyte/gigabyte.

manpage from lvextend: 

Size[UNIT]
              Size is an input number that accepts an optional unit.  Input units are always treated as base two values, regardless of capitalization, e.g. 'k' and 'K'  both  refer  to  1024.
              The  default input unit is specified by letter, followed by |UNIT.  UNIT represents other possible input units: bBsSkKmMgGtTpPeE.  b|B is bytes, s|S is sectors of 512 bytes, k|K
              is kilobytes, m|M is megabytes, g|G is gigabytes, t|T is terabytes, p|P is petabytes, e|E is exabytes.  (This should not be confused with the output control --units, where capi‐
              tal letters mean multiple of 1000.)


This makes playbooks no longer idempotent the following playbook should not fail since it is asking the same thing twice. Yet it does fail. Why? because it is created with 7GB but the second task wants to shrink it to 7GiB  (6.xxx GB)

```yaml
- name: test
  become: true
  become_method: sudo
  gather_facts: no
  hosts: all
  tasks:
    - name: 7g /tmp
      community.general.lvol:
        vg: rootvg
        lv: tmp
        size: "7G"
        resizefs: yes

    - name: 7G /tmp
      community.general.lvol:
        vg: rootvg
        lv: tmp
        size: "7G"
        resizefs: yes
```
```
ansible-playbook -i ,xxx.xxx.xxx.xxx -k -K test0.yml
SSH password:
BECOME password[defaults to SSH password]:

PLAY [test] ****************************************************************************************************************************************************************************************

TASK [7g /tmp] *************************************************************************************************************************************************************************************
changed: [xxx.xxx.xxx.xxx]

TASK [7G /tmp] *************************************************************************************************************************************************************************************
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "msg": "Sorry, no shrinking of tmp without force=yes."}
        to retry, use: --limit @/home/users/test0.retry

PLAY RECAP *****************************************************************************************************************************************************************************************
xxx.xxx.xxx.xxx : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
