### ISSUE TITLE
lvol: extending to ' +100%FREE' calculating wrong size

### ISSUE THREAD

**Issue by dominikkaminski** [ansible-collections/community.general#2370]
### Summary

When I try to extend lv to max free available disk space, it calculates the wrong size after upgrading from 2.5.1 to current release (3.0.0)

Error:
--------
```
fatal: [vm-001]: FAILED! => {"changed": false, "msg": "Logical Volume root could not be extended. Not enough free space left (5120.0m required / 5116.0m available)"}
```

Possibly related to:
-------------------------
https://github.com/ansible-collections/community.general/issues/1988
https://github.com/ansible-collections/community.general/pull/2267

### Issue Type

Bug Report

### Component Name

lvol

### Ansible Version

```console (paste below)
ansible 2.10.8
  config file = /home/dominik.kaminski/ansible/ansible.cfg
  configured module search path = ['/home/dominik.kaminski/ansible/library']
  ansible python module location = /home/dominik.kaminski/.local/lib/python3.6/site-packages/ansible
  executable location = /home/dominik.kaminski/.local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

UCS

### Steps to Reproduce

```yaml (paste below)
- name: "Extend logical volume to available space"
  community.general.lvol:
    vg: "{{ extend_root_lvm_volume_lvm_vg_name }}"
    lv: "{{ extend_root_lvm_volume_lvm_data_volume }}"
    resizefs: "yes"
    size: "+100%FREE"
  tags:
    - extend_root_lvm_volume_resize
```

### Expected Results

Volumes should be extended to available free space or calculating free available size correct.

### Actual Results

```console (paste below)
fatal: [vm-001]: FAILED! => {"changed": false, "msg": "Logical Volume root could not be extended. Not enough free space left (5120.0m required / 5116.0m available)"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
