### ISSUE TITLE
Error creating keystore when extracting public certificate from pkcs12

### ISSUE THREAD

**Issue by splieth** [ansible-collections/community.general#2374]
### Summary

When I recently updated to Ansible 2.10.8, the Playbook I'm using in order to create a keystore with the VMs certificate in it, the `java_cert` module fails to put that certificate into the keystore with the message: `"Internal module failure, cannot extract public certificate from pkcs12, error: "`.

With Ansible 2.10.6, I don't get that error. I suspect this to be related to the change regarding how the keystore password is handled (I've seen `Internal module failure, cannot extract public certificate from pkcs12, error: Enter keystore password:`, but not with the task provided here).

### Issue Type

Bug Report

### Component Name

java_cert

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.8
  config file = /Users/splieth/projects/deployment/ansible.cfg
  configured module search path = ['/Users/splieth/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/splieth/.local/share/virtualenvs/deployment-054P1BD-/lib/python3.9/site-packages/ansible
  executable location = /Users/splieth/.local/share/virtualenvs/deployment-054P1BD-/bin/ansible
  python version = 3.9.4 (default, Apr  5 2021, 01:50:46) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

ANSIBLE_SSH_ARGS(/Users/splieth/projects/deployment/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=60 -o StrictHostKeyChecking=no
ANSIBLE_SSH_CONTROL_PATH(/Users/splieth/projects/deployment/ansible.cfg) = /tmp/%%h-%%p
ANSIBLE_SSH_RETRIES(/Users/splieth/projects/deployment/ansible.cfg) = 10
CACHE_PLUGIN(/Users/splieth/projects/deployment/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/Users/splieth/projects/deployment/ansible.cfg) = ~/ansible_cache
CACHE_PLUGIN_PREFIX(/Users/splieth/projects/deployment/ansible.cfg) = _ansible_cache_
CACHE_PLUGIN_TIMEOUT(/Users/splieth/projects/deployment/ansible.cfg) = 43200
DEFAULT_FORKS(/Users/splieth/projects/deployment/ansible.cfg) = 20
DEFAULT_LOG_PATH(/Users/splieth/projects/deployment/ansible.cfg) = /Users/splieth/projects/deployment/logs/ansible.log
DEFAULT_ROLES_PATH(/Users/splieth/projects/deployment/ansible.cfg) = ['/Users/splieth/projects/deployment/roles', '/etc/ansible/roles']
DEFAULT_TIMEOUT(/Users/splieth/projects/deployment/ansible.cfg) = 900
DEFAULT_VAULT_PASSWORD_FILE(/Users/splieth/projects/deployment/ansible.cfg) = /Users/splieth/.ansible_vault_pw
DISPLAY_SKIPPED_HOSTS(/Users/splieth/projects/deployment/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/splieth/projects/deployment/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/Users/splieth/projects/deployment/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/Users/splieth/projects/deployment/ansible.cfg) = yaml
INVENTORY_CACHE_TIMEOUT(/Users/splieth/projects/deployment/ansible.cfg) = 43200
RETRY_FILES_ENABLED(/Users/splieth/projects/deployment/ansible.cfg) = False
```

### OS / Environment

macOS, CentOS 8.3

### Steps to Reproduce

```yaml (paste below)
---
- name: create new pkcs
  when: not ansible_check_mode
  openssl_pkcs12:
    action: export
    path: "/tmp/{{ inventory_hostname }}.p12"
    privatekey_path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
    certificate_path: "/etc/pki/tls/certs/{{ inventory_hostname }}.crt"
    passphrase: "changeit"
    friendly_name: "{{ inventory_hostname_short }}"
    owner: "someUser"
    group: "someUser"

- name: create new keystore keystore.p12
  become: yes
  become_user: "someUser"
  become_flags: "-i"
  java_cert:
    pkcs12_path: "/tmp/{{ inventory_hostname }}.p12"
    pkcs12_password: "changeit"
    pkcs12_alias: "{{ inventory_hostname_short }}"
    cert_alias: "{{ item }}"
    keystore_path: "/tmp/{{ inventory_hostname_short }}.jks"
    keystore_pass: "changeit"
    keystore_create: yes
    state: present
  loop:
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname_short }}"
```

### Expected Results

No error when creating the keystore.

### Actual Results

```console (paste below)
TASK [deploy_role : create new pkcs] ***********************************
task path: /Users/splieth/projects/deployment/roles/deploy_role/tasks/cert.yml:2
redirecting (type: modules) ansible.builtin.openssl_pkcs12 to community.crypto.openssl_pkcs12
changed: [hostname.dev.some-domain.com] => {"changed": true, "filename": "/tmp/hostname.p12", "mode": "0400", "privatekey_path": "/etc/pki/tls/private/hostname.dev.some-domain.com.key"}

TASK [deploy_role : create new keystore keystore.p12] ******************
task path: /Users/splieth/projects/deployment/roles/deploy_role/tasks/cert.yml:14
redirecting (type: modules) ansible.builtin.java_cert to community.general.java_cert
failed: [hostname.dev.some-domain.com] (item=hostname.dev.some-domain.com) => {"ansible_loop_var": "item", "changed": false, "item": "hostname.dev.some-domain.com", "msg": "Internal module failure, cannot extract public certificate from pkcs12, error: ", "rc": 1}
redirecting (type: modules) ansible.builtin.java_cert to community.general.java_cert
failed: [hostname.dev.some-domain.com] (item=hostname) => {"ansible_loop_var": "item", "changed": false, "item": "hostname", "msg": "Internal module failure, cannot extract public certificate from pkcs12, error: ", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/system/java_cert.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/java_cert.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @absynth76 @haad
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The way the module uses run_command, no shell is involved. Do you have an example what kind of special characters cause problems?

**Comment by felixfontein** [comment]
I only managed to reproduce this with non-ASCII characters, but not with regular special characters (like $, punctuation, ...). Mishandling of non-ASCII characters could be a encoding problem.

**Comment by absynth76** [comment]
To test I duplicated the embedded keystore, 
so far I tested with:
changeit
changeit!
changeit$
changeit\
changeit/
changeit.

and no issue at all, I can only reproduce the failure in case I provide an incorrect keystore password to the task.

In the meantime, reading the code I saw I made a mistake at another place, 
"Unused variable 'pkcs12_alias'pylint(unused-variable)"
```
            _export_public_cert_from_pkcs12(module, executable, pkcs12_path, cert_alias, pkcs12_pass, new_certificate)
```
it should be
```
            _export_public_cert_from_pkcs12(module, executable, pkcs12_path, pkcs12_alias, pkcs12_pass, new_certificate)
```
sorry for the noise, this one should deserve another ticket I guess

**Comment by felixfontein** [comment]
@absynth76 for the unrelated part, just create a small PR fixing it.

**Comment by felixfontein** [comment]
> I only managed to reproduce this with non-ASCII characters, but not with regular special characters (like $, punctuation, ...). Mishandling of non-ASCII characters could be a encoding problem.

In fact I didn't even reproduce it with this module, but with java_keystore. I tried to reproduce it using the java_cert integration tests, but the task it failed was a java_keystore task... I guess the problem there is that `openssl` (password via stdin) and `keytool` (password via env variable) handle encodings differently...

**Comment by felixfontein** [comment]
@splieth I have a question about your bug report. You are stating that you are using the `java_cert` module to **create** a keystore. The documentation does not state that it creates keystores, it only states that it **modifies** existing keystores. It could be that older versions of the module would create a keystore if none exists.

**Comment by absynth76** [comment]
It appears my tests were done with a previous version of the code because my working dir was outdated. please don't consider my previous 2 comments so.

To answer to @felixfontein, even if the main description does not talk about "creation" of a keystore, the module is able to do so. There is even a (default to False) flag to make it happen "keystore_create". It could (maybe) deserve a small update and mention that fact in the main description ("eventually create").

For your issue, @splieth I must admit I cannot reproduce it, here what I did:
```
- hosts: localhost
  tasks:
      - name: Generate the self signed cert used as a place holder to create the java keystore
        command: openssl req -x509 -newkey rsa:4096 -keyout {{ test_key_path }} -out {{ test_cert_path }} -days 365 -nodes -subj '/CN=localhost'
        args:
          creates: "{{ test_key_path }}"
      
      - name: create new pkcs
        openssl_pkcs12:
          action: export
          path: "{{ test_keystore2_path }}.with_openssl"
          privatekey_path: "{{ test_key_path }}"
          certificate_path: "{{ test_cert_path }}"
          passphrase: "{{ test_keystore2_password }}"
          friendly_name: "friendly_name"
          owner: myowner
          group: mygroup

      - name: create new keystore keystore.p12
        become: yes
        become_user: myowner
        become_flags: "-i"
        java_cert:
          pkcs12_path: "{{ test_keystore2_path }}.with_openssl"
          pkcs12_password: "{{ test_keystore2_password }}"
          pkcs12_alias: "friendly_name"
          cert_alias: "{{ item }}"
          keystore_path: "/tmp/friendly_name.jks"
          keystore_pass: "{{ test_keystore2_password }}"
          keystore_create: yes
          state: present
        loop:
          - "friendly_name"
```

and my parameters:
```
output_dir: /tmp/testzone
test_pkcs12_path: testpkcs.p12
test_keystore_path: keystore.jks
test_keystore2_path: "{{ output_dir }}/keystore2.jks"
test_keystore2_password: edzaedaz!$eza%eza#
test_cert_path: "{{ output_dir }}/cert.pem"
test_key_path: "{{ output_dir }}/key.pem"
test_cert2_path: "{{ output_dir }}/cert2.pem"
test_key2_path: "{{ output_dir }}/key2.pem"
test_pkcs_path: "{{ output_dir }}/cert.p12"
test_pkcs2_path: "{{ output_dir }}/cert2.p12"
```

I used keytool afterwards to read the resulted keystore without any issue I'm afraid

However, I saw one difference with your setup, which is "python version = 3.7.9".
