### ISSUE TITLE
github_repo always reports changed status

### ISSUE THREAD

**Issue by larsks** [ansible-collections/community.general#2376]
### Summary

When using the `github_repo` module to create a repository, the module always reports "changed" even when the repository already exists. Consider the following playbook:

```
- hosts: localhost
  gather_facts: false
  vars:
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
  tasks:
    - name: create repository
      community.general.github_repo:
          access_token: "{{ github_token }}"
          name: "ansible-sandbox"
          state: present
          organization: "oddbit-dot-com"
          private: false
```

Running it once produces:

```
TASK [create repository] *********************************************************************
changed: [localhost]
```

Running it one or more additional times reports:

```
TASK [create repository] *********************************************************************
changed: [localhost]
```

### Issue Type

Bug Report

### Component Name

github_repo

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.8
  config file = /home/lars/.ansible.cfg
  configured module search path = ['/home/lars/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lars/.local/lib/python3.9/site-packages/ansible
  executable location = /home/lars/.local/bin/ansible
  python version = 3.9.4 (default, Apr  6 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
COMMAND_WARNINGS(/home/lars/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/lars/.ansible.cfg) = False
```

### OS / Environment

Fedora 33

### Steps to Reproduce

(see the playbook in the description)

### Expected Results

I expect the module to report "ok" rather than "changed" if the named repository already exists.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
