### ISSUE TITLE
osx_defaults - Add dict support 

### ISSUE THREAD

**Issue by gschaetz** [ansible-collections/community.general#238]
##### SUMMARY

Looking to do this type of command with the module: 
defaults write com.apple.finder FXInfoPanesExpanded -dict \
  General -bool true \
  OpenWith -bool true \
  Privileges -bool true

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

osx_defaults.py

##### ADDITIONAL INFORMATION

Several of the defaults values are in a dictionary format

```yaml
- osx_defaults:
    domain: com.apple.finder
    key: FXInfoPanesExpanded
    type: dict
    value: 
         - {Key: General, type: bool, value: true}
         - {Key: Openwith, type: bool, value: true}
         - {Key: Privileges, type: bool, value: true}
    state: present
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/system/osx_defaults.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/osx_defaults.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @MorrisA @akasurde @bcoca @d-little @flynn1973 @gforster @kairoaraujo @kyleabenson @martinm82 @marvin-sinister @mator @molekuul @ramooncamacho @wtcross
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cfelder** [comment]
related: ansible/ansible#24808

**Comment by ChristinWhite** [comment]
It's a shame this has been an issue for so long and even had pull requests resolving the limitation. Will it ever be fixed? I have several common defaults that require dictionary values that I have to resort to a `defaults write` command and breaking idempotence until I figure out a better way to handle it.

**Comment by ansibullbot** [comment]
cc @!UNKNOWN @danieljaouen @indrajitr @notok
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
> Will it ever be fixed?

I guess it depends on whether someone is annoyed (or interested) enough to create a PR in this repository. I can help reviewing and also merge once ready, if someone wants to do the work.

**Comment by ChristinWhite** [comment]
Might be a good reason to finally pick up Python.

**Comment by aiotter** [comment]
I'm trying to fix this issue. I'm ready to create PR shortly.

**Comment by aiotter** [comment]
I found that the current implementation for reading current value from `defaults` output is hard to apply to dictionary.
It just read NeXTSTEP format and parse it with regex. It's easy for simple structure like array, but difficult for possibly nested dictionary.

https://github.com/ansible-collections/community.general/blob/e1cdad35373abfa3b32e37bd5bf17466dabe80c6/plugins/modules/system/osx_defaults.py#L248-L279

I need to find the other way than regex to parse the format properly. Otherwise the result will be always `changed`.
I'll create a PR. Please give me ideas on comments or send commits to it so that the module should work correctly.

**Comment by alteredtech** [comment]
Any update on this?

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/osx_defaults.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/osx_defaults.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by luixo** [comment]
I don't think this should be closed as I'd expect "dict support" to include settings dicts as well.
The unresolved problem is that I cannot set a dict value.

E.g.:
```
 - name: "Set dict task"
   osx_defaults:
     domain: "nevermind"
     key: "AnyKey"
     type: dict
     value:
       foo: bar
```

Result: `Task failed: Module failed: cannot user 'dict' as a set element (unhashable type: 'dict')`

**Comment by felixfontein** [comment]
@luixo that sounds like a bug in the implementation. Can you provide a stacktrace? See https://docs.ansible.com/projects/ansible/latest/reference_appendices/config.html#display-traceback for how to enable them.

@russoz ^

**Comment by russoz** [comment]
Will take a look in the next couple of days

**Comment by russoz** [comment]
Hi @luixo ,

The implementation added [this test](https://github.com/ansible-collections/community.general/blob/main/tests/integration/targets/osx_defaults/tasks/main.yml#L277-L285):

```yaml
- name: Write same dict value again, should not change
  osx_defaults:
    domain: com.ansible.fake_dict_value
    key: ExampleDictKey
    type: dict
    value:
      General: true
      OpenWith: true
  register: test_dict_write
```

which seems exactly like the case you reported. Could you please confirm you are using the updated version? You must use community.general 12.5.0 (or the `main` branch from git) for the `dict` support.
