### ISSUE TITLE
influxdb_retention_policy: add state argument to remove RPs

### ISSUE THREAD

**Issue by xabinapal** [ansible-collections/community.general#2383]
### Summary

`influxdb_retention_policy` module only supports creation of retention policies as it does not have an option to specify their state.

An `state` option with accepted `present` and `absent` values should be added to allow dropping existing retention policies.

### Issue Type

Feature Idea

### Component Name

influxdb_retention_policy

### Additional Information

`duration` and `replication` options are always required. If this new argument is added, they should be mandatory only if `state` is set as `present`.

```yaml (paste below)
- name: create retention policy
  community.general.influxdb_retention_policy:
      database_name: test
      policy_name: test
      duration: 1h
      replication: 1
      state: present

- name: drop retention policy
  community.general.influxdb_retention_policy:
      database_name: test
      policy_name: test
      state: absent
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
