### ISSUE TITLE
ali_instance_info - parameter marked deprecated in docs but not in code

### ISSUE THREAD

**Issue by russoz** [ansible-collections/community.general#2429]
### Summary

A couple of parameters are marked in the documentation as deprecated, for example:
```yaml
    availability_zone:
      description:
        - (Deprecated) Aliyun availability zone ID in which to launch the instance. Please use filter item 'zone_id' instead.
```
These deprecations were introduced in the documentation in https://github.com/ansible-collections/community.general/commit/4ebb65e6f6256e69ca772f23e543d2a4a06ec468 but there is no statement as to when they will be removed.

### Issue Type

Documentation Report

### Component Name

ali_instance_info

### Ansible Version

```console
ansible 2.10.8
  config file = None
  configured module search path = ['/home/az/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/az/.local/share/virtualenvs/russoz-ansible-collections__community.gene-m7xxMDta/lib/python3.8/site-packages/ansible
  executable location = /home/az/.local/share/virtualenvs/russoz-ansible-collections__community.gene-m7xxMDta/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### OS / Environment

Linux Mint

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
