### ISSUE TITLE
community.general.ipa_sudorule fails when cmdgroup is specified in the task.

### ISSUE THREAD

**Issue by ahambrick** [ansible-collections/community.general#2442]
### Summary

Multiple scenarios were tested:
- An empty list value for cmdgroup
- A single entry for cmdgroup
- A list for cmdgroup

All scenarios resulted in:
`msg": "response sudorule_add_allow_command_group: unknown command 'sudorule_add_allow_command_group` 

Once `cmdgroup` was removed from the task definition, ipa_sudorule then executes successfully.

### Issue Type

Bug Report

### Component Name

community.general.ipa_sudorule

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.18
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
# no changes
```

### OS / Environment

CentOS 7.9

### Steps to Reproduce

```yaml (paste below)
    - name: "PLAYBOOK:{{ playbook_name }}  ROLE:{{ ansible_role_name }}\tEnsure sudo rules are present"
      community.general.ipa_sudorule:
        name: "{{ item.key }}"
        hostcategory: all
        runasusercategory: all
        runasgroupcategory: all
        sudoopt: "{{ item.value.sudo_opts }}"
        usergroup:
          - privileged_users
        #cmdgroup: "{{ item.value.command_groups }}"
        #cmdgroup:
          #- hbase_commands
        ipa_user: admin
        ipa_pass: "xxxx"
        ipa_host: "ipa.test.net"
      loop: "{{ lookup('dict', ipa_sudo_rules) }}"

```

### Expected Results

Expected successful Ansible run with sudo rules defined in IPA with the specified sudo command groups as part of those sudo rules. 

### Actual Results

```console (paste below)
msg": "response sudorule_add_allow_command_group: unknown command 'sudorule_add_allow_command_group
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
