### ISSUE TITLE
ufw module fails when using loop

### ISSUE THREAD

**Issue by Kickimanjaro** [ansible-collections/community.general#2452]
### Summary

When I try to configure the firewall on my servers with the `ufw` module using a loop for each port and port range needed (commented nicely so I know what, why, and how) I receive an error indicating a file lock on xtables. This inconsistently appears when applying new rules with 3-4 ports, and constantly when applying 12 (like the provided playbook here). 

The example playbook has firewall rules that I need on my hosts for docker, docker swarm, gluster, and mongo. I usually run these all in their own role and this works for docker, and docker swarm, but starts to fail on the gluster rules.

I worked around this by adding a wait block before any ufw loops in my playbook (as they were usually only 1-4 ports needed).
```yaml
- name: wait a bit for that strange xtables lock thing...
  pause:
    seconds: 30
```

This still feels like a bug so I'm submitting it.

### Issue Type

Bug Report

### Component Name

ufw

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vollmero/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Target Hosts: `Ubuntu 20.04.2 LTS`
Control Host: `Fedora 31 (Server Edition)`
Target Host UFW version:
```
@sdl1:~$ ufw --version
ufw 0.36
Copyright 2008-2015 Canonical Ltd.
```

All machines are VMs running on `VMware ESXi, 6.5.0, 17477841` on AMD EPYC 7601 32-Core Processors. Network adapters on all VMs are `VMXNET 3`. The storage backing all these VMs is an HPE MSA 2050 hybrid flash storage array connected over 16Gbps fibre. 

I authenticate to the hosts using SSH key pair and sudo without password (`remote_user` has sudo). 

### Steps to Reproduce

ufw-bug.yaml
```yaml (paste below)
---
- hosts: docker_linux # I have three hosts in this group
  remote_user: "{{ remote_user }}"
  become: yes

  tasks:
  - name: open firewall for stuff (TCP)
    ufw:
      rule: allow
      direction: in
      proto: tcp
      port: "{{ item }}"
      comment: fun comment telling me which task created these rules
      state: enabled
      delete: no
    with_items:
    - '111' # NFS Port Mapper
    - '2375' # Docker Remote API unencrypted
    - '2376' # Docker Remote API encrypted w/ TLS
    - '2377' # Docker Swarm cluster management
    - '7946' # Docker Swarm intra-node communication
    - '24007' # Gluster Daemon
    - '24008' # Gluster Infiniband Management (optional)
    - '27017' # mongod/mongos
    - '27018' # mongod shard
    - '27019' # mongod config
    - '38465:38467' # Gluster inline NFS server
    - '49152:49251' # Gluster Data Brick Ports, one per brick
    notify: reload ufw
  - name: open firewall for stuff (UDP)
    ufw:
      rule: allow
      direction: in
      proto: udp
      port: "{{ item }}"
      comment: fun comment telling me which task created these rules
      state: enabled
      delete: no
    with_items:
    - '111' # NFS Port Mapper
    - '4789' # Docker Swarm overlay network traffic
    - '7946' # Docker Swarm intra-node communication
    notify: reload ufw
  - name: force all handlers to run if triggered
    meta: flush_handlers

  handlers:
  - name: reload ufw
    ufw:
      name: ufw
      state: reloaded
    become: yes

...
```
environments/ftc_dev_hosts.yaml
```yaml
---
all:
  children:
    docker_linux:
      hosts:
        sdl1.redacted.domain.net:
        sdl2.redacted.domain.net:
        sdl3.redacted.domain.net:
...
```

### Expected Results

I would expect the module to iterate through the list, checking if the rule exists or needs to be changed, and then changing it if needed. If there were locks, I would expect it to wait some reasonable amount of time, and then fail if the locks remain.

### Actual Results

```console (paste below)
$ git pull && ansible-playbook -i environments/ftc_dev_hosts.yaml ufw-bug.yaml 
Already up to date.

PLAY [docker_linux] ****************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [sdl2.redacted.domain.net]
ok: [sdl3.redacted.domain.net]
ok: [sdl1.redacted.domain.net]

TASK [open firewall for stuff (TCP)] ***********************************************************************************************************************************************************************
ok: [sdl2.redacted.domain.net] => (item=111)
ok: [sdl3.redacted.domain.net] => (item=111)
ok: [sdl1.redacted.domain.net] => (item=111)
failed: [sdl1.redacted.domain.net] (item=2375) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable"], "item": "2375", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
failed: [sdl1.redacted.domain.net] (item=2376) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable"], "item": "2376", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
ok: [sdl2.redacted.domain.net] => (item=2375)
ok: [sdl3.redacted.domain.net] => (item=2375)
ok: [sdl1.redacted.domain.net] => (item=2377)
failed: [sdl3.redacted.domain.net] (item=2376) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable", "/usr/sbin/ufw --version", "/usr/sbin/ufw allow in from any to any port 2376 proto tcp comment 'fun comment telling me which task created these rules'"], "item": "2376", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
ok: [sdl2.redacted.domain.net] => (item=2376)
failed: [sdl1.redacted.domain.net] (item=7946) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable", "/usr/sbin/ufw --version", "/usr/sbin/ufw allow in from any to any port 7946 proto tcp comment 'fun comment telling me which task created these rules'"], "item": "7946", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
ok: [sdl3.redacted.domain.net] => (item=2377)
ok: [sdl2.redacted.domain.net] => (item=2377)
ok: [sdl1.redacted.domain.net] => (item=24007)
ok: [sdl3.redacted.domain.net] => (item=7946)
ok: [sdl2.redacted.domain.net] => (item=7946)
ok: [sdl1.redacted.domain.net] => (item=24008)
ok: [sdl3.redacted.domain.net] => (item=24007)
ok: [sdl2.redacted.domain.net] => (item=24007)
ok: [sdl1.redacted.domain.net] => (item=27017)
ok: [sdl3.redacted.domain.net] => (item=24008)
ok: [sdl2.redacted.domain.net] => (item=24008)
ok: [sdl1.redacted.domain.net] => (item=27018)
ok: [sdl3.redacted.domain.net] => (item=27017)
failed: [sdl3.redacted.domain.net] (item=27018) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable"], "item": "27018", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
ok: [sdl2.redacted.domain.net] => (item=27017)
ok: [sdl1.redacted.domain.net] => (item=27019)
ok: [sdl3.redacted.domain.net] => (item=27019)
ok: [sdl2.redacted.domain.net] => (item=27018)
ok: [sdl1.redacted.domain.net] => (item=38465:38467)
failed: [sdl3.redacted.domain.net] (item=38465:38467) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable", "/usr/sbin/ufw --version", "/usr/sbin/ufw allow in from any to any port 38465:38467 proto tcp comment 'fun comment telling me which task created these rules'"], "item": "38465:38467", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
ok: [sdl2.redacted.domain.net] => (item=27019)
ok: [sdl1.redacted.domain.net] => (item=49152:49251)
ok: [sdl3.redacted.domain.net] => (item=49152:49251)
failed: [sdl2.redacted.domain.net] (item=38465:38467) => {"ansible_loop_var": "item", "changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw -f enable", "/usr/sbin/ufw --version", "/usr/sbin/ufw allow in from any to any port 38465:38467 proto tcp comment 'fun comment telling me which task created these rules'"], "item": "38465:38467", "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
ok: [sdl2.redacted.domain.net] => (item=49152:49251)

PLAY RECAP *************************************************************************************************************************************************************************************************
sdl1.redacted.domain.net : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
sdl2.redacted.domain.net : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
sdl3.redacted.domain.net : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
