### ISSUE TITLE
terraform 0.15.x breaks compatability with community.general.terraform

### ISSUE THREAD

**Issue by trondhindenes** [ansible-collections/community.general#2464]
### Summary

it looks like terraform 0.15.x makes some breaking changes to how command-line args are parsed which seems to affect Ansible.

From what I can see, Ansible runs `terraform validate -vars-file stuff.json` while terraform expects `terraform validate -vars-file=stuff.json`, so Ansible is missing the `=` sign between arg name and value, which seems to now be required.

Looking at the documentation for 0.14.x (one minor version back) it also seems to accept the `=` sign, so it might be as easy as adding that.

### Issue Type

Bug Report

### Component Name

community.general.terraform

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.9
  config file = None
  configured module search path = ['/home/trond/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
N/A
```

### Steps to Reproduce

```yaml (paste below)
  community.general.terraform:
    binary_path: /path/to/terraform_0_15_3
    project_path: "{{ role_path }}/tf/"
    state: "present"
    force_init: true
    variables_files: "{{ playbook_dir }}/temp/tfvars.json"
```

### Expected Results

It should apply

### Actual Results

```console (paste below)
flag provided but not defined: -var-file
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
