### ISSUE TITLE
Errors using json_query with contains

### ISSUE THREAD

**Issue by techBeck03** [ansible-collections/community.general#2468]
### Summary

I'm trying to use the `json_query` plugin to filter a json object but keep getting the same error message.  I've tried using the workaround mentioned in [#320](https://github.com/ansible-collections/community.general/issues/320) but still get the same error.

### Issue Type

Bug Report

### Component Name

`json_query`

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.9
  config file = None
  configured module search path = ['/Users/robbeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/robbeck/.pyenv/versions/3.9.4/envs/imm/lib/python3.9/site-packages/ansible
  executable location = /Users/robbeck/.pyenv/versions/imm/bin/ansible
  python version = 3.9.4 (default, Apr 14 2021, 15:37:58) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

MacOS BigSur 11.2.3

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vms: |
      {
        "vms": {
          "json": {
            "resources": [
              {
                "ips": [
                  "192.168.1.10",
                  "10.0.0.10"
                ],
                "name": "vm-001"
              },
              {
                "ips": [
                  "192.168.1.11",
                  "10.0.0.11"
                ],
                "name": "vm-002"
              },
              ...
            ]
          }
        }
      }
  tasks:
    - set_fact:
        my_vm: "{{ vms | to_json | from_json | json_query(query) }}"
        vars:
          query: "json.resources[?ips.contains(@, '192.168.1.11')].name"

    - debug: var=my_vm
```

### Expected Results

i should get an output containing` [“vm-002”]`

### Actual Results

```console (paste below)
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ****************************************************************************************************************************************

TASK [set_fact] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Error in jmespath.search in json_query filter plugin:\n'method' object is not iterable"}

PLAY RECAP **********************************************************************************************************************************************
localhost
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/filter/json_query.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/filter/json_query.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Ajpantuso** [comment]
I would check your indentation and query.

```yaml
   hosts: localhost
   vars:
     vms: {"vms": {"json": {"resources": [{"ips": ["192.168.1.10", "10.0.0.10"], "name": "vm-001"}, {"ips": ["192.168.1.11", "10.0.0.11"], "name": "vm-002"}]}}}
   tasks:
     - set_fact:
         my_vm: "{{ vms | json_query(query) }}" 
       vars: # vars should be at the same indentation as the task not the task options
         query: vms.json.resources[?ips.contains(@, `192.168.1.11`)].name # Note the top-level object 'vms' and the backticks around the literal value

     - debug:
         msg: "{{ my_vm }}"
```

Output:
```yaml
TASK [set_fact] *************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "vm-002"
    ]
}
```
