### ISSUE TITLE
Add ForwardAgent to community.general.ssh_config

### ISSUE THREAD

**Issue by MatthieuBizien** [ansible-collections/community.general#2473]
### Summary

I want to configure the ssh config on multiple servers using ansible.

Some of those servers should have `ForwardAgent yes`.

A setting for configuring it using Ansible would be very useful.

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

```yaml (paste below)
- name: configure .ssh/config for myserver
  community.general.ssh_config:
    user: "{{ ansible_user_id }}"
    host: "myserver"
    hostname: "127.0.0.1"
    identity_file: "~/.ssh/private_key"
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
