### ISSUE TITLE
Cloudflare CNAME Record Already Exists

### ISSUE THREAD

**Issue by natewiebe13** [ansible-collections/community.general#2496]
### Summary

When adding a CNAME record to Cloudflare, a 400 error message is received that the record already exists.

### Issue Type

Bug Report

### Component Name

cloudflare_dns

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```yaml
- name: Create CNAME record
  community.general.cloudflare_dns:
    zone: "domain.com"
    type: CNAME
    solo: yes
    ttl: 1
    proxied: no
    record: "*.dev.domain.com"
    value: "dev.domain.com"
    account_email: "{{ cf_email }}"
    account_api_key: "{{ cf_key }}"
    state: present
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml
- name: Create CNAME record
  community.general.cloudflare_dns:
    zone: "domain.com"
    type: CNAME
    solo: yes
    ttl: 1
    proxied: no
    record: "*.dev.domain.com"
    value: "dev.domain.com"
    account_email: "{{ cf_email }}"
    account_api_key: "{{ cf_key }}"
    state: present
```

### Expected Results

I would expect that using `state: present` would ensure that if the record already existed that it would ensure it's updated with the task details.

### Actual Results

```console
fatal: [localhost]: FAILED! => 
{
    "changed": false,
    "msg": "API bad request; Status: 400; Method: POST: Call: /zones/dc83a0836e4a98a2e7963d10c524978f/dns_records; Error details: code: 81054, error: A CNAME record with that host already exists.; "
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
