### ISSUE TITLE
datadog_monitor does not accept "process alert" monitor type anymore

### ISSUE THREAD

**Issue by asciifaceman** [ansible-collections/community.general#251]
##### SUMMARY
Datadog built-in module failing to deploy a "process alert" type which is a valid type of monitor.

This worked on ansible 2.6 as I referenced here: https://github.com/DataDog/ansible-datadog/issues/219 (I don't know how, but I have deployed several hundred of them)

I just updated to Ansible 2.9.7 and found the issue still.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`datadog_monitor`

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:27) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OSX 10.13.6
Python 3.7.7

##### STEPS TO REPRODUCE

```yaml
    - name: Deploy datadog monitor
      delegate_to: localhost
      register: datadogstatDeploy
      datadog_monitor:
        type: "process alert"
        thresholds:
          critical: 0
        name: "your alert name"
        state: "present"
        query: "your alert query"
        message: "your alert message"
        api_key: "{{ datadog.apiKey }}"
        app_key: "{{ datadog.appKey }}"
```

##### EXPECTED RESULTS

The process monitor to deploy.

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "msg": "value of type must be one of: metric alert, service check, event alert, got: process alert"}
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/monitoring/datadog/datadog_monitor.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/monitoring/datadog/datadog_monitor.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @skornehl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by asciifaceman** [comment]
It looks like this *may* be fixed in 2.10 but I can't find a reliable way to test this (nor a release date for 2.10 entering stable)

**Comment by asciifaceman** [comment]
Another one that was working previously:

```
 "msg": "value of type must be one of: metric alert, service check, event alert, got: log alert"}
```

**Comment by asciifaceman** [comment]
There is also "log alert" missing, ex. This also worked back on 2.6

```
- name: "Log alert"
  delegate_to: localhost
  datadog_monitor:
    type: "log alert"
    name: "Log Alert Name"
    state: "present"
    query: "logs(\"@envtype:prod @service_name:{{ service_name }} status:critical @http_status_code:504 @msg:\"check failed \"\").index(\"main\").rollup(\"count\").last(\"15m\") >= 2"
```
