### ISSUE TITLE
java_keystore: created file is in PKCS#12 format rather than expected JKS

### ISSUE THREAD

**Issue by quidame** [ansible-collections/community.general#2515]
### Summary

Depending on the version of Java, the `keytool` command that creates the java keystore from a PKCS#12 bundle (certificate + private key) may or may not need explicit `-deststoretype jks`. Without these arguments, the command may create a `PKCS#12` file rather than the expected `JKS`. Also note that most Java application servers accept PKCS#12 keystores, that makes easy to never notice that the file is not a JKS.

### Issue Type

Bug Report

### Component Name

java_keystore

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.9
  config file = /home/quidame/github.com/ansible.cfg
  configured module search path = ['/home/quidame/github.com/library']
  ansible python module location = /home/quidame/.venvs/py3/lib/python3.7/site-packages/ansible
  executable location = /home/quidame/.venvs/py3/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/home/quidame/github.com/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/quidame/github.com/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/quidame/github.com/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ProxyCommand=none -o UserKnownHostsFile=ssh_known_hosts -q
DEFAULT_ACTION_PLUGIN_PATH(/home/quidame/github.com/ansible.cfg) = ['/home/quidame/github.com/action_plugins']
DEFAULT_CALLBACK_WHITELIST(/home/quidame/github.com/ansible.cfg) = ['profile_roles']
DEFAULT_FILTER_PLUGIN_PATH(/home/quidame/github.com/ansible.cfg) = ['/home/quidame/github.com/filter_plugins']
DEFAULT_FORKS(/home/quidame/github.com/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/quidame/github.com/ansible.cfg) = ['/home/quidame/github.com/hosts']
DEFAULT_MODULE_PATH(/home/quidame/github.com/ansible.cfg) = ['/home/quidame/github.com/library']
DEFAULT_ROLES_PATH(/home/quidame/github.com/ansible.cfg) = ['/home/quidame/github.com/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/quidame/github.com/ansible.cfg) = /home/quidame/github.com/vault_password
HOST_KEY_CHECKING(/home/quidame/github.com/ansible.cfg) = True
INTERPRETER_PYTHON(/home/quidame/github.com/ansible.cfg) = auto_legacy_silent
```

### OS / Environment

Debian 10/11, CentOS 7/8 (or any OS running OpenJDK 11)

### Steps to Reproduce

- Install OpenJDK 11 on the targets (if possible, otherwise the latest available version)
- Create a private key and x509 certificate and copy them on the targets
- Run this playbook (in my case test1 is Debian 11, test4 is CentOS 7, test5 is CentOS 8, test6 is FreeBSD 12) :

```yaml
---
- name: TEST MODULE java_keystore
  hosts: test1:test4:test5:test6
  gather_facts: no
  vars:
    certificate: /tmp/ssl-cert-snakeoil.pem
    private_key: /tmp/ssl-cert-snakeoil.key
    keystore: /tmp/ssl-cert-snakeoil.jks
    password: /f00b4R-Baz!
    alias: snakeoil
  tasks:
    - name: Remove JKS
      file:
        path: "{{ keystore }}"
        state: absent

    - name: Create JKS
      java_keystore:
        dest: "{{ keystore }}"
        name: "{{ alias }}"
        certificate_path: "{{ certificate }}"
        private_key_path: "{{ private_key }}"
        password: "{{ password }}"

    - name: Get results
      command:
        cmd: "keytool -list -keystore {{ keystore }}"
        stdin: "{{ password }}"
      register: keystore_info
      environment:
        LC_MESSAGES: C

    - name: Show keystore format
      debug:
        var: keystore_info.stdout_lines[0]
```

### Expected Results

Result of last task should be `Keystore type: jks` or `Keystore type: JKS` everywhere, like:

```
TASK [Show keystore format] ************************************
ok: [test1] => {
    "keystore_info.stdout_lines[0]": "Keystore type: JKS"
}
ok: [test4] => {
    "keystore_info.stdout_lines[0]": "Keystore type: jks"
}
ok: [test5] => {
    "keystore_info.stdout_lines[0]": "Keystore type: jks"
}
ok: [test6] => {
    "keystore_info.stdout_lines[0]": "Keystore type: JKS"
}

```

### Actual Results

```console (paste below)
TASK [Show keystore format] ******************************************
ok: [test1] => {
    "keystore_info.stdout_lines[0]": "Keystore type: PKCS12"
}
ok: [test4] => {
    "keystore_info.stdout_lines[0]": "Keystore type: PKCS12"
}
ok: [test5] => {
    "keystore_info.stdout_lines[0]": "Keystore type: PKCS12"
}
ok: [test6] => {
    "keystore_info.stdout_lines[0]": "Keystore type: JKS"
}
```

The add of the explicit option `-deststoretype JKS` to create the keystore solves the issue.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
