### ISSUE TITLE
Add option to allow repository metadata to be unsigned

### ISSUE THREAD

**Issue by PrimaryCanary** [ansible-collections/community.general#2519]
### Summary

RPM repositories can optionally sign the repository metadata (`repomd.txt`). The `zypper_repository` module's inability to disable metadata signing makes it difficult to add repos that don't sign their metadata. While this can be worked around by disabling `gpgcheck`, doing so is ill-advised.

### Issue Type

Feature Idea

### Component Name

zypper_repository

### Additional Information

Zypper supports skipping the metadata signing check with `zypper addrepo --gpgcheck-allow-unsigned-repo ....`. This is more secure than `zypper addrepo --no-gpgcheck ....` because individual packages are still verified. The Ansible's builtin `yum_repository` module supports this use case with its `repo_gpgcheck` parameter.

I propose two solutions:
1. Adding a `repo_gpgcheck` parameter like that found in `yum_repository`.
2. Adding an `extra_args` parameter like that found in the `zypper` module.

I'm willing to implement one or both of these solutions. Which would you prefer?
```yaml (paste below)
- name: Add ZeroTier repo for SUSE/openSUSE
  community.general.zypper_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    repo: https://download.zerotier.com/redhat/el/8/
    gpgcheck: yes
    repo_gpgcheck: no
    state: present

- name: Add ZeroTier repo for SUSE/openSUSE
  community.general.zypper_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    repo: https://download.zerotier.com/redhat/el/8/
    gpgcheck: yes
    extra_args: "--gpgcheck-allow-unsigned-repo"
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/packaging/os/zypper.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/packaging/os/zypper.py)
* [`plugins/modules/packaging/os/zypper_repository.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/packaging/os/zypper_repository.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @AnderEnder @alxgu @andytom @commel @dcermak @evrardjp @lrupp @matze @sealor @toabctl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
I'm against adding something general like `extra_args`. Having a specific parameter for this makes more sense IMO.

**Comment by sealor** [comment]
@felixfontein @PrimaryCanary 
I agree that adding `extra_args` is too general. I'm fine with a new parameter.

What do you think about adding a parameter for `--no-gpgcheck` and `--gpgcheck-allow-unsigned-repo`?
This approach allows us to use the most secure way which is available.

How do we want to name the new parameters? `gpgcheck: no` and `gpgcheck_allow_unsigned_repo: yes`?
IMHO we do not need the `repo_` prefix here which is used in the `yum` configuration.

```yml
- name: Add ZeroTier repo for SUSE/openSUSE
  community.general.zypper_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    repo: https://download.zerotier.com/redhat/el/8/
    gpgcheck: no
    state: present

- name: Add ZeroTier repo for SUSE/openSUSE
  community.general.zypper_repository:
    name: zerotier
    description: ZeroTier, Inc. RPM Release Repository
    repo: https://download.zerotier.com/redhat/el/8/
    gpgcheck_allow_unsigned_repo: yes
    state: present
```
Useful links:
[Zypper manual](https://en.opensuse.org/SDB:Zypper_manual)
[man yum.conf](https://man7.org/linux/man-pages/man5/yum.conf.5.html)
