### ISSUE TITLE
docker_stack. fatal: [test]: failed! no such file or directory

### ISSUE THREAD

**Issue by ambazasador** [ansible-collections/community.general#253]
##### SUMMARY
Hi everyone! I tried to use docker_stack module but received error. where i did mistake ?
##### ISSUE TYPE
- issue

##### COMPONENT NAME
docker_stack

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/q/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

```
##### CONFIGURATION
```
ansible-config dump --only-changed

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```
pyyaml and jsondiff installed on host and remote server
```
root@q-VirtualBox:~/test-play# cat /etc/ansible/ansible.cfg
[defaults]
#remote_tmp = $HOME/.ansible/tmp
#local_tmp = $HOME/.ansible/tmp
host_key_checking = false
```

root@q-VirtualBox:~/test-play# cat comp.yaml
```
---
- name: deploy
  hosts: IG
  gather_facts: false
  become_user: root
  tasks:
    - name: Deploy stack
      docker_stack:
        state: present
        name: test
        compose:
          - version: '3.6'
            services:
              hello_world:
                image: ubuntu
                command: [/bin/echo, 'Hello world']

```

##### OS / ENVIRONMENT
ubuntu 18.04

##### STEPS TO REPRODUCE
ansible-playbook -i hosts comp.yaml

or

ansible-playbook -i hosts comp.yaml -e "ansible_python_interpreter=/usr/bin/python3"

##### EXPECTED RESULTS
Works fine

##### ACTUAL RESULTS
Fall
`fatal: [test]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "err": "open /tmp/tmpgwwymchn: no such file or directory\n", "msg": "docker stack up deploy command failed", "out": "", "rc": 1, "stderr": "open /tmp/tmpgwwymchn: no such file or directory\n", "stderr_lines": ["open /tmp/tmpgwwymchn: no such file or directory"], "stdout": "", "stdout_lines": []}`

```
