### ISSUE TITLE
yum_versionlock does not work on Fedora 34

### ISSUE THREAD

**Issue by aminvakil** [ansible-collections/community.general#2539]
### Summary

There has been several CI tests (nightly and PR) failing, because of this module integration test which didn't lock packages.

https://dev.azure.com/ansible/community.general/_build/results?buildId=15172&view=logs&j=3f683100-4eb3-5543-aafd-5a8f78237a65&t=eaabe179-f774-5877-fd69-78bb20f95bac

### Issue Type

Bug Report

### Component Name

yum_versionlock

### Ansible Version

```console (paste below)
2.12.0.dev0
```

### OS / Environment

Fedora 34 target

### Steps to Reproduce

```
- block:
    - name: Install necessary packages to test yum_versionlock
      yum:
        name: yum-plugin-versionlock
        state: present
      register: yum_versionlock_install

    - name: Yum checkupdate
      yum:
        list: updates
      register: yum_updates

    - block:
        - name: Lock all packages
          community.general.yum_versionlock:
            name: "{{ yum_updates.results | map(attribute='name') | list }}"
            state: present
          register: lock_all_packages

          # This should fail when it needs user interaction and missing -y is on purpose.
        - name: Update all packages (not really)
          command: yum update --setopt=obsoletes=0
          register: update_all_locked_packages
          changed_when:
            - '"No packages marked for update" not in update_all_locked_packages.stdout'
            - '"Nothing to do" not in update_all_locked_packages.stdout'

        - name: Unlock all packages
          community.general.yum_versionlock:
            name: "{{ yum_updates.results | map(attribute='name') | list }}"
            state: absent
          register: unlock_all_packages

        - name: Update all packages
          yum:
            name: '*'
            state: latest
          check_mode: yes
          register: update_all_packages
          when: yum_updates.results | length != 0

        - name: Assert everything is fine
          assert:
            that:
              - "{{ lock_all_packages.changed }}"
              - "{{ not update_all_locked_packages.changed }}"
              - "{{ unlock_all_packages.changed }}"
              - "{{ update_all_packages.changed }}"
      when: yum_updates.results | length != 0

    - name: Remove installed packages in case it was not installed
      yum:
        name: yum-plugin-versionlock
        state: absent
      when: yum_versionlock_install is changed
```

### Expected Results

Lock packages, and passing `assert` task.

### Actual Results

https://dev.azure.com/ansible/community.general/_build/results?buildId=15172&view=logs&j=3f683100-4eb3-5543-aafd-5a8f78237a65&t=eaabe179-f774-5877-fd69-78bb20f95bac

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
