### ISSUE TITLE
Document setting PYTHONHTTPSVERIFY to 0 for disabling SSL validation in the jenkins_job module

### ISSUE THREAD

**Issue by gustavomcarmo** [ansible-collections/community.general#255]
##### SUMMARY
Once the jenkins_job module does not have the validate_certs parameter to set to false for disabling the validation of an eventual self-signed certificate of the Jenkins instance, please document that as a workaround the environment variable [PYTHONHTTPSVERIFY can be set to 0](https://opendev.org/jjb/python-jenkins/src/branch/master/jenkins/__init__.py#L345) so the behaviour of the task will be the same.

```yaml
- name: Config the job
  jenkins_job:
    config: "{{ lookup('file', 'job-config.xml') }}"
    name: myjob
    url: "{{ url }}"
    user: "{{ username }}"
    password: "{{ password }}"
  environment:
    PYTHONHTTPSVERIFY: 0
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
jenkins_job

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = None
  configured module search path = ['/home/gustavomcarmo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gustavomcarmo/.local/lib/python3.6/site-packages/ansible
  executable location = /home/gustavomcarmo/.local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```
