### ISSUE TITLE
Instead of adding a new host into the ssh config, existing host gets updated

### ISSUE THREAD

**Issue by drenout** [ansible-collections/community.general#2567]
### Summary

While using the `community.general.ssh_config` plugin, if new host hame is the part of the already existed host (not fully matched, but the existing host name contains the new host name), then new host is not added to the config, but existing one gets updated with the new config. 

### Issue Type

Bug Report

### Component Name

`community.general.ssh_config` plugin

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.2
  config file = ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/venvs/ansible/lib/python3.8/site-packages/ansible
  executable location = ~/venvs/ansible/bin/ansible
  python version = 3.8.6 (default, Oct  9 2020, 06:03:53) [Clang 10.0.1 (clang-1001.0.46.3)]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_BECOME(~/ansible.cfg) = False
DEFAULT_BECOME_ASK_PASS(~/ansible.cfg) = False
DEFAULT_BECOME_METHOD(~/ansible.cfg) = sudo
DEFAULT_BECOME_USER(~/ansible.cfg) = root
DEFAULT_FORKS(~/ansible.cfg) = 20
DEFAULT_HOST_LIST(~/ansible.cfg) = ['~/inventory']
DEFAULT_REMOTE_USER(~/ansible.cfg) = user
HOST_KEY_CHECKING(~/ansible.cfg) = False
INTERPRETER_PYTHON(~/ansible.cfg) = /usr/bin/python
```

### OS / Environment

ProductName:    Mac OS X
ProductVersion: 10.14.6

### Steps to Reproduce

Run the next playbook:

```yaml (paste below)
- name: Set up ssh config
  hosts: all
  vars:
    config:
      - host: host_prod_west
        hostname: host_prod_west.com
        identity_file: /Users/user/.ssh/west-private-key
      - host: host_prod
        hostname: host_prod.com
        identity_file: /Users/user/.ssh/new-private-key
  tasks:
    - name: Add a hosts
      community.general.ssh_config:
        group: staff
        user: "{{ ansible_user }}"
        host: "{{ item.host }}"
        hostname: "{{ item.hostname }}"
        identity_file: "{{ item.identity_file }}"
        state: present
      loop: "{{config}}"
```

### Expected Results

I expected to get the next config file:

```console
Host host_prod_west
    identityfile /Users/user/.ssh/west-private-key
    hostname host_prod_west.com

Host host_prod
    identityfile /Users/user/.ssh/new-private-key
    hostname host_prod.com
```

### Actual Results

Instead of adding a new host, the first host got updated with new 

```console (paste below)
Host host_prod_west
    identityfile /Users/user/.ssh/new-private-key
    hostname host_prod.com
```

Ansible output logs:
```console
changed: [managed.node] => (item={'host': 'host_prod_west', 'hostname': 'host_prod_west.com', 'identity_file': '/Users/user/.ssh/west-private-key'}) => {"ansible_loop_var": "item", "changed": true, "hosts_added": ["host_prod_west"], "hosts_change_diff": [], "hosts_changed": [], "hosts_removed": [], "item": {"host": "host_prod_west", "hostname": "host_prod_west.com", "identity_file": "/Users/user/.ssh/west-private-key"}}
changed: [managed.node] => (item={'host': 'host_prod', 'hostname': 'host_prod.com', 'identity_file': '/Users/user/.ssh/new-private-key'}) => {"ansible_loop_var": "item", "changed": true, "hosts_added": [], "hosts_change_diff": [{"host_prod_west": {"new": {"hostname": "host_prod.com", "identityfile": "/Users/user/.ssh/new-private-key"}, "old": {"hostname": "host_prod.com", "identityfile": "/Users/user/.ssh/new-private-key"}}}], "hosts_changed": ["host_prod_west"], "hosts_removed": [], "item": {"host": "host_prod", "hostname": "host_prod.com", "identity_file": "/Users/user/.ssh/new-private-key"}}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
