### ISSUE TITLE
Archive module creates compressed tarball containing a compressed tarball greatly inflating archive size

### ISSUE THREAD

**Issue by UntouchedWagons** [ansible-collections/community.general#2587]
### Summary

I'm trying to automate backups of my docker stacks but for some reason the archive module creates a compressed tarball containing another compressed tarball greatly inflating archive size

### Issue Type

Bug Report

### Component Name

archive

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.7
  config file = /home/jordan/ansible/ansible.cfg
  configured module search path = ['/home/jordan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jordan/.local/lib/python3.8/site-packages/ansible
  executable location = /home/jordan/.local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/jordan/ansible/ansible.cfg) = ['/home/jordan/ansible/inventory']
DEFAULT_PRIVATE_KEY_FILE(/home/jordan/ansible/ansible.cfg) = /home/jordan/.ssh/id_ed25519
DEPRECATION_WARNINGS(/home/jordan/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 20.04 in WSL2

### Steps to Reproduce

```yaml (paste below)
---

- hosts: docker
  become: false
  tasks:

  - name: Compress directory /mnt/docker/ into /mnt/data/Backups/VM-Docker/Docker-{{ '%Y-%m-%d' | strftime }}.tgz
    community.general.archive:
      path: /mnt/docker
      dest: /mnt/data/Backups/VM-Docker/Docker-{{ '%Y-%m-%d' | strftime }}.tgz
```

### Expected Results

I expected the created archive to directly contain the files and folders in /mnt/docker

### Actual Results

```console (paste below)
PLAY [docker] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [docker]

TASK [Compress directory /mnt/docker/ into /mnt/data/Backups/VM-Docker/Docker-2021-05-22.tgz] ****************************************************************************************************************
changed: [docker]

PLAY RECAP ***************************************************************************************************************************************************************************************************
docker                     : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Here is a picture of the created archive https://cdn.discordapp.com/attachments/549021192363835403/845012648805531648/7zFM_WGUrPUTugb.png 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/files/archive.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/files/archive.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bendoh
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by UntouchedWagons** [comment]
The exclude_path directive is ignored.

```
  - name: Compress directory /mnt/docker/ into /mnt/data/Backups/VM-Docker/Docker-{{ '%Y-%m-%d' | strftime }}.tgz
    community.general.archive:
      path: /mnt/docker
      dest: /mnt/data/Backups/VM-Docker/Docker-{{ '%Y-%m-%d' | strftime }}.tgz
      exclude_path:
      - /mnt/docker/multimedia/appdata/lidarr/MediaCover
```

The excluded folder is still included in the wrapped archive

**Comment by felixfontein** [comment]
@UntouchedWagons is that a second example a different problem, or was your first example incomplete?

Please note that the documentation of `exclude_path` says "Remote absolute path, glob, or list of paths or globs for the **file or files** to exclude from I(path) list and glob expansion." (emphasis mine).

**Comment by UntouchedWagons** [comment]
It's a second example, if I can't exclude folders (which is a reasonable expectation) then it can be ignored for now.

**Comment by Ajpantuso** [comment]
> @UntouchedWagons is that a second example a different problem, or was your first example incomplete?
> 
> Please note that the documentation of `exclude_path` says "Remote absolute path, glob, or list of paths or globs for the **file or files** to exclude from I(path) list and glob expansion." (emphasis mine).

The emphasis is really on the predicate, _to exclude from I(path) list and glob expansion_, you cannot exclude nested files/directories within a path only a top-level archive path.
From the module examples
```yaml
- name: Create a bz2 archive of a globbed path, while excluding specific dirnames 
  community.general.archive:    
  path:
    - /path/to/foo/*    
  dest: /path/file.tar.bz2    
  exclude_path:    
    - /path/to/foo/bar    
    - /path/to/foo/baz    
  format: bz2
```
@UntouchedWagons can you maybe give a `tar -tf` showing the compressed tar within the outer `tgz` file? (Doesn't have to be your real data if you can reproduce with a comparable example)

I could only see the potential for this if there was a self-reference shared between source and destination, but your example should avoid any such issues.
