### ISSUE TITLE
Add systemd_escape algorithm as Jinja2 filter

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.general#2601]
_From @Zocker1999NET on May 10, 2020 17:14_

##### SUMMARY

Add a Jinja2 filter allowing to escape strings following the [systemd escape algorithm](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#String%20Escaping%20for%20Inclusion%20in%20Unit%20Names). Then the user would not require to mimic the escaping by combining other existing filters because the full implementation is not trivial.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

filters

##### ADDITIONAL INFORMATION

The usage is shown below. It allows to use the algorithm without implementing a mimic itself using other existing filters. For example the path escaping is required to generate the name a `.mount` must have for systemd to work (see [here](https://www.freedesktop.org/software/systemd/man/systemd.mount.html#Description)).

```yaml
escaped_name: {{ service_name | systemd_escape }} # For unit names for example
mount_name: {{ mount_path | systemd_escape(path=True) }} # For absolute paths (special behavior for path separator
# Example escaping
test_result: {{ ("/media/user/drive" | systemd_escape(path=True)) == "media-user-drive" }} # Should be True
```

_Copied from original issue: ansible/ansible#69415_
