### ISSUE TITLE
Allow to specify path of composer binary

### ISSUE THREAD

**Issue by hostep** [ansible-collections/community.general#2649]
### Summary

Hi!

I'm currently trying to implement some deployment scripts using Ansible for some PHP projects.
I'm currently trying to setup the `composer install` step, but I keep running into a problem when trying to deploy 2 different PHP projects on the same server where one project needs composer v1 and another composer v2 (both composer versions should theoretically be able to work on the same `composer.lock` file, but can conflict when composer plugins are build specifically only for v1 or v2, and that's where we have problems with).

We solve this by shipping the `composer.phar` file in our git repositories and always use those.

However, if I'm trying to automate this using Ansible, I run into the problem that the Ansible composer module always fetches the composer binary from `/usr/local/bin`. We have composer v1 installed in there by our hosting company, but would need composer v2 for a second project on the same server.

I already tried changing the `PATH` environment variable to point it to a directory in our project where a `composer` binary exists, but for some reason, Ansible keeps prepending `/usr/local/bin` in front of my own path, so it still finds the composer v1 binary that is installed by our hosting company.

The solution I would propose is that it should be possible to configure the composer executable in our Ansible playbooks. When that option is defined it should be used, otherwise, the old behavior can be used.
So this proposed solution is similar to the `executable` option where you can override the php binary to be used.

Does this sounds like a valid request?

Thanks for considering this! 🙂 

### Issue Type

Feature Idea

### Component Name

composer
code reference: https://github.com/ansible-collections/community.general/blob/909e9fe9508804b2e18b755ef36060861cde5228/plugins/modules/packaging/language/composer.py#L190

### Additional Information

```yaml
- name: Install composer dependencies
  community.general.composer:
    composer_binary: '{{ deploy_path }}/tools/composer.phar'
    command: 'install'
    no_dev: yes
    optimize_autoloader: yes
    prefer_dist: yes
    working_dir: '{{ deploy_path }}'
```

The `composer_binary` option would be a solution for this issue.
Feel free to pick another name if this doesn't fit your naming conventions.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
