### ISSUE TITLE
open_iscsi login multiple selective portals of same target

### ISSUE THREAD

**Issue by thebinary** [ansible-collections/community.general#2683]
### Summary

I am trying to login to multiple portals of same target. 
For eg: 
target = 2021-05.org.example:target1
portals = 10.10.10.1:3260 and 10.10.11.1:3260 (multiple network paths)

But I am not being able to since 'portal' argument is single string, so I cannot specify multiple portals. 

Also, I cannot do so using 2 tasks each for different portals, since the module checks if target is logged in or not instead of portal session.
```yaml
    - name: iscsi target1 portal1
      community.general.open_iscsi:
        portal: '10.10.10.1'
        port: '3260'
        target: '2021-05.org.example:target1'
        auto_node_startup: yes
        login: yes
        discover: yes

    - name: iscsi target1 portal2
      community.general.open_iscsi:
        portal: '10.10.11.1'
        port: '3260'
        target: '2021-05.org.example:target1'
        auto_node_startup: yes
        login: yes
        discover: no
```

The second task is tagged as unchanged by ansible and portal login does not occur.

### Issue Type

Feature Idea

### Component Name

open_iscsi

### Additional Information

```yaml (paste below)
    - name: iscsi target1 portal1
      community.general.open_iscsi:
        discover: yes
        portal: '10.10.10.1'
        port: '3260'
        target: '2021-05.org.example:target1'
        auto_node_startup: yes
        login: yes

    - name: iscsi target1 portal2
      community.general.open_iscsi:
        discover: no
        portal: '10.10.11.1'
        port: '3260'
        target: '2021-05.org.example:target1'
        auto_node_startup: yes
        login: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
