### ISSUE TITLE
ini_file: Incorrect handling when multiple options with the same name exist

### ISSUE THREAD

**Issue by C0rn3j** [ansible-collections/community.general#273]
##### SUMMARY
Option handling is inconsistent when there's multiple of them and there is seemingly no way to keep multiple options.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ini_file

##### ANSIBLE VERSION
```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
```

##### CONFIGURATION
```
N/A
```

##### OS / ENVIRONMENT
Arch Linux

##### STEPS TO REPRODUCE
Play:
```
- name: Ensure "Include=/etc/pacman.d/mirrorlist is in section "[multilib]" in specified file
  ini_file:
    path: /etc/pacman.conf
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist
```

How the file /etc/pacman.conf looks before the play:
```
[multilib]
Include = /etc/pacman.d/pacserve
Include = /etc/pacman.d/mirrorlist
```
After:

```
[multilib]
Include = /etc/pacman.d/mirrorlist
```

I'd like the play not to clobber existing Options, but there does not seem to be a way to do that.

Additionally, if the file looks like this, with the matching entry first, nothing is changed, which is inconsistent.

```
[multilib]
Include = /etc/pacman.d/mirrorlist
Include = /etc/pacman.d/pacserve
```
