### ISSUE TITLE
nmcli: add ipv4.routing-rules, ipv4.may-fail options and disabled to method6

### ISSUE THREAD

**Issue by omula** [ansible-collections/community.general#2730]
### Summary

I am trying to configure our network setup which is possible with nmcli command line but there are some missing options in the ansible collections which prevents us from using it. Adding this options will extend the possible configuration that the collection can do and get closer to nmcli command capabilities.

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

This type of configuration is for example used for Lustre and Multi-Rail environments.
https://wiki.lustre.org/LNet_Router_Config_Guide#ARP_flux_issue_for_MR_node
```
nmcli c add type infiniband con-name ib0 \
  ifname ib0 infiniband.mtu 2044 ipv4.method manual \
  ipv4.may-fail false ipv4.addresses 10.0.0.3/16 \
  ipv4.route-metric 0 ipv4.routes "10.0.0.0/16 src=10.0.0.3 table=200" \
  ipv4.routing-rules "priority 0 from 10.0.0.3 lookup 200" \
  ipv6.method disabled connection.zone internal
```

```yaml (paste below)
vars:
  infiniband_interfaces:
    - device: ib0
      type: infiniband
      ip4: 10.0.0.3/16
      mtu: 2044
      route_table: 200
      may_fail4: false

tasks:
  - name: "Configure IB MR interface"
    community.general.nmcli:
       conn_name: "{{ item.device }}"
       ifname: "{{ item.device }}"
       type: "{{ item.type }}"
       ip4: "{{ item.ip4 }}"
       mtu: "{{ item.mtu }}"
       method4: manual
       method6: disabled
       routes4: "{{ item.ip4 | ipaddr('network') }}/{{ item.ip4 | ipaddr('prefix') }} src={{ item.ip4 | ipaddr('address') }} table={{ item.route_table }}"
       route_metric4: 0
       routing_rules4: "priority 0 from {{ item.ip4 | ipaddr('address') }} lookup {{ item.route_table }}"
       may_fail4: false
       state: present

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
