### ISSUE TITLE
ImportError: No module named jenkins

### ISSUE THREAD

**Issue by ernestk86** [ansible-collections/community.general#2764]
### Summary

I am trying to manage a jenkins job using an Ansible playbook and plugin community.general.jenkins_job. When I run the playbook I get the error message:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named jenkins
[WARNING]: Platform linux on host 18.223.113.29 is using the discovered Python interpreter at /usr/bin/python, but
future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [18.223.113.29]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Failed to import the required Python library (python-jenkins) on ip-172-31-39-230.us-east-2.compute.internal's Python /usr/bin/python. See https://python-jenkins.readthedocs.io/en/latest/install.html for more info. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

I installed the community.general collection with: ansible-galaxy collection install community.general
My version of python-jenkins is 1.7.0

### Issue Type

Bug Report

### Component Name

jenkins_job

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/erniek86/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
---
- name: Create Jenkins Job
  hosts: vgrbackend
  gather_facts: false
  become: true
  tasks:
    - name: Create a jenkins job using basic authentication
      community.general.jenkins_job:
        config: "{{ lookup('file', '/home/erniek86/jenkins/vgr-backend CICD/config.xml') }}"
        name: "Test Job"
        password: "admin"
        url: "http://ec2-18-223-113-29.us-east-2.compute.amazonaws.com:8080"
        user: "admin"
        state: "absent"
```

### Expected Results

I wanted a new jenkins job named "Test Job" to be created with the config.xml file provided

### Actual Results

```console (paste below)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named jenkins
[WARNING]: Platform linux on host 18.223.113.29 is using the discovered Python interpreter at /usr/bin/python, but
future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [18.223.113.29]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Failed to import the required Python library (python-jenkins) on ip-172-31-39-230.us-east-2.compute.internal's Python /usr/bin/python. See https://python-jenkins.readthedocs.io/en/latest/install.html for more info. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Ajpantuso** [comment]
Have you tried:
- running `/usr/bin/python -m pip list` on that target host to see if `python-jenkins` is available to that interpreter?
- Adding a preceding task to ensure `python-jenkins` is installed?
example:
```yaml
- name: Ensure ``python-jenkins`` is installed
  ansible.builtin.pip:
    name: python-jenkins
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/web_infrastructure/jenkins_job.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/web_infrastructure/jenkins_job.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @nerzhul @sermilrod
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by russoz** [comment]
@ernestk86 Could you please confirm if @Ajpantuso suggestions helped you? So far this looks like a work-as-expected situation, but it would be nice to have the confirmation so we can close the issue (or not if there's something else going on).

**Comment by ernestk86** [comment]
Sure!

Yes @Ajpantuso your suggestion helped. To fix the issue I had to add the following code before mine to get it to work. My confusion came from the fact that I had python-jenkins installed on my machine. To get the Ansible task to work I had to ensure that python-jenkins was installed in the host machine, which in this case is different from my local.

```
    - name: Install Pip2
      yum:
        name: pip
    
    - name: Ensure python-jenkins is installed
      pip:
        executable: /usr/bin/pip
        name: python-jenkins
```
