### ISSUE TITLE
Module datadog_event API endpoint definition 

### ISSUE THREAD

**Issue by Anas-Hamadeh** [ansible-collections/community.general#2774]
### Summary

I'm trying to define an API endpoint for the datadog_event module to send data to. By default, it sends to api.datadog.com which is not necessarily always the case. 
It would be helpful if we have that as an optional parameter to pass to the module in order for the events to reach the right location. The current workaround is to hardcode the API endpoint into the datadog python library which is not optimal and future proof
The change mainly would target ``plugins/modules/monitoring/datadog/datadog_event.py``

### Pull Request

#2775 

### Issue Type

Feature Idea

### Component Name

datadog_event ansible module
plugins/modules/monitoring/datadog/datadog_event.py

### Additional Information

```yaml (paste below)
  - name: datadog_test
    community.general.datadog_event:
      title: Test
      text: This is just a test
      priority: low
      tags: '#group:heros'
      api_host: 'URL'
      api_key: KEY
      app_key: KEY
```
The addition of `api_host` will allow users to define a datadog API endpoint instead of using the default one as not all datadog deployments target the default URL

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
