### ISSUE TITLE
The archive module 

### ISSUE THREAD

**Issue by anappi-vc** [ansible-collections/community.general#2818]
### Summary

When I try to archive a single file as a .zip file using the archive module, it creates the zip file with the correct name but the file itself inside the archive is missing the first letter. I tested this on the latest release as well as the devel branch.

For example, if I archive `message.txt`, the name of the zip file is `message.txt.zip` (which is correct) but the file inside is named `essage.txt` (missing the first letter `m`).

### Issue Type

Bug Report

### Component Name

archive

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.1] 
  config file = None
  configured module search path = ['/home/anappi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/anappi/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/anappi/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/anappi/.local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### OS / Environment

Ubuntu 20.04.2 LTS running under Windows Subsytem for Linux (5.4.72-microsoft-standard-WSL2) under Windows 10

### Steps to Reproduce

Playbook:
```yaml (paste below)
- name: Testing the archive module
  hosts: localhost

  tasks:
    - name: Archive file
      community.general.archive:
        path: message.txt
        format: zip
    - name: List contents of message.txt.zip
      shell: unzip -l message.txt.zip
      register: output
    - debug:
        msg: "{{ output.stdout_lines }}"
```

Command:
```
ansible-playbook playbook.yaml
```

Work-around: Changing `path: message.txt` to `path: ./message.txt` retains the first letter of the file name (in this case 'm').

### Expected Results

I expected the file `message.txt` to be saved as `message.txt` inside `message.txt.zip`.

### Actual Results

```console (paste below)
$ unzip -l message.txt.zip
Archive:  message.txt.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       11  2021-06-16 14:19   essage.txt
---------                     -------
       11                     1 file
```

Note the missing `m` in the name.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
