### ISSUE TITLE
Terraform module returns output in object format

### ISSUE THREAD

**Issue by gthieleb** [ansible-collections/community.general#2857]
### Summary

When I try to run an terraform module with ansibles builtin terraform module, the output contains json data but in some mixed object formatted code.

### Issue Type

Bug Report

### Component Name

terraform

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/home/******/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```
^^ empty

### OS / Environment

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```

### Steps to Reproduce

```yaml (paste below)
    - terraform:
        project_path: "{{ (playbook_dir, '../terraform')|join('/') }}"
        state: present
      register: terraform_result
```

### Expected Results

Desired output:

```
{
    "changed": false,
    "command": "/usr/local/bin/terraform apply -no-color -input=false -auto-approve -lock=true /tmp/tmpvfayt923.tfplan",
    "failed": false,
    "outputs": {
        "windows-basic": {
                "ami": "ami-099b77680*********",
                "arn": "arn:aws:ec2:eu-central-1:221801580119:instance/i-09********ef6"
...
}
```

### Actual Results

Current output: 

```
{
    "changed": false,
    "command": "/usr/local/bin/terraform apply -no-color -input=false -auto-approve -lock=true /tmp/tmpvfayt923.tfplan",
    "failed": false,
    "outputs": {
        "windows-basic": {
            "sensitive": false,
            "type": [
                "object",
                {
                    "ami": "string",
                    "arn": "string",
...
            "value": {
                "ami": "ami-099b776803cf89b80",
                "arn": "arn:aws:ec2:eu-central-1:221801580119:instance/i-091eae42cd1bf6ef6",
...
}
```
You can see the `sensitive`, `type` and `value` attributes. These are not parseable using jinja filters e.g. `attr`.
Remark: I need to use this filter because forecast the instance name is (windows-basic) is not possible.

```
  - debug: msg="{{ terraform_result['outputs'].values()|list|first|attr('value') }}"
```

```
TASK [debug] ***********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'value'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Ajpantuso** [comment]
[Values representation](https://www.terraform.io/docs/internals/json-format.html#values-representation) comes straight from `HashiCorp`. I guess it's possible to add a utility to use that meta data to convert to `Ansible` friendly objects, but the format is versioned so that's not a trivial effort.

The objects are still filterable however.

Below are a few examples:
```yaml
- hosts: localhost
   vars:
     outputs:
       windows-basic:
         sensitive: false
         type:
           - object
           - ami: string
             arn: string
         value:
           ami: ami-099b776803cf89b80
           arn: arn:aws:ec2:eu-central-1:221801580119:instance/i-091eae42cd1bf6ef6
   tasks:
     - debug:
         msg: '{{ (outputs.values() | first).value }}'
     - debug:
         msg: "{{ item.key }} has values: {{ item.value.value }}"
       vars:
         item: "{{ outputs | dict2items | first }}"
     - debug:
         msg: "{{ item.key }} has values: {{ item.value.value }}"
       loop: "{{ outputs | dict2items }}"
```

**Comment by ansibullbot** [comment]
cc @m-yosefpor @rainerleber
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gthieleb** [comment]
@Ajpantuso: Thanks for answering and the examples you've given. My (mis)interpretion as I was interpreting output as some kind of python object.

If it is an upstream format we should not touch it. 

I was not aware dict2items will help here. Perhaps we could add your examples in the help section of terraform module?

**Comment by Ajpantuso** [comment]
The module describes the return values pretty well, but if you wanted to add an example using `dict2items` to address resources with dynamic names I'd be happy to review.
```yaml
outputs:
  type: complex
  description: A dictionary of all the TF outputs by their assigned name. Use `.outputs.MyOutputName.value` to access the value.
  returned: on success
  sample: '{"bukkit_arn": {"sensitive": false, "type": "string", "value": "arn:aws:s3:::tf-test-bukkit"}'
  contains:
    sensitive:
      type: bool
      returned: always
      description: Whether Terraform has marked this value as sensitive
    type:
      type: str
      returned: always
      description: The type of the value (string, int, etc)
    value:
      type: str
      returned: always
      description: The value of the output as interpolated by Terraform
```
