### ISSUE TITLE
nmcli does not modify connections without type parameter

### ISSUE THREAD

**Issue by coffeelover** [ansible-collections/community.general#2858]
### Summary

When setting a static configuration on an already configured interface, the parameters ip4, manual, etc. are ignored when type is missing. But the module does not complain.

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```
$ ansible --version
ansible 2.10.11
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/ansible-2.10/lib64/python3.6/site-packages/ansible
  executable location = /home/ansible/ansible-2.10/bin/ansible
  python version = 3.6.8 (default, Mar 19 2021, 05:13:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

$ ansible-galaxy collection list

# /home/ansible/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.2.0  
```

### Configuration

```
$ ansible-config dump --only-changed
DEFAULT_BECOME(/home/ansible/.ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/ansible/.ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/ansible/.ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/ansible/.ansible.cfg) = root
DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = ['/home/ansible/.ansible/inventory']
DEFAULT_REMOTE_USER(/home/ansible/.ansible.cfg) = ansible
DEPRECATION_WARNINGS(/home/ansible/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/ansible/.ansible.cfg) = False
```

### OS / Environment

RHEL8

### Steps to Reproduce

```
---
- name: "Network configuration"

  hosts:
    - "ansible1.example.com"

  tasks:
    - name: "remove configuration"
      community.general.nmcli:
        conn_name: "enp0s8"
        state: "absent"

    - name: "Configure dhcp"
      community.general.nmcli:
        conn_name: "enp0s8"
        type: "ethernet"
        method4: "auto"
        state: "present"

    - name: "Configure static"
      community.general.nmcli:
        conn_name: "enp0s8"
        method4: "manual"
        ip4: "192.168.0.2"
        state: "present"
```

### Expected Results

I expected a static configuration for enp0s8 or at least a complaint about missing "type".

### Actual Results

```
ok: [ansible1.example.com] => {
    "Exists": "Connections already exist and no changes made",
    "changed": false,
    "conn_name": "enp0s8",
    "invocation": {
        "module_args": {
            "ageingtime": 300,
            "arp_interval": null,
            "arp_ip_target": null,
            "autoconnect": true,
            "conn_name": "enp0s8",
            "dhcp_client_id": null,
            "dns4": null,
            "dns4_ignore_auto": false,
            "dns4_search": null,
            "dns6": null,
            "dns6_ignore_auto": false,
            "dns6_search": null,
            "downdelay": null,
            "egress": null,
            "flags": null,
            "forwarddelay": 15,
            "gw4": null,
            "gw4_ignore_auto": false,
            "gw6": null,
            "gw6_ignore_auto": false,
            "hairpin": true,
            "hellotime": 2,
            "ifname": null,
            "ingress": null,
            "ip4": "192.168.0.2",
            "ip6": null,
            "ip_tunnel_dev": null,
            "ip_tunnel_local": null,
            "ip_tunnel_remote": null,
            "mac": null,
            "master": null,
            "maxage": 20,
            "method4": "manual",
            "method6": null,
            "miimon": null,
            "mode": "balance-rr",
            "mtu": null,
            "never_default4": false,
            "path_cost": 100,
            "primary": null,
            "priority": 128,
            "route_metric4": null,
            "routes4": null,
            "slavepriority": 32,
            "ssid": null,
            "state": "present",
            "stp": true,
            "type": null,
            "updelay": null,
            "vlandev": null,
            "vlanid": null,
            "vxlan_id": null,
            "vxlan_local": null,
            "vxlan_remote": null,
            "wifi_sec": null,
            "zone": null
        }
    },
    "state": "present"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
