### ISSUE TITLE
Installing npm dependencies from package.json broken in 3.3.0

### ISSUE THREAD

**Issue by jasonaowen** [ansible-collections/community.general#2917]
### Summary

When I try to use the community.general.npm plugin to install dependencies from a `package.json` file, the step fails with a stacktrace ending in `KeyError: 'version'`.

This started breaking with 3.3.0, and was working previously. I believe it comes from this line: https://github.com/ansible-collections/community.general/blob/1ed4394c5ed4e3e9e31165b7979e5b38e16def05/plugins/modules/packaging/language/npm.py#L219

which was introduced in commit 1ed4394c5ed4e3e9e31165b7979e5b38e16def05 in PR #2830.

Additionally, it seems that none of the tests in [`test_npm.py`](https://github.com/ansible-collections/community.general/blob/main/tests/unit/plugins/modules/packaging/language/test_npm.py) cover installing dependencies for a folder with a `package.json` file. The [docs include a few examples](https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html#examples) of this pattern.

### Issue Type

Bug Report

### Component Name

npm

### Ansible Version

```console (paste below)
Run ansible --version
  ansible --version
  shell: /bin/bash -e {0}
ansible 2.10.11
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible-base/lib/python3.6/site-packages/ansible
  executable location = /opt/pipx_bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

### OS / Environment

GitHub Actions runner, Ubuntu 18.04

### Steps to Reproduce

`.github/workflows/deploy.yml`:
```yaml
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: debugging ansible
      run: ansible --version
    - name: Install ansible dependencies
      run: ansible-galaxy collection install 'community.general:==3.3.0'
    - name: Generate Inventory
      run: ./scripts/generate_inventory.sh ${{ env.perm_env }} ${{ matrix.machine }}
    - name: Run deploy
      run: ansible-playbook provisioners/install.yml -vv -i inventory.ini
```

`provisioners/install.yml`:
```yaml
- name: Deploy code on machine
  hosts: default
  become: true
  tasks:
    - name: Install upload-service dependencies
      community.general.npm:
        path: /data/www/upload-service
        production: yes 
```
(this is a stripped down version of our actual configuration, which is open source: `deploy.yml` comes from [`deploy-dev.yml`](https://github.com/PermanentOrg/infrastructure/blob/fb4f308d1fa4d1e128a13f737151cc5460db9d84/.github/workflows/deploy-dev.yml), and `install.yml` comes from [`deploy-backend.yml`](https://github.com/PermanentOrg/infrastructure/blob/fb4f308d1fa4d1e128a13f737151cc5460db9d84/provisioners/deploy-backend.yml).)

### Expected Results

I expected the dependencies (but not `devDependencies`) in `/data/www/upload-service/package.json` to be installed

### Actual Results

```console (paste below)
Traceback (most recent call last):
  File \"<stdin>\", line 102, in <module>
  File \"<stdin>\", line 94, in _ansiballz_main
  File \"<stdin>\", line 40, in invoke_module
  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module
    fname, loader, pkg_name)
  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code
    exec code in run_globals
  File \"/tmp/ansible_community.general.npm_payload_nrj108/ansible_community.general.npm_payload.zip/ansible_collections/community/general/plugins/modules/npm.py\", line 333, in <module>
  File \"/tmp/ansible_community.general.npm_payload_nrj108/ansible_community.general.npm_payload.zip/ansible_collections/community/general/plugins/modules/npm.py\", line 310, in main
  File \"/tmp/ansible_community.general.npm_payload_nrj108/ansible_community.general.npm_payload.zip/ansible_collections/community/general/plugins/modules/npm.py\", line 219, in list
KeyError: 'version'
```
See also a [failed GitHub Action log](https://github.com/PermanentOrg/infrastructure/runs/2966769852?check_suite_focus=true#step:9:77)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
