### ISSUE TITLE
docker_compose module uses inappropriate stop timeout

### ISSUE THREAD

**Issue by aaron-kaplan** [ansible-collections/community.general#293]
##### SUMMARY

When the `docker_compose` module is used with `stopped: yes` or `restarted: yes` and no explicit `timeout` argument, it defaults to a 10 second timeout, overriding any `stop_grace_period` that was specified in `docker-compose.yaml`. A more appropriate default would have been to respect `stop_grace_period` unless a timeout was specified explicitly in the ansible task.

Given that this is long-standing behavior, it might not be a good idea to change the default, but perhaps we could introduce a distinguished timeout value that lets the user explicitly specify that the timeout configured in the project should be used.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_compose
##### ANSIBLE VERSION

```paste below
ansible 2.8.2
```
is what I'm currently using, but the timeout logic hasn't changed since then.
##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Not relevant

##### STEPS TO REPRODUCE

Create the following three files in $HOME/timeout-bug:

foo.sh:
```bash
#!/usr/bin/env bash

terminate() {
    echo received SIGTERM
    kill -TERM $child
}
echo script has started
trap terminate SIGTERM
/bin/sleep infinity & # stand-in for the real service
child=$!
wait $child
sleep 11 # simulate waiting for a child that takes 11 seconds to finish up
echo exited cleanly
```
docker-compose.yaml:
```yaml
version: "3.2"
services:
  foo:
    image: bash
    command: ["/foo.sh"]
    volumes:
      - type: bind
        source: ./foo.sh
        target: /foo.sh
    stop_grace_period: 12s
```
playbook.yaml:
```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - project_src: "{{ lookup('env', 'HOME') }}/timeout-bug"
  tasks:
    - name: remove pre-existing container to clear logs from previous run
      docker_compose:
        project_src: "{{ project_src }}"
        services:
          - foo
        state: absent

    - name: start service
      docker_compose:
        project_src: "{{ project_src }}"
        services:
          - foo
        state: present

    - name: stop service
      docker_compose:
        project_src: "{{ project_src }}"
        services:
          - foo
        state: present
        stopped: yes
```

Then run the following commands:
```bash
cd $HOME/timeout-bug
ansible-playbook -i localhost, playbook.yaml
docker logs timeoutbug_foo_1
```

##### EXPECTED RESULTS

output should be
```
script has started
received SIGTERM
exited cleanly
```
##### ACTUAL RESULTS

The final line "exited cleanly" is not present in the log, because the container was sent a SIGKILL before it was finished.

```paste below
script has started
received SIGTERM
```
