### ISSUE TITLE
datadog_monitor should support composite monitors

### ISSUE THREAD

**Issue by Tyler-2** [ansible-collections/community.general#2956]
### Summary

The `datadog_monitor` module checks that a valid monitor `type` is provided. But [this list](https://github.com/ansible-collections/community.general/blob/518ace25621ee7ed08debd4d87509b0b2be33f2c/plugins/modules/monitoring/datadog/datadog_monitor.py#L54) is outdated and does not cover the monitor types supported in the [Datadog API](https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor).

In my specific use case, I'm trying to deploy/manage a composite monitor.

### Issue Type

Feature Idea

### Component Name

datadog_monitor

### Additional Information

```yaml (paste below)
# Create a metric monitor
- datadog_monitor:
    type: "composite alert"
    name: "Composite monitor"
    state: "present"
    query: "12345 && 67890" #where 12345 and 67890 are the IDs of non-composite monitors
    message: "Composite monitor is failing"
    api_key: "9775a026f1ca7d1c6c5af9d94d9595a4"
    app_key: "87ce4a24b5553d2e482ea8a8500e71b8ad4554ff"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
