### ISSUE TITLE
lvg: Does it support extend volume group?

### ISSUE THREAD

**Issue by itviet2021** [ansible-collections/community.general#2991]
### Summary

- name: create from 1 disk and 2 partitions
      lvg:
        vg: vg03
        pvs: /dev/nvme0n3,/dev/nvme0n4p2,/dev/nvme0n5p3

// check by command
# vgdisplay vg03
...
      Cur PV                3             --> OK, It's create new vg03 with 3 physical volume
      Act PV                3
      VG Size               6.39 GiB

Now I need to extend vg03 by add 1 partition

- name: extend vg03
      community.general.lvg:
        vg: vg03
        pvs: /dev/nvme0n5p2
        pvresize: yes                --> there is and there isn't

// check by command
# vgdisplay vg03
...
      Cur PV                1                 --> it is recreate new vg03 with 1 partition 
      Act PV                1                 --> not add this partition to existing vg03 and extend vg03
      VG Size               <1.20 GiB

Does community.general.lvg support extend existing volume group?

Thank you

### Issue Type

Bug Report

### Component Name

lvg

### Ansible Version

ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 19 2021, 05:13:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

CentOS 8

### Steps to Reproduce

- name: create from 1 disk and 2 partitions
      lvg:
        vg: vg03
        pvs: /dev/nvme0n3,/dev/nvme0n4p2,/dev/nvme0n5p3

- name: extend vg03
      community.general.lvg:
        vg: vg03
        pvs: /dev/nvme0n5p2
        pvresize: yes

### Expected Results

extend existing volume group size when adding physical volumes

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/system/lvg.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/lvg.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @abulimov
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by quidame** [comment]
hi @itviet2021 , this is the expected behaviour :) The module creates a VG from the given PVs

Module (current) documentation says https://github.com/ansible-collections/community.general/blob/11cdb1b661b302aca06edb62b17f0f42a4daa609/plugins/modules/system/lvg.py#L25-L31

Have you tried with:
```yaml
- name: create vg03 from 1 disk and 2 partitions
  lvg:
    vg: vg03
    pvs: /dev/nvme0n3,/dev/nvme0n4p2,/dev/nvme0n5p3

- name: extend vg03 with 1 partition
  lvg:
    vg: vg03
    pvs: /dev/nvme0n3,/dev/nvme0n4p2,/dev/nvme0n5p3,/dev/nvme0n5p2
```
?

or with YAML lists:
```yaml
- name: create vg03 from 1 disk and 2 partitions
  lvg:
    vg: vg03
    pvs:
      - /dev/nvme0n3
      - /dev/nvme0n4p2
      - /dev/nvme0n5p3

- name: extend vg03 with 1 partition
  lvg:
    vg: vg03
    pvs: 
      - /dev/nvme0n3
      - /dev/nvme0n4p2
      - /dev/nvme0n5p3
      - /dev/nvme0n5p2

- name: reduce vg03 of 1 partition
  lvg:
    vg: vg03
    pvs: 
      - /dev/nvme0n3
      - /dev/nvme0n4p2
      - /dev/nvme0n5p2
```
?

Both should work as expected (I mean: as stated by the tasks names; the module internally calls `vgcreate`, `vgextend` and/or `vgreduce` to do the job).
