### ISSUE TITLE
Use glob to select Jenkins plugins for upgrade

### ISSUE THREAD

**Issue by vwbusguy** [ansible-collections/community.general#2997]
### Summary

I'm using Ansible to update all installed Jenkins plugins.  I came up with a workaround for getting all currently installed plugins to feed it to this plugin since it doesn't yet exist.  In thinking of how this might be useful for others, selecting the plugins to update/install via glob would probably be the most widely useful.

Here's what I did as a workaround to get all currently installed plugins and update them, from the Jenkins master [sic]:

```
    - name: Get plugins
      shell: "find /var/lib/jenkins/plugins/ -maxdepth 1 -type d | sed 's,.*/,,g' | grep -Pv '^\\s*$' | sort -d"
      register: plugins

    - name: Update all plugins to latest
      jenkins_plugin:
        name: "{{ item }}"
        state: latest
        url_username: <REDACTED>
        url_password: <REDACTED>
      with_items: "{{ plugins.stdout_lines }}"
```
The plugin can already grok jenkins_home for a var, so it basically just needs a one-level dir search from jenkins_home/plugins (which can easily be done with python instead of bash).  The other thing to consider is that glob would only work against currently installed plugins this way, which would be useful for updating plugins, but not for installing new ones.  

If this seems like a possibly viable addition, I'm happy to work on getting a PR together for it.  Since there's not a very intuitive way to update all plugins remotely for Jenkins, this could be a useful thing for a lot of people, but if it's not a good fit, then hopefully my workaround above will at least be useful for someone else.

### Issue Type

Feature Idea

### Component Name

jenkins

### Additional Information

Example of current workaround:
```yaml
    - name: Get plugins
      shell: "find /var/lib/jenkins/plugins/ -maxdepth 1 -type d | sed 's,.*/,,g' | grep -Pv '^\\s*$' | sort -d"
      register: plugins

    - name: Update all plugins to latest
      jenkins_plugin:
        name: "{{ item }}"
        state: latest
        url_username: <REDACTED>
        url_password: <REDACTED>
      with_items: "{{ plugins.stdout_lines }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
