### ISSUE TITLE
Enhance gitlab_project module to allow to manage more (all) properties handled by at least python-gitlab

### ISSUE THREAD

**Issue by suukit** [ansible-collections/community.general#3001]
### Summary

The existing module community.general.gitlab_project needs to be enhanced to allow to manage additional properties provided by the gitlab API. Those should be at least the once managed by python-gitlab module - which is used by the ansible module.

In a first step simple scalar values could be handled, later on complex calues like protected branches.

### Issue Type

Feature Idea

### Component Name

gitlab_project

### Additional Information

```yaml (paste below)
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: "Test"
      community.general.gitlab_project:
        api_url: ""
        api_token: ""
        validate_certs: False
        group: "Test"
        name: "TestAPI"
        visibility: "internal"
        wiki_enabled: "False"
        issues_enabled: "False"
        snippets_enabled: "False"
        description: "Description"
        merge_method: "ff"
        merge_requests_enabled: "True"
        allow_merge_on_skipped_pipeline: "False"   # new
        only_allow_merge_if_all_discussions_are_resolved: "False"    # new
        only_allow_merge_if_pipeline_succeeds: "False"   # new
        packages_enabled: "False"   # new
        remove_source_branch_after_merge: "False"   # new
        squash_option: "default_off"   # new
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
