### ISSUE TITLE
community.general.gitlab_runner SSLError cert verify failed

### ISSUE THREAD

**Issue by QCU87Z** [ansible-collections/community.general#3007]
### Summary

I am trying to register some gitlab runners. On new openstack instances.
I get a SSL certificate verify failed error as the return.

If I curl the gitlab url from the command line of the box that I am trying to register I get a response back no TLS issues. 
The gitlab servers certificate is signed by an internal CA, which is installed into the system ca-trust /etc/pki/ca-trust/source/anchors and update-ca-trust has been run.

I am unable to copy and paste the actual out from the servers. Due to interal work policy

### Issue Type

Bug Report

### Component Name

gitlab_runner

### Ansible Version

```console (paste below)
$ ansible --version

```
ansible 2.9.33
python version 3.9.5

### Configuration

```

```

### OS / Environment

CentOS 8 on Openstack train
Gitlab 14.0.1 runner same version

### Steps to Reproduce

```yaml (paste below)
- name: register gitlab runner
  community.general.gitlab_runner
    api_url: https://gitlab.internal.addressing
    api_token: abc
    registration_token: def
    description: "{{ anisble_hostname }}"
    state: present
    active: false
    tag_list: shell
    run_untagged: false
    locked: false
```

### Expected Results

The ansible task to connect to the gitlab server and register the runner

### Actual Results

```console (paste below)
SSLError "Certificate_verify_failed"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/source_control/gitlab/gitlab_runner.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/source_control/gitlab/gitlab_runner.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Lunik @SamyCoenen @Shaps @dj-wasabi @marwatk @metanovii @scodeman @waheedi @zanssa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
It looks like Python isn't using the system ca-trust then.

**Comment by jayooin** [comment]
I have the same problem, only tested with community.general.gitlab_group, but if needed I can try with community.general.gitlab_users as well. 

The problem seems to come from the python-gitlab module. 

Here is what I tried: 

### On Python
```python
import socket
import ssl

hostname = 'gitlab.domain.local'
context = ssl.create_default_context()

with socket.create_connection((hostname, 443)) as sock:
    with context.wrap_socket(sock, server_hostname=hostname) as ssock:
        print(ssock.version())

```

I get no error. If the certificate is absent from my system, then I would have one.

### On python-gitlab
I defined the $HOME/.python-gitlab.cfg as following:
```
[global]
default = gitlab.domain.local
timeout = 5
[gitlab.domain.local]
api_version = 4
url = https://gitlab.domain.local
private_token = XXXXXXXXXXXXXXXX
```
When I run `gitlab group list` I have the following: 
```
HTTPSConnectionPool(host='gitlabl.domain.local', port=443): Max retries exceeded with url: /api/v4/user (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

The problem is fixed when I add the variable `ssl_verify = 'MyCertificate.cer'` in the python-gitlab.cfg.

### On Ansible
I then tried to add an extra variable in the community.general.gitlab_group module, called certs, and specified my certificate in my playbook, and it worked.

So while the python-gitlab module can be fixed regarding that matter, this is a solution that could be implemented for all gitlab ansiblle modules.

My Ansible task looks like that:
```yaml
- name: "Create GitLab Group"
  community.general.gitlab_group:
    api_url: "{{ gitlab_url }}"
    #validate_certs: no  # not working when set to yes
    certs: "/CA-ROOT.cer"
    api_token: "{{ gitlab_api_token }}"
    name: "{{ g_group }}"
    path: "{{ g_group }}"
    state: present
    parent: "{{ gitlab_group_parent }}"
```

#### The changes in the Ansible module
In community/general/plugins/module_utils/gitlab.py:81
Change to `module.params['certs']`
```python
def gitlabAuthentication(module):
    gitlab_url = module.params['api_url']
    validate_certs = module.params['certs']
    gitlab_user = module.params['api_username']
    gitlab_password = module.params['api_password']
    gitlab_token = module.params['api_token']
```

In community/general/plugins/modules/source_control/gitlab/gitlab_group.py:256
Add a line to define certs:
```python
def main():
    argument_spec = basic_auth_argument_spec()
    argument_spec.update(dict(
        api_token=dict(type='str', no_log=True),
        name=dict(type='str', required=True),
        certs=dict(type='str'),
        path=dict(type='str'),
        description=dict(type='str'),
        state=dict(type='str', default="present", choices=["absent", "present"]),
        parent=dict(type='str'),
        visibility=dict(type='str', default="private", choices=["internal", "private", "public"]),
    ))
```

That variable, `certs` can be either the certificate file's path, or no/yes.
