### ISSUE TITLE
Issue upgrading to terraform 1.0.0

### ISSUE THREAD

**Issue by edvinas31** [ansible-collections/community.general#3011]
### Summary

When trying to use terraform 1.0.0 https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html module fails. Does this module support terraform 1.0.0? I have noticed that terraform validate command has changed if compare to terraform0.14.10:

terraform0.14.10 validate --help
Usage: terraform validate [options] [dir]

terraform1.0.0 validate --help
Usage: terraform [global options] validate [options]

Could it be the reason why it is failing?

### Issue Type

Bug Report

### Component Name

https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html

### Ansible Version

```console (paste below)
$ ansible --version
2.8.5
```

### OS / Environment

OracleLinux 7

### Steps to Reproduce

```yaml (paste below)
# A Init is required to setup the statefile and workspace.
# A plan file is also generated, which can be used by destroy or apply steps
- name: TF init/validate/plan
  terraform:
    binary_path: "{{ terraform_bin }}"
    project_path: "{{ project_dir }}"
    state: planned # = `terraform plan`
    plan_file: "{{ plan_filename }}"
    workspace: "{{ custenv }}"
    force_init: true
    variables_file: "{{ tfvars_filepath }}"
    variables:
      oci_objectstorage_access_key:           "{{ terraform_vault.aws_access_key }}"
      oci_objectstorage_secret_key:           "{{ terraform_vault.aws_secret_key }}"
      oci_dbaas_home_database_admin_password: "{{ terraform_vault.oci_dbaas_home_database_admin_password }}"
    backend_config:
      access_key:                             "{{ terraform_vault.aws_access_key }}"
      secret_key:                             "{{ terraform_vault.aws_secret_key }}"
      bucket:                                 "{{ terraform_customer }}-terraform-state"
      key:                                    "{{ terraform_project }}"
  ignore_errors: yes
```

### Expected Results

I expect terraform module to behave as same as it was working with previous terraform versions

```console (paste below)
 ok: [localhost] => changed=false
  command: /tmp/terraform-1.0.0/terraform plan -input=false -no-color -detailed-exitcode -out tf_plan tf_plan
  outputs:
    compartment_id:
      sensitive: false
      type: string
      value: ocid1.compartment.oc1..aaaaaaaaugsatrnd5x6bmlleth7odw5qceh7hupxb6hsejklymygo3wvpljq
    vcn_cidr:
      sensitive: false
      type: string
      value: 10.100.0.0/16
    vcn_drg_id:
      sensitive: false
      type:
      - tuple
      - []
      value: []
    vcn_fqdn:
      sensitive: false
      type: string
      value: paasdev.oraclevcn.com
    vcn_id:
      sensitive: false
      type: string
      value: ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaazm5vxfyalirgfljguy2z4zg6cudnn2wwowfc2m667wsrjqyqol7a
    vcn_ig_id:
      sensitive: false
      type: string
      value: ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaapkn73lh5tar7xlrd6nzv3apcxotw553xwgzicgqsj6kudy72egsq
    vcn_name:
      sensitive: false
      type: string
      value: vcn0
    vcn_ng_id:
      sensitive: false
      type: string
      value: ocid1.natgateway.oc1.eu-frankfurt-1.aaaaaaaanhbjfmpal5wkfvm5ku4vips6xw3kzi2c4ljs7547uig5sps6j7la
  state: planned
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    module.oci_compartment.oci_identity_compartment.compartment: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaaugsatrnd5x6bmlleth7odw5qceh7hupxb6hsejklymygo3wvpljq]
    module.vcn.oci_core_vcn.vcn: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaazm5vxfyalirgfljguy2z4zg6cudnn2wwowfc2m667wsrjqyqol7a]
    module.vcn.oci_core_internet_gateway.vcn_ig[0]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaapkn73lh5tar7xlrd6nzv3apcxotw553xwgzicgqsj6kudy72egsq]
    module.vcn.oci_core_default_route_table.default_route_table: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaamtqbpwfstyxkqgnu2qecdxl3dbxj6u6nxp7w3o7vnygbidjuqecq]
    module.vcn.oci_core_nat_gateway.vcn_ng[0]: Refreshing state... [id=ocid1.natgateway.oc1.eu-frankfurt-1.aaaaaaaanhbjfmpal5wkfvm5ku4vips6xw3kzi2c4ljs7547uig5sps6j7la]
    module.vcn.oci_core_default_security_list.default_security_list: Refreshing state... [id=ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaasqqot3it5z3k4rqtypxaf3v3isc7lhq6cmcy4gd7tkmsp6baenqq]

    No changes. Infrastructure is up-to-date.

    This means that Terraform did not detect any differences between your
    configuration and real physical resources that exist. As a result, no
    actions need to be performed.
  stdout_lines: <omitted>
  workspace: paasdev
```

### Actual Results

```console (paste below)
  msg: |-
    Failed to validate Terraform configuration files:
    [31m╷[0m[0m
    [31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to parse command-line flags[0m
    [31m│[0m [0m
    [31m│[0m [0m[0mflag provided but not defined: -var
    [31m╵[0m[0m
    [31m╷[0m[0m
    [31m│[0m [0m[1m[31mError: [0m[0m[1mToo many command line arguments[0m
    [31m│[0m [0m
    [31m│[0m [0m[0mExpected at most one positional argument.
    [31m╵[0m[0m

    For more help on using this command, run:
      terraform validate -help
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
