### ISSUE TITLE
Support parameter revision for snap

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/community.general#3025]
### Summary

Hello!
Thanks for snap module.

I try install by ansible microk8s with specific revision
`snap install microk8s --channel=1.18/stable --classic --revision 2270`

```
- name: Install "microk8s" with option --channel=1.18/stable
  become: true
  community.general.snap:
    name: microk8s
    channel: 1.18/stable
    classic: true
    revision: 2270
```

But error
```
  msg: 'Unsupported parameters for (community.general.snap) module: revision Supported parameters include: channel, classic, name, state'
```

### Issue Type

Feature Idea

### Component Name

snap

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
