### ISSUE TITLE
slack: possibility to edit/modify/update existing message

### ISSUE THREAD

**Issue by anlutro** [ansible-collections/community.general#304]
##### SUMMARY
It would be nice if the `slack` module allowed modifying existing messages.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`plugins/modules/notification/slack.py`

##### ADDITIONAL INFORMATION

Slack supports this with the [`chat.update` method](https://api.slack.com/methods/chat.update), which uses a parameter `ts` to identify the message. This value is already part of the Ansible module's return value:

https://github.com/ansible-collections/community.general/blob/f887aff159356529747df52761482fa70cbd1b68/plugins/modules/notification/slack.py#L347

Presumably it's just a matter of adding an input argument for the module. Is `ts` the best name for this purpose? If so, I'd be happy to open a pull request implementing this change.

An example use case would be for messages regarding deployment. This is a fairly short message so it might not make sense to update instead of just sending 2 messages, but some messages can get quite lengthy with many attachments, in which case sending 2 messages adds a lot of noise.

Here's how I imagine the functionality could be used (`token` and `channel` parameters excluded for brevity's sake):

```yaml
- slack:
    msg: "Starting deployment of {{ deploy_version }}..."
    register: slack_msg
    color: warning
- block:
  - include_tasks: deploy.yml
  - slack:
      ts: "{{ slack_msg.ts }}"
      msg: "Successfully deployed {{ deploy_version }}!"
      color: danger
  rescue:
  - slack:
      ts: "{{ slack_msg.ts }}"
      msg: "Deployment of {{ deploy_version }} failed!"
      color: good
```
