### ISSUE TITLE
Issue with nmcli module after upgrade to 3.4.0

### ISSUE THREAD

**Issue by MartinHerren** [ansible-collections/community.general#3040]
### Summary

After upgrade to 3.4.0 our nmcli task stopped working with following error:

```
fatal: [xxxx]: FAILED! => changed=false 
  msg: |-
    Error: invalid or not allowed setting 'team': 'team' not among [connection, 802-3-ethernet (ethernet), 802-1x, dcb, ipv4, ipv6, tc, proxy].
  name: Wired connection 1
  rc: 2
```

Task is
```
- name: Set static IP
  community.general.nmcli:
    type: team
    conn_name: "Wired connection 1"
    ip4: "xxx/x"
    gw4: "xxx"
    dns4: "xxx"
    state: present
```

Didn't find a mention in the release changelog that there was a breaking change in this module, just an added feature.

Downgrading to 3.3.2 fixes the issue. Even works fine on 1.2.0.

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

Reproduced with multiple 2.9.x and 3.x versions

### OS / Environment

Reproduced on Debian 10, Ubuntu 18.04 and 20.04

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

I expected no change in existing behavior from this update

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/net_tools/nmcli.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/nmcli.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @alcamie101 @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Ajpantuso** [comment]
@omula Can you take a look and see if this is related to #2901

**Comment by omula** [comment]
I tried the example below and failed with the following error: `FAILED! => {"changed": false, "msg": "Error: Failed to add 'Wired connection 1' connection: connection.interface-name: 'Wired connection 1': interface name contains an invalid character\n", "name": "Wired connection 1", "rc": 4}`
```
---
- name: test
  hosts: all

  tasks:
    - name: Test
      community.general.nmcli:
        type: team
        conn_name: 'Wired connection 1'
        ip4: "192.168.0.10/24"
        gw4: "192.168.0.1"
        state: present
```

By changing the connection name to just `Wired` it worked.
`{"Connection": "Connection Wired of Type team is being added", "changed": true, "conn_name": "Wired", "state": "present", "stdout": "Connection 'Wired' (dc173ef5-50c8-45ef-a164-a18e90b740c8) successfully added.\n", "stdout_lines": ["Connection 'Wired' (dc173ef5-50c8-45ef-a164-a18e90b740c8) successfully added."]}`

Can you provide more info @MartinHerren?
