### ISSUE TITLE
Yarn module: support --frozen-lockfile argument 

### ISSUE THREAD

**Issue by JoelRobinson-Tista** [ansible-collections/community.general#3109]
### Summary

Ensure `yarn install` will not update the `yarn.lock` file, and fail if an update is required

### Issue Type

Feature Idea

### Component Name

yarn

### Additional Information

If a `yarn.lock` file is not in the current directory normally yarn will generate one. In order to add more stability to nodejs deployments `yarn install` has the `--frozen-lockfile` command line option which will fail the deployment if a `yarn.lock` is not in the current directory. 

```yaml (paste below)
- name: Install Node.js dependencies with Yarn
  yarn:
    production: true
    path: "{{ remote_app_directory }}"
    frozen_lockfile: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
