### ISSUE TITLE
community.general.flatpak - reports no match, but seems to install

### ISSUE THREAD

**Issue by bashfulrobot** [ansible-collections/community.general#3118]
### Summary

I have a role setup where I am leveraging flatpaks to install on my local system. It keeps reporting the package is not found but appears to have been installed.

Thank you for your time.

### Issue Type

Bug Report

### Component Name

community.general.flatpak

### Ansible Version

```console 

❯ ansible --version
ansible 2.10.5
  config file = None
  configured module search path = ['/home/dustin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]


```

### Configuration

```console
$ ansible-config dump --only-changed

```

This command results in an empty result.

### OS / Environment

```
❯ cat -p /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

### Steps to Reproduce

The task component of the role has:

```
- name: install flatpak
  become: yes
  apt:
    pkg:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

- name: add the flathub flatpak repository remote to the user installation
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: install flathub packages
  become: yes
  community.general.flatpak:
    name: "{{flathub_packages}}"
    state: present
    remote: flathub
```

Then in a loaded var file, I have:

```
# Install flathub packages
flathub_packages:
  - org.standardnotes.standardnotes
  - org.some.other
```

### Expected Results

I expect to there be no error displayed and the apps installed.

### Actual Results

When I run the playbook, it results in:

```
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/flatpak install --system --noninteractive flathub '['\"'\"'org.standardnotes.standardnotes'\"'\"']'", "msg": "error: Nothing matches ['org.standardnotes.standardnotes'] in remote flathub", "rc": 1, "stderr": "error: Nothing matches ['org.standardnotes.standardnotes'] in remote flathub\n", "stderr_lines": ["error: Nothing matches ['org.standardnotes.standardnotes'] in remote flathub"], "stdout": "", "stdout_lines": []}
```

when I manually run the installation with `/usr/bin/flatpak install --system --noninteractive flathub org.standardnotes.standardnotes` manually, it reports that the app is already installed.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/packaging/os/flatpak.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/packaging/os/flatpak.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @JayKayy @oolongbrothers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The flatpak module only allows to install multiple packages at once since community.general 3.3.0. Are you using this or a newer version of community.general?

needs_info

**Comment by bashfulrobot** [comment]
Hi there, 

I had simply added a task in a role with:

```
- name: install flatpak
  become: yes
  apt:
    pkg:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

- name: add the flathub flatpak repository remote to the user installation
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: install flathub packages
  become: yes
  community.general.flatpak:
    name: "{{flathub_packages}}"
    state: present
    remote: flathub

```

And then my var was defined with:

```
# Install flathub packages
flathub_packages:
  - org.standardnotes.standardnotes
```

Thank you.
