### ISSUE TITLE
Cloudflare module problem - API bad request

### ISSUE THREAD

**Issue by GuessWhy** [ansible-collections/community.general#3140]
### Summary

I have a problem with the cloudflare_dns module. When adding records I get something like this:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "API bad request; Status: 400; Method: GET: Call: /zones?name=example.com; Error details: code: 6003, error: Invalid request headers; code: 6103, error: Invalid format for X-Auth-Key header; "}`

The problem also occurs with A records.

### Issue Type

Bug Report

### Component Name

cloudflare_dns

### Ansible Version

```
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Jul 15 2021, 15:17:46) [GCC 8.5.0 20210514 (Red Hat 8.5.0-2)]
```

### Configuration

```
- name: Create CNAME
  hosts: localhost
  connection: local
  tasks:
  - name: Create CNAME record
    cloudflare_dns:
     zone: "example.com"
     type: CNAME
     solo: yes
     ttl: 1
     proxied: no
     record: "aaa.example.com"
     value: "example.com"
     account_email: EMAIL
     account_api_token: TOKEN
     state: present
```

### OS / Environment

CentOS Stream

### Steps to Reproduce

```
- name: Create CNAME
  hosts: localhost
  connection: local
  tasks:
  - name: Create CNAME record
    cloudflare_dns:
     zone: "example.com"
     type: CNAME
     solo: yes
     ttl: 1
     proxied: no
     record: "aaa.example.com"
     value: "example.com"
     account_email: EMAIL
     account_api_token: TOKEN
     state: present

```

### Expected Results

Add CNAME

### Actual Results

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "API bad request; Status: 400; Method: GET: Call: /zones?name=example.com; Error details: code: 6003, error: Invalid request headers; code: 6103, error: Invalid format for X-Auth-Key header; "}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
