### ISSUE TITLE
community.general.pkgin: add possibility to enable the verbose mode for installing packages via pkgin

### ISSUE THREAD

**Issue by bartoszkosiorek** [ansible-collections/community.general#3146]
### Summary

With current `community.general.pkgin` plugin implementation, there is no possibility to display the output from `pkgin`.
It is causing the issues in analysing issues, which could be only reproduced in Ansible

Proposal:
Add `verbose` parameter to be able to display StdOut and StdErr from running `pkgin` invocation, for example for installation:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/os/pkgin.py#L275
updating:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/os/pkgin.py#L290
etc.

This will allow to investigate more easily pkgin issues which are appearing only on CI.

### Issue Type

Feature Idea

### Component Name

pkgin

### Additional Information

```yaml (paste below)
- name: Install package foo with verbosity enabled
  community.general.pkgin:
    name: foo
    verbose: true
    state: present
```
Example of module, where the verbose parameter is available:
https://docs.ansible.com/ansible/latest/collections/community/general/hponcfg_module.html

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
