### ISSUE TITLE
udm_dns_record report a change where there is no change

### ISSUE THREAD

**Issue by tabacha** [ansible-collections/community.general#317]
##### SUMMARY
If you try to set a ipv6 host_record with an shortend IPv6 adddress the udm_dns_record it will always report a change.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/modules/cloud/univention/udm_dns_record.py

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/sven/.ansible.cfg) = ['/home/sven/src/anders-ansible/inventory.yml']
DEFAULT_REMOTE_USER(/home/sven/.ansible.cfg) = root
```

##### OS / ENVIRONMENT

Debian 10

##### STEPS TO REPRODUCE

```yaml
   - name: set record
      udm_dns_record:
        name: vb01.meet
        zone: adfc-intern.de
        type: host_record
        data:
          a: 2001:0db8::42
```
Plese note:
if you change:  2001:0db8 **::** 42 to 2001:0db8:**0000:0000:0000:0000:0000:00**42 no change will be reported.

##### EXPECTED RESULTS

If you call this task twice, there should be no change reported by ansible

##### ACTUAL RESULTS

Change will be reported, every time.
