### ISSUE TITLE
Allow one to override the hardcoded value "ansible_syslogger" in the syslogger module.

### ISSUE THREAD

**Issue by mivanov-itsonix** [ansible-collections/community.general#319]
##### SUMMARY

Copied from https://github.com/ansible/ansible/issues/69428.

It is useful to allow one to specify the application name in the syslogger module. It is hardcoded to "ansible_syslogger" at the moment, see:

https://github.com/ansible-collections/community.general/blob/master/plugins/modules/notification/syslogger.py#L145
https://github.com/ansible-collections/community.general/blob/master/plugins/modules/notification/syslogger.py#L149

Moreover, this hardcoded string is not mentioned in the documentation:

https://docs.ansible.com/ansible/latest/modules/syslogger_module.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/modules/notification/syslogger.py

##### ADDITIONAL INFORMATION

One could override it with:

```
- name: Test syslog
  syslogger:
    appname: "myapp"
    msg: "Hello from ansible"
    priority: "err"
    facility: "daemon"
    log_pid: true
```

or in some other way.
