### ISSUE TITLE
parted ignores "number" + flag is ignored

### ISSUE THREAD

**Issue by Loader009** [ansible-collections/community.general#3204]
### Summary

I am trying to setup partitions in different order
/boot -> 1
/ -> 2
bios_grub -> 10

But this doesn't work as expected.

### Issue Type

Bug Report

### Component Name

parted

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.3] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/anonymous/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/anonymous/.ansible/collections:/usr/share/ansible/collections
  executable location = /sbin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```
(nothing)

### OS / Environment

ArchLinux

### Steps to Reproduce

```yaml (paste below)
- name: partition -> setup boot
  parted:
    device: "/dev/{{ partitions.device }}"
    label: "{{ partitions.partitionTable }}"
    name: "{{ partitions.boot.name }}"
    number: "{{ partitions.boot.number }}"
    part_start: "{{ partitions.boot.part_start }}"
    part_end: "{{ partitions.boot.part_end }}"
    state: present

- name: partition -> setup root
  parted:
    device: "/dev/{{ partitions.device }}"
    label: "{{ partitions.partitionTable }}"
    name: "{{ partitions.root.name }}"
    number: "{{ partitions.root.number }}"
    part_start: "{{ partitions.root.part_start }}"
    part_end: "{{ partitions.root.part_end }}"
    state: present
  when: not partitions.encrypted

- name: partition -> setup BIOS boot
  parted:
    device: "/dev/{{ partitions.device }}"
    label: "{{ partitions.partitionTable }}"
    name: "{{ partitions.bios.name }}"
    number: "{{ partitions.bios.number }}"
    part_start: "{{ partitions.bios.part_start }}"
    part_end: "{{ partitions.bios.part_end }}"
    state: present
    flags:
      - bios_grub
    unit: 's'
```
variables:
```yaml
partitions:
  partitionTable: "gpt"
  device: "sda"

  bios:
    name: "biosBoot"
    part_start: "34s"
    part_end: "2047s"
    number: 10

  boot:
    name: "boot"
    part_start: "2MiB"
    part_end: "256MiB"
    number: 1

  root:
    name: "root"
    part_start: "256MiB"
    part_end: "100%"
    number: 2
```

### Expected Results

Set the partition number of the bios_grub partition to 10
```console
# parted /dev/sda p
Model: ATA QEMU HARDDISK (scsi)
Disk /dev/sda: 3221MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name     Flags
 10     17.4kB  1049kB  1031kB               primary  bios_grub
 1      2097kB  268MB   266MB   ext2         boot
 2      268MB   3220MB  2952MB               root
```

### Actual Results

partition number is set to the next free partition number - flag inside yaml is getting ignored
```console (paste below)
# parted /dev/sda p
Model: ATA QEMU HARDDISK (scsi)
Disk /dev/sda: 3221MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name     Flags
 3      17.4kB  1049kB  1031kB               primary
 1      2097kB  268MB   266MB   ext2         boot
 2      268MB   3220MB  2952MB               root
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
