### ISSUE TITLE
A status of parted module  always change option when specific units are specified and resize option is true

### ISSUE THREAD

**Issue by TakaseNochi** [ansible-collections/community.general#3236]
### Summary

A status of parted module always change to changed when specific units like KiB, s, or KB are specified and resize option is true.
But the status doesn't change when spcific GB, GiB and compact.

I think [`conver_to_bytes`](https://github.com/ansible-collections/community.general/blob/a343756e6f3a9ed24f1cb3c16a97dfbae2273bf3/plugins/modules/system/parted.py#L410) function has some problem.

### Issue Type

Bug Report

### Component Name

parted

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.2]
  config file = None
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu20.04

### Steps to Reproduce

```yaml (paste below)
community.general.parted:
  device: /dev/sda
   resize: true
   part_end: 100%
   number: "{{ partition_number }}"
   label: gpt
    unit: KiB
    state: present
```

### Expected Results

Don't chang status to changed

### Actual Results

```console (paste below)
changed: [inventory_hostname]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
