### ISSUE TITLE
udm_dns_record does not work for managing PTR records

### ISSUE THREAD

**Issue by SipSeb** [ansible-collections/community.general#3244]
### Summary

I can create an destroy A records in a Univention server with the module. However, managing PTR records does not work, and looking into the code can never have worked. 

### Issue Type

Bug Report

### Component Name

udm_dns_record

### Ansible Version

```console (paste below)
ansible [core 2.11.1]
  config file = None
  configured module search path = ['/Users/sdamm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sdamm/.venv/ansible3/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/sdamm/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/sdamm/.venv/ansible3/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console (paste below)
empty

```

### OS / Environment

Mac OS Big Sur, ansible installed in virtualenv via pip

### Steps to Reproduce

```yaml (paste below)
     - name: Generate DNS reverse entry
       udm_dns_record:
         state: present
         name: "192.168.1.222"
         zone: "192.168.1"
         type: ptr_record
         data:
           ptr_record: "wurstwasser.example.com."
```

### Expected Results

I would expect PTR records to be created. Instead the module throws an error. The error comes from looking up the zone in Univention, which does not work due to wrong parameters. But it's not the only error, after solving this one, other ones pop up.

### Actual Results

```console (paste below)
Creating/editing dns entry 192.168.1.222 in zoneName=192.168.1,cn=dns,dc=example,dc=com failed: list index out of range"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
