### ISSUE TITLE
pamd: module argument removal doesn't work with state=updated

### ISSUE THREAD

**Issue by gburjan** [ansible-collections/community.general#3260]
### Summary

When I try to execute the documented way to remove all the module arguments of an existing rule, it doesn't change anything. Current documentation on https://docs.ansible.com/ansible/latest/collections/community/general/pamd_module.html contains the following example

```
- name: Remove module arguments from an existing rule
  community.general.pamd:
    name: system-auth
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: ''
    state: updated
```

This simply cannot work, because update_rule method in plugins/modules/system/pamd.py calls parse_module_arguments with the list [''] but it returns with an empty list [], which will be the new value of new_args. After this, the conditional beginning with `if new_args:` will never be executed, so the rule is unchanged.

Please find my proposed fix and a test case attached (in patch format).
[ansible_collections_community.general.pamd_remove_module_args_fix.patch.txt](https://github.com/ansible-collections/community.general/files/7041216/ansible_collections_community.general.pamd_remove_module_args_fix.patch.txt)

### Issue Type

Bug Report

### Component Name

pamd (community.general.pamd)

### Ansible Version

```
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/gburjan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
(empty list)
```

### OS / Environment

Debian 11 (but I've also tested on older versions too and checked the latest code of this module on github)

### Steps to Reproduce

```
# echo "auth       required pam_env.so foo bar" > /etc/pam.d/test0823
```
Execute the following playbook

```yaml (paste below)

- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Remove module arguments from an existing rule
      community.general.pamd:
        name: test0823
        type: auth
        control: required
        module_path: pam_env.so
        module_arguments: ''
        state: updated
```

### Expected Results

Expected result: module arguments are removed.

### Actual Results

File is unchanged.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
