### ISSUE TITLE
lvol does not handle rounding down for resize 

### ISSUE THREAD

**Issue by parrishjd** [ansible-collections/community.general#3269]
### Summary
UPDATED:  Updated to ansible 2.9.24 resolved the first issue with multiple %VG, but did not resolve the issue with use if 100%FREE

When Using 100%FREE as the size the module is not idempotent 
```
   elif size_opt == 'l':
            # Resize LV based on % value
            tool = None
            size_free = this_vg['free']
            if size_whole == 'VG' or size_whole == 'PVS':
                size_requested = size_percent * this_vg['size'] / 100
            else:  # size_whole == 'FREE':
                size_requested = size_percent * this_vg['free'] / 100
```

First run through size_free is the whole disk, second run through Size free is 0.  Since there is a separate operator of +100%FREE to extend the lv to consume all remaining space or Percentage of remaining space, may be best to set size_requested = this_lv['size'] or not attempt to resize lvms created with %FREE as it will change each run.

### Issue Type

Bug Report

### Component Name

lvol

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL8 controller/RHel7 client

### Steps to Reproduce

```yaml (paste below)
   vars:
    vg: vg_example
    lvm:
      - lv: lv_log
        size: "20%VG"
        mount_point: "/var/log/"
        fs_type: xfs
      - lv: lv_lib
        size: "100%FREE"
        fs_type: xfs
        mount_point: "/var/lib/"

 - name: Create Logical volume "{{ item.lv }}"
      lvol:
        vg: "{{ vg }}"
        lv: "{{ item.lv  }}"
        shrink: no
        size: "{{ item.size }}"
      loop: "{{ lvm }}"

```

### Expected Results

I expected both LVs to be created and be idempotent, and not attempt to change on the second run. and additional runs after that.

### Actual Results

```console (paste below)
failed: [vm-xxx-21] (item={'lv': 'lv_log', 'size': '20%VG', 'mount_point': '/var/log/', 'fs_type': 'xfs'}) => {"ansible_loop_var": "item", "changed": false, "item": {"fs_type": "xfs", "lv": "lv_log", "mount_point": "/var/log/", "size": "20%VG"}, "msg": "Logical Volume lv_log could not be extended. Not enough free space left (3.2m required / 0.0m available)"}
ok: [vm-xxx-21] => (item={'lv': 'lv_lib', 'size': '100%FREE', 'fs_type': 'xfs', 'mount_point': '/var/lib/'})

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
