### ISSUE TITLE
pacman: return details on failure

### ISSUE THREAD

**Issue by antoinep92** [ansible-collections/community.general#3318]
### Summary

When `pacman` fails, the error visible to the master or in the remote logs carry very little information. I understand it mainly depends on flags passed to pacman, like there is one message if upgrading the index failed, and another if upgrading a package failed, etc.

I understand that handling all pacman's return codes, parsing it's output, etc. is a lot of work. What I'm proposing instead, is to send (part of) stdout and/or stderr in the callback in case of a failure, or maybe depending on a new verbosity option ?

In my case, I had an issue on a node with packages signatures, and it just failed with "could no upgrade". Also, when upgrading a dozen of already up-to-date hosts I sometimes get random failures, which is harder to debug as I can't reproduce by calling `pacman` manually on the system (it works).

### Issue Type

Feature Idea

### Component Name

pacman

### Additional Information

```yaml (paste below)
- name: ArchLinux up-to-date
  hosts: all
  tasks:
    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      register: out
    - debug: msg="{{ out }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
