### ISSUE TITLE
django_manage: loaddata fails with more than one fixture argument

### ISSUE THREAD

**Issue by bluetech** [ansible-collections/community.general#3333]
### Summary

I am doing the following:

```yml
- name: manage.py loaddata
  django_manage:
    command: loaddata
    fixtures: "fixture1 fixture2"
    app_path: "{{ my_django_path }}"
```

This used to work well, but broke with the latest ansible, with the following error (trimming the irrelevant parts):

```
fatal: [MyServer]: FAILED! => {"changed": false, "cmd": ["./manage.py", "loaddata", "fixture1 fixture2"], "msg": "\n:stderr: CommandError: No fixture named 'fixture1 fixture2' found.\n"}
```

The problem is that ansible now passes the `fixtures` as a single argument instead of multiple argument split by space. Remember that `django_manage`'s `fixtures` argument has type `string` and is documented as "A space-delimited list of fixture file names to load in the database", that is believe the usage is correct -- a list is not accepted.

### Issue Type

Bug Report

### Component Name

django_manage

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.4] 
  config file = /home/ran/foo/ansible.cfg
  configured module search path = ['/home/ran/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ran/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
TRANSFORM_INVALID_GROUP_CHARS(/home/ran/foo/ansible.cfg) = ignore
```

### OS / Environment

Arch Linux

### Steps to Reproduce

Create some Django project at `my_django_path` and run the below.

```yaml (paste below)
- name: manage.py loaddata
  django_manage:
    command: loaddata
    fixtures: "fixture1 fixture2"
    app_path: "{{ my_django_path }}"
```

### Expected Results

I don't remember the exact message, but should say "2 fixtures loaded" or such.

### Actual Results

```console (paste below)
fatal: [MyServer]: FAILED! => {"changed": false, "cmd": ["./manage.py", "loaddata", "fixture1 fixture2"], "msg": "\n:stderr: CommandError: No fixture named 'fixture1 fixture2' found.\n"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
