### ISSUE TITLE
ini_file: Support multiple option=value pairs to atomically change config ini

### ISSUE THREAD

**Issue by braindevices** [ansible-collections/community.general#3397]
### Summary

currently we can only do with loops:
```
- name: Update configuration
  ini_file:
    path: /etc/influxdb/influxdb.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "monitor", option: "store-interval", value: '"30s"' }
    - { section: "http", option: "log-enabled", value: "false" }
    - { section: "continuous_queries", option: "enabled", value: "false" }
```
but then the config file is not atomically changed, when service read this intermediate change, the service will get confused and error out or even cause damage to the database

We should allow follow way to put multiple options in one go:
```
ini_file:
    path: /tmp/test.ini
    section: plugh
    value:
        foo: bar
        baz: quux
```

The FR has been discussed before https://github.com/ansible/ansible/issues/33856 but closed due to project migration.

### Issue Type

Feature Idea

### Component Name

ini_file

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
