### ISSUE TITLE
mobule for git commits and other git actions 

### ISSUE THREAD

**Issue by mikedlr** [ansible-collections/community.general#3403]
### Summary

In order to be able to check that a git repository is correctly configured I would like to push a commit into that repository.  Having an ansible module that would do that would make sense in my case.

There is a pre-existing module, git_acp.  This has been discussed in https://github.com/ansible/ansible/issues/50334 - I'm primarily creating this issue for discussion of whether it makes sense to merge that into the community collection (or some other collection).  I haven't yet consulted others, however given the author started previous issue I'd guess they'd be willing and happy to have a merge.  

### Issue Type

Feature Idea

### Component Name

git_acp

### Additional Information

```
- name: SSH | push file1 and file2.
  git_acp:
    path: /Users/git/git_acp
    branch: master
    comment: Add file1 and file2.
    add: [ file1, file2 ]
    mode: ssh
    push_option: ci.skip
    url: "git@gitlab.com:networkAutomation/git_test_module.git"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
