### ISSUE TITLE
redfish_config: SetManagerNic Sub-property Address in nic_config is invalid

### ISSUE THREAD

**Issue by tubatodd** [ansible-collections/community.general#3404]
### Summary

Using community.general 3.6.0 ansible module

Running....

```
  - name: Set Manager NIC
    community.general.redfish_config:
      category: Manager
      command: SetManagerNic
      nic_config:
        DHCPv4:
          DHCPEnabled: False
        IPv4StaticAddresses:
          Address: xxx.xxx.xxx.xxx
          Gateway: xxx.xxx.xxx.xxx
          SubnetMask: xxx.xxx.xxx.xxx
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
```

Results in 
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_token": null,
            "baseuri": "10.0.1.103",
            "bios_attributes": {},
            "boot_order": [],
            "category": "Manager",
            "command": [
                "SetManagerNic"
            ],
            "network_protocols": {},
            "nic_addr": "null",
            "nic_config": {
                "DHCPv4": {
                    "DHCPEnabled": false
                },
                "IPv4StaticAddresses": {
                    "Address": "10.0.1.2",
                    "Gateway": "10.0.1.254",
                    "SubnetMask": "255.255.255.0"
                }
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_id": null,
            "timeout": 10,
            "username": "Administrator"
        }
    },
    "msg": "Sub-property Address in nic_config is invalid"
```

### Issue Type

Bug Report

### Component Name

redfish_config

### Ansible Version

Ubuntu 21.04: 2.10.5
Rocky Linux 8.4: 2.9.25

### Configuration

NA

### OS / Environment

Ubuntu 21.04 and Rocky Linux 8.4

### Steps to Reproduce

```
  - name: Set Manager NIC
    community.general.redfish_config:
      category: Manager
      command: SetManagerNic
      nic_config:
        DHCPv4:
          DHCPEnabled: False
        IPv4StaticAddresses:
          Address: xxx.xxx.xxx.xxx
          Gateway: xxx.xxx.xxx.xxx
          SubnetMask: xxx.xxx.xxx.xxx
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
```

### Expected Results

Success

### Actual Results

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_token": null,
            "baseuri": "10.0.1.103",
            "bios_attributes": {},
            "boot_order": [],
            "category": "Manager",
            "command": [
                "SetManagerNic"
            ],
            "network_protocols": {},
            "nic_addr": "null",
            "nic_config": {
                "DHCPv4": {
                    "DHCPEnabled": false
                },
                "IPv4StaticAddresses": {
                    "Address": "10.0.1.2",
                    "Gateway": "10.0.1.254",
                    "SubnetMask": "255.255.255.0"
                }
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_id": null,
            "timeout": 10,
            "username": "Administrator"
        }
    },
    "msg": "Sub-property Address in nic_config is invalid"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
