### ISSUE TITLE
Ansible Jira Community Module exits with error 

### ISSUE THREAD

**Issue by sojancj** [ansible-collections/community.general#3419]
### Summary

When I use ansible jira module for creating jira ticket , it exits with below error . The interesting part it had created the jira ticket , but the task exists with an error . 

To see the full traceback, use -vvv. The error was: KeyError: 'body'
fatal: [f51 -> localhost]: FAILED! => {"changed": false, "msg": "Module failed with exception: 'body'", "output": {"restbase": "https://jira2.domain/rest/api/2", "state": "create"}, "restbase": "https://jira2.domain.com/rest/api/2", "state": "create", "vars": {"restbase": "https://jira2.domain/rest/api/2", "state": "create"}}

### Issue Type

Bug Report

### Component Name

jira

### Ansible Version

```console (paste below)
ansible [core 2.11.3]
  config file = None
  configured module search path = ['/Users/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/user1/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

MAC OSX  BigSur : Version 11.3.1
darwin  20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

### Steps to Reproduce

```yaml (paste below)
- name: Create Subtask Jira for each expiring cert
  jira: 
    uri: https://jira2.domain.com/
    username: "{{jira_username}}"
    password: "{{jira_password}}"
    project: "INF"
    operation: create
    summary: "Certificate:{{outer_item.name}} expiring on {{outer_item.expiration_date}} "
    description: "Certificate Details {{outer_item}}"
    
    issuetype: Sub-task
    validate_certs: False
    
  args:
    fields:
      parent:
        key: 'INF-12345'
      components:
         - name: "INF OPS"
     # labels:
     #   - autocreated
     #   - ansible
        
  delegate_to: localhost
  loop_control: 
    extended: yes 
    label: 
      - "{{outer_item.name}}"

  register: subtask_jira_output
```

### Expected Results

I expect ok and completion of task so that it can continue executing further . but it errors out and stops the task

### Actual Results

```console (paste below)
TASK [Create Subtask Jira for each expiring cert] **********************************************************************************************************************************************************************************
To see the full traceback, use -vvv. The error was: KeyError: 'body'
fatal: [f51 -> localhost]: FAILED! => {"changed": false, "msg": "Module failed with exception: 'body'", "output": {"restbase": "https://jira2.domain/rest/api/2", "state": "create"}, "restbase": "https://jira2.domain.com/rest/api/2", "state": "create", "vars": {"restbase": "https://jira2.domain/rest/api/2", "state": "create"}}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
