### ISSUE TITLE
Failed to validate Terraform configuration files

### ISSUE THREAD

**Issue by tp199314** [ansible-collections/community.general#3421]
### Summary

Hi there,

i was running a short terraform task, which exists with the following error:

Failed to validate Terraform configuration files:
Failed to parse command-line flags
flag provided but not defined: -var
Error: 
Too many command line arguments
Expected at most one positional argument.
For more help on using this command, run:
  terraform validate -help

### Issue Type

Bug Report

### Component Name

terraform

### Ansible Version

```console (paste below)
$ ansible --version
2.9.25.post0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

CentOS

### Steps to Reproduce

```yaml (paste below)

    - name: Deploy resource group for statefiles
      terraform:
        project_path: "{{ terraform_dir }}/tfstatefiles/"
        state: present
        force_init: true
        variables:
          # Subscription credentials
          subscription_id: "{{ awxSubscriptionId }}"
          client_id: "{{ awxClientId }}"
          tenant_id: "{{ awxTenantId }}"
          client_secret: "{{ awxClientSecret }}"
          # Variables for the terraform run
          resource_group_id: "{{ api_resource_group_id }}" # 0900
          location_short: "{{ api_location_short|upper }}" # EUW
          location: "{{ api_location|lower }}" # westeurope
          environment: "{{ api_environment|upper }}" # DEV

```

### Expected Results

terraform task will create azure resources

### Actual Results

```console (paste below)

{
  "msg": "Failed to validate Terraform configuration files:\r\n\u001b[31m╷\u001b[0m\u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mFailed to parse command-line flags\u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\u001b[0mflag provided but not defined: -var\n\u001b[31m╵\u001b[0m\u001b[0m\n\u001b[31m╷\u001b[0m\u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mToo many command line arguments\u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\n\u001b[31m│\u001b[0m \u001b[0m\u001b[0mExpected at most one positional argument.\n\u001b[31m╵\u001b[0m\u001b[0m\n\nFor more help on using this command, run:\n  terraform validate -help\n",
  "invocation": {
    "module_args": {
      "project_path": "/runner/project/terraform/tfstatefiles/",
      "state": "present",
      "force_init": true,
      "variables": {
        "subscription_id": "xxx",
        "client_id": "xxx",
        "tenant_id": "xxx",
        "client_secret": "xxx",
        "resource_group_id": "0900",
        "location_short": "EUW",
        "location": "westeurope",
        "environment": "PRD"
      },
      "workspace": "default",
      "purge_workspace": false,
      "targets": [],
      "lock": true,
      "binary_path": null,
      "variables_file": null,
      "plan_file": null,
      "state_file": null,
      "lock_timeout": null,
      "backend_config": null
    }
  },
  "_ansible_no_log": false,
  "changed": false
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cloud/misc/terraform.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cloud/misc/terraform.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Have you tried installing community.general and using the module from this collection? The module coming with Ansible 2.9 is seriously outdated.

**Comment by tp199314** [comment]
I created a custom execution environment for AWX for my ansible scripts.

I am using the following version:

requirements.yml
```
collections:
  - community.general
```

execution-environment.yml
```
collections:
- RUN wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
```

context/Dockerfile
```
ARG EE_BASE_IMAGE=quay.io/ansible/ansible-runner:stable-2.9-latest
```

The ansible version is ansible 2.9.25.post0

**Comment by tp199314** [comment]
Hi @felixfontein

using community.general.terraform fixed the problem for me.
```
    - name: Deploy resource group for statefiles
      community.general.terraform:
        project_path: "{{ terraform_dir }}/tfstatefiles/"
        state: present
        force_init: true
        variables:
          # Subscription credentials
          subscription_id: "{{ awxSubscriptionId }}"
          client_id: "{{ awxClientId }}"
          tenant_id: "{{ awxTenantId }}"
          client_secret: "{{ awxClientSecret }}"
          # Variables for the terraform run
          resource_group_id: "{{ api_resource_group_id }}" # 0900
          location_short: "{{ api_location_short|upper }}" # EUW
          location: "{{ api_location|lower }}" # westeurope
          environment: "{{ api_environment|upper }}" # DEV
```

Thank you very much!
