### ISSUE TITLE
Can't set virtual media as one-time boot device

### ISSUE THREAD

**Issue by alexdepalex** [ansible-collections/community.general#3423]
### Summary

When trying to set the virtual cd as one-time boot device, the list of allowable values doesn't contain virtual media.

```
fatal: [n-1]: FAILED! => {"changed": false, "msg": "Boot device VCD-DVD not in list of allowable values (['None', 'Pxe', 'Floppy', 'Cd', 'Hdd', 'BiosSetup', 'Utilities', 'UefiTarget', 'SDCard', 'UefiHttp'])"}
```

### Issue Type

Bug Report

### Component Name

community.general.redfish_command

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.5]
  config file = /home/u-1/code/rancher/harvester-helper/ansible.cfg
  configured module search path = ['/home/u-1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/u-1/.venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/u-1/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/u-1/.venv/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/u-1/.vault.d/git_r
```

### OS / Environment

Ubuntu 20.04.2

### Steps to Reproduce

```yaml (paste below)
- name: "Set one-time boot to Virtual Media"
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootdevice: VCD-DVD
    boot_override_mode: Legacy
    baseuri: "{{ node_name }}"
    username: "xx"
    password: "xx"
  register: result
  #when: false
- debug:
    msg: "{{ result }}"
```

### Expected Results

Set the boot device to the virtual media.

### Actual Results

```console (paste below)
fatal: [n-1]: FAILED! => {"changed": false, "msg": "Boot device VCD-DVD not in list of allowable values (['None', 'Pxe', 'Floppy', 'Cd', 'Hdd', 'BiosSetup', 'Utilities', 'UefiTarget', 'SDCard', 'UefiHttp'])"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
