### ISSUE TITLE
[zypper_repository] `state: absent` does not work properly

### ISSUE THREAD

**Issue by gotmax23** [ansible-collections/community.general#3466]
### Summary

When passing `state: absent` to the `community.general_zypper_repository` module, Ansible reports a change but does not actually remove the `.repo` file in `/etc/zypp/repos.d`. This results in a task that does not behave as it should and a non-idempotent playbook.

### Issue Type

Bug Report

### Component Name

zypper_repository

### Ansible-core Version

```console (paste below)
$ ansible --version
 ansible [core 2.11.5] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/hostedtoolcache/Python/3.9.7/x64/bin/ansible
  python version = 3.9.7 (default, Sep  6 2021, 15:30:15) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/runner/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
 ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
```

### OS / Environment

Control Node: Github Actions Runner using Molecule
Targets: OpenSUSE Leap 15.2, OpenSUSE 15.3, and OpenSUSE Tumbleweed running in Podman containers.

Notably, this issue occurs on OpenSUSE Leap but not Tumbleweed. Also, Molecule bundles its own `ansible.cfg` file which more changes besides `ANSIBLE_FORCE_COLOR` that's show above; Here is a copy of that file:

``` ini
# Molecule managed

[defaults]
ansible_managed = Ansible managed: Do NOT edit this file manually!
display_failed_stderr = True
forks = 50
retry_files_enabled = False
host_key_checking = False
nocows = 1
interpreter_python = auto_silent
stdout_callback = yaml
[ssh_connection]
scp_if_ssh = True
control_path = %(directory)s/%%h-%%p-%%r
```

### Steps to Reproduce

I uncovered this bug by testing an Ansible role I wrote to install the Packman repository on SUSE. The actual code is located at [https://github.com/gotmax23/ansible-role-packman/tree/issue1](https://github.com/gotmax23/ansible-role-packman/tree/issue1), but here is a simplified playbook that demonstrates the bug.
```yaml (paste below)
---
- name: Install Packman Repository
  become: true

  vars:
    packman_state: present  # Run a second time with `absent` to reproduce the bug
    _packman_repo_url:
      "openSUSE Leap": "https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/"
      "openSUSE Tumbleweed": "https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/"
    packman_repo_url: "{{ _packman_repo_url[ansible_distribution] }}"

    _packman_gpg_key_url:
      "openSUSE Tumbleweed": "https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/repodata/repomd.xml.key"
      "openSUSE Leap": "https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_{{ ansible_distribution_version }}/repodata/repomd.xml.key"
    packman_gpg_key_url: "{{ _packman_gpg_key_url[ansible_distribution] }}"

    packman_gpg_key_fingerprint: "F887 5B88 0D51 8B6B 8C53  0D13 45A1 D067 1ABD 1AFB"

  tasks:
    - name: Install/Remove Packamn GPG key
      ansible.builtin.rpm_key:
        key: "{{ packman_gpg_key_url }}"
        state: "{{ packman_state }}"

    - name: Install/Remove Packman Repository
      notify: zypper_dist_upgrade
      community.general.zypper_repository:
        name: packman
        refresh: true
        priority: 90
        repo: "{{ packman_repo_url }}"
        state: "{{ packman_state }}"

```
I implemented a temporary fix in [this commit](https://github.com/gotmax23/ansible-role-packman/commit/d4134a75e1a93b515ebd65aa4fc510b9878f92d5) by adding an extra step to manually delete the `/etc/zypp/repos.d/packman.repo` file using the `file` module.

### Expected Results

For the module to actually remove the repository

### Actual Results

This includes only the relevant part (removing the repository) of the output. I only used  `-v` because `-vvvv` produces extra clutter that is not relevant to this issue. You can also take a look at [this Github Actions job](https://github.com/gotmax23/ansible-role-packman/runs/3736989967?check_suite_focus=true) which includes the full Molecule run, including the failed idempotency and verify tests.

```console (paste below)
  Using /home/runner/.cache/molecule/ansible-role-packman/single/ansible.cfg as config file
  
  PLAY [Converge] ****************************************************************
  
  TASK [Gathering Facts] *********************************************************
  ok: [packman-single-opensuse-15.3]
  
[...]
  
  TASK [gotmax23.packman : Remove Packamn GPG key] *******************************
  changed: [packman-single-opensuse-15.3] => changed=true
  
  TASK [gotmax23.packman : Remove Packman Repository] ****************************
  changed: [packman-single-opensuse-15.3] => changed=true 
    repodata:
      alias: packman
      autorefresh: '1'
      enabled: '1'
      gpgcheck: '1'
      name: null
      priority: 90
      url: https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/
    state: absent
  
  RUNNING HANDLER [gotmax23.packman : zypper_dist_upgrade] ***********************
  skipping: [packman-single-opensuse-15.3] => changed=false 
    skip_reason: Conditional result was False
  
  PLAY RECAP *********************************************************************
  packman-single-opensuse-15.3 : ok=8    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
