### ISSUE TITLE
gitlab_user should only modify provided fields

### ISSUE THREAD

**Issue by atosscsd-bb** [ansible-collections/community.general#3483]
### Summary

I'm trying to add SSH-keys to exsiting users:
```
- name: Add public key to GitLab user
  community.general.gitlab_user:
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_admin_token }}"
    username: "{{ gitlab_username }}"
    name: "{{ full_name }}"
    email: "{{ email }}"
    sshkey_name: "{{ gitlab_username }}@{{ ansible_hostname }}"
    sshkey_file: "{{ lookup('file', public_key_file) }}"
    state: present
```

When `gitlab_username` is an admin-account, the task removes the admin privileges as `isadmin` defaults to `false `.

Therefore `gitlab_user` should only modify the fields provided.

### Issue Type

Feature Idea

### Component Name

community.general.gitlab_user

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
