### ISSUE TITLE
apache2_module: using apachectl and broken ignore_configcheck

### ISSUE THREAD

**Issue by wolfgangkarall** [ansible-collections/community.general#3510]
### Summary

apache2_module uses `apachectl -M` in _module_is_enabled(), which depends on a working configuration, otherwise apachectl dies with:

```
<actual config problem as described by apachectl -t>
Action '-M' failed.
The Apache error log may have more information.
```

This means there is a dependency on the order of tasks, i.e.you have to enable the module first _before_ writing a configuration snippet that uses one of the directives the module provides. Same for disabling, first remove the snippet, then disable the module.

Using plain a2enmod/a2dismod, no such requirement exists. And it would be nice if this module wouldn't have, either.

Related to this, and the actual bug: there's ignore_configcheck, but it is not really helpful and results in misleading and wrong output. For example, take a loop with 2 items, where the first item is a module that is in active use:

```
- hosts: somehost
  tasks:
    - apache2_module:
        name: "{{ item }}"
        state: absent
        ignore_configcheck: true
      loop:
        # AuthGroupFile is used somehwere, but we disable it regardless
        - authz_groupfile
        - headers
```

Now, in the first run, if both the modules were enabled before, you get:

```
$ ansible-playbook apache2_modules.yml

PLAY [somehost] ****************************************************************************************************

TASK [apache2_module] *******************************************************************************************************
changed: [somehost] => (item=authz_groupfile)
ok: [somehost] => (item=headers)
[WARNING]: Error executing /usr/sbin/apache2ctl: AH00526: Syntax error on line 18 of /etc/apache2/sites-enabled/somefile.conf: Invalid command 'AuthGroupFile', perhaps misspelled or defined by a module not included in the server
configuration

PLAY RECAP ******************************************************************************************************************
somehost          : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

So, one changed, one ok, but the problem is, the module 'headers' is still enabled.

```
$ ssh somehost ls -l /etc/apache2/mods-enabled/headers.load
lrwxrwxrwx 1 root root 30 Oct  4 13:41 /etc/apache2/mods-enabled/headers.load -> ../mods-available/headers.load
```

And subsequent runs of that simple playbook will give you 2x ok, but the headers module will stay enabled.

So, the WARNING about the syntax problem is nice and all, but it breaks the promise that 'ok' means 'the module completed its work successfully'.

### Issue Type

Bug Report

### Component Name

apache2_module

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.12.post0
  config file = /home/user/work/ansible/all/playbooks/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/work/ansible/lib/ansible
  executable location = /home/user/work/ansible/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/user/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 2.4.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
```

### Steps to Reproduce

```yaml (paste below)
- hosts: somehost
  tasks:
    - apache2_module:
        name: "{{ item }}"
        state: absent
        ignore_configcheck: true
      loop:
        # AuthGroupFile is used somehwere, but we disable it regardless
        - authz_groupfile
        - headers
```

### Expected Results

I expected the headers module to be disabled.

### Actual Results

```console (paste below)
# the headers module is still enabled on the host
$ ssh somehost ls -l /etc/apache2/mods-enabled/headers.load
lrwxrwxrwx 1 root root 30 Oct  4 13:41 /etc/apache2/mods-enabled/headers.load -> ../mods-available/headers.load
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
