### ISSUE TITLE
ZFS extra options with ":" is not allowed

### ISSUE THREAD

**Issue by TheJenne18** [ansible-collections/community.general#3513]
### Summary

We use a setup property with a ";" in it. In this case we would like to do this:
```- name: "Setup backup location"
  zfs:
    name: "{{ item.dataset }}"
    state: present
    extra_zfs_properties:
      "autobackup:offsite1": true
  with_items: "{{ zfs_backups }}"
```

Because their is a ':' in the propery (aldo it is within double quotes), offsite 1 is seen  as the value.

Result: `    cannot set property for '<dataset>': invalid property 'autobackup:offsite1'` 

### Issue Type

Bug Report

### Component Name

zfs

### Ansible Version

```
ansible 2.9.18

```

### Community.general Version

```
v2.2.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Debian

### Steps to Reproduce

```
- name: "Setup backup location"
  zfs:
    name: "{{ item.dataset }}"
    state: present
    extra_zfs_properties:
      "autobackup:offsite1": true
  with_items: "{{ zfs_backups }}"

```

### Expected Results

```
root@testjens-client:~# zfs get -t filesystem,volume autobackup:offsite1
NAME            PROPERTY             VALUE                SOURCE
main            autobackup:offsite1  true                 local
main/test       autobackup:offsite1  true                 inherited from main
main/test2  autobackup:offsite1  true                 inherited from main
```

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
