### ISSUE TITLE
gitlab_deploy_key failed to enable key already uploaded to gitlab

### ISSUE THREAD

**Issue by giuliotripi** [ansible-collections/community.general#3516]
### Summary

When I try to add the same deploy key to multiple repos, after the key has been uploaded the first time, I get an error on the next attempts because the key is duplicated. I think that the key should be enabled and not created again for each project.

### Issue Type

Bug Report

### Component Name

community.general.gitlab_deploy_key

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.0.dev0] (devel 0c8b62b527) last updated 2021/10/05 21:22:15 (GMT +200)
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 3.0.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 3.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

local Ubuntu 21.04, remote Debian 10

### Steps to Reproduce

```yaml (paste below)
- name: add this deploy key in gitlab
      community.general.gitlab_deploy_key:
        api_url: https://gitlab.com/
        api_token: "your_api_token"
        project: "{{ item.repo }}"
        title: "{{ ansible_facts['nodename'] }} deploy key"
        state: present
        key: "{{ created_ssh_key.public_key }}"
      loop:
        - {repo: "username/project1"}
        - {repo: "username/project2"}
        - {repo: "username/project3"}
- name: disable this deploy key in gitlab
      community.general.gitlab_deploy_key:
        api_url: https://gitlab.com/
        api_token: "your_api_token"
        project: "{{ item.repo }}"
        title: "{{ ansible_facts['nodename'] }} deploy key"
        state: absent
        key: "{{ created_ssh_key.public_key }}"
      loop:
        - {repo: "username/project1"}
        - {repo: "username/project2"}
        - {repo: "username/project3"}
 - name: try to add this deploy key in gitlab again
      community.general.gitlab_deploy_key:
        api_url: https://gitlab.com/
        api_token: "your_api_token"
        project: "{{ item.repo }}"
        title: "{{ ansible_facts['nodename'] }} deploy key"
        state: present
        key: "{{ created_ssh_key.public_key }}"
      loop:
        - {repo: "username/project1"}
        - {repo: "username/project2"}
        - {repo: "username/project3"}
```

### Expected Results

I expect the deploy key to be added to the all the repositories.

### Actual Results

After it is uploaded once, it is impossible to upload it again. Instead, I think, it should be [enabled](https://python-gitlab.readthedocs.io/en/stable/gl_objects/deploy_keys.html#:~:text=project.keys.enable(key_id)) and not added once is added in at least one repository, as I can do in the GitLab GUI.
![imageedit_2_7104892856](https://user-images.githubusercontent.com/7399875/136097706-9cb44b30-44a0-4145-80c1-fd4b01525c0d.png)

```console (paste below)
failed: [host] (item={'repo': 'user/project'}) => {"ansible_loop_var": "item", "changed": false, "item": {"repo": "user/project"}, "msg": "Failed to create deploy key: 400: {'deploy_key.fingerprint': ['has already been taken']} "}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
