### ISSUE TITLE
keycloak_role should allow special characters in role name

### ISSUE THREAD

**Issue by laurpaum** [ansible-collections/community.general#3535]
### Summary

Using the keycloak_role module with role names containing special characters causes an error when calling the Keycloak API.

### Issue Type

Bug Report

### Component Name

keycloak_role

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.5.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/runner/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
```

### Steps to Reproduce

```yaml (paste below)
  - name: Create Keycloak realm role
    community.general.keycloak_role:
      auth_keycloak_url: https://keycloak.example.com/auth
      auth_realm: master
      auth_username: admin
      auth_password: password
      realm: myrealm
      name: my role
      state: present
```

### Expected Results

Role with name "my role" exists

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not fetch role my role in realm myrealm: URL can't contain control characters. '/auth/admin/realms/myrealm/roles/my role' (found at least ' ')"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
