### ISSUE TITLE
keycloak_identity_provider fails to detect mappers change

### ISSUE THREAD

**Issue by laurpaum** [ansible-collections/community.general#3537]
### Summary

When updating an identity provider with only changes to mappers, the module fails to detect the change and does not apply the required updates.

### Issue Type

Bug Report

### Component Name

keycloak_identity_provider

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.5.post0]   config file = None  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections  executable location = /usr/local/bin/ansible  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]  jinja version = 2.10.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
# /home/runner/.ansible/collections/ansible_collectionsCollection        Version
----------------- -------
community.general 3.7.0  
```

### Steps to Reproduce

```yaml (paste below)
  - name: Create identity provider
    community.general.keycloak_identity_provider:
      auth_keycloak_url: https://keycloak.example.com/auth
      auth_realm: master
      auth_username: admin
      auth_password: password
      realm: myrealm
      alias: myidp
      display_name: OpenID Connect IdP
      provider_id: oidc
      config:
        issuer: https://idp.example.com
        authorizationUrl: https://idp.example.com/auth
        tokenUrl: https://idp.example.com/token
        userInfoUrl: https://idp.example.com/userinfo
        clientAuthMethod: client_secret_post
        clientId: clientid
        clientSecret: secret
        syncMode: FORCE
      mappers:
        - name: "first_name"
          identityProviderAlias: "myidp"
          identityProviderMapper: "oidc-user-attribute-idp-mapper"
          config:
            claim: "first_name"
            user.attribute: "first_name"
            syncMode: "INHERIT"
      state: present

  - name: Update identity provider mappers
    community.general.keycloak_identity_provider:
      auth_keycloak_url: https://keycloak.example.com/auth
      auth_realm: master
      auth_username: admin
      auth_password: password
      realm: myrealm
      alias: myidp
      mappers:
        - name: "first_name"
          identityProviderAlias: "myidp"
          identityProviderMapper: "oidc-user-attribute-idp-mapper"
          config:
            claim: "first_name"
            user.attribute: "first_name"
            syncMode: "INHERIT"
        - name: "last_name"
          identityProviderAlias: "myidp"
          identityProviderMapper: "oidc-user-attribute-idp-mapper"
          config:
            claim: "last_name"
            user.attribute: "last_name"
            syncMode: "INHERIT"
      state: present
```

### Expected Results

Second task should update the identity provider to add the new mapper.

### Actual Results

Identity provider is not updated.

```console (paste below)
TASK [Create identity provider] ********************
changed: [localhost]

TASK [Update identity provider mappers] *************
ok: [localhost]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
