### ISSUE TITLE
DNSimple does not return records

### ISSUE THREAD

**Issue by edhilgendorf** [ansible-collections/community.general#3569]
### Summary

According to dnsimple docs [1] it should be possible to list all records of a given domain but it actually is not.

### Issue Type

Bug Report

### Component Name

dnsimple

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.6


```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
3.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Fetch my.com domain records
  community.general.dnsimple:
    domain: my.com
    state: present
  delegate_to: localhost
  register: records

```

### Expected Results

all records from the my.com domain in a list/dictionary/etc

### Actual Results

```console (paste below)
info about the domain, no records
```
@drcapulet

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
cc @drcapulet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by edhilgendorf** [comment]
Hi, in the examples section:
```
- name: Fetch my.com domain records
  community.general.dnsimple:
    domain: my.com
    state: present
  delegate_to: localhost
  register: records
```
In the DNSimple UI if you click "my.com" records, you will see a list of records. This task seems to imply that records variable should hold the records to my.com domain.

**Comment by edhilgendorf** [comment]
Thanks for checking, I believe this is the most recent version:
`dnsimple in /home/user/.local/lib/python3.8/site-packages (2.2.1)`
general version is:
```
collections:
  - name: community.general
    version: 3.7.0
```

**Comment by edhilgendorf** [comment]
The action of "fetch" on "state: present" does not make a lot of sense to begin with, and is a little counter-intuitive.. If the domain doesn't exist this actually CREATES if it does not exist. Which can be pretty dangerous, for ex:
you have records under my.com:
ex1.subdomain.my.com
ex2.subdomain.my.com

and you run with this domain in attempt to see what is under "subdomain.my.com" expecting the above to return. Instead it creates an entire new domain "subdomain.my.com" which then breaks resolution for the existing records.
Similar seems to be true for adding records:
```
- name: Create a test.my.com A record to point to 127.0.0.1
  community.general.dnsimple:
    domain: my.com
    record: test
    type: A
    value: 127.0.0.1
  delegate_to: localhost
  register: record
```
Without "state" you would think this might just check if the record exists, instead it creates it... State is required for removing a record, seems like it ought to be the same for adding. Same way that "state: present" does not make a lot of sense for:
"if the domain exists, **fetch** records, if not create the domain"
Instead it should just be "if state is present and the domain exists, show the domain exists(**unchanged**) if not, create it".
But I guess this is up to the author, I am pretty new to this
