### ISSUE TITLE
[Feature Request] [zypper] Allow refreshing cache without specifying `name:`

### ISSUE THREAD

**Issue by gotmax23** [ansible-collections/community.general#3570]
### Summary

Currently, it is not possible to update the package cache with the `community.general.zypper` module without specifying the `name` argument.

This task fails with the following error message:

``` console
$ ansible all -i inventory -b -m zypper -a update_cache=true
hostname | FAILED! => {
    "changed": false,
    "msg": "missing required arguments: name"
}
```

This usecase is supported by every other distro package module (or at least the ones I've used). This includes `apt`, `yum`, `dnf`, `pacman`, and `apk`.

This missing feature makes updating the package cache in my gotmax23.update role unnecessarily complicated.

``` yaml
- name: Update package cache
  changed_when: false
  when: ansible_pkg_mgr != "zypper"
  ansible.builtin.package:
    update_cache: true

- name: Update package cache (Zypper only)
  when: ansible_pkg_mgr == "zypper"
  changed_when: false
  check_mode: false
  ansible.builtin.command:
    cmd: "zypper refresh"
    warn: false
```

-- https://git.sr.ht/~gotmax23/ansible-role-update/tree/d3ef47593f85fb917e6cc71833970f03994bf5ab/item/molecule/all/molecule.yml

### Issue Type

Feature Idea

### Component Name

plugins/modules/packaging/os/zypper.py

### Additional Information

The example playbook below does not work.

```yaml (paste below)
- name: Update Zypper Cache
  community.general.zypper:
    update_cache: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/packaging/os/zypper.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/os/zypper.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @AnderEnder @alxgu @andytom @commel @dcermak @evrardjp @lrupp @sealor @toabctl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/zypper.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/zypper.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Hummdis** [comment]
I was looking for something else, like using `zypper clean --all` via a native Ansible way when I came across this feature request.

Why add this to `zypper` when you can use `zypper_repository`? I'm playing devils advocate here, but you can do this using something like:
```
- name: Building Zypper Cache...
  community.general.zypper_repository:
    repo: '*'
    runrefresh: true
    auto_import_keys: true
```
 While YUM has the `yum_repository` module for managing repos and Apt has the `apt_repository` module, Zypper has `zypper_repository`.
