### ISSUE TITLE
Implement persistent/non persistent flag for OpenNebula images

### ISSUE THREAD

**Issue by peterloeffler** [ansible-collections/community.general#3578]
### Summary

Using the module plugins/modules/cloud/opennebula/ it is not possible to define or change the persistent flag for an image.
Would be helpful for example if you have a cloud image and want to update packages.

### Issue Type

Feature Idea

### Component Name

one_image

### Additional Information

```
- name: Clone the IMAGE by name
  community.general.one_image:
    name: bar-image
    persistent: yes
    state: cloned
    new_name: bar-image-clone
  register: result

--- do some other stuff like OS upgrades

- name: Rename existing IMAGE
  community.general.one_image:
    id: result.id
    persistent: no
    state: renamed
    new_name: bar-image-new
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
