### ISSUE TITLE
Haproxy: Allow passing multiple backends

### ISSUE THREAD

**Issue by jameswilliams1** [ansible-collections/community.general#3594]
### Summary

It's possible to either not pass a backend pool (and use all available) or pass only a single backend, but not pass a specific list of backends. Looking at the code it already works with a list, but the module expects a string as user input (and makes a list of one). Ideally if the input is type list it should pass this through directly so users can specify a group of backends rather than resorting to looping manually.

### Issue Type

Feature Idea

### Component Name

haproxy

### Additional Information

```yaml (paste below)
- name: Set the server in 'www' and 'ww2' backend pool to drain mode
  community.general.haproxy:
    state: drain
    host: '{{ inventory_hostname }}'
    socket: /var/run/haproxy.sock
    backend:
      - www
      - ww2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
