### ISSUE TITLE
Opentelemetry: error handling for loops does not provide enough context

### ISSUE THREAD

**Issue by v1v** [ansible-collections/community.general#3597]
### Summary

When the playbook failed in some cases the reported error does not show any meaningful information but the below details:

```
message: "All items completed"
exception: "None"
stderr: "None"
```

As far as I see `All items completed` might be related to a loop -> https://github.com/ansible/ansible/blob/6319a0f415e5fcc966e5424bb2191b19e770cf49/docs/docsite/rst/user_guide/playbooks_loops.rst#registering-variables-with-a-loop

### Issue Type

Bug Report

### Component Name

opentelemetry

### Ansible Version

2.9

### Community.general Version

3.8.0  

### OS / Environment

Linux ubuntu 20

### Steps to Reproduce

```
---
- name: Echo
  hosts: localhost
  connection: local

  tasks:
  - name: Register loop output as a variable
    shell: "exit {{ item }}"
    loop:
      - 0
      - 1
      - 2
    register: echo
```

### Expected Results

```console (paste below)
message: "non-zero return code"
exception: "None"
stderr: "None"
```

### Actual Results

```console (paste below)
message: "All items completed"
exception: "None"
stderr: "None"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
