### ISSUE TITLE
keycloak_client detects changes on check_mode regarding `redirectUris`, `attributes`, and `protocol_mappers`

### ISSUE THREAD

**Issue by pmdumuid** [ansible-collections/community.general#3609]
### Summary

When I have a task that creates a keycloak client:

```
  community.general.keycloak_client: 
    # .. auth_args
    realm: "{{ realm }}"
    client_id: "{{ client_id }}"
    state: present
    redirect_uris: '{{redirect_uris1}}'
    attributes: '{{client_attributes1}}'
    protocol_mappers: '{{protocol_mappers1}}'
```

When I run the step once, it creates the client.
When I run the step a second time, it determines there are not changes, but when I run it in `--check` mode it determine there are.

### Issue Type

Bug Report

### Component Name

keycloak_client

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.0] 
  config file = None
  configured module search path = ['/home/pmdumuid/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pmdumuid/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/pmdumuid/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/pmdumuid/.local/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True


```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

As per in the description above.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
