### ISSUE TITLE
parted module return docs appear to have the wrong field name

### ISSUE THREAD

**Issue by abadger** [ansible-collections/community.general#362]
##### SUMMARY
The returndocs for parted say that the return will contain two fields, one named `device` and the other named `partitions:`
```
  contains:
    device:
      description: Generic device information.
      type: dict
    partitions:
      description: List of device partitions.
      type: list
```
https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/parted.py#L110

In reality it looks like one is named `disk` and the other is named `partitions`: https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/parted.py#L689

The module also seems to return `script` which seems to be the commands passed to parted over the course of the module's run.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
parted.py

##### ANSIBLE VERSION

```paste below

```
