### ISSUE TITLE
Redfish: Add support to configure Redfish Host Interface

### ISSUE THREAD

**Issue by jyundt** [ansible-collections/community.general#3631]
### Summary

Using `redfish_config`, I would like to be able to configure the Redfish Host Interface. Specifically, I'd like to toggle the `InterfaceEnabled` property to enable or disable the Redfish Host Interface.

### Issue Type

Feature Idea

### Component Name

redfish_config

### Additional Information

Currently we are using the `uri` module with (some) hardcoded URIs to enable or disable the RF HI.

One example:
```
- name: Capture current redfish host interface status
  become: false
  uri:
    url: "https://{{ bmc_address }}/{{ redfish_uri }}"
    method: GET
    user: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    timeout: "{{ default_uri_timeout }}"
  register: redfish_interface_status
  delay: "{{ default_uri_delay }}"
  retries: "{{ default_uri_retries }}"
  until: redfish_interface_status is succeeded
  changed_when: False
  vars:
    redfish_uri: "redfish/v1/Managers/1/HostInterfaces/1"
  delegate_to: 127.0.0.1

- name: Disable redfish host interface
  become: false
  uri:
    url: "https://{{ bmc_address }}/{{ redfish_uri }}"
    method: PATCH
    user: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
    validate_certs: no
    force_basic_auth: yes
    timeout: "{{ default_uri_timeout }}"
    body_format: json
    body:
      InterfaceEnabled: False
  register: redfish_host_interface_disable_status
  delay: "{{ default_uri_delay }}"
  retries: "{{ default_uri_retries }}"
  until: redfish_host_interface_disable_status is succeeded
  changed_when: True
  vars:
    redfish_uri: "redfish/v1/Managers/1/HostInterfaces/1"
  delegate_to: 127.0.0.1
  when:
    - redfish_interface_status.json.InterfaceEnabled
```

I would like to replace this with a `redfish_config` command like:
```
- name: Enable HostInterface
  community.general.redfish_config:
    category: Manager
    command: SetHostInterface 
    hostinterface_config:
      InterfaceEnabled: true
    baseuri: "{{ bmc_address }}"
    username: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
