### ISSUE TITLE
ini_file doesn't support multiline values (backslash at EOL)

### ISSUE THREAD

**Issue by bendem** [ansible-collections/community.general#3663]
### Summary

When changing an ini value containing multiple lines, only the line with the option is removed and the rest of the value is left in the file.

### Issue Type

Bug Report

### Component Name

ini_file

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.6] 
  config file = /home/demarteaub/projects/infra/ansible/ansible.cfg
  configured module search path = ['/home/demarteaub/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/demarteaub/.local/share/virtualenvs/ansible-JeMCc-2q/lib/python3.8/site-packages/ansible
  ansible collection location = /home/demarteaub/projects/infra/ansible/vendors/collections:/home/demarteaub/projects/infra/ansible/collections
  executable location = /home/demarteaub/.local/share/virtualenvs/ansible-JeMCc-2q/bin/ansible
  python version = 3.8.6 (default, Jun 29 2021, 21:14:45) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/demarteaub/.local/share/virtualenvs/ansible-JeMCc-2q/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.0  

# /home/demarteaub/projects/infra/ansible/vendors/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.1  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/demarteaub/projects/infra/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/home/demarteaub/projects/infra/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
COLLECTIONS_PATHS(/home/demarteaub/projects/infra/ansible/ansible.cfg) = ['/home/demarteaub/projects/infra/ansible/vendors/collections', '/home/demarteaub/projects/infra/ansible/collections']
DEFAULT_HOST_LIST(/home/demarteaub/projects/infra/ansible/ansible.cfg) = ['/home/demarteaub/projects/infra/ansible/inventory/inventory.ini']
DEFAULT_ROLES_PATH(/home/demarteaub/projects/infra/ansible/ansible.cfg) = ['/home/demarteaub/projects/infra/ansible/vendors/roles', '/home/demarteaub/projects/infra/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/demarteaub/projects/infra/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/demarteaub/projects/infra/ansible/ansible.cfg) = 5
DEFAULT_VAULT_ID_MATCH(/home/demarteaub/projects/infra/ansible/ansible.cfg) = true
DIFF_ALWAYS(/home/demarteaub/projects/infra/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/home/demarteaub/projects/infra/ansible/ansible.cfg) = /usr/bin/python3
INVENTORY_UNPARSED_IS_FAILED(/home/demarteaub/projects/infra/ansible/ansible.cfg) = True
```

### OS / Environment

RockyLinux 8 controller, CentOS 8 server, python3

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  tasks:
    - name: Set ini values
      community.general.ini_file:
        path: "/tmp/test.ini"
        section: "test"
        option: "option"
        value: |-
          something \
            multiline

    - name: Set ini values
      community.general.ini_file:
        path: "/tmp/test.ini"
        section: "test"
        option: "option"
        value: |-
          other things \
            completely
```

### Expected Results

```
[test]
option = other things \
  completely
```

### Actual Results

```
[test]
option = other things \
  completely
  multiline
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
