### ISSUE TITLE
Add --apply-live option for rpm-ostree module

### ISSUE THREAD

**Issue by MisterWS** [ansible-collections/community.general#3670]
### Summary

I would like to be able to have the option to run `rpm-ostree` with the --apply-live flag, so that I don't have to restart my Fedora CoreOS machines before the packages apply.

### Issue Type

Feature Idea

### Component Name

rpm_ostree_pkg

### Additional Information

Example of current task & handler file:

```yaml
- name: Install needed packages
  community.general.rpm_ostree_pkg:
    name:
      - zsh
  notify: Reboot server

- name: Flush handlers
  meta: flush_handlers
```

```yaml
- name: Reboot server
  ansible.builtin.reboot:
```

Offering the option to --apply-live would remove the need for the reboot

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/packaging/os/rpm_ostree_pkg.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/os/rpm_ostree_pkg.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Akasurde @dustymabe
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by TkPegatron** [comment]
I would like this feature as well.

Though, I can already see a drawback where doing something like so could perhaps cause some confusion:

```yaml
- name: Install needed packages
  community.general.rpm_ostree_pkg:
    name:
      - zsh
    state: present
    apply_live: true
```

- Is the intention to apply to the live system and not have the package on the next boot with a single `rpm-ostree install --apply-live`?

- Or does the module execute first `rpm-ostree install zsh` followed by `rpm-ostree ex apply-live --allow-replacement`?

This comes down to the behavior of `rpm-ostree` in its current state since the first `install` command stages the packages for the next "booted branch" while the second `ex apply-live` patches the currently "booted branch" but running `rpm-ostree install --apply-live` overlays the packages to the booted tree but does not stage it for the next "booted branch".

An alternative way is to use a trinary of options for the `apply_live` argument, such as `['false','overlay','staged']`. `overlay` would simply append `--apply-live` to the list of arguments in the module, `staged` will follow the default command generated by the module with a second `ex apply-live` command, while the default`false` would keep the current behavior of the module.
