### ISSUE TITLE
community.general.udm_user - no primary group handling

### ISSUE THREAD

**Issue by Nox-404** [ansible-collections/community.general#3691]
### Summary

When trying to create a user with `udm_user`, we cannot set the `primary_group`

### Issue Type

Bug Report

### Component Name

community.general.udm_user

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.14
  python version = 3.6.8
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 1.3.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

CentOS 7

### Steps to Reproduce

```yaml
- udm_user:
    name: user1
    password: password1
    primary_group: cn=mygroup,cn=groups,dc=my-domain,dc=my-tld
```

### Expected Results

The user should have `mygroup` as primary group.

### Actual Results

The user will have `Domain Users` for it's primary group.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
