### ISSUE TITLE
redfish_command: example command has wrong arg

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/community.general#3710]
### Summary

The example in `redfish_command` is missing underscore in the arg `boot_next`:
```yaml
- name: Set one-time boot to BiosSetup
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootnext: BiosSetup
    boot_override_mode: Legacy
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
```

There is another example command that has the right arg:
```yaml
- name: Set one-time boot device to BootNext target of "Boot0001"
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    resource_id: 437XR1138R2
    bootdevice: "UefiBootNext"
    boot_next: "Boot0001"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
```

### Issue Type

Bug Report

### Component Name

redfish_command

### Ansible Version

```console (paste below)
$ ansible --version
2.11.6
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
not relevant
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
not relevant
```

### OS / Environment

not relevant

### Steps to Reproduce

Try to execute the example command would fail with unknown arg `bootnext`.

### Expected Results

The example command should have the right arg.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
