### ISSUE TITLE
nmcli module does not change dns4_search

### ISSUE THREAD

**Issue by Atoms** [ansible-collections/community.general#3728]
### Summary

I want to change only `dns4_search` setting for connection on the GCP instance. As GCP instance configuration is strict we need to ensure OS appends DNS search domains, to ensure that command to add domain is: 
`nmcli connection modify $conenction_name ipv4.dns-search "some.domain"` 

when executing ansible task with just change dns_search parameter it returns

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.5]
  config file = /home/xxx/projects/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/projects/ansible/.env/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/projects/ansible/.env/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/xxx/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0

# /home/xxx/projects/ansible/.env/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_HASH_BEHAVIOUR(/home/asterns/projects/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/asterns/projects/ansible/ansible.cfg) = ['/home/asterns/projects/ansible/inventory']
DEFAULT_STDOUT_CALLBACK(/home/asterns/projects/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON(/home/asterns/projects/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

Centos8

### Steps to Reproduce

```yaml
- name: "Get connection name"
  shell: "nmcli -t -f GENERAL.CONNECTION d show eth0 | cut -d \\: -f 2"
  register: connection_name
  become: yes

- name: "Configure proper search domains in GCP"
  nmcli:
    conn_name: "{{ connection_name.stdout }}"
    dns4_search: 
      - "dome.domain"
    state: present
  become: yes
  notify: restart NetworkManager
```

### Expected Results

DNS search domains are added and NetworkManager restarted

### Actual Results

DNS search domain is not added and NetworkManager is not restarted

if NetworkManager is restarted after change it still does not have configured search domains

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
