### ISSUE TITLE
UFW proto icmp not supported for no reason

### ISSUE THREAD

**Issue by DBLaci** [ansible-collections/community.general#3730]
### Summary

```
- community.general.ufw:
  rule: allow
  proto: icmp
  src: 192.168.50.0/24
```

Error:

    fatal: [ub3]: FAILED! => {"changed": false, "msg": "value of proto must be one of: ah, any, esp, ipv6, tcp, udp, gre, igmp, got: icmp"}

But there is an "icmp" proto supported by ufw (iptables). If I add this to /etc/ufw/user.rules

```
### tuple ### allow any any 0.0.0.0/0 any 192.168.50.0/24 in
-A ufw-user-input -p icmp -s 192.168.50.0/24 -j ACCEPT
```

It works fine.

I propose adding icmp to the list of supported protos in the system/ufw.py

### Issue Type

Feature Idea

### Component Name

ufw

### Additional Information

```yaml (paste below)
- community.general.ufw:
  rule: allow
  proto: icmp
  src: 192.168.50.0/24
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
