### ISSUE TITLE
Please add wireguard connection type for nmcli module

### ISSUE THREAD

**Issue by Yvan-Masson** [ansible-collections/community.general#3750]
### Summary

Hi,

I would like to use the `nmcli` module to create Wireguard connections, but it does not seem to be possible yet (`wireguard` is not valid for the `type` parameter). I believe Wireguard is widely used.

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

```yaml (paste below)
- name: add Wireguard connection
  community.general.nmcli:
    type: wireguard
    autoconnect: false
    conn_name: wg_example
    wg-private-key: "{ my_private_key }"
    wg-private-key-policy: "always_ask"
    wg-peer:
      wg-public-key: "{ peer_public_key }"
      wg-peer-ip: "{ peer_ip }"
    ip4: 10.0.0.2/24
    method6: disabled
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
