### ISSUE TITLE
extend open_iscsi to allow rescanning a session to discover new mapped LUN's

### ISSUE THREAD

**Issue by michaelalang** [ansible-collections/community.general#3763]
### Summary

I want to ask for the feature of _rescanning_ a session to discover new mapped LUN targets.
Targetd configurations with multiple mapped LUN's at a Target can not be addressed with the current features.

The patch below POCs how to add a _rescan_ feature to the module.

```bash
--- ./lib/python3.6/site-packages/ansible_collections/community/general/plugins/modules/system/open_iscsi.py	2021-11-17 20:05:32.490394594 +0100
+++ ./lib/python3.6/site-packages/ansible_collections/community/general/plugins/modules/system/open_iscsi.py	2021-11-20 08:14:11.776162349 +0100
@@ -86,6 +86,12 @@
         - Whether the list of nodes in the persistent iSCSI database should be returned by the module.
         type: bool
         default: false
+    rescan:
+        description:
+        - rescan an established session for discovering new targets.
+        type: bool
+        default: false
+
 '''
 
 EXAMPLES = r'''
@@ -124,6 +130,12 @@
     portal: 10.1.1.250
     auto_portal_startup: false
     target: iqn.1986-03.com.sun:02:f8c1f9e0-c3ec-ec84-c9c9-8bfb0cd5de3d
+
+- name: Rescan one or all established sessions to discover new targets (omit target for all sessions)
+  community.general.open_iscsi:
+    rescan: true
+    target: iqn.1986-03.com.sun:02:f8c1f9e0-c3ec-ec84-c9c9-8bfb0cd5de3d
+
 '''
 
 import glob
@@ -178,6 +190,14 @@
     cmd = [iscsiadm_cmd, '--mode', 'discovery', '--type', 'sendtargets', '--portal', '%s:%s' % (portal, port)]
     module.run_command(cmd, check_rc=True)
 
+def iscsi_rescan(module, target=None):
+    if target == None:
+        cmd = [iscsiadm_cmd, '--mode', 'session', '--rescan']
+    else:
+        cmd = [iscsiadm_cmd, '--mode', 'node', '--rescan', '-T', target]
+    rc, out, err = module.run_command(cmd)
+    return out
+
 
 def target_loggedon(module, target, portal=None, port=None):
     cmd = [iscsiadm_cmd, '--mode', 'session']
@@ -305,6 +325,7 @@
             auto_portal_startup=dict(type='bool'),
             discover=dict(type='bool', default=False),
             show_nodes=dict(type='bool', default=False),
+            rescan=dict(type='bool', default=False),
         ),
 
         required_together=[['node_user', 'node_pass'], ['node_user_in', 'node_pass_in']],
@@ -330,6 +351,7 @@
     automatic_portal = module.params['auto_portal_startup']
     discover = module.params['discover']
     show_nodes = module.params['show_nodes']
+    rescan = module.params['rescan']
 
     check = module.check_mode
 
@@ -421,6 +443,10 @@
             result['changed'] |= True
             result['automatic_portal_changed'] = True
 
+    if rescan != False:
+        result['changed'] = True
+        result['sessions'] = iscsi_rescan(module, target)
+
     module.exit_json(**result)
```

### Issue Type

Feature Idea

### Component Name

open_iscsi

### Additional Information

```yaml (paste below)
---
- name: ISCSI configurations
  hosts: all
  vars:
    - node1:
      - iqn.1994-05.com.redhat:21a09593b660:disk1
      - iqn.1994-05.com.redhat:3f2e7f7725:disk1
    - node1:
      - iqn.1994-05.com.redhat:21a09593b660:disk2
      - iqn.1994-05.com.redhat:3f2e7f7725:disk2
    - node1:
      - iqn.1994-05.com.redhat:21a09593b660:disk3
    - node1:
      - iqn.1994-05.com.redhat:3f2e7f7725:disk3
    - node1:
      - iqn.1994-05.com.redhat:21a09593b660:disk4

  tasks:
  - name: Perform a discovery on portal1
    open_iscsi:
      show_nodes: yes
      discover: yes
      portal: portal1
    when: ansible_facts['hostname'] in lookup('inventory_hostnames', 'portal1nodes')

  - name: Perform a discovery on portal2
    open_iscsi:
      show_nodes: yes
      discover: yes
      portal: portal2
    when: ansible_facts['hostname'] in lookup('inventory_hostnames', 'portal2nodes')
  
  - name: Connect to the named target
    open_iscsi:
      login: yes
      target: "{{ item.0 }}"
    loop:
      - "{{ lookup('vars', ansible_facts['hostname']) }}"

  - name: Rescan Targets
    open_iscsi:
      rescan: true
      target: "{{ item.0 }}"
    register: iscsi_rescan
    tags:
      - rescan

  - name: Output rescan output
    debug:
      var: iscsi_rescan
    tags:
      - rescan
```

# example targeted configuration
```bash
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block ................................................................................................. [Storage Objects: 4]
  | | o- disk1 ....................................................... [/dev/sdb (1.0TiB) write-thru activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | o- disk2 ....................................................... [/dev/sdc (1.0TiB) write-thru activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | o- disk3 ....................................................... [/dev/sdd (1.0TiB) write-thru activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | o- disk4 ....................................................... [/dev/sde (1.0TiB) write-thru activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | |      o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.1994-05.com.redhat:21a09593b660 .............................................................................. [TPGs: 1]
  |   o- tpg1 ............................................................................................... [no-gen-acls, no-auth]
  |     o- acls .......................................................................................................... [ACLs: 4]
  |     | o- iqn.1994-05.com.redhat:node1 .......................................................................... [Mapped LUNs: 2]
  |     | | o- mapped_lun0 ................................................................................ [lun0 block/sdb (rw)]
  |     | | o- mapped_lun1 ................................................................................ [lun1 block/sdc (rw)]
  |     | o- iqn.1994-05.com.redhat:node2 .......................................................................... [Mapped LUNs: 2]
  |     | | o- mapped_lun0 ................................................................................ [lun2 block/sdd (rw)]
  |     | | o- mapped_lun1 ................................................................................ [lun3 block/sde (rw)]
  |     o- luns ......................................................................................................... [LUNs: 4]
  |     | o- lun0 ................................................. [block/sdb (/dev/sdb) (default_tg_pt_gp)]
  |     | o- lun1 ................................................. [block/sdc (/dev/sdc) (default_tg_pt_gp)]
  |     | o- lun2 ................................................. [block/sdd (/dev/sdd) (default_tg_pt_gp)]
  |     | o- lun3 ................................................. [block/sde (/dev/sde) (default_tg_pt_gp)]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 0.0.0.0:3260 ..................................................................................................... [OK]
  o- loopback ......................................................................................................... [Targets: 0]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
