### ISSUE TITLE
Add `--allow-untrusted` to `apk add` so that local apks can be installed

### ISSUE THREAD

**Issue by munnik** [ansible-collections/community.general#3773]
### Summary

I have an apk which is not created by myself and I want to installed it on some remote servers. When I copy the file to the server and then point the apk module to the file it wont install because the file is not trusted. Can you add an `allow-untrusted` option to the apk module so it will install this file?

### Issue Type

Feature Idea

### Component Name

apk

### Additional Information

```yaml (paste below)
apk:
  name: "a-local-file.apk"
  allow-untrusted: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
