### ISSUE TITLE
pacman: diff output is wrong when VerbosePkgLists is enabled

### ISSUE THREAD

**Issue by jraby** [ansible-collections/community.general#3783]
### Summary

If `VerbosePkgLists` is present in `pacman.conf`, the diff output generated by the pacman plugin is broken:

```
TASK [common : workstation pkgs] *************************************************************************************************************
--- before
+++ after
@@ -0,0 +1,4 @@
+New
+Version
+Net
+Change
```



### Issue Type

Bug Report

### Component Name

pacman

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jean/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True

```


### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 3.8.1
```


### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```


### OS / Environment

Arch

### Steps to Reproduce

Add `VerbosePkgLists` to `/etc/pacman.conf` and run a task that installs a pkg via `pacman`.


### Expected Results

```
TASK [common : workstation pkgs] ************************************************************************************************************ 
--- before
+++ after
@@ -0,0 +1 @@
+plasma-firewall-5.23.3-1

changed: [localhost]
```

### Actual Results

```console (paste below)
TASK [common : workstation pkgs] *************************************************************************************************************
--- before
+++ after
@@ -0,0 +1,4 @@
+New
+Version
+Net
+Change

changed: [localhost]
```


The module expects the default output from `pacman` and cannot currently cope with the verbose output.

Since it is not possible to turn off the verbose output from pacman's cli, I ended up adding a simple wrapper script that uses `pacman-conf` to grep out the verbose output option and using that as pacman's executable:


```yaml
    - name: pacman-noverbosepkglist                                                                                                                                                                                                                                                        
      copy:                                                                                                                                                                                                                                                                                
        content: |                                                                                                                                                                                                                                                                         
            #!/bin/sh                                                                                                                                                                                                                                                                      
            /usr/bin/pacman-conf | /bin/grep -v '^VerbosePkgLists$' | /usr/bin/pacman --config /dev/stdin "$@"                                                                                                                                                                             
        dest:  /usr/local/bin/pacman-noverbosepkglists
        owner: root                                                                                                                                                                                                                                                                        
        group: root                                                                                                                                                                                                                                                                        
        mode: 0555 
    - name: workstation pkgs                                                                                                                                                                                                                                                               
      community.general.pacman:                                                                                                                                                                                                                                                            
        executable: /usr/local/bin/pacman-noverbosepkglists
        name:                                                                                                                                                                                                                                                                              
          - plasma-firewall                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 ```

I feel like the pacman  module should work regardless of what display options are used in the system config file, but at the same time I'm not sure how to fix this properly.
Relying on the human readable output of the tool feels brittle and adding a new parser for the verbose output wouldn't help in the long run if that format ever changes.
I kinda wish `pacman` could output in a stable format, like json or something like that.

In any case, maybe the above will help other people who like the Verbose format :-)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
