### ISSUE TITLE
keycloak  saml-user-property-mapper mapper and property

### ISSUE THREAD

**Issue by haresotto** [ansible-collections/community.general#3789]
### Summary

Hello,

I am trying to create a client mapper of type saml-user-property-mapper. Unfortunately, It does not seem possible to set the "property" value. 
Plus, it does not seem possible to set the "friendy name" either, but this might be less important.

I might be doing something wrong though because I am new to keycloak plus did not understand how to dump an already-existing mapper as stated in the doc:

`protocol_mappers -> config :` Dict specifying the configuration options for the protocol mapper; the contents differ depending on the value of protocolMapper and are not documented other than by the source of the mappers and its parent class(es). An example is given below. It is easiest to obtain valid config values by **dumping an already-existing protocol mapper configuration through check-mode in the existing field.**

### Issue Type

Bug Report

### Component Name

keycloak_client

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.0]
  config file = None
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/USER/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.9/ansible
  python version = 3.9.9 (main, Nov 18 2021, 19:42:27) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/USER/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.1.0  

# /usr/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.1 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
EMPTY
```

### OS / Environment

Gentoo

### Steps to Reproduce

Here is a snippet of the protocol_mappers part, guessing you already have a realm in your environment. I hope this will be enough.
```yaml (paste below)
    protocol_mappers:
      - config:
          attribute.name: username
          attribute.nameformat: Basic
          property: username
          friendly_name: "User Name"
          friendlyName: "User Name"
        protocol: saml
        name: user_name
        protocolMapper: saml-user-property-mappe
```

### Expected Results

I expected "property" and "friendly name" to be set in REALM -> Clients -> Mappers -> user_name.

### Actual Results

```console (paste below)
These fields remain empty.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/identity/keycloak/keycloak_client.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/identity/keycloak/keycloak_client.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @eikef @ndclt
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by haresotto** [comment]
My bad:
in the config dictionary, property = user.attribute and friendly name = friendly.name
here is an example if anyone is facing the same questioning:

```yaml
protocol_mappers:
  - name: user_name
     protocol: saml
      protocolMapper: saml-user-property-mapper
      consentRequired: false
      config:
        attribute.nameformat: Basic
        user.attribute: username
        friendly.name: User Name
        attribute.name: username
```
