### ISSUE TITLE
Yarn add support for multiple packages

### ISSUE THREAD

**Issue by joshunger** [ansible-collections/community.general#3799]
### Summary

Run the following -

```
- name: install global packages
  community.general.yarn:
    executable: command yarn --ignore-engines
    global: yes
    name: 
      - '@prettier/plugin-ruby'
      - '@squoosh/cli'
    state: latest
```

### Issue Type

Bug Report

### Component Name

yarn

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/Users/josh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.7.0_1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/josh/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/local/Cellar/ansible/4.7.0_1/libexec/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

mac

### Steps to Reproduce

```yaml (paste below)
- name: install global packages
  community.general.yarn:
    executable: command yarn --ignore-engines
    global: yes
    name: 
      - '@prettier/plugin-ruby'
      - '@squoosh/cli'
    state: latest
```

### Expected Results

Installs both packages.

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "command yarn --ignore-engines global add '' --no-emoji", "msg": "warning package.json: No license field\nerror An unexpected error occurred: \"https://registry.yarnpkg.com/[%27: Not found\".", "rc": 1, "stderr": "warning package.json: No license field\nerror An unexpected error occurred: \"https://registry.yarnpkg.com/[%27: Not found\".\n", "stderr_lines": ["warning package.json: No license field", "error An unexpected error occurred: \"https://registry.yarnpkg.com/[%27: Not found\"."], "stdout": "yarn global v1.22.17\n[1/4] Resolving packages...\ninfo If you think this is a bug, please open a bug report with the information provided in \"/Users/josh/.config/yarn/global/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.\n", "stdout_lines": ["yarn global v1.22.17", "[1/4] Resolving packages...", "info If you think this is a bug, please open a bug report with the information provided in \"/Users/josh/.config/yarn/global/yarn-error.log\".", "info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command."]}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
