### ISSUE TITLE
become: machinectl

### ISSUE THREAD

**Issue by dustymabe** [ansible-collections/community.general#3809]
### Summary

When I try to execute a command using the machinectl become plugin that has an environment like:
```
- block:                          
    - name: Install flatpaks      
      environment:                
        ANSIBLE_TIMEOUT: 30       
      flatpak:                    
        name: "org.mozilla.Firefox"
        state: present            
        method: user              
        remote: fedora            
      become: yes                 
      become_user: dustymabe   
      become_method: machinectl
```

I get an error because the environment isn't passed properly through to machinectl:

```
<192.168.122.228> ESTABLISH SSH CONNECTION FOR USER: root                               
<192.168.122.228> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostba
sed,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=30 -o ControlPath=/dev/shm/cp%h-%p-%r -tt 192.168.122.228 '/bin/sh -c '"'"'machinectl -q shell  dus
tymabe@ ANSIBLE_TIMEOUT=30 /usr/bin/python3 /var/tmp/ansible-tmp-1638217333.966461-10855-153022006441761/AnsiballZ_flatpak.py && sleep 0'"'"''                                   
<192.168.122.228> (1, b"\x1b[0;1;31mFailed to get shell PTY: Specified path 'ANSIBLE_TIMEOUT=30' is not absolute\x1b[0m\r\n", b'Shared connection to 192.168.122.228 closed.\r\n'
)                                                                                       
<192.168.122.228> Failed to connect to the host via ssh: Shared connection to 192.168.122.228 closed.                                            
<192.168.122.228> ESTABLISH SSH CONNECTION FOR USER: root                                                                                                                        
<192.168.122.228> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostba
sed,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=30 -o ControlPath=/dev/shm/cp%h-%p-%r 192.168.122.228 '/bin/sh -c '"'"'rm -f -r /var/tmp/ansible-tm
p-1638217333.966461-10855-153022006441761/ > /dev/null 2>&1 && sleep 0'"'"''                                                                                                     
<192.168.122.228> (0, b'', b'')                                                                                                                                                  
failed: [mactop] (item={'name': 'firefox', 'flatpak': 'org.mozilla.Firefox'}) => changed=false 
  ansible_loop_var: item                                                                
  item:                                                                                                                                                                          
    flatpak: org.mozilla.Firefox                                                                                                                                                 
    name: firefox                                                                                                                                                                
  module_stderr: |-                                                                                                                                                              
    Shared connection to 192.168.122.228 closed.         
  module_stdout: |-                                                                                                                                                              
    [0;1;31mFailed to get shell PTY: Specified path 'ANSIBLE_TIMEOUT=30' is not absolute[0m                                                                                      
  msg: |-                                                                                                                                                                        
    MODULE FAILURE                                                                                                                                                               
    See stdout/stderr for the exact error                                               
  rc: 1
```

It doesn't look like environment is getting passed properly through. We might have to use `--setenv=` option to `machinectl`. 

### Issue Type

Bug Report

### Component Name

machinectl become plugin

### Ansible Version

```
# ansible --version
ansible 2.9.27
  config file = /var/b/shared/code/gitlab.com/dustymabe/pc-ansible-config/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

### Community.general Version

```
# rpm -q ansible-collection-community-general
ansible-collection-community-general-3.8.0-1.fc35.noarch
```

### Configuration

```
# ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/var/b/shared/code/gitlab.com/dustymabe/pc-ansible-config/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/var/b/shared/code/gitlab.com/dustymabe/pc-ansible-config/ansible.cfg) = /dev/shm/cp%%h-%%p-%%r
DEFAULT_CALLBACK_WHITELIST(/var/b/shared/code/gitlab.com/dustymabe/pc-ansible-config/ansible.cfg) = ['yaml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/var/b/shared/code/gitlab.com/dustymabe/pc-ansible-config/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/var/b/shared/code/gitlab.com/dustymabe/pc-ansible-config/ansible.cfg) = yaml
```

### OS / Environment

Fedora 35

### Steps to Reproduce

```yaml
- block:                          
    - name: Install flatpaks      
      environment:                
        ANSIBLE_TIMEOUT: 30       
      flatpak:                    
        name: "org.mozilla.Firefox"
        state: present            
        method: user              
        remote: fedora            
      become: yes                 
      become_user: dustymabe   
      become_method: machinectl
```

### Expected Results

I expected the env vars to get passed through

### Actual Results

```
Failed to get shell PTY: Specified path 'ANSIBLE_TIMEOUT=30' is not absolute
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
