### ISSUE TITLE
influxdb_user: Updating password of an existing user

### ISSUE THREAD

**Issue by pandafy** [ansible-collections/community.general#3824]
### Summary

Allow updating password of an existing user. 

### Issue Type

Feature Idea

### Component Name

inflxudb_user

### Additional Information

It should be possible to update password of a user using following example from the docs

```yml
- name: Create an admin user on a remote host using custom login credentials
  community.general.influxdb_user:
    user_name: john
    user_password: s3cr3t
    admin: yes
    hostname: "{{ influxdb_hostname }}"
    login_username: "{{ influxdb_username }}"
    login_password: "{{ influxdb_password }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
