### ISSUE TITLE
Allow community.general.random_string to produce string with special characters EXCEPT certain ones (e.g. backslash `\`)

### ISSUE THREAD

**Issue by tomkivlin** [ansible-collections/community.general#3836]
### Summary

`community.general.random_string` is a fab module, but sometimes I use it to produce a variable that is then used within a jinja2 template to be placed within some quotes (e.g. in a file).  This works great, except when a backslash is placed at the end of the string, as it escapes the quotes used in the file.

It would be fab if there was a way to specify that no backslashes (or any other character, I guess) are contained in the randomly generated string.

### Issue Type

Feature Idea

### Component Name

random_string

### Additional Information

```yaml (paste below)
  - name: Generate random string for django secret 
    ansible.builtin.set_fact:
      secret_key: "{{ lookup('community.general.random_string', length=50) }}" 
    no_log: true
```

might (has, in this case) produce a string like:

```
`A!)TSyruZ5Zhr[ozd~;JK%|Kzvawc+RU`";2crwwHSpXE{=4\
```

when used in quotes in a file, the `\` escapes the final quote, creating an error.

```
Dec 02 10:43:44 ip-10-0-2-150 gunicorn[1269]: SECRET_KEY = '`A!)TSyruZ5Zhr[ozd~;JK%|Kzvawc+RU`";2crwwHSpXE{=4\'
Dec 02 10:43:44 ip-10-0-2-150 gunicorn[1269]:                                                                 ^
Dec 02 10:43:44 ip-10-0-2-150 gunicorn[1269]: SyntaxError: EOL while scanning string literal
```

Note - this is as far from urgent as it's possible to be - just logging as a feature request in case it's feasible.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
