### ISSUE TITLE
not able to take single table dump from postgresql using ansible

### ISSUE THREAD

**Issue by SHUFIL** [ansible-collections/community.general#384]
##### SUMMARY

I have used postgresql_db module, but its taken full schema backup, target_opts I mention both schema and table, but again its taken full schema with all table, or we need to use a different module?
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_db module
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/ubuntu/Ansible/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = postgres
```

##### OS / ENVIRONMENT

ubuntu 16.04

##### STEPS TO REPRODUCE

not able to take single table backup from schema, its taken only full schema.

```yaml
- name: Dump a single table for an existing database schema
  postgresql_db:
    name: acme
    state: dump
    target: /tmp/acme.sql
    target_opts: "-n test-table.test-schema"
```

##### EXPECTED RESULTS

i want to take single or selective muliple table dump from schema

##### ACTUAL RESULTS

its taken dump file , but that is full schema , i want only single table from schema, i used target_opts: "-n test-table.test-schema" , but still its taken full schema backup.

```paste below

```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/database/postgresql/postgresql_db.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/database/postgresql/postgresql_db.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Andersson007 @Dorn- @amenonsen @andytom @jbscalia @kostiantyn-nemchenko @matburt @nerzhul @sebasmannem @tcraxs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Andersson007** [comment]
@SHUFIL have you tried to pass something like
```
- name: test
  become: yes
  become_user: postgres
  postgresql_db:
     name: postgres 
     state: dump
     target: /tmp/test_table_dump.sql
     target_opts: '-t public.test'
```
i've just tried, works for me to dump only one table (i checked the dump file)
Could you please try and provide feedback?

**Comment by SHUFIL** [comment]
@Andersson007 **Great its working fine** , 

And one more think , i have to take muliple selective tables  , i ave tried below options
target_opts: '-t public.test' '-t public.test12' and
same target option repeat with two lines one by one with different table name ,but both are not working

**Comment by Andersson007** [comment]
@SHUFIL you're welcome
if i need to dump two or more tables i would run something like below
```
  - name: test
    become: yes
    become_user: postgres
    postgresql_db:
      name: postgres
      state: dump
      target: /tmp/test_table_dump.sql
      target_opts: '-t public.test -t public.test1'
```
i just checked, works as well

**Comment by SHUFIL** [comment]
Working fine thanks

**Comment by Andersson007** [comment]
@SHUFIL thanks for reporting this!
it helped improve the module's documentation https://github.com/ansible-collections/community.general/pull/387

**Comment by SHUFIL** [comment]
@Andersson007 
I can drop the table using the below code, but I am not able to drop multiple tables, if you look at this it will be very grated full.
---

- hosts: dbserver
  become: true
  gather_facts: yes

  vars:
    dbname: postgres
    dbuser: postgres
    password: password123

  tasks:
  - name: Remove Table
    postgresql_table:
      db: testapp
      name: schema.table1
      state: absent
      login_user: "{{ dbuser }}"
      login_password: "{{ password }}"

**Comment by Andersson007** [comment]
@SHUFIL 
you could use a loop, e.g.
```
- name: Remove tables
  postgresql_table:
    name: '{{ item }}'
    state: absent
  loop:
  - schema1.table1
  - schema1.table2
  - schema2.table3
  - etc
```

**Comment by SHUFIL** [comment]
I have used the same but it is not at all working getting Syntax Error while loading YAML.

---

- hosts: dbserver
  become: true
  gather_facts: yes

  vars:
    dbname: postgres
    dbuser: postgres
    password: password123

  tasks:
  - name: Remove Table
    postgresql_table:
      db: app
      name: '{{ item }}'
      state: absent
    loop:
    - scheema-table1
    - scheema-table2
    - scheema-table3
      state: absent
      login_user: "{{ dbuser }}"
      login_password: "{{ password }}"

**Comment by Andersson007** [comment]
@SHUFIL 
```
  tasks:
  - name: Remove Table
    postgresql_table:
      login_user: "{{ dbuser }}"
      login_password: "{{ password }}"
      db: app
      name: '{{ item }}'
      state: absent
    loop:
    - schema.table1
    - schema.table2
```
it should work now
