### ISSUE TITLE
ipa netgroup functionality

### ISSUE THREAD

**Issue by lengoldenstein** [ansible-collections/community.general#3864]
### Summary

Functionality for management of netgroups is missing from community.general.ipa.  It is a gap for environments using netgroups with-in IPA as all other host and host group functionality is present.  netgroup functionality should be very similar to existing group functionality.

### Issue Type

Feature Idea

### Component Name

ipa

### Additional Information

```yaml (paste below)
  - name: 'Update IPA netgroup(s) for a host'
    community.general.ipa_netgroup:
      name: 'ipanetgroup'
      host: '{{ inventory_name }}'
      append: true
      state: 'present'
    delegate_to: 'localhost'
```
A simple role to add/remove users/hosts to netgroups in a similar function to how users and hosts are already handled by the community.general.ipa_group module.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
