### ISSUE TITLE
redhat_subscription: add new pools keeping current consumed

### ISSUE THREAD

**Issue by felmasper** [ansible-collections/community.general#3871]
### Summary

I'd like to append new pools/products to the already consumed ones. User/password or activationkey would not be needed in this case -- system is already registered. The behavior would be similar to rhsm_repos' `purge` parameter. In redhat_subscription, purge would default to true.

### Issue Type

Feature Idea

### Component Name

redhat_subscription

### Additional Information

```yaml (paste below)
- redhat_subscription:
    pools: "epel"
    purge: no
  become: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
