### ISSUE TITLE
ansible_collections.community.general.plugins.inventory.icinga2 plugin: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible-collections/community.general#3875]
### Summary

When I try to use the icinga2 inventory plugin, ansible-inventory reports a 404: Not found.

### Issue Type

Bug Report

### Component Name
community.general.icinga2
icinga2.py

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.4]

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 4.1.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['community.general.icinga2', 'host_list', 'script', 'auto', 'yaml', 'ini', 'toml']

```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
root @ ~ # ansible-inventory -i my.icinga2.yml --list
[WARNING]:  * Failed to parse /root/my.icinga2.yml with ansible_collections.community.general.plugins.inventory.icinga2 plugin: HTTP Error 404: Not Found

cat my.icinga2.yml
# my.icinga2.yml
plugin: community.general.icinga2
url: https://excample.domain.com:5665
user: ansible
password: secret
host_filter: None
validate_certs: false
```

### Expected Results

A valid inventory

### Actual Results

```console (paste below)
Nothing
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
