### ISSUE TITLE
community.general.icinga2_host - including template not working

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible-collections/community.general#3905]
### Summary

I am trying to create a Host with this module. The original curl command, which works, is (anonymized)
```
curl -k -s -S -i -u root:secret -H 'Accept: application/json' \
 -X PUT 'https://icinga2-master.example.com:5665/v1/objects/hosts/myhost.example.com' \
 -d '{ "templates": [ "generic-linux" ], "attrs": { "address": "1.2.3.4", "check_command": "icmp", "zone": "myzone", "vars.procs.myproc.procs_command": "fancyproc", "vars.procs.myproc.procs_critical": "1:" }, "pretty": true }'
```
The host is created. The "generic-linux" template, has an 'import "generic-host"' inside and both are imported into the host

Trying to add this via the playbook
```
- hosts: all
  tasks:
    - name: Add host to icinga
      community.general.icinga2_host:
        url: "https://icinga2-master.example.com:5665"
        url_username: "root"
        url_password: "secret"
        validate_certs: no
        state: present
        name: "{{ ansible_fqdn }}"
        ip: "{{ ansible_default_ipv4.address }}"
        check_command: "icmp"
        zone: "myzone"
        template: "generic-linux"
        variables:
          procs: {
             myproc: {
               'procs_command' : 'fancyproc',
               'procs_critical' : '1:'
             }
          }
      delegate_to: 127.0.0.1
```
creates the host, but does not both import the generic-linux and generic-host template. Also the procs service, which is applied via curl, is not applied via playbook. Does this module calls curl in a different way than my example?

### Issue Type

Bug Report

### Component Name

community.general.icinga2_host
icinga2_host.py

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.4]

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 4.1.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04 LTS

### Steps to Reproduce

```yaml (paste below)
- hosts: all
  tasks:
    - name: Add host to icinga
      community.general.icinga2_host:
        url: "https://icinga2-master.example.com:5665"
        url_username: "root"
        url_password: "secret"
        validate_certs: no
        state: present
        name: "{{ ansible_fqdn }}"
        ip: "{{ ansible_default_ipv4.address }}"
        check_command: "icmp"
        zone: "myzone"
        template: "generic-linux"
        variables:
          procs: {
             myproc: {
               'procs_command' : 'fancyproc',
               'procs_critical' : '1:'
             }
          }
      delegate_to: 127.0.0.1
```

### Expected Results

Host is created with all variables from the generic-linux ( + generic-host) templates.

### Actual Results

Host is created without variables from the templates.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
