### ISSUE TITLE
redfish_config - set HttpPushUriOptions / atttribute ApplyTime to OnReset

### ISSUE THREAD

**Issue by frsauvage** [ansible-collections/community.general#3910]
### Summary

Hi all,
I may misunderstood how redfish_info module/module_utils behaves, but I can't simply set the ApplyTime attribute.

Set HttpPushUriOptions ApplyTime=OnReset 
Is it possible ? What do I miss ?

Best regards,
Francine 

### Issue Type

Feature Idea

### Component Name

redfish_config remote_management

### Additional Information

```yaml (paste below)
  community.general.redfish_config:
    category: UpdateService
    command: SetHttpPushUriOptions
    httppushurioptions:
      HttpPushUriOptions:
        HttpPushUriApplyTime
          ApplyTime: OnReset
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/remote_management/redfish/redfish_config.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/remote_management/redfish/redfish_config.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bhavya06 @mraineri @rajeevkallur @renxulei @tomasg2012 @xmadsen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mraineri** [comment]
Sorry this took so long to come back to triage.

As of this moment, the only support the Redfish module has with any update capability is with the SimpleUpdate request found in redfish_command. There's no support today for HttpPush updates, so controlling the apply time for an HttpPush update doesn't help folks too much.

Would adding push update support be useful? If so, we should be able to add that along with the other types of control parameters for the update (such as configuring the apply time). One thing worth noting though is sometimes the update process requires intervention from the user to perform reset operations. The existing flow for SimpleUpdate in the module isn't quite complete as noted in issue #4276.

**Comment by frsauvage** [comment]
Hi @mraineri , Thank a lot for your answer.
SimpleUpdate is simple, but my problem is to be sure that firware was updated + rebooted if necessary.
From client side, I got an issue with it: 
Client (browser) doesn't read the MANIFEST, so no purpose and no version to compare with.
My current solution is:
1. Set ApplyTime = OnReset  
2. Post SimpleUpdate
3. Wait for taskmonitoring/taskcompletedOK ou warning (ResetRequired)
4. received status code = 204 => task OK ! update completed !
5. Post Reset if necessary => status code= 200 ! reboot received !

No better way.

So yes, ApplyTime=OnReset on ansible/redfish module would be so helpful :-)

Best Regards,
Francine

**Comment by mraineri** [comment]
So, it sounds like for your usage you want to specify the apply time when performing a SimpleUpdate. You won't need to use the HttpPush properties to configure that (since that will affect the apply time if invoking the update via the HttpPushUri). So, I would propose extending the SimpleUpdate command to add an apply time parameter. Something like this:

```
  - name: Simple update with additional options
    community.general.redfish_command:
      category: Update
      command: SimpleUpdate
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      update_apply_time: OnReset
      update_image_uri: //example.com/myupdate.img
      update_protocol: FTP
      update_targets:
        - /redfish/v1/UpdateService/FirmwareInventory/BMC
      update_creds:
        username: operator
        password: supersecretpwd
```
