### ISSUE TITLE
Mattermost: Add attachments message

### ISSUE THREAD

**Issue by xobtoor** [ansible-collections/community.general#3944]
### Summary

I would like to use Slack like message attachments: https://developers.mattermost.com/integrate/admin-guide/admin-message-attachments/ for well composed and nice looking notifications in Mattermost.

### Issue Type

Feature Idea

### Component Name

mattermost

### Additional Information

```yaml (paste below)
- name: Send attachments notification
  community.general.mattermost:
    url: <mattermost_url>
    api_key: <api-key>
    channel: notifications
    attachments:
      - text: Display my system load on host A and B
        color: '#ff00dd'
        title: System load
        fields:
          - title: System A
            value: "load average: 0,74, 0,66, 0,63"
            short: True
          - title: System B
            value: 'load average: 5,16, 4,64, 2,43'
            short: True
  delegate_to: localhost
  run_once: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
