### ISSUE TITLE
Proxmox 7 LXC Creation 400 Bad Request: Parameter verification failed

### ISSUE THREAD

**Issue by djarbz** [ansible-collections/community.general#3956]
### Summary

When using _community.general.proxmox_ to create a CT, it fails with exception _400 Bad Request: Parameter verification failed_

I had just recently upgraded to Proxmox 7.1-8.
This was working in Proxmox 6.

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.0]
  config file = /home/ansible/ansible.cfg
  configured module search path = ['/home/ansible/ansible/library']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.0.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CALLBACKS_ENABLED(/home/ansible/ansible.cfg) = ['profile_tasks', 'human_log']
DEFAULT_GATHERING(/home/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ansible/ansible.cfg) = ['/home/ansible/ansible/hosts.yaml']
DEFAULT_MODULE_PATH(/home/ansible/ansible.cfg) = ['/home/ansible/ansible/library']
DEFAULT_ROLES_PATH(/home/ansible/ansible.cfg) = ['/home/ansible/ansible/roles']
```

### OS / Environment

Debian 11

### Steps to Reproduce

```yaml (paste below)
- name: "DEBUG: pve dictionary"
  ansible.builtin.debug:
    msg: "{{ item.0 }} - {{ item.1 }}"
  loop: "{{ pve | dictsort }}"
  when: pve.lxc.features is not defined

- name: "Create LXC Container {{ pve.lxc.hostname }}"
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    api_host: "{{ pve.api.host }}"
    api_user: "{{ pve.api.user }}"
    api_password: "{{ pve.api.pass }}"
    validate_certs: "{{ pve.api.cert }}"
    node: "{{ pve.lxc.node }}"
    vmid: "{{ pve.lxc.vmid }}"
    storage: "{{ pve.lxc.storage }}"
    password: "{{ pve.lxc.pass }}"
    hostname: "{{ pve.lxc.hostname }}"
    ostemplate: "{{ pve.lxc.template }}"
    disk: "{{ pve.lxc.disk }}"
    onboot: "{{ pve.lxc.boot }}"
    cpus: "{{ pve.lxc.cpus }}"
    cores: "{{ pve.lxc.cores }}"
    memory: "{{ pve.lxc.memory }}"
    mounts: "{{ pve.lxc.mounts }}"
    netif: "{{ pve.lxc.netif }}"
    pubkey: "{{ pve.lxc.pubkey }}"
    state: "{{ pve.lxc.state }}"
    timeout: "{{ pve.lxc.timeout }}"
  register: ct_create
  delegate_to: localhost
  when: pve.lxc.features is not defined
```

PVE Dictionary
```
"msg": "lxc - {'hostname': '2005-ct.domain.lan', 'vmid': 2005, 'boot': True, 'cpus': 0, 'cores': 4, 'cpuunits': 1024, 'memory': 8192, 'disk': 8, 'netif': '{\"net0\":\"name=eth0,gw=###.###.###.###,ip=###.###.###.###/24,ip6=slacc,bridge=vmbr1002\"}', 'pubkey': 'ssh-rsa REDACTED', 'mounts': {}, 'state': 'present', 'timeout': 30, 'node': 'ml350p', 'storage': 'local-zfs', 'pass': 'REDACTED', 'template': 'local:vztmpl/debian-11-standard_11.0-1_amd64.tar.gz'}"
```

### Expected Results

The Proxmox plugin should create the new CT as it did in Proxmox v6.

### Actual Results

```console (paste below)
TASK [pve-ct-config : Create LXC Container 2005-ct.arbour.me] *******************************************************************************************************************************************
task path: /home/ansible/ansible/roles/pve-ct-config/tasks/main.yaml:68
Monday 27 December 2021  12:59:05 -0600 (0:00:00.066)       0:00:00.941 ******* 
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<localhost> EXEC /bin/sh -c 'echo ~ansible && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp `"&& mkdir "` echo /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597 `" && echo ansible-tmp-1640631546.0492344-9724-272782416133597="` echo /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597 `" ) && sleep 0'
Using module file /home/ansible/.local/lib/python3.9/site-packages/ansible_collections/community/general/plugins/modules/proxmox.py
<localhost> PUT /home/ansible/.ansible/tmp/ansible-local-9699_vmhn5q9/tmpmxtpyyxa TO /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597/AnsiballZ_proxmox.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597/ /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597/AnsiballZ_proxmox.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.9 /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597/AnsiballZ_proxmox.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1640631546.0492344-9724-272782416133597/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.general.proxmox_payload_ejbezhsu/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 599, in main
  File "/tmp/ansible_community.general.proxmox_payload_ejbezhsu/ansible_community.general.proxmox_payload.zip/ansible_collections/community/general/plugins/modules/proxmox.py", line 417, in create_instance
  File "/home/ansible/.local/lib/python3.9/site-packages/proxmoxer/core.py", line 135, in create
    return self.post(*args, **data)
  File "/home/ansible/.local/lib/python3.9/site-packages/proxmoxer/core.py", line 126, in post
    return self(args)._request("POST", data=data)
  File "/home/ansible/.local/lib/python3.9/site-packages/proxmoxer/core.py", line 105, in _request
    raise ResourceException(
fatal: [2005-ct.DOMAIN.LAN -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "ml350p.DOMAIN.LAN",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_token_id": null,
            "api_token_secret": null,
            "api_user": "ansible@pam",
            "cores": 4,
            "cpus": 0,
            "cpuunits": null,
            "description": null,
            "disk": "8",
            "features": null,
            "force": false,
            "hookscript": null,
            "hostname": "2005-ct.DOMAIN.LAN",
            "ip_address": null,
            "memory": 8192,
            "mounts": {},
            "nameserver": null,
            "netif": {
                "net0": "name=eth0,gw=###.###.###.###,ip=###.###.###.###/24,ip6=slacc,bridge=vmbr1002"
            },
            "node": "ml350p",
            "onboot": true,
            "ostemplate": "local:vztmpl/debian-11-standard_11.0-1_amd64.tar.gz",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool": null,
            "proxmox_default_behavior": "no_defaults",
            "pubkey": "ssh-rsa REDACTED",
            "purge": false,
            "searchdomain": null,
            "state": "present",
            "storage": "local-zfs",
            "swap": null,
            "timeout": 30,
            "unprivileged": false,
            "validate_certs": false,
            "vmid": 2005
        }
    },
    "msg": "creation of lxc VM 2005 failed with exception: 400 Bad Request: Parameter verification failed."
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
