### ISSUE TITLE
Add cargo module

### ISSUE THREAD

**Issue by jack1142** [ansible-collections/community.general#3975]
### Summary

This collection has modules for many package managers but there isn't one for Rust's cargo yet. Considering the popularity of the language and the popularity of some of the binary crates ([bat](https://github.com/sharkdp/bat), [ripgrep](https://github.com/BurntSushi/ripgrep), [exa](https://github.com/ogham/exa), [fd-find](https://github.com/sharkdp/fd), [git-delta](https://github.com/dandavison/delta), etc.), it seems like a reasonable addition to the existing packaging modules.

### Issue Type

Feature Idea

### Component Name

cargo

### Additional Information

```yaml
- name: playbook name
  hosts: localhost
  tasks:
    - name: install bat
      community.general.cargo:
        name: bat
        locked: true
        state: present
    - name: install ripgrep
      community.general.cargo:
        name: ripgrep
        version: 13.0.0
        state: present
    - name: install/upgrade exa
      community.general.cargo:
        name: exa
        no_default_features: true
        state: latest
    - name: uninstall git-delta
      community.general.cargo:
        name: git-delta
        state: absent
    - name: install fd-find from git
      community.general.cargo:
        # crate name is only required when the repository contains multiple crates
        # name: fd-find
        git: https://github.com/sharkdp/fd
        state: present
# etc...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
