### ISSUE TITLE
Jira module adds trailing \ to URL which throws a 404 error

### ISSUE THREAD

**Issue by governmentSponsored** [ansible-collections/community.general#4024]
### Summary

When I attempt to run this playbook it generates a fatal error. It is clear that a trailing `\` is added to the URL. When I put that URL without the `\` in my browser (https://servername/jira/rest/api/2/search?jql=cf%5B11000%5D%3D%27Platform%20Engineering%27%20AND%20status%20%21%3D%20Resolved&fields=lastViewed&maxResults=10), the JSON comes back just fine. 

Is there a way to enforce this on the playbook or is this a bug?

### Issue Type

Bug Report

### Component Name

jira

### Ansible Version

```console (paste below)
$ ansible --version
Ansible 2.9.27
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
4.3.0 (latest)
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

AKS container on RHEL 7: registry.redhat.io/ansible-tower-38/ansible-tower-rhel7:3.8.5

### Steps to Reproduce

```yaml (paste below)
---
- hosts: wildfly_tst,wildfly_dev
  become: true

  tasks:
  - name: Search for an issue
    community.general.jira:
      uri: 'servername'
      username: service_account_name
      password: service_account_pw
      project: DSD
      operation: search
      maxresults: 10
      jql: cf[11000]='Platform Engineering' AND status != Resolved
    args:
      fields:
        lastViewed: null
    register: issue

  - name: Print values from Jira search
    ansible.builtin.debug:
      msg: "{{ issue }}"
```

### Expected Results

Return JSON results from Jira query

### Actual Results

```console (paste below)
fatal: [servername]: FAILED! => 
{
    "changed": false, 
    "msg": "The request \"None https://servername/jira/rest/api/2/search?jql=cf%5B11000%5D%3D%27Platform%20Engineering%27%20AND%20status%20%21%3D%20Resolved&fields=lastViewed&maxResults=10\" returned the unexpected status code 401 HTTP Error 401: \n\n\n\n\n\n\n\n\n\n\n\n<html>\n\n<head>\n    <title>Unauthorized (401)</title>\n    \n\n\n\n<!--[if IE]><![endif]-->\n<script type=\"text/javascript\">\n    (function() {\n        var contextPath = '/jira';\n\n
    ..."
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
