### ISSUE TITLE
modprobe option for permanent load of modules

### ISSUE THREAD

**Issue by lucab85** [ansible-collections/community.general#4028]
### Summary

I'm like the load of the module performed by `modprobe` command is `persistent` after reboot.

### Issue Type

Feature Idea

### Component Name

modprobe

### Additional Information

```yaml (paste below)
---
- name: modprobe module demo
  hosts: all
  become: true
  vars:
    module_name: "dummy"
    module_params: "numdummies=2"
  tasks:
    - name: load the module
      community.general.modprobe:
        name: "{{ module_name }}"
        state: present
        params: "{{ module_params }}"
        persistent: true

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
