### ISSUE TITLE
CloudFlare - Add support to create / delete zones

### ISSUE THREAD

**Issue by ravensorb** [ansible-collections/community.general#4031]
### Summary

I am looking to automate setting up websites and it would be very helpful if I could include the automatic creation of new zones within cloudflare (or deletion when cleaning up retired sites)

### Issue Type

Feature Idea

### Component Name

cloudflare_dns

### Additional Information

```yaml (paste below)
- community.general.cloudflare_dns:
  account_email: email@email.com
  account_api_key: accountkey
  zone: somesamplezone.com
  state: present
```
or
```yaml (paste below)
- community.general.cloudflare_dns:
  account_email: email@email.com
  account_api_key: accountkey
  zone: somesamplezone.com
  state: absent
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
