### ISSUE TITLE
Implement parameters 'recursive' and 'list_merge' in the filter lists_mergeby.

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#4057]
### Summary

The function 'merge_hash' from ansible.utils.vars provides the required functionality. This function is used by the filter 'combine' as described in [Combining hashes/dictionaries](https://docs.ansible.com/ansible/devel/user_guide/playbooks_filters.html#combining-hashes-dictionaries). Implement this well-known functionality of the parameters  'recursive' and 'list_merge' in the filter 'lists_mergeby'. As a result, the same functionality provided by the filter 'combine' for the dictionaries will be available for the merging of the lists of dictionaries.

### Issue Type

Feature Idea

### Component Name

filter lists_mergeby

### Additional Information

Given the lists
```yaml (paste below)
list100:
  - name: myname01
    param01:
      - default1
  - name: myname02
    param01:
      - default2

list101:
  - name: myname01
    param01:
      - patch1
  - name: myname02
    param01:
      - patch2
```
The task below
```yaml
- name: Merge 2 lists by attribute name. list_merge='append'
  set_fact:
    my_list: "{{ [list100, list101]|
                 community.general.lists_mergeby('name', list_merge='append') }}"
```
would give

```yaml
my_list:
  - name: myname01
    param01:
      - default1
      - patch1
  - name: myname02
    param01:
      - default2
      - patch2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
