### ISSUE TITLE
nmcli - allow setting ipv6 routes

### ISSUE THREAD

**Issue by trewest** [ansible-collections/community.general#4059]
### Summary

I have a use case for using nmcli to set static routes. The module currently works fine for my IPv4 need but it seems there isn't functionality for setting IPv6 routes. I was curious why there isn't a `routes6` parameter to match the `routes4` parameter? Is there an alternative for this? Does this seem like a feasible addition?

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

```yaml (paste below)
- name: Set up sit tunnel
  when: tunnel_type == 'sit'
  become: true
  community.general.nmcli:
    conn_name: "{{ interface_name }}"
    ifname: "{{ interface_name }}"
    ip_tunnel_local: "{{ local_tunnel_ip }}"
    ip_tunnel_remote: "{{ remote_tunnel_ip }}"
    type: "{{ tunnel_type }}"
    method4: disabled
    ip6:
      - "{{ address }}"
    routes6:
      - "{{ static_route }}"
    method6: manual
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
