### ISSUE TITLE
Gitlab variable names couldn't be defined from ansible variables on community.general.gitlab_project_variable and community.general.gitlab_group_variable

### ISSUE THREAD

**Issue by sguarin** [ansible-collections/community.general#4074]
### Summary

I'm trying to use community.general.gitlab_*_variable specifying variable names from other variables. And this is not supported:

```
vars:
       "{{ item.secret_id_var }}":
         value: "{{ item_secret_id }}"
         protected: true
         masked: true
```
Using variables on keys is the not supported in ansible. Despite there are some hacks to template another ansible and then include it, I propose the following change in the API that will support managing the variable names from ansibe variables, loop, etc:

```
vars:
      - name: <var name>
        value: <var value>
        protected: true
        masked: true
      - name: <var name2>
        value: <var value2>
        protected: true
        masked: true
```

So it will support this kind of instantation:

```
vars:
       - name: "{{ item.secret_id_var }}"
         value: "{{ item.secret_id }}"
         protected: true
         masked: true
```

### Issue Type

Feature Idea

### Component Name

community.general.gitlab_project_variable

### Additional Information

It will solve the issue if specifing variable names from variables would be for ex: 

```yaml (paste below)
- name: "Adding/Updating Project Gitlab Variable"
  community.general.gitlab_project_variable:
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_access_token }}"
    project: "{{ item.project_name }}"
    state: present
    vars:
      - name: "{{ item.role_id_var }}"
        value: "{{ item.role_id }}"
        protected: true
      - name: "{{ item.secret_id_var }}"
        value: "{{ item.secret_id }}"
        protected: true
        masked: true
  no_log: true
  loop: "{{ gitlab_project_names }}"
  when: gitlab_project_names is defined
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
