### ISSUE TITLE
IndicatorLED / Systems / redfish_command.py 

### ISSUE THREAD

**Issue by frsauvage** [ansible-collections/community.general#4084]
### Summary

Hi all,

IndicatorLED is implemented for Chassis, not Systems.

Is it possible to add it in:
community.general/plugins/modules/remote_management/redfish/redfish_command.py  

Best Regards,
Francine

### Issue Type

Feature Idea

### Component Name

module community.general/plugins/modules/remote_management/redfish/redfish_command.py

### Additional Information

```yaml (paste below)
  - name: Set system indicator LED to blink using security token for auth
    community.general.redfish_command:
      category: Systems
      command: IndicatorLedBlink
      resource_id: system
      baseuri: "{{ baseuri }}"
      auth_token: "{{ result.session.token }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
