### ISSUE TITLE
listen_port_facts modules does not behave well with ipv6

### ISSUE THREAD

**Issue by gaetan-craft** [ansible-collections/community.general#4091]
### Summary

When using the `listen_port_facts` module it reports a service listening on port 1 which does not exist because it failed to parse the [::1]:631 entry from ss

### Issue Type

Bug Report

### Component Name

listen_port_facts

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/gduchaussois/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gduchaussois/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/gduchaussois/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gduchaussois/.local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.2.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  tasks:
    - name: check open ports
      community.general.listen_ports_facts:
        command: ss
    - name: debug
      debug:
        var: ansible_facts.tcp_listen | selectattr('port','eq',9999)

```
start a process binding only in ipv6 in antoher shell like `busybox httpd -p [::1]:9999`

### Expected Results

```
ok: [localhost] => {
    "ansible_facts.tcp_listen | selectattr('port','eq',9999)": [
        {
            "address": "[::1]",
            "name": "busybox",
            "pid": XXXX,
            "port": 9999,
            "protocol": "tcp",
            "stime": "Thu Jan 27 17:43:29 2022",
            "user": "XXXXX"
        }
    ]
}
```

### Actual Results

```console (paste below)
ok: [localhost] => {
    "ansible_facts.tcp_listen | selectattr('port','eq',9999)": []
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
