### ISSUE TITLE
jenkins_job fails with Jenkins 2.319.x due to: Unable to create job, Error in request. Possibly authentication failed [403]

### ISSUE THREAD

**Issue by nhojpatrick** [ansible-collections/community.general#4113]
### Summary

Trying to use ansible to manage jenkins and having issues with jenkins_job. Believe it's this previously reported issue #1631.

I've discovered this work around to get jenkins_job working, but ideally I won't need to unset, execute and then set the CrumIssuer. Workaround solution is https://github.com/samrocketman/demo-jenkins-world-2017/blob/main/scripts/disable-csrf-protection.groovy, i.e;

```yaml
- name: Disable CrumbIssuer - define script
  ansible.builtin.set_fact:
    disableCsrfProtection: |
        import hudson.security.csrf.DefaultCrumbIssuer
        import jenkins.model.Jenkins
        if (!Jenkins.instance.isQuietingDown()) {
            def j = Jenkins.instance
            if (j.getCrumbIssuer() != null) {
                j.setCrumbIssuer(null)
                j.save()
            }
        }

- name: Disable CrumbIssuer - execute script
  community.general.jenkins_script:
    script: "{{ disableCsrfProtection }}"
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
```

### Issue Type

Bug Report

### Component Name

ugins/modules/web_infrastructure/jenkins_job.py

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
$
```

### Community.general Version

```console
$ ansible-galaxy collection list community.general
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')
$
```

The ansible collections requirements file is;
```yaml
collections:
  - name: community.general
    version: 4.3.0
```

### Configuration

```console
$ ansible-config dump --only-changed
$
```

### OS / Environment

CentOS 7 (Vagrant config.vm.box = "centos/7")

### Steps to Reproduce

```yaml
- name: Create job
  community.general.jenkins_job:
    name: seeding-job
    config: "{{ lookup('file', 'seeding-job.xml') }}"
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
```

### Expected Results

Either;
```console
TASK [Create job] ************************************************************
ok: [jenkins-master]
```

Or;
```console
TASK [Create job] ************************************************************
changed: [jenkins-master]
```

### Actual Results

```
TASK [Create job] ************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: JenkinsException: Error in request. Possibly authentication failed [403]: Forbidden
fatal: [jenkins-master]: FAILED! => {"changed": false, "msg": "Unable to create job, Error in request. Possibly authentication failed [403]: Forbidden for http://localhost:8080"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
