### ISSUE TITLE
nmcli reports changed for routes4 parameter that includes attributes

### ISSUE THREAD

**Issue by wazepp** [ansible-collections/community.general#4131]
### Summary

When using nmcli with the routes4 parameter that includes attributes for the routes it always reports as changed.   A different format needs to be used for the check then when setting the parameter.

In particular when using the "table" attribute, when checking the value the following format needs to be used with "ip =" and "nh =" for the check to not show change, but when configuring the interface those cannot be included.

For example if "0.0.0.0/0 192.168.138.1 table=201" is used then it will not be idempotent and show changed.
--- before
+++ after
@@ -10 +10 @@
-- '{ ip = 0.0.0.0/0, nh = 192.168.138.1 table=201 }'
+- 0.0.0.0/0 192.168.138.1 table=201

If "{ ip = 0.0.0.0/0, nh = 192.168.138.1 table=201 }" used then it will correctly show as not changed if set, but if not already set it needs to be in the format "0.0.0.0/0 192.168.138.1 table=201" when setting.

### Issue Type

Bug Report

### Component Name

community.general.nmcli

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/collections/ansible_collections/tfdm/utils/plugins/modules', '/usr/share/ansible/collections/ansible_collections/tfdm/utils/plugins/modules', '/home/tfdmseed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/tfdmseed/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 8

### Steps to Reproduce

See routes4 parameter.

```yaml (paste below)
# Run in check_mode first with routes4 paramater formatted for check mode
# This is needed due to bug in nmcli where it checks routes4 in different format
- name: Check nmcli configure interfaces
  community.general.nmcli:
    conn_name: "{{ interface }}"
    ifname: "{{ interface }}"
    vlandev: "{{ vlandev }}"
    vlanid: "{{ vlanid }}"
    type: "{{ type }}"
    ip4: "{{ ip4 }}"
    gw4: "{{ gw4 }}"
    method4: "{{ ipv4_method }}"
    never_default4: "{{ never_default4 }}"
    method6: "{{ ipv6_method }}"
    routes4: "{ ip = 0.0.0.0/0, nh = 192.168.138.1 table=201 }"
    routing_rules4: "{{ routing_rules4 }}"
    state: present
    autoconnect: yes
  check_mode: yes
  register: nmcli_result_check

- name: Configure interfaces
  community.general.nmcli:
    conn_name: "{{ interface }}"
    ifname: "{{ interface }}"
    vlandev: "{{ vlandev }}"
    vlanid: "{{ vlanid }}"
    type: "{{ type }}"
    ip4: "{{ ip4 }}"
    gw4: "{{ gw4 }}"
    method4: "{{ ipv4_method }}"
    never_default4: "{{ never_default4 }}"
    method6: "{{ ipv6_method }}"
    # Use routes4 format depending on if changes are required, to handle idempotency
    routes4: "{{ '0.0.0.0/0 192.168.138.1 table=201' if nmcli_result_check.changed else '{ ip = 0.0.0.0/0, nh = 192.168.138.1 table=201 }'}}"
    routing_rules4: "{{ routing_rules4 }}"
    state: present
    autoconnect: yes
  register: nmcli_result

```

### Expected Results

The "0.0.0.0/0 192.168.138.1 table=201" format should not report a change if already set.   It should be able to be used for both the check and configuring route4 parameter.

### Actual Results

```console (paste below)
{ ip = 0.0.0.0/0, nh = 192.168.138.1 table=201 }' is required when checking interface in order for it to not report change.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
