### ISSUE TITLE
ini_file: reports change when told to remove non-existing section

### ISSUE THREAD

**Issue by Kagee** [ansible-collections/community.general#4154]
### Summary

When using ini_file to remove a section from an ini file, changes are reported even if no changes were done/required.

### Issue Type

Bug Report

### Component Name

ini_file

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.6] 
  config file = /home/user/ansible/ansible.cfg
  configured module search path = ['/home/user/ansible/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/user/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(env: ANSIBLE_CALLBACKS_ENABLED) = ['profile_tasks']
DEFAULT_FORKS(/home/user/ansible/ansible.cfg) = 150
DEFAULT_HOST_LIST(/home/user/ansible/ansible.cfg) = ['/home/user/ansible/inventory-production.ini']
DEFAULT_LOCAL_TMP(/home/user/ansible/ansible.cfg) = /home/user/.ansible/tmp/ansible-local-19356977961lflx
DEFAULT_MODULE_PATH(/home/user/ansible/ansible.cfg) = ['/home/user/ansible/library']
DEFAULT_MODULE_UTILS_PATH(/home/user/ansible/ansible.cfg) = ['/home/user/ansible/module_utils']
DEFAULT_POLL_INTERVAL(/home/user/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_USER(/home/user/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/user/ansible/ansible.cfg) = ['/home/user/ansible/roles']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
DEFAULT_TIMEOUT(/home/user/ansible/ansible.cfg) = 45
DEFAULT_VAULT_IDENTITY_LIST(/home/user/ansible/ansible.cfg) = ['prod@vault-prod', 'dev@vault-dev']
DIFF_ALWAYS(env: ANSIBLE_DIFF_ALWAYS) = True
GALAXY_ROLE_SKELETON(/home/user/ansible/ansible.cfg) = /home/user/ansible/skeleton-role
HOST_KEY_CHECKING(/home/user/ansible/ansible.cfg) = False
INVENTORY_ANY_UNPARSED_IS_FAILED(env: ANSIBLE_INVENTORY_ANY_UNPARSED_IS_FAILED) = True
INVENTORY_UNPARSED_IS_FAILED(env: ANSIBLE_INVENTORY_UNPARSED_FAILED) = True
RETRY_FILES_SAVE_PATH(/home/user/ansible/ansible.cfg) = /home/user/ansible/.ansible-retry
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
- name: reset test file
  ansible.builtin.copy:
      content: |
        [section1]
        foo=bar

        [section2]
        bar=foo

        [section3]
        haha=hoho
      dest: /tmp/foo.ini

- name: remove section
  community.general.ini_file:
    path: /tmp/foo.ini
    section: "section2"
    state: absent

- name: remove section again
  community.general.ini_file:
    path: /tmp/foo.ini
    section: "section2"
    state: absent

- name: remove section again w. loop
  community.general.ini_file:
    path: /tmp/foo.ini
    section: "{{ item.section }}"
    state: absent
  with_items:
    - { section: "section2" }
```

### Expected Results

I would expect task `remove section again` and task `remove section again w. loop` to report no changes

### Actual Results

Task `remove section again` and task `remove section again w. loop` reports changes

```console (paste below)
TASK [reset test file] ***********************************************
fredag 04 februar 2022  14:17:20 +0100 (0:00:02.062)       0:00:02.107
--- before: /tmp/foo.ini
+++ after: /home/user/.ansible/tmp/ansible-local-1936585ojv905_r/tmpftrnqd9q
@@ -1,5 +1,8 @@
 [section1]
 foo=bar
  
+[section2]
+bar=foo
+
 [section3]
 haha=hoho

changed: [node01.example.com]

TASK [remove section] ************************************************
fredag 04 februar 2022  14:17:22 +0100 (0:00:01.235)       0:00:03.343
--- before: /tmp/foo.ini (content)
+++ after: /tmp/foo.ini (content)
@@ -1,8 +1,5 @@
 [section1]
 foo=bar
  
-[section2]
-bar=foo
-
 [section3]
 haha=hoho

changed: [node01.example.com]

TASK [remove section again] ******************************************
fredag 04 februar 2022  14:17:22 +0100 (0:00:00.355)       0:00:03.699
changed: [node01.example.com]

TASK [remove section again w. loop] **********************************
fredag 04 februar 2022  14:17:22 +0100 (0:00:00.259)       0:00:03.958
changed: [node01.example.com] => (item={'section': 'section2'})


```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
