### ISSUE TITLE
xml.children parameter in documentation examples does not exist

### ISSUE THREAD

**Issue by jooola** [ansible-collections/community.general#4166]
### Summary

In the xml module the `children` parameter does not exist, but the documentation example does refer to such parameter:

```yml
- name: Remove all children from the 'website' element (option 2)
  community.general.xml:
    path: /foo/bar.xml
    xpath: /business/website
    children: []
```

### Issue Type

Documentation Report

### Component Name

xml

### Community.general Version

4.2.0

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
