### ISSUE TITLE
community.general.xml: incorrect documentation & missing feature

### ISSUE THREAD

**Issue by trantor** [ansible-collections/community.general#4187]
### Summary

The documentation for the `community.general.xml` module states:
```yaml
[...]
  value:
    description:
    - Desired state of the selected attribute.
    - Either a string, or to unset a value, the Python C(None) keyword (YAML Equivalent, C(null)).
    - Elements default to no value (but present).
    - Attributes default to an empty string.
 [...]
 ```
According to this, one can _unset_ an attribute by providing `the Python None keyword (YAML Equivalent, null)`.
Which would allow, for instance, to do something like
```yaml
[...]
value: "{{ variable_parameter | default(None) }}"
[...]
```
to set an attribute value according to a parameter and remove it if the parameter is missing, for instance.

However, the code is like this:
```python
    # Is the xpath target an attribute selector?
    if value is not None:
        set_target(module, doc, xpath, namespaces, attribute, value)

    # If an xpath was provided, we need to do something with the data
    if xpath is not None:
        ensure_xpath_exists(module, doc, xpath, namespaces)
```

which, empirically, gives back an "ok" status if the attribute in question is present and does not remove/unset it.

The behaviour related to unset the attribute if value is null would be ideal, since it would change the behaviour of setting/unsetting the attribute value according to the contents provided.

### Issue Type

Bug Report

### Component Name

xml

### Ansible Version

Core 2.12.1
Python 3.8.5
Jinja 3.0.3

### Community.general Version

4.4.0

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

See summary

### Expected Results

When the `value` parameter is set to `null` the xml attribute should be **unset** 

### Actual Results

The module returns an `ok` status just checking that the attribute exists, essentially the opposite of what's supposed to happen.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/files/xml.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/files/xml.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by trantor** [comment]
Noone?

**Comment by russoz** [comment]
The documentation claim that `value: null` unsets an attribute is incorrect — the feature was never implemented.

When `value` is set to `null`, AnsibleModule treats it as "not provided" due to how `required_by` and `required_one_of` validation works, so the task fails with a validation error before the module logic is even reached. Even if that were bypassed, there is no code path in `set_target_inner` to handle a `None` value — it would be rejected by the non-string guard added to catch accidental YAML booleans/floats.

For the attribute removal case, `state: absent` already covers this cleanly:

```yaml
- community.general.xml:
    path: /foo/bar.xml
    xpath: /business/rating/@subjective
    state: absent
```

The proposed fix is to correct the documentation by removing the `null` claim from the `value` parameter description, and pointing users to `state: absent` as the supported way to remove an attribute or element.

Note: clearing element *text* (turning `<address>text</address>` into `<address/>`) has no equivalent via `state: absent`, but that is a separate enhancement request and out of scope here.
