### ISSUE TITLE
lxc_container doesn't replace existing container_config values

### ISSUE THREAD

**Issue by moqmar** [ansible-collections/community.general#4205]
### Summary

When changing a value in `container_config`, a line gets *added* instead of replaced in `/var/lib/lxc/CONTAINER/config`.

It seems to affect line https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cloud/lxc/lxc_container.py#L723 - I don't really understand why it's using `container_config.insert` there instead of just setting `container_config[line_index]`

### Issue Type

Bug Report

### Component Name

lxc_container

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/momar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/momar/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/momar/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/momar/.local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.4.0  
```

### OS / Environment

Debian 11 Bullseye

### Steps to Reproduce

```yaml
- hosts: all
  tasks:
  - ansible.builtin.apt:
      name: [python3-lxc, lxc-templates, debootstrap, apparmor]
  - community.general.lxc_container:
      name: "example"
      template: "debian"
      template_options: "--release bullseye"
      container_config:
      - lxc.cgroup2.memory.max = 43421772800
```

```console
ansible-playbook -i hosts playbook.yml
sed -i 's/43421772800/13421772800/' playbook.yml
ansible-playbook -i hosts playbook.yml
```

### Expected Results

I'd expect the line to be replaced:

```console
$ ssh HOST cat /var/lib/lxc/example/config | grep -Fn lxc.cgroup2.memory.max
25:lxc.cgroup2.memory.max = 13421772800
```

### Actual Results

The line gets added:

```console
$ ssh HOST cat /var/lib/lxc/example/config | grep -Fn lxc.cgroup2.memory.max
25:lxc.cgroup2.memory.max = 43421772800
26:lxc.cgroup2.memory.max = 13421772800
```

This by itself accidentally "works", as LXC will take the latter value, but if I change it back to the first value, nothing will happen and it will forever stay at the second value.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
