### ISSUE TITLE
nios_network add field to specify a template to use for network creation

### ISSUE THREAD

**Issue by noziwatele** [ansible-collections/community.general#424]
##### SUMMARY
When a network is created in NIOS a pre-defined template can be specified that automatically creates commonly used objects within the new network, such as fixed addresses/reservations for router IPs, DHCP ranges, etc.

It would be great if a template could be specified by name in a field in the nios_network module. Other nios_ modules could possibly also use templates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nios_network

(could also be added to other nios_* modules for objects that support templates)

##### ADDITIONAL INFORMATION
A string field would be added, possibly named 'template', that would be used to specify the template to be used. This is passed directly through to the NIOS API or infoblox_client module in the template=TEMPLATE_NAME argument.

```yaml
- name: configure a network ipv4
  nios_network:
    network: 192.168.10.0/24
    comment: this is a test comment
    template: TEST_TEMPLATE
    state: present
    provider:
      host: "{{ inventory_hostname_short }}"
      username: admin
      password: admin
  connection: local
```
