### ISSUE TITLE
Add --editable option to pipx module

### ISSUE THREAD

**Issue by firecat53** [ansible-collections/community.general#4300]
### Summary

It would be useful to add the `--editable` and the `--pip-args` flags to the pipx module.

Thanks!

### Issue Type

Feature Idea

### Component Name

pipx

### Additional Information

```yaml 
- name: "[laptop] install/update pipx packages"
  community.general.pipx:
    state: upgrade
    name: urlscan
    source: /home/firecat53/src/urlscan
    editable: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
