### ISSUE TITLE
ini_file fails to create working facts file for ansible if the value of the token is multiline string.

### ISSUE THREAD

**Issue by rasjani** [ansible-collections/community.general#4335]
### Summary

When ini_file adds a token that has multiple lines, each line after the first linefeed should be prefixed with n. amount of spaces for the generated ini file to be useable as a fact within ansible itself.

### Issue Type

Bug Report

### Component Name

community.general.ini_file

### Ansible Version

```console (paste below)
(venv) rasjani@rasjani-northcode ~$ ansible --version
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/Users/rasjani/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rasjani/src/XXXX/environments/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/rasjani/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/rasjani/src/XXXX/environments/venv/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:40:53) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
(venv) rasjani@rasjani-northcode ~$
```

### Community.general Version

```console (paste below)
(venv) rasjani@rasjani-northcode ~$ ansible-galaxy collection list community.general

# /Users/rasjani/src/XXXX/environments/venv/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.5.0

# /Users/rasjani/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.1.0
(venv) rasjani@rasjani-northcode ~$

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_FILTER_PLUGIN_PATH(/Users/rasjani/src/XXXX/environments/ansible/ansible.cfg) = ['/Users/rasjani/src/XXXX/environments/ansible/filter_plugins']
DEFAULT_HOST_LIST(/Users/rasjani/src/XXXX/environments/ansible/ansible.cfg) = ['/Users/rasjani/src/XXXX/environments/ansible/inventory']
INVENTORY_ENABLED(/Users/rasjani/src/XXXX/environments/ansible/ansible.cfg) = ['ini', 'host_list', 'yaml']
```

### OS / Environment

macos Monteray but imho, not relevant

### Steps to Reproduce

```yaml
- name: Demonstration That Does Not Work
  community.general.ini_file:
    create: yes
    no_extra_spaces: yes
    option: "token"
    section: "api"
    state: present
    value: "{{ generated_token | vault(default_passphrase) }}"
    path: "{{ token_file }}"
    owner: root
    group: root
    mode: '0600'
```

### Expected Results

Ansible should be able to load the ini file but its not ..

As a workaround, regex_replace filter can be used:

```yaml
- name: Demonstration That Works
  community.general.ini_file:
    create: yes
    no_extra_spaces: yes
    option: "token"
    section: "api"
    state: present
    value: "{{ generated_token | vault(default_passphrase) | regex_replace('\n', '\n   ')}}"
    path: "{{ token_file }}"
    owner: root
    group: root
    mode: '0600'
```

### Actual Results

When running a playbook that accesses the fact ini file created with the demostration:
```console
TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************
[WARNING]: error loading facts as JSON or ini - please check content: /etc/ansible/facts.d/SERVICENAME.fact
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
