### ISSUE TITLE
[Feature Request] ini_file: remove sections that are emptied using state: absent

### ISSUE THREAD

**Issue by kaysond** [ansible-collections/community.general#4350]
### Summary

If used with `state: absent`, and `ini_file` removes the last option for a given section, `ini_file` should have an option to also remove that section label.

### Issue Type

Feature Idea

### Component Name

ini_file

### Additional Information

If I have an ini file with something like:

```
[sectionfoo]
parameterbar = value
```
and I run:
```
  community.general.ini_file:
    state: absent
    exclusive: yes
    section: sectionfoo
    option: parameterbar
```
the file is left with 
```
[sectionfoo]
```

this causes problems for some services, like samba

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
