### ISSUE TITLE
zypper fails to install with specified version

### ISSUE THREAD

**Issue by tover99** [ansible-collections/community.general#4371]
### Summary

If a package is already installed on the target system, the zypper module fails to install a specified different version, claiming it's already there.

### Issue Type

Bug Report

### Component Name

zypper

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.4.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

```console (paste below)
# cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

```
### Steps to Reproduce

The following task ALWAYS reports [ok] if any version of _a-very-important-package_ is already installed on the target system.

```yaml (paste below)

    - name: Install a specific package version via zypper
      zypper:
        name:
          - "a-very-important-package=2.1"
        state: present
        oldpackage : yes

```
As soon as at least one other package WITHOUT a version specification is requestet, everything works as expected.

```yaml (paste below)

    - name: Install a specific package version via zypper
      zypper:
        name:
          - "a-very-important-package=2.1"
          - "another-package"
        state: present
        oldpackage : yes

```

### Expected Results

specific package version gets installed/updated/downgraded

### Actual Results

specific package version is reported as present even if it is not in the requested version

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
