### ISSUE TITLE
iso_create to create files per source directory structure

### ISSUE THREAD

**Issue by jamesholland-uk** [ansible-collections/community.general#4374]
### Summary

It would be great if there was an option for `iso_create` to create files per the source directory structure.

Currently, if a file `directory/filename.txt` is in the source list, it gets added as `/filename.txt` in the ISO instead of `/directory/filename.txt` in the ISO.

The module code doing this is [here](https://github.com/ansible-collections/community.general/blob/421ccd5dc99c9fed441a767e6371476d613a37a0/plugins/modules/files/iso_create.py#L282).

### Issue Type

Feature Idea

### Component Name

iso_create

### Additional Information

Example task definition:

```
  - name: Create ISO
    community.general.iso_create:
      src_files:
        - directory/filename.txt
```

Current result:
```
ISO: /filename.txt
```

Desired result:
```
ISO: /directory/filename.txt
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
