### ISSUE TITLE
add a 'runas' parameter to sudoers module

### ISSUE THREAD

**Issue by doubletwist13** [ansible-collections/community.general#4379]
### Summary

It would be very useful to be able to define a 'runas' option for sudo rules in the sudoers module instead of defaulting to only running as root.

For example, if I want a user `bob` to be able to run `/usr/bin/somecommand` as the user `alice`, the sudo rule would look like this:
```
bob ALL=(alice) /usr/bin/somecommand
```

So I'd propose a parameter called something like `runas` that takes a string containing the user you want to run as. 

Also, while not critical, since the current result is effectively defaulting to root, it might be worth having that parameter default to 'root' and thus include `ALL=(root)` in the output as it would be a little more clear and more consistent.

So the value returned by sudoers.py might look like:
```
return "{owner} ALL=({runas}) {nopasswd} {commands}\n".format(owner=owner, nopasswd=nopasswd_str, commands=commands_str)
```
 
As an added bonus you could probably easily include a 'host' parameter as well.
```
return "{owner} {host}=({runas}) {nopasswd} {commands}\n".format(owner=owner, nopasswd=nopasswd_str, commands=commands_str)

```

### Issue Type

Feature Idea

### Component Name

sudoers.py

### Additional Information

```yaml (paste below)

 - name: Allow the bob to run commands as alice
   community.general.sudoers:
    name: bob_as_alice
      user: bob
      commands: /usr/bin/somecommand
      runas: alice
      nopassword: true

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
