### ISSUE TITLE
pacman: Apply extra arguments to all pacman commands

### ISSUE THREAD

**Issue by maxbrunet** [ansible-collections/community.general#438]
##### SUMMARY

Support injecting extra arguments to **all** pacman commands (update, query, install...).

For example `query_package()` does not support extra arguments:
https://github.com/ansible-collections/community.general/blob/f81e562301e1d69be98b51138d4c859f7c92daa0/plugins/modules/packaging/os/pacman.py#L172

I'm thinking about re-purposing the `extra_args` parameter and use it everywhere, or adding a `global_extra_args` parameter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
pacman

##### ADDITIONAL INFORMATION

I want to be able to change the root directory by using the `--root` and `--cachedir` arguments, similarly to how [`pacstrap`](https://git.archlinux.org/arch-install-scripts.git/tree/pacstrap.in) does.

```yaml
- name: Install packages in new root
  pacman:
    name:
    - base
    - base-devel
    - python
    extra_args: &extra_args >-
      --root=/mnt
      --cachedir=/mnt/var/cache/pacman/pkg
      --config=/path/to/another/config
    update_cache: true
    update_cache_extra_args: *extra_args
```

Currently, this will skip the packages installed outside the root, since `query_package()` does not use any extra arguments.
