### ISSUE TITLE
The nmcli routes functions are not idempotent.

### ISSUE THREAD

**Issue by VolodymyrSerhiienko** [ansible-collections/community.general#4383]
### Summary

When using the nmcli to set the routes and routing rules, we noticed the module is not idempotent. 

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```console (paste below)
$ ansible --version

```
ansible 2.9.17
  config file = /home/vserhiienko/git/ansible_configs/ansible.cfg
  configured module search path = ['/home/vserhiienko/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```
ANSIBLE_PIPELINING(/home/nnn/git/ansible_configs/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/nnn/git/ansible_configs/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_STRATEGY(/home/nnn/git/ansible_configs/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/nnn/git/ansible_configs/ansible.cfg) = ['/home/nnn/git/ansible_configs/plugins/strategy/mitogen-0.2.10/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/home/nnn/git/ansible_configs/ansible.cfg) = False
MAX_FILE_SIZE_FOR_DIFF(/home/nnn/git/ansible_configs/ansible.cfg) = 2097152
PERSISTENT_CONNECT_TIMEOUT(/home/nnn/git/ansible_configs/ansible.cfg) = 30

### OS / Environment

Ubuntu 20.04 LTS

### Steps to Reproduce

```yaml (paste below)
---
- name: Routing manipulation via nmcli
  hosts: all-linux-servers
  user: "{{ user | default(lookup('env', 'USER')) }}"
  become: yes
  vars:
    sources:
      - priority 5 from 172.20.129.0/24 table 101
      - priority 10 from 172.17.100.0/24 table 106
   
    destinations:
      - 1.1.1.1/32 172.16.1.3 table=101
      - 8.8.8.8/32 172.16.1.3 table=101
      - 199.10.0.2/32 172.16.1.3 table=106

  tasks:
  - name: Modify routes and routing rules
    community.general.nmcli:
      conn_name: eth1
      ifname: eth1
      type: ethernet
      ip4: "{{ full_addr_local | ipaddr('host/prefix') }}"
      routes4: "{{ destinations }}"
      routing_rules4: "{{ sources }}"
      state: present


```

### Expected Results

I expected that nmcli module fills routes and routing rules as that is described in community.general.nmcli documentation. Sure I used the data format described there, something like '1.1.1.1/32 172.16.1.3 table=101'
But when nmcli module finished the nmcli conn show command showed the routes record in the different format something like "{ ip = 1.1.1.1/32, nh = 172.16.1.3, mt = 5 table=101 }".
As result, EVERY run of the playbook leads to overwriting all these records as shown below:
```
"ipv4.routes": [

"{ ip = 1.1.1.1/32, nh = 172.16.1.3, mt = 5 table=101 }",
"{ ip = 8.8.8.8/32, nh = 172.16.1.3, mt = 5 table=101 }",
"{ ip = 199.10.0.2/32, nh = 172.16.1.3, mt = 10 table=106 }"
+ "1.1.1.1/32 172.16.1.3 table=101",
+ "8.8.8.8/32 172.16.1.3 table=101",
+ "199.10.0.2/32 172.16.1.3 table=106"
],

```
Looks like it can't be considered as the correct behavior of the ansible module.

### Actual Results

```
"ipv4.routes": [

"{ ip = 1.1.1.1/32, nh = 172.16.1.3, mt = 5 table=101 }",
"{ ip = 8.8.8.8/32, nh = 172.16.1.3, mt = 5 table=101 }",
"{ ip = 199.10.0.2/32, nh = 172.16.1.3, mt = 10 table=106 }"
+ "1.1.1.1/32 172.16.1.3 table=101",
+ "8.8.8.8/32 172.16.1.3 table=101",
+ "199.10.0.2/32 172.16.1.3 table=106"
],

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
