### ISSUE TITLE
Keycloak client - alwaysDisplayInConsole 

### ISSUE THREAD

**Issue by whoamiUNIX** [ansible-collections/community.general#4390]
### Summary

I would like to get support for keycloak_client module tu support the following parameter for client: `alwaysDisplayInConsole`.

### Issue Type

Feature Idea

### Component Name

keycloak_client

### Additional Information

- Use this as reference for suggested parameter.
```yaml (paste below)
- name: Display client in console
  community.general.keycloak_client:
    always_display_in_console: True  #On keycloak side this parameter is mapped as alwaysDisplayInConsole
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
