### ISSUE TITLE
Keycloak authentication - validate_certs value is ignored

### ISSUE THREAD

**Issue by whoamiUNIX** [ansible-collections/community.general#4391]
### Summary

community.general.keycloak_authentication module ignore value `False` and I can't disable TLS validation for self signed instance without adding certificate into trust store. I think this should works by default as this is useful for development instances with self signed cert. 

### Issue Type

Bug Report

### Component Name

keycloak_authentication

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.27
  config file = /home/myuser/.ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Fedora release 35 (Thirty Five)

### Steps to Reproduce

```yaml (paste below)
- name: Modify authentication flow for browser
  community.general.keycloak_authentication:
    auth_keycloak_url: "{{ keycloak_configuration_auth_url }}"
    auth_realm: "{{ keycloak_configuration_auth_realm }}"
    auth_username: "{{ keycloak_configuration_auth_username }}"
    auth_password: "{{ keycloak_configuration_auth_password }}"
    validate_certs: False
    realm: "{{ auth.realm }}"
    alias: "{{ auth.alias }}"
    copyFrom: "{{ auth.copyFrom }}"
    description: "{{ auth.description | default(omit) }}"
    authenticationExecutions:
      "{{ auth.authenticationExecutions | default(omit) }}"
    force: "{{ auth.force | default(omit) }}"
    providerId: "{{ auth.providerId | default(omit) }}"
    state: present
  register: auth_results
  delegate_to: localhost
  loop: "{{ keycloak_configuration_authentication }}"
  loop_control:
    loop_var: auth
```

### Expected Results

Task play should use `False` value and ignore not trusted certificate.

### Actual Results

```console (paste below)
` <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
