### ISSUE TITLE
"interpreter_python=auto" does not work with "github_key" Module with only Python3 installed

### ISSUE THREAD

**Issue by hadfiiw** [ansible-collections/community.general#4427]
### Summary

When I have interpreter_python=auto in my ansible.cfg file, the github_key module will not work if the only python installed on my Ansible server is Python3

As a workaround, I changed the line in my ansible.cfg file to be...
interpreter_python=/usr/bin/python3
...and everything works as expected.

### Issue Type

Bug Report

### Component Name

github_key

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/operations/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
$

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
$ 
```

### Configuration

(note, the below is when I have already manually set the python interpreter)

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_FORKS(/home/operations/Workspaces/homelab/ansible.cfg) = 20
DEFAULT_HOST_LIST(/home/operations/Workspaces/homelab/ansible.cfg) = ['/home/operations/Workspaces/homelab/inventory/hosts']
DEFAULT_MODULE_PATH(/home/operations/Workspaces/homelab/ansible.cfg) = ['/home/operations/Workspaces/homelab/library', '/home/operations/Workspaces/homelab/library/vmware', '/hom>
DEFAULT_ROLES_PATH(/home/operations/Workspaces/homelab/ansible.cfg) = ['/home/operations/Workspaces/homelab/roles', '/home/operations/Workspaces/nsxansible/roles', '/home/operati>
HOST_KEY_CHECKING(/home/operations/Workspaces/homelab/ansible.cfg) = False
INTERPRETER_PYTHON(/home/operations/Workspaces/homelab/ansible.cfg) = /usr/bin/python3
$
```

### OS / Environment

Target OS version is PiOS version 11
Ansible server is Ubuntu 20

### Steps to Reproduce

```yaml (paste below)
- name: Authorize key with GitHub
  connection: local
  github_key:
    name: "{{ server_name }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
    force: yes
    state: present
```

### Expected Results

Excepted the module to not fail when "interpreter_python=auto" is set and python 2 is _not_ installed

### Actual Results

```console (paste below)
fatal: [had01-0-cds-b]: FAILED! => {
    "changed": false,
    "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n",
    "module_stdout": "",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/source_control/github/github_key.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/source_control/github/github_key.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @stpierre
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
I think ansible/ansible was the proper place to file this. An issue with the INTERPRETER_PYTHON config wouldn't be specific to a certain module.

I wasn't able to reproduce on 2.9.6. I'm guessing there's some context missing. Did that host run other tasks (or gather facts) before the reproducer task?

If no interpreter is found, there should be a warning that indicates which interpreters were tried like
```
[WARNING]: No python interpreters found for host (tried ['/usr/bin/python', 'python3.7', 'python3.6', 'python3.5', 'python2.7', 'python2.6', '/usr/libexec/platform-
python', '/usr/bin/python3', 'python'])
```

**Comment by hadfiiw** [comment]
Hi @s-hertel  thanks for the reply.

I have been running tasks and using other modules with an ansible.cfg of "interpreter_python=auto" for a few years now but this is the first time any module has complained about this issue.

Per your question, this is actually in a role I created.  Before this module is called in the role, the "user" module and "shell" modules are used without a problem..

BUT I did just notice that this is the only play, within that role, that is running as "connection: local"...

I removed "connection: local" and changed my ansible.cfg back to "interpreter_python=auto" and the module works as expected...

So I checked my ansible server (where the play would run from when set to "connection: local") and I don't have a /usr/bin/python "directory" (which should be a link pointing to /usr/bin/python3.  The /usr/bin/python3 entry does exist).

My only concern is I have other roles that use "connection: local" without an issue (like the "shell", "set_fact", and various vmware modules)...

If /usr/bin/python has to exist for "interpreter_python=auto" to work, I am now scratching my head on how the other modules are working...

Does the github_key module do anything differently when "connection: local" is set or is that totally outside of the module?

**Comment by felixfontein** [comment]
You should probably test with a more up to date 2.9.x version. 2.9.6 is very old and outdated, a **lot** of bugs have been fixed in the latest 2.9.x release since 2.9.6. Maybe this issue has been long resolved in there.

In any case, this is definitely unrelated to this specific module. It is probably related to `connection: local` though.

**Comment by hadfiiw** [comment]
Thanks @felixfontein .  Unfortunately no luck with the latest 2.9....

```
operations@had01-0-cds-a:~/Workspaces/homelab$ ansible --version
ansible 2.9.27
  config file = /home/operations/Workspaces/homelab/ansible.cfg
  configured module search path = ['/home/operations/Workspaces/homelab/library', '/home/operations/Workspaces/homelab/library/vmware', '/home/operations/Workspaces/homelab/library/windows', '/home/operations/Workspaces/nsxansible/library']
  ansible python module location = /home/operations/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
operations@had01-0-cds-a:~/Workspaces/homelab$ 
```

I'll keep digging outside the module.  I could also run a "sudo ln -s /usr/bin/python3 /usr/bin/python" to create the /usr/bin/python "directory" but that still doesn't explain why it works with other modules.  If I find anything out, I'll post it here.

**Comment by s-hertel** [comment]
Once interpreter discovery occurs it's saved as a host fact for future tasks. So the failing task isn't doing interpreter discovery, but using the discovered value from earlier. You could try adding a `- meta: clear_host_facts` task right above the failing task to see if interpreter discovery for that individual task finds /usr/bin/python3. I'm happy to debug if you can share a more complete reproducer, I'm curious what's happening here.

> My only concern is I have other roles that use "connection: local" without an issue (like the "shell", "set_fact", and various vmware modules)...

> If /usr/bin/python has to exist for "interpreter_python=auto" to work, I am now scratching my head on how the other modules are working...

It may not be `connection: local` per se. It might be due to using different connections for the host in the same play or some combination with `connection: local`. I wonder if adding `delegate_to: localhost` to the task would work around it - then it shouldn't use facts for `had01-0-cds-b` (though `delegate_to` had some fixes around 2.9/2.10 so may not work on 2.9.6.).

**Comment by hadfiiw** [comment]
Thanks, I'll give that a shot and let you know what happens...

**Comment by hadfiiw** [comment]
@s-hertel  Thanks for the suggestions!  Test outcome below.  This was all run with version 2.9.27

I added "clear_facts" and that works with "connection: local".  The new role looks like...
```
- name: Generate new SSH key "{{ ssh_key_name }}"
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{ ssh_key_name }}
    ssh_key_passphrase: "{{ ssh_key_pass }}"
    force: yes

- name: Read SSH public key
  shell: cat /home/operations/.ssh/{{ ssh_key_name }}.pub
  register: ssh_pub_key

- meta: clear_facts

- name: Authorize key with GitHub
  connection: local
  github_key:
    name: "{{ server_name }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
    force: yes
    state: present
```


I then removed "clear_facts" and replaced "connection: local" with "delegate_to: localhost" and that also worked.  That part of the role now looked like...
```
- name: Read SSH public key
  shell: cat /home/operations/.ssh/{{ ssh_key_name }}.pub
  register: ssh_pub_key

#- meta: clear_facts

- name: Authorize key with GitHub
  delegate_to: localhost
#  connection: local
  github_key:
    name: "{{ server_name }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
    force: yes
    state: present
```


Then, to be sure it was those changes that "fixed" things, I modified the role to the original config and verified that it fails again.  That part of the role...
```
#- meta: clear_facts

- name: Authorize key with GitHub
#  delegate_to: localhost
  connection: local
  github_key:
    name: "{{ server_name }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
    force: yes
    state: present
```

...and the outcome of the "failed" role...
```
PLAY [Configure Pi Ansible Server] ************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************
[WARNING]: Platform linux on host had01-0-cds-b is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change
this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [had01-0-cds-b]

TASK [github-create-access-key : Generate new SSH key "gh_cds_id_rsa"] ************************************************************************************************************
ok: [had01-0-cds-b]

TASK [github-create-access-key : Read SSH public key] *****************************************************************************************************************************
changed: [had01-0-cds-b]

TASK [github-create-access-key : Authorize key with GitHub] ***********************************************************************************************************************
fatal: [had01-0-cds-b]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP ************************************************************************************************************************************************************************
had01-0-cds-b              : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

I always thought that "connection: local" and "delegate_to: localhost" served the same purpose - but maybe not?  I have some reading to do...

Thanks again!
