### ISSUE TITLE
[cloudflare_dns] solo: true keeps last record when multiple CNAME with same name

### ISSUE THREAD

**Issue by vshuraeff** [ansible-collections/community.general#4433]
### Summary

I want to add multiple `CNAME` records with same name targeted to list of hosts. when I run playbook I see only one last record instead if all.

### Issue Type

Bug Report

### Component Name

`cloudflare_dns` 

### Ansible Version

``` console
$ ansible --version
ansible [core 2.12.2]
$ brew info ansible 
ansible: stable 5.3.0 (bottled), HEAD
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.6.1

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

# nothin special
```

### OS / Environment

MacOS 12.2.1, homebrew ansible, asdf python3.10 

### Steps to Reproduce

```yaml (paste below)
- name: create CNAME shortcuts in CF
  tags:
    - cloudflare
  cloudflare_dns:
    state: present
    solo: False
    account_api_key: "{{ cloudflare_api_key }}"
    account_email: "{{ cloudflare_api_email }}"
    zone: "{{ cluster_base_fqdn }}"
    record: cluster
    proxied: false
    type: CNAME
    value: "{{ item }}.{{ cluster_base_fqdn }}"
  with_items: "{{ groups.cluster_servers }}"
```

### Expected Results

expected 3 records in dns with same name and values from `groups.cluster_servers` 

### Actual Results

```console (paste below)
changed: [localhost] => (item=cluster-server3) => changed=true 
  ansible_loop_var: item
  invocation:
    module_args:
      account_api_key: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      account_email: CENSORED
      algorithm: null
      api_token: null
      cert_usage: null
      hash_type: null
      key_tag: null
      port: null
      priority: 1
      proto: null
      proxied: false
      record: cluster
      selector: null
      service: null
      solo: false
      state: present
      timeout: 30
      ttl: 1
      type: CNAME
      value: cluster-server3.domain.com
      weight: 1
      zone: domain.com
  item: cluster-server3
  result:
    record:
      content: cluster-server3.domain.com
      created_on: '2022-04-01T14:30:54.735038Z'
      id: -
      locked: false
      meta:
        auto_added: false
        managed_by_apps: false
        managed_by_argo_tunnel: false
        source: primary
      modified_on: '2022-04-01T14:53:35.956052Z'
      name: cluster.domain.com
      proxiable: true
      proxied: false
      ttl: 1
      type: CNAME
      zone_id: -
      zone_name: domain.com
```
it runs 3 time with each of server, but record is still for last

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
