### ISSUE TITLE
filter/version_sort: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by simontunnat** [ansible-collections/community.general#4451]
### Summary

The "version_sort" filter fails to sort the following list of versions:
`
[ "1.1.0-SNAPSHOT", "1.1-SNAPSHOT" ]
`

It works fine for the same version numbers without -SNAPSHOT suffixes:
`
[ "1.1.0", "1.1" ]
`

### Issue Type

Bug Report

### Component Name

filter/version_sort

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.12.4]
  config file = /home/XXX/YYY/ansible.cfg
  configured module search path = ['/home/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/XXX/YYY/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

Collection        Version
----------------- -------
community.general 4.6.1  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml (paste below)
---
- name: Working version_sort
  hosts: all
  gather_facts: false
  tasks:
    - name: Show the sorted versions
      ansible.builtin.debug:
        var: versions

  vars:
    versions: >-
      {{ [ "1.1.0", "1.1" ] | community.general.version_sort }}

- name: Failing version_sort
  hosts: all
  gather_facts: false
  tasks:
    - name: Show the sorted versions
      ansible.builtin.debug:
        var: versions

  vars:
    versions: >-
      {{ [ "1.1.0-SNAPSHOT", "1.1-SNAPSHOT" ] | community.general.version_sort }}
```

### Expected Results

ok: [localhost] => {
    "versions": [
        "1.1-SNAPSHOT",
        "1.1.0-SNAPSHOT"
    ]
}

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ [ \"1.1.0-SNAPSHOT\", \"1.1-SNAPSHOT\" ] | community.general.version_sort }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ [ \"1.1.0-SNAPSHOT\", \"1.1-SNAPSHOT\" ] | community.general.version_sort }}): '<' not supported between instances of 'str' and 'int'"}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
