### ISSUE TITLE
Iscsi discover incorrectly formats command for ipv6 addresses

### ISSUE THREAD

**Issue by twiclo** [ansible-collections/community.general#4467]
### Summary

My playbook fails when running the below task
```
- name: Perform a discovery on the iscsi target
  community.general.open_iscsi:
    show_nodes: yes
    discover: yes
    portal: example.com
    auto_portal_startup: yes
```
The command it tries to run is
`/usr/sbin/iscsiadm --mode discovery --type sendtargets --portal blah:blah:blah::1:3260`
When it should be
`/usr/sbin/iscsiadm --mode discovery --type sendtargets --portal [blah:blah:blah::1]:3260`

Looks like the code doesn't care what the type is and just appends `:3260`
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/system/open_iscsi.py
Lines 343-347

### Issue Type

Bug Report

### Component Name

iscsi

### Ansible Version

```console (paste below)
ansible [core 2.12.4]
  config file = /home/twiclo/Projects/ansible/ansible.cfg
  configured module search path = ['/home/twiclo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/twiclo/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/twiclo/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/twiclo/.local/bin/ansible
  python version = 3.9.10 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.1.1
  libyaml = True
```

### Community.general Version

```console (paste below)

# /home/twiclo/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.6.1  

# /home/twiclo/.local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.7.0  
```

### Configuration

```console (paste below)
DEFAULT_HOST_LIST(/home/twiclo/Projects/ansible/ansible.cfg) = ['/home/twiclo/Projects/ansible/inventory.yml']
HOST_KEY_CHECKING(/home/twiclo/Projects/ansible/ansible.cfg) = False

```

### OS / Environment

Fedora

### Steps to Reproduce

```yaml (paste below)
- name: Perform a discovery on the iscsi target
  community.general.open_iscsi:
    show_nodes: yes
    discover: yes
    portal: example.com
    auto_portal_startup: yes
```

### Expected Results

`/usr/sbin/iscsiadm --mode discovery --type sendtargets --portal [blah:blah:blah::1]:3260`

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
