### ISSUE TITLE
nsupdate module does not work as documented with pythondns 2.1.0

### ISSUE THREAD

**Issue by itcultus** [ansible-collections/community.general#4484]
### Summary

When I try to create a reverse DNS entry without setting the zone it fails with rc 5 (refused)
I noticed this:

  dns_rc: 5
  dns_rc_str: REFUSED
  invocation:
    module_args:
      key_algorithm: hmac-sha512
      key_name: <keyname>
      key_secret: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      port: 53
      protocol: tcp
      record: 32.0.10.10.in-addr.arpa.
      server: 10.0.0.1
      state: present
      ttl: 3600
      type: PTR
      value:
      - demo.example.com.
      zone: null

The same code if executed on my openSUSE Leap 15.3 which has dnspython 1.15 works perfectly fine.

I tried to debug the output and the issue seems to be related to dnspython. An issue is already filled in the [dnspython library ](https://github.com/rthalley/dnspython/issues/803).
Long story short, the DNS zone returned from the library is wrong or it's expecting something different. 

As described in the above issue report, the dns zone returned from the library seems to be the parent zone. 
For example, if the PTR record is `32.0.10.10.in-addr.arpa.` the zone should be `0.10.10.in-addr.arpa.`, however, the library returns `10.10.in-addr.arpa.` and as a result it fails. 

I think until the  [dnspython issue ](https://github.com/rthalley/dnspython/issues/803) is resolved, documentation should reflect this and the description of the `zone` attribute, as well as the examples, should reflect this. 

### Issue Type

Bug Report

### Component Name

nsupdate

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.27
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```
N/A

### OS / Environment

Fedora 34

### Steps to Reproduce

```yaml (paste below)
  nsupdate:
    key_algorithm: "{{ keyalgo }}"
    key_name: "{{ key_name }}"
    key_secret: "{{ key_secret }}"
    server: dns.example.com
    record: "32.0.0.1.in-addr.arpa."
    type: "PTR"
    value: "host.example.com."
    state: present
```

### Expected Results

PTR record is updated. 

### Actual Results

```console (paste below)
msg: 'Failed to create DNS record (rc: 5)'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
