### ISSUE TITLE
xen_orchestra inventory plugin problematic environment variable names ( Error in AWX)

### ISSUE THREAD

**Issue by kebl-reflact** [ansible-collections/community.general#4501]
### Summary

When unsing the Inventory Plugin xen_orchestra with AWX, I am unable to inject the environment Variabels. 
AWX seems to have an issue with environment Variables in credentials starting with ANSIBLE_ since these could affect Ansible itself.

Since I think it's a valid error, I would propose a new environment variable naming structure for this module by removing the "ANSIBLE_" part of it and starting with "XO_" instead.
This would be more in line with other inventory plugins in this collection, by simultaniously shorten and make the vars more complicit

### Issue Type

Bug Report

### Component Name

xen_orchestra
https://docs.ansible.com/ansible/latest/collections/community/general/xen_orchestra_inventory.html

### Ansible Version

ansible             5.6.0

### Community.general Version

community.general             4.7.0

### OS / Environment

AWX 20.1.0

### Steps to Reproduce

https://awx.example.com/#/credential_types/
Input configuration
```yaml (paste below)
fields:
  - id: XO_USER
    type: string
    label: XenOrchestra User
  - id: XO_PASSWORD
    type: string
    label: XenOrchestra Password
    secret: true
  - id: XO_HOST
    type: string
    label: XenOrchestra Host
required:
  - XO_USER
  - XO_PASSWORD
  - XO_HOST
```
Injector configuration
```yaml
env:
  ANSIBLE_XO_HOST: '{{ XO_HOST }}'
  ANSIBLE_XO_USER: '{{ XO_USER }}'
  ANSIBLE_XO_PASSWORD: '{{ XO_PASSWORD }}'
```

### Expected Results

No error because of the variable name.

### Actual Results

```console (paste below)
Environment variable ANSIBLE_XO_HOST may affect Ansible configuration so its use is not allowed in credentials.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
