### ISSUE TITLE
I couldn't to delete multiple tables from Postgresql

### ISSUE THREAD

**Issue by muhaarif** [ansible-collections/community.general#451]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_table

##### ANSIBLE VERSION

```paste below
ansible 2.9.7

```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/ubuntu/Ansible/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = postgres
```

##### OS / ENVIRONMENT

Ubuntu 18

##### STEPS TO REPRODUCE

I couldn't to delete multiple tables from Postgresql

```yaml
---

- hosts: serv1-mainDB
gather_facts: true
become: true
tasks:
- name: "post-db-t-rm"
postgresql_table:
db: healcare
login_password: password
login_user: dbuser
name: "{{ item }}"
state: absent
with_items:
- acc.one
- acc.two
```

##### EXPECTED RESULTS

I need to delete multiple tables

##### ACTUAL RESULTS

ERROR! 'with_items' is not a valid attribute for a Play.
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: No JSON object could be decoded.

```paste below

```
