### ISSUE TITLE
rhsm_repository is really slow

### ISSUE THREAD

**Issue by CendioOssman** [ansible-collections/community.general#452]
##### SUMMARY
Using rhsm_repository is really slow, making it annoying to use a playback that uses it.
(copied from https://github.com/ansible/ansible/issues/69722)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rhsm_repository

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
[defaults]
stdout_callback = yaml
force_handlers = True
```

##### OS / ENVIRONMENT
Ansible machine:
Target machine: RHEL 8

##### STEPS TO REPRODUCE
```yaml
- name: enable Red Hat CodeReady repo
  rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
```

##### EXPECTED RESULTS
The above task should complete in a short time, at least when the repository is already enabled.

##### ACTUAL RESULTS
You have time to get coffee whilst your playbook runs.
