### ISSUE TITLE
When importing an amazon correto certificate with java_cert, the response is lost. The following patch will fix it.

### ISSUE THREAD

**Issue by banil246** [ansible-collections/community.general#4523]
### Summary

_check_cert_present is no response

--- java_cert.py.org    2022-04-18 15:02:24.121828400 +0900
+++ java_cert.py        2022-04-18 14:57:28.923968600 +0900
@@ -207,7 +207,7 @@
     ]
     test_cmd += _get_keystore_type_keytool_parameters(keystore_type)

-    (check_rc, stdout, dummy) = module.run_command(test_cmd, data=keystore_pass, check_rc=False)
+    (check_rc, stdout, dummy) = module.run_command(test_cmd, data="%s\n%s" % ( keystore_pass, keystore_pass ), check_rc=False)
     if check_rc == 0:
         return (True, stdout)
     return (False, '')

### Issue Type

Bug Report

### Component Name

java_cert

### Ansible Version

```console (paste below)
$ ansible --version

```
2.12.1

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```
4.7.0

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Import trusted CA from SSL certificate
  community.general.java_cert:
    cert_path: /opt/certs/rootca.crt
    keystore_path: /tmp/cacerts
    keystore_pass: changeit
    keystore_create: yes
    state: present
    cert_alias: LE_RootCA
    trust_cacert: True
```

### Expected Results

none
no response

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
