### ISSUE TITLE
pritunl_user: Always get HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by vvatlin** [ansible-collections/community.general#4527]
### Summary

Hello. 

I always get HTTP Error 401: Unauthorized when I try to create user, but for Organization everything is ok. 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "HTTP Error 401: Unauthorized"}
```

Http log:
```
49.12.xx.xx - - [19/Apr/2022:09:17:02 +0000] "GET /organization HTTP/1.1" 200 130 "-" "Python-urllib/3.8"
49.12.xx.xx - - [19/Apr/2022:09:17:02 +0000] "GET /user/6206687703ab512b88adbb14 HTTP/1.1" 200 4173 "-" "Python-urllib/3.8"
49.12.xx.xx - - [19/Apr/2022:09:17:02 +0000] "POST /user/6206687703ab512b88adbb14 HTTP/1.1" 401 17 "-" "Python-urllib/3.8"
```

I can see that /organization and /user are working correctly, so I think I have correct api_key and secret_token , but when I try to create user I always get 401 Unauthorized.

could you please help me ?

```
- name: create user
  hosts: localhost
  connection: local

  tasks:
    - name: create the user foo with email address foo@
      community.general.pritunl_user:
        pritunl_api_secret: qjE50Psxxxxxxxx
        pritunl_api_token: 0ecqo1uxxxxxxxxxxx
        pritunl_url: https://vpn.mydomain.com
        organization: org
        state: present
        user_groups: org
        user_name: foo
        user_email: foo@mydomain.com
```

### Issue Type

Bug Report

### Component Name

pritunl_user

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.4]
  config file = /home/vadim/ansible/ansible.cfg
  configured module search path = ['/home/vadim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/vadim/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/vadim/ansible/ansible.cfg) = True
DEFAULT_BECOME(/home/vadim/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/vadim/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/vadim/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/vadim/ansible/ansible.cfg) = root
DEFAULT_FORKS(/home/vadim/ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/home/vadim/ansible/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/vadim/ansible/ansible.cfg) = merge
DEFAULT_MANAGED_STR(/home/vadim/ansible/ansible.cfg) = Ansible managed: modified on %Y-%m-%d %H:%M:%S by {uid}
DEFAULT_ROLES_PATH(/home/vadim/ansible/ansible.cfg) = ['/home/vadim/ansible/roles']
DEFAULT_TIMEOUT(/home/vadim/ansible/ansible.cfg) = 30
DEPRECATION_WARNINGS(/home/vadim/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/vadim/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/vadim/ansible/ansible.cfg) = auto_silent
```

### Steps to Reproduce

```yaml (paste below)
- name: create user
  hosts: localhost
  connection: local

  tasks:
    - name: create the user foo with email address foo@
      community.general.pritunl_user:
        pritunl_api_secret: qjE50Psxxxxxxxx
        pritunl_api_token: 0ecqo1uxxxxxxxxxxx
        pritunl_url: https://vpn.mydomain.com
        organization: org
        state: present
        user_groups: org
        user_name: foo
        user_email: foo@mydomain.com
```

### Expected Results

User has been created

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
