### ISSUE TITLE
Filter containers by multiple labels

### ISSUE THREAD

**Issue by Yajo** [ansible-collections/community.general#453]
##### SUMMARY

Cannot filter for multiple labels.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_host_info

##### ADDITIONAL INFORMATION

This cannot work because we can't define the same key twice in a dict:

```yaml
- name: find running docker containers
  register: docker_info
  docker_host_info:
    containers: yes
    containers_filters:
      label: com.docker.compose.project=myproject # THIS GETS IGNORED
      label: com.docker.compose.service=backup
```

Possible solutions:

1.  Allow a list in `containers_filters`:

    ```yaml
    - name: find running docker containers
      register: docker_info
      docker_host_info:
        containers: yes
        containers_filters:
          - label=com.docker.compose.project=myproject
          - label=com.docker.compose.service=backup
    ```

1.  Allow a dict in `containers_filters.label` filter:

    ```yaml
    - name: find running docker containers
      register: docker_info
      docker_host_info:
        containers: yes
        containers_filters:
          label:
            com.docker.compose.project: myproject
            com.docker.compose.service: backup
    ```

I have not tested, but I guess the same applies to `images_filters`, `networks_filters` and `volumes_filters`.

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cloud/docker/docker_host_info.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/docker/docker_host_info.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @danihodovic @dariko @felixfontein @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
This is the interface provided by Docker itself: it wants a dictionary of filters. If we provide something more sophisticated, we probably have to parse and process this by ourselves.

**Comment by Yajo** [comment]
But you can actually do that filtering with CLI, right?

**Comment by felixfontein** [comment]
No idea. Feel free to figure out how the CLI does it.

**Comment by Yajo** [comment]
Definitely the CLI can do it:

![2020-06-05_09-30](https://user-images.githubusercontent.com/973709/83854847-31cba880-a70f-11ea-8117-39bf4af1bf58.png)

I think you use docker-py behind the scenes, right? [Its docs say you can pass a list to the label fiilter](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.list). That would easily map like this to ansible:

```yaml
- name: find running docker containers
  register: docker_info
  docker_host_info:
    containers: yes
    containers_filters:
      label:
        - com.docker.compose.project=myproject
        - com.docker.compose.service=backup
```
