### ISSUE TITLE
ipa_dnsrecord: multiple record_value

### ISSUE THREAD

**Issue by genofire** [ansible-collections/community.general#4553]
### Summary

It is not possible to manage multiple records under same name.

- call this module multiple time replaced the old value
- record_value accept only one value

### Issue Type

Bug Report

### Component Name

ipa_dnsrecord

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.27
  python version = 3.9.11 (main, ...)
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
invalid choice 'list'
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
ipa_dnsrecord:
  name: "a"
  zone_name: "example.org"
  record_value: [ "127.0.0.1", "127.0.0.2" ]
```

(Call this module multiple time replaced the old value)

### Expected Results

Add both IP-Adresses.

### Actual Results

```console (paste below)

```

invalid a_rec

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
