### ISSUE TITLE
sefcontext: the doc example fails with "type ... is invalid, must be a file or device type"

### ISSUE THREAD

**Issue by marcindulak** [ansible-collections/community.general#4564]
### Summary

It looks that the example included in the documentation https://docs.ansible.com/ansible/2.9/modules/sefcontext_module.html fails

```yaml
- name: Allow apache to modify files in /srv/git_repos
  sefcontext:
    target: '/srv/git_repos(/.*)?'
    setype: httpd_git_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv /srv/git_repos
```

It results in the following error
```
...
TASK [Allow apache to modify files in /srv/git_repos] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ValueError: Type httpd_git_rw_content_t is invalid, must be a file or device type\n"}
```

Maybe `httpd_sys_rw_content_t` instead of `httpd_git_rw_content_t` was meant to be used?

### Issue Type

Bug Report

### Component Name

sefcontext

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Nov 17 2021, 16:10:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

### Community.general Version

As part of ansible 2.9, no separate community modules are used.

```console (paste below)
$ ansible-galaxy collection list community.general
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

```
$ cat /etc/*release | grep PRETTY
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
```

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  become: True
  tasks:
  - name: Allow apache to modify files in /srv/git_repos
    sefcontext:
      target: '/srv/git_repos(/.*)?'
      setype: httpd_git_rw_content_t
      state: present

  - name: Apply new SELinux file context to filesystem
    command: restorecon -irv /srv/git_repos
```

### Expected Results

Successful execution.

### Actual Results

```console (paste below)
ansible-playbook play.yaml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

PLAY [localhost] ***************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************
ok: [localhost]

TASK [Allow apache to modify files in /srv/git_repos] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ValueError: Type httpd_git_rw_content_t is invalid, must be a file or device type\n"}

PLAY RECAP *********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
