### ISSUE TITLE
community.general.gitlab_group module fails without optional arguments

### ISSUE THREAD

**Issue by lupa95** [ansible-collections/community.general#4577]
### Summary

When i try to run community.general.gitlab_group module without specifying "subgroup_creation_level" or "project_creation_level", the task fails with gitlab error 500. Both arguments are not specified as "required" in the module documentation. I ran this task against Gitlab EE 14.7.6.

Example without specifying "subgroup_creation_level":
```
The full traceback is:
  File "/tmp/ansible_community.general.gitlab_group_payload_1um8dni8/ansible_community.general.gitlab_group_payload.zip/ansible_collections/community/general/plugins/modules/gitlab_group.py", line 258, in create_group
  File "/usr/local/lib/python3.8/dist-packages/gitlab/exceptions.py", line 313, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
fatal: [ttps://git.example.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_job_token": null,
            "api_oauth_token": null,
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_token": null,
            "api_url": "https://git.example.com",
            "api_username": "root",
            "auto_devops_enabled": null,
            "avatar_path": null,
            "description": "test",
            "name": "mys2_first_group",
            "parent": "parent",
            "path": "mys2_first_group",
            "project_creation_level": "maintainer",
            "require_two_factor_authentication": null,
            "state": "present",
            "subgroup_creation_level": null,
            "validate_certs": false,
            "visibility": "private"
        }
    },
    "msg": "Failed to create group: 500: 500 Internal Server Error "
}
```

### Issue Type

Bug Report

### Component Name

community.general.gitlab_group

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.2]
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
ansible [core 2.12.2]
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.1
  libyaml = True
root@81f25ddf34f8:/ansible# community.general.gitlab_group^C
root@81f25ddf34f8:/ansible# ansible-galaxy collection list community.general

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

Run this task and comment out either one of the arguments mentioned in the description
```yaml (paste below)
- name: "Create GitLab Group"
  community.general.gitlab_group:
    api_url: https://git.example.com/
    validate_certs: False
    parent: "parent"
    subgroup_creation_level: maintainer # comment out one of those
    project_creation_level: maintainer # comment out one of those
    api_username: "test"
    description: "test"
    api_password: "test"
    name: my_first_group
    path: my_first_group
    state: present
```

### Expected Results

I expect the module to work without specifying both arguments, because they are not marked as "required" in the module documentation and they are not part of the first three examples. (They don't work)

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
