### ISSUE TITLE
redfish_command VirtualMediaInsert does not work with HPE iLO4

### ISSUE THREAD

**Issue by adarobin** [ansible-collections/community.general#4595]
### Summary

When I attempt to use redfish_command to mount virtual media on a server with HPE iLO4 I get an error.

I used mitmproxy to look at the full response and I see that it is because `Inserted` is not a supported argument for the Patch request.
```
{
    "error": {
        "@Message.ExtendedInfo": [
            {
                "MessageArgs": [
                    "Inserted"
                ],
                "MessageId": "Base.0.10.PropertyUnknown"
            }
        ],
        "code": "iLO.0.10.ExtendedInfo",
        "message": "See @Message.ExtendedInfo for more information."
    }
}
```

Poking around on https://redfish.dmtf.org/schemas/v1/ it looks like VirtualMedia schema 1.1.0 and earlier have `Inserted` as a read-only attribute. It looks like this is breaking due to `Inserted` being forced into the request body. https://github.com/ansible-collections/community.general/blob/c3aba0f10e5d1641d77669f68ddb9173a0c8ca1d/plugins/module_utils/redfish_utils.py#L2246

~~I am going to see if I can add a check for the version contained in `@odata.type` on that line. I can submit a PR, but I don't have a way of knowing if this would break any other hardware. I would expect the hardware that requires the `Inserted` field would not be using a version of the schema where that field is designated as read-only.~~

The PR I have submitted checks the `FirmwareVersion` to see if it starts with "iLO 4" so the fix should not impact any other hardware types.

### Issue Type

Bug Report

### Component Name

redfish_command

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/Users/adarobin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/adarobin/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/adarobin/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/adarobin/ansible/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /Users/adarobin/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.0  

# /Users/adarobin/ansible/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- community.general.redfish_command:
    auth_token: '{{ iloToken }}'
    baseuri: '{{ iloAddress }}'
    category: 'Manager'
    command: 'VirtualMediaInsert'
    virtual_media:
      image_url: 'http://example.com/rhel-8.5-x86_64-boot.iso'
      media_types:
        - CD
        - DVD
      write_protected: null
      inserted: null
  delegate_to: localhost
```

### Expected Results

Virtual media is attached to the server

### Actual Results

```console (paste below)
TASK [provision_host : community.general.redfish_command] ***************************************************************************************
fatal: [redacted -> localhost]: FAILED! => {"changed": false, "msg": "HTTP Error 400 on PATCH request to 'https://10.111.250.26/redfish/v1/Managers/1/VirtualMedia/2/', extended message: 'Bad Request'"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
