### ISSUE TITLE
gitlab_runner unable to create runner

### ISSUE THREAD

**Issue by tormodmacleod** [ansible-collections/community.general#4622]
### Summary

when i try to create a group runner it reports success but doesn't appear to perform all of the necessary actions

### Issue Type

Bug Report

### Component Name

gitlab_runner

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.4]

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/tormod/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.0  


```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora 35

### Steps to Reproduce

```yaml (paste below)

- name: gitlab_runner - register runner
  community.general.gitlab_runner:
    access_level: not_protected
    api_url: https://gitlab.com/
    api_token: '{{ vault_all_gitlab_api_token }}'
    registration_token: '{{ vault_gitlab_registration_token }}'
    description: ansible_container_host
    state: present
    active: true
    tag_list: ['podman','fedora','linux','redhat','turnberry']
    run_untagged: false
    locked: false
    owned: true
  when: gitlab_runner_shell is defined and gitlab_runner_shell == true

```

### Expected Results

i expected the runner to be registered with gitlab.com and the runner to be running locally

### Actual Results

```console (paste below)
TASK [gitlab-runner : gitlab_runner - register runner] ********************************************************************************************************************
changed: [ansible_container_host]
```
as above, ansible reports that it has completed the task. when i look at the runners on gitlab.com i can see that it has been created

![image](https://user-images.githubusercontent.com/38500472/166829615-d56377c9-b8a2-4445-953c-65d3970be8b1.png)

however, the runner is not configured in `/etc/gitlab-runner/config.toml` on the host

```yaml (paste below)

# cat /etc/gitlab-runner/config.toml 
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800
```

```

# gitlab-runner list
Runtime platform                                    arch=amd64 os=linux pid=13413 revision=f761588f version=14.10.1
Listing configured runners                          ConfigFile=/etc/gitlab-runner/config.toml
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
