### ISSUE TITLE
nmcli module doesn't support `autoconnect.priority`

### ISSUE THREAD

**Issue by shosti** [ansible-collections/community.general#4634]
### Summary

I am trying to set up an internet connection with failover using the `nmcli` plugin, but the `connection.autoconnect-priority` isn't supported. It would be nice if it were supported.

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

```yaml (paste below)
- name: Add cellular connection
  community.general.nmcli:
    conn_name: cellular
    autoconnect: yes
    autoconnect_priority: yes
    type: gsm
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
