### ISSUE TITLE
When mysql_db fails to decompress a file for an import, it returns an empty byte string for an error.

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.general#464]
_Copied from https://github.com/ansible/ansible/issues/41505_
_Initially reported by @Everspace_

##### SUMMARY

When mysql_db fails to decompress a file for an import, it returns an empty byte string for an error.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
mysql_db

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/library', '/usr/share/ansible']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, May  5 2018, 03:09:35) [GCC 4.9.2]
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Create a bogus dump to pull from `weird.sql.bz2`, or prevent it from being accessed then attempt to 

```yaml
  - name: Import Dump
    become: no
    run_once: yes
    local_action:
      module: mysql_db
      login_host: my_host.com
      login_user: root
      login_password: password
      name: my_db
      state: import
      target: weird.sql.bz2
```

##### EXPECTED RESULTS

A useful message or diagnostic message to indicate that bzip2 or whatever failed for whatever reason. 

Should probably include the return code as well through something like `module.fail_json(code = p1.returncode)`

##### ACTUAL RESULTS

```
[server] => {"changed": false, "msg": "b''", ...
```

bzip2 returned error code -13
