### ISSUE TITLE
Cannot update "NS" types entries from Bind9 managed DNS zone

### ISSUE THREAD

**Issue by Simon-TheUser** [ansible-collections/community.general#4657]
### Summary

When running a nsupdate task where the type: "NS" is used, Ansible reports a successful change.

Unfortunately, Bind9 will silently ignore the deletes statement for NS type for a zone and the Ansible change does not work.

### Issue Type

Bug Report

### Component Name

nsupdate

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/github.Simon-TheUser.community.general/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/github.Simon-TheUser.community.general/venv/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.8.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

The changes are made against a Bind9.18 DNS Server

### Steps to Reproduce

Before running the test, gather the list of NS entries for a DNS zone.
```console (paste below)
$ dig NS lab @192.168.1.2 +short
ns6.lab.
ns3.lab.
ns2.lab.
ns4.lab.
```

Create a task that does not include the ns3.lab. entry and execute it:

```yaml (paste below)
  tasks:
    - name: New NS entries
      set_fact:
        ns_list:
          - 'ns2.lab.'
          - 'ns4.lab.'
          - 'ns6.lab.'

    - name: Update NS entries
      community.general.nsupdate:
        key_name: '{{ rndc_key_name }}'
        key_secret: '{{ rndc_key }}'
        key_algorithm: 'hmac-sha256'
        server: "192.168.1.2"
        zone: "lab."
        record: "lab."
        value: "{{ ns_list }}"
        type: "NS"
```

```console
$ ansible-playbook test_NS_nsupdate.yml 

PLAY [Test for Dynamic DNS updates of NS entries with Bind9] **********************************************************************************************************************************************************************

TASK [New NS entries] *************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Update NS entries] **********************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### Expected Results

After executing the task, I would expect the new list of NS records to only contain 3 items:

```console (paste below)
$ dig NS lab @192.168.1.2 +short
ns6.lab.
ns2.lab.
ns4.lab.
```

### Actual Results

Running the domain query shows that ns3.lab. is still present as a NS entry:

```console (paste below)
$ dig NS lab @192.168.1.2 +short
ns6.lab.
ns3.lab.
ns2.lab.
ns4.lab.
```

Inside the Bind9 logs, you can see that the delete request for NS records is ignored:
```
09-May-2022 18:00:50.352 client @0x7fe7dd1f9568 192.168.1.3#45458/key rndc_ddns_ansible: updating zone 'lab/IN': attempt to delete all SOA or NS records ignored
```
Bind9 source code reference: https://gitlab.isc.org/isc-projects/bind9/-/blob/v9_18/lib/ns/update.c#L3304

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
