### ISSUE TITLE
nmap inventory plugin to support non DNS-resolvable hosts

### ISSUE THREAD

**Issue by felizkk** [ansible-collections/community.general#4658]
### Summary

Currently nmap.py inventory plugin only outputs hosts that are DNS resolvable.
However, outputting all hosts regardless of DNS resolution can be useful in may cases i.e. include host names that are just IP addresses as ansible inventory.
This is basically using '-n' as the nmap argument.

In my case, I modify nmap.py to force "nmap -n" execution with this line:
cmd.append('-n')

I think having the plugin parameter options for DNS resolution will be useful so users can have a choice.

### Issue Type

Feature Idea

### Component Name

nmap.py

### Additional Information

```yaml (paste below)
plugin: community.general.nmap
address: 192.168.1.0/24
strict: False
ports: True
dnsresolve: False
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
