### ISSUE TITLE
community.general.sudoers add parameter "exclusive"

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible-collections/community.general#4678]
### Summary

Hi all,
the current version of community.general.sudoers always overwrites the sudoers file with the commands from the task.
Instead of always overwriting, it should be able to verify, that the given command(s) is/are present/absent without touching the others. Basically the same function as in the authorized_key module with its "exclusive" parameter

### Issue Type

Feature Idea

### Component Name

sudoers

### Additional Information

```yaml (paste below)
- name: Set authorized key, removing all the authorized keys already set
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', 'public_keys/doe-jane') }}"
    state: present
    exclusive: True

- name: Allow the backup user to sudo /usr/local/bin/backup
  community.general.sudoers:
    name: allow-backup
    state: present
    user: backup
    commands: /usr/local/bin/backup
    exclusive: False
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
