### ISSUE TITLE
5.0.0 community.general.locale_gen doesn't exist

### ISSUE THREAD

**Issue by thinkl33t** [ansible-collections/community.general#4706]
### Summary

When upgrading community.general from 4.x to 5.0.0, the locale_gen module is no longer found.  This works fine if we specify community.general<5.0.0 when installing the collection.

### Issue Type

Bug Report

### Component Name

community.general.locale_gen

### Ansible Version

```console (paste below)
$ ansible --version

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.0.2  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Ensure locale is en_GB.UTF-8
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: present
```

### Expected Results

locale_gen module to exist and work.

### Actual Results

```console (paste below)
ERROR! couldn't resolve module/action 'community.general.locale_gen'. This often indicates a misspelling, missing collection, or incorrect module path.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
