### ISSUE TITLE
nmcli: TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by learnitall** [ansible-collections/community.general#472]
##### SUMMARY
Almost a year ago now, an issue was brought up with the `nmcli` module (https://github.com/ansible/ansible/issues/59095).  Essentially this issue states that when `nmcli` will go to create or modify bridges by executing a command with  `ansible.module_utils.basic.AnsibleModule.run_command`, it will pass a `list` that contains non-text objects which causes a `TypeError` to be raised later on. The bridge interface is the only interface type in the `nmcli` module that seems to have this issue.

A pull request was created by @marcin-sucharski (https://github.com/ansible/ansible/pull/58115) that should fix the issue, but it was never merged. I'm adding this issue here since now `nmcli` has been moved to the `community.general` collection and the original issue has a `needs_collection_redirect` label. Thanks!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nmcli

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rdrew/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
```

##### OS / ENVIRONMENT

Both my deployment host and target hosts are rocking CentOS 7 with an outdated kernel:

`uname -a`:

```
Linux my.censored.hostname 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

`cat /etc/os-release`

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

##### STEPS TO REPRODUCE

All of these playbook snippets will reproduce the problem:

Minimal parameters specified:

```yaml
- name: Add a br-mgmt interface
  nmcli:
    state: present
    conn_name: br-mgmt
    ifname: br-mgmt
    type: bridge
    autoconnect: yes
```

`community.general` collection from Ansible Galaxy used:

```yaml
- name: Add a br-mgmt interface
  community.general.nmcli:
    state: present
    conn_name: br-mgmt
    ifname: br-mgmt
    type: bridge
    autoconnect: yes
```

All parameters specified:

```yaml
- name: Add a br-mgmt interface
  nmcli:
    state: present
    conn_name: br-mgmt
    ifname: br-mgmt
    type: bridge
    autoconnect: yes
    ip4: ''
    gw4: ''
    ip6: ''
    gw6: ''
    stp: yes
    priority: 12
    slavepriority: 32
    forwarddelay: 15
    hellotime: 2
    maxage: 20
    ageingtime: 300
    hairpin: yes
    path_cost: 100
```

##### EXPECTED RESULTS

A new bridge interface named `br-mgmt` is added.

##### ACTUAL RESULTS

Relevant playbook snippet

```yaml
- name: Add a br-mgmt interface
  nmcli:
    state: present
    conn_name: br-mgmt
    ifname: br-mgmt
    type: bridge
    autoconnect: yes
    ip4: ''
    gw4: ''
    ip6: ''
    gw6: ''
    stp: yes
    priority: 12
    slavepriority: 32
    forwarddelay: 15
    hellotime: 2
    maxage: 20
    ageingtime: 300
    hairpin: yes
    path_cost: 100
```

```paste below
fatal: [my.censored.hostname]: FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to my.censored.hostname closed.\r\n", 
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/rdrew/.ansible/tmp/ansible-tmp-1591484621.63-5274-190515947338267/AnsiballZ_nmcli.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/rdrew/.ansible/tmp/ansible-tmp-1591484621.63-5274-190515947338267/AnsiballZ_nmcli.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/rdrew/.ansible/tmp/ansible-tmp-1591484621.63-5274-190515947338267/AnsiballZ_nmcli.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.nmcli', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_community.general.nmcli_payload_IUFCxF/ansible_community.general.nmcli_payload.zip/ansible_collections/community/general/plugins/modules/nmcli.py\", line 1547, in <module>\r\n  File \"/tmp/ansible_community.general.nmcli_payload_IUFCxF/ansible_community.general.nmcli_payload.zip/ansible_collections/community/general/plugins/modules/nmcli.py\", line 1525, in main\r\n  File \"/tmp/ansible_community.general.nmcli_payload_IUFCxF/ansible_community.general.nmcli_payload.zip/ansible_collections/community/general/plugins/modules/nmcli.py\", line 1423, in modify_connection\r\n  File \"/tmp/ansible_community.general.nmcli_payload_IUFCxF/ansible_community.general.nmcli_payload.zip/ansible_collections/community/general/plugins/modules/nmcli.py\", line 680, in execute_command\r\n  File \"/tmp/ansible_community.general.nmcli_payload_IUFCxF/ansible_community.general.nmcli_payload.zip/ansible/module_utils/basic.py\", line 2506, in run_command\r\n  File \"/usr/lib64/python2.7/posixpath.py\", line 293, in expandvars\r\n    if '$' not in path:\r\nTypeError: argument of type 'int' is not iterable\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

```

The command args passed to `ansible.module_utils.basic.AnsibleModule.run_command`:

```python
['/bin/nmcli', 'con', 'mod', 'br-mgmt', 'ipv4.gateway', '', 'bridge.ageing-time', 300, 'ipv6.address', '', 'bridge.forward-delay', 15, 'autoconnect', 'yes', 'bridge.stp', 'yes', 'ipv6.gateway', '', 'bridge.hello-time', 2, 'bridge.priority', 128, 'ipv4.address', '', 'bridge.max-age', 20]
```
