### ISSUE TITLE
Add ability in nmcli module to bind vlan interface to a bridge interface.

### ISSUE THREAD

**Issue by learnitall** [ansible-collections/community.general#473]
##### SUMMARY

In the `nmcli` module, add a `master` and `slave-type` parameter for vlan interface types to allow them to be enslaved onto bridge interfaces.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nmcli

##### ADDITIONAL INFORMATION

I'm currently trying to setup a bunch of different network interfaces for an Openstack deployment in my home lab. Per the [Openstack documentation](https://docs.openstack.org/openstack-ansible/latest/user/network-arch/example.html#single-interface-or-bond), I'm need to create three bridge interfaces that are all on separate vlans. I'm trying to use the `nmcli` module to do this, however it seems currently impossible given the list of possible options in the [documentation](https://docs.ansible.com/ansible/latest/modules/nmcli_module.html). 

From what I can see based on [this snippet](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-vlan_on_bond_and_bridge_using_the_networkmanager_command_line_tool_nmcli) of RedHat documentation, what I'd like is for the following playbook:

```yaml
-name: Add br-mgmt interface
  nmcli:
    state: present
    conn_name: br-mgmt
    ifname: br-mgmt
    type: bridge
- name: Create vlan 100 interface and bind to br-mgmt
  nmcli:
    state: present
    conn_name: em1.100
    ifname: em1.100
    type: vlan
    vlanid: 100
    vlandev: em1
    master: br-mgmt
    slave-type: bridge
```

To execute something like the following:

```
nmcli connection add type bridge con-name br-mgmt ifname br-mgmt
nmcli connection add type vlan con-name em1.100 ifname em1.100 dev em1 id 100 master br-mgmt slave-type bridge
```

It's the functionality of appending the `master br-mgmt slave-type bridge` to the command that would need to be implemented in the `nmcli` module.
