### ISSUE TITLE
community.general.newrelic_deployment is broken

### ISSUE THREAD

**Issue by matiasba** [ansible-collections/community.general#4758]
### Summary

The module is using a NewRelic endpoint that is no longer available
` # Send the data to NewRelic
    url = "https://rpm.newrelic.com/deployments.xml"
    data = urlencode(params)
    headers = {
        'x-api-key': module.params["token"],
    }`

It should be https://api.newrelic.com/v2/applications/{application_id}/deployments.json
[Here](https://rpm.newrelic.com/api/explore/application_deployments/create) is the documentation 

### Issue Type

Bug Report

### Component Name

community.general.newrelic_deployment

### Ansible Version

```
  ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

### Community.general Version

```
Collection        Version
----------------- -------
community.general 5.0.1
```

### Steps to Reproduce

```
---
- name: Deploy
  hosts: 127.0.0.1
  tasks:
  - name:  Notify newrelic about an app deployment
    community.general.newrelic_deployment:
      token: <insert-token>
      app_name: 'some_app'
      revision: 'v7.11'
```

### Expected Results

I expected the module to work, got a http code 403 instead

### Actual Results

```
FAILED! => {"changed": false, "msg": "unable to update newrelic: HTTP Error 403: Forbidden"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
