### ISSUE TITLE
community.general.ufw rule deletion fails silently when used in a concurrent/parallel way

### ISSUE THREAD

**Issue by delahondes** [ansible-collections/community.general#4769]
### Summary

When I try to use community.general.ufw to delete rules, it fails sometimes silently. This happens only when playbooks are launched in parallel typically doing something like:
```bash
for i in $(seq 1 20); do ansible-playbook destroy_vm.yaml --extra-vars "nodename=node$i" & done
```
(in which destroy_vm.yaml will call community.general.ufw at one step)

### Issue Type

Bug Report

### Component Name

ufw

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.5.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory']
INVENTORY_CACHE_ENABLED(/etc/ansible/ansible.cfg) = False
INVENTORY_CACHE_TIMEOUT(/etc/ansible/ansible.cfg) = 3600000
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
name: Update the firewall with node IPv4
  community.general.ufw:
    from_ip: "{{ hostvars[nodename].ipv4 }}"
    rule: allow
    delete: yes
```
Launch in parallel at least 3 times such a task in a playbook and you should see that ufw fails silently to remove the rules

### Expected Results

The firewall rule should be deleted.

### Actual Results

The firewall rule is not deleted.

I am aware that this is a UFW bug, not an ansible bug or this collection fault. However, it affects the behaviour of Ansible and or the collection. I have commented UFW already opened (and closed) bug on that topic: 
https://bugs.launchpad.net/ufw/+bug/1204579

However, this issue can be bypassed using `task-spooler`, a very basic Debian/Ubuntu task spooler which can be installed this way
```bash
apt install task-spooler
```

And the task has to be changed that way:
```yaml
ansible.builtin.script:
   cmd: /usr/bin/tsp /usr/sbin/ufw delete allow from "{{ hostvars[nodename].ipv4 }}"
   become: true
```

This is very efficient with one defect: the rule is not instantly deleted, there can be a little delay. As it is intended in a house cleaning spirit, this did not bother me too much.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
