### ISSUE TITLE
Add support for `nmcli connection import` for VPN config files

### ISSUE THREAD

**Issue by tandy-1000** [ansible-collections/community.general#4790]
### Summary

It would be useful to be able to do the equivalent of
`nmcli connection import type wireguard file "/etc/wireguard/{{device}}.conf"`
without having to use the ansible shell.

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

```yaml
- name: Enable config:
  community.general.nmcli:
    import:
      type: wireguard
      file: "/etc/wireguard/{{device}}.conf"
  become: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
