### ISSUE TITLE
maven_artifact keep_name does not behave as documented

### ISSUE THREAD

**Issue by gz243** [ansible-collections/community.general#4796]
### Summary

Per the `keep_name` [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/maven_artifact_module.html):

> This option only has effect when dest is a directory and version is set to latest or version_by_spec is defined.

However, actual behavior is `keep_name` must be enabled irrespective of the stated conditions in order to include the artifact version as part of the destination filename:

```
        filename = "{artifact_id}{version_part}{classifier}.{extension}".format(
            artifact_id=artifact_id,
            version_part="-{0}".format(version_part) if keep_name else "",
            classifier="-{0}".format(classifier) if classifier else "",
            extension=extension
        )
        dest = posixpath.join(dest, filename)
```
https://github.com/ansible-collections/community.general/blob/e5e485390df1fe242dd6e394b13852e6e7b92c06/plugins/modules/packaging/language/maven_artifact.py#L694

### Issue Type

Bug Report

### Component Name

maven_artifact

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.6]
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Feb 18 2021, 01:25:00) [GCC 7.3.1 20180712 (Red Hat 7.3.1-12)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/local/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Amazon Linux 2 container

### Steps to Reproduce

Using the below sample task, the artifact is downloaded without the `version` as part of the destination filename.

```yaml (paste below)
- name: Download artifact
  local_action:
    module: "maven_artifact"
    repository_url: "{{ repository_url }}"
    validate_certs: "no"
    dest: "tmp/"
    group_id: "my_group"
    artifact_id: "my_artifact_id"
    version: "my_artifact_version"
    classifier: ""
    extension: "jar"
```

### Expected Results

Artifact downloaded using the version as part of the filename when provided without requiring `keep_name` to be enabled.  That is the behavior of older versions of the plugin - https://github.com/ansible/ansible-modules-extras/blob/f216ba8e0616bc8ad8794c22d4b48e1ab18886cf/packaging/language/maven_artifact.py#L402.

### Actual Results

artifact downloaded without the version as part of the filename.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
