### ISSUE TITLE
IdentitiesOnly for ssh_config

### ISSUE THREAD

**Issue by wolf128058** [ansible-collections/community.general#4801]
### Summary

Could you please support the Attribute `IdentitiesOnly`?

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

```yaml (paste below)
- name: Another SSH Host Configuration
  community.general.ssh_config:
    user: "myniceusername"
    host: "dings.bums.com 192.168.42.23"
    hostname: "192.168.42.23"
    identity_file: "~/.ssh/ed25519_irish.pub"
    identities_only: yes
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
