### ISSUE TITLE
Symbolic links missing avoiding to use community.general.redhat_subscription

### ISSUE THREAD

**Issue by feramp** [ansible-collections/community.general#4815]
### Summary

Hi, after sync the new version https://galaxy.ansible.com/download/community-general-5.1.0.tar.gz I figure out missing symbolic links behind it.

Version 4.x

ansible_collections/community/general/plugins/modules
# ls -l redhat_subscription.py
lrwxrwxrwx. 1 awx awx 35 May 3 15:50 redhat_subscription.py -> packaging/os/redhat_subscription.py

Version 5.1.x

ansible_collections/community/general/plugins/modules
# ls -l redhat_subscription.py
ls: cannot access redhat_subscription.py: No such file or directory

This issue avoid I use the collection as follow:

- name: Register with and consume subscriptions matching Red Hat Enterprise Server
   community.general.redhat_subscription:

### Issue Type

Bug Report

### Component Name

community.general.redhat_subscription

### Ansible Version

```console (paste below)
# ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Community.general Version

```console (paste below)
5.10.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL7

### Steps to Reproduce

```yaml (paste below)
 - name: Register and consume subscriptions matching Red Hat Enterprise Server
     community.general.redhat_subscription:
       state: present
       activationkey: "{{ act_key }}"
       org_id: "{{ org }}"
       server_hostname: "{{ server_url }}" 
       rhsm_baseurl: "{{ base_url }}"
       force_register: "{{ force }}"
       consumer_name:  "{{ server_name }}"
```

### Expected Results

Subscribe RHEL to satellite

### Actual Results

```console (paste below)
ERROR! couldn't resolve module/action 'community.general.redhat_subscription'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/opt/ey/ansible-tower/execution_path/bwrap_2167_mtts31q9/awx_2167__oxgrk9p/project/vm_satellite_subscription.yml': line 32, column 6, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
   - name: Register with activationkey RHEL8-VMware-Lab and consume subscriptions matching Red Hat Enterprise Server
     ^ here
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
