### ISSUE TITLE
Puppet: Disable/Enable Agent

### ISSUE THREAD

**Issue by sitzmoebelchronograph** [ansible-collections/community.general#4843]
### Summary

When using Ansible and Puppet in conjunction, it is possible for one to "step on" the other.

To avoid Puppet interfering with a running Ansible playbook, it would be helpful if there was support for specifically running:

```
puppet agent --disable "Doing Blah"
```

and, when done, run:

```
puppet agent --enable
```

It'd be "nice to have" for this to be part of the puppet module, rather than using raw commands, as it can be idempotent.

### Issue Type

Feature Idea

### Component Name

puppet

### Additional Information

I'd see this working in a playbook something like this:

```
- name: Disable Puppet
  puppet:
    enabled: no
    message: Doing Blah
- name: Upgrade Stuff
  yum: '....'
- name: Enable Puppet
  puppet:
    enabled: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
