### ISSUE TITLE
community.general.make: Support multiple targets

### ISSUE THREAD

**Issue by eszense** [ansible-collections/community.general#4919]
### Summary

It would be useful to allow multiple makefile targets to be specified in community.general.make.

### Issue Type

Feature Idea

### Component Name

community.general.make

### Additional Information

Example Test playbook
```yaml (paste below)
---
- community.general.make:
    target:
      - target1
      - target2
```

Example Test Makefile
```
target1:
        echo target1
target2:
        echo target2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
