### ISSUE TITLE
nmcli: Unable to configure the network interface

### ISSUE THREAD

**Issue by Udayendu** [ansible-collections/community.general#4928]
### Summary

nmcli is not configuring the interface and saying **"Connections already exist and no changes made"**.

### Issue Type

Bug Report

### Component Name

- nmcli

### Ansible Version

```
$ pip3 show ansible
Name: ansible
Version: 6.0.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: ansible-core
Required-by:
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```
$ ansible-galaxy collection list community.general
# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.0.2
```

### OS / Environment

- rhel7
- rhel8

### Steps to Reproduce

Deploy a vm from ovf template which is available in the content library using the following play and then configure the network:

```
- name: Deploy Virtual Machine from template in content library
  vmware_content_deploy_template:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    template: '{{ vmware_rhel8_temp }}'
    library: '{{ vmware_Content_library }}'
    cluster: '{{ vsphere_cluster }}'
    datastore: '{{ vsphere_datastore }}'
    datacenter: '{{ vsphere_datacenter }}'
    folder: '{{ vsphere_folder }}'
    resource_pool: '{{ resource_pool }}'
    name: '{{ inventory_hostname }}'
    validate_certs: 'no'
    state: present
  delegate_to: localhost

- name: Configure Network Interface '{{ vmware_vm_ifname }}'
  nmcli:
    conn_name: "{{ vmware_vm_ifname }}"
    ifname: "{{ vmware_vm_ifname }}"
    type: ethernet
    ip4: "{{ Mgmt_network_ipv4 }}"
    gw4: "{{ Mgmt_network_gwv4 }}"
    dns4:
      - "{{ dns_server1 }}"
    state: present
```

### Expected Results

- Network configuration should work using nmcli

### Actual Results

- Network configuration is not working using nmcli.
- Template is fine because when doing the deployment using `vmware_guest` module, its working perfectly.

There is a requirement to use the content library and hence exploring the network configuration using `nmcli` which is not working.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
