### ISSUE TITLE
community.general.crypttab doesn't handle second equal sign in header correctly

### ISSUE THREAD

**Issue by mcexit** [ansible-collections/community.general#4963]
### Summary

community.general.crypttab module doesn't handle second equal sign in header correctly when using detached LUKS header. The format is `header=/header.img:UUID=0000-0000`

### Issue Type

Bug Report

### Component Name

crypttab

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.13.2]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/.ansible/inventory', '/etc/ansible/hosts']
```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml (paste below)
- name: Setting device
  community.general.crypttab:
    backing_device: PARTUUID=00000000-0000-0000-0000-000000000000
    name: crypt
    opts: "header=/header.img:UUID=0000-0000,password-echo=no,x-initrd.attach"
    path: /etc/crypttab.initramfs
    state: present
```

### Expected Results

```
cryptroot PARTUUID=00000000-0000-0000-0000-000000000000 none header=/root-header.img:UUID=0000-0000,password-echo=no,x-initrd.attach
```

### Actual Results

```
cryptroot PARTUUID=00000000-0000-0000-0000-000000000000 none header=/root-header.img,password-echo=no,x-initrd.attach
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
