### ISSUE TITLE
Fix wrong url path in plugins/modules/web_infrastructure/jenkins_plugin.py

### ISSUE THREAD

**Issue by pavelp77** [ansible-collections/community.general#4972]
### Summary

When we use option from community.general.jenkins_plugin module to verify installed plugins. We received error like below:

`failed: [localhost] (item={'key': 'http_request', 'value': '1.15'}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "details": "HTTP Error 404: Not Found", "item": {"key": "http_request", "value": "1.15"}, "msg": "Plugin not found. http://localhost:8080/pluginManager/plugin/http_request/pin"}`

There is wrong url path "pluginManager/plugin" **Which need to be modified to** "pluginManager/plugins"
Follow link below:
https://github.com/ansible-collections/community.general/blob/788cfb624aa7e694b533b5d2722aab0ff4522ce6/plugins/modules/web_infrastructure/jenkins_plugin.py#L774

### Issue Type

Bug Report

### Component Name

plugins/modules/web_infrastructure/jenkins_plugin.py

### Ansible Version

```console (paste below)
sh-4.2$ ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.10 (default, Jun  3 2021, 00:02:01) [GCC 7.3.1
20180712 (Red Hat 7.3.1-13)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ssm-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  ansible collection location = /home/ssm-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.7.10 (default, Jun  3 2021, 00:02:01) [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/local/lib/python3.7/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.3

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
#Simple http request on Jenkins controller

sh-4.2$ curl http://localhost:8080/pluginManager/plugin
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/pluginManager/plugin</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>

</body>
</html>


#Task from Ansible playbook:
- name: Running through and installing specified plugins
  jenkins_plugin:
    name: '{{ item.key }}'
    version: '{{ item.value }}'
    jenkins_home: '{{ jenkins_home_dir }}'
    url_username: 'admin'
    url_password: '{{ jenkins_administrator_password }}'
    state: pinned
    timeout: 120
    url: 'http://{{ jenkins_fqdn }}:{{ jenkins_http_port }}'
  with_dict: 
    - "{{ jenkins_install_plugins| items2dict(key_name='name', value_name='version') }}"
  notify: Restart Jenkins service
  register: plugin_install_result
  until: plugin_install_result is success
  retries: 3
  delay: 10




```

### Expected Results

h-4.2$ curl http://localhost:8080/pluginManager/plugins | jq '.data[]|select(.name == "http_request")'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  906k  100  906k    0     0  3543k      0 --:--:-- --:--:-- --:--:-- 3567k
{
  "installed": false,
  "name": "http_request",
  "title": "HTTP Request",
  "excerpt": "This plugin sends a http request to an url with some parameters",
  "site": "default",
  "dependencies": {
    "javax-mail-api": "1.6.2-5",
    "workflow-durable-task-step": "2.40",
    "apache-httpcomponents-client-4-api": "4.5.13-1.0",
    "credentials": "2.6.1",
    "javax-activation-api": "1.2.0-2",
    "script-security": "1.78",
    "sshd": "3.0.1",
    "workflow-basic-steps": "2.22"
  },
  "website": "https://plugins.jenkins.io/http_request"
}

### Actual Results

```console (paste below)
sh-4.2$ curl http://localhost:8080/pluginManager/plugin | jq '.data[]|select(.name == "http_request")'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   464  100   464    0     0  11397      0 --:--:-- --:--:-- --:--:-- 11600
parse error: Invalid numeric literal at line 2, column 0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
