### ISSUE TITLE
pam_limits does not work by using version 4.8.3 on Ubuntu 20.04/Ansible 2.12.7

### ISSUE THREAD

**Issue by cyberaa** [ansible-collections/community.general#4997]
### Summary

When I try to configure security limits via `community.general.pam_limits module`, the file is created as empty and no limits are defined.

### Issue Type

Bug Report

### Component Name

community.general.pam_limits module

### Ansible Version

```console (paste below)
ansible [core 2.12.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Community.general Version

```console (paste below)
ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.3  
```

### Configuration

```console (paste below)
xxx@xxx: ansible-config dump --only-changed
xxx@xxx: 
```

**Configuration used:**
```
- name: Configure pam_limits
  community.general.pam_limits:
    domain: '*'
    dest: '/etc/security/limits.d/test.conf'
    limit_type: hard
    limit_item: fsize
    value: 1000000
    use_max: yes
```

### OS / Environment
```bash
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### Steps to Reproduce

1. Install ansible or community.general collection via `galaxy collection install`
2. Add task to configure pam limits:

```yaml
- name: Configure pam_limits
  community.general.pam_limits:
    domain: '*'
    dest: '/etc/security/limits.d/test.conf'
    limit_type: hard
    limit_item: fsize
    value: 1000000
    use_max: yes
```
3. Run ansible-playbook on a given host with same specs.

### Expected Results

I expect `/etc/security/limits.d/test.conf` to have limits configured inside like `* hard fsize 1000000`.

### Actual Results

```console (paste below)
xxx@xxx/etc/security/limits.d$ cat test.conf 
xxx@ixxx:/etc/security/limits.d$ ls -lah
total 8.0K
drwxr-xr-x 2 root root 4.0K Jul 25 11:11 .
drwxr-xr-x 4 root root 4.0K Jun 10 10:45 ..
-rw-r--r-- 1 root root    0 Jul 25 11:11 test.conf
```
Limits `test.conf` file is created but is empty and no configurations are found inside.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
