### ISSUE TITLE
parted fails when partition is in use (no live resize)

### ISSUE THREAD

**Issue by agowa338** [ansible-collections/community.general#5015]
### Summary

The community.general.parted fails if the specified partition is already mounted.
Even if no changes need to be performed.
This also makes live resizes impossible.

### Issue Type

Bug Report

### Component Name

community.general.parted

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.2]
  config file = /workspaces/ansible.cfg
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /workspaces/.venv/ansible.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /workspaces/collections
  executable location = /workspaces/.venv/ansible.venv/bin/ansible
  python version = 3.10.4 (main, Jul 27 2022, 08:41:51) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /workspaces/.venv/ansible.venv/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.3.0  

# /workspaces/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.4.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/workspaces/ansible.cfg) = ['/workspaces/collections']
DEFAULT_BECOME(/workspaces/ansible.cfg) = True
DEFAULT_BECOME_FLAGS(/workspaces/ansible.cfg) = -l
DEFAULT_BECOME_METHOD(/workspaces/ansible.cfg) = su
DEFAULT_FORCE_HANDLERS(/workspaces/ansible.cfg) = True
DEFAULT_FORKS(/workspaces/ansible.cfg) = 50
DEFAULT_HOST_LIST(/workspaces/ansible.cfg) = ['/workspaces/inventory.ini']
DEFAULT_MANAGED_STR(/workspaces/ansible.cfg) = This file is managed by ansible - local changes will be lost
DEFAULT_REMOTE_USER(/workspaces/ansible.cfg) = root
DEFAULT_TRANSPORT(/workspaces/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/workspaces/ansible.cfg) = /workspaces/.vpass
DEPRECATION_WARNINGS(/workspaces/ansible.cfg) = True
SYSTEM_WARNINGS(/workspaces/ansible.cfg) = True
```

### OS / Environment

running within venv and target OS is Debian

### Steps to Reproduce

Run this playbook twice and have a unpartitioned /dev/sdb beforehand:

```yaml
- name: Partition data drive
  community.general.parted:
    device: "/dev/sdb"
    number: 1
    state: present
    fs_type: btrfs
    label: gpt
    resize: yes
- name: Format data partition
  community.general.filesystem:
    fstype: btrfs
    dev: "/dev/sdb"
    resizefs: yes
- name: Mount data partition
  ansible.posix.mount:
    fstype: btrfs
    src: "/dev/sdb"
    path: "/mnt/disk1"
    state: mounted
```

### Expected Results

I expect:

A) The module to complete without error and report unchanged when no changes need to be done.
B) Do a live resize of the partition as long as it is possible without dataloss and report changed.
C) If data loss would occur return with error unless `force: yes` is also specified.

### Actual Results

```console (paste below)
TASK [test : Partition data drive] ************************************************************************************************************************************************************
failed: [vm001] (item=/dev/sdb) => {"ansible_loop_var": "item", "changed": false, "err": "Error: Partition(s) on /dev/sdb are being used.\n", "item": "/dev/sdb", "msg": "Error while running parted script: /usr/sbin/parted -s -m -a optimal /dev/sdb -- unit KiB mklabel gpt mkpart primary btrfs 0% 100%", "out": "", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
