### ISSUE TITLE
Terraform Azure backend configuration fails when client_secret contains special characters

### ISSUE THREAD

**Issue by ppodgorsek** [ansible-collections/community.general#5016]
### Summary

I recently had to change the client secret of my Azure service principal. If the new password contains `~` then Terraform cannot connect to the remote backend configuration.
It is however fine with other characters matching this pattern: `[a-zA-Z0-9.]+` (I didn't try with other characters.

### Issue Type

Bug Report

### Component Name

Terraform

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ppodgorsek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ppodgorsek/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ppodgorsek/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.3  

# /home/ppodgorsek/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.2.0  

# /home/ppodgorsek/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Fedora 36

### Steps to Reproduce

The Ansible task is declared as follows:

```yaml (paste below)
- name: Provision the infrastructure
  community.general.terraform:
    project_path: "{{ role_path }}/templates/terraform/"
    force_init: true
    backend_config:
      resource_group_name: "{{ resource_group }}"
      storage_account_name: "{{ storage_account }}"
      container_name: "{{ storage_container_terraform }}"
      key: "terraform.tfstate"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_secret }}"
      subscription_id: "{{ azure_subscription_id }}"
      tenant_id: "{{ azure_tenant }}"
    workspace: "{{ terraform_workspace }}"
```

The variables are defined in the inventory:
```
---
resource_group: MY_RG
storage_account: MY_STORAGE_ACCOUNT
storage_container_terraform: MY_CONTAINER
azure_client_id: MY_CLIENT_ID
azure_secret: "MY~CLIENT.SECRET"
azure_subscription_id: MY_SUBSCRIPTION_ID
azure_tenant: MY_TENANT_ID
terraform_workspace: MY_WORKSPACE
```

### Expected Results

Terraform should be able to connect to the remote backend in Azure. (similarly to how it worked when there was no `~` like in my previous password)

### Actual Results

The verbose logs show the following malformed command line:
```console (paste below)
    "cmd": "/usr/bin/terraform init -input=false -backend-config resource_group_name=MY_RG -backend-config storage_account_name=MY_STORAGE_ACCOUNT -backend-config container_name=MY_CONTAINER -backend-config key=terraform.tfstate -backend-config client_id=MY_CLIENT_ID -backend-config ''\"'\"'client_secret=MY~CLIENT\\.SECRET'\"'\"'' -backend-config subscription_id=MY_SUBSCRIPTION_ID -backend-config tenant_id=MY_TENANT_ID"
```

Followed by this error message:
```console
    "stderr_lines": [
        "\u001b[31m\u001b[31m╷\u001b[0m\u001b[0m",
        "\u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mInvalid backend configuration argument\u001b[0m",
        "\u001b[31m│\u001b[0m \u001b[0m",
        "\u001b[31m│\u001b[0m \u001b[0m\u001b[0mThe backend configuration argument \"'client_secret\" given on the command",
        "\u001b[31m│\u001b[0m \u001b[0mline is not expected for the selected backend type.",
        "\u001b[31m╵\u001b[0m\u001b[0m",
        "\u001b[0m\u001b[0m"
    ],
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
