### ISSUE TITLE
[Feature] Get specific/custom release of a public repository github

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/community.general#5032]
### Summary

Hello! Thanks for community.general.github_release module.
Proposal: Get specific/custom release of a public repository github

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

```yaml (paste below)
- name: Get latest release of a public repository
  community.general.github_release:
    user: jenkinsci
    repo: plugin-installation-manager-tool
    version: 2.12.8
```

and download https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.8/jenkins-plugin-manager-2.12.8.jar

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
