### ISSUE TITLE
pipx: Add `latest` option to the `state` parameter to keep packages up to date

### ISSUE THREAD

**Issue by trallnag** [ansible-collections/community.general#5039]
### Summary

Currently the [community.general.pipx module](https://docs.ansible.com/ansible/devel/collections/community/general/pipx_module.html) does not support a `latest` option for the `state` parameter.

Such an option would be a good addition to the module to make it easier to keep packages up to date.

The supported `upgrade` option is similar, but differs from `latest` by erroring out when the given package is not installed at all.

A workaround exists: First use the pipx module with the `present` state option, then another task with the `upgrade` state option.

### Issue Type

Feature Idea

### Component Name

pipx

### Additional Information

This should work just like the apt module works:

```yaml
- name: Install with Pipx
  community.general.pipx:
    name: pre-commit
    state: latest
```

Current workaround:

```yaml
- name: Install with Pipx
  community.general.pipx:
    name: pre-commit
    state: present

- name: Install with Pipx
  community.general.pipx:
    name: pre-commit
    state: upgrade
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
