### ISSUE TITLE
Add a module for managing Keycloak Users

### ISSUE THREAD

**Issue by drpdishant** [ansible-collections/community.general#5089]
### Summary

The user management module formodule is missing, it would be a good feature to have. Following modules can be added for users:
- keycloak_user_info (To fetch details of  one or all users in a realm)
- keycloak_user (to create, change,delete a user in a realm)

### Issue Type

Feature Idea

### Component Name

keycloak

### Additional Information

Example:
```yaml
- name: Get all users in a realm
  community.general.keycloak_user_info:
    realm: MyCustomRealm
    auth_keycloak_url: https://auth.example.com/auth
  delegate_to: localhost

- name: Get a Keycloak User Info by User Id
  community.general.keycloak_user_info:
    realm: MyCustomRealm
    userid: "677a27df-02e8-48e9-8f90-fa95caf64bd7" #UUID of the User
    auth_keycloak_url: https://auth.example.com/auth
  delegate_to: localhost

- name: Get a Keycloak User Info by User Name
  community.general.keycloak_user_info:
    realm: MyCustomRealm
    username: "user@example.com"
    auth_keycloak_url: https://auth.example.com/auth
  delegate_to: localhost
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
