### ISSUE TITLE
parted does not respect "number" when creating partition

### ISSUE THREAD

**Issue by olastor** [ansible-collections/community.general#5090]
### Summary

I try to create a partition with a custom number and it does not assign it, but also shows no errors.

### Issue Type

Bug Report

### Component Name

parted module

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.7]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 5.4.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
nothing
```

### OS / Environment

Running on Fedora 34, target OS Ubuntu 20.04 on KVM.

### Steps to Reproduce

```yaml (paste below)
- name: create new part
  parted:
    device: "/dev/vda"
    label: gpt
    fs_type: ext4
    number: 6
    state: present
    part_start: '{{ (root_part_devinfo["start"] | int) + (root_part_devinfo["sectors"] | int) + 2 }}s'
    part_end: '60%'
```

### Expected Results

I expected the new partition to have the number 6.

### Actual Results

The new partition had the number 3.

```console (paste below)
Number  Start   End     Size    File system  Name     Flags
14      1049kB  5243kB  4194kB                        bios_grub
15      5243kB  116MB   111MB   fat32                 boot, esp
 1      116MB   2361MB  2245MB  ext4
 3      2361MB  6442MB  4081MB               primary <--- THIS ONE WAS CREATED
 2      9664MB  10.7GB  1073MB               primary
```

I tested many times and I don't get the module to set the number I specified. It just seems to always choose the next one available (e.g., 1, 2 already taken, it picks 3).

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
