### ISSUE TITLE
redfish_command: UEFI one time boot is set but module errors with HTTP 400 on Dell 13th gen

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/community.general#5091]
### Summary

Working with Dell 13th gen servers such as R730, the `redfish_command` module cannot set one time boot setting correctly in UEFI mode. In BIOS mode everything works fine but in UEFI mode there are 2 issues:
1. The module always fails with HTTP error 400: `Unable to set the attribute value because it depends on other attribute(s).` but the one time boot setting *is* indeed set, the "Next Boot" setting in iDRAC console is indeed changed and the server does follow the commanded one time boot on the next server boot.
2. Setting one time boot seems to be run as a BIOS Configuration Job in the Lifecycle Controller, contrary to BIOS mode where the change does not cause a BIOS Configuration Job to run. I do not know if this is fixable or if it is a "feature" of the UEFI mode on these Dells. When setting one time boot in BIOS mode the console will just show on the next boot boot for example `IPMI: PXE boot requested` and continue to boot from PXE; in UEFI mode the boot will show `Lifecycle Controller: System Configuration Requested` and will continue to run a BIOS Configuration job similarly to changing any BIOS setting and then after completion of the configuration job it will reboot once again and display `IPMI: Boot to configured UEFI device path`. This is much slower.

Additionally, the example in documentation for module `redfish_command` using UEFI one time boot is not very clear, currently having parameter:
```yaml
    uefi_target: "/0x31/0x33/0x01/0x01"
```
Where does this hex string come from? What does it mean?

### Issue Type

Bug Report

### Component Name

redfish_command

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/x/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.0.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
I do not think this is relevant.
```

### OS / Environment

EL7, Dell R730xd BIOS 2.13.0, Dell Lifecycle Controller 2.81.81.81

### Steps to Reproduce

```yaml (paste below)
- name: Configure one time boot
  community.general.redfish_command:
    baseuri: "{{ redfish_uri }}"
    category: Systems
    command: SetOneTimeBoot
    bootdevice: UefiTarget
    uefi_target: MAC(010203040506)
    username: "{{ redfish_user }}"
    password: "{{ redfish_password }}"
    timeout: "{{ redfish_timeout }}"
  become: false
  delegate_to: localhost
```

### Expected Results

The module should not error, especially if the boot setting is set correctly in the system.

### Actual Results

```console (paste below)
fatal: [host.example.com -> localhost]: FAILED! => changed=false
  msg: 'HTTP Error 400 on PATCH request to ''https://192.0.2.1/redfish/v1/Systems/System.Embedded.1'', extended message: ''Unable to set the attribute value because it depends on other attribute(s).'''
```

It does not matter if `boot_override_mode` is included (set to `UEFI`) or not included.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/remote_management/redfish/redfish_command.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/remote_management/redfish/redfish_command.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bhavya06 @mraineri @rajeevkallur @renxulei @tomasg2012 @xmadsen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bluikko** [comment]
Since in iDRAC a "PXE" boot can be requested the same way in both BIOS/UEFI modes, for example in iDRAC console `Next Boot` -> `PXE`, I tested to use the same task for commanding PXE boot that I use in BIOS mode:
```yaml
- name: Configure one time boot
  community.general.redfish_command:
    baseuri: "{{ redfish_uri }}"
    category: Systems
    command: SetOneTimeBoot
    bootdevice: PXE
    username: "{{ redfish_user }}"
    password: "{{ redfish_password }}"
    timeout: "{{ redfish_timeout }}"
  become: false
  delegate_to: localhost
```

Earlier when I tested this task on a server set to UEFI boot the server booted to Lifecycle Controller where user can do various management tasks - it did not boot to PXE. But now when I tested it again it did correctly do a PXE boot...

So it seems the problem is happening only with `bootdevice: UefiTarget` which I do not seem to then need in the end and will just use a `bootdevice: PXE` same as in BIOS mode.  
But anyways it looks like something is wrong with `bootdevice: UefiTarget` with the 400 HTTP error.
