### ISSUE TITLE
Logstash Plugin Offline Install

### ISSUE THREAD

**Issue by kclinden** [ansible-collections/community.general#5128]
### Summary

There might be a situation where a logstash plugin needs to be installed offline and it cannot reach out to download the plugin and its gems from the internet.

For example `/usr/share/logstash/bin/logstash-plugin install --local --no-verify file:///root/logstash-output-opensearch.zip`

### Issue Type

Feature Idea

### Component Name

logstash_plugin

### Additional Information

```yaml (paste below)
- name: Install specific version of a plugin
  community.general.logstash_plugin:
    state: present
    name: logstash-input-syslog
    local: true
    patch: /root/logstash-output-opensearch.zip
    verify: false
    version: '3.2.0'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
