### ISSUE TITLE
yaml callback plugin doesn't support ANSI colors

### ISSUE THREAD

**Issue by shinebayar-g** [ansible-collections/community.general#5146]
### Summary

Yaml callback plugin doesn't support ANSI colors from command outputs. For example following task prints colored output.

```yml
- name: Test Ansi Colors
  hosts: all
  strategy: linear
  gather_facts: no
  tasks:
    - name: Test Ansi Colors
      shell: printf "\e[31mHello World\e[0m\n"
      changed_when: false
```
`ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook -v plays/test.yml`

![image](https://user-images.githubusercontent.com/3091558/186046360-27589b88-2020-4aa8-a9c4-a46425cc2bf0.png)

---
while other callback plugins support colored output.

`ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -v plays/test.yml`

![image](https://user-images.githubusercontent.com/3091558/186046263-48014b27-d019-4301-acb6-bfadbeac8076.png)

`ANSIBLE_STDOUT_CALLBACK=minimal ansible-playbook -v plays/test.yml`

![image](https://user-images.githubusercontent.com/3091558/186046505-d0bec2b3-fdfd-43e3-a9cc-5aa46fc3c4e7.png)

### Issue Type

Bug Report

### Component Name

yaml callback

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.12]
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 3.8.3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 7.9

### Steps to Reproduce

```yaml (paste below)
- name: Test Ansi Colors
  hosts: all
  strategy: linear
  gather_facts: no
  tasks:
    - name: Test Ansi Colors
      shell: printf "\e[31mHello World\e[0m\n"
      changed_when: false

```

`ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook -v plays/test.yml`

### Expected Results

Expected task outputs printed in colored format just like other plugins.

### Actual Results

`ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook -v plays/test.yml`

![image](https://user-images.githubusercontent.com/3091558/186046360-27589b88-2020-4aa8-a9c4-a46425cc2bf0.png)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
