### ISSUE TITLE
Scaleway inventory plugin generates Warning regarding invalid characters found in group name

### ISSUE THREAD

**Issue by hleroy** [ansible-collections/community.general#5162]
### Summary

When using the scaleway inventory plugin, a WARNING message is shown:

Not replacing invalid character(s) "{'-'}" in group name (fr-par-2)
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Parsed scaleway_inventory.yml inventory source with auto plugin

### Issue Type

Bug Report

### Component Name

community.general/plugins/inventory/scaleway.py

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.8
  config file = ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6
```

### OS / Environment

Ubuntu 22.04.1 LTS

### Steps to Reproduce

```yaml (paste below)
plugin: scaleway
oauth_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          xxxxxxxxxx
hostnames:
  - hostname
regions:
  - par1
  - par2
variables:
  ansible_host: public_ip.address
```

### Expected Results

I expect no warning.

### Actual Results

```console (paste below)
$ ansible-inventory --list -i inventories/scaleway_inventory.yml
(...)
Not replacing invalid character(s) "{'-'}" in group name (fr-par-2)
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Parsed scaleway_inventory.yml inventory source with auto plugin
(...)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
