### ISSUE TITLE
cloudflare_dns: unable to add SRV records using example from docs

### ISSUE THREAD

**Issue by martin-schlossarek** [ansible-collections/community.general#5167]
### Summary

I'm unable to add SRV records using the example from the official documentation: 

```yaml
- name: Create an SRV record _foo._tcp.example.net
  community.general.cloudflare_dns:
    domain: example.net
    service: foo
    proto: tcp
    port: 3500
    priority: 10
    weight: 20
    type: SRV
    value: fooserver.example.net
```

This will result in an api error:

```
failed: [localhost] (item={...}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "account_api_key": null,
            "account_email": null,
            "algorithm": null,
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cert_usage": null,
            "hash_type": null,
            "key_tag": null,
            "port": 3500,
            "priority": 10
            "proto": "tcp",
            "proxied": false,
            "record": "@",
            "selector": null,
            "service": "foo",
            "solo": null,
            "state": "present",
            "timeout": 30,
            "ttl": 1,
            "type": "SRV",
            "value": "fooserver.example.net",
            "weight": 20,
            "zone": "example.net"
        }
    },
    "item": {
        ...
    },
    "msg": "API bad request; Status: 400; Method: POST: Call: /zones/$somehash/dns_records; Error details: code: 1004, error: DNS Validation Error; code: 9000, error: DNS name is invalid.; "
} 
```      

After digging a little bit in the code I noticed that the `name` item requires the `record` item to be set (which is not documented): https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/cloudflare_dns.py#L690

~In order to get this to work you have to modify the yaml to:~

```yaml
- name: Create an SRV record _foo._tcp.example.net
  community.general.cloudflare_dns:
    domain: example.net
    service: foo
    proto: tcp
    port: 3500
    priority: 10
    weight: 20
    type: SRV
    value: fooserver.example.net
    record: _foo._tcp  # required!
```

~Either the `record` item should be generated automatically or setting `proto` and `service` is useless.~

EDIT: Does also not work. This will create  an "_foo._tcp._foo._tcp.example.net" entry

### Issue Type

Bug Report

### Component Name

cloudflare_dns

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.1

# /home/user/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Fedora 36

### Steps to Reproduce

```yaml (paste below)
- name: Create an SRV record _foo._tcp.example.net
  community.general.cloudflare_dns:
    domain: example.net
    service: foo
    proto: tcp
    port: 3500
    priority: 10
    weight: 20
    type: SRV
    value: fooserver.example.net
```

### Expected Results

domain entries should be added

### Actual Results

api error

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/net_tools/cloudflare_dns.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/cloudflare_dns.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @mgruener
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by martin-schlossarek** [comment]
After fiddling aroung with the raw cloudflare api I think I found the problem.

In [line 404](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/cloudflare_dns.py#L404) `record` is set to `zone` if no custom `record` was set. 
```python
        if self.record == '@':
            self.record = self.zone
```
In [line 690](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/net_tools/cloudflare_dns.py#L404) `record` is spliced to a zero length string (if no custom `record` was given)
```python
	                "name": params['record'][:-len('.' + params['zone'])],
```

This results in an empty name and throws errors at the cloudflare api. 

In order to get this to work you have to specify a `record` like this:
  - `@.example.net` or `example.net.example.net` for the root domain
  - `subdomain.example.net` for subdomains

Is this really intended? All other record types (a, aaaa, cname, ...) expect `record` to be the shortname of the subdomain or `@`

**Comment by martin-schlossarek** [comment]
The easiest fix would be to simply remove the splicing of `record`. 

```diff
@@ -7,7 +7,7 @@
                 "port": params['port'],
                 "weight": params['weight'],
                 "priority": params['priority'],
-                "name": params['record'][:-len('.' + params['zone'])],
+                "name": params['record'],
                 "proto": params['proto'],
                 "service": params['service']
             }
```

**Comment by felixfontein** [comment]
> The easiest fix would be to simply remove the splicing of `record`.

But isn't that breaking the module for everyone who creates a SRV entry for a proper subdomain?

How about to simply replace `params['record'][:-len('.' + params['zone'])]` by `params['record'][:-len('.' + params['zone'])] or '@'` to make sure that if the result is empty, `@` is used?

**Comment by martin-schlossarek** [comment]
Why?  Just use the subdomain as `record ` like in a,  a, cname ... entries:

```yaml 
- name: Create SRV records
  community.general.cloudflare_dns:
    zone: "mydomain.tld"
    record: "subdomain"
    type: SRV
    proto: "tcp"
    service: "mysrv"
    value: "example.com"
    port: 443
    api_token: "{{ cloudflare_api_token }}"
```

This works with my modified code:

![image](https://user-images.githubusercontent.com/33715215/187031122-0a3d0ffc-248c-47d8-a1d5-7985c8b7e6ee.png)
