### ISSUE TITLE
Creation of qemu VM failed with exception='agent'

### ISSUE THREAD

**Issue by humberto-garza** [ansible-collections/community.general#5181]
### Summary

After updating community.general to the latest version 5.5.0 (which was released yesterday as of 8/24/2022), we started getting this error when creating a VM via the proxmox_kvm module:
```sh
# FAILED! => changed=false
#   msg: creation of qemu VM dev-test with vmid 100 failed with exception='agent'
#   vmid: 100
```

It looks like it may have been introduced here:
[Change Proxmox agent argument to string. #5107](https://github.com/ansible-collections/community.general/pull/5107)

# Workaround
Lock to 5.4.0:
```yaml
- name: community.general
  version: 5.5.0
```

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/plugins/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.5.0

# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.5.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/callback', '/root/.ansible/plugins/callback', '/usr/share/ansible/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/filter', '/root/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/module_utils', '/root/.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_VAULT_IDENTITY_LIST(env: ANSIBLE_VAULT_IDENTITY_LIST) = ['@.key', 'mac_sign@mac_signing.key']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /etc/ansible/.key
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Running on a Docker Container

### Steps to Reproduce

Playbook to reproduce
```yaml
---
- hosts: <REDACTED>
  gather_facts: no
  tasks:
    - name: Create VM
      community.general.proxmox_kvm:
        api_user    : "{{ proxmox_vm_target_node_user }}@pam"
        api_password: "{{ proxmox_vm_target_node_password }}"
        api_host    : localhost
        name        : dev-test
        node        : "{{ proxmox_vm_target_node_short }}"
        vmid        : 100
      delegate_to: "{{ proxmox_vm_target_node }}"
```

### Expected Results

```sh
TASK [Create VM] 
task path: /etc/ansible/runner/tests/playbooks/playbook.yml:7
changed: [ <REDACTED> ] => changed=true
  devices: {}
  mac: {}
  msg: VM dev-test with vmid 100 deployed
  vmid: 100
```

### Actual Results

```console (paste below)
TASK [Create VM] *******************************task path: /etc/ansible/runner/tests/playbooks/playbook.yml:7
fatal: [ <REDACTED> ]: FAILED! => changed=false
  msg: creation of qemu VM dev-test with vmid 100 failed with exception='agent'
  vmid: 100
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
