### ISSUE TITLE
community.general.xml: change attribute only if xpath selection exists

### ISSUE THREAD

**Issue by gevezex** [ansible-collections/community.general#5200]
### Summary

I am trying to change an attribute, only if the xpath exists. This works as designed if the xpath has a match.
But if there is no xpath match then it creates also the element, what is not desired in my case. How can I change this default behaviour.

```
- name: Replace logstash hosts with xpath
      community.general.xml:
        path: /tmp/ansible/admin-log4j.xml
        xpath: /Configuration/Appenders/Socket[@remoteEnd='clv']
        attribute: 'host'
        value: '{{ clv_syslog_host }}'
      delegate_to: localhost
      become: no
```

### Issue Type

Documentation Report

### Component Name

xml

### Ansible Version

ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dbxaci0/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dbxaci0/miniconda3/lib/python3.9/site-packages/ansible
  ansible collection location = /home/dbxaci0/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dbxaci0/miniconda3/bin/ansible
  python version = 3.9.12 (main, Apr  5 2022, 06:56:58) [GCC 7.5.0]
  jinja version = 3.1.2
  libyaml = True

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/files/xml.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/files/xml.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
hi @gevezex Thanks for submitting this issue.

I haven't used the `xml` module myself, but taking a look at the docs it seems that:
[option `content`](https://docs.ansible.com/ansible/latest/collections/community/general/xml_module.html#parameter-content)
 will give you the current state of the XML doc. Based on the results of that, you can have your playbook changing the attribute or not.

Keep in mind that Ansible modules are meant to be idempotent, so expressing a desired state will produce that outcome, regardless of the initial state.

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/xml.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/xml.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
This is not a documentation issue — the module behaves as designed. When an XPath expression does not match any existing node and `state: present` (the default), the module creates the element so that the declared state is satisfied. This is intentional idempotent behaviour.

That said, the need to *conditionally* set an attribute only when the element already exists is a valid use case. A workable approach today is to use the `count` parameter in a first task to probe for the element, then gate the second task with `when`:

```yaml
- name: Check if element exists
  community.general.xml:
    path: /tmp/ansible/admin-log4j.xml
    xpath: /Configuration/Appenders/Socket[@remoteEnd='clv']
    count: true
  register: xml_check

- name: Set attribute only if element exists
  community.general.xml:
    path: /tmp/ansible/admin-log4j.xml
    xpath: /Configuration/Appenders/Socket[@remoteEnd='clv']
    attribute: host
    value: "{{ clv_syslog_host }}"
  when: xml_check.count > 0
```

Leaving this open as a feature request, since a dedicated `no_create` (or similar) parameter would make this pattern unnecessary.
