### ISSUE TITLE
parted: unexpected partition table wipe

### ISSUE THREAD

**Issue by ei-grad** [ansible-collections/community.general#522]
##### SUMMARY

If the disk label is unspecified and actual label is different from msdos, then parted module wipes the partition table.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ei-grad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Execute the following task on disk with gpt label:

```yaml
  - name: create partition for lvm on each nvme
    parted:
      device: "/dev/nvme1n1"
      number: 3
      part_start: 197257216s
      part_end: 100%
      state: present
```

##### EXPECTED RESULTS

New partition is created.

##### ACTUAL RESULTS

The partition table is wiped.

```paste below
failed: [myhostname] (item=/dev/nvme1n1) => changed=false 
  ansible_loop_var: item
  err: |-
    Error: Partition(s) 2 on /dev/nvme1n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
  item: /dev/nvme1n1
  msg: 'Error while running parted script: /sbin/parted -s -m -a optimal /dev/nvme1n1 -- unit KiB mklabel msdos mkpart primary 197257216s 100%'

```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/system/parted.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/system/parted.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @ColOfAbRiX @MorrisA @bcoca @d-little @flynn1973 @gforster @kairoaraujo @marvin-sinister @mator @molekuul @ramooncamacho @wtcross
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rosowiecki** [comment]
I'm sorry for loss of your partitions (I hope you didn't lose any important data!)

The parted module always inserts mklabel command when there's no label or current label is different than specified, see https://github.com/ansible-collections/community.general/blob/f16a93f976e0379b4d405f2bd9031d8eb95fa367/plugins/modules/system/parted.py#L615

You didn't specify any label type, but 'msdos' is default value for this parameter -- hence the confusion. Moreover documentation ("Creates a new disk label) may suggest, that module takes action only if there is no partition label and leaves current label when unspecified. 

I suggest documentation change (PR will come soon), something like: 'Disk label type to be created. If device contains different label, any previous partitions will be lost'.

I use parted for GPT partitions exclusively, so I've added the following code:

```yaml
 - name: get partiton info.
   parted:
      device: /dev/{{device_name}}
      unit: "{{part.unit}}"
   register: parted_call
  
 - name: check GPT label
   fail: msg="GPT table required"
   when: parted_call.disk.table not in ['gpt', 'unknown']
```
