### ISSUE TITLE
define custom path to opkg

### ISSUE THREAD

**Issue by CWempe** [ansible-collections/community.general#5236]
### Summary

I am trying to configure my new Odroid N2+ with CoreELEC (based on Just enough OS) via Ansible.

I want to use `community.general.opkg` to install some tools.

Unfortunately the bin file is located at another path than usual.

```
TASK [Install useful tools] ***************************************************************************************************************************************
fatal: [odroid]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"opkg\" in paths: /bin:/usr/bin:/usr/sbin:/sbin"}
```

this is the correct location:

```
odroid:~ # which opkg
/opt/bin/opkg
```

Crating a symbolic link in the expected path is no solution either:

```
TASK [Create a symbolic link for opkg] ***************************************************************************************************************************************
fatal: [odroid]: FAILED! => {"changed": false, "msg": "Error while linking: [Errno 30] Read-only file system: b'/opt/bin/opkg' -> b'/bin/opkg'", "path": "/bin/opkg"}
```

### Issue Type

Feature Idea

### Component Name

opkg

### Additional Information

I would like to define the location of the `opkg` bin file somewhere.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/packaging/os/opkg.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/os/opkg.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @skinp
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by CWempe** [comment]
As a workaround I use this now:

```yaml
  tasks:
    - name: Update opkg list
      ansible.builtin.command: /opt/bin/opkg update

    - name: Upgrade opkg packages
      ansible.builtin.command: /opt/bin/opkg upgrade

    - name: Install useful tools
      ansible.builtin.command: /opt/bin/opkg install mc htop iftop dstat iperf iotop oping git multitail unzip ncdu qrencode imagemagick
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/opkg.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/opkg.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
Hi @CWempe thanks for requesting this feature. I am taking a look at it now.

In the meantime, another thing that could work (not tested) is:

```yaml
- community.general.opkg:
    name: [ mc htop iftop dstat iperf iotop oping git multitail unzip ncdu qrencode imagemagick ]
    update_cache: true
  environment:
    PATH: /opt/bin:{{ ansible_env.PATH }}
```

**Comment by russoz** [comment]
hi @CWempe could you please check whether the code in the PR works for you?

**Comment by CWempe** [comment]
I finally found some time to test this.
But it does not work.

I updates ansible and the collection to get the new parameter `executable`.

```
ansible-galaxy collection install community.general
````

This is my task:

```yaml
    - name: Install useful tools
      community.general.opkg:
        executable: /opt/bin/opkg
        name: iotop
        state: present
```

I get this error:

```xml
The full traceback is:
  File "/tmp/ansible_community.general.opkg_payload_qneplcxl/ansible_community.general.opkg_payload.zip/ansible/module_utils/basic.py", line 1440, in get_bin_path
    bin_path = get_bin_path(arg=arg, opt_dirs=opt_dirs)
  File "/tmp/ansible_community.general.opkg_payload_qneplcxl/ansible_community.general.opkg_payload.zip/ansible/module_utils/common/process.py", line 42, in get_bin_path
    raise ValueError('Failed to find required executable "%s" in paths: %s' % (arg, os.pathsep.join(paths)))
fatal: [odroid]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "executable": "/opt/bin/opkg",
            "force": null,
            "name": [
                "iotop"
            ],
            "state": "present",
            "update_cache": false
        }
    },
    "msg": "Failed to find required executable \"opkg\" in paths: /:/:/usr/bin:/usr/sbin:/storage/.kodi/addons/service.aml-vnc/bin:/storage/.kodi/addons/service.system.docker/bin:/storage/.kodi/addons/virtual.system-tools/bin:/sbin"
}
```

The path should be correct:
![image](https://github.com/ansible-collections/community.general/assets/1270359/ddcd33fe-2d25-4fc5-85f3-d2145174416f)

Am I missing something?
