### ISSUE TITLE
File: iso_create module not handle type or value of parameter "dest_iso" well

### ISSUE THREAD

**Issue by Tomorrow9** [ansible-collections/community.general#527]
##### SUMMARY

The type of parameter "dest_iso" in module is set to "path", but when giving this parameter a value of "list of path string", no error returned and no ISO file created.
```
dest_iso:
    - "/tmp/test.iso"
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iso_create
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: Create an ISO file
      iso_create:
        src_files:
          - /tmp/ansible/meta-test1
          - /tmp/ansible/meta-test2
        dest_iso:
          - /tmp/ansible/test.iso
        interchange_level: 4
      register: test_result
    - debug: var=test_result

```

##### EXPECTED RESULTS

Error returned about the configured parameter is not expected type.

##### ACTUAL RESULTS

No error returned, and no ISO file created.

```paste below
PLAY [localhost] *****************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [Create an ISO file] ********************************************************************************************************************************************************
changed: [localhost]

TASK [debug] *********************************************************************************************************************************************************************
ok: [localhost] => {
    "test_result": {
        "changed": true, 
        "created_iso": "['/tmp/ansible/test.iso']", 
        "failed": false, 
        "interchange_level": 4, 
        "joliet": null, 
        "rock_ridge": null, 
        "source_file": [
            "/tmp/ansible/meta-test1", 
            "/tmp/ansible/meta-test2"
        ], 
        "udf": null, 
        "vol_ident": ""
    }
}
```
