### ISSUE TITLE
influxdb_retention_policy: shard group duration not changeable

### ISSUE THREAD

**Issue by sbaygithub** [ansible-collections/community.general#529]
##### SUMMARY
The original issue is from https://github.com/ansible/ansible/issues/44711

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
influxdb_retention_policy

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/sbaygithub/.ansible.cfg) = True
DEFAULT_MANAGED_STR(/Users/sbaygithub/.ansible.cfg) = THIS FILE IS MANAGED BY ANSIBLE
DEFAULT_NO_TARGET_SYSLOG(/Users/sbaygithub/.ansible.cfg) = True
```

##### OS / ENVIRONMENT

MacOSX 10.15.5

##### STEPS TO REPRODUCE
Use the option shard_group_duration and set it to e.x. 1d

```yaml
- name: 'create retention policy for prometheus database'
  influxdb_retention_policy:
    hostname: localhost
    port: 8888
    database_name: prom
    policy_name: prom
    duration: 2d
    shard_group_duration: 1d
    replication: 1
    default: true
```

##### EXPECTED RESULTS

I would expect that the retention policy will be changed

##### ACTUAL RESULTS

```
fatal: [prometheus.emoto2.local]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (influxdb_retention_policy) module: shard_group_duration Supported parameters include: database_name, default, duration, hostname, password, policy_name, port, proxies, replication, retries, ssl, timeout, udp_port, use_udp, username, validate_certs"}
fatal: [prometheus.rz.emoto2.local]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (influxdb_retention_policy) module: shard_group_duration Supported parameters include: database_name, default, duration, hostname, password, policy_name, port, proxies, replication, retries, ssl, timeout, udp_port, use_udp, username, validate_certs"}
```

```paste below

```
