### ISSUE TITLE
LXC module uses python2

### ISSUE THREAD

**Issue by Igorgro** [ansible-collections/community.general#5294]
### Summary

LXC related modules use python2, which is EOL since 2020 and is not available in modern linux distros.

### Issue Type

Bug Report

### Component Name

lxc
lxc_container

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.4]
  config file = /home/igormahov/dev/ansible/miem/collection/ansible.cfg
  configured module search path = ['/home/igormahov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/igormahov/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.6.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Arch Linux, but generally it doesn't matter

### Steps to Reproduce

Try to connect to LXC host using lxc connection. Sample inventory:
```yaml (paste below)
all:
  hosts:
    mylxc:
      ansible_connection: community.general.lxc
      ansible_host: 192.168.123.123
      ansible_user: root
```
Sample playbook:
```yaml
- name: Setup VM
  hosts: mylxc
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: Hello
```
Results in error:
```
fatal: [mylxc]: FAILED! => {"msg": "lxc bindings for python2 are not installed"}
```
which cannot be resolved because python2 no longer available.
The same porblem is related to `lxc_container` module which also requires python2 lxc bindings.

### Expected Results

It is expected that lxc modue depends on [python3 lxc binding](https://github.com/lxc/python3-lxc) rather than python2.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
