### ISSUE TITLE
onepassword_info sign in issue with 1password-cli 2.7.1

### ISSUE THREAD

**Issue by a-gold** [ansible-collections/community.general#5303]
### Summary

Hi,

when signing in to 1password cli and executing my ansible playbook immediately afterwards the **onepassword_info** module isn't able to retrieve data from onepassword, because it doesn't seem to recognize that I'm already signed in.

The module throws the following error message:
```
Unable to perform an initial sign in to 1Password. Please run 'op signin' or define credentials in 'auto_login'. See the module documentation for details.
```
These are the current versions installed on my debian11 machine:
- ansible 6.4.0
- ansible-core 2.13.4
- 1password-cli/stable,now 2.7.1-1 amd64
- community.general:5.6.0

**However I can avoid this issue, if I remove the current version of 1password-cli and use the binary of version 1.8.0 instead.** Because of this workaround this isn't an urgent issue for me, but nevertheless I would prefer to use the latest version of the 1password-cli.

Since it's working fine with the binary, I'm not quite sure if it's some kind version (or configuration?) conflict/incompatibility...
I hope I didn't create a duplicated issue, but I did not found anything regarding this topic.

Thanks in advance.

### Issue Type

Bug Report

### Component Name

onepassword_info

### Ansible Version

- ansible 6.4.0
- ansible-core 2.13.4

### Community.general Version

community.general:5.6.0

### OS / Environment

debian11

### Steps to Reproduce

My ansible task:

```yaml (paste below)
- name: Retrieve secrets from onepassword
  community.general.onepassword_info:
    search_terms:
      - name: "{{item.password_op_entry}}"
  register: myData_with_secrets
  loop: "{{ myData }}"
  no_log: yes
```
Ansible playbook (executed locally, therefore I don't need the delegate_to_localhost parameter at my task).
```yaml (paste below)
- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  roles:
    - { role: myRole }
```

### Expected Results

I expected to retrieve passwords from the 1password-cli / the onepassword_info module. But onepassword_info keeps failing with an error message saying I'm not signed in although I already am.

### Actual Results

```console (paste below)
msg: Unable to perform an initial sign in to 1Password. Please run 'op signin' or define credentials in 'auto_login'. See the module documentation for details.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
