### ISSUE TITLE
Support for interfaces of type MACVLAN using nmcli module.

### ISSUE THREAD

**Issue by ganniterix** [ansible-collections/community.general#5316]
### Summary

Currently there is no support for interfaces of type macvlan using the nmcli module.

Currently running a similar script will configure a macvlan that persists across reboots.

```script
nmcli connection add \
   type macvlan \
   con-name macvlan0
   dev eth0 \
   mode bridge \
   mac aa:bb:cc:00:11:22 \
   802-3-ethernet.cloned-mac-address aa:bb:cc:00:11:22 \
   ifname macvlan0 \
   ip4 192.168.1.1/24 \
   ipv6.method ignore \
   connection.autoconnect yes
```

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

```yaml (paste below)
name: Configure connection
  community.general.nmcli:
    type: "macvlan"
    conn_name: "macvlan0"
    ifname: "macvlan0"
    autoconnect: True
    ip4: "192.168.1.1/24"
    macvlanhwaddress: "aa:bb:cc:00:11:22"
    macvlandev: "eth0" 
    mode: "bridge"
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
