### ISSUE TITLE
ejabberd_user rc: 1

### ISSUE THREAD

**Issue by eliteaz** [ansible-collections/community.general#5355]
### Summary

Use a simple task to create ejabberd user
```
    - name: Create xmpp user
      community.general.ejabberd_user:
        host: "test-xmpp.org"
        username: "bot-dev"
        password: "YZSdvce93FbeRopvT5s8vPVvP"
```

When I create ejabberd user always get an error `rc:1`
```
failed: [tvm-prod-test-xmpp01.org] (item={'xmpp_username': 'bot-dev', 'xmpp_password': 'YZSdvce93FbeRopvT5s8vPVvP'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "xmpp_password": "YZSdvce93FbeRopvT5s8vPVvP",
        "xmpp_username": "bot-dev"
    },
    "rc": 1
}
```
as module require:
ejabberd configuration file include **mod_admin_extra** as a module.
and password also stored in **clear text**

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.5]
python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
jinja version = 2.11.3
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 5.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

expect to create user for ejabberd 

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
