### ISSUE TITLE
Enable the use of a seed in random_string

### ISSUE THREAD

**Issue by rmbleeker** [ansible-collections/community.general#5362]
### Summary

I realize this request defeats the point of a truly random result, but sometimes it can be useful to generate a random string in an idempotent way by setting a seed. The [random number filter](https://docs.ansible.com/ansible/2.9/user_guide/playbooks_filters.html#random-number-filter) already supports this according to the documentation.

### Issue Type

Feature Idea

### Component Name

random_string

### Additional Information

```yaml (paste below)
---
- name: create a new user with a default password
  hosts: workstations
  become: true

  vars:
    default_user_password: 'whatever'
    special_chars: './'

  tasks:
    - name: create user account
      user:
        name: test
        password: "{{ default_user_password | password_hash('sha512', lookup('community.general.random_string', override_special=special_chars, seed=inventory_hostname) | string) }}"
        update_password: on_create

    # require the user to change the default password at first login
    - name: pre-expire the default password
      command: chage -d 0 test
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
