### ISSUE TITLE
scaleway_sshkey and other accounts related modules are broken (api change on scaleway side)

### ISSUE THREAD

**Issue by mpaulon** [ansible-collections/community.general#5376]
### Summary

The modules scaleway_sshkey, scaleway_organization_info and maybe some other are broken.
Looks like scaleway "silently deprecated the `https://account.scaleway.com/organizations` endpoint becuase it always return `{"organizations": []}` now.
Looking at their golang sdk, they are now using endpoints like `https://api.scaleway.com/account/v2alpha1/ssh-keys` to manage sshkeys.
I'll try to propose a pull-request to fix at least some of theses issues.

### Issue Type

Bug Report

### Component Name

community.general.scaleway_organization_info, ansible.builtin.scaleway_sshkey

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.5]
  config file = /home/michael/git/lemp/infra/ansible/ansible.cfg
  configured module search path = ['/home/michael/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/michael/git/lemp/infra/ansible/env/lib/python3.10/site-packages/ansible
  ansible collection location = /home/michael/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/michael/git/lemp/infra/ansible/env/bin/ansible
  python version = 3.10.7 (main, Oct  1 2022, 04:31:04) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/michael/git/lemp/infra/ansible/env/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Gather Scaleway organizations information
  connection: local
  become: false
  community.general.scaleway_organization_info:
    api_token: "{{ scaleway.token }}"
  register: result

- ansible.builtin.debug:
    msg: "{{ result.scaleway_organization_info }}"
```

### Expected Results

I expect a debug message with infos about my organizations

### Actual Results

```console (paste below)
"scaleway_organization_info": []
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
