### ISSUE TITLE
lvol: specify activation option

### ISSUE THREAD

**Issue by raspbeguy** [ansible-collections/community.general#538]
##### SUMMARY
This issue was already submitted on the [Ansible repo](https://github.com/ansible/ansible/issues/66623).

I think it would be useful to be able to specify the activation option (exclusive, shared, local) for LVs in a shared VG.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lvol

##### ADDITIONAL INFORMATION
We could introduce a new parameter `activation_option` which could take `exclusive`, `shared` or `local` as values.

```yaml
- name: Activate a logical volume with shared lock
  lvol:
    vg: firefly
    lv: test
    active: true
    activation_option: shared
```
