### ISSUE TITLE
jc filter is not working on my machine

### ISSUE THREAD

**Issue by georgettica** [ansible-collections/community.general#5390]
### Summary

I tried to use the jc filter but it didn't work for me at all

### Issue Type

Bug Report

### Component Name

jc

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.5]
  config file = $HOME/$CFG_DIR/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = $HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.8 (main, Oct 12 2022, 09:32:59) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# $HOME/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.1.1  

# /opt/homebrew/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0  


```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING($HOME/$CFG_DIR/ansible.cfg) = True
CACHE_PLUGIN($HOME/$CFG_DIR/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION($HOME/$CFG_DIR/ansible.cfg) = /var/tmp/ansible_cache
CACHE_PLUGIN_TIMEOUT($HOME/$CFG_DIR/ansible.cfg) = 86400
DEFAULT_FORKS($HOME/$CFG_DIR/ansible.cfg) = 25
DEFAULT_GATHERING($HOME/$CFG_DIR/ansible.cfg) = smart
DEFAULT_HOST_LIST($HOME/$CFG_DIR/ansible.cfg) = ['$HOME/$CFG_DIR/inventory.ini']
DEFAULT_LOAD_CALLBACK_PLUGINS($HOME/$CFG_DIR/ansible.cfg) = True
DEFAULT_LOCAL_TMP($HOME/$CFG_DIR/ansible.cfg) = /tmp/ansible-local-24831_xmkv4wm
DEFAULT_ROLES_PATH($HOME/$CFG_DIR/ansible.cfg) = ['$HOME/$CFG_DIR/roles/galaxy', '$HOME/$CFG_DIR/roles']
DEFAULT_STDOUT_CALLBACK($HOME/$CFG_DIR/ansible.cfg) = yaml
DEFAULT_TIMEOUT($HOME/$CFG_DIR/ansible.cfg) = 60
DEPRECATION_WARNINGS($HOME/$CFG_DIR/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS($HOME/$CFG_DIR/ansible.cfg) = ignore
```

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  name: Test JC failure
  tasks:
    - name: Install the pip package
      become: true
      ansible.builtin.pip:
        name: jc
        state: present
        executable: "{{ item }}"
      with_items:
        - pip
        - pip3
    - name: Save nmcli connection
      ansible.builtin.command:
        cmd: nmcli c s
      register: nmcli_result
      changed_when: true # no-changed-when - this is a hack to disable the change_when, as I don't know what check I should put there
    - name: Print nmcli info parsed
      ansible.builtin.debug:
        var: nmcli_result.stdout |  community.general.jc('nmcli')
@georgettica

```

### Expected Results

that the filter will show a json with the values

### Actual Results

```console (paste below)
PLAY [Test JC failure] *********************************************************************************************************************************************************************************************************************************************************

TASK [Install the pip package] *************************************************************************************************************************************************************************************************************************************************
ok: [HOST] => (item=pip)
ok: [HOST] => (item=pip3)

TASK [Save nmcli connection] ***************************************************************************************************************************************************************************************************************************************************
changed: [HOST]

TASK [Print nmcli info parsed] *************************************************************************************************************************************************************************************************************************************************
fatal: [HOST]: FAILED! => 
  msg: You need to install "jc" prior to running jc filter

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
HOST                       : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
