### ISSUE TITLE
Can not create group at Gitlab.com

### ISSUE THREAD

**Issue by Mr4lci** [ansible-collections/community.general#5394]
### Summary

I want to create a group on Gitlab.com, but all I get is a 500 (when using api)

### Issue Type

Bug Report

### Component Name

gitlab_group

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_FORCE_HANDLERS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto
```

### OS / Environment

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

### Steps to Reproduce

```yaml (paste below)
- name: "Creating/Updating repositories in Gitlab.com"
  hosts: localhost
  tasks:
      - name: "Create GitLab SubGroup"
        community.general.gitlab_group:
          api_token: "ApiToken"
          api_url: https://gitlab.com/
          validate_certs: true
          name: "Test group"
          path: "test-group"
          parent: "Apertoso/Proj"
          state: present
```

### Expected Results

Would expect to have a group created.

### Actual Results

```console (paste below)
The full traceback is:
  File "/tmp/ansible_community.general.gitlab_group_payload_rah1kp3j/ansible_community.general.gitlab_group_payload.zip/ansible_collections/community/general/plugins/modules/source_control/gitlab/gitlab_group.py", line 251, in create_group
  File "/usr/lib/python3/dist-packages/gitlab/exceptions.py", line 281, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_job_token": null,
            "api_oauth_token": null,
            "api_password": null,
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_url": "https://gitlab.com/",
            "api_username": null,
            "auto_devops_enabled": null,
            "avatar_path": null,
            "description": null,
            "name": "Test group",
            "parent": "Apertoso/Proj",
            "path": "test-group",
            "project_creation_level": null,
            "require_two_factor_authentication": null,
            "state": "present",
            "subgroup_creation_level": null,
            "validate_certs": true,
            "visibility": "private"
        }
    },
    "msg": "Failed to create group: 500: 500 Internal Server Error "
}
```

I have use the same methode on a group that exists and can change the name but it will not create the group if it doesn't exists, little bit confusing :/

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
