### ISSUE TITLE
docker stack ls - functionality

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.general#540]
_From @jifox on Jun 19, 2020 09:55_

##### SUMMARY

I would like to list all stacks like `docker stack ls` in order to run some setup containers if a particular stack is not present.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_stack

##### ADDITIONAL INFORMATION

```yaml
   - name: List all docker stacks
     docker_stack_info:
         stacks: yes      # return list of known stacks
         ...
```

_Copied from original issue: ansible/ansible#70165_

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cloud/docker/docker_stack.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/cloud/docker/docker_stack.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @danihodovic @dariko @felixfontein @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jifox** [comment]
```yaml
- name: Get list of all stacks with shell command
  command: "docker stack ls --format {{ ('{{ '  ~ '.Name' ~ '}}')|quote }}"
  register: res_stacks
```

**Comment by felixfontein** [comment]
This should rather go into a separate module, `docker_stack_info` (or `docker_stack_list`?).

**Comment by imjoseangel** [comment]
I have prepared the following ready to PR. Let me know if you like the solution:

The playbook

```yaml
---
- name: Docker stack list
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: List stack
      docker_stack_info:
      register: stacklist

    - name: show stack
      debug:
        msg: "{{ stacklist.msg }}"

    - name: Get stack first element
      docker_stack_info:
        name: "{{ stacklist.msg[0].name }}"
        action: tasks
      register: tasks

    - name: Show stack tasks
      debug:
        msg: "{{ tasks.msg }}"
```

The module is able to list the stack and show the tasks associated to the first element (In the example)

Debugs are something like:

```json
ok: [localhost] => {
    "msg": [
        {
            "name": "grafana",
            "namespace": "default",
            "orchestrator": "Kubernetes",
            "services": "2"
        }
    ]
}
```

and

```json
ok: [localhost] => {
    "msg": [
        {
            "current state": "Running 24 hours ago",
            "desired state": "Running",
            "error": "",
            "id": "eda0cda3-1bc",
            "image": "grafana/grafana",
            "name": "grafana_grafana-0",
            "node": "docker-desktop",
            "ports": "*:0->3000/tcp"
        },
        {
            "current state": "Running 24 hours ago",
            "desired state": "Running",
            "error": "",
            "id": "075e8ac3-d28",
            "image": "graphiteapp/graphite-statsd",
            "name": "grafana_graphite-5b5b99dd5f-sk4rh",
            "node": "docker-desktop",
            "ports": "*:0->80/tcp,*:0->2003/tcp,*:0->2004/tcp"
        }
    ]
}
```

Regards
