### ISSUE TITLE
Support lists in community.general.npm

### ISSUE THREAD

**Issue by lstrojny** [ansible-collections/community.general#5421]
### Summary

Following the example of `ansible.builtin.apt` or `ansible.builtin.yum` `community.general.npm` should supports a list of packages as well

### Issue Type

Feature Idea

### Component Name

npm

### Additional Information

```yaml
- name: install some npm packages
  npm:
    name:
      - foo
      - bar
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
