### ISSUE TITLE
Flatpak "No remote refs found" for user while it's there

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible-collections/community.general#5430]
### Summary

Trying to install a flatpak for the first time, if I install it for user only, it doesn't work. It prints a dumb error and if I run the reported command, it works fine in the shell...

### Issue Type

Bug Report

### Component Name

flatpak

### Ansible Version

```console
ansible [core 2.13.5rc1]
  executable location = /bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_HOST_LIST(/home/me/Documents/Ansible/playbooks/LOCAL/ansib>
DEFAULT_ROLES_PATH(/home/me/Documents/Ansible/playbooks/LOCAL/ansi>
DEFAULT_STDOUT_CALLBACK(/home/me/Documents/Ansible/playbooks/LOCAL>
DEFAULT_VAULT_PASSWORD_FILE(/home/me/Documents/Ansible/playbooks/L>
DIFF_ALWAYS(/home/me/Documents/Ansible/playbooks/LOCAL/ansible.cfg>
RETRY_FILES_ENABLED(/home/me/Documents/Ansible/playbooks/LOCAL/ans>
```

### OS / Environment

PopOS 22.04

### Steps to Reproduce

```yaml (paste below)
    - name: Install Krita as Flatpak (because bugs in .deb) for user
      community.general.flatpak:
        name: org.kde.krita
        state: present
        method: user
        #remote: flathub
```

With or without the #remote, with or without this:
```yaml (paste below)
    - name: Add the flathub remote for the whole system
      community.general.flatpak_remote:
        name: flathub
        state: present
        method: user
```
it's always the same result

### Expected Results

It should install.

Note that I have both remotes (I installed system only because of that ansible bug, I already had --user):
```sh
flatpak remotes
Name    Options
flathub system
flathub user
```

I already have krita installed as user manually though.

```
/usr/bin/flatpak install --user --noninteractive flathub org.kde.krita
Skipping: org.kde.krita/x86_64/stable is already installed
```

### Actual Results

```console
TASK [Install Krita as Flatpak (because bugs in .deb) for user] ****************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/flatpak install --user --noninteractive flathub org.kde.krita",
    "rc": 1
}

STDERR:

error: No remote refs found similar to ‘flathub’



MSG:

error: No remote refs found similar to ‘flathub’
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
