### ISSUE TITLE
simple set key hangs

### ISSUE THREAD

**Issue by amit777** [ansible-collections/community.general#5432]
### Summary

the following tasks hangs when trying to set a key
```
- name: Set node.txt key in redis
  tags: redis
  community.general.redis_data:
    login_host: localhost
    key: node.txt
    value: "{{inventory_hostname}}"
    state: present
```

### Issue Type

Bug Report

### Component Name

community.general.redis_data

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /Users/amit/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0

# /opt/homebrew/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Client running on MacOSX
Server is Ubuntu 22.04

### Steps to Reproduce

```yaml 
- name: Set node.txt key in redis
  tags: redis
  community.general.redis_data:
    login_host: localhost
    key: node.txt
    value: "{{inventory_hostname}}"
    state: present
```

### Expected Results

The task should not hang

### Actual Results

```console (paste below)
redirecting (type: modules) community.general.redis_data to community.general.database.misc.redis_data
Using module file /Users/user/.ansible/collections/ansible_collections/community/general/plugins/modules/database/misc/redis_data.py
Pipelining is enabled.
<server> ESTABLISH SSH CONNECTION FOR USER: root
<server> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=1200s -o BatchMode=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="user"' -o ConnectTimeout=10 -o 'ControlPath="/tmp/ansible-%h-%p-%r"' pndb1 '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
