### ISSUE TITLE
community.general.filesystem fails to detect file system already present on iSCSI LUN

### ISSUE THREAD

**Issue by gilgwath** [ansible-collections/community.general#5467]
### Summary

When using community.general.filesystem on a iSCSI LUN the module fails to detect that a filesystem is present, due to the fact that `blkid` does not return any information an iSCSI LUN. However, using `lisblk`instead yields the correct information.

```console
[localadmin@nargothrond ~]$ sudo blkid /dev/disk/by-path/ip-10.0.0.11\:3260-iscsi-iqn.2022-10.net.fam-fa.erebor\:container-nargothrond-lun-2
```
oposed to:

``` console
[localadmin@nargothrond ~]$ sudo lsblk -f /dev/disk/by-path/ip-10.0.0.11\:3260-iscsi-iqn.2022-10.net.fam-fa.erebor\:container-nargothrond-lun-2
NAME FSTYPE FSVER LABEL    UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sdc  xfs          yf_media f2b3d3e6-e46e-4622-9a85-8b765a932aeb  198.5G     1% /mnt/container/jellyfin
```

### Issue Type

Bug Report

### Component Name

community.general.filesystem

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.10]
  config file = /home/simon/ansible-home-lab/ansible.cfg
  configured module search path = ['/home/simon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/simon/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.2  

# /home/simon/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0  

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.7  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/user/ansible-home-lab/ansible.cfg) = ['/home/user/ansible-home-lab/inventory']
```

### OS / Environment

[localadmin@nargothrond ~]$ cat /etc/redhat-release
CentOS Stream release 9

### Steps to Reproduce

```yaml (paste below)
- name: login iscsi targets
  open_iscsi:
    portal: "{{ lookup('dig', iscsi.portal) }}"
    target: "{{ iscsi.iqn }}"
    node_user: "{{ iscsi.username }}"
    node_pass: "{{ iscsi.password }}"
    node_auth: CHAP
    login: true
    auto_node_startup: true
    auto_portal_startup: true
  notify:
    - Restart iscsid

- name: format LUNs
  community.general.filesystem:
    dev: "/dev/disk/by-path/{{ item.path }}"
    fstype: xfs
    opts: "-L {{ item.label }}"
    state: present
  loop:
    - path: "ip-{{ lookup('dig', iscsi.portal) }}:3260-iscsi-{{ iscsi.iqn }}-lun-1"
      label: "{{ iscsi.labels[0] }}"
    - path: "ip-{{ lookup('dig', iscsi.portal) }}:3260-iscsi-{{ iscsi.iqn }}-lun-2"
      label: "{{ iscsi.labels[1] }}"
```

### Expected Results

If no file system is not present, the LUN gets formatted with XFS, if a file system is present the LUN is not formated

### Actual Results

```console (paste below)
failed: [nargothrond.fam-fa.net] (item={'path': 'ip-10.0.0.11:3260-iscsi-iqn.2022-10.net.fam-fa.erebor:container-nargothrond-lun-1', 'label': 'cmn_data'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "/sbin/mkfs.xfs -f -L cmn_data /dev/disk/by-path/ip-10.0.0.11:3260-iscsi-iqn.2022-10.net.fam-fa.erebor:container-nargothrond-lun-1", "item": {"label": "cmn_data", "path": "ip-10.0.0.11:3260-iscsi-iqn.2022-10.net.fam-fa.erebor:container-nargothrond-lun-1"}, "msg": "mkfs.xfs: /dev/disk/by-path/ip-10.0.0.11:3260-iscsi-iqn.2022-10.net.fam-fa.erebor:container-nargothrond-lun-1 contains a mounted filesystem\n
```
The module tries to format the LUN even though there's already a file system present and mounted.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
