### ISSUE TITLE
community.general.keycloak_client does not update the default_client_scopes on rerun 

### ISSUE THREAD

**Issue by dsaju** [ansible-collections/community.general#5495]
### Summary

I created a task with keycloak_client to create/update client. But the rerrun of the task with changed values for default_client_scopes does not update the client . 

### Issue Type

Bug Report

### Component Name

community.general.keycloak_client

### Ansible Version

```console (paste below)
ansible --version
ansible [core 2.12.3]




### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```
Collection        Version
----------------- -------
community.general 5.8.0

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

GNU/Linux

### Steps to Reproduce

Steps 
1. Run keycloak locally using docker at localhost:8080/auth
2. Create a task for creating client as seen in yaml below 

```
- hosts: localhost
  tasks:
  - name: Create or update Keycloak client (minimal example), authentication with credentials
    community.general.keycloak_client:
      auth_keycloak_url: http://localhost:8080/auth
      auth_realm: master
      auth_username: admin
      auth_password: admin
      default_client_scopes: [email]
      client_id: testSD-bug
      state: present
    delegate_to: localhost
```
3. Run the ansible-playbook with above yaml  . Client is created 
4. Update the playbook by modifying the parameter default_client_scopes 

```
- hosts: localhost
  tasks:
  - name: Create or update Keycloak client (minimal example), authentication with credentials
    community.general.keycloak_client:
      auth_keycloak_url: http://localhost:8080/auth
      auth_realm: master
      auth_username: admin
      auth_password: admin
      default_client_scopes: []
      client_id: testSD-bug
      state: present
    delegate_to: localhost
```
5. Run ansible-playbook again with the modifying yaml 

### Expected Results

default_client_scopes is modified for the client and should be empty as seen with --check option 

```
ansible-playbook -i inventories/local  create_client_test.yml  --check -K

PLAY [localhost] *****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create or update Keycloak client (minimal example), authentication with credentials] ***************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

### Actual Results

```
 ansible-playbook -i inventories/local  create_client_test.yml  -K
BECOME password:
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths

PLAY [localhost] *****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create or update Keycloak client (minimal example), authentication with credentials] ***************************************************************************************************************************
ok: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
