### ISSUE TITLE
ERROR! couldn't resolve module/action 'mail' even though community.general.mail is installed on Ansible Automation Platform 4.2.1

### ISSUE THREAD

**Issue by souovan** [ansible-collections/community.general#5498]
### Summary

I'm trying to use the module ```mail``` (community.general.mail) to send and e-mail with a playbook

### Issue Type

Bug Report

### Component Name

community.general.mail

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.10 (main, Sep 23 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL9

### Steps to Reproduce

```yaml (paste below)
    - name: Check if ( error_file.txt ) exists and send it by email
      mail:
          host: smtp.gmail.com
          port: 587
          secure: starttls
          username: "{{ email_smtp_username }}"
          password: "{{ email_smtp_password }}"
          subject: Ansible-Websphere-report
          from: "{{ email_smtp_username }}"
          body: Attach contains hosts where the update task failed
          to:
          - User <some.user@gmail.com>
          attach:
          - /home/van/ansible/error_file.txt
          headers:
          - Reply-To=noreply@example.com
          charset: us-ascii
      when: error_file_output.stat.exists
```

### Expected Results

I expected the module to be executed and sent an email

### Actual Results

```console (paste below)
ERROR! couldn't resolve module/action 'mail'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/test/tasks/test.yml': line 71, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: Check if ( error_file.txt ) exists and send it by email
      ^ here
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/mail.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/mail.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
This collection doesn't do anything special, so this isn't a problem related to this collection, but more a support problem for ansible-core. Please ask in one of the following places:

* IRC: #ansible on irc.libera.chat
* Matrix: [#users:ansible.com](https://matrix.to/#/#users:ansible.com)
* Mailing List: https://groups.google.com/forum/#!forum/ansible-project
* More details: https://docs.ansible.com/ansible/latest/community/communication.html

(In the unlikely case that you're building an EE with Ansible 2.9, please note that community.general 5.x.y does not support Ansible 2.9. You either have to upgrade to a more modern ansible-core version, or stick to older community.general releases.)

(This seems like a similar problem, maybe even the same: #5375.)

**Comment by russoz** [comment]
You might want to try to use the fully qualified name:
```yaml
    - name: Check if ( error_file.txt ) exists and send it by email
      community.general.mail:
          host: smtp.gmail.com
          port: 587
(...)
```
