### ISSUE TITLE
apt_repo has no filename support

### ISSUE THREAD

**Issue by HOSTED-POWER** [ansible-collections/community.general#5519]
### Summary

I'm trying to move from apt_repository to apt_repo so we can use the fantastic remove_others feature, however I'm missing the filename which is crucial for our usage.

Probably this is a small enhancement? 

### Issue Type

Feature Idea

### Component Name

apt_repo

### Additional Information

Current code

```yaml (paste below)
- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: |
      deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main
      deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main
    state: present
    filename: nodejs
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
