### ISSUE TITLE
[flatpak] Can’t remove runtimes

### ISSUE THREAD

**Issue by fbruetting** [ansible-collections/community.general#553]
##### SUMMARY
I just can’t remove runtimes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
flatpak

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/frank/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Fedora 32

##### STEPS TO REPRODUCE
On a new Fedora 32, you have `org.fedoraproject.Platform` and `org.gnome.Extensions` installed. When you want to delete them both, the following task would work just for the application, not for the runtime (I also tried with `org.fedoraproject.Platform/x86_64/f32`). The same way you can install `org.gnome.Platform` of the `flathub` repo and also there you would not be able to uninstall it.

```yaml
- name: Test
  hosts: localhost
  gather_facts: yes
  become: yes

    - name:                 "Delete packages"
      when:                 (ansible_facts['distribution'] == "Fedora")
      flatpak:
        name:               "{{ item }}"
        state:              absent
        remote:             fedora
      loop:
                            - org.gnome.Extensions
                            - org.fedoraproject.Platform
```

##### EXPECTED RESULTS
I would expect that it works for runtimes, too.

##### ACTUAL RESULTS
Doesn’t work for runtimes:

```paste below
TASK [Delete packages] ******************************************
changed: [khazad-dum] => (item=org.gnome.Extensions)
ok: [khazad-dum] => (item=org.fedoraproject.Platform)
```
