### ISSUE TITLE
gitlab_project: enable/disable CI/CD 

### ISSUE THREAD

**Issue by staehler** [ansible-collections/community.general#5530]
### Summary

I'ld like to enable CI/CD when creating a new gitlab_project. At the moment I need to extract the project ID via gitlab API and then enable CI/CD via gitlab API.

### Issue Type

Feature Idea

### Component Name

gitlab_project

### Additional Information

substitute this API call
```- name: "enable CI/CD on project {{ gitlab_project.project_name }}"
  uri:
    url: "https://{{ gitlab_api_url }}/api/v4/projects/{{ gitlab_project_result.project.id }}?private_token={{ gitlab_api_token }}"
    method: "PUT"
    validate_certs: True
    body: "jobs_enabled=true&builds_access_level=enabled&repository_access_level=enabled"
```
by a parameter like `cicd_enabled`
```
- name: "create GitLab project {{ gitlab_project.project_name }}"
  community.general.gitlab_project:
    api_url: "https://{{ gitlab_api_url }}"
    validate_certs: True
    api_token: "{{ gitlab_api_token }}"
    name: "{{ gitlab_project.project_name }}"
    group: "group"
    visibility: private
    cicd_enabled: true
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/gitlab_project.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/gitlab_project.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Lunik @Shaps @dj-wasabi @lgatellier @marwatk @metanovii @nejch @scodeman @sh0shin @suukit @waheedi @zanssa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by staehler** [comment]
Only this variables are filled after creating/updating a project. There is no project Key as expected
![image](https://user-images.githubusercontent.com/6258158/201124532-c4a4a2f1-cf27-4276-9613-7fcf2226abaa.png)

```
TASK [gitlab_projects : create GitLab project] **********************************************************************************************
ok: [localhost]

TASK [gitlab_projects : debug] ****************************************************************************************************************************************************************************
ok: [localhost] => 
  msg:
    changed: false
    failed: false
    msg: Successfully created or updated the project
```

**Comment by Lunik** [comment]
The GitLab document says that CI/CD is enabled by default on all new projects. Not sure what you want to achieve here.
Référence : https://docs.gitlab.com/ee/ci/enable_or_disable_ci.html

**Comment by staehler** [comment]
Good morning and thank your for this quick response. As I saw, you already made a new module for project badges. Wow, that's very fast :-)
When can I expect this enhancement in the community collection package?

Unfortunately, I'm not able to create a gitlab project with CI/CD enabled, although the documentation says otherwise. 
Im using ansible 2.12 and community general collection version 6.0.

My task looks like this (it's in a loop over lots of projects):

```
- name: "create GitLab project {{ gitlab_project.project_name }} "
  community.general.gitlab_project:
    api_url: "https://{{ gitlab_api_url }}"
    validate_certs: True
    api_token: "{{ gitlab_api_token }}"
    name: "{{ gitlab_project.project_name }}"
    group: "test"
    description: "Test project {{ gitlab_project.project_name }}"
    visibility: private
    packages_enabled: false
    lfs_enabled: true
    shared_runners_enabled: false
    merge_requests_enabled: true
    issues_enabled: true    # issues_access_level
    wiki_enabled: false     # wiki_access_level
    snippets_enabled: false # snippets_access_level
    import_url: "https://{{ gitlab_api_url }}/itssm/0200-templates.git"
    state: present
  no_log: "{{ nolog }}"
  register: gitlab_project_result
```
Can you find any obvious mistake I made?

And just one thougth: it seems, that the module is not able to switch CI/CD ON or OFF. I have indeed some projects, where CI/CD should not be enabled.
