### ISSUE TITLE
ansible_galaxy_install not idempotent for git sources

### ISSUE THREAD

**Issue by gone-for-coding** [ansible-collections/community.general#5568]
### Summary

When installing a collection from a git repo, the module is not idempotent.

### Issue Type

Bug Report

### Component Name

The issue is withing ansible-galaxy having an implicit --force on git sources. See: https://github.com/ansible/ansible/issues/78481

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.15 (default, Oct 14 2022, 00:26:24) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = auto_silent
```

### OS / Environment

Debian 11

### Steps to Reproduce

```yaml (paste below)
    - name: Check for Ansible collections with correct version
      community.general.ansible_galaxy_install:
        name: "{{ item }}"
        type: collection
        dest: /usr/share/ansible/collections
      loop:
        - "ansible.posix:>=1.4.0,<1.5.0"
        - "ansible.windows:>=1.11.1,<1.12.0"
        - "community.windows:>=1.11.0,<1.12.0"
        - "https://github.com/ansible-collections/community.general.git,6.0.1"
```

### Expected Results

On a second run nothing is reported as changed. This is true for all but the git source.

### Actual Results

```console (paste below)

```
Git source will always report changed and overwrite the collection.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
