### ISSUE TITLE
idrac_redfish_command module - requesting job_id on the output

### ISSUE THREAD

**Issue by naveen-kumar-r** [ansible-collections/community.general#5603]
### Summary

idrac_redfish_command CreateBiosConfigJob  command doesn't return job id now. I'm trying to check if job is completed before moving to next steps. This will ensure system is consistent state before next steps are executed.

### Issue Type

Feature Idea

### Component Name

idrac_redfish_command

### Additional Information

```yaml (paste below)
- name: Create BIOS Config job
  community.general.idrac_redfish_command:
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    category: Systems
    command: CreateBiosConfigJob
  register: bios_job

- debug:
     msg: "{{ bios_job.job_id }}


```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/idrac_redfish_command.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/idrac_redfish_command.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bhavya06 @mraineri @rajeevkallur @renxulei @tomasg2012 @xmadsen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jyundt
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mraineri** [comment]
Since "msg" typically contains a message string and isn't necessarily programmatic, I would propose adding a new return property to contain the job ID. I would recommend using something like "return_values" like we did in the common Redfish module. This is what I'm thinking specifically:

```
RETURN = '''
msg:
    description: Message with action result or error description
    returned: always
    type: str
    sample: "Action was successful"
return_values:
    description: Dictionary containing command-specific response data from the action.
    returned: on success
    type: dict
    sample: {
        "job_id": "/redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_471269252011"
    }
'''
```

Would this approach work for you?
