### ISSUE TITLE
Snapcraft: Add 'alias'

### ISSUE THREAD

**Issue by dmp1ce** [ansible-collections/community.general#566]
##### SUMMARY
Because of naming restrictions on snaps it is sometimes necessary to use an alias for snaps. Right now this can be done by requesting an alias in the snapcraft forum or by setting up an alias in the shell.

##### ANSIBLE VERSION
```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

##### ISSUE TYPE
I would like to propose a snap module addition to support the snap alias commands.

##### COMPONENT NAME
lib/ansible/modules/packaging/os/snap.py

##### ADDITIONAL INFORMATION
Currently, I run commands like this:

```yaml
    - name: Snap Package - Standard Install
      snap:
        name: check-cgminer
    - name: Snap Package - Setup Alias
      shell: 'snap alias check-cgminer check_cgminer'
```

Ideally, it should be configurable with something similar to:

```yaml
    - name: Snap Package - Standard Install
      snap:
        name: check-cgminer
        alias: check_cgminer
```

Similar to issue https://github.com/ansible/ansible/issues/58403
Recreated as requested in https://github.com/ansible/ansible/issues/61400 and https://github.com/ansible/ansible/issues/70194

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/packaging/os/snap.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/packaging/os/snap.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
@dmp1ce: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @angristan @vcarceler
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @dmp1ce how would you do if you have a list of two packages and you want only one alias?

Something like?

```yaml
    - name: Snap Package - Standard Install
      snap:
        name: 
            - check-cgminer
            - hello-world
        alias: hello-world:hw
```

I think it is interesting to have `unalias` too: Would you proceed the same way?

```yaml
    - name: Snap Package - Standard Install
      snap:
        name: 
            - check-cgminer
            - hello-world
        unalias: hello-world:hw
```

Also alias and unalias should be incompatible with `absent` status. Do you agree?

What about also the `prefer` option together with `alias` and `unalias`?
