### ISSUE TITLE
Add dotnet_tool module

### ISSUE THREAD

**Issue by Jackenmen** [ansible-collections/community.general#5683]
### Summary

This collection has modules for many package managers but there isn't one for .NET's `dotnet tool` yet. Considering the popularity of the language, it seems like a reasonable addition to the existing packaging modules.

### Issue Type

Feature Idea

### Component Name

dotnet_tool

### Additional Information

```yaml
- name: playbook name
  hosts: localhost
  tasks:
    - name: install git-credential-manager
      community.general.dotnet_tool:
        name: git-credential-manager
        global: true
        state: present

    - name: install/upgrade git-credential-manager to latest version
      community.general.dotnet_tool:
        name: git-credential-manager
        global: true
        state: latest

    - name: uninstall git-credential-manager
      community.general.dotnet_tool:
        name: git-credential-manager
        global: true
        state: absent

    - name: install/update/downgrade Microsoft.dotnet-interactive to v1.0.355206
      community.general.dotnet_tool:
        name: Microsoft.dotnet-interactive
        global: true
        version: 1.0.355206
        state: present

    - name: update all
      community.general.dotnet_tool:
        global: true
        state: update_all
```

I'm unsure how installing/updating/downgrading to a specific version of a package and how updating all tools should be specified in the YAML file.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
