### ISSUE TITLE
community.general.gitlab_group_variable:  state "absent" has no impact

### ISSUE THREAD

**Issue by olwe0002** [ansible-collections/community.general#5684]
### Summary

deleting single variables with state `absent` and purge: `false` is not possible. it will end up in the `untouched` array of the results and the task will do nothing at all

### Issue Type

Bug Report

### Component Name

gitlab_group_variable

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.14.0]
  config file = /home/work/dev/gec/alm/maintenance-tasks/ansible/ansible.cfg
  configured module search path = ['/home/work/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/work/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/work/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/work/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general


# /home/work/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.1.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6 


```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

ubuntu

### Steps to Reproduce

```yaml (paste below)


- name: set variable to delete  # works fine
  community.general.gitlab_group_variable:
    api_url: "{{ gitlab_host }}"
    api_token: "{{ gitlab_login_token }}"
    group: "{{ gitlab_group_name }}"
    vars:
      some: value

- name: delete the variable again  # does nothing
  community.general.gitlab_group_variable:
    api_url: "{{ gitlab_host }}"
    api_token: "{{ gitlab_login_token }}"
    group: "{{ gitlab_group_name }}"
    state: absent
    vars:
      some: value
```

### Expected Results

after the second task is executed, the variable `some` is deleted 

### Actual Results

after the second task is executed, the variable `some` is still existing 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
