### ISSUE TITLE
gitlab_project_variable add support for new `expanded` key

### ISSUE THREAD

**Issue by envy** [ansible-collections/community.general#5685]
### Summary

On 2022-11-22, GitLab released support for a new flag: `expand`, see [here](https://docs.gitlab.com/ee/ci/yaml/#variablesexpand).

This also introduced a [new toggle for project CI vars](https://docs.gitlab.com/ee/ci/variables/index.html#expand-cicd-variables):

![grafik](https://user-images.githubusercontent.com/241552/207574327-12faf44d-6e16-45e7-a4a8-558c7052d64b.png)
(Ignore the green border)
![grafik](https://user-images.githubusercontent.com/241552/207577020-bf0b2263-5455-4a57-86f5-8b1126ce0acf.png)

GitLab claims, this has been there since GitLab 13.7 (which released 2 years ago) but I have never seen this before.

Anyway, my ansible playbook that sets CI vars now claims all my variables are missing and it would like to add them all.
I guess this is because GitLab now puts the expand flag an all of them by default and ansible sees that as a difference?
It's also not possible to set this from ansible as the module does not support the flag.

So this is kinda a feature request to add the flag but also a bug report because currently it incorrectly thinks everything is different.

### Issue Type

Feature Idea

### Component Name

gitlab_project_variable

### Additional Information

Example taken from the docs and altered:

```yaml (paste below)
- name: Set or update some CI/CD variables
  community.general.gitlab_project_variable:
    api_url: https://gitlab.com
    api_token: secret_access_token
    project: markuman/dotfiles
    purge: false
    variables:
      - name: ACCESS_KEY_ID
        value: abc123
      - name: SECRET_ACCESS_KEY
        value: dassgrfaeui8989
        masked: true
        protected: true
        expanded: false  # This would be a new key to disable variable expansion, GitLab default is true
        environment_scope: production
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
