### ISSUE TITLE
Support gitlab forking_access_level, builds_access_level and container_registry_access_level fields

### ISSUE THREAD

**Issue by juanvalino** [ansible-collections/community.general#5691]
### Summary

Add support for the following gitlab project fields (see [gitlab api rest](https://docs.gitlab.com/ee/api/projects.html#create-project) for detail of these fields):
- `forking_access_level`: shown as `Repository forks`  project setting in gitlab web user interface
- `builds_access_level`: shown as `Repository CI/CD` project setting in gitlab web user interface
- `container_registry_access_level`:  shown as `Container registry`  project setting in gitlab web user interface

### Issue Type

Feature Idea

### Component Name

gitlab_project

### Additional Information

Example of project creation using the new fields:

```yaml
- name: Setup gitlab project
  community.general.gitlab_project:
    api_url: https://gitlab.example.com/
    validate_certs: true
    api_username: dj-wasabi
    api_password: "MySecretPassword"
    name: my_project
    group: ansible
    builds: disabled
    container_registry: disabled
    forks: disabled
    state: present
  delegate_to: localhost
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
