### ISSUE TITLE
zfs_delegate_admin doesn't allow properties to be delegated

### ISSUE THREAD

**Issue by bvarick** [ansible-collections/community.general#5707]
### Summary

When I try to delegate a property (i.e. recordsize), the task fails with the error message: "value of permissions must be one or more of: allow, clone, create, destroy, diff, hold, mount, promote, readonly, receive, release, rename, rollback, send, share, snapshot, unallow. Got no match for: recordsize".

The man pages for zfs allow list properties as an option: https://openzfs.github.io/openzfs-docs/man/8/zfs-allow.8.html
and doing the command zfs allow $user recordsize $dataset works as intended

### Issue Type

Bug Report

### Component Name

community.general.zfs_delegate_admin

### Ansible Version

```console (paste below)
$ ansible --version

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: Grant `zfs send,receive` to users 
  community.general.zfs_delegate_admin:
    name: dataset
    users: user
    permissions: receive,mount,create,rollback,recordsize
```

### Expected Results

I expected the permissions to be delgated

### Actual Results

```console (paste below)
"value of permissions must be one or more of: allow, clone, create, destroy, diff, hold, mount, promote, readonly, receive, release, rename, rollback, send, share, snapshot, unallow. Got no match for: recordsize"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
