### ISSUE TITLE
In HP iLO and dell iDRAC the category changed to Managers keep in mind that it's work with Manager as well

### ISSUE THREAD

**Issue by reihl** [ansible-collections/community.general#5736]
### Summary

Documentation point on Systems category while the real category in some providers is Managers

### Issue Type

Documentation Report

### Component Name

redfish_command

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.5]
  config file = /home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg
  configured module search path = ['/home/rhalle/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rhalle/projects/ocp-edge-auto/python39-venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/rhalle/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rhalle/projects/ocp-edge-auto/python39-venv/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/rhalle/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.1.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_BECOME(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = False
DEFAULT_BECOME_ASK_PASS(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = root
DEFAULT_HOST_LIST(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = ['/home/rhalle/ansible-playbooks/deploy-manage/i>
DEFAULT_REMOTE_USER(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = rhce
DEFAULT_ROLES_PATH(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = ['/home/rhalle/.ansible/roles', '/usr/share/ans>
DEPRECATION_WARNINGS(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = False
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/rhalle/ansible-playbooks/deploy-manage/ansible.cfg) = 90

```

### OS / Environment

rhel 8.7
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
Red Hat Enterprise Linux release 8.7 (Ootpa

### Additional Information

ansible localhost -m redfish_command -e '{"parms": {"category": "Manager", "command": "VirtualMediaInsert", "baseuri": "<fqdn>", "username": "admin", "password": "admin", "resource_id": "1", "virtual_media": {"image_url": "http://<IP>:8880/agent.x86_64.iso", "media_types": "CD"}}}' -a '{{ parms }}' -u root
[WARNING]: Using a variable for a task's 'args' is unsafe in some situations (see
https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#argsplat-unsafe)
localhost | CHANGED => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": true,
    "msg": "Action was successful",
    "return_values": {},
    "session": {}

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/redfish_command.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/redfish_command.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bhavya06 @mraineri @rajeevkallur @renxulei @tomasg2012 @xmadsen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mraineri** [comment]
There are two different virtual media paths in Redfish. Originally the spec modeled virtual media underneath "Manager", but was  later migrated to "Systems". Ansible supports both methods for inserting virtual media to allow for older implementations to still work. From a documentation perspective, I see both paths listed, which is correct given the state of the Redfish standard today:

```
  - name: Insert Virtual Media
    community.general.redfish_command:
      category: Systems
      command: VirtualMediaInsert
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      virtual_media:
        image_url: 'http://example.com/images/SomeLinux-current.iso'
        media_types:
          - CD
          - DVD
      resource_id: 1
  - name: Insert Virtual Media
    community.general.redfish_command:
      category: Manager
      command: VirtualMediaInsert
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      virtual_media:
        image_url: 'http://example.com/images/SomeLinux-current.iso'
        media_types:
          - CD
          - DVD
      resource_id: BMC
```
