### ISSUE TITLE
openbsd_pkg: No progress meter: failed termcap lookup on xterm-kitty

### ISSUE THREAD

**Issue by samuel-hunter** [ansible-collections/community.general#5738]
### Summary

I run my playbooks under `kitty` terminal which exports the varaible `TERM=xterm-kitty`. Since `pkg_add` wants to look up the terminal on its own system to learn how to show the progress meter, it warns via stderr "No progress meter: failed termcap lookup on xterm-kitty". The command still works and the packages are installed, though the task detects the warning in text as a failure.

Overriding the env var `TERM: dumb` to the task fixes the issue, eg.:

```yaml
- name: Install rsync
  hosts: all
  become: yes
  tasks:
    - name: Install rsync
      community.general.openbsd_pkg:
        name: rsync--
        state: present
      environment:
        TERM: dumb
```

To free the task from clutter and an environment-based footgun, is it possible to include this in the task itself?

### Issue Type

Bug Report

### Component Name

openbsd_pkg

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/russky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/russky/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/russky/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/russky/.local/bin/ansible
  python version = 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 6.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

host: Debian bookworm/sid Linux 6.0.0-4
remote: OpenBSD 7.2

### Steps to Reproduce

Any play that prompts the remote to install a new package

```yaml (paste below)
---
- name: Install some package
  hosts: all
  become: yes
  tasks:
    - name: Install rsync
      community.general.openbsd_pkg:
        name: rsync--
        state: present
```

### Expected Results

The task reports itself as OK (changed)
```
changed: [example.org]
```

### Actual Results

The task falsely reports itself as fatal
```console (paste below)
fatal: [example.org]: FAILED! => {"build": false, "changed": false, "msg": "No progress meter: failed termcap lookup on xterm-kitty\n", "name": ["rsync--"], "state": "present"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
