### ISSUE TITLE
Feature Request: gitlab_group add LDAP link to an existing GitLab group

### ISSUE THREAD

**Issue by mick1627** [ansible-collections/community.general#575]
##### SUMMARY
gitlab_group should be able to manage group syncing. it allows LDAP groups to be mapped to GitLab groups as explain here => https://docs.gitlab.com/ee/user/group/index.html#manage-group-memberships-via-ldap
This options is only available on gitlab EE.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gitlab_group

##### ADDITIONAL INFORMATION
Here how it is manage using API call => https://docs.gitlab.com/ee/api/groups.html#add-ldap-group-link-with-cn-or-filter-starter
```yaml
    - name: Set an LDAP link to an existing GitLab group
      gitlab_group_ldap_link:
        group_id: "12345"
        cn: "testuser"
        access_level: "developer"
        ldap_provider: "ldapmain"
```
