### ISSUE TITLE
Homebrew modules improvements

### ISSUE THREAD

**Issue by Caesarovich** [ansible-collections/community.general#5792]
### Summary

I would like to have more information via the return values in the homebrew module. For exemples, the upgraded + old versions of packages (Useful when running updates) to know which version has now been installed.

Also I would love to have a new module / include to the current existing ones to run `brew cleanup` commands to remove cached files, and retrieve the information about that as well.

Does that seem like good ideas ?
If so I'll make a PR later on

### Issue Type

Feature Idea

### Component Name

homebrew

### Additional Information

```yaml (paste below)
# Remove stale lock files and outdated downloads for all formulae and casks, and remove old versions of installed formulae
# Also Remove all cache files older than 7 days
- community.general.homebrew_cleanup:
    prune: 7
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
