### ISSUE TITLE
git_config: Add option "override" (true as default)

### ISSUE THREAD

**Issue by valerio-bozzolan** [ansible-collections/community.general#5807]
### Summary

It can be useful to add a configuration, only if the configuration is empty.

In this way you can add something new, keeping existing value.

### Issue Type

Feature Idea

### Component Name

git_config

### Additional Information

```yaml (paste below)
- name: Add a git email only if it's missing
  community.general.git_config:
    name: user.email
    repo: /etc
    override: false
    value: "root@example.com"
```

So this feature request is about implementing the possibility to have an `override: false`  or something similar.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
