### ISSUE TITLE
proxmox_kvm: can't check if VM exists

### ISSUE THREAD

**Issue by Vanav** [ansible-collections/community.general#5819]
### Summary

I want to check if VM exists by its name (to workaround another issue #1964). But it fails if VM doesn't exist:
```
fatal: [fresh_ubuntu_22_node -> localhost]: FAILED! => 
    changed: false
    msg: VM with name = fresh-ubuntu-22 does not exist in cluster
```

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.1]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 6.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```
- name: Check if VM exists
  proxmox_kvm:
    api_host: '{{ proxmox_api_host }}'
    api_user: '{{ proxmox_api_user }}'
    api_password: '{{ proxmox_api_password }}'
    node: pve
    name: fresh_ubuntu_22
    state: current
  delegate_to: localhost
```

### Expected Results

I expect to not get fatal error, but to get VM state or id.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/proxmox_kvm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @helldorado @joshainglis @karmab @tleguern
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The module doesn't document that it allows to determine existence of a VM. So I don't think this is a bug, but rather a feature request.

Also `state=current` should be removed and an `_info` module should be added instead. CC @russoz

**Comment by Vanav** [comment]
I just found no better way. How can I check existence of VM? It is required, because for some strange reason "update" option works only for already existing VMs, so it doesn't allow to write just single idempotent task (#1964).

**Comment by tovoro** [comment]
Hi @Vanav 
This works for me to figure out if a vm exists or not: 

```
    - name: Check if vm exists
      community.general.proxmox_kvm:     
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ proxmoxnode }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmoxnode }}"
        vmid: "{{ vmid }}"
      register: status


    - name: Info vm exists
      ansible.builtin.debug:
        msg: "VM-ID found, updating existing VM"
      when: '" exists" in status.msg'   

    - name: Info vm not found 
      ansible.builtin.debug:
        msg: "VM-ID not found, creating new one"
      when: '"exists" not in status.msg'   
```

**Comment by Vanav** [comment]
@tovoro Maybe it works only if VMID is known? In my case, if "name" is known, I got fatal error.

**Comment by peschmae** [comment]
To be able to check if a VM exists, using the currently implementation (using the VM name), you'll need to set `failed_when: false` on the initial task where you just fetch the status.

This is taken directly from my playbooks and works using VM names

```
- name: "get current vm state"
      community.general.proxmox_kvm:
        api_user: "{{ api_user}}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        name: "{{ inventory_hostname }}"
        node: "{{ proxmox_node }}"
        state: current
      register: vm_state
      check_mode: false
      failed_when: false

    - name: show  vm state
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is {{ vm_state.status }}"
      when:
        - "'status' in vm_state"

    - name: VM must be created
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} will be created"
      when:
        - "'status' not in vm_state"
```

Having an `_info` module would still be nice

**Comment by UnderGreen** [comment]
@Vanav, @tovoro, @peschmae 
Done via #6852. Let me know if the new module fits your needs.

**Comment by drewburr** [comment]
Hey @UnderGreen, I noticed that `proxmox_vm_info` requires `node: ` to function, but the Proxmox API does not require this value to retrieve VM configuration if we first call `/api2/json/cluster/resources`. 

I also feel that one of the major values of having a `proxmox_vm_info` is that it could be used to retrieve an unknown VM ID. Is this something we could consider adding to the module?

**Comment by UnderGreen** [comment]
@drewburr, with that module you can retrieve all machines on node and filter them in your playbook. I used those api endpoints to also retrieve extra info, like vm config, which is not available via resources. I will update module to use resources endpoint soon. That makes sense, for sure.

**Comment by UnderGreen** [comment]
@drewburr fixed in https://github.com/ansible-collections/community.general/pull/6976

**Comment by Vanav** [comment]
> Done via #6852. Let me know if the new module fits your needs.

@UnderGreen, I've tried to use new module to check existence of VM, but if VM doesn't exist I got fatal error. So seems not much different from my original way. I think, there should be no fatal error, just an empty list. For example, [ansible.builtin.stat](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html) doesn't return fatal error if file doesn't exist.

Test:
```
- name: Check if VM exists
  community.general.proxmox_vm_info:
    api_host: proxmox.example.com:443
    api_user: root@pam
    api_token_id: Terraform
    api_token_secret: xxx

    node: MyHost
    name: Ubuntu-22.04
  delegate_to: localhost
  register: check_vm_reg
```
Result:
```
PLAY [Proxmox VM] ***

TASK [proxmox-env : Check if VM exists] ***
task path: /srv/Projects/my-servers/roles/proxmox-env/tasks/main.yml:1
fatal: [ubuntu_22_04_node -> localhost]: FAILED! => 
    changed: false
    msg: No VM with name Ubuntu-22.04 found

NO MORE HOSTS LEFT ***

PLAY RECAP ***
ubuntu_22_04_node          : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
