### ISSUE TITLE
Gem: Force is not working when uninstalling

### ISSUE THREAD

**Issue by juan-vg** [ansible-collections/community.general#5821]
### Summary

Force flag is not being appended when uninstalling, which could lead to a hang because gem could interactively ask if the user is sure to uninstall when there are dependencies

### Issue Type

Bug Report

### Component Name

gem

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.6]
  [...]
  python version = 3.11.0 (main, Oct 25 2022, 13:57:33) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /Users/admin/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.6.0  

# /opt/homebrew/Cellar/ansible/6.6.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0
```

### Configuration

Not relevant

### OS / Environment

Not relevant

### Steps to Reproduce

```yaml (paste below)
- name: Uninstall fastlane gem
  community.general.gem:
    name: fastlane
    state: absent
    force: true
    user_install: no
```

### Expected Results

The `--force` flag should be appended to the `gem uninstall` command

### Actual Results

The `--force` flag is not being appended to the `gem uninstall` command

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
