### ISSUE TITLE
Add support to Bitwarden Lookup for filtering results by collection id

### ISSUE THREAD

**Issue by psalkowski** [ansible-collections/community.general#5849]
### Summary

Bitwarden allow to use collections for storing data. In some cases, to simplify CI/CD process with ansible, users may setup collections per environment (like dev, staging, production). They will use the same names for vault items, but stores in different collections. At the end, in CI/CD you can setup one ENV variable that mention the collection id and pass it to ansible. Otherwise, you will have to have unique vault item names.

Of course collection id should be optional.

### Issue Type

Feature Idea

### Component Name

lookup/bitwarden

### Additional Information

```yaml
- name: "Get 'password' from Bitwarden record named 'a_test' from collection "
  ansible.builtin.debug:
    msg: >-
      {{ lookup('community.general.bitwarden', 'a_test', field='password', collectionId='bafba515-af11-47e6-abe3-af1200cd18b2') }}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
