### ISSUE TITLE
groupby_as_dict: support json path/nested dicts as key

### ISSUE THREAD

**Issue by azrdev** [ansible-collections/community.general#5862]
### Summary

I want to replace `registered_uri_looped.results | groupby('json.somekey')` with groupby_as_dict, where groupby supports selecting a key in a nested dict (`json`) but groupby_as_dict does not, with the error `Attribute not contained in element #0 of sequence`

### Issue Type

Feature Idea

### Component Name

groupby_as_dict

### Additional Information

```yaml
---
- hosts: all
  gather_facts: false
  vars:
    rul:
      results:
        - rc: 0
          json:
            key: v1
        - rc: 0
          json:
            key: v2
  tasks:
    # - uri:
    #     ...
    #   loop: [...]
    #   register: rul

    - debug:
        msg: "{{ rul.results | groupby('json.key') }}"

    - debug:
        msg: "{{ rul.results | community.general.groupby_as_dict('json.key') }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
