### ISSUE TITLE
is there any way to let xml use default namespaces inside the documents?

### ISSUE THREAD

**Issue by braindevices** [ansible-collections/community.general#5864]
### Summary

example file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Testdoc xmlns:ns1="http://example.com/ns1.xsd" xmlns:ns2="http://example.com/ns2.xsd">
    <Prop id="Wi-Fi">
        <ns1:Position x="0.0" y="0.0" z="0.0"/>
        <ns2:Orientation roll="0.0" pitch="0.0" yaw="0.0"/>
    </Prop>
</Testdoc>

```

I would like to be able to run xml module with the default namespaces instead of filling the namespaces value explicitly. Because the values can change in any time. It should depend on the file itself.

If you have a way to obtain the namespaces easily that will do too. But so far I cannot find that tool.

I attached a patch that could work already. If that is fine I can try to make a PR.

### Issue Type

Feature Idea

### Component Name

xml

### Additional Information

```yaml (paste below)
- set_fact:
    example: |
      <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <Testdoc xmlns:ns1="http://example.com/ns1.xsd" xmlns:ns2="http://example.com/ns2.xsd">
          <Prop id="Wi-Fi">
              <ns1:Position x="0.0" y="0.0" z="0.0"/>
              <ns2:Orientation roll="0.0" pitch="0.0" yaw="0.0"/>
          </Prop>
      </Testdoc>

- name: get attributes
  xml:
    xmlstring: "{{ example }}"
    xpath: '//ns2:Orientation'
    namespaces:
      ns2: http://example.com/ns3.xsd
    content: attribute
  register: magic_res

- debug:
    var: magic_res.matches
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
