### ISSUE TITLE
Not able configure hostname in redfish

### ISSUE THREAD

**Issue by kotireddy478** [ansible-collections/community.general#5892]
### Summary

Hi,

I'm trying to configure ilo hostname using redfish config in https://github.com/HewlettPackard/ilo-ansible-collection/blob/main/roles/playbooks/Manager/config_hostname.yml but i'm getting below error. Could you please help?

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'ret'
fatal: [host_name]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1674659669.5978777-8741-211049437950632/AnsiballZ_redfish_config.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1674659669.5978777-8741-211049437950632/AnsiballZ_redfish_config.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-tmp-1674659669.5978777-8741-211049437950632/AnsiballZ_redfish_config.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_community.general.redfish_config_payload_ob0p90/ansible_community.general.redfish_config_payload.zip/ansible_collections/community/general/plugins/modules/redfish_config.py\", line 389, in <module>\n  File \"/tmp/ansible_community.general.redfish_config_payload_ob0p90/ansible_community.general.redfish_config_payload.zip/ansible_collections/community/general/plugins/modules/redfish_config.py\", line 379, in main\nKeyError: 'ret'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

Thanks

### Issue Type

Bug Report

### Component Name

community.general.redfish_config

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.12] 

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 4.8.1  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

CentOS 7

### Steps to Reproduce

```yaml (paste below)
 https://github.com/HewlettPackard/ilo-ansible-collection/blob/main/roles/playbooks/Manager/config_hostname.yml 

```

### Expected Results

I expected hostname removed to passed var

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/redfish_config.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/redfish_config.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bhavya06 @mraineri @rajeevkallur @renxulei @tomasg2012 @xmadsen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mraineri** [comment]
Running the same request with a stripped down playbook seems to work okay for me. Will need to experiment with your exact playbook.

I also see you're using an older version of the module; would you be able to try the latest version (6.2)?

Here's my reduced playbook for reference:

```
---
- hosts: all
  gather_facts: false
  vars:
    username: <REDACTED>
    password: <REDACTED>
    baseuri: <REDACTED>
    default_uri_timeout: 40
    default_uri_retries: 5
    attribute_value: <REDACTED>
  tasks:
  - name: Set Manager NIC
    community.general.redfish_config:
      category: Manager
      command: SetManagerNic
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      nic_config:
        HostName: "{{ attribute_value }}"
    retries: "{{ default_uri_retries }}"
    timeout: "{{ default_uri_timeout }}"
    register: redfish_results
  - debug:
      var: redfish_results
```

**Comment by mraineri** [comment]
Downgraded on my end to 4.8.1 and the above playbook still works... Will keep digging...

**Comment by mraineri** [comment]
Still not recreating the issue with this playbook:

```
---
- hosts: all
  name: Configure HostName
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    - attribute_name: HostName
    - attribute_value: <REDACTED>
    - username: <REDACTED>
    - password: <REDACTED>
    - baseuri: <REDACTED>

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Set Manager NIC
      community.general.redfish_config:
        category: Manager
        command: SetManagerNic
        nic_config:
          HostName: "{{ attribute_value }}"
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
```
