### ISSUE TITLE
Cloudflare DNS CAA record capabilities

### ISSUE THREAD

**Issue by iamsilvio** [ansible-collections/community.general#5910]
### Summary

The Cloudflare API supports CAA records which is not yet supported by the module

### Issue Type

Feature Idea

### Component Name

community.general.cloudflare_dns

### Additional Information

```yaml (paste below)
- name: Configure CAA DNS {{ uri }}
  community.general.cloudflare_dns:
    api_token: "{{ cloudflare_api_token}}"
    zone: "{{ uri }}"
    record: "{{ uri }}"
    type: CAA
    value: letsencrypt.org
    caa_tag: issue
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
