### ISSUE TITLE
archive exclude_path doesn't work

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.general#593]
_From @mdavis-xyz on Jun 27, 2020 06:24_

##### SUMMARY

Yes I know this module is probably maintained in some other repo.
But I don't know how to figure out what other repo it's in.
Please tell me how to figure out where to report this issue.

The issue is that the `exclude_path` parameter to the `archive` module is ignored.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

archive

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /home/ec2-user/.ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.10 (default, Feb 10 2020, 19:55:14) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/ec2-user/.ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/ec2-user/.ansible.cfg) = /dev/shm/ansible/tmp_local/ansible-local-4551timoym04
```

##### OS / ENVIRONMENT

Amazon Linux.

```
$ tar --version
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

```
$ zip --version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.

...

Compiled with gcc 4.4.4 20100726 (Red Hat 4.4.4-13) for Unix (Linux ELF) on Jan 15 2011.

Zip special compilation options:
        USE_EF_UT_TIME       (store Universal Time)
        SYMLINK_SUPPORT      (symbolic links supported)
        LARGE_FILE_SUPPORT   (can read and write large files on file system)
        ZIP64_SUPPORT        (use Zip64 to store large files in archives)
        UNICODE_SUPPORT      (store and read UTF-8 Unicode paths)
        STORE_UNIX_UIDs_GIDs (store UID/GID sizes/values using new extra field)
        UIDGID_NOT_16BIT     (old Unix 16-bit UID/GID extra field not used)
        [encryption, version 2.91 of 05 Jan 2007] (modified for Zip 3)
...

Zip environment options:
             ZIP:  [none]
          ZIPOPT:  [none]
```

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  vars:
    src: "/tmp/src"
    archive: "/tmp/data.tgz"
    unwanted: "unwanted" # folder relative to src or dest
    dest: "/tmp/dest"

  tasks:
    - name: start with clean slate
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - "{{ src }}"
      - "{{ dest }}"
      - "{{ archive }}"
        
    - name: create folders
      file:
        path: "{{ src }}/{{ unwanted }}"
        state: directory
        
    - name: create data to compress
      copy:
        dest: "{{ item['path'] }}"
        content: "{{ item['content'] }}"
      with_items:
        - path: "{{ src }}/{{unwanted}}/discard.txt"
          content: I don't want this file
        - path: "{{ src }}/keep.txt"
          content: I want this file
          
    - name: compress files
      archive:
        path: "{{ src }}/"
        dest: "{{ archive }}"
        exclude_path:
        # no idea what to include here
        # so I'm just trying everything
        - "discard.txt"
        - "*.discard.txt"
        - "{{ src }}/{{ unwanted }}/discard.txt"
        - "{{ unwanted }}/discard.txt"
        - "*/*/discard.txt"
        - "**discard.txt"
      register: compress
        
    - name: print excluded files
      debug:
        var: compress.expanded_exclude_paths
        
    - name: create target for decompression
      file:
        path: "{{ dest }}"
        state: directory
        
    - name: decompress files
      unarchive:
        src: "{{ archive }}"
        dest: "{{ dest }}"
        
    - name: check excluded file is excluded
      vars:
        path: "{{ dest }}/{{ unwanted }}/discard.txt"
      assert:
        that:
        - path is not exists
        - (compress.expanded_exclude_paths | length) > 0
    
        
    - name: check included file is included
      vars:
        path: "{{ dest }}/keep.txt"
      assert:
        that:
        - path is exists
```

##### EXPECTED RESULTS

Playbook should run without error.

##### ACTUAL RESULTS

The first assertion task fails.

The `archive` task has included all files within the path, even when matched by `exclude_paths`.

The debug task shows that the `archive` module *thinks* it's excluded the file.

```
    "compress.expanded_exclude_paths": [
        "discard.txt",
        "/tmp/src/unwanted/discard.txt",
        "unwanted/discard.txt"
    ]
```

_Copied from original issue: ansible/ansible#70341_

**Comment by rosowiecki** [comment]
As weird as it looks, it's a FAD

Look ad the `expanded_paths` key in compress.results, it conains only one path: /tmp/src/ which doesn't match any of your exclude statements. 
```
 "expanded_exclude_paths": ["discard.txt", "/tmp/src/unwanted/discard.txt", "unwanted/discard.txt"], 
"expanded_paths": ["/tmp/src/"], 
```


`exclude_path` option is not matched against every possible file under `path` list, but only removes items selected by applying glob search to `patch`.

Try: path: "{{ src }}/*.txt" or path: "{{src}}/*"  exclude_path = [ /tmp/src/unwanted ].

**Comment by ansibullbot** [comment]
cc @bendoh
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rosowiecki** [comment]
This is a documentation issue: `exclude_path` description promises more that actually does.

**Comment by rosowiecki** [comment]
Anyway: why don't we machi files agains exclusion in this loop? https://github.com/ansible-collections/community.general/blob/a7a74a6eb7d9a6d5fb7b4fd018227373a82befab/plugins/modules/files/archive.py#L385

Maybe exclude_path behaviour reported in this issue comes from some earlier version of the module which relied on calling tar/zip programs instead of using tarfile/zipfile modules?

**Comment by rosowiecki** [comment]
notabug

A way to exclude particular files from archive would be nice though, @mdavis-xyz -- submit a separate request for new param (lest's call it `ecxlude_files`) to exclude files from actual archive contents, not only from the `path` list.

**Comment by mdavis-xyz** [comment]
@rosowiecki , what does FAD mean?

I'm afraid your PR and comments have not made anything clearer to me.

As far as I can tell, the behavior described by the examples in the documentation does not match how the module actually works. Therefore it is a bug.

In [the docs](https://docs.ansible.com/ansible/latest/modules/archive_module.html#archive-module):

```
- name: Create a bz2 archive of a globbed path, while excluding specific dirnames
  archive:
    path:
    - /path/to/foo/*
    dest: /path/file.tar.bz2
    exclude_path:
    - /path/to/foo/bar
    - /path/to/foo/baz
    format: bz2

- name: Create a bz2 archive of a globbed path, while excluding a glob of dirnames
  archive:
    path:
    - /path/to/foo/*
    dest: /path/file.tar.bz2
    exclude_path:
    - /path/to/foo/ba*
    format: bz2
```
What's the difference between that example, and replacing `exclude_path` in my example with `{{ src }}/{{ unwanted }}` (which causes the assertion to fail)?

**Comment by mdavis-xyz** [comment]
> Try: path: "{{ src }}/*.txt"

Hmm, yes adding `*` to the `path` does work.

```
    - name: compress files
      archive:
        path: "{{ src }}/*"
        dest: "{{ archive }}"
        exclude_path:
                - /tmp/src/unwanted
      register: compress
```

Please document the different between:

* `path: mydir`
* `path: mydir/`
* `path: mydir/*`

Because I would expect all of those to behave identically, but they don't.

**Comment by mdavis-xyz** [comment]
Similarly, please document what happens with `dest: other_dir` vs `dest: other_dir/`

**Comment by rosowiecki** [comment]
The difference is: `/path/to/foo/*` glob pattern is expanded to list of files/directories under `foo`. This list is then filtered by `exclude_path` and everything that is on exclude_path list is removed from path. They key is that this operation is done on lists, not on actual files. You didn't use any glob pattern, so your path list is only `[ /tmp/src/ ]`, which means: archive this directory.

I don't think this behaviour is a bug (it's not intuitive, but I've seen similar weirdness in of include/exclude clauses in backup software), but even if we could agree upon that, it shouldn't be fixed the way you want it. I personally have a dreadful suspition someone out there is using archive module for backup and will lost important data when `exclude_path` suddenly starts working in different way.

**Comment by rosowiecki** [comment]
> Please document the different between:
I'm sorry I don't think it is possible to do that in such way that is both informative and *short*. Glob pattern matching makes such a long and exciting story, explaining only those examples in path and exclude_path documentation wouldn't be any good in my opinion.

**Comment by rosowiecki** [comment]
> what does FAD mean?

Oh, I haven't noticed that question: Functions As Design.

**Comment by mdavis-xyz** [comment]
How about these changes to the documentation:

# Change 1

Existing example:

```
- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  archive:
    path: /path/to/foo
    dest: /path/to/foo.tgz
```

Replace with:

```
# The top level of the contents of foo.tgz will contain a folder called foo
- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  archive:
    path: /path/to/foo
    dest: /path/to/foo.tgz

# the top level of the contents of foo.tgz will contain the files and subdirectories of foo
- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  archive:
    path: /path/to/foo/
    dest: /path/to/foo.tgz
```

# Change 2

For each of the `exclude_path` examples, add a comment to `path` saying `# Must be a glob` (or is it 'should be a glob'?)

# Change 3

Append to explanation of `expanded_exclude_paths` to add:

> Does not necessarily equal a list of all the files which have been excluded.

# Change 4

Modify documentation for `exclude_path` to say that it only works if the `path` is a glob. (Is that true? I can't find a situation where it isn't).

**Comment by rosowiecki** [comment]
Change2, Change4: No, both `path` and `exclude_path` may contain globs and paths. Actually there's a little difference between them, because one may see a fixed path as a special case of glob pattern which does not contain any special signs and expands only to itself. So you may add certain fixed (not glob) item to `path` and exclude it from `exclude_path`, which doesn't seem to make much sense if they are just defined in playbook, but I imagine that someone defines some general role with variables like _my_paths_  and _my_exclude_paths_ in defaults or group_vars and my_exclude_paths may be redefined in host_vars to exclude certain paths on some hosts.

Change3:
In my PR it changed: "Remote absolute path, glob, or list of paths or globs for the file or files to exclude from I(path) list and glob expansion." After the change it emphasizes that exclude_path actually modifies list of paths defined in path, but not the archive itself. 

I think most surprising result is when path conains a directory and exclude_path contains a item (file or subdirectory) in it, in which case whole directory will be archived anyway. Vice versa: when /path/to/some/directory/included is in `path` and `/path/to/some/directory` is in `exclude_path`, the included directory will be in the result archive (Again: because it operates only on path list, not on filesystem contents). Adding such example do docs or examples would be nice, I suppose.


Change1:
I think the only difference in between /path/to/foo and /path/to/foo/ if when foo is a file (not a directory); then in you first example foo.tgz will conain single file and second one fill fail with error. When foo is a directory the result of you both examples will be the same. But I'll check that to be sure.

**Comment by mdavis-xyz** [comment]
Honestly the more of these comments I read, the more confused I get.

That "surprising result" seems to me to be exactly the opposite of how things should work.

And I still don't understand what you mean when you say exclude_path modifies the path but not the archive. The purpose of the task is to create/modify an archive. If exclude_path doesn't affect the archive then doesnt that make it useless?

**Comment by rosowiecki** [comment]
I agree that exclude_path is very limitted, but the best we can do is precisely document about how it works, which due to nature of glob patterns and way it works seems to be harder than expected :/ Most useful way to use exclude_path is indeed: only to limit glob patterns (*?) of items in `path` like: `path= [ /somedir/* ]`, exclude_path = [/somedir/not_this_one]` and according to original commit https://github.com/ansible/ansible/commit/f65f3570a842608d9e355881ad83d8488690b0da  it was only meant to work this way.

As an additional method to close this issue up I propose: add a featrure request for `exclude_files` and even `exclude_regex` additional options which will give more control in a way @mdavis-xyz  expected and won't break backward compatibility.

**Comment by rosowiecki** [comment]
Another suggested improvement: Warning if `exclude_path` contains something that is not preset on `path`.

**Comment by rapekas** [comment]
Just for someone who will search an approach how to archive two folders excluding some subfolders with Ansible at once. I tried many attempts before found a solution.

For instance, I have a Tomcat application and I would like to backup some folders:
```ruby
{{ catalina_home }}/webapps/app
{{ catalina_home }}/webapps/app-mobile
{{ catalina_home }}/webapps/app-portal
```
excluding these subfolders:
```ruby
{{ catalina_home }}/webapps/app/static
{{ catalina_home }}/webapps/app/META-INF
{{ catalina_home }}/webapps/app-mobile/META-INF
{{ catalina_home }}/webapps/app-portal/META-INF
```

One of the solution is putting proper `*` and removing ending slash `/` both at `path` and `exclude_path`.

```ruby
    - name: backup app
      archive:
        remote_src: yes
        remove: no
        format: zip
        path:
        - "{{ catalina_home }}/webapps/app*/*"
        dest: "{{ backup_folder }}/{{ inventory_hostname }}-{{ ansible_date_time.time }}-app.zip"
        exclude_path:
        - "{{ catalina_home }}/webapps/app/static"
        - "{{ catalina_home }}/webapps/app*/META-INF"
      no_log: yes
```

**Comment by elburro1887** [comment]
So after spending hours on this i finally figured out that it is impossible to exclude directories that are below the 1st level.

I would like to exclude the `subdir3/subsubdir4`

First try:

```
 - name: Create backup of files/directories - TEST
      community.general.archive:
        path: 
          - "/home/user/foldertobackup/*"
        dest: "/home/user/backup/myarchive.gz"
        format: gz
        mode: 0644
        exclude_path: 
          - "/home/user/foldertobackup/log"
          - "/home/user/foldertobackup/sql"
          - "/home/user/foldertobackup/subdir3/subsubdir4"
```

But the path `/home/user/foldertobackup/subdir3/subsubdir4` is not expanded in the `expanded_paths` list so it cannot be removed.



Second try, i specifically add the `subdir3` to the `path` list

```
 - name: Create backup of files/directories - TEST
      community.general.archive:
        path: 
          - "/home/user/foldertobackup/*"
          - "/home/user/foldertobackup/subdir3/*"
        dest: "/home/user/backup/myarchive.gz"
        format: gz
        mode: 0644
        exclude_path: 
          - "/home/user/foldertobackup/log"
          - "/home/user/foldertobackup/sql"
          - "/home/user/foldertobackup/subdir3/subsubdir4"
```

Doesn't work, since even though the `path` list doesn't contain the subdirectory after the "subtraction" this path is then added to the archiving command. So we will walk the whole path again and reinclude the mentioned subdirectory and its contents.

In my opinion this is a bug, because users would of course want to remove files and folders that are below the 2nd level.

I have added a new issue #6857

**Comment by elburro1887** [comment]
I was beating my head against the wall whilst using `exclude_path` again, so I tried it with `exclusion_patterns` and somehow figured out how it works. 

In case this could help anyone, here is a working example.

### Test folder contents
````
/home/myuser/services/jenkins/test.txt
/home/myuser/services/jenkins/jenkins_data/workspace/file1.txt
/home/myuser/services/jenkins/jenkins_data/workspace/file2.txt
/home/myuser/services/jenkins/jenkins_data/jobs/myjob1/test1.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob1/test2.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob1/build/test.zip
/home/myuser/services/jenkins/jenkins_data/jobs/myjob2/test3.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob2/test4.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob2/build/test2.zip
````

We want to remove the `workspace` folder, and any `build` folder that is nested in the subfolders of `jobs`.

### Resulting archived files
````
/home/myuser/services/jenkins/test.txt
/home/myuser/services/jenkins/jenkins_data/jobs/myjob1/test1.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob1/test2.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob2/test3.xml
/home/myuser/services/jenkins/jenkins_data/jobs/myjob2/test4.xml
````


### Ansible Task
````
  tasks:
    - name: Create archive
      community.general.archive:
        path:
          - "/home/myuser/services/jenkins/*"
        dest: "/home/myuser/backup/jenkins.tar.gz"
        format: gz
        exclusion_patterns:
          - "jenkins_data/workspace*"
          - "jenkins_data/jobs/*/builds*"
````

### Notes
`exclusion_patterns` are given relative to the root of the archive. 

  - `jenkins_data/workspace*` will remove the `workspace` folder and its contents, but also a file that could be called `jenkins_data/workspace1.zip` for example
  - `jenkins_data/workspace/*` will keep the `workspace` folder, but the folder itself will be empty
  -  `jenkins_data/jobs/*/builds*` This style can be used to just remove only specific subdirectories inside a folder
