### ISSUE TITLE
community.mongodb.mongodb_replicaset unable to update priority

### ISSUE THREAD

**Issue by paulsjohnson91** [ansible-collections/community.general#5936]
### Summary

I've been trying this on a full best practice mongo cluster but to simplify I've built a simple docker-compose 3 mongo node set with  

```
version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
    networks:
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    container_name: mongo2
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongo-network:
    driver: bridge
```

On this set I ran the playbook

```
---
  - name: "Create Replicaset"
    hosts: localhost
    connection: local 
    tasks:
      - name: "create replica set"
        community.mongodb.mongodb_replicaset:
          login_host: localhost
          login_port: 27017
          replica_set: dbrs
          members:
          - host: "mongo1:27017"
            priority: 4
          - host: "mongo2:27017"
            priority: 2
          - host: "mongo3:27017"
            priority: 1
```

I confirmed that the replicaset was created successfully then ran the following playbook
```
---
  - name: "Create Replicaset"
    hosts: localhost
    connection: local 
    tasks:
      - name: "update replica set"
        community.mongodb.mongodb_replicaset:
          login_host: localhost
          login_port: 27017
          force: yes
          reconfigure: yes
          replica_set: dbrs
          members:
          - host: "mongo1:27017"
            priority: 4
          - host: "mongo2:27017"
            priority: 3
          - host: "mongo3:27017"
            priority: 1
```

This ran successfully with the debug log
```
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "arbiter_at_index": null,
            "auth_mechanism": null,
            "chaining_allowed": true,
            "cluster_cmd": "hello",
            "connection_options": null,
            "debug": false,
            "election_timeout_millis": 10000,
            "force": true,
            "heartbeat_timeout_secs": 10,
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": null,
            "login_port": 27017,
            "login_user": null,
            "max_time_ms": null,
            "members": [
                {
                    "host": "mongo1:27017",
                    "priority": 4
                },
                {
                    "host": "mongo2:27017",
                    "priority": 3
                },
                {
                    "host": "mongo3:27017",
                    "priority": 1
                }
            ],
            "protocol_version": 1,
            "reconfigure": true,
            "replica_set": "dbrs",
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "strict_compatibility": true,
            "validate": true
        }
    },
    "replica_set": "dbrs"
}
```

Unfortunately running rs.config on the primary shows that the priority of the secondary wasn't updated.

### Issue Type

Bug Report

### Component Name

mongodb_replicaset 

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.7
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 5.7.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Tested on OSX and ubuntu

### Steps to Reproduce

```yaml (paste below)
See summary above
```

### Expected Results

secondary priority changed to 3 from 2

### Actual Results

```console (paste below)
No changes to rs.config()
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
