### ISSUE TITLE
Add ProxyJump option to ssh_config

### ISSUE THREAD

**Issue by Bustel** [ansible-collections/community.general#5970]
### Summary

The ssh_config module is missing the `ProxyJump` option. This limitation can be worked-around by using the ProxyCommand but this feels very unnecessarily cumbersome.

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

Instead of specifying:

```
- name: Add a host in the configuration
  community.general.ssh_config:
    user: akasurde
    host: "example.com"
    hostname: "github.com"
    identity_file: "/home/akasurde/.ssh/id_rsa"
    port: '2223'
    state: present
    proxycommand: "ssh -W %h:%p -q username@bastionhost.com"
```
this could be simplified to:

```
- name: Add a host in the configuration
  community.general.ssh_config:
    user: akasurde
    host: "example.com"
    hostname: "github.com"
    identity_file: "/home/akasurde/.ssh/id_rsa"
    port: '2223'
    state: present
    proxyjump: "username@bastionhost.com"
````
or potentially even a list of jump hosts:

````
```
- name: Add a host in the configuration
  community.general.ssh_config:
    user: akasurde
    host: "example.com"
    hostname: "github.com"
    identity_file: "/home/akasurde/.ssh/id_rsa"
    port: '2223'
    state: present
    proxyjump: 
       - "username@bastion1.com"
       - "username@bastion2.com"
```` 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
