### ISSUE TITLE
support for new gitlab api features

### ISSUE THREAD

**Issue by zhemant** [ansible-collections/community.general#5985]
### Summary

Gitlab API has new features added to support enabling/disabling/access control some parts of git repository, they are as follows:

- `releases_access_level`: to control the visibility of  `release tab` in web-ui
- `environments_access_level`: to control the visibility of `environment tab` in web-ui
- `feature_flags_access_level`: to control the visibility of `feature tab` in web-ui
- `infrastructure_access_level`: to control the visibility of `infrastructure tab` in web-ui
- `monitor_access_level`: to control the visibility of `monitoring tab` in web-ui
- `security_and_compliance_access_level`:  to control the visibility of `security and compliance tab` in web-ui

### Issue Type

Feature Idea

### Component Name

gitlab_project

### Additional Information
Example of project creation using new fields

```yaml (paste below)
- name: Setup gitlab project
  community.general.gitlab_project:
    api_url: https://gitlab.example.com/
    validate_certs: true
    api_username: dj-wasabi
    api_password: "MySecretPassword"
    name: my_project
    group: ansible
    releases_access_level: enabled
    environments_access_level: disabled
    feature_flags_access_level: disabled
    infrastructure_access_level: disabled
    monitor_access_level: disabled
    security_and_compliance_access_level: disabled
    state: present
  delegate_to: localhost
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
