### ISSUE TITLE
community.general.gitlab_branch: add option default (branch)

### ISSUE THREAD

**Issue by staehler** [ansible-collections/community.general#5995]
### Summary

Is it feasable to add the option `default: true/false`, so this branch would be either the default branch or not?

### Issue Type

Feature Idea

### Component Name

community.general.gitlab_branch

### Additional Information

```yaml (paste below)
- name: Create branch branch2 from main
  community.general.gitlab_branch:
    api_url: https://gitlab.com
    api_token: secret_access_token
    project: "group1/project1"
    branch: branch2
    ref_branch: main
    state: present
    default: true

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
