### ISSUE TITLE
gitlab_user: msg: User is not blocked or does not exists

### ISSUE THREAD

**Issue by staehler** [ansible-collections/community.general#5999]
### Summary

I try do unblock a blocked user, but get this message:  
`msg: User is not blocked or does not exists`

The user already exists in gitlab and is blocked. The username also exists. I have no idea, what I'm doing wrong.

### Issue Type

Bug Report

### Component Name

community.general.gitlab_user

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.10]
  config file = ../ansible.cfg
  configured module search path = ['../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ../ansible5.10.0/lib64/python3.8/site-packages/ansible
  ansible collection location = ../collections
  executable location = ../ansible5.10.0/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/../ansible5.10.0/lib64/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.3  

# /home/../ansible5.10.0/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.3  

# /home/../../collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.3.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Rhel 8

### Steps to Reproduce

```yaml (paste below)
  - name: 40_add_remove_user | unblock user {{ gitlab_user.name }}
    community.general.gitlab_user:
      api_url: https://{{ gitlab_api_url }}
      api_token: "{{ gitlab_api_token }}"
      validate_certs: true
      username: "{{ gitlab_user.username }}"
      state: unblocked
```

### Expected Results

User is unblocked

### Actual Results

```console (paste below)
TASK [gitlab_projects : 40_add_remove_user | unblock user xxx] ***********************************************************************************************************************
ok: [localhost]

TASK [gitlab_projects : debug] *****************************************************************************************************************************************************************************
ok: [localhost] => 
  unblocked:
    changed: false
    failed: false
    msg: User is not blocked or does not exists
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
