### ISSUE TITLE
[Keycloak] Identity Provider unchanged mappers are deleted

### ISSUE THREAD

**Issue by ymazzer** [ansible-collections/community.general#6002]
### Summary

When updating an IdP with a deterministic list of mappers, unchanged mappers are deleted because no changes are detected.

### Issue Type

Bug Report

### Component Name

keycloak_identity_provider

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.2]
  config file = [...]/ansible.cfg
  configured module search path = ['[...]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = [...]/venv/lib/python3.10/site-packages/ansible
  ansible collection location =[...]/{{ ANSIBLE_HOME ~ "/collections" }}
  executable location = [...]/venv/bin/ansible
  python version = 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] ([...]/venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 6.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

Given email is already created and given_name is to be created, here is an example mappers attribute for keycloak_identity_provider module:
```yaml (paste below)
    mappers:
    - name: email
      identityProviderMapper: oidc-user-attribute-idp-mapper
      config:
        claim: email
        user.attribute: email
        syncMode: FORCE
    - name: first_name
      identityProviderMapper: oidc-user-attribute-idp-mapper
      config:
        claim: given_name
        user.attribute: firstName
        syncMode: FORCE
```

### Expected Results

All mappers are present in Keycloak IdP if only one exists

### Actual Results

Existing mapper is deleted 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
