### ISSUE TITLE
opkg update_cache not working after ansible update

### ISSUE THREAD

**Issue by garar** [ansible-collections/community.general#6004]
### Summary

Hi!

It seems that some recent updates to `opkg` command broke `update_cache`.

When I set `update_cache: true` ansible returns an error. Switch to `update_cache: false` fixes the issue.

Installing `community.general:==6.2.0` fixed the issue.

### Issue Type

Bug Report

### Component Name

community.general.opkg

### Ansible Version

```console (paste below)
ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/garar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/garar/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.3.0  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 22.04 and OpenWrt 21.02.3

### Steps to Reproduce

```yaml
---
- name: Base tasks for openwrt
  hosts: openwrt
  tasks:
    - name: Install vim
      opkg:
        name:
          - vim-fuller
        state: present
        update_cache: true

```

### Expected Results

Ansible should update opkg cache and install vim-fullter.

### Actual Results

Log too long, please see here: https://gist.github.com/garar/9f71392a682f8f16f2645c0dbee091cc

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
