### ISSUE TITLE
Return more information (e.g. uid / username) for processes in the pid module

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/community.general#6029]
### Summary

I need to notify the user of a running process about something.  It would be helpful if the pid module could return more detailed information about the processes it finds.

### Issue Type

Feature Idea

### Component Name

pids

### Additional Information

```yaml (paste below)
  - name: "Linux: See if firefox is running"
    community.general.pids:
      name: firefox
    register: firefox_pids

 - name: "Notify users"
   community.general.mail:
     to: "{{ item.user }}"
   loop: "{{ firefox_pids.pid_details }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
