### ISSUE TITLE
ldap_attrs: #5450 breaks OpenLDAP config

### ISSUE THREAD

**Issue by martin-kuba** [ansible-collections/community.general#6045]
### Summary

The merged PR #5450 has broken adding new databases in OpenLDAP's cn=config database using Ansible. 

The PR was meant to allow to omit the {X} indexes, which it does, unfortunatelly when multliple databases are configured, they all have the same DN just with different {X}, and the ldap_entry module incorrectly says that the entry already exists when it does not.

This happens for example when replication is configured. Then there should be two databases:
```
olcDatabase={1}mdb,cn=config
olcDatabase={2}mdb,cn=config
``` 
The second database `olcDatabase={2}mdb,cn=config` cannot be now created using Ansible ldap_entry module, because it wrongly finds the `olcDatabase={1}mdb,cn=config` that exists and does not create the second entry.

The problem is caused by the change from 
```python
    self.dn = self.module.params['dn']
```
to
```python
    # Try to find the X_ORDERed version of the DN
    self.dn = self._find_dn()
```
in LdapGeneric init method in the commit https://github.com/ansible-collections/community.general/commit/ee39fd5c90ea07980bd9f9cc50d6be9da7ab82a4 .

I suggest to add a new config option for enabling or disabling this smart behavior.

### Issue Type

Bug Report

### Component Name

plugins/module_utils/ldap.py

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/makub/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/makub/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.3.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

```

### Steps to Reproduce

Install a vanilla OpenLDAP server, e.g. on Debian Linux:
```console
# apt install slapd
```
then try to execute the following playbook. It will say that the entry exists even if it does not exist.

```yaml (paste below)
- name: "show Ansible wrongly detecting LDAP entry existence"
  hosts: all
  remote_user: root
  vars:
    ldap_basedn: "dc=example,dc=org"
  tasks:
    - name: "accesslog database"
      ldap_entry:
        dn: "olcDatabase={2}mdb,cn=config"
        objectClass:
          - olcDatabaseConfig
          - olcMdbConfig
        attributes:
          olcDatabase: '{2}mdb'
          olcDbDirectory: /var/lib/ldap/accesslog
          olcSuffix: cn=accesslog
          olcAccess: '{0}to dn.subtree="cn=accesslog" by dn.exact="cn=replication,{{ ldap_basedn }}" read'
          olcLastMod: 'TRUE'
          olcMaxDerefDepth: 15
          olcReadOnly: 'FALSE'
          olcLimits: 'dn.exact="cn=replication,{{ ldap_basedn }}" time=unlimited size=unlimited'
          olcSizeLimit: unlimited
          olcTimeLimit: unlimited
          olcMonitoring: 'TRUE'
          olcDbCheckpoint: '0 0'
          olcDbIndex:
            - entryCSN eq
            - objectClass eq
            - reqEnd eq
            - reqResult eq
            - reqStart eq
            - reqDN eq
          olcDbMode: '0600'
          olcDbSearchStack: 16
          olcDbMaxsize: 85899345920
        state: present

```

### Expected Results

The LDAP entry should be detected as non-existing and thus created.

### Actual Results

```console (paste below)
TASK [accesslog database] **********************************************************************************************************************************************************************************************************************************************
ok: [ip-147-251-21-135.flt.cloud.muni.cz]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
