### ISSUE TITLE
community.general.gitlab_runner KeyError: 'access_level' bug

### ISSUE THREAD

**Issue by papdaniel** [ansible-collections/community.general#6112]
### Summary

Line 237 always gives KeyError:

https://github.com/ansible-collections/community.general/blob/d2094669859fe4b48aa20f1b3ae868b61023b51d/plugins/modules/gitlab_runner.py#L227-L239

arguments is just defined right there and it doesn't have 'access_level' key. The if always fails in the line 237.

### Issue Type

Bug Report

### Component Name

gitlab_runner

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.10 (main, Feb  9 2023, 02:08:14) [GCC 12.2.1 20220924]
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.0  

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.4.0  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
- name: "Register {{ runner_name }} runner"
  become: yes
  community.general.gitlab_runner:
    access_level: not_protected
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_admin_api_token }}"
    registration_token: "{{ runner_registration_token }}"
    description: "{{ runner_description }}"
    state: present
    active: True
    tag_list: "{{ runner_tag_list }}"
    run_untagged: False
    locked: no
    owned: yes
```

### Expected Results

Playbook runs successfully

### Actual Results

```console (paste below)

tmp/ansible_community.general.gitlab_runner_payload_64flh7vp/ansible_community.general.gitlab_runner_payload.zip/ansible_collections/community/general/plugins/modules/gitlab_runner.py\", line 237, in create_or_update_runner\r\nKeyError: 'access_level'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
