### ISSUE TITLE
xml module should be able to write cdata fields

### ISSUE THREAD

**Issue by SirUli** [ansible-collections/community.general#6146]
### Summary

The current implementation of the xml module is not capable of changing a value with CDATA.

Example where it isn't possible to change the three asterisks without removing or invalidating the CDATA:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Replace the 3 asterisks with the password -->
<Passwords>
    <password><![CDATA[***]]></password>
</Passwords>
```

### Issue Type

Feature Idea

### Component Name

xml

### Additional Information

Different attempts have been made:

```yaml
- name: Change the password file
  community.general.xml:
    path: "/path/to/the/xml/file"
    xpath: "//password"
    strip_cdata_tags: false
    value: "<![CDATA[ThisIsThePassword]]>"
```

Leads to an escape of the CDATA:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Replace the 3 asterisks with the password -->
<Passwords>
    <password>&lt;![CDATA[ThisIsThePassword]]&gt;</password>
</Passwords>
```

```yaml (paste below)
- name: Change the password file
  community.general.xml:
    path: "/path/to/the/xml/file"
    xpath: "//password"
    value: "systemdb_user_sidadm_password"
    strip_cdata_tags: false
```

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Replace the 3 asterisks with the password -->
<Passwords>
    <password>ThisIsThePassword</password>
</Passwords>
```

My guess is that an additional module option has to be available which allows to define if the value in the `set_target_inner` method ([link](https://github.com/ansible-collections/community.general/blob/627371e2d8cfdd9be43a00e697a0d631036bcb10/plugins/modules/xml.py#L670))  should be set as a CDATA field. When this is true, then the value has to be encoded before setting it basically instead of:

```python
element.text = value
```

having an encoding:

```python
element.text = etree.CDATA(value)
```

Not sure if you would want to add an additional option or if one of the existing ones could be reused.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
