### ISSUE TITLE
community.general.proxmox_kvm module update VM error

### ISSUE THREAD

**Issue by it-pappa** [ansible-collections/community.general#6147]
### Summary

From documentation it says you can use VM name, but it fails with error: 
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to update vm test with vmid None=int() argument must be a string, a bytes-like object or a number, not 'NoneType'", "vmid": null}`

The playbook: 
`- name: Clone VM from template
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: "{{ node }}"
    name: "{{ pve_kvm_hostname }}"
    clone: "{{ pve_kvm_clone_vm }}"
    timeout: 600
  register: cloned_vm

- name: Update VM configuration
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    name: "{{ pve_kvm_hostname }}"
    node: "{{ node }}"
    cores: "{{ pve_kvm_cores }}"
    memory: "{{ pve_kvm_memory }}"
    update: true
  when: cloned_vm
`

### Issue Type

Bug Report

### Component Name

community.general.proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
core 2.14.1
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
6.4.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ran from RHEL9
Ansible-playbook 

### Steps to Reproduce

```yaml (paste below)
`- name: Clone VM from template
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: "{{ node }}"
    name: "{{ pve_kvm_hostname }}"
    clone: "{{ pve_kvm_clone_vm }}"
    timeout: 600
  register: cloned_vm

- name: Update VM configuration
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    name: "{{ pve_kvm_hostname }}"
    node: "{{ node }}"
    cores: "{{ pve_kvm_cores }}"
    memory: "{{ pve_kvm_memory }}"
    update: true
  when: cloned_vm
`
```

### Expected Results

To create a fully cloned template and then reconfigure the vm

### Actual Results

```console (paste below)
TASK [clone_vm_tmpl : Clone VM from template] **********************************
changed: [localhost]

TASK [clone_vm_tmpl : Update VM configuration] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to update vm test with vmid None=int() argument must be a string, a bytes-like object or a number, not 'NoneType'", "vmid": null}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/proxmox_kvm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @helldorado @joshainglis @karmab @tleguern
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by PC-Admin** [comment]
This doesn't just happen when you clone a VM, when you create one from scratch with `update: true` this also occurs:
```
    - name: Create the requested VMs
      delegate_to: localhost
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        # api_password: "{{ proxmox_password }}"
        api_host: proxmox.estuary.tech
        timeout: 60
        name: "{{ vm_name }}{{ '%02d' | format(item) }}"
        memory: "{{ amount_of_memory | int }}"
        balloon: "{{ minimum_memory | default(0) | int }}"
        cores: "{{ number_of_vcpus | int }}"
        agent: true
        description: "{{ vm_description | default('A VM spawned by ProxMAAS and Ansible') }}"
        onboot: false
        # Set machines to boot from network first, then hard disk
        boot: nc
        cpu: host
        node: "{{ proxmox_nodes[item % 8] }}"
        scsihw: "virtio-scsi-single"
        scsi: "{{ scsi_disk_layout }}"
        net:
          net0: 'bridge=vmbr0,virtio,mtu=1,firewall=1'
        bios: ovmf
        efidisk0:
          storage: vm-storage
          format: raw
          efitype: 4m
          pre_enrolled_keys: false
        update: true
      loop: "{{ range(starting_number_target | int, vm_count | int + starting_number_target | int) | list }}"
      register: vm_result
```

generates:
```
TASK [Create the requested VMs] **************************************************************************************************
failed: [localhost] (item=1) => {"ansible_loop_var": "item", "changed": false, "item": 1, "msg": "Unable to update vm dev-demo01 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'", "vmid": null}
failed: [localhost] (item=2) => {"ansible_loop_var": "item", "changed": false, "item": 2, "msg": "Unable to update vm dev-demo02 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'", "vmid": null}
failed: [localhost] (item=3) => {"ansible_loop_var": "item", "changed": false, "item": 3, "msg": "Unable to update vm dev-demo03 with vmid None=int() argument must be a string, a bytes-like object or a real number, not 'NoneType'", "vmid": null}
```

If you remove the `update: true` line, or set this value to 'false' it works. Obviously this would be better if you could create or update a VM irregardless of whether it already exists or not.

**Comment by ansibullbot** [comment]
cc @UnderGreen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by drewburr** [comment]
@it-pappa @PC-Admin 

I've found that after creating a new VM, that VM's information will not immediately be available in the Proxmox API. A workaround would be to add a "get state" task between the create and update steps with an `until` clause so it'll retry up to 3 times.

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met

```yaml
- name: Get VM state
  community.general.proxmox_kvm:
    name: "{{ vm_name }}"
    state: current
  register: vm_state
  until:
    - not vm_state.failed
```

It also looks like a "create and update" task isn't something that the module is currently capable of. This will need to be two separate tasks for now.
