### ISSUE TITLE
ssh_config: identiy_file should supports a list of paths

### ISSUE THREAD

**Issue by sleif** [ansible-collections/community.general#6181]
### Summary

As .ssh/config file allows multiple IdentityFile declarations per each Host it would be good to also support this within this module.

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

```yaml (paste below)
- name: adapt .ssh/config to different keys
  community.general.ssh_config:
    user: username
    host: "*"
    identity_file:
      - ~/.ssh/id_rsa_20200101
      - ~/.ssh/id_rsa_20230301
```
should results in:

```text
Host *
  IdentityFile ~/.ssh/id_rsa_20200101
  IdentityFile ~/.ssh/id_rsa_20230301
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
