### ISSUE TITLE
nmcli module creates bridge with stp on

### ISSUE THREAD

**Issue by alet** [ansible-collections/community.general#6195]
### Summary

I meet some issue with nmcli module. If bridge created from playbook the traffic switches to the bridge. As a sample, DHCP offer for other interface was seen on bridge's enp0s31f6. It looks like STP issue, but the properties STP is off.

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.3]
  config file = /home/USER/.ansible.cfg
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/USER/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/USER/.ansible/collections:/usr/share/ansible/collections
  executable location = .local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 6.4.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 22.04.1

### Steps to Reproduce

```yaml (paste below)
- name: Create bridge
  community.general.nmcli:
    conn_name: 'br0'
    ifname: 'br0'
    dhcp_client_id: 'workstation'
    type: 'bridge'
    stp: false
    state: 'present'

- name: Add network card to bridge
  community.general.nmcli:
    conn_name: "{{ wired_card }}"
    master: 'br0'
    ifname: "{{ wired_card }}"
    type: 'bridge-slave'
    state: 'present'
```

### Expected Results

I meet some issue with nmcli module. After switched to Ubuntu 22.04 the bridge created by playbook works strange. Some investigation shows that if I create bridge from terminal with:
```sh
nmcli con add type bridge ifname br0 stp no
nmcli con add type bridge-slave ifname enp0s31f6 master br0
```
it works. If bridge created from playbook the traffic switches to the bridge. As a sample, DHCP offer for other interface was seen on bridge's enp0s31f6. It looks like STP issue, but in properties STP is off.

### Actual Results

There are packet loss and DHCP answers capture

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
