### ISSUE TITLE
Redis Cluster support for flush command

### ISSUE THREAD

**Issue by subbotinkv** [ansible-collections/community.general#6202]
### Summary

I'm trying to implement data clean up for Redis Cluster. At the moment direct interaction /w each node required to clean up cluster fully. It requires hard coding cluster topology somewhere or getting it with additional call to Redis. Starting from v4.1.0 (or even v4.0.2) redis-py supports cluster commands [docs](https://redis.readthedocs.io/en/v4.1.0/redis_cluster_commands.html#redis.commands.cluster.RedisClusterCommands) and it it possible to clean up cluster in one call. It would be nice to have this feature in community.general.redis module for easier implementation of clean up procedure, especially in cloud environments. 

### Issue Type

Feature Idea

### Component Name

redis module

### Additional Information

```yaml (paste below)
- name: Flush Redis Cluster db
  community.general.redis:
    command: flush
    cluster: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
