### ISSUE TITLE
Add worklog comment for Jira module

### ISSUE THREAD

**Issue by hugoprudente** [ansible-collections/community.general#6209]
### Summary

In the `jira` module we have the ability to create the Jira and estimate the times.

This is achieved by the `/worklog` api similar to what `comment` does:

* https://docs.atlassian.com/software/jira/docs/api/REST/7.3.3/?_ga=2.174542626.1666439307.1519293627-1080493640.1514451808#api/2/issue-updateWorklog

This is really interesting if you share times of user vs automation.

### Issue Type

Feature Idea

### Component Name

community.general.jira

### Additional Information

```yaml (paste below)
- name: Worklog on issue
  community.general.jira:
    uri: '{{ server }}'
    username: '{{ user }}'
    password: '{{ pass }}'
    issue: '{{ issue.meta.key }}'
    operation: worklog
    comment: A worklog added by Ansible
    fields:
      timeSpentSeconds: 12000
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
