### ISSUE TITLE
Add visibility info for github_repo module

### ISSUE THREAD

**Issue by emersonyh** [ansible-collections/community.general#6219]
### Summary

When creating a new repository, allow the user to specify a specific visibility info (internal for example).

### Issue Type

Feature Idea

### Component Name

github_repo

### Additional Information

```yaml (paste below)
- name: Create a Github repository
  community.general.github_repo:
    access_token: mytoken
    organization: MyOrganization
    name: myrepo
    description: "Just for fun"
    visibility: internal
    state: present
  register: result
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
