### ISSUE TITLE
community.general.one_vm: creating fails with "Parse error: syntax error"

### ISSUE THREAD

**Issue by salfers** [ansible-collections/community.general#6225]
### Summary

When we try to create a VM in our OpenNebula environment using an Ansible task it fails with an error message.
Notably this worked before on `community.general` 6.2.0 or lower and thus is a **regression**.

We suspect that the bug appeared in 8818a6f2421d50980229db464a710a84e4748eff, especially since it relates to new ONE features (we are still on an old ONE version).

### Issue Type

Bug Report

### Component Name

one_vm

### Ansible Version

```console (paste below)
ansible [core 2.14.3]
  config file = /root/projects/server-automation/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.13 (main, Nov 16 2022, 10:51:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.4.0
```

### Configuration

no special configuration

### OS / Environment

OpenNebula installation: version 6.0.0.2

### Steps to Reproduce

```yaml
  - community.general.one_vm:
      api_url: "{{ one_api }}"
      api_username: "{{ one_user }}"
      api_password: "{{ one_token }}" 
      template_id: 577
      disk_size: "5 GB"
      memory: "2048 MB"
      cpu: 1
      vcpu: 1
      networks:
        - NETWORK_ID: 6
      attributes:
        name: "testvm123"
        HYPERVISOR: kvm

```

### Expected Results

VM in OpenNebula successfully created

### Actual Results

```console
TASK [community.general.one_vm] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "[one.template.instantiate] Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 32643, columns 735:739"}
```

Depending on which vm template is used, there is sometimes a different error:
```console
TASK [community.general.one_vm] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "[one.template.instantiate] Error allocating a new virtual machine template. Wrong OS/BOOT value: \"None\" should be a comma-separated list of disk# or nic#"}
```

In either case the exact same playbook worked before.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
