### ISSUE TITLE
New module `github_gist` request

### ISSUE THREAD

**Issue by ak1ra-komj** [ansible-collections/community.general#6230]
### Summary

I am trying to use Ansible to create or update GitHub Gists, I found that some github related roles have been implemented in `community.general`, such as [github_repo](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/github_repo.py) and [github_release](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/github_release.py), perhaps we can create a `github_gist` role to operate GitHub Gists based on the role `github_repo`.

According to [GitHub Gists REST API Docs](https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28), the `github_gist` role should have the following parameters:

* `username`, `password`, `access_token` are used for authentication, where `username` and `access_token` are mutually exclusive, as described in `github_repo`
* `state` indicates the state of Gists, the possible values are `[present, absent, updated, forked, starred, unstarred]`

About `gist_id` and `state`,

* When the `state` is `present` and no `gist_id` is provided, it means to create Gists based on `files`, the `files` should be required at this time?
* When the `state` is `present` and `gist_id` is provided at the same time, it means to **ensure** that the corresponding `gist_id` exists, that is, to obtain the content of specific `gist_id`, and raise error when `gist_id` does not exist
* `gist_id` is required when `state` is other than `present`

### Issue Type

Feature Idea

### Component Name

github_gist

### Additional Information

The following is the possible usage of `github_gist` role in tasks,

```yaml
---
tasks:
  - name: create a github gist with username and password
    github_gist:
      username: githubuser
      password: <password>
      description: Example of a gist
      public: False
      state: present
      files:
        README.md:
          content: |
            Hello World

  - name: create a github gist with access_token
    github_gist:
      access_token: <token>
      description: Example of a gist
      public: False
      state: present
      files:
        README.md:
          content: |
            Hello World

  - name: get a github gist and register for later use, raise error when gist_id does not exist?
    github_gist:
      gist_id: 2decf6c462d9b4418f2
      state: present
    register: gh_gist_fact

  - name: update a github gist
    github_gist:
      access_token: <token>
      gist_id: 2decf6c462d9b4418f2
      files:
        README.md:
          content: |
            {{ gh_gist_fact.files[README.md].content }}, Hello Ansible

  - name: delete a github gist
    github_gist:
      access_token: <token>
      gist_id: 2decf6c462d9b4418f2
      state: absent

  - name: star a github gist
    github_gist:
      access_token: <token>
      gist_id: 2decf6c462d9b4418f2
      state: starred

  - name: unstar a github gist
    github_gist:
      access_token: <token>
      gist_id: 2decf6c462d9b4418f2
      state: unstarred
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
