### ISSUE TITLE
postgresql_privs fails with schema name which contain '-' (dash) character

### ISSUE THREAD

**Issue by peterkrawiec1** [ansible-collections/community.general#6253]
### Summary

Task with module postgresql_privs fails with syntax error when it's trying to apply privileges to group roles on schema with a name which contain '-' (dash) character.

### Issue Type

Bug Report

### Component Name

postgresql_privs

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.3]
ansible 7.0.0
python 3.9.6
jinja 3.0.2
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 6.0.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

MacOS Ventura 13.2.1

### Steps to Reproduce

```yaml (paste below)
roles:
  - name: test-role
    role_flags: "NOLOGIN,NOCREATEROLE,NOCREATEDB"
    state: present
    privs:
      - db: test
        type: table
        objs: ALL_IN_SCHEMA
        privs: SELECT,UPDATE,INSERT
        schema: public
        state: present
      - db: test
        type: sequence
        objs: ALL_IN_SCHEMA
        privs: SELECT,USAGE
        schema: public
        state: present
      - db: test
        type: schema
        objs: public
        privs: USAGE
        state: present
      - db: test
        type: table
        objs: ALL_IN_SCHEMA
        privs: SELECT,UPDATE,INSERT
        schema: test-schema
        state: present
      - db: test
        type: sequence
        objs: ALL_IN_SCHEMA
        privs: SELECT,USAGE
        schema: test-schema
        state: present
      - db: test
        type: schema
        objs: test-schema
        privs: USAGE
        state: present
      - db: test
        type: schema
        objs: sample
        privs: USAGE
        state: present
      - db: test
        type: table
        schema: sample
        objs: table1,table2
        privs: SELECT,UPDATE,INSERT,DELETE
        state: present


- name: Configure group role privileges
  postgresql_privs:
    db: "{{ item.1.db }}"
    schema: "{{ item.1.schema | default(omit) }}"
    objs: "{{ item.1.objs }}"
    privs: "{{ item.1.privs }}"
    type: "{{ item.1.type }}"
    role: "{{ item.0.name }}"
    state: "{{ item.1.state | default('present') }}"
    port: "{{ instance.port }}"
    login_host: "{{ ansible_host }}"
    login_user: "{{ instance.owner | default('postgres') }}"
    login_password: "{{ instance.password }}"
  loop: "{{ roles | subelements('privs', 'skip_missing=True') }}"
  loop_control:
    label: "{{ item.0.name }}:{{ item.1.db }}:{{ item.1.schema | default('public') }} -> {{ item.1.state | default('present') }} -> {{ item.1.privs }} ON {{ item.1.objs }}"
  register: role_privs
  tags: ["groups", "permissions"]
```

### Expected Results

Group role privileges applied to all objects as per `roles` block.

Sample of the output should be:

```
ok: [test-db-instance] => (item=test-role:test:public -> present -> USAGE ON public)
ok: [test-db-instance] => (item=test-role:test:test-schema -> present -> SELECT,UPDATE,INSERT ON ALL_IN_SCHEMA)

```

### Actual Results

```console (paste below)
failed: [test-db-instance] (item=test-role:test:test-schema -> present -> SELECT,UPDATE,INSERT ON ALL_IN_SCHEMA) => changed=false

ansible_loop_var: item
item:
- db: test
    objs: ALL_IN_SCHEMA
    privs: SELECT,UPDATE,INSERT
    schema: test-schema
    state: present
    type: table

msg: |-
  syntax error at or near "-"
  LINE 1: ...PDATE,INSERT,SELECT ON ALL TABLES IN SCHEMA test-schema TO "t...
                                                             ^
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
