### ISSUE TITLE
proxmox_kvm unable to force-stop a VM quickly

### ISSUE THREAD

**Issue by elelayan** [ansible-collections/community.general#6257]
### Summary

`state: stopped` won't stop a VM not responding to ACPI until 10 minutes, even with  `force: true`.

It will create a shutdown task, with the (proxmox VE) timeout of 10 minutes.
The task will finally halt the VM after 10 minutes but it's too long.

pve api `timeout` parameter should be exposed, to have proxmox kill the VM quicker.

Maybe it could be computed as the module's `timeout` parameter `- 1`?

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/software/miniconda/envs/yyyy/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/software/miniconda/envs/yyyyy/bin/ansible
  python version = 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 4.0.2 
```

### Configuration

N/A

### Steps to Reproduce

```yaml
---
- hosts: all
  gather_facts: false

  tasks:
    - name: Stop template VM Will timeout
      community.general.proxmox_kvm:
        api_user: "{{ pve_user }}"
        api_token_id: "{{ pve_token_id }}"
        api_token_secret: "{{ pve_token_secret }}"
        api_host: "{{ pve_api_host }}"
        vmid: "{{ pve_template_vm_id }}"
        state: stopped
        force: true
      delegate_to: localhost

    - name: Stop template VM will succeed after 10 minutes
      community.general.proxmox_kvm:
        api_user: "{{ pve_user }}"
        api_token_id: "{{ pve_token_id }}"
        api_token_secret: "{{ pve_token_secret }}"
        api_host: "{{ pve_api_host }}"
        vmid: "{{ pve_template_vm_id }}"
        state: stopped
        force: true
        timeout: 610
      delegate_to: localhost
```

### Expected Results

I expected to be able to specify a shorter timeout than 10 minutes for the force shutdown to apply.

### Actual Results

Proxmox will halt the VM after 10 minutes, but it's too long.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
