### ISSUE TITLE
archive: compressing single file uses a lot of RAM in calculating the checksum

### ISSUE THREAD

**Issue by nilsmeyer** [ansible-collections/community.general#6272]
### Summary

When running the archive module for compressing a large file the crc32 checksum is calculated over the whole file, this requires a lot of RAM as a memory buffer for running zlib.crc32 over. This seems to happen when the file specified by the `dest` parameter already exists. 

### Issue Type

Bug Report

### Component Name

archive

### Ansible Version

```console (paste below)
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/nils/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nils/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nils/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/nils/.local/bin/ansible
  python version = 3.10.7 (main, Mar 10 2023, 10:47:39) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = False
```

### Community.general Version

```console (paste below)
Collection        Version
----------------- -------
community.general 6.5.0
```

### OS / Environment

Ubuntu 22.04
Ubuntu 22.10
Probably others

### Steps to Reproduce

```yaml (paste below)
- name: demonstrate ram usage bug for archive
  hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: create large file
    community.general.filesize:
      path: ./testfile
      size: 8G
  - name: compress file
    community.general.archive:
      path: "./testfile"
      dest: "./testfile.gz"
      format: gz
    register: _pass1
  - name: compress file
    when: _pass1.changed
    community.general.archive:
      path: "./testfile"
      dest: "./testfile.gz"
```
Running this on a system with less than 8GiB RAM results in an OOM kill of the ansible python process

### Expected Results

Playbook should run with a reasonable amount of RAM

### Actual Results

```console (paste below)
TASK [compress file] *********************************************************************************************************************************************************************************
task path: /home/test/test_playbook.yml:10
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Killed\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}

```
From kernel log
```console
[Sun Apr  2 13:42:18 2023] Out of memory: Killed process 34804 (python3) total-vm:3403924kB, anon-rss:3380620kB, file-rss:1840kB, shmem-rss:0kB, UID:1000 pgtables:6704kB oom_score_adj:0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
