### ISSUE TITLE
redhat_subscription module doesn't work as expected on collection version 6.5.0

### ISSUE THREAD

**Issue by hrgrigorov** [ansible-collections/community.general#6276]
### Summary

When I try to subscribe an RHEL box to RHSM using the redhat_subscription module, provided by collection version 6.5.0, it is throwing me the below message:
**FAILED! => {"changed": false, "cmd": "/usr/sbin/subscription-manager unregister", "msg": "This system is currently not registered.", "rc": 1, "stderr": "This system is currently not registered.\n", "stderr_lines": ["This system is currently not registered."], "stdout": "", "stdout_lines": []}** 

Recently I updated community.general collection from v.5.8.0 to v.6.5.0 and since then redhat_subscription module is not working. If I downgrade the version it starts working again.

### Issue Type

Bug Report

### Component Name

redhat_subscription

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.5]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general         6.5.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
  - name: Register RHEL system to RHSM
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
        force_register: true
```
  

### Expected Results

I expect that using this module the box will be subscribed to RHSM, at least this is how it works on collection version 5.8.0, but not on the latest 6.5.0

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
