### ISSUE TITLE
Adding Topics on Gitlab module

### ISSUE THREAD

**Issue by tanganellilore** [ansible-collections/community.general#6277]
### Summary

Team,

I notice that in the `gitlab_project `module is missing the support to `topics`.
Implementation of it should be very easy and i will propose you a PR to add it.

Should be backward compatible with all gitlab server version.

### Issue Type

Feature Idea

### Component Name

gitlab_project

### Additional Information

```yaml (paste below)
- name: Create GitLab Project in group Ansible
  community.general.gitlab_project:
    api_url: "gitlab_url"
    api_token: "gitlab_token"
    name: "project_name"
    topics:
      - automation
      - awx
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
