### ISSUE TITLE
pacman: Install of group base-devel does not install member package make

### ISSUE THREAD

**Issue by kisp** [ansible-collections/community.general#6290]
### Summary

When I use `community.general.pacman` to install the group `base-devel`, I expect that all member packages will be installed. As an example, `make` is a member package, but for some reason it does not get installed.

### Issue Type

Bug Report

### Component Name

pacman

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/user/repos/xxx/ansible/ansible_collections
Collection        Version
----------------- -------
community.general 5.2.0

# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.5.0
```

I believe that upgrading the local ansible_collections to `community.general 6.5.0` does not change the observed behaviour (but I can double check that again if desired).

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/user/repos/repo/ansible/ansible.cfg) = ['/home/user/repos/repo/ansible']
CONFIG_FILE() = /home/user/repos/repo/ansible/ansible.cfg
DEFAULT_ROLES_PATH(/home/user/repos/repo/ansible/ansible.cfg) = ['/home/user/repos/repo/ansible/>
DEFAULT_STDOUT_CALLBACK(/home/user/repos/repo/ansible/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/user/repos/repo/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/repos/repo/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml (paste below)
---
- name: Test playbook
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure make is not installed
      community.general.pacman:
        state: absent
        name:
          - make
    - name: Install base-devel
      community.general.pacman:
        state: present
        name:
          - base-devel
    - name: Run make -v
      ansible.builtin.command:
        cmd: make -v
      register: make_v
    - name: Show make -v output
      ansible.builtin.debug:
        msg: "{{ make_v.stdout }}"
```

### Expected Results

I expect `make` to be available after installing `base-devel`.

```console
PLAY [Test playbook] **********************************************************************

TASK [Gathering Facts] ********************************************************************
ok: [172.105.72.134]

TASK [Ensure make is not installed] *******************************************************
ok: [172.105.72.134]

TASK [Install base-devel] *****************************************************************
ok: [172.105.72.134]

TASK [Run make -v] ************************************************************************
changed: [172.105.72.134]

TASK [Show make -v output] ****************************************************************
ok: [172.105.72.134] => {}

MSG:

GNU Make 4.4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

PLAY RECAP ********************************************************************************
172.105.72.134             : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual Results

```console (paste below)
PLAY [Test playbook] **********************************************************************

TASK [Gathering Facts] ********************************************************************
ok: [172.105.72.134]

TASK [Ensure make is not installed] *******************************************************
ok: [172.105.72.134]

TASK [Install base-devel] *****************************************************************
ok: [172.105.72.134]

TASK [Run make -v] ************************************************************************
fatal: [172.105.72.134]: FAILED! => {
    "changed": false,
    "cmd": "make -v",
    "rc": 2
}

MSG:

[Errno 2] No such file or directory: b'make'

PLAY RECAP ********************************************************************************
172.105.72.134             : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
