### ISSUE TITLE
Ansible flags option in community.general.parted does not work on SUSE12 SP5

### ISSUE THREAD

**Issue by pyendell** [ansible-collections/community.general#6292]
### Summary

When I try to use the flags option in a playbook and set it to [lvm] I get following error.

fatal: [servername]: FAILED! => {"changed": false, "err": "/usr/sbin/parted: invalid token: type=83\n", "msg": "Error while running parted script: /usr/sbin/parted -s -m -a optimal /dev/sdb -- unit MiB set 1 lvm on set 1 type=83 off", "out": "", "rc": 1}

If I remove 

flags: [lvm] from the playbook parted works fine, so this works :

---

- name: (20-partition.yml) Create partition

  community.general.parted:

    device: /dev/sdb

    number: 1

    unit: MiB

    state: present

    part_end: "100%"

### Issue Type

Bug Report

### Component Name

community.general.parted

### Ansible Version

```console (paste below)
$ ansible --version

```
AWX 21.5
ansible 2.9.21

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

AWX controller is at SUSE 15 SP3

client node is at SUSE 12 SP5

### Steps to Reproduce

```yaml (paste below)

```
---
- name: (20-partition.yml) Create partition
  community.general.parted:
    device: /dev/sdb
    number: 1
    unit: MiB
    flags: [ lvm ]
    state: present
    part_end: "100%"

### Expected Results

expected to create /dev/sdb1 as Linux LVM partition.

### Actual Results

```console (paste below)

```
fatal: [servername]: FAILED! => {"changed": false, "err": "/usr/sbin/parted: invalid token: type=83\n", "msg": "Error while running parted script: /usr/sbin/parted -s -m -a optimal /dev/sdb -- unit MiB set 1 lvm on set 1 type=83 off", "out": "", "rc": 1}

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/parted.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/parted.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @ColOfAbRiX @jake2184 @rosowiecki
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mator** [comment]
1. is it possible to properly format issue? 

2. i can't reproduce your issue:
```
ansible.dev]$ cat playbooks/parted.yml
---
- name: community.general/issues/6292
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: create partition
      community.general.parted:
        device: /dev/loop0
        number: 1
        unit: MiB
        flags: [ lvm ]
        state: present
        part_end: "100%"

ansible.dev]$ ansible-playbook playbooks/parted.yml

PLAY [community.general/issues/6292] **************************************************************

TASK [create partition] ***************************************************************************
ok: [localhost]

PLAY RECAP ****************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
