### ISSUE TITLE
redhat_subscription should be able to add subscriptions without overwriting all

### ISSUE THREAD

**Issue by gardar** [ansible-collections/community.general#6324]
### Summary

Currently the `redhat_subscription` module overwrites all of the subscriptions that are defined on a host rather than appending to the subscriptions that currently exist.
I would like to be able to add subscriptions without having to define the whole list of subscriptions.

I manage a few ansible roles which are used in RedHat Satellite, in many of them I'm installing packages that are only available through certain subscriptions and products(repos). It would be great if I could simply define the pool names or pool id's I want to add without having to populate the whole list of already consumed subscriptions.

As a workaround I'm using subscription-manager through the command module such as this:

```yaml
- name: "Check if subscription is enabled"
  ansible.builtin.command:
    cmd: "subscription-manager list --consumed --matches={{ my_subscription_name | quote }} --pool-only"
  register: __subscription_manager_consumed
  changed_when: false

- name: "Find subscription pool id"
  ansible.builtin.command:
    cmd: "subscription-manager list --available --matches={{ my_subscription_name | quote }} --pool-only"
  register: __subscription_manager_available
  changed_when: false
  when:
    - "__subscription_manager_consumed.stdout | length <= 0"

- name: Attach subscription
  ansible.builtin.command:
    cmd: "subscription-manager attach --pool={{ __subscription_manager_available.stdout }}"
  register: __subscription_manager_attach
  changed_when: "__subscription_manager_attach.stdout is search('Successfully attached a subscription')"
  failed_when: "__subscription_manager_attach.stdout is search('could not be found')"
  when:
    - "__subscription_manager_consumed.stdout | default() | length <= 0"
    - "__subscription_manager_available.stdout | default() | length > 0"


```

But I'd prefer to be able to simply do this:

```yaml
- name: Attach subscription
  community.general.redhat_subscription:
    pool: "{{ my_subscription_name }}"
```

### Issue Type

Feature Idea

### Component Name

redhat_subscription

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
