### ISSUE TITLE
redhat_subscription:   status or print state needed

### ISSUE THREAD

**Issue by SoMoney** [ansible-collections/community.general#6335]
### Summary

The module would benefit from a way to print the registration status/state (Im using identity) for when conditionals to prevent "Re-Registration" attempts.

Currently, I am using 'subscription-manager identity' shell command to get the status for my when condition but It would be nice to have all this view functionality inside the module itself.

### Issue Type

Feature Idea

### Component Name

redhat_subscription

### Additional Information

```
`- name: "[RHSM] Check RH subscription status"
  shell: subscription-manager identity
  register: subscription_check
  ignore_errors: true

- include: register.yml
  when:
  - ansible_distribution == "RedHat"
  - "'not yet registered' in subscription_check.stderr"
`

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/redhat_subscription.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/redhat_subscription.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ptoscano** [comment]
Hello @SoMoney,

`redhat_subscription` maintainer here.

> The module would benefit from a way to print the registration status/state (Im using identity) for when conditionals to prevent "Re-Registration" attempts.

The module already figures out when to register (when not registered or when forcing) and when not (when already registered) -- you can simply write:
```yaml
- name: Ensure the system is registered
  redhat_subscription:
    username: "your-username"
    password: "your-password"
    # or activationkey + org_id, etc
```
and `redhat_subscription` will register only when needed, without any conditionals needed.

So let me ask directly: what's exactly your use case? which reasons you do need to know the registration status for?
