### ISSUE TITLE
Add full DMIDecode facts module

### ISSUE THREAD

**Issue by jhg03a** [ansible-collections/community.general#6359]
### Summary

I'm trying to mine OEM specific information out of DMIDecode which isn't part of the ansible core fact collection library (for example HPE NVME disk serial numbers).  The ansible core team in the past I believe has had a stance against using `dmidecode` directly because of 3rd party libraries to parse it as well as its requirement of root privileges.  I'd like to see a separate module created where I can get all the facts dumped for later reporting, parsing, and filtering that can have these design limitations.

### Issue Type

Feature Idea

### Component Name

dmidecode_facts

### Additional Information

```yaml (paste below)
- name: Collect all DMIDecode data
  dmidecode_facts:
    type: 8,46 (optional, can be either a list of integers or a list of names as supported by dmidecode.  Note that the integers are not limited to those present in the documentation and frequently are the goal for OEM data)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
