### ISSUE TITLE
community.general.slack Add delay for msg

### ISSUE THREAD

**Issue by ma3s7ro** [ansible-collections/community.general#6429]
### Summary

I have playbook which updates from all servers in inventory after it is done. We drop notification to slack about need or not need server restart. Infrastructure has grown. 
And I have error:
_Due to a high volume of activity, we are not displaying some messages from this incoming webhook integration._

Maybe add delay for sending msg

### Issue Type

Feature Idea

### Component Name

slack

### Additional Information

```yaml (paste below)
- name: Alarm restart not required
  delegate_to: localhost
  slack:
    token: "{{ token }}"
    msg: '{{ inventory_hostname }} do not require restart'
    color: good
  become: false
  when: if_restart_not_required

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/slack.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/slack.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @ramondelafuente
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Sounds like something that should be solved by other means than by adding a new parameter to the module. You could for example use `run_once: true`, loop over all servers, and thus serialize the `community.general.slack` module calls.

**Comment by ma3s7ro** [comment]
So is it should be like? 
But this play running on runner. I think it will not work. I will check tomorrow 
```
- name: Alarm restart not required
  delegate_to: 127.0.0.1
  slack:
    token: "{{ token  }}"
    msg: '{{ inventory_hostname }} do not require restart'
    color: good
  run_once: true
  become: false
  loop: "{{inventory_hostname}}"
  when: if_restart_not_required

```

**Comment by ma3s7ro** [comment]
I have tried few solution with loop and run once. 
```
- name: Alarm restart not required
  delegate_to: localhost
  slack:
    token: "{{ token}}"
    msg: '{{ inventory_hostname }} do not require restart'
    color: good
  run_once: true
  become: false
  loop: "{{ query('inventory_hostnames', 'all') }}"
  when: os_restart_notify_if_restart_not_required
```

Output from ansible: 
ok: [server1 -> localhost] => (item=server1)
ok: [server1 -> localhost] => (item=server2)
ok: [server1 -> localhost] => (item=server3)

So pushed only information about first server. Maybe you know how to create correct loop with run once? I'll be very grateful

**Comment by felixfontein** [comment]
1. You need to use `item` instead of `inventory_hostname`.
2. You need to check the hostvars of `item` for the value of `os_restart_notify_if_restart_not_required`.

Maybe something like
```yaml
- name: Alarm restart not required
  delegate_to: localhost
  slack:
    token: "{{ token}}"
    msg: '{{ item }} do not require restart'
    color: good
  run_once: true
  become: false
  loop: "{{ query('inventory_hostnames', 'all') }}"
  when: hostvars[item].os_restart_notify_if_restart_not_required
```

**Comment by ma3s7ro** [comment]
I have tested. loop with run once not working
The same error 
_Due to a high volume of activity, we are not displaying some messages from this incoming webhook integration._ 

Need interval or delay to sending the messages.

**Comment by flowerysong** [comment]
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#pausing-within-a-loop

**Comment by flowerysong** [comment]
Fundamentally this isn't something that can be addressed at the module level, because the running module has no way of coordinating with other invocations of the same module. You need to structure your play itself to have a delay between the tasks, whether that's by using `serial` at the play level and a `pause` task, or a loop with `run_once` and `loop_control: pause`.

Alternatively, you could avoid the throttling issue by sending a single message with aggregated data instead of a bunch of individual messages.

**Comment by ma3s7ro** [comment]
@flowerysong Thanks for the tip. I somehow missed this little block in the ansible loop documentation.
Pausing resolve the error. 

You tell about aggregated messages. Do you have any example? I just thought about it.

**Comment by flowerysong** [comment]
There are multiple ways to approach it, but one of the simplest is to just use a Jinja loop, something like the following (untested) code:

```yaml
- name: Alarm restart not required
  delegate_to: localhost
  slack:
    token: "{{ token }}"
    msg: |
      Host restart required:
      {% for host in groups.all %}
      {{ host }}: {{ not (hostvars[host].os_restart_notify_if_restart_not_required | default(false)) }}
      {% endfor %}
    color: good
  run_once: true
  become: false
```
