### ISSUE TITLE
gitlab_protected_branch add code owner approval option

### ISSUE THREAD

**Issue by mcoreix** [ansible-collections/community.general#6432]
### Summary

pls add Code owner approval option to gitlab_protected_branch as a boolean value

### Issue Type

Feature Idea

### Component Name

community.general.gitlab_protected_branch

### Additional Information

```yaml (paste below)
- name: Create protected branch on main
  community.general.gitlab_protected_branch:
    api_url: https://gitlab.com
    api_token: secret_access_token
    project: "dj-wasabi/collection.general"
    name: main
    merge_access_levels: maintainer
    push_access_level: nobody
    code_owner_approval: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
