### ISSUE TITLE
SetBiosAttributes: handle vendors who don't provide @Redfish.Settings attribute

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#6433]
### Summary

Attempting to use `SetBiosAttributes` on Gigabyte servers results in:

TASK [bios_config : Configure BIOS Settings] ***********************************************************************************************************************************
fatal: [X.X.X.X]: FAILED! => {"changed": false, "msg": "Settings resource for BIOS attributes not found."}

https://github.com/ansible-collections/community.general/blob/33ccabed1341f8e0a425696aa6e91a5b915bafed/plugins/module_utils/redfish_utils.py#L1924-L1927

due to Gigabyte not providing @Redfish.Settings attribute with the URL.

Gigabyte uses `https://x.x.x.x/redfish/v1/Systems/Self/Bios/SD` as the settings endpoint. To avoid having to hardcode endpoints it would be great if the SetBiosAttributes command accepted a manually specified endpoint similar to the SimpleUpdate command:

https://github.com/ansible-collections/community.general/blob/33ccabed1341f8e0a425696aa6e91a5b915bafed/plugins/module_utils/redfish_utils.py#L1513

### Issue Type

Feature Idea

### Component Name

redfish_config

### Additional Information

```
  - name: Configure BIOS Settings
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes: "{{ bios_config[ansible_system_vendor][ansible_product_name]['bios_attrs'] }}"
      baseuri: "{{ bmc_address }}"
      update_targets:
      - /redfish/v1/Bios/SD: 
```

with a valid bios_attributes dict.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
