### ISSUE TITLE
community.general.terraform Relative project_path

### ISSUE THREAD

**Issue by eszense** [ansible-collections/community.general#6463]
### Summary

The terraform modules works with relative project_path (from the playbook directory) but only if it includes a '/'.
And the validation error message `Path for Terraform project can not be None or ''.` does not match with the cause of failing validation (path not contain '/') 

### Issue Type

Bug Report

### Component Name

community.general.terraform

### Ansible Version

```
ansible [core 2.14.4]
  python version = 3.9.6 (default, Oct 18 2022, 12:41:40) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```
Collection        Version
----------------- -------
community.general 6.5.0  
```

### OS / Environment

MacOS

### Steps to Reproduce

Directory structure set up as bellow
```
playbook.yaml
terraform/main.tf
```

playbook.yaml
```
hosts: localhost
tasks:
- name: Apply terraform (this will succeed)
  community.general.terraform:
    project_path: terraform/
- name: Apply terraform (this will fail)
  community.general.terraform:
    project_path: terraform

```

### Expected Results

Both relative path with or without '/' should succeed

### Actual Results

```
TASK [Apply terraform (this will succeed)] ****************
ok: [localhost]
TASK [Apply terraform (this will fail)] ****************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Path for Terraform project can not be None or ''."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
