### ISSUE TITLE
ini_file creates new file instead of following symlink

### ISSUE THREAD

**Issue by tod-uma** [ansible-collections/community.general#6470]
### Summary

When you use community.general.ini_file to modify a symlink (like /etc/yum.conf which is a symlink to /etc/dnf/dnf.conf on a oel9 machine) it appears to copy the file, edit it and replace the symlink with the edited file. There should at least be an option to follow symlinks instead of replacing them.

### Issue Type

Bug Report

### Component Name

ini_file

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.4]
  config file = /home/tod.detre/code/gitlab/tower-projects/ansible.cfg
  configured module search path = ['/home/tod.detre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tod.detre/.virtualenvs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/tod.detre/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tod.detre/.virtualenvs/ansible/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2.1.0.1)] (/home/tod.detre/.virtualenvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 6.5.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

OracleLinux 9

### Steps to Reproduce

```yaml (paste below)
- name: "Ensure yum is configured to use a proxy (globally)"
  community.general.ini_file:
    path: "/etc/yum.conf"
    section: main
    option: proxy
    value: 'http://proxy.myorg.org:3128'
```

### Expected Results

I expected it to edit the file that already existed instead of creating a new one.

### Actual Results

```console (paste below)

```
Instead of modifying the existing file, it created a new file and replaced the symlink with it.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
