### ISSUE TITLE
Redfish Support multi-part HTTP Push Update

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#6471]
### Summary

At the moment we have GPU devices that only support HTTP push Redfish update capability. Would it be possible to open a discussion around implementing that functionality?

Per https://github.com/ansible-collections/community.general/issues/3910 I see that it isn't supported and doesn't appear to be on a roadmap that I could find.

@mraineri - thank you in advance :) 

### Issue Type

Feature Idea

### Component Name

redfish_command

### Additional Information

Potentially implement it as:

```
- name: Update with http push
  community.general.redfish_command:
    category: Update
    command: PushUpdate
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    update_image_file: file_to_push_to_target
    update_targets:
      - /redfish/v1/UpdateService/upload
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
