### ISSUE TITLE
Cloudflare DNS record support for Tags and Comments

### ISSUE THREAD

**Issue by seanatcesa** [ansible-collections/community.general#6494]
### Summary

Cloudflare has recently added support for some admin-facing tags and comments.  These features are not yet implemented in Ansible.

### Abstract
These new fields are helpful for organizing records within Cloudflare, and setting metadata which can be used to affect future conditional actions.  These fields and their data have no effect on DNS responses.

Reference: [Cloudflare API documentation](https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-create-dns-record)

#### Creating Records
Endpoint: **POST** to `https://api.cloudflare.com/client/v4/zones/{zone_identifier}/dns_records`

Body Attributes:
  - `comment` (`string`)
  - `tags` (`array[string]`)

#### Read/Query records
Endpoint: **GET** to `https://api.cloudflare.com/client/v4/zones/{zone_identifier}/dns_records`

To search and filter records using these new fields based on these values, use these parameters

URI Parameters available:
- comment.absent
- comment.contains (`string`)
- comment.endswith (`string`)
- comment.exact (`string`)
- comment.present
- comment.startswith (`string`)
- tag.absent
- tag.contains (`string`)
- tag.endswith (`string`)
- tag.exact (`string`)
- tag.present
- tag.startswith (`string`)

#### Update/Patch records

Endpoint: **PATCH** to `https://api.cloudflare.com/client/v4/zones/{zone_identifier}/dns_records/{identifier}`

Body Attributes:
  - `comment` (`string`)
  - `tags` (`array[string]`)

#### Delete records

This field is not used for for deleting records.

### Issue Type

Feature Idea

### Component Name

cloudflare

### Additional Information

```yaml 
---
- name: Manage DNS records based on lifecycle_status
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: Set DNS records based on our vars.  Include tags and comments.
      community.general.cloudflare_dns:
        zone: {{zone_name}
        type: CNAME
        record: "{{record_name}}"
        value: {{ record value }}
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_api_token }}"
        proxied: "{{(item.value.proxy }}"
        state: "{{ 'present' if item.value.site_enabled else absent
        tags: 
          - "customerid_12345"
          - "host_aws"
          - "requires_gdpr"
        comment: "Some helpful comment goes here.  This is seen only in the Cloudflare dashboard."
      loop: "{{ websites|dict2items }}"
      vars:
        cloudflare_email: YOUR_CLOUDFLARE_EMAIL
        cloudflare_api_token: YOUR_CLOUDFLARE_API_TOKEN

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
