### ISSUE TITLE
sudoers module could include Defaults/requiretty options

### ISSUE THREAD

**Issue by joaoolavobv** [ansible-collections/community.general#6528]
### Summary

Can't find how to set with community.general.sudoers Defaults options/parameters, such as requiretty.

Could you please incluse this feature on the module?

### Issue Type

Feature Idea

### Component Name

community.general.sudoers

### Additional Information

```yaml (paste below)
- community.general.sudoers:
        name: admin
        user: myadmin
        commands: ALL
        nopassword: true
        defaults:           ### THIS
             - !requiretty ### THIS
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/sudoers.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/sudoers.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @JonEllis
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Sneedes** [comment]
Seconding this feature request.

Would like to be able to add/set defaults like
`lecture = never`
`passwd_tries = 0`

for the specified user or group in the sudoers.d file.

**Comment by JonEllis** [comment]
Appologies for a bit of a ramble here. I'm aware perfect is the enemy of good, but I can imagine that once this is supported, the extra use cases will arrise.

Defaults seem reasonable, but they're not all boolean flags - flags (boolean), integers, strings, and lists are possible values.
So I'd assume we'd need something like this?

```yaml
- community.general.sudoers:
    name: admin
    user: myadmin
    commands: ALL
    nopassword: true
    defaults:
      requiretty: false
      log_servers:
        - 10.10.10.10
        - 10.10.10.11
```

Which I _guess_ would generate such a sudoers file in `/etc/sudoers.d/admin`?
```
myadmin ALL=(ALL) NOPASSWD:ALL
Defaults !requiretty
Defaults log_servers="0.10.10.10 10.10.10.11"
```

Difficulty might come in should different options need to be handled differently.
Indeed, the examples given in a standard sudoers file in an Ubuntu installation seem more complex still, with the addition of items to existing lists(?):
```
Defaults:%sudo env_keep += "EDITOR"
```

I'm wondering whether this should be a separate module for managing defaults.
For instance, if we specify a user or group for a command, would that user/group also be used for the defaults rule too?
I also see the case where you want to set defaults, but not authenticate a user for some or all commands.

Perhaps something on these lines:
```yaml
- community.general.sudoers_defaults:
    name: mydefaults
    defaults:
      requiretty: false
      log_servers:
        - 10.10.10.10
        - 10.10.10.11
```

Something extra would be required to support the case of adding to lists. perhaps an `append` flag on the module. but would this be messy if we want more than one.

How about an `extra` or `raw` parameter, where the module can append whatever text is given to the file.
While this is potentially a bad thing, at least we validate files (where possible), so the task would fail for invalid data.
