### ISSUE TITLE
`github_key` method to read keys

### ISSUE THREAD

**Issue by matthewgrossman** [ansible-collections/community.general#6547]
### Summary

When I provision a new computer with ansible, I would like to download the public keys I have uploaded to github and add it to the new machine's `authorized_keys`. To do this, I could just use the github API, get each SSH pubkey, then use the [authorized_key module](https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html).

The `github_key` module actually already has a helper method to grab all of the keys, but simply no way to just spit out the results to `register`: https://github.com/ansible-collections/community.general/blob/main/plugins/modules/github_key.py#LL136C5-L136C17

What I'm proposing here is adding something new to the `github_key` module that'll let us store the output into a variable, something like this:
```yaml
- name: Get ssh keys from Github
  github_key_read:
    token: '{{ github_access_token }}'
    name: '{{ maybe_name_to_match_filter }}'
  register: ssh_keys
- name: Add ssh keys to authorized_keys
   ansible.posix.authorized_key:
       ... something to iterate over each ssh_key in ssh_keys ...
```

### Issue Type

Feature Idea

### Component Name

github_key

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
