### ISSUE TITLE
postgresql_privs fails with schema name which contain '-' (dash) character 

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.general#656]
_From @vosmax on Jul 15, 2020 14:44_

##### SUMMARY

Task with module **postgresql_privs** fails with error when it's trying to apply default privileges to schema with name, which contain '-' (dash) character.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_privs

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = None
  configured module search path = ['/Users/ilon.mask/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT

MacOS Catalina 10.15.5

##### STEPS TO REPRODUCE

```yaml
vars:
  postgres_db:
     host: localhost
     user: test
     password: test 
     db: test 
     schema: "test-schema"
     role: "my-role"

- name: Set default privs 
  postgresql_privs:
     login_host: "{{ postgres_db.host }}"
     login_user: "{{ postgres_db.user }}"
     login_password: "{{ postgres_db.password }}"
     login_db: "{{ postgres_db.db  }}"
     schema: "{{ postgres_db.schema | quote }}"
     role: "{{ postgres_db.role }}"
     type: default_privs
     obj: TABLES
     privs: all
```

##### EXPECTED RESULTS

Default privileges are applied to the schema 

##### ACTUAL RESULTS

```paste below
"msg": "syntax error at or near \"-\"\nLINE 1: ALTER DEFAULT PRIVILEGES IN SCHEMA test-schema REVOKE A...\n
```

_Copied from original issue: ansible/ansible#70654_
