### ISSUE TITLE
Add an option to update any flatpaks if updates are available

### ISSUE THREAD

**Issue by RichardJActon** [ansible-collections/community.general#6563]
### Summary

When I make an adjustment to my Ansible playbook and apply it to an existing system with flatpaks installed, it would be convenient if I could configure it so that the flatpaks are automatically updated when I re-run the playbook.

### Issue Type

Feature Idea

### Component Name

flatpak

### Additional Information

I'm not sure what the convention if any is for doing this but two different approaches to setting this option occured to me:

Have a `state` option which asserts that the flatpaks should be up-to-date:

```yaml
  - name: Install flatpaks
    flatpak:
      name:
        # utilities 
        - com.github.tchx84.Flatseal
      state: uptodate
```

Having a seperate option for enabling auto-updates

```yaml
  - name: Install flatpaks
    flatpak:
      autoupdate: true
      name:
        # utilities 
        - com.github.tchx84.Flatseal
      state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
