### ISSUE TITLE
nmcli: clear out routes4_extended

### ISSUE THREAD

**Issue by mdidomenico4** [ansible-collections/community.general#6574]
### Summary

given this syntax how does one clear out any existing routes from the table?

```
- name: Setting up infiniband interfaces
   community.general.nmcli:
     conn_name: "{{ item.conn_name }}"
     ifname: "{{ item.conn_name }}"
     type: "{{ item.type }}"
     ip4: "{{ item.ip4 }}"
    routes4_extended: "{{ item.routes4_extended | default([]) }}"
```

the variables are pulled from a table in the vars section, but if no routes4_extended entry exists in the table i'd like the command to make sure that the field is empty in nmcli

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.3]
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /ansible/ansible_ccm/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /ansible/ansible_ccm/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.0.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/ansible/ansible.cfg) = ['/ansible/ansible_ccm/collections']
DEFAULT_FACT_PATH(/ansible/ansible.cfg) = /ansible/ansible_ccm/facts
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/ansible_ccm/inventory/inventory.py']
DEFAULT_VAULT_PASSWORD_FILE(/ansible/ansible.cfg) = /ansible/etc/vault-pass
DEPRECATION_WARNINGS(/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/ansible/ansible.cfg) = /usr/bin/python3.6
INVENTORY_UNPARSED_IS_FAILED(/ansible/ansible.cfg) = True
```

### OS / Environment

rhel8

### Steps to Reproduce

```yaml (paste below)
see description
```

### Expected Results

nmcli c s doesn't have any entries in the routes heading

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
