### ISSUE TITLE
community.general.proxmox_snap trim snapshots

### ISSUE THREAD

**Issue by lexxxel** [ansible-collections/community.general#6576]
### Summary

I would like to be able to trim proxmox snapshots. e.g. I have a gitlab pipeline that snapshots a lxc before each deployment. Over time this will hurt performance and storage. I would like to have the option to create a new snapshot and only keep the last X snapshots.

### Issue Type

Feature Idea

### Component Name

proxmox_snap

### Additional Information

```yaml (paste below)
- name: Create new container snapshot and keep only the 2 newest snapshots
  community.general.proxmox_snap:
    api_user: root@pam
    api_password: 1q2w3e
    api_host: node1
    vmid: 100
    state: present
    snapname: snapshot-42
    trim: 2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
