### ISSUE TITLE
onepassword lookup with service account

### ISSUE THREAD

**Issue by Domi-cc** [ansible-collections/community.general#6635]
### Summary

1password has new service accounts. via lookup should be possible to get secrets.

we can offer to contribute, but want to know, do you want a new lookup file for that, or should we try to expand: plugins/lookup/onepassword.py ?

### Issue Type

Feature Idea

### Component Name

lookup onepassword

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/lookup/onepassword.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/lookup/onepassword.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @azenk @samdoran @scottsb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Domi-cc** [comment]
Hey @samdoran added the service_account_token. Works everything fine. Please review and feel free to change or improve the PR. Thanks!

**Comment by BlexToGo** [comment]
I was looking at using service accounts for my Ansible playbook since I need an initial sign in and don't want to use my master password with unrestricted read/write access to all vaults for security reasons, so I tried out @Domi-cc's fork directly instead of waiting for the 7.1.0 release by installing it via:
```
ansible-galaxy collection install git@github.com:Domi-cc/community.general.git,onepassword-lookup-add-service-accounts
```
And I can confirm that it works as expected. Had just to pass my generated token with the `service_account_token` parameter and could retrieve secrets from the corresponding vault.

**Comment by samdoran** [comment]
This is indeed a much better way to do things than passing around the master password. I'm glad service account tokens are a thing now.

**Comment by kitforbes** [comment]
Sorry to respond to an old issue, but I'm unclear about how to use the service account when the token is set in the environment. The [docs](https://docs.ansible.com/ansible/latest/collections/community/general/onepassword_lookup.html) have no examples sadly.

I have set `OP_SERVICE_ACCOUNT_TOKEN` and confirmed that Ansible can see it with the `ansible.builtin.env` lookup
```yaml
- name: debug | Read from environment
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.env', 'OP_SERVICE_ACCOUNT_TOKEN') }}"
```
It all works fine when I explicitly use the token from a variable
```yaml
- name: debug | Retrieve with explicit assignment
  ansible.builtin.debug:
    var: lookup('community.general.onepassword', 'entry', vault='infra', service_account_token='{{ op_sa_token }}')
```
But doesn't seem to work when relying on the environment variable
```yaml
- name: debug | Retrieve with environment variable
  ansible.builtin.debug:
    var: lookup('community.general.onepassword', 'entry', vault='infra')
```
And the error it gives is 
> fatal: [host]: FAILED! => {"msg": "Unable to sign in to 1Password. Missing required parameters: master_password, secret_key, username, subdomain."}

I'd like to avoid using a variable, so any tips on using this with an environment variable would be appreciated!
