### ISSUE TITLE
Composite variables support for Proxmox nodes in dynamic inventory plugin

### ISSUE THREAD

**Issue by levytskyip** [ansible-collections/community.general#6640]
### Summary

In my environment Proxmox nodes are assigned an IP address in management VLAN and DNS name in a subdomain of my local domain. Currently if I try to configure the `ansible_host` variable in `compose:` section it will only work for hosts on the Proxmox nodes but not for the nodes themselves.

### Issue Type

Feature Idea

### Component Name

plugins/inventory/proxmox.py

### Additional Information

```yaml
plugin: community.general.proxmox
url: https://pve.domain.local:8006
want_facts: false
want_proxmox_nodes_ansible_host: false
compose:
   ansible_host: inventory_hostname + '.domain. Local'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
