### ISSUE TITLE
snap: set config of snaps

### ISSUE THREAD

**Issue by monkz** [ansible-collections/community.general#666]
##### SUMMARY
It should be possible to set configurations for snaps.
Example: lxd has configuration lxcfs.loadavg, lxcfs.cfs, lxcfs.pidfd

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
snap

##### ADDITIONAL INFORMATION
```
# snap get -d lxd 
{
	"lxcfs": {
		"cfs": false,
		"loadavg": true,
		"pidfd": true
	}
}
```
Per default the return of snap get is `{}`. In this case it was set via:
```
snap set lxd lxcfs.loadavg=true
snap set lxd lxcfs.cfs=false
snap set lxd lxcfs.pidfd=true
```

as snap get -d returns json It is possible to diff and set values according to a task in a playbook.
```
    - name: ensure lxd is installed with config
      snap:
        name: lxd
        config:
           lxcfs:
              cfs: false
              pidfd: true
              loadavg: true

```
