### ISSUE TITLE
redfish_info: GetNetworkProtocols does not support resource_id parameter

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#6764]
### Summary

When I attempt to use a task such as:

```
- name: Get network protocol settings
    community.general.redfish_info:
      category: Manager
      command: GetNetworkProtocols
      baseuri: "{{ bmc_address }}"
      username: "{{ bmc_username }}"
      password: "{{ bmc_password }}"
    register: protocol_output
```

I receive the following:
```
ok: [localhost] => {
    "enable_ipmi_lan": {
        "attempts": 1,
        "changed": false,
        "failed": false,
        "redfish_facts": {
            "network_protocols": {
                "entries": {
                    "HTTP": {
                        "Port": 80,
                        "ProtocolEnabled": true
                    },
                    "SSH": {
                        "Port": 22,
                        "ProtocolEnabled": true
                    }
                },
                "ret": true
            }
        }
    }
}
```

which is not coming from the main system manager as expected. The system BMC itself returns the expected full configuration:

```
  "HTTPS": {
    "Certificates": {
      "@odata.id": "/redfish/v1/Managers/Self/NetworkProtocol/HTTPS/Certificates"
    },
    "Port": 443,
    "ProtocolEnabled": true
  },
  "HostName": "bmcHostname",
  "IPMI": {
    "Port": 623,
    "ProtocolEnabled": true
  },
  "Id": "NetworkProtocol",
  "KVMIP": {
    "Port": 443,
    "ProtocolEnabled": true
  },
  "NTP": {
    "NTPServers": [
      "time.domain.com",
      null
    ],
    "Port": 123,
    "ProtocolEnabled": true
  },
  "Name": "Manager Network Protocol",
  "SNMP": {
    "AuthenticationProtocol": "Account",
    "EnableSNMPv1": true,
    "EnableSNMPv2c": true,
    "EnableSNMPv3": true,
    "EncryptionProtocol": "Account",
    "EngineId": {
      "ArchitectureId": "80 26 a4 36 56 64 a8 4a 64",
      "PrivateEnterpriseId": "80 00 1f 88"
    },
    "Port": 161,
    "ProtocolEnabled": true
  },
  "SSDP": {
    "Port": 1900,
    "ProtocolEnabled": true
  },
  "SSH": {
    "Port": 22,
    "ProtocolEnabled": true
  },
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  },
  "VirtualMedia": {
    "Port": 443,
    "ProtocolEnabled": true
  }
}
```

### Issue Type

Bug Report

### Component Name

redfish_info

### Ansible Version

```
ansible [core 2.14.5]
  config file = /home/username/Github/fwmanager/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/username/.local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```
Collection        Version
----------------- -------
community.general 6.5.0
```

### Configuration

```
ANSIBLE_NOCOLOR(env: NO_COLOR) = False
CALLBACKS_ENABLED(/home/username/Github/fwmanager/ansible.cfg) = ['ansible.posix.profile_tasks', 'timer']
CONFIG_FILE() = /home/username/Github/fwmanager/ansible.cfg
DEFAULT_GATHERING(/home/username/Github/fwmanager/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/username/Github/fwmanager/ansible.cfg) = merge
DEFAULT_TIMEOUT(/home/username/Github/fwmanager/ansible.cfg) = 120
HOST_KEY_CHECKING(/home/username/Github/fwmanager/ansible.cfg) = False
INTERPRETER_PYTHON(/home/username/Github/fwmanager/ansible.cfg) = auto
LOCALHOST_WARNING(/home/username/Github/fwmanager/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/username/Github/fwmanager/ansible.cfg) = 360
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/username/Github/fwmanager/ansible.cfg) = 180
PERSISTENT_CONNECT_TIMEOUT(/home/username/Github/fwmanager/ansible.cfg) = 360
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

On a system with multiple managers available:

```
---
- name: test redfish facts
  gather_facts: false
  hosts: localhost
  connection: local

  tasks:
  - name: Get network protocol settings
     community.general.redfish_info:
       category: Manager
       command: GetNetworkProtocols
       baseuri: "{{ bmc_address }}"
       username: "{{ bmc_username }}"
       password: "{{ bmc_password }}"
    register: protocol_output
```

### Expected Results

I expect to see all the protocol services available on the specified manager of my choosing

### Actual Results

Per above, I only get a minimal list of service data back from the first manager returned, which happens to be a separate device from the BMC:

```
"HTTP": {
                        "Port": 80,
                        "ProtocolEnabled": true
                    },
                    "SSH": {
                        "Port": 22,
                        "ProtocolEnabled": true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
