### ISSUE TITLE
Add `IdentitiesOnly` parameter to `ssh_config` module

### ISSUE THREAD

**Issue by lonix1** [ansible-collections/community.general#6801]
### Summary

When multiple ssh keys are defined for a host, one quickly runs into connection problems.

The solution is to use `IdentitiesOnly` in `~/.ssh/config`, e.g.
```ini
Host github1
    Hostname github.com
    User git
    IdentityFile /home/me/.ssh/id_rsa_github_1
    IdentitiesOnly yes                           # <-----------------
Host github2
    Hostname github.com
    User git
    IdentityFile /home/me/.ssh/id_rsa_github_2
    IdentitiesOnly yes                           # <-----------------
```
But the [`community.general.ssh_config`](https://docs.ansible.com/ansible/latest/collections/community/general/ssh_config_module.html) does not expose an equivalent parameter.

Please consider adding one (with default false)? Then we could do this:
```yml
- community.general.ssh_config:
    user: me
    host: github1
    hostname: github.com
    identity_file: /home/me/.ssh/id_rsa_github_1
    identities_only: true                         # <------------------- default false
- community.general.ssh_config:
    user: me
    host: github2
    hostname: github.com
    identity_file: /home/me/.ssh/id_rsa_github_2
    identities_only: true                         # <------------------- default false
```

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

From `$ man ssh_config`:
```
IdentitiesOnly
        Specifies that ssh(1) should only use the configured authentica‐
        tion identity and certificate files (either the default files, or
        those explicitly configured in the ssh_config files or passed on
        the ssh(1) command-line), even if ssh-agent(1) or a
        PKCS11Provider or SecurityKeyProvider offers more identities.
        The argument to this keyword must be yes or no (the default).
        This option is intended for situations where ssh-agent offers
        many different identities.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
