### ISSUE TITLE
redhat_subscription: options have exclusivity and dependence (activationkey and auto_attach)

### ISSUE THREAD

**Issue by wespiard** [ansible-collections/community.general#6802]
### Summary

When trying to register using a server URL and activation key, I'm unable to also set `auto_attach` to true due to an exclusivity error between `auto_attach` and `activationkey`. However, if I try to run `auto_attach` in a second play, I then get an error saying that `activationkey` is required to use `auto_attach`.

I am able to run the following on the target machine without any issues:
```console
$ subscription-manager register --baseurl <url> --org <org> --activationkey <key>
$ subscription-manager attach --auto
```

### Issue Type

Bug Report

### Component Name

redhat_subscription

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.10]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 5.8.3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
- name: RedHat Subscription
      community.general.redhat_subscription:
        state: present
        rhsm_baseurl: <url>
        org_id: <org>
        activationkey: <key>
        auto_attach: true
```

### Expected Results

I expect the subscription to be registered, and then auto-attach to be set.

### Actual Results

```console (paste below)
"msg": "parameters are mutually exclusive: activationkey|auto_attach"
```

I also tried doing two separate plays (one to register, and a second to just auto-attach).

When running the following two plays:

```yaml
    - name: RedHat Subscription
      community.general.redhat_subscription:
        state: present
        rhsm_baseurl: <url>
        org_id: <id>
        activationkey: <key>

    - name: RedHat Subscription (auto-attach)
      community.general.redhat_subscription:
        auto_attach: true
```

I get the following error: 
```console (paste below)
"msg": "parameters are mutually exclusive: activationkey|auto_attach"
```

So `activationkey` is required for `auto_attach`, but they are also mutually exclusive.

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
