### ISSUE TITLE
Error when installing packages with snap after update to 8.1.0

### ISSUE THREAD

**Issue by maciejkra** [ansible-collections/community.general#6803]
### Summary

When trying to update install packages via snap module after upgrade to ansible 8.1.0 the task fails. Although they are properly installed.
Rolling back to the previous version (7.x) solves the issue.

### Issue Type

Bug Report

### Component Name

snap

### Ansible Version

```console (paste below)
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/Users/jamicque/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.1.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jamicque/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.1.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
empty
```

### Configuration

```console (paste below)
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

### OS / Environment

Os X 13.4.1 (22F82)

### Steps to Reproduce

```yaml (paste below)
- name: install microk8s on the host
  remote_user: root
  hosts: all
  gather_facts: false
  tasks:
  - name: install microk8s & kubectl
    snap:
      name:
        - microk8s
        - kubectl
      classic: yes

```

### Expected Results

installed microk8s and kubectl without errors

### Actual Results

https://gist.github.com/maciejkra/51d283c5b066a231fe38d6ad0aa02407

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
