### ISSUE TITLE
SRV Records are not correctly managed by Identity DNS (IPA)

### ISSUE THREAD

**Issue by Koma-Andrea** [ansible-collections/community.general#682]
**NOTE:**
This problem has already been stated in at least 3 issues in the old repo:

https://github.com/ansible/ansible/issues/69621
https://github.com/ansible/ansible/issues/33193
https://github.com/ansible/ansible/pull/66170

_There are tentative addressing this problem in the past issues but there is no idempotent solution AFAIK._

**The problem itself:**
You should be able to append values to a record or to substitute it if the record already exist.
I.E. Tipically an SRV or a MX record will contain many values and those values may change during time.

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
@Koma-Andrea: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Koma-Andrea** [comment]
edit: updated the description as requested

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/identity/ipa/ipa_dnsrecord.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/identity/ipa/ipa_dnsrecord.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Akasurde @Nosmoht @fxfitz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Elyytscha** [comment]
an example where this occur is

```
base_ipa_dns_entrys:
  - name: _etcd-server-ssl._tcp.cloud.domain.com.
    domain: domain.com
    type: SRV
    record: '0 10 2380 etcd-0.cloud.domain.com.'
  - name: _etcd-server-ssl._tcp.cloud.domain.com.
    domain: domain.com
    type: SRV
    record: '0 10 2380 etcd-1.cloud.domain.com.'
  - name: _etcd-server-ssl._tcp.cloud.domain.com.
    domain: domain.com
    type: SRV
    record: '0 10 2380 etcd-2.cloud.domain.com.'

-  name: Add DNS Entries
   ipa_dnsrecord:
     name: "{{ item.name }}"
     zone_name: "{{ item.domain }}"
     state: "{{ item.state | default('present') }}"
     record_type: "{{ item.type }}"
     record_value: "{{ item.record }}"
     ipa_host: "{{ ipa_host }}"
     ipa_user: "{{ ipa_user }}"
     ipa_pass: "{{ ipa_pass }}"
     validate_certs: false
   loop: "{{ base_ipa_dns_entries }}"
```

this does not result in a srv record containing the valid wanted 3 records

this results in a srv record with the last item as record
