### ISSUE TITLE
Redfish Account settings

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#6823]
### Summary

I am trying to set the "AccountTypes" array for a Redfish user and it doesn't appear to be supported in the current redfish_command module.

We are looking to do the equivalent of:
```
curl -v -s -k -L -X PATCH -u bmcuser:bmcpass
https://x.x.x.x/redfish/v1/AccountService/Accounts/4
-H "If-Match: W/"XXXXXXX""
-H 'Content-Type: application/json'
-d '{ "AccountTypes": [ "Redfish", "KVMIP" ]}'
```

### Issue Type

Feature Idea

### Component Name

redfish_command

### Additional Information

Ideally it would be great to have an option like:

```
- name: Add user
  community.general.redfish_command:
    category: Accounts
    command: UpdateUser/AddUser
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    new_username: "{{ new_username }}"
    new_password: "{{ new_password }}"
    roleid: "{{ roleid }}"
    account_types:
      - KVMIP
      - Redfish
      - SNMP
      - etc
```

Thanks!

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
