### ISSUE TITLE
java_keystore module failing - unexpected keyword argument 'path

### ISSUE THREAD

**Issue by JensVD** [ansible-collections/community.general#6853]
### Summary

When I try to create a JKS using the java_keystore module this fails with the underlying exception:

```
{
	"changed": false,
	"module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.general.java_keystore_payload_17biq5uy/ansible_community.general.java_keystore_payload.zip/ansible_collections/community/general/plugins/modules/java_keystore.py\", line 578, in <module>\n  File \"/tmp/ansible_community.general.java_keystore_payload_17biq5uy/ansible_community.general.java_keystore_payload.zip/ansible_collections/community/general/plugins/modules/java_keystore.py\", line 570, in main\n  File \"/tmp/ansible_community.general.java_keystore_payload_17biq5uy/ansible_community.general.java_keystore_payload.zip/ansible_collections/community/general/plugins/modules/java_keystore.py\", line 265, in update_permissions\nTypeError: load_file_common_arguments() got an unexpected keyword argument 'path'\n",
	"module_stdout": "",
	"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
	"rc": 1
}
```

### Issue Type

Bug Report

### Component Name

community.general.java_keystore

### Ansible Version

```console (paste below)
$ ansible --version

ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/hcadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Jan 25 2023, 15:03:30) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install'
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=accept-new
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/collections']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles', '/usr/share/ansible/roles', '/home/hcadmin/ansible/roles']
MAX_FILE_SIZE_FOR_DIFF(/etc/ansible/ansible.cfg) = 1048576
```

### OS / Environment

CentOS 8 Stream

### Steps to Reproduce

```yaml (paste below)

- name: Generate the private key for the server certificate
  openssl_privatekey:
    path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
    unsafe_writes: yes

- name: Generate the CSR for the server certificate
  openssl_csr:
    path: "/etc/pki/tls/csr/{{ inventory_hostname }}.csr"
    privatekey_path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
    common_name: "{{ inventory_hostname }}"
    country_name: US
    state_or_province_name: California
    locality_name: Silicon Valley
    organization_name: RedHat
    organizational_unit_name: Operations
    email_address: test@redhat.be
    key_usage:
      - digitalSignature
      - keyEncipherment
    keyUsage_critical: yes
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_critical: no
    subject_alt_name: 'DNS:{{ inventory_hostname }},IP:{{ ansible_default_ipv4.address }}'
    subject_alt_name_critical: yes
    use_common_name_for_san: no
    unsafe_writes: yes

- name: Generate the server certificate (Valid for 10 years)
  openssl_certificate:
    path: "/etc/pki/tls/certs/{{ inventory_hostname }}.crt"
    ownca_path: "/etc/pki/tls/certs/intermediate-ca.crt"
    ownca_privatekey_path: "/etc/pki/tls/private/intermediate-ca.key"
    ownca_privatekey_passphrase: "{{ intermediate_ca_key_pw }}"
    csr_path: "/etc/pki/tls/csr/{{ inventory_hostname }}.csr"
    subject:
      C: US
      ST: California
      L: Silicon Valley
      O: Redhat
      OU: Operations
      CN: "{{ inventory_hostname }}"
      email: test@redhat.com
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_strict: yes
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_strict: no
    subject_alt_name: 'DNS:{{ inventory_hostname }},IP:{{ ansible_default_ipv4.address }}'
    subject_alt_name_strict: yes
    provider: ownca
    not_after: 20291231235900Z
    unsafe_writes: yes

- name: Generate JKS keystore when required
  community.general.java_keystore:
    name: "{{ inventory_hostname }}"
    certificate_path: "/etc/pki/tls/certs/{{ inventory_hostname }}.crt"
    private_key_path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
    password: "{{ server_keystore_pw }}"
    dest: "/etc/pki/tls/jks/{{ inventory_hostname }}.jks"
```

### Expected Results

I expected a keystore to be created, changed or unchanged but I got an error.

### Actual Results

```console (paste below)
{
	"changed": false,
	"module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.general.java_keystore_payload_17biq5uy/ansible_community.general.java_keystore_payload.zip/ansible_collections/community/general/plugins/modules/java_keystore.py\", line 578, in <module>\n  File \"/tmp/ansible_community.general.java_keystore_payload_17biq5uy/ansible_community.general.java_keystore_payload.zip/ansible_collections/community/general/plugins/modules/java_keystore.py\", line 570, in main\n  File \"/tmp/ansible_community.general.java_keystore_payload_17biq5uy/ansible_community.general.java_keystore_payload.zip/ansible_collections/community/general/plugins/modules/java_keystore.py\", line 265, in update_permissions\nTypeError: load_file_common_arguments() got an unexpected keyword argument 'path'\n",
	"module_stdout": "",
	"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
	"rc": 1
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
