### ISSUE TITLE
archive exclude_path can't exclude directories below 2nd level

### ISSUE THREAD

**Issue by elburro1887** [ansible-collections/community.general#6857]
### Summary

When running archive, it is not possible to exclude a directory or files that are below the 2nd level of hierarchy

Backup path
- `/home/user/foldertobackup/*`

I want to exclude the folder (and its contents):
- `/home/user/foldertobackup/subdir3/subsubdir4`

### Issue Type

Bug Report

### Component Name

plugins/modules/archive.py

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.1]
  config file = /Users/zzz/coding/prs/servertools/backup_ansible/ansible.cfg
  configured module search path = ['/Users/zzz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/zzz/.pyenv/versions/3.9.16/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/zzz/.pyenv/versions/3.9.16/bin/ansible
  python version = 3.9.16 (main, Jul  4 2023, 14:48:26) [Clang 12.0.0 (clang-1200.0.32.29)] (/Users/zzz/.pyenv/versions/3.9.16/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Mac OS and Debian Bullseye tested

### Steps to Reproduce

```yaml (paste below)

 - name: Create backup of files/directories - TEST
      community.general.archive:
        path: 
          - "/home/user/foldertobackup/*"
          - "/home/user/foldertobackup/subdir3/*"
        dest: "/home/user/backup/myarchive.gz"
        format: gz
        mode: 0644
        exclude_path: 
          - "/home/user/foldertobackup/log"
          - "/home/user/foldertobackup/sql"
          - "/home/user/foldertobackup/subdir3/subsubdir4"
```

### Expected Results

The archive should not contain the folder or any files in it: 

- `/home/user/foldertobackup/subdir3/subsubdir4`

### Actual Results

Archive contains the folder (among others)
- `/home/user/foldertobackup/subdir3/subsubdir4`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/archive.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/archive.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bendoh
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by paradox-lab** [comment]
how about this?

```yml
 - name: Create backup of files/directories - TEST
      community.general.archive:
        path: 
          - "/home/user/foldertobackup/*"
          - "/home/user/foldertobackup/subdir3/*"
        dest: "/home/user/backup/myarchive.gz"
        format: gz
        mode: 0644
        exclude_path: 
          - "/home/user/foldertobackup/log"
          - "/home/user/foldertobackup/sql"
          # ​avoid walking the whole path again and reinclude the mentioned subdirectory and its contents
          - "/home/user/foldertobackup/subdir3"
          - "/home/user/foldertobackup/subdir3/subsubdir4"

```
