### ISSUE TITLE
ipa_dnsrecord: please implement management of NS type records

### ISSUE THREAD

**Issue by macrokernel** [ansible-collections/community.general#6910]
### Summary

I am trying to create an NS record using the following ansible script
```yaml
      community.general.ipa_dnsrecord:
        ipa_host: "{{ ipa_host }}"
        ipa_user: "{{ ipa_user }}"
        ipa_pass: "{{ ipa_password }}"
        state: present
        zone_name: "{{ domain }}"
        record_type: "NS"
        record_name: "consul"
        record_value: "consul-server-1.{{ domain }}."
      run_once: true
```
and am getting the following error:
```
value of record_type must be one of: A, AAAA, A6, CNAME, DNAME, PTR, TXT, SRV, MX, got: NS
```

A, CNAME and SRV records are working fine.

### Issue Type

Feature Idea

### Component Name

[plugins/modules/ipa_dnsrecord.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ipa_dnsrecord.py)

### Additional Information

```yaml
      community.general.ipa_dnsrecord:
        ipa_host: "{{ ipa_host }}"
        ipa_user: "{{ ipa_user }}"
        ipa_pass: "{{ ipa_password }}"
        state: present
        zone_name: "{{ domain }}"
        record_type: "NS"
        record_name: "consul"
        record_value: "consul-server-1.{{ domain }}."
      run_once: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
