### ISSUE TITLE
proxmox_kvm: Create VM without providing vmid not idempotent

### ISSUE THREAD

**Issue by wozniaka** [ansible-collections/community.general#6911]
### Summary

When I try to run playbook that uses `community.general.proxmox_kvm` module to create a new VM without specifying its `vmid` and with the same `name` more than one time, new one with different `vmid` is always created.

Module behaviour changed with version `7.1.0` due to issue #6155.

Possible solution is to change the following:
https://github.com/ansible-collections/community.general/blob/2e0079cb3e683915d7421461839bd653f85334a4/plugins/modules/proxmox_kvm.py#L1265-L1273

to something like that:

```python
   if not vmid:
        if state == 'present' and not update and not clone and not delete and not revert and not migrate:
            existing_vmid = proxmox.get_vmid(name, ignore_missing=True)
            if existing_vmid:
                vmid = existing_vmid
            else:
                try:
                    vmid = proxmox.get_nextvmid()
                except Exception:
                    module.fail_json(msg="Can't get the next vmid for VM {0} automatically. Ensure your cluster state is good".format(name))
        else:
            clone_target = clone or name
            vmid = proxmox.get_vmid(clone_target, ignore_missing=True)
```

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.0]
...
    python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
...
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

```console
$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

```console
$ pip3 list | grep -iE "proxmoxer|requests"
proxmoxer          2.0.1
requests           2.31.0
```

### Steps to Reproduce

Run following playbook at least to times. With each run new VM named `test-vm` with different `vmid` is created.

In this test case fist playbook run creates a VM named `test-vm` with `vmid: 100`.

```yaml (paste below)
- hosts: localhost
  gather_facts: false
  vars_files:
    - api_credentials.yml
  tasks:
    - name: Deploy VM
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: pve
        name: test-vm
        state: present
```

### Expected Results

After discovering that VM with name `test-vm` already exists and no `vmid` was provided module shouldn't make any changes (`changed: false`, unless `update: true` or related flags are set) and return info about previously created one (as in `7.0.0`)

First run:
```console
$ ansible-playbook -v test.yml
changed: [127.0.0.1] => {
    "changed": true,
    "devices": {},
    "mac": {},
    "msg": "VM test-vm with vmid 100 deployed",
    "vmid": 100
}
```

Second run:
```console
$ ansible-playbook -v test.yml
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "VM with name <test-vm> already exists",
    "vmid": 100
}
```

### Actual Results

Multiple VM instances with different `vmid` and the same `name` are created every playbook run.

First run:
```console
$ ansible-playbook -v test.yml
changed: [127.0.0.1] => {
    "changed": true,
    "devices": {},
    "mac": {},
    "msg": "VM test-vm with vmid 100 deployed",
    "vmid": 100
}
```
Second run:
```console (paste below)
$ ansible-playbook -v test.yml
changed: [127.0.0.1] => {
    "changed": true,
    "devices": {},
    "mac": {},
    "msg": "VM test-vm with vmid 101 deployed",
    "vmid": 101
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
