### ISSUE TITLE
dnsmadesy 

### ISSUE THREAD

**Issue by quenode** [ansible-collections/community.general#6971]
### Summary

Hi we go error using playbook and dnsmadeesy.py

TASK [dns-made-easy : Fetch mydomain.com domain record] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "parameters are required together: record_value, record_ttl, record_type"}

We are using simple task to fetch domain into json as example i shown 
Here is the task role 

```

# tasks file for dnsmadeeasy
- name: Fetch mydomain.com domain record
  moz.worker.dnsmadeeasy:
    account_key: '888888888'
    account_secret: '8888888'
    domain: mydomain.com
    state: present
  register: response

```

Looks like there is an problem somewhere with var required_together=[] we removed the required_together and fixed the problem. But it's as nasty workaround.  

       ```
     httpQueryString=dict(required=False),
            failover=dict(default=False, type='bool'),
            autoFailover=dict(default=False, type='bool'),
            ip1=dict(required=False),
            ip2=dict(required=False),
            ip3=dict(required=False),
            ip4=dict(required=False),
            ip5=dict(required=False),
            validate_certs=dict(default=True, type='bool'),
        ),
        required_together=[
            ['record_value', 'record_ttl', 'record_type']
        ],
        required_if=[
            ['failover', True, ['autoFailover', 'port', 'protocol', 'ip1', 'ip2']],
            ['monitor', True, ['port', 'protocol', 'maxEmails', 'systemDescription', 'ip1']]
        ]
    )

 
```

So maybe some could solve this better ?

### Issue Type

Bug Report

### Component Name

dnsmadeeasy.py

### Ansible Version

ansible [core 2.15.2]

### Community.general Version

Collection        Version
----------------- -------
community.general 7.2.0

### Steps to Reproduce

```

# tasks file for dnsmadeeasy
- name: Fetch mydomain.com domain record
  moz.worker.dnsmadeeasy:
    account_key: '888888888'
    account_secret: '8888888'
    domain: mydomain.com
    state: present
  register: response

```

### Expected Results

fetch no error 

### Actual Results

```
TASK [dns-made-easy : Fetch mydomain.com domain record] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "parameters are required together: record_value, record_ttl, record_type"}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
