### ISSUE TITLE
The 'Expand variable reference' flag in the variable properties is not supported by the gitlab_project_variable.py module

### ISSUE THREAD

**Issue by ltraveler** [ansible-collections/community.general#6973]
### Summary

The variable flag 'Expand variable reference' was introduced in GitLab version 15.7, but it is still not supported by the gitlab_project_variable module. Could you please add it, as it is a very useful function?

![image](https://github.com/ansible-collections/community.general/assets/5625337/b299205d-c234-4e44-9576-9c4e85039bb8)

### Issue Type

Feature Idea

### Component Name

gitlab_project_variable

### Additional Information

```yaml (paste below)
- name: Set or update some CI/CD variables
  community.general.gitlab_project_variable:
    api_url: https://gitlab.com
    api_token: secret_access_token
    project: markuman/dotfiles
    purge: false
    vars:
      ACCESS_KEY_ID: abc123
      SECRET_ACCESS_KEY:
        value: 3214cbad
        masked: true
        raw: true
        protected: true
        variable_type: env_var
        environment_scope: '*'
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
