### ISSUE TITLE
Proxmox v8 incompatibility

### ISSUE THREAD

**Issue by dusatvoj** [ansible-collections/community.general#6974]
### Summary

When I want to create a VM via proxmox_kvm module @ proxmox 8.0.3, I'm stuck with this message:
```
"msg": "Unable to retrieve Proxmox VE version: 'ProxmoxKvmAnsible' object has no attribute 'proxmox_api'
```

### Issue Type

Bug Report

### Component Name

`community.general.proxmox_kvm`

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.1
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```
(running via ansible-semaphore)

### OS / Environment

Debian 11

### Steps to Reproduce

There's a role I've copied and just used parametrized for me. It worked great before upgrade to PVE 8

https://github.com/pvelati/ansible-role-proxmox-kvm-mgmt/tree/master

### Expected Results

It work's with PVE 8

### Actual Results

```console (paste below)
... "msg": "Unable to retrieve Proxmox VE version: 'ProxmoxKvmAnsible' object has no attribute 'proxmox_api' ...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/proxmox_kvm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @UnderGreen @helldorado @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by UnderGreen** [comment]
Fixed in #6980. Feel free to close the issue.

**Comment by Drugoy** [comment]
I have Proxmox-VE 8.0.3 and I didn't experience the issue even before the yesterday's fix.
However, I am not using token auth, just plain simple API auth was used instead.

**Comment by UnderGreen** [comment]
@Drugoy issue was related to token auth and was broken for all versions.

**Comment by Drugoy** [comment]
@UnderGreen I got it from your PR, but this ticket's summary doesn't reflect that the bug was narrower than described.

**Comment by dusatvoj** [comment]
I didn't have a problem before upgrading to PVE 8.
Yes, I'm using API token auth

**Comment by jsabater** [comment]
I can confirm that this issue also happens in the latest version of Proxmox 7, that is 7.4-16 at the time of writing. I have an Ansible playbook that is used to provision LXC and the first thing it does is to download the required template. This is the error I get:

```
"Unable to retrieve Proxmox VE version: 'ProxmoxTemplateAnsible' object has no attribute 'proxmox_api'"
```

I am using `community.general` version 7.2 at the time of writing, with `proxmoxer` version 2.0.1 and the error is raised by the `community.general.proxmox_template` module, which is being run as follows:

```
- name: Download the required template
  community.general.proxmox_template:
    state: present
    api_user: "{{ vault_proxmox_api_user }}"
    api_token_id: "{{ vault_proxmox_api_token_id }}"
    api_token_secret: "{{ vault_proxmox_api_token_secret }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    storage: "{{ proxmox_tmplstorage }}"
    content_type: vztmpl
    template: "{{ proxmox_ostemplate }}"
    timeout: 30
  delegate_to: localhost
```
