### ISSUE TITLE
community.general.consul_kv - suppor datacenter

### ISSUE THREAD

**Issue by k0st1an** [ansible-collections/community.general#7005]
### Summary

the module does not support the ability to specify a DC. This interferes with the receipt of data from other DCs.

### Issue Type

Feature Idea

### Component Name

community.general.consul_kv

### Additional Information

```yaml (paste below)
- community.general.consul_kv:
    key: cert/dm.com/privkey
    datacenter: us
  register: _var
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
