### ISSUE TITLE
Redfish return changed: False on no-op patch requests

### ISSUE THREAD

**Issue by smiller248** [ansible-collections/community.general#7006]
### Summary

When Redfish makes a patch request, the returned object is always `'changed': True` (as long as the request succeeds). This happens even when the patch is a no-op due to the patched attributes already being present in the target. I would like to have Redfish commands that use patch requests under the hood behave in smarter manner, where tthe return object becomes `'changed': False` if the patch has no effect.

This feature would be beneficial to me and others because oftentimes it is necessary to perform restarts if and only if a patch request actually caused a configuration change. Knowing which patch requests are no-ops would enable reducing the number of unnecessary restarts in our playbooks.

### Issue Type

Feature Idea

### Component Name

redfish_config+redfish_command

### Additional Information

Here is the line where `'changed': True` is set on all patch requests: https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/redfish_utils.py#L250.

Example playbook that would benefit from this feature:

```
- name: Toggle Host Interface
  community.general.redfish_config:
    category: Manager
    command: SetHostInterface
    hostinterface_config:
      InterfaceEnabled: "{{ bmc_host_interface_enabled }}"
    baseuri: "{{ bmc_address }}"
    username: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
    timeout: "{{ default_uri_timeout }}"
    resource_id: "{{ system_manager | default(omit) }}"
  retries: "{{ default_uri_retries }}"
  register: redfish_toggle_hi

- name: Restart BMC
  community.general.redfish_command:
    category: Manager
    command: GracefulRestart
    baseuri: "{{ bmc_address }}"
    username: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
    timeout: "{{ default_uri_timeout }}"
    resource_id: "{{ system_manager | default(omit) }}"
  retries: "{{ default_uri_retries }}"
  register: redfish_bmc_restart
  when:
    - redfish_toggle_hi is changed
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
