### ISSUE TITLE
cobbler_system module doesn't handle interfaces correctly, results in KeyError

### ISSUE THREAD

**Issue by glbyers** [ansible-collections/community.general#7007]
### Summary

Defining a new interface in cobbler_system for a pre-existing system that does not already have that interface defined results in KeyError. Here's the culprit;

```
        # Add interface properties
...
                    if not system or system['interfaces'][device][IFPROPS_MAPPING[key]] != value:
                        result['changed'] = True
...
```
                    

It's expecting that either system doesn't exist, or if it does it already has a "device" key in "interfaces". If it doesn't, KeyError. Should be something like this instead?

```
       if not system or system['interfaces'].get(device, {}).get(IFPROPS_MAPPING[key]) != value:
                        result['changed'] = True
```

### Issue Type

Bug Report

### Component Name

cobbler_system

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.0]
  config file = /home/xxxx/work/git/a4-ansible/ansible.cfg
  configured module search path = ['/home/xxxx/work/git/a4-ansible/modules', '/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxxx/venv/ansible2.14/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/xxxx/work/git/a4-ansible/collections:/home/xxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxxx/venv/ansible2.14/bin/ansible
  python version = 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/xxxx/venv/ansible2.14/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/xxxx/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.0.1  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/collections', '/home/xxxx/.ansible/collections', '/usr/share/ansible/collections']
COLOR_VERBOSE(/home/xxxx/work/git/a4-ansible/ansible.cfg) = dark gray
CONFIG_FILE() = /home/xxxx/work/git/a4-ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/plugins/action', '/usr/share/ansible/plugins/action']
DEFAULT_ASK_PASS(/home/xxxx/work/git/a4-ansible/ansible.cfg) = True
DEFAULT_BECOME(/home/xxxx/work/git/a4-ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/xxxx/work/git/a4-ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/xxxx/work/git/a4-ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/xxxx/work/git/a4-ansible/ansible.cfg) = root
DEFAULT_CONNECTION_PLUGIN_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/plugins/connection', '/usr/share/ansible/plugins/connection']
DEFAULT_FILTER_PLUGIN_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(/home/xxxx/work/git/a4-ansible/ansible.cfg) = This file is Ansible managed from role: {{{{ ansible_role_name }}}}
DEFAULT_MODULE_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/modules', '/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_ROLES_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/roles', '/home/xxxx/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(env: ANSIBLE_STRATEGY_PLUGINS) = ['/home/xxxx/.local/share/ansible/mitogen-0.3.4.dev0/ansible_mitogen/plugins/strategy']
DEFAULT_TEST_PLUGIN_PATH(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['/home/xxxx/work/git/a4-ansible/plugins/test', '/usr/share/ansible/plugins/test']
GALAXY_ROLE_SKELETON(/home/xxxx/work/git/a4-ansible/ansible.cfg) = /home/xxxx/work/git/a4-ansible/roles/skel
GALAXY_ROLE_SKELETON_IGNORE(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['^.git$', '^.*/.git_keep$']
GALAXY_SERVER_LIST(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['galaxy', 'automation_hub']
HOST_KEY_CHECKING(/home/xxxx/work/git/a4-ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/xxxx/work/git/a4-ansible/ansible.cfg) = ['advanced_host_list', 'host_list', 'constructed', 'generator', 'ini', 'auto', 'yaml']
MAX_FILE_SIZE_FOR_DIFF(/home/xxxx/work/git/a4-ansible/ansible.cfg) = 150000
PERSISTENT_CONNECT_TIMEOUT(/home/xxxx/work/git/a4-ansible/ansible.cfg) = 30
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
- name: Create system in cobbler
  community.general.cobbler_system:
    username: "{{ deploy_cobbler_username }}"
    password: "{{ deploy_cobbler_password }}"
    use_ssl: true
    validate_certs: false
    name: testme                                                            
    properties:
      hostname: testme.example.com
      profile: rhel8-x86_64
      name_servers: [8.8.8.8, 8.8.4.4]                                                                   
      netboot_enabled: false
      
- name: Update system in cobbler
  community.general.cobbler_system:
    username: "{{ deploy_cobbler_username }}"
    password: "{{ deploy_cobbler_password }}"
    use_ssl: true
    validate_certs: false
    name: testme                                                            
    interfaces:
      eth0:
        dnsname: testme.example.com
        ipaddress: 192.168.0.100
        ifgateway: 192.168.0.1
        netmask: 255.255.255.0
        macaddress: 'de:ad:be:ef:de:ad'
        mtu: 9000
        static: true
    properties:
      hostname: testme.example.com
      profile: rhel8-x86_64
      name_servers: [8.8.8.8, 8.8.4.4]                                                                   
      netboot_enabled: false
```

### Expected Results

I expected it to update an existing host with an eth0 interface.

### Actual Results

```console (paste below)
TASK [deploy : Update system in cobbler] *************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'eth0'                                            
fatal: [testme.example.com -> cobbler.example.com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n 
 File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/usr/lib64/py
thon3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line
 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.general.cobbler_system_payload_h8s7b1wo/ansible_community.general.cobbler_system_payload.zip/ansible_collections/community/general/plugins/modules/cobbler_system.py\", line 348, in <module>\n  File \"/tmp/ansible_community.general.cobbler_system_payload_h8s7b1wo/ansible_community.general.cobbler_system_payload.zip/ansible_collections/community/general/plugins/modules/cobbler_system.py\", line 313, in main\nKeyError: 'fuckyou'\n", "modul
e_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}    
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
