### ISSUE TITLE
gandi_livedns: No method to delete records by name (regardless of type)

### ISSUE THREAD

**Issue by rc5hack** [ansible-collections/community.general#7008]
### Summary

Currently the only supported way to delete DNS records with gandi_livedns plugin is to delete them at name+type basis. Code below will delete `foo.domain.tld` record with type A (if any), implementing [Delete record with {rrset_name} and {rrset_type}](https://api.gandi.net/docs/livedns/#delete-v5-livedns-domains-fqdn-records-rrset_name-rrset_type) method of Gandi API:

```yaml
- name: Delete DNS records
  community.general.gandi_livedns:
    domain: 'domain.tld'
    record: 'foo'
    type: 'A'
    api_key: 'dummy'
    state: 'absent'
  register: record
```

In fact there is another method in Gandi API which allows to delete record at name basis, regardless of type, which is usable in some cases: [Delete all records named {rrset_name}](https://api.gandi.net/docs/livedns/#delete-v5-livedns-domains-fqdn-records-rrset_name). E.g. I don't know if there are A, AAAA or CNAME `foo.domain.tld` record(s), but I want just delete all records with name `foo`.

So I'm asking to add into gandi_livedns plugin option to call [Delete all records named {rrset_name}](https://api.gandi.net/docs/livedns/#delete-v5-livedns-domains-fqdn-records-rrset_name) API method. 

### Issue Type

Feature Idea

### Component Name

gandi_livedns

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
