### ISSUE TITLE
GetFirmwareInventory support for paginated results

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#7011]
### Summary

Running a basic:

```
  - name: Collect Firmware Inventory
    community.general.redfish_info:
      category: Update
      command: GetFirmwareInventory
      baseuri: "{{ bmc }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: redfish_fw_inventory
```

returns the expected redfish_facts.firwmare.entries results, but it does not appear to respect:
```
  "Members@odata.count": 61,
  "Members@odata.nextLink": "/redfish/v1/UpdateService/FirmwareInventory?$skip=50",
  "Name": "Firmware Inventory Collection"
```

to retrieve firmware for entries 51 and above.

### Issue Type

Feature Idea

### Component Name

redfish_info

### Additional Information

It would be great if the module would automatically handle following pagination links to retrieve the full inventory list.

```  
- debug:
      msg: "{{ redfish_fw_inventory.redfish_facts.firmware.entries | length }}"

ok: [localhost] => {
    "msg": "50"
}

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
