### ISSUE TITLE
Community.General.Jira module error with Jira Fetch operation 

### ISSUE THREAD

**Issue by mohitnordea12** [ansible-collections/community.general#7014]
### Summary

Below code is giving the error 

`---
- name: JIRA Main Task Creation for CVMP project
  hosts: localhost
  gather_facts: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    jira_base_url: 'jira.dummy.net'
    jira_project_name: 'DUMMY'

  tasks:

     - name: Fetch issues
       jira:
         uri: '{{ jira_base_url }}'
         username: '{{ username }}'
         password: '{{ pass }}'
         project: '{{ jira_project_name }}'
         operation: fetch
         issue: "DUMMY-1739"
         timeout: 360
       register: issue_fetch
       retries: 10
       delay: 10
       until: issue_fetch.changed|bool

     - debug:
         msg: "{{issue_fetch.changed}}"
`

issue_fetch.changed is always coming false in case of Ansible Automation Platform 
But working fine AWX 11.2

### Issue Type

Bug Report

### Component Name

     - name: Create and fetch issues
       jira:
         uri: '{{ jira_base_url }}'
         username: '{{ username }}'
         password: '{{ pass }}'
         project: '{{ jira_project_name }}'
         operation: fetch
         issue: "DUMMY-1739"
         timeout: 360
       register: issue_fetch
       retries: 10
       delay: 10
       until: issue_fetch.changed|bool

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.2]
  config file = /home/g83336-udm/cvmp/ansible.cfg
  configured module search path = ['/home/g83336-udm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/g83336-udm/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.3.0

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /home/user/cvmp/ansible.cfg
DEFAULT_HOST_LIST(/home/user-udm/cvmp/ansible.cfg) = ['/home/user-udm/cvmp/inventory']
DEFAULT_ROLES_PATH(/home/user-udm/cvmp/ansible.cfg) = ['/home/user-udm/cvmp/roles']
HOST_KEY_CHECKING(/home/user-udm/cvmp/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/user-udm/cvmp/ansible.cfg) = False
SHOW_CUSTOM_STATS(/home/user-udm/cvmp/ansible.cfg) = True
STRING_CONVERSION_ACTION(/home/user-udm/cvmp/ansible.cfg) = ignore

```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
  - name: Fetch issues
       jira:
         uri: '{{ jira_base_url }}'
         username: '{{ username }}'
         password: '{{ pass }}'
         project: '{{ jira_project_name }}'
         operation: fetch
         issue: "DUMMY-1739"
         timeout: 360
       register: issue_fetch
       retries: 10
       delay: 10
       until: issue_fetch.changed|bool
```

### Expected Results

I expected issue_fetch.changed value to be true

### Actual Results

```console (paste below)
issue_fetch.changed value is false 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
