### ISSUE TITLE
proxmox_kvm: Cloning template to create new VM fails

### ISSUE THREAD

**Issue by jhofmueller** [ansible-collections/community.general#7017]
### Summary

When I try to clone a new VM from an existing template named "ubuntu" I get the error "VM with name = ubuntu does not exist in cluster". This is the task:

```
- name: Clone VM
  community.general.proxmox_kvm:
    api_host: HOST
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    clone: ubuntu
    name: zavala
    node: NODE
    storage: STORAGE
    format: qcow2
    timeout: 500
```

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.8]
  config file = /home/jogi/git/dcim/netbox-dev/ansible.cfg
  configured module search path = ['/home/jogi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/jogi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/USER/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.1.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.3  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 22.04.2

### Steps to Reproduce

```yaml (paste below)

- name: Clone VM
  community.general.proxmox_kvm:
    api_host: HOST
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    clone: ubuntu
    name: zavala
    node: NODE
    storage: STORAGE
    format: qcow2
    timeout: 500

```

### Expected Results

I expected a new VM cloned from the specified template.

### Actual Results

```console (paste below)
TASK [proxmox_vm : Clone VM] ****************************************************************************************************************************************************************
fatal: [PROXMOX]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "VM with name = ubuntu does not exist in cluster"}

PLAY RECAP **********************************************************************************************************************************************************************************
PROXMOX      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
