### ISSUE TITLE
Jira module doesn't allow to use numbers in fields

### ISSUE THREAD

**Issue by peterhadac** [ansible-collections/community.general#7018]
### Summary

I am creating issue via
```yaml
- name: Create an issue
  community.general.jira:
    uri: "https://{{ url }}"
    username: "{{ username }}"
    password: "{{ password }}"
    project: "STORY"
    operation: create
    summary: "{{ summary }}"
    description: "{{ description }}"
    issuetype: "Story"
    validate_certs: false
    fields:
      customfield_12802: "{{ epic }}"
      customfield_14102: "{{ acceptance }}"
      customfield_12806: "{{ item.story_points | int }}"
```

This creates outcome of 

"customfield_12806": "2",

No matter how I edit customfield_12806 value, it still results in error: 

**"msg": "{'customfield_12806': 'Operation value must be a number'}"**

### Issue Type

Bug Report

### Component Name

jira

### Ansible Version

```console (paste below)
> ansible --version
\ansible [core 2.15.0]
  config file = None
  configured module search path = ['/Users/peter.hadac/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/peter.hadac/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/8.0.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
ansible-galaxy collection list community.general

# /Users/peter.hadac/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.1.0  

# /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.0.1  
```

### Configuration

```console (paste below)
ansible-config dump --only-changed
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nvim
PAGER(env: PAGER) = less
```

### OS / Environment

Mac

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

Number will be passed to customfield e.g.:
```json
"customfield_12806": 2,
```

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/jira.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/jira.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Slezhuk @pertoft @tarka
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
hi @Paxhape thanks for reporting this issue.

The module does not manipulate the type of elements of the `fields` dictionary. It is converted to JSON using `json.dumps()` and sent in the http request.

Could you please confirm whether you can reproduce the issue using a literal `2`, as opposed to using `"{{ item.story_points | int }}"`? TIA

**Comment by Paxhape** [comment]
Hi, it does work, when I enter directly number. 
```yaml
- name: Create an issue
  community.general.jira:
    uri: 'https://{{ url }}'
    username: '{{ username }}'
    password: '{{ password }}'
    project: STORY
    operation: create
    summary: '{{ summary }}'
    description: '{{ description }}'
    issuetype: Story
    validate_certs: false
    fields:
        priority:
          name: '{{ priority }}'
        customfield_12802: '{{ epic }}'
        customfield_12806: 1
```

But however I want to template it, it ends same way. 

Also debug shows it is int 
```shell
- name: Debug story_points
  ansible.builtin.debug:
    msg: " Type of story_points id {{ story_points | int | type_debug }}"
```

```shell
ok: [localhost] => {
    "msg": " Type of story_points id int"
}
```

I have found maybe it is an issue with jinja - https://github.com/ansible/ansible/issues/30366

**Comment by russoz** [comment]
Hi @peterhadac 
I believe this has already been solved:

- https://github.com/ansible/ansible/issues/30366
- https://github.com/pallets/jinja/pull/708
- https://github.com/ansible/ansible/pull/32738

I ran a quick'n'dirty local test:

```yaml
---
- name: check |int
  hosts: localhost
  tasks:
    - set_fact:
        x: "{{ '2' | int }}"

    - debug:
        var: x
```

And the result seems to be OK:
```
$ ansible-playbook -v main.yml
No config file found; using defaults
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [check |int] ******************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [localhost]

TASK [set_fact] ********************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"x": 2}, "changed": false}

TASK [debug] ***********************************************************************************************************************
ok: [localhost] => {
    "x": 2
}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Could you please confirm whether this is still an issue?

needs_info
