### ISSUE TITLE
Documentation is incorrect for proxmox_kvm for boot order

### ISSUE THREAD

**Issue by lungj** [ansible-collections/community.general#7035]
### Summary

When I specify `boot` as `c` to boot from a drive as described in the [documentation](https://github.com/ansible-collections/community.general/blob/87053e52661efdbe7ac08099d92fcaea1943621c/plugins/modules/proxmox_kvm.py#L66), no changes to boot order occur.

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.1]
  config file = /mnt/hgfs/step1.2/ansible.cfg
  configured module search path = ['/home/lungj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lungj/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/lungj/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lungj/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/lungj/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0  

# /home/lungj/.local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.1.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Debian 11 connecting to Proxmox VE 8.

### Steps to Reproduce

```yaml
- name: "Set boot to drive"
  community.general.proxmox_kvm:
    api_user: SOME_USER
    api_token_id: SOME_TOKEN_ID
    api_token_secret: SOME_SECRE
    api_host: SOME_HOST
    node: SOME_NODE
    
    name: SOME_TEMPLATE_NAME
    boot: "c"
    update: yes
```

### Expected Results

I expect the (virtual) internal drives to be selected for booting.

### Actual Results

No change to VM configuration.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
