### ISSUE TITLE
Add replace_value option to ini_file

### ISSUE THREAD

**Issue by hqstevenson** [ansible-collections/community.general#7047]
### Summary

I have multiple situations where I only want to add the option and value to the configuration file if it does not exist - I don't want to replace an existing value.  Adding a "replace_value" option (or something like that) would be very helpful.

The default value of the option should be "true" to preserve existing behavior.  But if the value of the option is set to "false", an existing value for the option would be left untouched, even if it didn't match the value specified in the playbook.

### Issue Type

Feature Idea

### Component Name

ini_file

### Additional Information

```
     # In this example, the value of the 'passphrase' option in the 'general' section would NOT be replaced if it was already present in the configuration file
      - name: Replace value in file
        community.general.ini_file:
          path: /tmp/test.conf
          section: 'general'
          option: 'passphrase'
          value:  'some secret'
          replace_value: false

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
