### ISSUE TITLE
Add support for rustup

### ISSUE THREAD

**Issue by pythops** [ansible-collections/community.general#7059]
### Summary

Add a module to support adding/removing/listing `rustup` components.

### Issue Type

Feature Idea

### Component Name

rustup

### Additional Information

Example:

```yaml

- name: Add clippy component
  name: community.general.rustup:
    name: clippy
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
