### ISSUE TITLE
Ldap_Entry - State:Exact

### ISSUE THREAD

**Issue by Mycaelis1** [ansible-collections/community.general#7076]
### Summary

My directory has a dn, cn=core,cn=config which already exists.
I want to add an additional objectClass to this dn.
When running ldap_entry it doesn't make the change as the dn aready exists, due to state:present.
Ideally looking for state:exact like the ldap_attrs collection as I believe this would add the additional objectClass correctly to the cn=core,cn=config dn.

### Issue Type

Feature Idea

### Component Name

ldap_entry

### Additional Information

```yaml (paste below)
- name: Add Password Hashing objectClass to cn=core,cn=config
  community.general.ldap_entry:
    server_uri: "{{ host }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw "{{ bind_pw }}"
    dn: cn=core,cn=config
    objectClass: pwdHashSchemePolicy
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/ldap_entry.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ldap_entry.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Gnonthgol** [comment]
This is per documentation. The correct way to add an object class would be:

```
- name: Add Password Hashing objectClass to cn=core,cn=config
  community.general.ldap_attr:
    server_uri: "{{ host }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"
    state: present
    dn: cn=core,cn=config
    attributes:
      objectClass: pwdHashSchemePolicy
```
I would argue that it is possible to combine ldap_entry and ldap_state but that would be a bigger rewrite.
