### ISSUE TITLE
ipa_sudorule: task fail when sudo rule exist

### ISSUE THREAD

**Issue by cwchristerw** [ansible-collections/community.general#7082]
### Summary

I have temporarily solved this issue with using this in playbook:
```yaml (paste below)
- name: "Create sudo rule"
  community.general.ipa_sudorule:
    ipa_host: "https://idm.example.com"
    ipa_user: "admin"
    ipa_pass: "password"
    name: sysadmin
    usergroup:
    - sysadmin
    hostcategory: all
    cmdcategory: all
    sudoopt:
      - '!authenticate'
  register: task
  failed_when:
    - task.msg is defined
    - "task.msg.find(\"response sudorule_mod: no modifications to be performed\") == -1"
```

### Issue Type

Bug Report

### Component Name

ipa_sudorule

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/cwchristerw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/cwchristerw/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/opt/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /opt/ansible/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.2.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
-
```

### OS / Environment

Linux Mint 21.2

### Steps to Reproduce

```yaml (paste below)
- name: "Create sudo rule"
  community.general.ipa_sudorule:
    ipa_host: "https://idm.example.com"
    ipa_user: "admin"
    ipa_pass: "password"
    name: sysadmin
    usergroup:
    - sysadmin
    hostcategory: all
    cmdcategory: all
    sudoopt:
      - '!authenticate'
```

### Expected Results

When created or changed:
```console (paste below)
changed: [idm.example.com]
```

When not changed:
```console (paste below)
ok: [idm.example.com]
```

### Actual Results

When not changed:
```console (paste below)
fatal: [idm.example.com]: FAILED! => {"changed": false, "msg": "response sudorule_mod: no modifications to be performed"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
