### ISSUE TITLE
Redfish: Add 'PowerCycle' to the supported ResetType power commands

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#7083]
### Summary

I would like to execute a Redfish `PowerCycle` ResetType operation.

### Issue Type

Feature Idea

### Component Name

redfish_command

### Additional Information

`PowerCycle` is different than a `Force/GracefulRestart` in our hardware models and would be a welcome feature addition to have available in the module.

```
- name: Restart system power gracefully
  community.general.redfish_command:
    category: Systems
    command: PowerCycle
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
