### ISSUE TITLE
Add support for routing_rules6

### ISSUE THREAD

**Issue by robert-scheck** [ansible-collections/community.general#7094]
### Summary

As of writing, community.general.nmcli supports unfortunately only "routing_rules4", but no "routing_rules6".

To be able to use community.general.nmcli for non-trivial non-legacy-only environments, "routing_rules6" would be really helpful. Typical use-cases for "routing_rules6" are dual-stacked or IPv6-only environments with source/policy based routing (PBR).

### Issue Type

Feature Idea

### Component Name

nmcli

### Additional Information

```yaml (paste below)
- name: Interface with IPv6 source/policy based routing (PBR)
  community.general.nmcli:
    type: ethernet
    conn_name: em1
    ifname: em1
    ip6: 2001:db8::1/64
    routes6_extended:
      - { ip: 2001:db8::/64, next_hop: 2001:db8::1, table: 1 }
      - { ip: 2001:db8::/64, table: 1 }
    routing_rules6:
      - 'priority 5 from ::/0 iif em1 table 1'
      - 'priority 5 from 2001:db8::/64 table 1'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
