### ISSUE TITLE
SSHA password hash filter

### ISSUE THREAD

**Issue by Laborratte5** [ansible-collections/community.general#7114]
### Summary

When setting up an LDAP Server there currently seems no way to generate a salted sha (SSHA) hash from a password (e.g. retrieved via ansible-vault). As the [OpenLDAP doc](https://openldap.org/doc/admin26/security.html) states, "[SSHA] is believed to be the most secure password storage scheme supported by slapd", I think it would be helpful to have a filter that generates a SSHA value based on a given password.
I hope I did not miss an existing solution.

Note: I have already implemented a proof of concept, so if this feature request is accepted I would be happy to work on this, as I think only proper documentation and tests are missing.

### Issue Type

Feature Idea

### Component Name

plugins.filter.ssha

### Additional Information

```yaml (paste below)
- name: Create LDAP entry with SSHA hashed password
  become: true
  community.general.ldap_entry:
    ...
    attributes:
      olcRootPW: "{{ '{SSHA}' + item.rootPW | ssha(salt='00112233aabbeeff') }}"
      ...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sumpfralle** [comment]
FYI: here is a script for re-using the existing salt of the current LDAP userPassword content.
This ensures that an unchanged password does not lead to unwanted hash changes.

[ldap-get-salted-password-hash.py](https://github.com/user-attachments/files/24393999/ldap-get-salted-password-hash.py)

The corresponding ansible task could look like this:
```yaml
- name: 'generate password hash for LDAP account'
  ansible.builtin.command:
    cmd: /usr/local/bin/ldap-get-salted-password-hash "{{ account_dn }}"
    stdin: "{{ account_password }}"
    stdin_add_newline: false
  register: account_password_hash
  changed_when: false
  check_mode: false

- name: 'update password hash for LDAP account'
  ldap_attrs:
    dn: "{{ account_dn }}"
    attributes:
      userPassword: "{{ account_password_hash.stdout }}"
    state: exact
```

This avoids the need for specifying a hard-coded salt for the password.

Feel free to use this (GPL-3+) code for assembling an ansible plugin (or anything else).
