### ISSUE TITLE
Consul ACL token creation fails

### ISSUE THREAD

**Issue by danielkaszonyi** [ansible-collections/community.general#7123]
### Summary

consul_acl module fails when trying to create a new ACL token 

### Issue Type

Bug Report

### Component Name

consul_acl

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/Users/dkaszonyi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/dkaszonyi/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True```


### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.0.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
NONE
```

### OS / Environment

Ubuntu 20.04 running in Multipass
Consul v1.16.1

### Steps to Reproduce

```yaml (paste below)
---
- name: Creating Consul tokens
  hosts: master_test
  become: true

  tasks:
    - name: Create a key/value
      community.general.consul_kv:
        key: insert_test
        value: 'asldkfasldkfalsdkf'
        state: present

    - name: Create an ACL token in consul
      community.general.consul_acl:
        mgmt_token: <token-with-global-management>
        name: testuser
        state: present
        validate_certs: false
        token_type: management

```

### Expected Results

New ACL token with management privileges.

### Actual Results

```console (paste below)
fatal: [ubuntu-chabl]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.64.14 closed.\r\n",
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1692188728.677614-10112-48301478190766/AnsiballZ_consul_acl.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1692188728.677614-10112-48301478190766/AnsiballZ_consul_acl.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1692188728.677614-10112-48301478190766/AnsiballZ_consul_acl.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.consul_acl', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.consul_acl', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.general.consul_acl_payload__ej7norv/ansible_community.general.consul_acl_payload.zip/ansible_collections/community/general/plugins/modules/consul_acl.py\", line 691, in <module>\r\n  File \"/tmp/ansible_community.general.consul_acl_payload__ej7norv/ansible_community.general.consul_acl_payload.zip/ansible_collections/community/general/plugins/modules/consul_acl.py\", line 676, in main\r\n  File \"/tmp/ansible_community.general.consul_acl_payload__ej7norv/ansible_community.general.consul_acl_payload.zip/ansible_collections/community/general/plugins/modules/consul_acl.py\", line 271, in set_acl\r\n  File \"/usr/local/lib/python3.8/dist-packages/consul/base.py\", line 1930, in list\r\n    return self.agent.http.get(\r\n  File \"/usr/local/lib/python3.8/dist-packages/consul/std.py\", line 21, in get\r\n    return callback(self.response(\r\n  File \"/usr/local/lib/python3.8/dist-packages/consul/base.py\", line 225, in cb\r\n    return response.headers['X-Consul-Index'], None\r\n  File \"/usr/lib/python3/dist-packages/requests/structures.py\", line 52, in __getitem__\r\n    return self._store[key.lower()][1]\r\nKeyError: 'x-consul-index'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
