### ISSUE TITLE
proxmox_snap: VM with vmid xxx does not exist in cluster

### ISSUE THREAD

**Issue by YourSandwich** [ansible-collections/community.general#7133]
### Summary

I am trying to create a snapshot with the proxmox_snap module. It worked for a long time, the issue occurred some time after upgrading to proxmox 8.0, but I am not sure if this is related. The target is Proxmox VE 8.0.4
 
The Playbook looks like this:
```
---
- name: Snapshot and Update Proxmox VMs
  hosts: localhost
  become: no
  gather_facts: false
  vars:
    proxmox_api_host: "proxmox.lan"
    proxmox_api_user: "supersecret"
    proxmox_api_password: "supersecret"
    restart_confirmation: "yes"

  tasks:
    - name: Create Proxmox Snapshot
      community.general.proxmox_snap:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "100"
        state: present
        snapname: pre-updates
```

The verbose output:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "proxmox.lan",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_token_id": null,
            "api_token_secret": null,
            "api_user": "supersecret",
            "description": null,
            "force": false,
            "hostname": null,
            "retention": 0,
            "snapname": "pre-updates",
            "state": "present",
            "timeout": 30,
            "unbind": false,
            "validate_certs": false,
            "vmid": "100",
            "vmstate": false
        }
    },
    "msg": "VM with vmid 100 does not exist in cluster"
}

```

This is the output of proxmox_vm_info module it runs successfully, but it's suspicious that it does not detect the vm name:
```
{
                "ansible_loop_var": "item",
                "changed": false,
                "failed": false,
                "invocation": {
                    "module_args": {
                        "api_host": "proxmox.lan",
                        "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "api_token_id": null,
                        "api_token_secret": null,
                        "api_user": "supersecret",
                        "name": null,
                        "node": null,
                        "type": "all",
                        "validate_certs": false,
                        "vmid": 100
                    }
                },
                "item": "100",
                "proxmox_vms": []
            }
```

### Issue Type

Bug Report

### Component Name

proxmox_snap

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/home/sandwich/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/sandwich/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/sandwich/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.4.0  

# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Ansible Host:
ArchLinux (2023-08-20 09:42:10 UTC)
Kernel 6.5.0-rc6

Target:
Proxmox VE 8.0.4 (Debian 12)

### Steps to Reproduce

```yaml (paste below)
- name: Snapshot 
  hosts: localhost
  become: no
  gather_facts: false
  vars:
    proxmox_api_host: "proxmox.lan"
    proxmox_api_user: "supersecret"
    proxmox_api_password: "supersecret"

  tasks:
    - name: Create Proxmox Snapshot
      community.general.proxmox_snap:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        vmid: "100"
        state: present
        snapname: pre-updates
```

### Expected Results

It creates a snapshot called pre-updates for the VM with the id 100.

### Actual Results

```console (paste below)
TASK [Create Proxmox Snapshot] ****************************************************************************************************************************************************************************************************
task path: /home/sandwich/lol.yaml:13
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sandwich
<127.0.0.1> EXEC /bin/sh -c 'echo ~sandwich && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sandwich/.ansible/tmp `"&& mkdir "` echo /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923 `" && echo ansible-tmp-1692524737.551306-3304485-195505057295923="` echo /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923 `" ) && sleep 0'
Using module file /home/sandwich/.ansible/collections/ansible_collections/community/general/plugins/modules/proxmox_snap.py
<127.0.0.1> PUT /home/sandwich/.ansible/tmp/ansible-local-33044810kzhh19_/tmp_hwo1znf TO /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923/AnsiballZ_proxmox_snap.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923/ /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923/AnsiballZ_proxmox_snap.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923/AnsiballZ_proxmox_snap.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/sandwich/.ansible/tmp/ansible-tmp-1692524737.551306-3304485-195505057295923/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "10.1.0.2",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_token_id": null,
            "api_token_secret": null,
            "api_user": "snapshot@pve",
            "description": null,
            "force": false,
            "hostname": null,
            "retention": 0,
            "snapname": "pre-updates",
            "state": "present",
            "timeout": 30,
            "unbind": false,
            "validate_certs": false,
            "vmid": "100",
            "vmstate": false
        }
    },
    "msg": "VM with vmid 100 does not exist in cluster"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by YourSandwich** [comment]
Please let me know if you need any additional information.

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @UnderGreen @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by YourSandwich** [comment]
I have also tried to use ansible-collections git with the same result

**Comment by YourSandwich** [comment]
I tried it out with an Admin user as well, without any difference. My proxmoxer verison is 2.0.1
The playbook worked the last time 13 days ago on 08.09.2023 and the next time it ran on 12.09 it suddenly failed.

I just tried it with vm name instead, and it also failed with "No vm with name xxx found"

**Comment by Thulium-Drake** [comment]
Hmm, apparently I was mistaken... The snippet below is from the playbook I use (wrote it a few years ago :sweat_smile: )

```
    - name: 'Remove old maintenance snapshots of Proxmox VMs'
      community.general.proxmox_snap:
        api_user: "{{ proxmox_username }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_cluster }}"
        vmid: "{{ proxmox_vmid }}"
        state: 'absent'
        snapname: "{{ snapshot }}"
      loop: "{{ proxmox_snapshots }}"
      loop_control:
        loop_var: 'snapshot'
      when:
        - proxmox_vmid is defined
        - snapshot is match("^maintenance_snap_*")
      delegate_to: 'localhost'
      retries: 3
      delay: 3

    - name: 'Create maintenance snapshots of Proxmox VMs'
      community.general.proxmox_snap:
        api_user: "{{ proxmox_username }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_cluster }}"
        vmid: "{{ proxmox_vmid }}"
        state: 'present'
        snapname: "maintenance_snap_{{ ansible_facts['date_time']['date'] }}"
        description: 'Pre system-updates'
      when: proxmox_vmid is defined
      delegate_to: 'localhost'
      become: false
```

It works by iterating over my entire inventory and using the ```proxmox_vmid``` discovered by the ```community.general.proxmox``` when it is defined.

I just ran it against my system:

```
proxmox-ve: 8.0.2 (running kernel: 6.2.16-4-pve)
pve-manager: 8.0.4 (running version: 8.0.4/d258a813cfa6b390)
pve-kernel-6.2: 8.0.5
proxmox-kernel-helper: 8.0.3
pve-kernel-5.15: 7.4-4
proxmox-kernel-6.2.16-8-pve: 6.2.16-8
proxmox-kernel-6.2: 6.2.16-8
proxmox-kernel-6.2.16-6-pve: 6.2.16-7
pve-kernel-6.2.16-4-pve: 6.2.16-5
pve-kernel-5.15.108-1-pve: 5.15.108-1
ceph-fuse: 16.2.11+ds-2
corosync: 3.1.7-pve3
criu: 3.17.1-2
glusterfs-client: 10.3-5
ifupdown: 0.8.41
ksm-control-daemon: 1.4-1
libjs-extjs: 7.0.0-4
libknet1: 1.25-pve1
libproxmox-acme-perl: 1.4.6
libproxmox-backup-qemu0: 1.4.0
libproxmox-rs-perl: 0.3.1
libpve-access-control: 8.0.4
libpve-apiclient-perl: 3.3.1
libpve-common-perl: 8.0.7
libpve-guest-common-perl: 5.0.4
libpve-http-server-perl: 5.0.4
libpve-rs-perl: 0.8.5
libpve-storage-perl: 8.0.2
libspice-server1: 0.15.1-1
lvm2: 2.03.16-2
lxc-pve: 5.0.2-4
lxcfs: 5.0.3-pve3
novnc-pve: 1.4.0-2
openvswitch-switch: 3.1.0-2
proxmox-backup-client: 3.0.2-1
proxmox-backup-file-restore: 3.0.2-1
proxmox-kernel-helper: 8.0.3
proxmox-mail-forward: 0.2.0
proxmox-mini-journalreader: 1.4.0
proxmox-offline-mirror-helper: 0.6.2
proxmox-widget-toolkit: 4.0.6
pve-cluster: 8.0.3
pve-container: 5.0.4
pve-docs: 8.0.4
pve-edk2-firmware: 3.20230228-4
pve-firewall: 5.0.3
pve-firmware: 3.7-1
pve-ha-manager: 4.0.2
pve-i18n: 3.0.5
pve-qemu-kvm: 8.0.2-4
pve-xtermjs: 4.16.0-3
pve-zsync: 2.3.0
qemu-server: 8.0.6
smartmontools: 7.3-pve1
spiceterm: 3.3.0
swtpm: 0.8.0+pve1
vncterm: 1.8.0
zfsutils-linux: 2.1.12-pve1
```

With an administrator user as I mentioned before, see below for my ACL setup:

```
(R) (14:31:08) root@virt-1:~# pveum acl list
┌────────────┬───────────────┬───────┬────────────┬───────────┐
│ path       │ roleid        │ type  │ ugid       │ propagate │
╞════════════╪═══════════════╪═══════╪════════════╪═══════════╡
│ /          │ PVEAuditor    │ user  │ search@pve │ 1         │
├────────────┼───────────────┼───────┼────────────┼───────────┤
│ /          │ Administrator │ group │ admin      │ 1         │
├────────────┼───────────────┼───────┼────────────┼───────────┤
│ /pool      │ PVEPoolAdmin  │ user  │ search@pve │ 1         │
├────────────┼───────────────┼───────┼────────────┼───────────┤
│ /pool/test │ NoAccess      │ user  │ search@pve │ 1         │
└────────────┴───────────────┴───────┴────────────┴───────────┘
```
