### ISSUE TITLE
lvol.py allow state: merged for snapshots

### ISSUE THREAD

**Issue by 101smurf** [ansible-collections/community.general#7150]
### Summary

I'm trying to write a playbook that merges an LVM snapshot. This can be achieved using the lvconvert command, but I'd rather use a module. 

### Issue Type

Feature Idea

### Component Name

lvol

### Additional Information

```yaml (paste below)
- name: Merge a snapshot volume of the test logical volume.
  community.general.lvol:
    vg: firefly
    lv: test
    snapshot: snap1
    state: merged
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
