### ISSUE TITLE
keycloak_authz_permission incorrectly sends a one element array as string

### ISSUE THREAD

**Issue by RobinGoussey** [ansible-collections/community.general#7151]
### Summary

When running:

```yaml
- name: Allow all users to list sessions
  community.general.keycloak_authz_permission:
    validate_certs: false
    name: allow-users-to-list-sessions
    state: present
    description: Allow users to list sessions
    permission_type: scope
    decision_strategy: AFFIRMATIVE
    scopes:
      - urn:ebo:CS:scopes:list
    resources:
      - Session
    policies:
      - all-users
    client_id: charging-stations
    realm: "{{ keycloak_realm }}"
    auth_keycloak_url: https://{{ ansible_default_ipv4.address }}:{{ keycloak_https_port }}/auth
    auth_username: admin
    auth_password: "{{ secret_keycloak_admin_password }}"
    auth_realm: master
```
It returns a 500, where java/keycloak prints:

```text
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.HashSet` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('34a556e1-95c0-482c-91df-4bccc865d356')
```

Which means it expects an array, but it got a string.

Looking at the python code [https://github.com/ansible-collections/community.general/blob/7721420388aa1d9cf7751fa250754d3419f3a2b1/plugins/modules/keycloak_authz_permission.py#L333](https://github.com/ansible-collections/community.general/blob/7721420388aa1d9cf7751fa250754d3419f3a2b1/plugins/modules/keycloak_authz_permission.py#L333):
```python
                payload['resources'] = r['_id']
```
I think this should be wrapped in an array.

    

### Issue Type

Bug Report

### Component Name

community.general.keycloak_authz_permission

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/home/rgoussey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rgoussey/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rgoussey/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rgoussey/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.3.0  

```

### Configuration

```console (paste below)

```

### OS / Environment

Ubuntu

### Steps to Reproduce

Tweak variables, and run against a running keycloak.

```yaml (paste below)
- name: Allow all users to list sessions
  community.general.keycloak_authz_permission:
    validate_certs: false
    name: allow-users-to-list-sessions
    state: present
    description: Allow users to list sessions
    permission_type: scope
    decision_strategy: AFFIRMATIVE
    scopes:
      - urn:ebo:CS:scopes:list
    resources:
      - Session
    policies:
      - all-users
    client_id: charging-stations
    realm: "{{ keycloak_realm }}"
    auth_keycloak_url: https://{{ ansible_default_ipv4.address }}:{{ keycloak_https_port }}/auth
    auth_username: admin
    auth_password: "{{ secret_keycloak_admin_password }}"
    auth_realm: master
```

### Expected Results

The task should use the correct serialization format.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
