### ISSUE TITLE
Various Pritunl API methods do not honour `validate_certs`

### ISSUE THREAD

**Issue by dsmackie** [ansible-collections/community.general#7155]
### Summary

Various methods of the Pritunl module do not honour the `validate_certs` parameter. Hardcoded values of `True` exist which ignore any user passing of `False`.

The harecoded `True` values make it impossible to bypass certificate validation when using various methods of the Pritunl module.

### Issue Type

Bug Report

### Component Name

pritunl

### Ansible Version

```console
ansible [core 2.15.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/daniel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0
```

### OS / Environment

Ubuntu 22.04.2 LTS

### Steps to Reproduce

```yaml
- block:
  - name: "Install Pritunl | Create Organisation"
    community.general.pritunl_org:
      name: NAME
      pritunl_api_secret: SECRET
      pritunl_api_token: TOKEN
      pritunl_url: https://URL
      validate_certs: False
      state: present
```

### Expected Results

I expected the call to ignore self signed certificates

### Actual Results

```console
TASK [pritunl-server-ubuntu : Install Pritunl | Create Organisation] ***************************************************************
fatal: [server01-vm_8aac]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)>"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
