### ISSUE TITLE
community.general.gitlab_project: update option default (branch)

### ISSUE THREAD

**Issue by staehler** [ansible-collections/community.general#7159]
### Summary

Is ist possible to make the option 'default_branch' updateable, so that I can change the default_branch?
Maybe default_branch of project 'my_first_project' was 'main', update the default_branch to 'develop'.
There is a Issue #5995 , where this module (community.general.gitlab_project) was suggested.

### Issue Type

Feature Idea

### Component Name

community.general.gitlab_project

### Additional Information

```yaml (paste below)
- name: set default_branch of project
  community.general.gitlab_project:
    api_url: https://gitlab.example.com/
    validate_certs: true
    api_username: user1
    api_password: "MySecretPassword"
    name: my_first_project
    group: my_group
    default_branch: develop # default_branch was 'main' and should change to 'develop'
    ```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
