### ISSUE TITLE
xml Module Failure with lxml.etree

### ISSUE THREAD

**Issue by shepster** [ansible-collections/community.general#7171]
### Summary

Running the Ansible community.general.xml module on a playbook that worked in the past now throws an error.

### Issue Type

Bug Report

### Component Name

xml

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/Users/shepherd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/8.3.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/shepherd/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.4 (main, Jul 25 2023, 17:08:27) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/Cellar/ansible/8.3.0/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/local/Cellar/ansible/8.3.0/libexec/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

The remote version of the lxml library is:
```console (paste below)
[root@128.34.171.254 ~]# pip list | grep lxml
lxml                             3.2.1
[root@128.34.171.254 ~]#
```

### OS / Environment

local system: macOS Monterey 12.6.8
target system: Amazon Linux 2

### Steps to Reproduce

```yaml (paste below)
---

- name: Configure QA Services / Jira Nodes
  hosts: jira_qa
  remote_user: ec2-user
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  vars:
#     ansible_python_interpreter: /usr/bin/python
#     ansible_python_interpreter: /usr/bin/python3
#     ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    - name: "Add FIPSMode attribute in server.xml"
      community.general.xml:
        path: "/opt/atlassian/jira-software/current/conf/server.xml"
        xpath: /Server/Listener[@className='org.apache.catalina.core.AprLifecycleListener']
        attribute: FIPSMode
        value: off

...
```

### Expected Results

I expected the Ansible code to run and not error out. I have run this code before and it has worked. I don't know what changed in my environment. I think it was a  macOS Monterey upgrade 12.6.7 -> 12.6.8.

My example is using Python 2.7 on the remote system. I have also tried it with #     `ansible_python_interpreter: /usr/bin/python3` and `ansible_python_interpreter: /usr/bin/python3.8` with similar results.

### Actual Results

```console (paste below)
shepherd@duffman dc-deployments-automation % ansible-playbook -v -i inv/hosts xmlTest.yml
Using /Users/shepherd/prog/dc-deployments-automation/ansible.cfg as config file

PLAY [Configure QA Services / Jira Nodes] **************************************************************************

TASK [Add FIPSMode attribute in server.xml] ************************************************************************
Tuesday 29 August 2023  10:15:11 -0700 (0:00:00.079)       0:00:00.079 ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Argument must be bytes or unicode, got 'bool'
fatal: [128.34.171.254]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 128.34.171.254 closed.
", "module_stdout": "Traceback (most recent call last):
  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1693329313.416832-52117-179003560861876/AnsiballZ_xml.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1693329313.416832-52117-179003560861876/AnsiballZ_xml.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1693329313.416832-52117-179003560861876/AnsiballZ_xml.py\", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python2.7/runpy.py\", line 188, in run_module
    fname, loader, pkg_name)
  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code
    exec code in run_globals
  File \"/tmp/ansible_community.general.xml_payload_5xUqf9/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 996, in <module>
  File \"/tmp/ansible_community.general.xml_payload_5xUqf9/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 982, in main
  File \"/tmp/ansible_community.general.xml_payload_5xUqf9/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 707, in set_target
  File \"/tmp/ansible_community.general.xml_payload_5xUqf9/ansible_community.general.xml_payload.zip/ansible_collections/community/general/plugins/modules/xml.py\", line 701, in set_target_inner
  File \"src/lxml/lxml.etree.pyx\", line 713, in lxml.etree._Element.set
  File \"src/lxml/apihelpers.pxi\", line 520, in lxml.etree._setAttributeValue
  File \"src/lxml/apihelpers.pxi\", line 1333, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'bool'
", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************************************************
128.34.171.254             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Tuesday 29 August 2023  10:15:17 -0700 (0:00:05.734)       0:00:05.814 ********
===============================================================================
Add FIPSMode attribute in server.xml ------------------------------------------------------------------------ 5.73s
shepherd@duffman dc-deployments-automation %
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
