### ISSUE TITLE
community.general.make params without value

### ISSUE THREAD

**Issue by snail59** [ansible-collections/community.general#7178]
### Summary

Sometimes, parameters of make do not look like "foo=bar" but just 'foo'  or '-foo'.
For example on FreeBSD,  one can build the system like this: `make buildworld -DWITH_FDT`, as show here: [https://wiki.freebsd.org/FlattenedDeviceTree#FreeBSD_buildworld_WITH_FDT](https://wiki.freebsd.org/FlattenedDeviceTree#FreeBSD_buildworld_WITH_FDT).
But this case does not seem to be manageable as of now. 
For example,
```
community.general.make:
  target: buildworld
  chdir: "{{ freebsd_src_dir }}"
  params:
    -DWITH_FDT: ""
```
becomes `make buildworld -DWITH_FDT=""`

and

```
community.general.make:
  target: buildworld
  chdir: "{{ freebsd_src_dir }}"
  params:
    -DWITH_FDT:
```
becomes `make buildworld -DWITH_FDT=None` 

Do you think it could be implemented ? 

IDEA: I might be wrong, but setting =None as a value is maybe not useful, I do not think this behavior is expected by a user. Instead, it could be set to nothing and fit the case I am talking about.
I do not know if I am clear here so in other words, 
```
  params:
    -DWITH_FDT:
```
could remain `-DWITH_FDT` instead of becoming` -DWITH_FDT=None`

What do you think ?

### Issue Type

Feature Idea

### Component Name

make

### Additional Information

```yaml (paste below)
community.general.make:
  target: buildworld
  chdir: "{{ freebsd_src_dir }}"
  params:
    -DWITH_FDT:
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
