### ISSUE TITLE
sudoers support BSD

### ISSUE THREAD

**Issue by imp1sh** [ansible-collections/community.general#7238]
### Summary

When deploying a sudoers on a FreeBSD system it will fail because it tries to send it to _/etc/sudoers.d_.
This path does not exist.
I know it can be overriden by setting _sudoers_path_ but it would be better IMO when this works out of the box.

This might also be the case for OpenBSD and/or NetBSD but I cannot check.

### Issue Type

Feature Idea

### Component Name

sudoers

### Additional Information

```yaml
- name: test sudoers
  community.general.sudoers:
    name: "test sudoers"
    user: username
    state: present
    commands:
      - "/usr/bin/ls"

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
