### ISSUE TITLE
nmcli: can not set LACP rate for bonded interface

### ISSUE THREAD

**Issue by rptaylor** [ansible-collections/community.general#7243]
### Summary

Similar to https://github.com/ansible-collections/community.general/issues/6065
There is a `runner_fast_rate` option that does exactly what is needed, setting the LACPDU rate to fast or slow - however this only applies when runner=lacp, which is only for network teaming, not bonding. For bonds there is no way to set the LACPDU rate currently AFAICT based on the [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html)

### Issue Type

Feature Idea

### Component Name

community.general.nmcli

### Additional Information

```yaml (paste below)
  - name: Set up bonded network interface
    community.general.nmcli:
      conn_name: bond0
      state: present
      type: bond
      method4: disabled
      method6: disabled
      mode: 802.3ad
      miimon: 100
      xmit_hash_policy: layer2+3
      runner: lacp
      runner_fast_rate: true       # DOES NOT WORK
  - name: Set up network interfaces for bonding
    community.general.nmcli:
      conn_name: "{{ item }}"
      state: present
      type: bond-slave
      master: bond0
      method4: disabled
      method6: disabled
    with_items:
      - enp4s0f0
      - enp4s0f1
```
After that it sets up the bonded interface as expected, but without configuring the desired LACPDU rate:
```
# grep rate /proc/net/bonding/bond0 
LACP rate: slow
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
