### ISSUE TITLE
onepassword lookup plugin - get filecontents from item-type document

### ISSUE THREAD

**Issue by ogaida** [ansible-collections/community.general#7246]
### Summary

Dear Developers,

I tried to get the filecontent with the onepassword lookup plugin. I had a look into the python script and it seems that there is no implementation for that kind of item yet. I would like to use it, because i have some secrets like private keys inside my 1password, which i want to deploy via ansible. 

with the op_cli_v2 i would do a:

```
op read op://<vault>/<document-name>/<file-name>
```

to get the content. 

Thanks in Advance and best regards 
Olli

### Issue Type

Feature Idea

### Component Name

community.general.onepassword

### Additional Information

```yaml (paste below)
- name: Retrieve filecontent for myprivate.key when already signed in to 1Password
  ansible.builtin.debug:
    var: lookup('community.general.onepassword', 'myprivate.key', vault='myvault', type='document', filename='myprivate.key')
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/lookup/onepassword.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/lookup/onepassword.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @azenk @samdoran @scottsb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I think the interface for `onepassword_doc` could be like this:
- `item` is a required
- `vault` is optional

This should use the [`op document get`](https://developer.1password.com/docs/cli/reference/management-commands/document#document-get) command. That is a better interface than `op read` since it doesn't require `vault` to or `filename` be specified.

```yaml
"{{ lookup('community.general.onepassword_doc', 'document name') }}"
```

**Comment by samdoran** [comment]
Since this is a new plugin, it should only support `op` CLI v2. That will make things much easier.

**Comment by ogaida** [comment]
I use it like this `op document get myDocumentName --vault myVaultName` and op cli v2 output the file content to stdout.

**Comment by samdoran** [comment]
That's exactly the command the plugin should run, capturing the output and returning it. Do you want to work on implementing this? Otherwise I would probably start on it.

**Comment by ogaida** [comment]
It would be very very nice if you could do this, my python knowledge is not so great. Thanks in advance samdoran!

**Comment by samdoran** [comment]
Sure thing!

**Comment by ogaida** [comment]
Hello Sam,

did you find time to do something on that topic? It would be great.

best regards
Oliver

**Comment by samdoran** [comment]
Not yet. On my list.

**Comment by samdoran** [comment]
I started working on this Friday. I'll have a draft PR up this week.

**Comment by VirtualWolf** [comment]
Would this also work for files attached to regular items (like a secure note for example)? My use-case is similar to @ogaida but I've got some Cloudflare SSL origin certificates stored as files attached to a secure note (as opposed to the specific "Document" type of item). With `op` I can read the content quite happily:

```
$ op read "op://VMs/Cloudflare Origin Certificates/example.com.crt"
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
```

But running the current `community.general.onepassword` lookup just returns an empty string:

```yaml
- name: Testing
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: "{{ lookup('community.general.onepassword', 'Cloudflare Origin Certificates', field='example.com.crt') }}"
```

```
$ ansible-playbook playbooks/test.yml 

PLAY [Testing] **************************************************************************************************************

TASK [ansible.builtin.debug] **************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}

PLAY RECAP **************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
