### ISSUE TITLE
gitlab_*_variables deletes all variables in purge mode

### ISSUE THREAD

**Issue by MaxBidlingmaier** [ansible-collections/community.general#7250]
### Summary

When using community.general 7.4 to provision gitlab with an exact list of variables (purge:true) all variables get deleted. This took our GitLab env with more then 1000 repos fully offline ;-)

This is due to the change done to the modules without adding the new 'raw' parameter to the list of known parameters in the module_utils/gitlab

### Issue Type

Bug Report

### Component Name

gitlab_group_variable
gitlab_project_variable

### Ansible Version

does not matter

### Community.general Version

7.4

### OS / Environment

any

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  gather_facts: false
  vars:
    gv:
      Test:
        value: "12345"
        masked: false
        protected: false
        variable_type: env_var

  tasks:
    - name: test
      community.general.gitlab_group_variable:
        api_url: "https://gitlab/"
        api_token: "secrettoken
        group: "an existing gitlab group"
        purge: true
        vars: "{{ gv }}"
```

### Expected Results

The group varibale Test is set, and no other variable

### Actual Results

no variables are set at all

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
