### ISSUE TITLE
Add `executable` option to community.general.ansible_galaxy_install module

### ISSUE THREAD

**Issue by smatterchew** [ansible-collections/community.general#7261]
### Summary

The `community.general.ansible_galaxy_install` module does not find my copy of `ansible-galaxy` in `~/.local/bin`.  I would like to be able to define an explicit path to `ansible-galaxy`. 

### Issue Type

Feature Idea

### Component Name

plugins/modules/ansible_galaxy_install.py

### Additional Information

```yaml (paste below)
- name: Ansible collections are installed
  become: true
  become_user: "{{ new_user_account }}"
  community.general.ansible_galaxy_install:
    type: collection
    name:
      - ansible.netcommon
      - ansible.posix
      - ansible.controller
    executable: ~/.local/bin/ansible-galaxy
```
I tried adding and environmental var to add `~/.local/bin` to the path with no effect.
```yaml
  environment:
    - PATH: ~/.local/bin:$PATH
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
