### ISSUE TITLE
Ooops! Snap installation failed while executing

### ISSUE THREAD

**Issue by onknows** [ansible-collections/community.general#7265]
### Summary

This is related to #7130 . This issue #7130 is still not completely fixed. The following code fails on Ubuntu 22.04. I tested this with 7.3.0, 7.4.0. It fails with those versions. The code below does however work when using 6.6.0.

```yaml
    - name: Install packages
      ansible.builtin.apt:
        name:
          - snapd
          - fuse
          - udev
        state: present
        update_cache: true

    - name: Install Microk8s
      community.general.snap:
        name: microk8s
        classic: true
        channel: 1.26/stable
```

```bash
TASK [Install Microk8s] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.general.plugins.module_utils.mh.exceptions.ModuleHelperException
fatal: [c2d-galaxy1]: FAILED! => changed=false 
  channel: 1.26/stable
  classic: true
  cmd: '[''state'', ''classic'', ''channel'', ''dangerous'', ''microk8s'']'
  msg: Ooops! Snap installation failed while executing '['state', 'classic', 'channel', 'dangerous', 'microk8s']', please examine logs and error output for more details.
  output:
    channel: 1.26/stable
    classic: true
    cmd: '[''state'', ''classic'', ''channel'', ''dangerous'', ''microk8s'']'
    snap_names:
    - microk8s
    snaps_installed:
    - microk8s
  snap_names:
  - microk8s
  snaps_installed:
  - microk8s
  vars:
    channel: 1.26/stable
    classic: true
    cmd: '[''state'', ''classic'', ''channel'', ''dangerous'', ''microk8s'']'
    snap_names:
    - microk8s
    snaps_installed:
    - microk8s
```

### Issue Type

Bug Report

### Component Name

snap

### Ansible Version

```console (paste below)
θ97° [:ansible-dev]└2 master(+104/-29,-1)* 130 ± ansible --version
ansible [core 2.15.0]
  config file = /home/onknows/git/gitlab/c2/ansible-dev/ansible-dev.cfg
  configured module search path = ['/home/onknows/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/onknows/.virtualenv/c2d/lib/python3.10/site-packages/ansible
  ansible collection location = /home/onknows/git/gitlab/c2/ansible-dev-collections:/home/onknows/git/gitlab/c2/ansible-dev
  executable location = /home/onknows/.virtualenv/c2d/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/onknows/.virtualenv/c2d/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
# /home/onknows/git/gitlab/c2/ansible-dev/ansible_collections
Collection        Version
----------------- -------
community.general 7.4.0 

```

### Configuration

```yaml
    - name: Install packages
      ansible.builtin.apt:
        name:
          - snapd
          - fuse
          - udev
        state: present
        update_cache: true

    - name: Install Microk8s
      community.general.snap:
        name: microk8s
        classic: true
        channel: 1.26/stable

```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
---
- name: galaxy.yml
  hosts: galaxy
  become: yes

  tasks:

    - name: Install packages
      ansible.builtin.apt:
        name:
          - snapd
          - fuse
          - udev
        state: present
        update_cache: true

    - name: Install Microk8s
      community.general.snap:
        name: microk8s
        classic: true
        channel: 1.26/stable
```

### Expected Results

Snap install like on community.general 6.6.0

### Actual Results

```console (paste below)
TASK [Install Microk8s] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.general.plugins.module_utils.mh.exceptions.ModuleHelperException
fatal: [c2d-galaxy1]: FAILED! => changed=false 
  channel: 1.26/stable
  classic: true
  cmd: '[''state'', ''classic'', ''channel'', ''dangerous'', ''microk8s'']'
  msg: Ooops! Snap installation failed while executing '['state', 'classic', 'channel', 'dangerous', 'microk8s']', please examine logs and error output for more details.
  output:
    channel: 1.26/stable
    classic: true
    cmd: '[''state'', ''classic'', ''channel'', ''dangerous'', ''microk8s'']'
    snap_names:
    - microk8s
    snaps_installed:
    - microk8s
  snap_names:
  - microk8s
  snaps_installed:
  - microk8s
  vars:
    channel: 1.26/stable
    classic: true
    cmd: '[''state'', ''classic'', ''channel'', ''dangerous'', ''microk8s'']'
    snap_names:
    - microk8s
    snaps_installed:
    - microk8s

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
