### ISSUE TITLE
filesystem: Fails if the filesystem already exists

### ISSUE THREAD

**Issue by mks-h** [ansible-collections/community.general#7283]
### Summary

I'm trying to format a partition with BTRFS, but the module fails if it already exists (like on the second run of the same playbook)

### Issue Type

Bug Report

### Component Name

filesystem

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mks/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/mks/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

My OS: Fedora 38
Host OS: Alpine Linux Standard 3.18.3 x86_64

### Steps to Reproduce

```yaml (paste below)
 - name: Create primary partition
      community.general.parted:
        device: /dev/sda
        number: 2
        part_start: 1MiB
        part_end: 100%
        fs_type: btrfs
        label: gpt
        state: present
 - name: Format primary partition with BTRFS
      community.general.filesystem:
        dev: /dev/sda2
        fstype: btrfs
```

### Expected Results

Expected to don't have any change or failure, since the partition already is in the defined state.

### Actual Results

```console (paste below)
TASK [Format primary partition with BTRFS] *************************************************************************
fatal: [192.168.1.2]: FAILED! => {"changed": false, "err": "", "msg": "'/dev/sda2' is already used as /dev/sda2: UUID=\"dd9b269b-7ecf-401b-9f65-60d626d59e96\" TYPE=\"btrfs\", use force=true to overwrite", "rc": 0}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
