### ISSUE TITLE
New Docker Stack Task Info Module

### ISSUE THREAD

**Issue by imjoseangel** [ansible-collections/community.general#729]
##### SUMMARY

I would like to list all stacks tasks from a given stack name like `docker stack ps` in order to run some setup containers if a particular stack is not present.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

docker_stack_task_info.py

##### ADDITIONAL INFORMATION

```yaml
   - name: List all docker stacks
     docker_stack_task_info:
       name: test_stack      # return list tasks from specific stack name
```
