### ISSUE TITLE
cargo: Support git, branch, force, features, and all-features flags

### ISSUE THREAD

**Issue by aretrosen** [ansible-collections/community.general#7338]
### Summary

I’d like to be able to use ```community.general.cargo``` to install from git (mentioning branch, tag, rev if needed) and also mention whether we should force install, and enable features or all-features when needed. One example situation where I needed it was when I was installing taplo from git and needed the all-features flag.

### Issue Type

Feature Idea

### Component Name

cargo

### Additional Information

```yaml (paste below)
name: Installing taplo cli
community.general.cargo:
  name: taplo-cli
  git: https://github.com/tamasfe/taplo
  all-features: true
  locked: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/cargo.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cargo.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @radek-sprta
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by radek-sprta** [comment]
Thanks for the suggestion. I'll try to look into it Soon™

**Comment by maximiliankolb** [comment]
I also ran into this issue due to [uv](https://docs.astral.sh/uv/getting-started/installation/#cargo) which you have to install from source. My current solution:

````yaml
# tasks/main.yml
- name: "Check if uv_revision exists"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.uv_revision"
  register: result_file_check

- name: "Create uv_revision if not present"
  ansible.builtin.file:
    mode: "0644"
    path: "{{ ansible_user_dir }}/.uv_revision"
    state: touch
  when: not result_file_check.stat.exists

- name: "Read present uv_revision"
  ansible.builtin.slurp:
    src: "{{ ansible_user_dir }}/.uv_revision"
  register: uv_result

- name: "Ensure uv_revision exists"
  when: uv_result.content | b64decode | trim != uv_revision
  block:
    - name: "Build Rust crate uv from source"
      ansible.builtin.command:
        cmd: "cargo install --git https://github.com/astral-sh/uv --version {{ uv_revision }} uv"
      register: result
      changed_when: "'Installed package uv v{{ uv_revision }}' in result.stdout_lines"

    - name: "Write uv revision to file"
      ansible.builtin.template:
        dest: "{{ ansible_user_dir }}/.uv_revision"
        mode: "0644"
        src: uv_revision.j2

# templates/uv_revision.j2
{{ uv_revision }}

# vars/main.yml
uv_revision: "0.5.18"
````
