### ISSUE TITLE
community.general.proxmox_kvm won't adjust cpu/memory/ballooning with cloned VMs

### ISSUE THREAD

**Issue by PC-Admin** [ansible-collections/community.general#7361]
### Summary

The community.general.proxmox_kvm module doesn't allow you to set cores/memory/balloon/shares settings when cloning a VM.

It copies these values from the clone and ignores values defined in the Ansible task. As a workaround I ended up using the Proxmox API, but it would be cool if this module could handle it instead.

Here's the module for reference: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html

### Issue Type

Bug Report

### Component Name

community.general.proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.4]
  config file = /home/pcadmin/MyVault/PSP_Repos/provision-servers/ansible.cfg
  configured module search path = ['/home/pcadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/pcadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/pcadmin/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 22.04 for the Ansible controller
Proxmox 8.0 cluster

### Steps to Reproduce

1) Get a Proxmox 8 server/cluster setup.

2) Create a VM template for whatever OS you fancy.

3) Attempt to clone it while specifying cores, memory, balloon/shares using an Ansible task that's similar to this one:
```
- name: "Create a full clone of the template for each host (sequentially)"
  delegate_to: localhost
  community.general.proxmox_kvm:
    api_host: "{{ hostvars[item].proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ hostvars[item].inventory_hostname }}"
    node: "{{ hostvars[item].proxmox_node }}"
    clone: "{{ hostvars[item].proxmox_template }}"
    storage: "{{ hostvars[item].proxmox_storage }}"
    cores: "{{ hostvars[item].proxmox_kvm_cores | int }}"
    memory: "{{ hostvars[item].proxmox_kvm_memory | int }}"
    balloon: "{{ hostvars[item].proxmox_kvm_balloon | int }}"
    shares: "{{ hostvars[item].proxmox_kvm_shares | int }}"
    full: true
    state: present
    timeout: 300
  register: new_clone_info
  when: hostvars[item].spawn_on_proxmox | bool
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    pause: 1
  run_once: true
```

### Expected Results

I expect that the values defined here would actually be applied to that new host:
```
    cores: "{{ hostvars[item].proxmox_kvm_cores | int }}"
    memory: "{{ hostvars[item].proxmox_kvm_memory | int }}"
    balloon: "{{ hostvars[item].proxmox_kvm_balloon | int }}"
    shares: "{{ hostvars[item].proxmox_kvm_shares | int }}"
```

### Actual Results

But even when running this task repeatedly it only copies these values from the VM template.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/proxmox_kvm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @UnderGreen @helldorado @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by PC-Admin** [comment]
If anyone's curious about the workaround you can use the Proxmox API to set these:
```
- name: Set VM cores/memory/balloon/shares via the Proxmox API
  delegate_to: localhost
  uri:
    url: "https://{{ hostvars[item].proxmox_host }}:8006/api2/json/nodes/{{ hostvars[item].proxmox_node }}/qemu/{{ hostvars[item].vmid }}/config"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_user }}!{{ proxmox_token_id }}={{ proxmox_token_secret }}"
    body_format: form-urlencoded
    body:
      cores: "{{ hostvars[item].proxmox_kvm_cores | default(omit) }}"
      memory: "{{ hostvars[item].proxmox_kvm_memory | default(omit) }}"
      balloon: "{{ hostvars[item].proxmox_kvm_balloon | default(omit) }}"
      shares: "{{ hostvars[item].proxmox_kvm_shares | default(omit) }}"
    validate_certs: no  # set this to yes in a production environment if you have valid SSL certs
  register: api_response
  when: ( hostvars[item].proxmox_kvm_cores is defined ) and ( hostvars[item].spawn_on_proxmox | bool )
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    pause: 1
  run_once: true
```

**Comment by randompherret** [comment]
I'm working on doing some cloning as well. I am just doing a second update call such as:
```
- name: Create guest
  delegate_to: localhost
  community.general.proxmox_kvm:
    node: vh02
    target: vh02
    name: "{{ inventory_hostname }}"
    clone: jammyTemplate
- name: Update guest Specs
  delegate_to: localhost
  community.general.proxmox_kvm:
    name: "{{ inventory_hostname }}"
    cores: 4
    sockets: 4
    memory: 16384
    update: true
```
