### ISSUE TITLE
community.general.lxd_container: "Cannot connect to the LXD server"

### ISSUE THREAD

**Issue by mormislaw** [ansible-collections/community.general#7393]
### Summary

When I try to connect to a remote server, according to the sixth example in the [lxd_container documentation](https://docs.ansible.com/ansible/latest/collections/community/general/lxd_container_module.html#examples) I receive this message:
```
    "msg": "cannot connect to the LXD server"
```

I'd really appreciate any help with fixing it

### Issue Type

Bug Report

### Component Name

community.general.lxd_container

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/home/joshua/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/joshua/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/joshua/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/joshua/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/joshua/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.0  

# /home/joshua/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.4.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Ubuntu 22.04.3 with Ansible installed using APT and LXD installed using Snap

### Steps to Reproduce

Example playbook:

```yaml (paste below)
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      community.general.lxd_container:
        url: https://127.0.0.1:8443
        client_cert: "/home/joshua/snap/lxd/common/config/client.crt"
        client_key: "/home/joshua/snap/lxd/common/config/client.key"
        trust_password: 1234
        name: test
        ignore_volatile_options: true
        state: started
        config: {"user.testkey": "test"}
        #cloud_init: |
        #    #cloud-config
        #    packages:
        #      - openssh-server
        #    users:
        #      - name: root
        #        shell: /bin/bash
        #        ssh_authorized_keys:
        #          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJpXcJ4r3xLSc3zZdFOqMz+IKsmn/Lxhbk55pjIDVmwL pawel.urbanek@medvc.eu
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams # if you get a 404, try setting protocol: simplestreams
          alias: ubuntu/22.04/cloud
        profiles: ["testing1"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

### Expected Results

Ansible should connect to the server

### Actual Results

```console (paste below)
The full traceback is:
  File "/tmp/ansible_community.general.lxd_container_payload_313fpkxm/ansible_community.general.lxd_container_payload.zip/ansible_collections/community/general/plugins/modules/lxd_container.py", line 723, in run
  File "/tmp/ansible_community.general.lxd_container_payload_313fpkxm/ansible_community.general.lxd_container_payload.zip/ansible_collections/community/general/plugins/module_utils/lxd.py", line 86, in authenticate
    return self._send_request('POST', '/1.0/certificates', body_json=body_json)
  File "/tmp/ansible_community.general.lxd_container_payload_313fpkxm/ansible_community.general.lxd_container_payload.zip/ansible_collections/community/general/plugins/module_utils/lxd.py", line 110, in _send_request
    raise LXDClientException('cannot connect to the LXD server', err=e)
fatal: [localhost]: FAILED! => {
    "actions": [],
    "changed": false,
    "diff": {
        "after": {},
        "before": {}
    },
    "invocation": {
        "module_args": {
            "architecture": null,
            "client_cert": "/home/joshua/snap/lxd/common/config/client.crt",
            "client_key": "/home/joshua/snap/lxd/common/config/client.key",
            "config": {
                "user.testkey": "test"
            },
            "devices": null,
            "ephemeral": null,
            "force_stop": false,
            "ignore_volatile_options": true,
            "name": "test",
            "profiles": [
                "testing1"
            ],
            "project": null,
            "snap_url": "unix:/var/snap/lxd/common/lxd/unix.socket",
            "source": {
                "alias": "ubuntu/22.04/cloud",
                "mode": "pull",
                "protocol": "simplestreams",
                "server": "https://images.linuxcontainers.org",
                "type": "image"
            },
            "state": "started",
            "target": null,
            "timeout": 600,
            "trust_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "type": "container",
            "url": "https://127.0.0.1:8443",
            "wait_for_container": false,
            "wait_for_ipv4_addresses": true
        }
    },
    "msg": "cannot connect to the LXD server"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
