### ISSUE TITLE
Support creating ZFS snapshots recursively

### ISSUE THREAD

**Issue by Spanfile** [ansible-collections/community.general#7395]
### Summary

Support creating ZFS snapshots recursively on all descendant datasets with the `-r` option for the `zfs snapshot` command, i.e. `zfs snapshot -r tank/dataset@now`. The recursion could be controlled with a `recurse` parameter on the module.

### Issue Type

Feature Idea

### Component Name

zfs

### Additional Information

```yaml (paste below)
- name: Create snapshots on dataset and all its descendants
  community.general.zfs:
    name: tank/dataset@now
    state: present
    recurse: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
