### ISSUE TITLE
keycloak_user: create user with groups atomically

### ISSUE THREAD

**Issue by rmuir** [ansible-collections/community.general#7400]
### Summary

The current code causes a module failure in my configuration, due to the use of ldap filters on user groups.

Even though I supply groups, the code initially creates a user with zero groups, then comes back around and tries to add groups after-the-fact. But the module crashes before that second step happens, when it tries to do a GET on the user it just created (which is now gone from keycloak because it the user doesn't match the ldap filters, because it doesn't have any groups)

For now as a workaround I use two `uri` tasks to manage keycloak users (this is how I feel the module should work when you supply `groups` for the user). The user is created atomically in one http request with the groups supplied:

```
- name: Fetch Token with direct access grant
  uri:
    url: https://xxx/auth/realms/master/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
      username: admin
      password: xxxx
      client_id: admin-cli
      grant_type: password
  register: token

- name: Create new user
  uri:
    url: https://xxx/auth/admin/realms/master/users
    method: POST
    headers:
      Authorization: "Bearer {{ token.json.access_token }}"
    status_code: [201,409]
    body_format: json
    body:
      username: someuser
      groups:
        - ImportantGroup
  register: user_creation
  changed_when: user_creation.status == 201
```

### Issue Type

Feature Idea

### Component Name

keycloak_user

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
