### ISSUE TITLE
Support server-side artifact fetching

### ISSUE THREAD

**Issue by aph3rson** [ansible-collections/community.general#7402]
### Summary

The `proxmox_template` module allows for uploading images for either iso or vztmpl usage. These images have to be available locally to the Ansible runner, and are specified by the `src` parameter. Under the hood, this method calls the [`upload` method](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/storage/{storage}/upload) within the Proxmox API:
https://github.com/ansible-collections/community.general/blob/cdb19ab8c173b2ac9352d07a320da112c8d3dd72/plugins/modules/proxmox_template.py#L174

However, there's also a [`download-url` method](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/storage/{storage}/download-url) which causes Proxmox itself to download the artifact from an appropriate URL. This has the benefits of using Proxmox's task engine vs. alternatives like `get_url` on the Proxmox node directly.

### Issue Type

Feature Idea

### Component Name

proxmox_template

### Additional Information

How this currently looks with uploading a local file:

```yaml
- name: Upload new openvz template with minimal options
  community.general.proxmox_template:
    node: uk-mc02
    api_user: root@pam
    api_password: 1q2w3e
    api_host: node1
    src: ~/ubuntu-14.04-x86_64.tar.gz
```

How this might look by fetching the file server-side:
```yaml
- name: Fetchnew openvz template with minimal options
  community.general.proxmox_template:
    node: uk-mc02
    api_user: root@pam
    api_password: 1q2w3e
    api_host: node1
    fetch:
      url: https://foo.example.com/fedora.img
      checksum: sha256:d334670401ff3d5b4129fcc662cf64f5a6e568228af59076cc449a4945318482
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
