### ISSUE TITLE
redis_data module needs support for the db parameter

### ISSUE THREAD

**Issue by betelgeuse** [ansible-collections/community.general#7404]
### Summary

https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/redis.py

There's currently no way to specify that data to operate on is in a db other than 0. 

### Issue Type

Feature Idea

### Component Name

redis_data

### Additional Information

```yaml (paste below)
- name: Set key foo=bar on db 1
  community.general.redis_data:
    key: foo
    value: bar
    db: 1
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
