### ISSUE TITLE
nomad_job module needs support host ports difent than 4646

### ISSUE THREAD

**Issue by apecnascimento** [ansible-collections/community.general#7411]
### Summary

Currently the nomad_job module only has the host parameter, making it impossible to use ports other than the default (4646)

### Issue Type

Feature Idea

### Component Name

nomad_job

### Additional Information

```yaml (paste below)
- name: Create job
  community.general.nomad_job:
    host: localhost
    port: 4645
    state: present
    content: "{{ lookup('ansible.builtin.file', 'job.hcl') }}"
    timeout: 120
```
Adding the port parameter will make it possible to use ports other than the default port

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
