### ISSUE TITLE
Abiliti to assign realm roles to groups

### ISSUE THREAD

**Issue by ablasmiisu** [ansible-collections/community.general#7424]
### Summary

Hello

I am maping keycloak realm admin permissions to imported LDAP groups and it would be nice to be able to assign realm based (composite) roles to groups with ansible. Example below.

### Issue Type

Feature Idea

### Component Name

keycloak_group

### Additional Information

```
- name: Assign admin role to group
  community.general.keycloak_group:
    name: kc-group-name
    state: present
    auth_client_id: admin-cli
    auth_keycloak_url: https://auth.example.com/auth
    auth_realm: master
    auth_username: USERNAME
    auth_password: PASSWORD
    realmRoles
      - name: admin
  delegate_to: localhost

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
