### ISSUE TITLE
Assign OTP Token to Users

### ISSUE THREAD

**Issue by gary-sixgen** [ansible-collections/community.general#7432]
### Summary

I am able to add a OTP token with an owning User and configure the user to user 'password+otp' to login, however, I see no way to assign the OTP Token to a User(s) for login so authentication fails.

Using the CLI, I believe the command `ipa otptoken-add-yubikey` works to this effect.

![Screenshot 2023-10-26 at 11 45 44 AM](https://github.com/ansible-collections/community.general/assets/126720554/1151a193-ba7c-4649-b4de-b8b871e147ac)

This request is to add a "Users" field to `ipa_otptoken`

### Issue Type

Feature Idea

### Component Name

ipa_otptoken
ipa_user

### Additional Information

```yaml
- name: base64 encode username for secret
  set_fact:
    secret: "{{ user.username | b64encode }}"
- name: Create OTP Token in IPA with the secret
  community.general.ipa_otptoken:
    uniqueid: "{{ user.username }}"
    otptype: totp
    owner: "{{ user.username }}"
    description: "An OTP token for {{ user.username }}"
    ipa_host: "{{ groups['ipaservers'] | list | first }}"
    ipa_user: admin
    ipa_pass: "{{ ipa_password }}"
    secretkey: "{{ secret }}"
- name: enable 'Two factor authentication (password + OTP)'
  community.general.ipa_user:
    name: "{{ user.username }}"
    ipa_host: "{{ groups['ipaservers'] | list | first }}"
    ipa_pass: "{{ ipaadmin_password }}"
    ipa_user: "{{ ipaadmin_user }}"
    userauthtype:
      - otp
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
