### ISSUE TITLE
keycloak_user: setting group state to absent doesn't remove group from user

### ISSUE THREAD

**Issue by ziermmar** [ansible-collections/community.general#7433]
### Summary

When I try to remove a group membership from a user, it doesn't work

### Issue Type

Bug Report

### Component Name

keycloak_user

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.8]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 7.5.0  
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
    - name: Add user to groups
      community.general.keycloak_user:
        username: user1
        groups:
          - name: group1
            state: present
          - name: group2
            state: present
        state: present

    - name: Remove user from group2
      community.general.keycloak_user:
        username: user1
        groups:
          - name: group1
            state: present
          - name: group2
            state: absent
        state: present
```

### Expected Results

User is member of group1, but not group2

### Actual Results

User is member of both groups

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
