### ISSUE TITLE
IdentityAgent for ssh_config

### ISSUE THREAD

**Issue by jamesdh** [ansible-collections/community.general#7435]
### Summary

Support for SSH config attribute "IdentityAgent":

```
IdentityAgent
   Specifies the UNIX-domain socket used to communicate with
   the authentication agent.

   This option overrides the SSH_AUTH_SOCK environment
   variable and can be used to select a specific agent.
   Setting the socket name to none disables the use of an
   authentication agent.  If the string "SSH_AUTH_SOCK" is
   specified, the location of the socket will be read from the
   SSH_AUTH_SOCK environment variable.  Otherwise if the
   specified value begins with a ‘$’ character, then it will
   be treated as an environment variable containing the
   location of the socket.

   Arguments to IdentityAgent may use the tilde syntax to
   refer to a user's home directory, the tokens described in
   the TOKENS section and environment variables as described
   in the ENVIRONMENT VARIABLES section.
```

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

```yaml
- name: SSH config
  community.general.ssh_config:
    user: serviceuser
    forward_agent: true
    host: "*"
    identity_agent: "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    state: present
```

Password managers such as 1Password [now support SSH agent integration](https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client) which require configuration similar to the one given here. 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
