### ISSUE TITLE
proxmox_kvm: Configuration updates are not idempotent

### ISSUE THREAD

**Issue by rayment** [ansible-collections/community.general#7438]
### Summary

Updating a VM configuration is not an idempotent operation, always returning `status: changed` despite no change or difference in configuration.

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/ansible/venv/bin/python3)
  jinja version = 3.1.2
  libyaml = Tru
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/ansible/venv/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.0
```

### Configuration

n/a

### OS / Environment

**Ansible controller:**

```
$ uname -a
Linux ANSIBLEHOST 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

Running as a Debian 12 Virtual Machine inside of Proxmox 8.0.4.

**Proxmox host:**

```
$ uname -a
Linux PRIME 6.2.16-15-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-15 (2023-09-28T13:53Z) x86_64 GNU/Linux
```

### Steps to Reproduce

Run the following playbook:

```yaml (paste below)
- hosts: controller
  tasks:
    - name: Clone VM
      community.general.proxmox_kvm:
        # API setup
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_host: "{{ proxmox_api_host }}"

        # Clone options
        full: true
        format: unspecified
        storage: local-lvm
        clone: "{{ template }}"
        node: "{{ node }}"
        name: "{{ name }}"
        newid: "{{ vmid }}"

        # Machine hardware
        ide:
          ide0: 'local:cloudinit,format=qcow2'

        state: present
      register: vm_create

    - name: Update VM configuration
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_host: "{{ proxmox_api_host }}"
        name: "{{ name }}"
        node: "{{ node }}"
        kvm: true
        machine: pc
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        #balloon: 1024
        update: true
      register: vm_config
```

For me, variables are as follows:
- `template=Template.Debian12`
- `node: PRIME`
- `storage=local-lvm`
- `name=BUILDSRV01`
- `vmid=400`
- `cores=4`
- `memory=8192`

### Expected Results

- When the configuration inside of the playbook differs to the current configuration on Proxmox, `changed` is expected.
- When the configuration inside of the playbook matches the current configuration on Proxmox, `succeeded` is expected.

### Actual Results

```console (paste below)
$ ansible-playbook $PLAYBOOK_FILE
[WARNING]: Found variable using reserved name: name
PLAY [controller] ******************************************************************
TASK [Gathering Facts] *********************************************************
ok: [controller]
TASK [Clone VM] ****************************************************************
ok: [controller]
TASK [Update VM configuration] *************************************************
changed: [controller]
PLAY RECAP *********************************************************************
controller              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

Note how the last task is `changed`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
