### ISSUE TITLE
ipa_host fails

### ISSUE THREAD

**Issue by sjpb** [ansible-collections/community.general#7457]
### Summary

I'm trying to get info about freeIPA hosts which may or may not exist using check_mode:

```
- name: Get ipa host information
  # This uses DNS to find the ipa server, which works as this is running on the enrolled ipa server
  # It doesn't fail even if the host doesn't exist
  community.general.ipa_host:
    name: "{{ node_fqdn }}"
    ip_address: "{{ freeipa_client_ip }}"
    ipa_host: "{{ groups['freeipa_server'].0 }}"
    ipa_pass: "{{ vault_freeipa_admin_password }}"
    ipa_user: admin
    state: present
    validate_certs: false
  delegate_to: "{{ groups['freeipa_server'].0 }}"
  register: _ipa_host_check
  check_mode: yes
  changed_when: false
```

The module fails with `login: HTTP Error 401: Unauthorized`.

From adding `debug=true` to `/etc/ipa/default.conf` and running `systemctl restart ipa` then retrying it I see this in `/var/log/httpd/error_log `:

```
[Tue Oct 31 15:02:26.700542 2023] [wsgi:error] [pid 39338:tid 140085431125760] [remote 192.168.3.148:53992] ipa: DEBUG: http://noetchosts-control.noetchosts.invalid:80 "GET /ipa/session/cookie HTTP/1.1" 301 274
[Tue Oct 31 15:02:26.702574 2023] [wsgi:error] [pid 39338:tid 140085431125760] [remote 192.168.3.148:53992] ipa: DEBUG: http://noetchosts-control.noetchosts.invalid:80 "GET /public/need_auth.html HTTP/1.1" 200 577
[Tue Oct 31 15:02:26.703174 2023] [wsgi:error] [pid 39338:tid 140085431125760] [remote 192.168.3.148:53992] ipa: INFO: 401 Unauthorized: No session cookie found
```

This is reviving a dormant PR in my code, so other things may have changed but the above task definitely used to work.

### Issue Type

Bug Report

### Component Name

community.general.ipa_host

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.6]
  config file = /home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg
  configured module search path = ['/home/rocky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rocky/slurm-app-noetchosts/venv/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/rocky/slurm-app-noetchosts/ansible/collections
  executable location = /home/rocky/slurm-app-noetchosts/venv/bin/ansible
  python version = 3.8.12 (default, May 10 2022, 23:46:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/rocky/slurm-app-noetchosts/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.0  

# /home/rocky/slurm-app-noetchosts/venv/lib64/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.0.2  

# /home/rocky/slurm-app-noetchosts/venv/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.0.2 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANY_ERRORS_FATAL(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = True
CALLBACKS_ENABLED(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = ['ansible.posix.profile_tasks']
COLLECTIONS_PATHS(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = ['/home/rocky/slurm-app-noetchosts/ansible/collections']
DEFAULT_FILTER_PLUGIN_PATH(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = ['/home/rocky/slurm-app-noetchosts/ansible/filter_plugins']
DEFAULT_FORKS(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = 30
DEFAULT_GATHERING(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = ['/home/rocky/slurm-app-noetchosts/environments/common/inventory', '/home/rocky/slurm-app-noetchosts/environments/.stackhpc/invent>
DEFAULT_ROLES_PATH(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = ['/home/rocky/slurm-app-noetchosts/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/rocky/slurm-app-noetchosts/environments/.stackhpc/ansible.cfg) = False
```

### OS / Environment

RockyLinux 8.5 (ansible host), RockyLinux8.8 (targets)

### Steps to Reproduce

See above

### Expected Results

`_ipa_host_check` to be populated

### Actual Results

See above

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
