### ISSUE TITLE
ldap_attrs throws error on multiple runs with olcSyncRepl

### ISSUE THREAD

**Issue by jake2184** [ansible-collections/community.general#746]
##### SUMMARY

ldap_attrs is throwing an error on subsequent runs after correctly applying config on the first run. I am using the module to set a number of attributes, and olcSyncRepl is the first attribute I have met which exhibits this behaviour.

I suspect the issue is that the value isn't matched on a check, so the module tries to re-add it. However:
1) Why doesn't the check work correctly?
2) The state is specified as exact, so why isn't the value forcibly overwritten if the check fails? (Not my expected/desired behaviour in this situation, but what I would expect the logic of the module to do)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.ldap_attr(s)

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/jake2184/ansible.cfg
  configured module search path = ['/home/jake2184/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/jake2184/ansible.cfg) = True
DEFAULT_FORKS(/home/jake2184/ansible.cfg) = 25
DEFAULT_HOST_LIST(/home/jake2184/ansible.cfg) = [~/ansible/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/jake2184/ansible.cfg) = ['~/ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup']
DEFAULT_REMOTE_USER(/home/jake2184/ansible.cfg) = root
DEFAULT_STDOUT_CALLBACK(/home/jake2184/ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(/home/jake2184/ansible.cfg) = /home/jake2184/.ssh/vault_password
HOST_KEY_CHECKING(/home/jake2184/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Centos 8.2

##### STEPS TO REPRODUCE

Running the below task on a database which has olcSyncRepl not defined correctly applies the config on first run. On subsequent runs the error is thrown.

I have tested using both "ordered: yes" and hard-coding indexes, and the ldap_attr/ldap_attrs module. The behaviour is the same.

```yaml
- name: Configure replication
  community.general.ldap_attrs:
    dn: olcDatabase={2}mdb,cn=config
    attributes:
      olcSyncRepl:
        - >-
          rid=1 provider=ldaps://ldap-001.internal searchbase=dc=company,dc=com tls_cert=/etc/openldap/certs/ldap-001.internal.crt.pem tls_key=/etc/openldap/certs/ldap-001.internal.key.pem
        - >-
          rid=2 provider=ldaps://ldap-002.internal searchbase=dc=company,dc=com tls_cert=/etc/openldap/certs/ldap-002.internal.crt.pem tls_key=/etc/openldap/certs/ldap-002.internal.key.pem
        - >-
          rid=3 provider=ldaps://ldap-003.internal searchbase=dc=company,dc=com tls_cert=/etc/openldap/certs/ldap-003.internal.crt.pem tls_key=/etc/openldap/certs/ldap-003.internal.key.pem
    state: exact
    ordered: yes
```

##### EXPECTED RESULTS

The subsequent runs to not error or implement any changes. 

##### ACTUAL RESULTS

```
Type or value exists', 'info': 'modify/add: olcSyncrepl: value #0 already exists
```
Outputs of the initial successful run and a failed subsequent run (-vvv): https://gist.github.com/jake2184/0efd2bccb7e365f8ee8025baa61126da
