### ISSUE TITLE
Allow Keycloak_* modules to use grant_type=client_credentials

### ISSUE THREAD

**Issue by logabot** [ansible-collections/community.general#7469]
### Summary

Some of keycloak modules( example [keycloak_realm.py](plugins/modules/keycloak_realm.py) ) don't allow to use grant_type = client_credentials. 
In argument I can't define auth_client_secret  without `auth_username` and `auth_password`. 
https://github.com/ansible-collections/community.general/blob/6d0bcec1cb579ce7244b3042177d44ca1abd9573/plugins/modules/keycloak_realm.py#L692-L697

In module_utils grant_type is hardcoded. 
https://github.com/ansible-collections/community.general/blob/6d0bcec1cb579ce7244b3042177d44ca1abd9573/plugins/module_utils/identity/keycloak/keycloak.py#L164-L180

You can allow to define custom grant_type or one of. 

### Issue Type

Feature Idea

### Component Name

keycloak_realm

### Additional Information

```yaml
- name: Create keycloak realm
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_client_id: "{{ auth_client_id }}"
    auth_realm: "{{ auth_realm }}"
    auth_client_secret: "{{ auth_client_secret }}"
    realm: "{{ realm_name }}"
    state: present
    auth_username: omit
    auth_password: omit
.....
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
