### ISSUE TITLE
nmcli module wifi_sec failed to set pairwise, proto, group

### ISSUE THREAD

**Issue by Kabor42** [ansible-collections/community.general#7500]
### Summary

I need to set up some WiFi hotspot with nmcli and set:
- pairwise: ccmp
- group: ccmp
- proto: rsn
because of some connection issues regarding some device.

Playing this tasks resolves in the following errors for each parameter:

```
TASK [setup_network : Create WiFi Hotspot] ***********************************************************************
fatal: [device1]: FAILED! => changed=false
  msg: |-
    Error: failed to modify 802-11-wireless-security.pairwise: 'm' not among [tkip, ********].
  name: Hothspot
  rc: 2
```
```
fatal: [device1]: FAILED! => changed=false
  msg: |-
    Error: failed to modify 802-11-wireless-security.group: 'm' not among [wep40, wep104, tkip, ********].
  name: Hothspot
  rc: 2
```
```
fatal: [device1]: FAILED! => changed=false
  msg: |-
    Error: failed to modify 802-11-wireless-security.proto: 's' not among [wpa, ********].
  name: Hothspot
  rc: 2
```

Without these parameters the **nmcli** module works fine.

Setting these parameters from the command line with `nmcli edit c hotspot` works.

### Issue Type

Bug Report

### Component Name

nmcli

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/domi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/domi/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.11.5 (main, Aug 31 2023, 07:57:41) [GCC] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.0  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
PAGER(env: PAGER) = less
```

### OS / Environment

openSUSE Tumbleweed 20231103, x86_64 6.5.4-1-default
both host and target systems run the same OS

### Steps to Reproduce

```yaml (paste below)
- name: Create WiFi Hotspot
  become: true
  hosts: devices
  tasks:
  - name: Hotspot test
    community.general.nmcli:
      conn_name: hotspot
      type: wifi
      ssid: test_hotspot
      wifi:
        mode: ap
        band: bg
      wifi_sec:
        key-mgmt: wpa-psk
        psk: "test_pass"
        pairwise: "ccmp"
        group: "ccmp"
        proto: "rsn"
      autoconnect: true
      ip4:
        - 192.168.1.1/24
      method4: shared
      method6: link-local
      gw4: 192.168.1.1
      state: present
      ifname: "wlo1"
```
Save this to **test_hotspot.yaml**

`ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook -i hosts test_hotspot.yaml -vvv`

### Expected Results

On the [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html#parameter-wifi_sec) it stays that these parameter with the provided values are supported.
I was expecting this to work.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
