### ISSUE TITLE
sudoers add items in append mode

### ISSUE THREAD

**Issue by r1200gsdave** [ansible-collections/community.general#7532]
### Summary

I am using the sudoers module in a loop for multiple groups to be added into a file.  The module loops through the items fine but the last item is all that is in the file when the step is done.

Perhaps I am looping wrong.  I have added a variable to the name and then I get a seperate file for each item and it works fine.  I would just like it better if all of the groups would be in the same file.

### Issue Type

Feature Idea

### Component Name

sudoers

### Additional Information

```yaml (paste below)
---
- hosts: dev
  gather_facts: yes
  vars:
    dev_groups:
      - 'GroupOne'
      - 'GroupTwo'
      - 'GroupThree'
   tasks:  
    - name: update sudoers dev
      community.general.sudoers:
        name: "dev-groups-as-root-{{ item }}"
        state: present
        group: "{{ item }}"
        runas: root
        commands: ALL
      loop: "{{ dev_groups }}"



```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
