### ISSUE TITLE
docker_compose creates mariadb container without a root password

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.general#758]
_From @smacz42 on Apr 09, 2020 05:24_

##### SUMMARY

When using `docker_compose` module building `mariadb:10.4`, the database password is not set. However, executing docker-compose from the CLI creates a container that sets the database password.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`docker_compose`

##### ANSIBLE VERSION

```paste below
2.8.10
```

##### CONFIGURATION

```paste below
rundeck@6b596c382ca1:~/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481$ ansible-config dump --only-changed
Using /home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg as config file
ANSIBLE_SSH_ARGS(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANY_ERRORS_FATAL(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = True
DEFAULT_GATHERING(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = 30
DEFAULT_REMOTE_USER(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = ['/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/roles']
DEFAULT_STDOUT_CALLBACK(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = debug
DEFAULT_VAULT_IDENTITY_LIST(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = ['./environment/.vault_pass', 'plays@./.vault_pass']
DEFAULT_VERBOSITY(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = 1
HOST_KEY_CHECKING(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/ansible.cfg) = /home/rundeck/186b489c-2073-4d31-a0e8-b5a7da2a1cc2-481/.retry_files

```

##### OS / ENVIRONMENT

Source OS: Ubuntu 16.04 LTS
Source Python: Python 3.6.10

Target OS: Ubuntu 18.04 LTS
Target Python: Python 3.6.9
Target Docker: Docker version 19.03.8, build afacb8b7f0
Target Docker Compose: docker-compose version 1.25.4, build unknown

#### `requirements.yml`
```yaml 
---
- src: nickjj.docker
  name: docker
```
#### `environment/group_vars/compositional/all.yml`
```yaml
compositional_database_root_password: "{{ vault_compositional_database_root_password }}
```

#### `ansible-vault view environment/group_vars/compositional/vault.yml`
```yaml
vault_compositional_database_root_password: quEfaBHnAFmad7Fs
```

#### `create_db.yml`
```yaml
- name: Install Dependencies
  hosts: all
  become: yes
  vars:
    docker__pip_packages:
      - "docker"
      - "python-apt"

  pre_tasks:
    - name: Update APT
      command: apt update -y

  roles:
    - role: docker

- name: Create Mariadb Database
  hosts: all
  become: yes
  vars_files:
    - ../environment/group_vars/all/all.yml

  tasks:
    - set_fact:
        ansible_python_interpreter: "/usr/bin/env python-docker"

    - name: (mariadb) The latest mariadb service is build and present
      docker_compose:
        project_name: mariadb
        definition:
          version: '3.6'
          services:
              mariadb:
                  image: "mariadb:10.4"
                  container_name: database_test
                  restart: always
                  environment:
                      MYSQL_ROOT_PASSWORD: "{{ compositional_database_root_password }}"
        build: yes
        state: present
        restarted: yes
```

## ANSIBLE RUN

```
$ ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -i environment/hosts.yml playbooks/create_db.yml
[...]
    "services": {                                          
        "mariadb": {                                       
            "database_test": {
[...]
ok=19   changed=15   unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
```

##### EXPECTED RESULTS

I should not be able to log into the container without a root password.

##### ACTUAL RESULTS

I am able to log in to the container without a root password:

```paste below
$ docker exec -it database mysql -uroot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.4.12-MariaDB-1:10.4.12+maria~bionic mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> Bye
```

# DEBUGGING

## RUNNING MODULE ON TARGET

```
Module expanded into:
/root/.ansible/tmp/ansible-tmp-1586408747.1439543-108068564744345/debug_dir
root@host:~/.ansible/tmp/ansible-tmp-1586408747.1439543-108068564744345# cd debug_dir/
```
#### Change the code to prevent the docker-compose file from being deleted:
```python
        if self.definition:
            compose_file = os.path.join(self.project_src, "docker-compose.yml")
            print(compose_file)
            #self.log("removing %s" % compose_file)
            #os.remove(compose_file)
            #self.log("removing %s" % self.project_src)
            #os.rmdir(self.project_src)
```
#### Delete the docker container created in the ansible run
```
docker stop database_test && docker rm database_test
database_test
database_test
```

#### Run the code which saves the docker-compose file for us
```
# /usr/bin/env python-docker __main__.py args
/tmp/ansibletonakh46/docker-compose.yml

{"changed": true, "ansible_facts": {"mariadb": {"database_test": {"cmd": ["mysqld"], "labels": {"com.docker.compose.config-hash": "ec3a0785e200a620240f3187ae4e59aa41be61f40047781b02034ab9efebfaca", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "mariadb", "com.docker.compose.project.config_files": "/tmp/ansibletonakh46/docker-compose.yml", "com.docker.compose.project.working_dir": "/tmp/ansibletonakh46", "com.docker.compose.service": "mariadb", "com.docker.compose.version": "1.25.4"}, "image": "mariadb:10.4", "state": {"running": true, "status": "running"}, "networks": {"mariadb_default": {"aliases": ["0b8543b0f889", "mariadb"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "IPAddress": "172.18.0.2", "IPPrefixLen": 16, "links": null, "macAddress": "02:42:ac:12:00:02"}}}}}, "services": {"mariadb": {"database_test": {"cmd": ["mysqld"], "labels": {"com.docker.compose.config-hash": "ec3a0785e200a620240f3187ae4e59aa41be61f40047781b02034ab9efebfaca", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "mariadb", "com.docker.compose.project.config_files": "/tmp/ansibletonakh46/docker-compose.yml", "com.docker.compose.project.working_dir": "/tmp/ansibletonakh46", "com.docker.compose.service": "mariadb", "com.docker.compose.version": "1.25.4"}, "image": "mariadb:10.4", "state": {"running": true, "status": "running"}, "networks": {"mariadb_default": {"aliases": ["0b8543b0f889", "mariadb"], "globalIPv6": "", "globalIPv6PrefixLen": 0, "IPAddress": "172.18.0.2", "IPPrefixLen": 16, "links": null, "macAddress": "02:42:ac:12:00:02"}}}}}, "invocation": {"module_args": {"project_name": "mariadb", "definition": {"version": "3.6", "services": {"mariadb": {"image": "mariadb:10.4", "container_name": "database_test", "restart": "always", "environment": {"MYSQL_ROOT_PASSWORD": "quEfaBHnAFmad7Fs"}}}}, "build": true, "state": "present", "restarted": true, "docker_host": "unix://var/run/docker.sock", "tls_hostname": "localhost", "api_version": "auto", "timeout": 10, "tls": false, "validate_certs": false, "debug": false, "hostname_check": false, "recreate": "smart", "remove_volumes": false, "remove_orphans": false, "stopped": false, "dependencies": true, "pull": false, "nocache": false, "ca_cert": null, "client_cert": null, "client_key": null, "ssl_version": null, "project_src": null, "files": null, "remove_images": null, "scale": null, "services": null}}}
```

#### Test login without password - successful
```
docker exec -it database_test mysql -uroot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.4.12-MariaDB-1:10.4.12+maria~bionic mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```

# Here's where docker-compose works on the command line

#### Go to directory with docker-compose file and remove running container

```
cd /tmp/ansibletonakh46 && docker stop database_test && docker rm database_test
database_test
database_test
```

#### Start the container using docker-compose from the CLI
```
docker-compose -f docker-compose.yml up -d
```

#### Try to log in without the root password

```
docker exec -it database_test mysql -uroot
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

# SUMMARY

The same docker-compose file that ansible creates works if invoked from the CLI, but not from Ansible's `docker_compose` module's code.

_Copied from original issue: ansible/ansible#68803_
