### ISSUE TITLE
Add validate_certs parameter to community.general.jabber module

### ISSUE THREAD

**Issue by juanvalino** [ansible-collections/community.general#7585]
### Summary

Currently is not possible to disable certificates validation in `community.general.jabber`.

So, we propose to add `validate_certs` parameter name module in a similar way than other modules.

### Issue Type

Feature Idea

### Component Name

community.general.jabber

### Additional Information

```yaml
- name: Send a message to a user
  community.general.jabber:
    user: mybot@example.net
    password: secret
    to: friend@example.net
    msg: Ansible task finished
    validate_certs: false
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
