### ISSUE TITLE
add hookscript parameter to proxmox_kvm

### ISSUE THREAD

**Issue by elelay** [ansible-collections/community.general#7600]
### Summary

I would like to add the config `hookscript` parameter which is not exposed via the proxmox_kvm module.

### Issue Type

Feature Idea

### Component Name

proxmox_kvm

### Additional Information

```yaml (paste below)
- name: Create new VM with minimal options and hookscript
  community.general.proxmox_kvm:
    # existing params
    api_user: root@pam
    api_password: secret
    api_host: helldorado
    name: spynal
    node: sabrewulf
    # this param is new:
    hookscript: local:snippets/myhook.py
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
