### ISSUE TITLE
Updating network interface method ignores specified address family

### ISSUE THREAD

**Issue by tiesjan** [ansible-collections/community.general#7610]
### Summary

I am trying to update the _method_ of a network interface in `/etc/network/interfaces` while specifying `address_family`, using the `community.general.interfaces_file` module.

It seems that the interfaces are not properly filtered by address family in doing so. As a result, all entries of that interface have their _method_ updated.

### Issue Type

Bug Report

### Component Name

interfaces_file

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/user/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/user/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.0.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CALLBACKS_ENABLED(env: ANSIBLE_CALLBACKS_ENABLED) = ['profile_tasks']
CONFIG_FILE() = None
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/user/.vault-personal
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

### OS / Environment

Both host and target OS is Debian 12.

### Steps to Reproduce

```yaml (paste below)
---

- name: Configure IPv6 interface
  community.general.interfaces_file:
    iface: "{{ ansible_default_ipv4.alias }}"
    address_family: "inet6"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - option: "method"
      value: "static"
    - option: "address"
      value: "{{ static_ipv6_address }}/48"
  loop_control:
    label: "{{ item.option }}"
```

### Expected Results

Given the following entries for an interface:

```
iface ens3 inet dhcp
iface ens3 inet6 auto
```

I expect the playbook above to update them to:

```
iface ens3 inet dhcp
iface ens3 inet6 static
    address fd00:1234:5678:1::1/48
```

### Actual Results

Instead, it's updated to the following result:

```
iface ens3 inet static
iface ens3 inet6 static
    address fd00:1234:5678:1::1/48
```

The `inet` entry also has its _method_ updated to `static`, whereas it should stay `dhcp`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
