### ISSUE TITLE
pipx does not install anything

### ISSUE THREAD

**Issue by oregonpillow** [ansible-collections/community.general#7640]
### Summary

When using community.general.pipx to install python packages, the TASK always reports "ok" even when the correct state is NOT achieved

### Issue Type

Bug Report

### Component Name

pipx

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/home/debian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/debian/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/debian/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/debian/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/debian/.local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Debian 11

### Steps to Reproduce

```yaml (paste below)
- name: Basic system setup
  hosts: home
  become: true
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        cache_valid_time: 3600
        pkg: "{{ apt_packages }}"
    - name: Install pipx
      become: false
      ansible.builtin.pip:
        name: pipx
        virtualenv: "/home/debian/python3.11"
        virtualenv_command: python3 -m venv
    - name: Add pipx to PATH
      ansible.builtin.lineinfile:
        path: /home/debian/.bashrc
        line: 'export PATH="$PATH:/home/debian/.local/bin"'
    - name: Add venv to PATH
      ansible.builtin.lineinfile:
        path: /home/debian/.bashrc
        line: 'export PATH="$PATH:/home/debian/python3.11/bin"'
    - name: Install yt-dlp
      community.general.pipx:
        name: yt-dlp
        executable: "/home/debian/python3.11/bin/pipx"
        state: latest
    - name: Install ansible-lint
      community.general.pipx:
        name: ansible-lint
        executable: "/home/debian/python3.11/bin/pipx"
        state: latest
```

### Expected Results

the pipx packages, in this case yt-dlp and ansible-lint should be installed. 

### Actual Results

```console (paste below)

PLAY [Basic system setup] ******************************************************************

TASK [Gathering Facts] *********************************************************************
ok: [debian@192.168.0.28]

TASK [Install apt packages] ****************************************************************
ok: [debian@192.168.0.28]

TASK [Install pipx] ************************************************************************
ok: [debian@192.168.0.28]

TASK [Add pipx to PATH] ********************************************************************
ok: [debian@192.168.0.28]

TASK [Add venv to PATH] ********************************************************************
ok: [debian@192.168.0.28]

TASK [Install yt-dlp] **********************************************************************
ok: [debian@192.168.0.28]

TASK [Install ansible-lint] ****************************************************************
ok: [debian@192.168.0.28]

PLAY RECAP *********************************************************************************
debian@192.168.0.28        : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

But the packages are definitely NOT installed and can be confirmed on host after running playbook:

```
$ pipx list
nothing has been installed with pipx 😴
```

Remember how i explicitly chose the pipx executable in the playbook (/home/debian/python3.11/bin/pipx) ? Well I can confirm that it works no problem if i use it manually:

```
$ /home/debian/python3.11/bin/pipx install yt-dlp
  installed package yt-dlp 2023.11.16, installed using Python 3.11.2
  These apps are now globally available
    - yt-dlp
done! ✨ 🌟 ✨

```
which proves that the pipx executable is working fine and that the problem looks like it must be related to the role?

Thanks for any advice! Great work @russoz !

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/pipx.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/pipx.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @russoz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by oregonpillow** [comment]
Found the problem, i was executing the tasks as root.

```yml
    - name: Install yt-dlp
      become: false                                                <----- fixes issue
      community.general.pipx:
        name: yt-dlp
        executable: "/home/debian/python3.11/bin/pipx"
        state: latest
    - name: Install ansible-lint
      become: false                                                <----- fixes issue
      community.general.pipx:
        name: ansible-lint
        executable: "/home/debian/python3.11/bin/pipx"
        state: latest

```
