### ISSUE TITLE
keycloak_user: Subgroups not working

### ISSUE THREAD

**Issue by monsdar** [ansible-collections/community.general#7650]
### Summary

Adding a user to a subgroup isn't working. Top-level groups work fine. This seems to be related to [get_groups](https://github.com/ansible-collections/community.general/blob/e3a3950e3db9d3954490218bf68f6a98259b81fc/plugins/module_utils/identity/keycloak/keycloak.py#L1393) only returning the top-level groups and therefore [update_user_groups_membership](https://github.com/ansible-collections/community.general/blob/e3a3950e3db9d3954490218bf68f6a98259b81fc/plugins/module_utils/identity/keycloak/keycloak.py#L2885) thinking that the group to join does not exist.

Looking at the Keycloak API it seems that there is no [easy way](https://www.keycloak.org/docs-api/21.0.0/rest-api/index.html#_groups_resource) to query for the groups including subgroups. Even in the Keycloak UI when joining a user to a group it first only shows the top-level groups and you need to search for the explicit subgroup-name to have it listed as joinable groups.

### Issue Type

Bug Report

### Component Name

keycloak_user

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.16.0]
  config file = None
  [...]
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

Collection        Version
----------------- -------
community.general 8.0.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

CONFIG_FILE() = None
```

### OS / Environment

Ubuntu 22.04 LTS

### Steps to Reproduce

```yaml (paste below)
- name: Create user
  community.general.keycloak_user:
    auth_keycloak_url: REDACTED
    auth_realm: master
    auth_username: admin
    auth_password: REDACTED
    realm: REDACTED
    username: foo
    firstName: foo
    lastName: foo
    email: foo@bar.com
    enabled: true
    emailVerified: true
    credentials:
        - type: password
          value: REDACTED
          temporary: false
    groups:
        - name: NAME_OF_SUBGROUP
          state: present
    state: present
```

### Expected Results

User is joined or removed from the given subgroup (depending on `state: present` or `state: absent`)

### Actual Results

User is NOT joined or removed from the desired subgroup (depending on `state: present` or `state: absent`)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
