### ISSUE TITLE
pipx: add native list support

### ISSUE THREAD

**Issue by oregonpillow** [ansible-collections/community.general#7666]
### Summary

Currently, if you want to specify multiple pipx packages, you need to do something like this:

```yml
# vars.yml
pipx_packages:
  - package1
  - package2
  - package3
```
```yml
# playbook.yml
- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pipx_packages }}"
```

would be more user friendly if we `name` would accept a list as well. What do you think?

### Issue Type

Feature Idea

### Component Name

pipx

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
