### ISSUE TITLE
Proxmox: add module to retrieve node status / usage information

### ISSUE THREAD

**Issue by jwbernin** [ansible-collections/community.general#7686]
### Summary

I am developing a playbook to provision VMs to a Proxmox cluster, and I would like to be able to deploy each enw VM to the "least loaded" node of the cluster. This module will let me retrieve current load information - specifically CPU and memory usage - which I can then sort on to select the "least loaded" node.

### Issue Type

Feature Idea

### Component Name

proxmox_node_info

### Additional Information

```yaml (paste below)
- name: List existing nodes
  community.general.proxmox_node_info:
    api_host: proxmox1
    api_user: root@pam
    api_password: "{{ password | default(omit) }}"
    api_token_id: "{{ token_id | default(omit) }}"
    api_token_secret: "{{ token_secret | default(omit) }}"
  register: proxmox_nodes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
