### ISSUE TITLE
gitlab_runner can't handle more than 20 runners

### ISSUE THREAD

**Issue by hazzeh** [ansible-collections/community.general#7690]
### Summary

This looks like regression of https://github.com/ansible/ansible/issues/57759

When register runners on a system with more than 20 runners an existing runner will not be updated, but a new will be registered. 

It looks like other gitlab modules were updated with https://github.com/ansible-collections/community.general/pull/4491

By updating the find_runner(self, description) function from
``` runners = self._runners_endpoint(as_list=False)```
to
``` runners = self._runners_endpoint(as_list=False, all=True)```
it solves my problem.
   

### Issue Type

Bug Report

### Component Name

gitlab_runner

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.1]
  config file = None
  configured module search path = ['/<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /<redacted>/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /<redacted>/.ansible/collections:/usr/share/ansible/collections
  executable location = /<redacted>/venv/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 13.2.0] (/<redacted>/venv/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /<redacted>/venv/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less
```

### OS / Environment

Ubuntu 20.04.6 LTS

### Steps to Reproduce

1. Create a project in gitlab.com.
2. Do not allow shared runners
3. Create a personal access token with api and create_runner scopes.
4. Run the following play twice.

```yaml (paste below)
- hosts: localhost
  tasks:
   - community.general.gitlab_runner:
       api_url: https://gitlab.com/
       api_token: <api-token>
       description: "runner-{{ item }}"
       state: present
       project: <your project id>
     loop: "{{ range(0, 21) }}"
```

### Expected Results

The second run should be idempotent. 

### Actual Results

The first 20 runners is working as expected, the 21th is newly registered causing duplicate runners in gitlab.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
