### ISSUE TITLE
xml: unexpectedly does html encoding on value

### ISSUE THREAD

**Issue by pemontto** [ansible-collections/community.general#770]
##### SUMMARY
Taken from https://github.com/ansible/ansible/issues/58316
XML module converts characters to their HTML representation. In my case it converted & to &amp; despite & actually opening a encoded sequence (in my specific case is &#x5c; for example).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = None
  configured module search path = ['/Users/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/x/.pyenv/versions/3.7.6/lib/python3.7/site-packages/ansible
  executable location = /Users/x/.pyenv/versions/3.7.6/bin/ansible
  python version = 3.7.6 (default, Jan 21 2020, 14:27:10) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7/8

##### STEPS TO REPRODUCE

```bash
$ echo '<test>my value</test>' > test.xml
$ ansible localhost -m xml -a 'path=test.xml xpath=/test value=&quot;'
localhost | CHANGED => {
    "actions": {
        "namespaces": {},
        "state": "present",
        "xpath": "/test"
    },
    "changed": true
}
$ cat test.xml
<?xml version='1.0' encoding='UTF-8'?>
<test>&amp;quot;</test>
$ ansible localhost -m xml -a 'path=test.xml xpath=/test value="& \& \\& \\\&"'
localhost | CHANGED => {
    "actions": {
        "namespaces": {},
        "state": "present",
        "xpath": "/test"
    },
    "changed": true
}
$ cat test.xml
<?xml version='1.0' encoding='UTF-8'?>
<test>&amp; \&amp; \&amp; \\&amp;</test>
```

Example task

```yaml
- name: configure server.xml
  xml:
    path: "/path/to/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "relaxedPathChars", value: "[]|" }
    - { name: "relaxedQueryChars", value: "[]|{}^&#x5c;&#x60;&quot;&lt;&gt;" }
```

##### EXPECTED RESULTS

```xml
<Connector relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"/>
```

##### ACTUAL RESULTS

```xml
<Connector relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&amp;#x5c;&amp;#x60;&amp;quot;&amp;lt;&amp;gt;"/>
```
