### ISSUE TITLE
ini_file support for nested sections

### ISSUE THREAD

**Issue by mbrancato** [ansible-collections/community.general#771]
##### SUMMARY

Add support in `ini_file` to allow it to create or modify nested sections

An example of nested sections is:
```ini
[plugins]
  [plugins.cgroups]
    no_prometheus = false
```
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`ini_file`

##### ADDITIONAL INFORMATION

```yaml
- name: Set cgroup driver
  ini_file:
    path: /etc/containerd/config.toml
    section: plugins/plugins.cri
    option: systemd_cgroup
    value: 'true'
```
