### ISSUE TITLE
Getting TSIG update error (PeerBadKey) when running Bind9 role

### ISSUE THREAD

**Issue by bobul** [ansible-collections/community.general#7713]
### Summary

I am getting this kind of error `fatal: [bobul-2]: FAILED! => {"changed": false, "msg": "TSIG update error (PeerBadKey): The peer didn't know the key we used"}` when I am trying to create A record in the Bind9 zone using nsupdate module. I am sure that key is specified in the **named.conf.local** and **named.conf.options** because I am changing configuration there using template module. 

```yaml
- name: Set backup A record
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    server: "bobul-2"
    zone: "{{ startup_domain }}"
    record: backup
    value: "{{ backup_ip }}"
  when: inventory_hostname in groups['dns_masters']
  ``` 
 My task which is responsible for creating A record.
  
 I have no idea why this error throws, because my configs are OK. 

### Issue Type

Bug Report

### Component Name

community.general.nsupdate

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.11]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/pns/ansible-venv/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.8.3  

# /home/pns/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_BECOME(/home/pns/ica0002/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/pns/ica0002/ansible.cfg) = ['/home/pns/ica0002/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/pns/ica0002/ansible.cfg) = /home/pns/.ansible/vault_password
HOST_KEY_CHECKING(/home/pns/ica0002/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/pns/ica0002/ansible.cfg) = False

ssh:
___
host_key_checking(/home/pns/ica0002/ansible.cfg) = False
```

### OS / Environment

Ubuntu

### Steps to Reproduce

```yaml (paste below)
- name: Change bind9 configuration
  ansible.builtin.template:
    dest: /etc/bind/named.conf.{{ item }}
    src: named.conf.{{ item }}.j2
  loop:
    - options
    - local
  notify: Restart bind9

- name: Configure master zone
  ansible.builtin.template:
    dest: /var/cache/bind/db.{{ startup_domain }}
    src: zone.j2
    force: no
  notify: Rndc reload
  when: inventory_hostname in groups['dns_masters']

- name: Configure ptr zone
  ansible.builtin.template:
    dest: /var/cache/bind/db.rev
    src: zone.rev.j2
    force: no
  notify: Rndc reload
  when: inventory_hostname in groups['dns_masters']

- name: Set backup A record
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key_secret }}"
    server: "bobul-2"
    zone: "{{ startup_domain }}"
    record: backup
    value: "{{ backup_ip }}"
  when: inventory_hostname in groups['dns_masters']
```

### Expected Results

I am expecting that module will create A record in my managed host.

### Actual Results

```console (paste below)
TASK [bind : Change bind9 configuration] ***************************************
ok: [bobul-2] => (item=options)
ok: [bobul-1] => (item=options)
ok: [bobul-2] => (item=local)
ok: [bobul-1] => (item=local)

TASK [bind : Configure master zone] ********************************************
skipping: [bobul-1]
ok: [bobul-2]

TASK [bind : Configure ptr zone] ***********************************************
skipping: [bobul-1]
ok: [bobul-2]

TASK [bind : Set backup A record] **********************************************
skipping: [bobul-1]
fatal: [bobul-2]: FAILED! => {"changed": false, "msg": "TSIG update error (PeerBadKey): The peer didn't know the key we used"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
