### ISSUE TITLE
Add module to list content of proxmox storage

### ISSUE THREAD

**Issue by l00ptr** [ansible-collections/community.general#7724]
### Summary

It could be nice to have a module to list content (by type) from proxmox storage. I would like to use that kind of feature to automate backup restoration. I can imagine that:

- launch a task to retrieve backups dedicated to a vmid on a specific storage
- calculate the newest backup (some json parsing on my role)
- launch a task to restore that backup

### Issue Type

Feature Idea

### Component Name

proxmox

### Additional Information

```yaml (paste below)
- name: List existing backup stored on specific storage
  register: backups_for_vmid_123
  community.general.proxmox_storage_list:
    api_host: helldorado
    api_user: root@pam
    api_password: "{{ password | default(omit) }}"
    api_token_id: "{{ token_id | default(omit) }}"
    api_token_secret: "{{ token_secret | default(omit) }}"
    storage:  backup_store
    vmid: 123
    content: backup
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
