### ISSUE TITLE
ilo_redfish_config SetNTPServers "key error"

### ISSUE THREAD

**Issue by rich549** [ansible-collections/community.general#7753]
### Summary

Using the ilo_redfish_config module to configure NTP servers for an HP ILO.  I've followed the example in ilo_redfish_config.py, (my code is below) and this returns "KeyError: 'nic_addr'".

Yaml:
  - name: ILO Set NTP Servers
    community.general.ilo_redfish_config:
      category: Manager
      command: SetNTPServers
      baseuri: x.x.x.x
      username: admin
      password: password
      attribute_name: StaticNTPServers
      attribute_value: x.x.x.x

Error:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'nic_addr'.

### Issue Type

Bug Report

### Component Name

ilo_redfish_config

### Ansible Version

```
ansible [core 2.15.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/raspley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/raspley/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```
Collection        Version
----------------- -------
community.general 8.1.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.2

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Host: Ubuntu 22.04.3
Targer: HP ILO 5 (Firmware 2.91)

### Steps to Reproduce

```yaml (paste below)
  - name: ILO Set NTP Servers
    community.general.ilo_redfish_config:
      category: Manager
      command: SetNTPServers
      baseuri: x.x.x.x
      username: admin
      password: password
      attribute_name: StaticNTPServers
      attribute_value: x.x.x.x
```

### Expected Results

Expected the NTP server addresses to be updated on the ILO, with the following result in Ansible.

changed: [hostname.domain] => {"changed": true, "ilo_redfish_config": {"SetNTPServers": {"changed": true, "msg": "Modified NTP Servers", "ret": true}}}

### Actual Results

```console (paste below)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'nic_addr'
fatal: [hostname.domain]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1703079319.0017676-2081-94938643574458/AnsiballZ_ilo_redfish_config.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1703079319.0017676-2081-94938643574458/AnsiballZ_ilo_redfish_config.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1703079319.0017676-2081-94938643574458/AnsiballZ_ilo_redfish_config.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.ilo_redfish_config', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.ilo_redfish_config', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.general.ilo_redfish_config_payload_jhgtfn4y/ansible_community.general.ilo_redfish_config_payload.zip/ansible_collections/community/general/plugins/modules/ilo_redfish_config.py\", line 194, in <module>\n  File \"/tmp/ansible_community.general.ilo_redfish_config_payload_jhgtfn4y/ansible_community.general.ilo_redfish_config_payload.zip/ansible_collections/community/general/plugins/modules/ilo_redfish_config.py\", line 186, in main\n  File \"/tmp/ansible_community.general.ilo_redfish_config_payload_jhgtfn4y/ansible_community.general.ilo_redfish_config_payload.zip/ansible_collections/community/general/plugins/module_utils/ilo_redfish_utils.py\", line 60, in set_ntp_server\nKeyError: 'nic_addr'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
/

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/ilo_redfish_config.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ilo_redfish_config.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bhavya06 @jyundt @mraineri @rajeevkallur @renxulei @tomasg2012 @xmadsen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by a-dawg** [comment]
same error here. SetDNSserver command throws the same keyerror as well. I am using ilo firmware v1.55 or v1.53
https://github.com/HewlettPackard/ilo-ansible-collection/blob/d95e13f4735d39d2acef2573fab9025776ab6347/roles/setdns/tasks/main.yml

**Comment by a-dawg** [comment]
@rich549 try this first before setting your ntp servers, this has worked for me:
```
 - name: Disable DHCP overrides for nic settings
    community.general.redfish_config:
      <<: *ilo_creds
      baseuri:  "{{ baseuri }}"
      category: Manager
      command: SetManagerNic
      nic_config:
        DHCPv4:
          UseNTPServers: false
        DHCPv6:
          UseNTPServers: false
````
