### ISSUE TITLE
Cloudflare no longer support SPF records (They must be TXT records)

### ISSUE THREAD

**Issue by gderber** [ansible-collections/community.general#7758]
### Summary

cloudflare_dns module fails to create 'SPF' records.  Looking at cloudflare's site, and their DNS management, they no longer supports 'SPF' record type for DNS entries.  They must be 'TXT' records.

I did try to make a quick patch: https://github.com/ansible-collections/community.general/compare/main...gderber:community.general:bugfix/cloudflare_spf

My editor messed up the formatting, which is why I am not submitting it.  That's in addition to the tests that I need to learn how to run.

### Issue Type

Bug Report

### Component Name

cloudflare_dns

### Ansible Version

```
ansible [core 2.16.2]
  python version = 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```
community.general 8.1.0 
```

Also checked against 8.2.0

### Steps to Reproduce

```
- name: "Add or modify SPF records."
  community.general.cloudflare_dns:
    api_token: "dummyapitoken"
    zone: "example.com"
    type: "{{ item }}"
    state: "present"
    solo: true
    value: "v=spf1 mx -all"
  become: false
  loop: "{{ __spf_record_type }}"
  vars:
    __spf_record_type:
      - "SPF"
      - "TXT"
```

### Expected Results

changed: [inventory_hostname] => (item=TXT)

### Actual Results

failed: [inventory_hostname] (item=SPF) => {"ansible_loop_var": "item", "changed": false, "item": "SPF", "msg": "API bad request; Status: 400; Method: POST: Call: /zones/06b0857ee2d54423ff516ccb8802ab91/dns_records"}

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
