### ISSUE TITLE
Quoted values are falsly identified as boolean #60044

### ISSUE THREAD

**Issue by mowgli** [ansible-collections/community.general#779]
This is the copy of the bug #60044 in ansible/ansible (https://github.com/ansible/ansible/issues/60044) due to closing bugs without solving them.

##### SUMMARY
Quoted 'True' or 'False' are falsly identified as booleans.

With the new policy of nagging about that, that becomes to verbose.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ini_file

##### ANSIBLE VERSION
```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 11 2019, 10:43:21) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = su
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed file
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
linux

##### STEPS TO REPRODUCE
```yaml
- name: Setting ansible variables
  ini_file:
    dest: /etc/ansible/ansible.cfg
    section: "{{ item.section|default('defaults') }}"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: gathering, value: smart}
    - {section: privilege_escalation, name: become_method, value: su}
    - {section: ssh_connection, name: pipelining, value: 'True'}
    - {name: retry_files_enabled, value: 'False'}
    - {name: ansible_managed, value: 'Ansible managed file'}
```

##### EXPECTED RESULTS
Nothing

##### ACTUAL RESULTS
```paste below
ansible-ini_file: [WARNING] The value True (type bool) in a string field was converted to u'True' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
ansible-ini_file: [WARNING] The value False (type bool) in a string field was converted to u'False' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```
