### ISSUE TITLE
Regression on maven_artifact from 8.x "Could not find imported module support code"

### ISSUE THREAD

**Issue by Netherwhal** [ansible-collections/community.general#7796]
### Summary

On Version `8.1.0` I get the following error:

```
Could not find imported module support code for ansible_collections.community.general.plugins.modules.maven_artifact.  Looked for (['ansible.module_utils.compat.version.LooseVersion', 'ansible.module_utils.compat.version'])
```

When using the following task:

```yaml
- name: Fetch jolokia agent
  community.general.maven_artifact:
    group_id: org.jolokia
    artifact_id: jolokia-jvm
    version: "{{ mcs_jolokia_version }}"
    dest: /opt/jolokia/jolokia-jvm-{{ mcs_jolokia_version }}.jar
    mode: '0644'
  become: true
```

When downgrading to `7.5.1` it works.

### Issue Type

Bug Report

### Component Name

maven_artifact

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/circleci/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
8.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

-

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
