### ISSUE TITLE
Cannot reach lxc AND vm via ansible_host composing

### ISSUE THREAD

**Issue by Denyreal** [ansible-collections/community.general#7816]
### Summary

Hi folks.

i got this problem.

When i try to run a playbook on vm using proxm inventory plugin the ansible_host compose can't reach vm AND lxc at the same time but only alternatively.

here is my command : 

```bash
ansible-playbook -i plugins/inventory/server1.proxmox.yml playbooks/debug_proxmox_inventory.yml
```

all vault are correctly setup. 

It's a problem with compose ansible_host option which cannot compose vm AND lxc  . 

I can reach lxc with this one : 

```yaml
  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')
```

I can reach vm with this 

```yaml
  ansible_host : ansible_host: proxmox_agent_interfaces | selectattr('name', 'in', 'eth0,ens18') | map(attribute='ip-addresses') | flatten | first | ipaddr('address')
```

it's similar to this problem : 

https://forum.ansible.com/t/proxmox-dynamic-inventory-pull-ip-address-for-vm-lxc/1857

If someone can give me a hint it would be great. 

Thank you very much ;)

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
$ ansible --version
2.16.2
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/spin0/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.2.0  

# /usr/lib/python3.12/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.1.0  

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.0.2 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_NOCOLOR(/home/spin0/ansible/ansible.cfg) = False                                                                                                                                      
ANSIBLE_NOCOWS(/home/spin0/ansible/ansible.cfg) = True                                                                                                                                        
COLOR_CHANGED(/home/spin0/ansible/ansible.cfg) = yellow                                                                                                                                       
COLOR_DEBUG(/home/spin0/ansible/ansible.cfg) = dark gray                                                                                                                                      
COLOR_DEPRECATE(/home/spin0/ansible/ansible.cfg) = purple                                                                                                                                     
COLOR_DIFF_ADD(/home/spin0/ansible/ansible.cfg) = green                                                                                                                                       
COLOR_DIFF_LINES(/home/spin0/ansible/ansible.cfg) = cyan                                                                                                                                      
COLOR_DIFF_REMOVE(/home/spin0/ansible/ansible.cfg) = red                                                                                                                                      
COLOR_ERROR(/home/spin0/ansible/ansible.cfg) = red                                                                                                                                            
COLOR_HIGHLIGHT(/home/spin0/ansible/ansible.cfg) = white                                                                                                                                      
COLOR_OK(/home/spin0/ansible/ansible.cfg) = green                                                                                                                                             
COLOR_SKIP(/home/spin0/ansible/ansible.cfg) = cyan                                                                                                                                            
COLOR_UNREACHABLE(/home/spin0/ansible/ansible.cfg) = red
COLOR_VERBOSE(/home/spin0/ansible/ansible.cfg) = blue
COLOR_WARN(/home/spin0/ansible/ansible.cfg) = bright purple
CONFIG_FILE() = /home/spin0/ansible/ansible.cfg 
DEFAULT_HOST_LIST(/home/spin0/ansible/ansible.cfg) = ['/home/spin0/ansible/hosts']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/spin0/ansible/ansible.cfg) = ['/home/spin0/ansible/plugins/inventory']
DEFAULT_LOCAL_TMP(/home/spin0/ansible/ansible.cfg) = /home/spin0/.ansible/tmp/ansible-local-222066zvng_ag
DEFAULT_LOG_PATH(/home/spin0/ansible/ansible.cfg) = /tmp/ansible.log
DEFAULT_MODULE_PATH(/home/spin0/ansible/ansible.cfg) = ['/home/spin0/ansible/collections']
DEFAULT_NO_TARGET_SYSLOG(/home/spin0/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/spin0/ansible/ansible.cfg) = ['/home/spin0/ansible/roles']
DEFAULT_TIMEOUT(/home/spin0/ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/home/spin0/ansible/ansible.cfg) = /home/spin0/ansible/vault_password
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/home/spin0/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/spin0/ansible/ansible.cfg) = python3.11
INVENTORY_ENABLED(/home/spin0/ansible/ansible.cfg) = ['yaml', 'constructed', 'ini', 'community.general.proxmox']
```

### OS / Environment

ansible controller fedora 39
targeted host : proxmox 8.1.3

### Steps to Reproduce

```yaml (paste below)
# More complete example demonstrating the use of 'want_facts' and the constructed options
# Note that using facts returned by 'want_facts' in constructed options requires 'want_facts=true'
# my.proxmox.yml
plugin: community.general.proxmox
url: https://192.168.10.30:8006
user: 6admin@pve
token_id: Administrator
# generated via echo -n 'YOURSUPERTOKEN' | ansible-vault encrypt_string
# the password has to be the same as your vault for more convenience
token_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          BLABLA

validate_certs: false
want_facts: true
exclude_nodes: true
groups:
  preprod_vm: "'preprod' in (proxmox_tags_parsed|list) and hostvars[inventory_hostname].proxmox_type|default('') == 'qemu'"
  preprod_ct: "'preprod' in (proxmox_tags_parsed|list) and hostvars[inventory_hostname].proxmox_type|default('') == 'lxc'"
  prod_vm: "'prod' in (proxmox_tags_parsed|list) and hostvars[inventory_hostname].proxmox_type|default('') == 'qemu'"
  prod_ct: " prod' in (proxmox_tags_parsed|list) and hostvars[inventory_hostname].proxmox_type|default('') == 'lxc'"
  lab_vm: "'lab' in (proxmox_tags_parsed|list) and hostvars[inventory_hostname].proxmox_type|default('') == 'qemu'"
  lab_ct: "'lab' in (proxmox_tags_parsed|list) and hostvars[inventory_hostname].proxmox_type|default('') == 'lxc'"
  # Repeat similar lines for other groups

want_proxmox_nodes_ansible_host: true
# Create hostvars
compose:
  ansible_port: 22
  ansible_user: "'ansible'"
  ansible_ssh_private_key_file: "'~/.ssh/mars.lab'"
  ansible_become_method: "'sudo'"
  ansible_become_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    BLABLA

  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')
...
```

### Expected Results

i expected plugin to access all lxc and vm . i can access lxc (pgsql) but not vm (medialife) 

### Actual Results

```console (paste below)
ok: [pgsql]
fatal: [medialife]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname medialife: Name or service not known", "unreachable": true}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* `plugins/modules/proxmox`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @UnderGreen @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Denyreal** [comment]
it solves the issue : 

https://github.com/ansible-collections/community.general/issues/4854

**Comment by felixfontein** [comment]
!component =plugins/inventory/proxmox.py

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/inventory/proxmox.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/inventory/proxmox.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @ilijamt
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by TrendMend** [comment]
> it solves the issue :
> 
> #4854

Could you follow up on what you mean? which comment resolved the issue?

**Comment by ansibullbot** [comment]
cc @krauthosting
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ATunderSP** [comment]
I think its problem of guidelines on the web. Not a single example i copy-pasted from the web worked for me. Official example from [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_inventory.html) can to be parsed because it stores the mask too.

```yaml
ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')
```

I have constructed my own pattern that works for IPv4, but not IPv6 yet. In my use case i had machines with a lot of network interfaces. And it was not always index 0, that was required for ansible_host. So i had to select network interfaces by name. Following works for (some) nodes and all my LXC and qemu.

```yaml
compose:
  # TODO Make IPv6 working.
  ansible_host: "ansible_host | default ( (proxmox_agent_interfaces | default({}) | selectattr('name', 'in', ['eth0', 'Ethernet']) | first)['ip-addresses'] | default([]) | map('upper') | select('regex', '([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+|[0-9A-F]+::[0-9A-F]+:[0-9A-F]+:[0-9A-F]+:[0-9A-F]+)/[0-9]+') | first | default(proxmox_net0.ip) | default('') | regex_replace('^(.+)/(.+)$', '\\1') )"
```

***Note that you have to customize network interface `name` for your use-case.***

I belive the correct solution is to fix and improve documentation of this plugin.
