### ISSUE TITLE
proxmox_kvm - Unable to import Ubuntu cloud image in .img format.

### ISSUE THREAD

**Issue by BladeWDR** [ansible-collections/community.general#7820]
### Summary

The proxmox_kvm module doesn't appear to work with the cloud images provided by Ubuntu. The same play works with a qcow2 file provided by Debian,

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
ansible [core 2.15.1]
  config file = /home/scott/git/doting_calamity/ansible.cfg
  configured module search path = ['/home/scott/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/scott/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/scott/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/scott/ansible/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/scott/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
# /home/scott/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.2.0

# /home/scott/ansible/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.1.0
```

### Configuration

```console (paste below)
CONFIG_FILE() = /home/scott/git/doting_calamity/ansible.cfg
DEFAULT_HOST_LIST(/home/scott/git/doting_calamity/ansible.cfg) = ['/home/scott/git/doting_calamity/hosts']
DEFAULT_PRIVATE_KEY_FILE(/home/scott/git/doting_calamity/ansible.cfg) = /home/scott/.ssh/ansible
DEFAULT_REMOTE_USER(/home/scott/git/doting_calamity/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/scott/git/doting_calamity/ansible.cfg) = ['/home/scott/git/doting_calamity/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/scott/git/doting_calamity/ansible.cfg) = /home/scott/git/doting_calamity/vaultpass
HOST_KEY_CHECKING(/home/scott/git/doting_calamity/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/scott/git/doting_calamity/ansible.cfg) = False
```

### OS / Environment

Proxmox 8.1.3

### Steps to Reproduce

The proxmox_kvm module doesn't appear to work with the cloud images provided by Ubuntu. The same play works with a qcow2 file provided by Debian, but if you use any of the .img files provided [here](https://cloud-images.ubuntu.com/jammy/current/) it gives this error:

`"msg": "creation of qemu VM testvm with vmid 133 failed with exception=500 Internal Server Error: unable to parse volume filename 'jammy-server-cloudimg-amd64-disk-kvm.img'", "vmid": 133}`

Here is the play in question:

```
- name: "Create the VMs on Proxmox node 1."
  community.general.proxmox_kvm:
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    api_host: '{{ gv_proxmox_api_host }}'
    node: '{{ item.node }}'
    name: '{{ item.name }}'
    vmid: '{{ item.vmid }}'
    vga: serial0
    net: '{"net0":"virtio,bridge={{ gv_proxmox_linux_bridge }},firewall=1"}'
    serial: '{"serial0":"socket"}'
    scsihw: virtio-scsi-single
    scsi:
      scsi0: '{{ item.drive_storage }}:0,import-from={{ gv_proxmox_image_storage }}:0/{{ item.image_file }},format={{ item.drive_format }},iothread=1'
    ide:
      ide2: '{{ item.drive_storage }}:cloudinit'
    ostype: 'l26'
    onboot: 'no'
    cpu: 'host'
    cores: '{{ item.cores }}'
    sockets: 1
    memory: '{{ item.memory }}'
    balloon: 0
    boot: order=scsi0
    ipconfig:
      ipconfig0: 'ip=dhcp'
    cicustom: 'user={{ gv_proxmox_snippets_storage }}:snippets/{{ item.vmid }}-user.yml'
    agent: 'enabled=1'
    timeout: 700
  loop: '{{ computers }}'
  when: 'item.state == "new"'
```

I have tried hard coding the variables for scsi0 just to make sure it wasn't an issue with how the variables were being interpreted, but had the same issue.

I'm not sure if this is an issue with the collection or something internal to proxmoxer.

### Expected Results

I expected the volume to be imported like the qcow2 is.

Running `qm import VMID` with the same image file works.

### Actual Results

```console (paste below)
The full traceback is:
  File "/tmp/ansible_community.general.proxmox_kvm_payload_lh72o60x/ansible_community.general.proxmox_kvm_payload.zip/ansible_collections/community/general/plugins/modules/proxmox_kvm.py", line 1432, in main
  File "/tmp/ansible_community.general.proxmox_kvm_payload_lh72o60x/ansible_community.general.proxmox_kvm_payload.zip/ansible_collections/community/general/plugins/modules/proxmox_kvm.py", line 1132, in create_vm
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 135, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 126, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 105, in _request
    raise ResourceException(
failed: [sb-proxmox.bladewdr.xyz] (item={'name': 'testvm', 'vmid': '133', 'node': 'SB-PROXMOX', 'image_file': 'jammy-server-cloudimg-amd64-disk-kvm.img', 'cpu_type': 'x86-64-v2-AES', 'cores': 2, 'drive_storage': 'fast', 'drive_format': 'raw', 'disk_size': '32GB', 'memory': 2048, 'ipv4mode': 'static', 'ipv4_address': '10.13.37.222/24', 'ipv4_gateway': '10.13.37.1', 'state': 'new'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "acpi": null,
            "agent": "enabled=1",
            "api_host": "sb-proxmox.bladewdr.xyz",
            "api_password": null,
            "api_token_id": "terraform",
            "api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "terraform@pam",
            "archive": null,
            "args": null,
            "autostart": null,
            "balloon": 0,
            "bios": null,
            "boot": "order=scsi0",
            "bootdisk": null,
            "cicustom": "user=local:snippets/133-user.yml",
            "cipassword": null,
            "citype": null,
            "ciuser": null,
            "clone": null,
            "cores": 2,
            "cpu": "host",
            "cpulimit": null,
            "cpuunits": null,
            "delete": null,
            "description": null,
            "digest": null,
            "efidisk0": null,
            "force": null,
            "format": null,
            "freeze": null,
            "full": true,
            "hookscript": null,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": {
                "ide2": "fast:cloudinit"
            },
            "ipconfig": {
                "ipconfig0": "ip=dhcp"
            },
            "keyboard": null,
            "kvm": null,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 2048,
            "migrate": false,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "testvm",
            "net": {
                "net0": "virtio,bridge=vmbr0,firewall=1"
            },
            "newid": null,
            "node": "SB-PROXMOX",
            "numa": null,
            "numa_enabled": null,
            "onboot": false,
            "ostype": "l26",
            "parallel": null,
            "pool": null,
            "protection": null,
            "proxmox_default_behavior": "no_defaults",
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": {
                "scsi0": "fast:0,import-from=local:0/jammy-server-cloudimg-amd64-disk-kvm.img,format=raw,iothread=1"
            },
            "scsihw": "virtio-scsi-single",
            "serial": {
                "serial0": "socket"
            },
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "sshkeys": null,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": null,
            "tablet": null,
            "tags": null,
            "target": null,
            "tdf": null,
            "template": null,
            "timeout": 700,
            "tpmstate0": null,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "serial0",
            "virtio": null,
            "vmid": 133,
            "watchdog": null
        }
    },
    "item": {
        "cores": 2,
        "cpu_type": "x86-64-v2-AES",
        "disk_size": "32GB",
        "drive_format": "raw",
        "drive_storage": "fast",
        "image_file": "jammy-server-cloudimg-amd64-disk-kvm.img",
        "ipv4_address": "10.13.37.222/24",
        "ipv4_gateway": "10.13.37.1",
        "ipv4mode": "static",
        "memory": 2048,
        "name": "testvm",
        "node": "SB-PROXMOX",
        "state": "new",
        "vmid": "133"
    },
    "msg": "creation of qemu VM testvm with vmid 133 failed with exception=500 Internal Server Error: unable to parse volume filename 'jammy-server-cloudimg-amd64-disk-kvm.img'",
    "vmid": 133
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/proxmox_kvm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @UnderGreen @helldorado @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sudo-battlekafer** [comment]
I also am encountering the same issue with Ubuntu 22.04 
(img: https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img)  

[Source code](https://github.com/sudo-battlekafer/ansible-pve-automation)

**Comment by wwonka92** [comment]
Also having this error message when trying to import an alpine image of type .vhd from /var/lib/vz/images/0/

my playbook :
`
---
- name: Création de la VM LocalDNS
  hosts: proxmox
  become: true

  tasks:
    - name: Personnalisation de l'image
      copy:
        src: 'local_dns_os_setup.yml'
        dest: '/var/lib/vz/snippets/201-user.yml'
        owner: root
        group: root
        mode: 0644
    - name: Création de la VM
      proxmox_kvm:
        # Proxmox API
        api_host: 192.168.1.254
        api_user: ansible@pam
        api_token_id: ansible-token
        api_token_secret: my-secret
        # Id
        node: homelab
        vmid: 201
        name: LocalDNS
        # Boot
        onboot: true
        startup: 'order=2'
        boot: 'order=scsi0'
        # Specification
        ostype: l26
        memory: 1024
        cores: 2
        cicustom: 'user=local:snippets/201-user.yml'
        # Network
        net:
          net0: 'virtio,bridge=vmbr0,firewall=0'
        ipconfig:
          ipconfig0: 'ip=192.168.1.2/24,gw=192.168.1.1'
        # IO
        vga: serial0
        serial:
          serial0: socket
        scsihw: virtio-scsi-single
        scsi:
          scsi0: 'local-zfs:4,import-from=local:0/alpine-3.19.1.vhd'
        ide:
          ide2: 'local-zfs:cloudinit'
        agent: 'enabled=1'`

**Comment by wwonka92** [comment]
Quick workaround is to go with direct CLI in proxmox instead of trying to use the proxmox_kvm module. With proxmox CLI, absolute path is possible.

Simply remove the 'scsi0' part and add 2 new tasks for 1. import the image as a vm disk  and 2. resize the disk to fit your needs.

Hence this playbook:
```
---
- name: Déploiement de la VM LocalDNS
  hosts: proxmox
  become: true

  tasks:
    - name: Création du dossier de téléchargement des images
      file:
        path: '/var/lib/vz/images/0'
        state: directory
    - name: Téléchargement de l'image cloud-init Alpine 3.19.1 x86_64
      get_url:
        url: 'https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/cloud/aws_alpine-3.19.1-x86_64-bios-cloudinit-r0.vhd'
        dest: '/var/lib/vz/images/0/alpine-3.19.1.vhd'
    - name: Personnalisation de l'image
      copy:
        src: user.yml
        dest: '/var/lib/vz/snippets/201-user.yml'
        owner: root
        group: root
        mode: 0644
    - name: Création de la VM
      proxmox_kvm:
        # Proxmox API
        api_host: 192.168.1.254
        api_user: ansible@pam
        api_token_id: '{{ proxmox_api_token_id }}'
        api_token_secret: '{{ proxmox_api_token_secret }}'
        # Id
        node: homelab
        vmid: 201
        name: LocalDNS
        # Boot
        onboot: true
        startup: 'order=2'
        boot: 'order=scsi0'
        # Specification
        ostype: l26
        memory: 1024
        cores: 2
        cicustom: 'user=local:snippets/201-user.yml'
        # Network
        net:
          net0: 'virtio,bridge=vmbr0,firewall=0'
        ipconfig:
          ipconfig0: 'ip=192.168.1.2/24,gw=192.168.1.1'
        # IO
        vga: serial0
        serial:
          serial0: socket
        scsihw: virtio-scsi-single
        # scsi:
        #   scsi0: 'local-zfs:4,import-from=local:0/alpine-3.19.1.vhd' BUG: NOT WORKING!
        ide:
          ide2: 'local-zfs:cloudinit'
        agent: 'enabled=1'
    - name: Import de l'image et création du disque de la VM
      command:
        cmd: 'qm set 201 --scsi0 local-zfs:0,import-from=/var/lib/vz/images/0/alpine-3.19.1.vhd'
    - name: Redimensionnement du disque de la VM
      command:
        cmd: 'qm resize 201 scsi0 4G'
```

**Comment by ansibullbot** [comment]
cc @krauthosting
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by nameless66** [comment]
Had the same problem with ubuntu.img - Solution is to rename the file to ubuntu.qcow2

Download Definition:
````
- name: ubuntu-24.04-minimal-cloudimg-amd64
  cloud_init_file: ubuntu-24.04-minimal-cloudimg-amd64.qcow2 #Use .qcow2 as extension (not img), otherwise create vms doesnt work
  image_url: 'https://cloud-images.ubuntu.com/minimal/releases/noble/release/ubuntu-24.04-minimal-cloudimg-amd64.img'
  image_checksum: sha256:d4ff5b1a8ab829a5ffc8580e16a047d7a7fc73455d528d7e76f20ffcfb51f7d3
  state: present
````

Ansible Download Task - Attention on dest - cloud_init_file - it makes the rename
````
- name: Download cloud-init images
  get_url:
    url: '{{item.image_url}}'
    dest: '{{image_path}}{{item.cloud_init_file}}'
    checksum: '{{item.image_checksum}}'
  loop: '{{os_images}}'
  when: 'item.state == "present"'
````
