### ISSUE TITLE
Enable action_groups so that module_defaults can be used

### ISSUE THREAD

**Issue by randompherret** [ansible-collections/community.general#7844]
### Summary

I am trying to use module_defaults in my playbook to keep things DRY. adding action_groups specifically for the proxmox group of the modules would certainly help. I am willing to write a PR if it would be accepted.

### Issue Type

Feature Idea

### Component Name

proxmox module, proxmox_disk module, proxmox_domain_info module, proxmox_group_info module, proxmox_kvm module, proxmox_nic module, proxmox_pool module, proxmox_pool_member module, proxmox_snap module, proxmox_storage_info module, proxmox_tasks_info module, proxmox_template module, proxmox_user_info module, proxmox_vm_info module

### Additional Information

Example of a play without groups being set:
```
- name: Checks guests
  hosts: guests
  gather_facts: no
  module_defaults:
    community.general.proxmox_disk:
      api_user: "{{ vault_proxmoxUser }}"
      api_token_id: "{{ vault_proxmoxTokenId }}"
      api_token_secret: "{{ vault_proxmoxToken }}"
      api_host: "{{ vault_proxmoxHost }}"
    community.general.proxmox_kvm:
      api_user: "{{ vault_proxmoxUser }}"
      api_token_id: "{{ vault_proxmoxTokenId }}"
      api_token_secret: "{{ vault_proxmoxToken }}"
      api_host: "{{ vault_proxmoxHost }}"
  roles:
    - guests
  ```
How it would look after:
```
- name: Checks guests
  hosts: guests
  gather_facts: no
  module_defaults:
    group/community.general.proxmox:
      api_user: "{{ vault_proxmoxUser }}"
      api_token_id: "{{ vault_proxmoxTokenId }}"
      api_token_secret: "{{ vault_proxmoxToken }}"
      api_host: "{{ vault_proxmoxHost }}"
  roles:
    - guests
  `````

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
