### ISSUE TITLE
gitlab_issue: title attribute not used when listing

### ISSUE THREAD

**Issue by gpongelli** [ansible-collections/community.general#7846]
### Summary

Using gitlab_issue module, `title` string is required but it's not used by underlying library python_gitlab's list method.

More specifically, [this call into gitlab_issue module](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/gitlab_issue.py#L186) passes a keyword "title" to python-gitlab library, that [does not use it for "list" method](https://github.com/python-gitlab/python-gitlab/blob/72e1aa7f2c2aad739db2f5dd4394165a5b5f2432/gitlab/v4/objects/issues.py#L54).

What happens is that many issues are returned, filtering only through the state (that's an admitted filter), ignoring the title.

### Issue Type

Bug Report

### Component Name

gitlab_issue

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.cache/pypoetry/virtualenvs/gitlab-user-checks-bxct1Kz8-py3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.cache/pypoetry/virtualenvs/gitlab-user-checks-bxct1Kz8-py3.11/bin/ansible
  python version = 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] (/root/.cache/pypoetry/virtualenvs/gitlab-user-checks-bxct1Kz8-py3.11/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general


# /root/.cache/pypoetry/virtualenvs/gitlab-user-checks-bxct1Kz8-py3.11/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

debian trixie

### Steps to Reproduce

```yaml (paste below)
  - name: Change assignee
    community.general.gitlab_issue:
      api_url: "{{ api_url }}"
      api_token: "{{ access_token }}"
      project: "existing-project"
      title: "title copied from gitlab issue page"
      assignee_ids:
        - assignee
      state: present
```

### Expected Results

`title` parameter used to filter gitlab's issue, or another way to obtain only one issue to be then changed.

task above should be executed changing the issue's assignee, searched through title, with specified one.

### Actual Results

```console (paste below)
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Multiple Issues matched search criteria."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### Solution
"search" is the keyword to be used, instead of "title".
