### ISSUE TITLE
make module archive in zstd

### ISSUE THREAD

**Issue by MozeBaltyk** [ansible-collections/community.general#7849]
### Summary

```
  ansible.builtin.command:
    "tar -I zstd -vcf {{ tar_zst_name }} -C {{ directory_package }} ."
  args:
    chdir: "{{ directory_package }}/.."
```

Which generate an error with ansible-lint ... 

### Issue Type

Feature Idea

### Component Name

community.general.archive

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
