### ISSUE TITLE
keycloak_realm_key module creates key, but fails to create proper relation to realm

### ISSUE THREAD

**Issue by Ernstsen** [ansible-collections/community.general#7850]
### Summary

When creating a keyProvider using ``community.general.keycloak_realm_key`` it is created with a wrong relation in KeyCloak.
While many realm-lookups (including ones made in the process of this call) requires the realm-name and _not_ the GUID to be used, the ``parent_id`` field provided on component-creation needs the GUID and not the realm-name.
Passing the realm-name creates a strange relation, where it does exist, but is not usable from the realm, thus not allowing for the provided key to be used in SAML

### Issue Type

Bug Report

### Component Name

keycloak_realm_key

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.1]
  config file = /src/system/keycloak/ansible/ansible.cfg
  configured module search path = ['/home/jsje/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jsje/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/jsje/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jsje/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/username/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.2.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/src/system/keycloak/ansible/ansible.cfg) = True
CONFIG_FILE() = /src/system/keycloak/ansible/ansible.cfg
DEFAULT_HOST_LIST(/src/system/keycloak/ansible/ansible.cfg) = ['/src/system/keycloak/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/src/system/keycloak/ansible/ansible.cfg) = ['/src/system/keycloak/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/src/system/keycloak/ansible/ansible.cfg) = /home/username/.ansible-pass
HOST_KEY_CHECKING(/src/system/keycloak/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu in WSL2 for Windows 

### Steps to Reproduce

```yaml (paste below)
---
- name: Manage Keycloak Instance
  hosts: localhost
  vars_files:
    - ./certificate.yml
  tasks:
    - name: Manage Keycloak realm key and certificate
      community.general.keycloak_realm_key:
        name: custom
        state: present
        parent_id: {{ realm_name }}
        provider_id: rsa-enc
        auth_keycloak_url: {{ keycloak_url }}
        auth_username: admin
        auth_password: {{ keycloak_password }}
        auth_realm: master
        force: true
        config:
          private_key: "{{ private_key }}"
          certificate: "{{ certificate }}"
          enabled: true
          active: true
          priority: 120
          algorithm: RSA-OAEP
```

### Expected Results

I expect that when i open the realm associated with ``{{ realm_guid }}`` then i'll see the newly created keyProvider in the GUI

### Actual Results

The playbook prints:
```json
{"changed": true, "end_state": {"config": {"active": ["true"], "algorithm": ["RSA-OAEP"], "enabled": ["true"], "priority": ["120"]}, "id": "b7f4788d-fc6e-4209-8ae2-ad3264a30d08", "name": "custom", "parentId": "test-realm", "providerId": "rsa-enc", "providerType": "org.keycloak.keys.KeyProvider"}, "msg": "Realm key custom was forcibly updated"}
```

But when i go to the overview of 'test-realm' i do not see the key.
However, when i URL-hack:
``{{ keycloak_url}}/admin/master/console/#/test-realm/realm-settings/keys/providers/b7f4788d-fc6e-4209-8ae2-ad3264a30d08/rsa-enc/settings``
I am able to see the key.

However it is not used to create a key for the realm.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
