### ISSUE TITLE
community.zabbix.zabbix_maintenance cannot get it to fire from localhost

### ISSUE THREAD

**Issue by RobinGoussey** [ansible-collections/community.general#7869]
### Summary

I was trying to migrate the collection from:
https://docs.ansible.com/ansible/2.9/modules/zabbix_maintenance_module.html
to
https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_maintenance_module.html

We I feel like there is a lack of documentation on where to run this from. We used to have a task that we delegated to localhost, to then go to zabbix to create the maintenance, as the servers don't have access to the zabbix http api.

But when I try to migrate, I get variable unknown issues:

```yaml
- hosts: all
  tasks:
    - name: Create or delete a named maintenance window
      vars:
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: true
        ansible_host: "{{ zabbix_url}}"
        ansible_user: "{{ zabbix_maintenance_username }}"
        ansible_httpapi_pass: "{{ secret_zabbix_maintenance_password }}"
     delegate_to: localhost
     connection: local
     run_once: true
     community.zabbix.zabbix_maintenance:
        name: "{{ customer }} {{ customer_environment }} {{ product_name }} - automated deploy and maintenance"
        desc: |
            This maintenance has been created by ansible, while auto deploying.
            Host running ansible: {{ ansible_hostname }}
            Ip: {{ ansible_default_ipv4['address'] }}
            Username: {{ ansible_user_id }}
        host_names: "{{ hostvars['prod_machine']['ansible_hostname'] }}"
        state: "{{ zabbix_state }}"
        minutes: 90
        collect_data: true
```

Could you extend the documentation, on where the task should run?
Is it something that is meant to run on the server itself, or is it possible in some way to delegate to localhost?

Variables like zabbix_maintenance_username aren't found if I delegate to localhost. Maybe I'm lacking in ansible knowledge, but I can't get this to work.

### Issue Type

Documentation Report

### Component Name

zabbix_maintenance

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/home/rgoussey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rgoussey/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rgoussey/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rgoussey/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.2.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = True
CALLBACKS_ENABLED(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = ['profile_tasks']
COLLECTIONS_PATHS(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = ['/home/rgoussey/projects/the_project/ansible/ansible_collections']
CONFIG_FILE() = /home/rgoussey/projects/the_project/ansible/ansible.cfg
DEFAULT_JINJA2_NATIVE(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = /home/rgoussey/projects/the_project/ansible/.run_logs/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = yaml
DEFAULT_TRANSPORT(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = paramiko
DEFAULT_VAULT_IDENTITY_LIST(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = ['the-project@~/.ansible/vault/the-project']
HOST_KEY_CHECKING(/home/rgoussey/projects/the_project/ansible/ansible.cfg) = False
PAGER(env: PAGER) = less

```

### OS / Environment

Ubuntu 22

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
