### ISSUE TITLE
redfish_command: Add redfish_info command to get service identification

### ISSUE THREAD

**Issue by stegosaur** [ansible-collections/community.general#7882]
### Summary

We would like to add support to get the service identification from a manager resource

### Issue Type

Feature Idea

### Component Name

redfish_command

### Additional Information

example playbook:

```yaml (paste below)
- name: get svc id
  become: false
  community.general.redfish_info:
    category: Manager
    command: GetServiceIdentification
    baseuri: "{{ address }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    manager: "{{ manager}}" #this is only required if more than one service identification is found across multiple managers
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
