### ISSUE TITLE
Add support for ini files without section headers

### ISSUE THREAD

**Issue by chriscroome** [ansible-collections/community.general#7889]
### Summary

The new [from_ini](https://docs.ansible.com/ansible/devel/collections/community/general/from_ini_filter.html) filter only supports INI files with section headers, could supporting input without headers be considered?

### Issue Type

Feature Idea

### Component Name

from_ini

### Additional Information

```yaml (paste below)

- name: Slurp /etc/default/grub
  ansible.builtin.slurp:
    src: /etc/default/grub
  register: grub_defaults_b64encoded

- name: Set a fact for the existing grub defaults
  ansible.builtin.set_fact:
    grub_existing_defaults: "{{ grub_defaults_b64encoded['content'] | ansible.builtin.b64decode | community.general.from_ini }}"

- name: Debug the existing grub defaults
  ansible.builtin.debug:
    var: grub_existing_defaults
```

The above fails with:

```
TASK [grub : Set a fact for the existing grub defaults] *******************************************************************************
fatal: [workspace.webarch.org.uk]: FAILED! => 
  msg: |-
    from_ini failed to parse given string: File contains no section headers.
    file: '<???>', line: 6
    'GRUB_DEFAULT=0\n'. File contains no section headers.
    file: '<???>', line: 6
    'GRUB_DEFAULT=0\n'
```

However if `community.general.from_ini` is replaced with `community.general.jc('ini')` you get:

```
TASK [grub : Debug the existing grub defaults] ****************************************************************************************
ok: [workspace.webarch.org.uk] => 
  grub_existing_defaults:
    GRUB_CMDLINE_LINUX: ''
    GRUB_CMDLINE_LINUX_DEFAULT: vsyscall=emulate
    GRUB_DEFAULT: '0'
    GRUB_DISTRIBUTOR: '`lsb_release -i -s 2> /dev/null || echo Debian`'
    GRUB_TIMEOUT: '5'
```

The [jc issue](https://github.com/kellyjonbrazil/jc/issues/344) has some background regardig the two ini filters that now `jc` has.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
