### ISSUE TITLE
community.general.ldap_entry not creating entries on Ansible > 6.x

### ISSUE THREAD

**Issue by madrover** [ansible-collections/community.general#7894]
### Summary

We are in process of migrating our roles from Ansible 6.x to 8.x and we have noticed that the `community.general.ldap_entry` task doesn't create entries on a task that has been working unmodified since ancient Ansible 2.x (at least).

The task on Ansible <= 6.x appears as changed and actually applies the requested changes but on > 6.x does not do any change nor fails.

This is working well on ansible-6.7.0, ansible-core-2.13.1, community.general 5.8.3 but not on higher versions such as:

- ansible-7.7.0 ansible-core-2.14.13, community.general 6.6.2
- ansible-8.7.0 ansible-core-2.15.8, community.general 7.5.2
- ansible-9.1.0 ansible-core-2.16.2, community.general 8.1.0

### Issue Type

Bug Report

### Component Name

ldap_entry

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.8]
  config file = /Users/miquela/.ansible.cfg
  configured module search path = ['/Users/miquela/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/miquela/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = False
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /opt/homebrew/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

CONFIG_FILE() = /Users/miquela/.ansible.cfg
DEFAULT_STDOUT_CALLBACK(/Users/miquela/.ansible.cfg) = yaml
PAGER(env: PAGER) = less
```

### OS / Environment

target OS: Centos 7.0

### Steps to Reproduce

```
- name: Initialize database configuration
  community.general.ldap_entry:
    state: present
    server_uri: "{{ openldap_server_configuration_uri }}"
    dn: olcDatabase=hdb,cn=config
    objectClass:
      - olcDatabaseConfig
      - olcHdbConfig
    attributes:
      olcDatabase: "{1}hdb"
      olcSuffix: "{{ openldap_server_suffix }}"
      olcDbDirectory: "{{ openldap_server_dbdirectory }}"
      olcRootDN: "{{ openldap_server_rootdn }}"
      olcRootPW: "{{ openldap_server_rootpw_hashed.stdout }}"
      olcDbConfig:
        - set_cachesize 0 2097152 0
        - set_lk_max_objects 1500
        - set_lk_max_locks 1500
        - set_lk_max_lockers 1500
      olcDbIndex: objectClass eq
      olcLastMod: "TRUE"
      olcDbCheckpoint: 512 30
      olcAccess:
        - to attrs=userPassword by dn="{{ openldap_server_rootdn }}" write by anonymous auth by self write by * none
        - to attrs=shadowLastChange by self write by * read
        - to dn.base="" by * read
        - to * by dn="{{ openldap_server_rootdn }}" write by * read
  register: task_result

- name: View task_result
  ansible.builtin.debug:
    var: task_result

- name: Add domain and top objectClass for {{ openldap_server_suffix }}
  community.general.ldap_entry:
    dn: "{{ openldap_server_suffix }}"
    bind_dn: "{{ openldap_server_rootdn }}"
    bind_pw: "{{ openldap_server_rootpw }}"
    objectClass:
      - domain
      - top
    attributes:
      dc: "{{ openldap_server_sub_domain }}"

```

### Expected Results

Tasks output:

```
TASK [ansible-openldap : Initialize database configuration] ********************
jueves 25 enero 2024  16:36:23 +0100 (0:00:00.181)       0:01:12.492 **********
changed: [openldap-centos7]

TASK [ansible-openldap : View task_result] *************************************
jueves 25 enero 2024  16:36:24 +0100 (0:00:00.268)       0:01:12.760 **********
ok: [openldap-centos7] =>
  task_result:
    changed: true
    failed: false

TASK [ansible-openldap : Add domain and top objectClass for dc=example,dc=com] ***
jueves 25 enero 2024  16:36:24 +0100 (0:00:00.022)       0:01:12.783 **********
changed: [openldap-centos7]
```

Files created in the filesystem:

```
$ ls -l /var/lib/ldap/dc=example,dc=com
total 740
-rw-r--r-- 1 ldap ldap       96 Jan 25 15:36 DB_CONFIG
-rw------- 1 ldap ldap   614400 Jan 25 15:36 __db.001
-rw------- 1 ldap ldap   163840 Jan 25 15:36 __db.002
-rw------- 1 ldap ldap   114104 Jan 25 15:36 __db.003
-rw-r--r-- 1 ldap ldap     2048 Jan 25 15:36 alock
-rw------- 1 ldap ldap     8192 Jan 25 15:36 dn2id.bdb
-rw------- 1 ldap ldap    32768 Jan 25 15:36 id2entry.bdb
-rw------- 1 ldap ldap 10485760 Jan 25 15:36 log.0000000001
-rw------- 1 ldap ldap     8192 Jan 25 15:36 objectClass.bdb
```

### Actual Results

Tasks output:

```
TASK [ansible-openldap : Initialize database configuration] ********************
jueves 25 enero 2024  16:40:29 +0100 (0:00:00.170)       0:01:17.585 **********
ok: [openldap-centos7]

TASK [ansible-openldap : View task_result] *************************************
jueves 25 enero 2024  16:40:29 +0100 (0:00:00.243)       0:01:17.828 **********
ok: [openldap-centos7] =>
  task_result:
    changed: false
    failed: false

TASK [ansible-openldap : Add domain and top objectClass for dc=example,dc=com] ***
jueves 25 enero 2024  16:40:29 +0100 (0:00:00.022)       0:01:17.851 **********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
fatal: [openldap-centos7]: FAILED! => changed=false
  details: '{''desc'': ''Invalid credentials''}'
  msg: Cannot bind to the server.

```

Files created in the filesystem:

```
$ ls -l /var/lib/ldap/dc=example,dc=com
total 740
total 0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
