### ISSUE TITLE
redfish_config: Add redfish_config command to set service identification

### ISSUE THREAD

**Issue by stegosaur** [ansible-collections/community.general#7916]
### Summary

We would like to add support to set the service identification for a manager resource

### Issue Type

Feature Idea

### Component Name

redfish_config

### Additional Information

example playbook:
```yaml (paste below)
  - name: set svc id
    community.general.redfish_config:
      category: Manager
      command: SetServiceIdentification 
      service_id: "{{ service_id }}"
      baseuri: "{{ base_uri }}"
      resource_id: "{{ manager }}"
      username: "{{ user }}"
      password: "{{ pass }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
