### ISSUE TITLE
community.general.onepassword: bug with field name casing

### ISSUE THREAD

**Issue by Hvitgar** [ansible-collections/community.general#7918]
### Summary

When using the onepassword lookup plugin with `op` cli v2 on a field that contains uppercase letters while also specifying a section name, the lookup always fails. I think the problem originates here:

https://github.com/ansible-collections/community.general/blob/82e74e35d96e589677c213c71a1b1a8270e3b253/plugins/lookup/onepassword.py#L468

the field name from the lookup query is transformed to lower case

https://github.com/ansible-collections/community.general/blob/82e74e35d96e589677c213c71a1b1a8270e3b253/plugins/lookup/onepassword.py#L490-L496

but compared against the untransformed label from the json data.

### Issue Type

Bug Report

### Component Name

onepassword

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.5]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 8.2.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
---
- name: op bug
  hosts: localhost
  gather_facts: false
  tasks:
    - name: debug
      ansible.builtin.debug:
        var: ip
      vars:
        ip: "{{ lookup('community.general.onepassword',
          'Test',
          field='IP',
          section='server',
          vault=vault_name) }}"
```

### Expected Results

Assuming that there is an entry 'Test' in the vault that has a section 'server' and a field 'IP' with value `192.168.1.1`, the result should be `192.168.1.1`

### Actual Results

```console (paste below)
TASK [debug] ***********************************************************************************************************************************************************************************
ok: [localhost] =>
  ip: ''
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
