### ISSUE TITLE
community.general.gandi_livedns using wrong authentication

### ISSUE THREAD

**Issue by mthynell** [ansible-collections/community.general#7926]
### Summary

Gandi API_KEY authentication is deprecated and not accepted anymore. Gandi API is using Personal Access Token (PAT).
Gandi API authorization header is changed. 

Quick fix was to change Apikey to Bearer on gandi.livedns_api.py line 53: 
`headers = {'Authorization': 'Bearer {0}'.format(self.api_key),`

### Issue Type

Bug Report

### Component Name

gandi_livedns_api.py

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.13.13]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.3.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

vcode devcontainer 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    gandi_pat: "{{ lookup('env', 'GANDI_API_KEY') }}"

  tasks:
  - name: Create an example record 
    community.general.gandi_livedns:
      domain: example.com
      record: test221
      type: A
      values:
      - 127.0.0.1
      ttl: 3600
      api_key: "{{ gandi_pat  }}"
      state: present
```

### Expected Results

```
TASK [Create an example record to example.com] ****************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

### Actual Results

```console (paste below)
PLAY [localhost] *********************************************************************************************************************************************************************************

TASK [Create an example record to example.com] ****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "API Error : "}

PLAY RECAP ***************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
