### ISSUE TITLE
Puppet Facts not  working 

### ISSUE THREAD

**Issue by skhan28** [ansible-collections/community.general#7932]
### Summary

I was trying to mention facts in puppet modle and passing it with dict variable but seems like it is not able to work with dict 

- hosts: all
  gather_facts: false
  vars:
    facts_new:
      "FACTER_deployment_state": "running"

  tasks:
    - name: Run puppet agent on puppet 7 node
      become: yes
      block:
        - name: Run puppet agent
          ansible.builtin.puppet:
            debug: yes
            verbose: yes
            summarize: yes
            facts: "{{ facts_new }}"
 Error:  File \"/tmp/ansible_ansible.builtin.puppet_payload_x2g77c2j/ansible_ansible.builtin.puppet_payload.zip/ansible_collections/community/general/plugins/modules/puppet.py\", line 185, in _write_structured_data\r\nTypeError: write() argument must be str, not bytes\r\n",

### Issue Type

Bug Report

### Component Name

puppet

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.8]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.5.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
- hosts: all
  gather_facts: false
  vars:
    facts_new:
      "FACTER_deployment_state": "running"

  tasks:
    - name: Run puppet agent on puppet 7 node
      become: yes
      block:
        - name: Run puppet agent
          ansible.builtin.puppet:
            debug: yes
            verbose: yes
            summarize: yes
            facts: "{{ facts_new }}"
```

### Expected Results

puppet agent run

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
