### ISSUE TITLE
Cloning a template returns source vm not found

### ISSUE THREAD

**Issue by traxeon** [ansible-collections/community.general#7939]
### Summary

When using the clone function of the ansible playbook, the playbook returns a result of:
"Container to be cloned does not exist"

### Issue Type

Bug Report

### Component Name

proxmox
https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.15.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/disco/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/disco/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

Collection        Version
----------------- -------
community.general 8.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

CONFIG_FILE() = /etc/ansible/ansible.cfg
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### Steps to Reproduce

```yaml (paste below)

- name: Clone Proxmox template and start VM
  hosts: localhost
  vars_files:
    - proxmox_secrets.yml
  gather_facts: false  # Not required for this task

  tasks:
    - name: Clone template to a new VM
      community.general.proxmox:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "pve.galvoti.net"
        node: "pve"
        clone: "9001"
        vmid: "{{ vm_id }}"
        clone_type: "full"
        hostname: "{{ vm_name }}"
        ostype: "debian"
        storage: "vol2"  # Replace with the desired storage for the VM
        state: present

    - name: Start the cloned VM
      community.general.proxmox:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "pve.galvoti.net"
        node: "pve"
        vmid: "{{ vm_id }}"
        state: started
```

### Expected Results

I expected the template image to be cloned to a new vm (and then started).   The template clone is a cloud-init based image.  Cloning by hand in proxmox works as expected.

### Actual Results

Command run: 
vm_id and vm_name are passed in on commandline.
api_token_id and api_token_secret are passed in from the vault.

``
ansible-playbook build_debian_12_proxmox.yml --ask-vault-pass -e "vm_id=203 vm_name=test" -vvv
```

```console (paste below)

ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "pve.galvoti.net",
            "api_password": null,
            "api_token_id": "integration",
            "api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "svc_ansible@pve",
            "clone": 9001,
            "clone_type": "full",
            "cores": null,
            "cpus": null,
            "cpuunits": null,
            "description": null,
            "disk": null,
            "features": null,
            "force": false,
            "hookscript": null,
            "hostname": "test",
            "ip_address": null,
            "memory": null,
            "mounts": null,
            "nameserver": null,
            "netif": null,
            "node": "pve",
            "onboot": null,
            "ostemplate": null,
            "ostype": "debian",
            "password": null,
            "pool": null,
            "proxmox_default_behavior": "no_defaults",
            "pubkey": null,
            "purge": false,
            "searchdomain": null,
            "state": "present",
            "storage": "vol2",
            "swap": null,
            "tags": null,
            "timeout": 30,
            "timezone": null,
            "unprivileged": true,
            "update": false,
            "validate_certs": false,
            "vmid": 203
        }
    },
    "msg": "Container to be cloned does not exist",
    "vmid": 203
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
