### ISSUE TITLE
nmcli not idempotent when adding bond

### ISSUE THREAD

**Issue by mueller-ma** [ansible-collections/community.general#7945]
### Summary

When executing the following task Ansible always reports "changed":

````yaml
- name: Add bond
  community.general.nmcli:
    type: bond
    conn_name: bond0
    ip4: '<redacted>'
    gw4: '<redacted>'
    mode: 'active-backup'
    state: present
````

````
TASK [common : Add bond] **************
--- before
+++ after
@@ -1,5 +1,5 @@
 {
-    "802-3-ethernet.mtu": null,
+    "802-3-ethernet.mtu": "auto",
     "connection.autoconnect": "yes",
     "ipv4.addresses": [
         "<redacted>"
````

### Issue Type

Bug Report

### Component Name

nmcli 

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.3]
[....]
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 8.3.0
```

### OS / Environment

Debian 12

### Steps to Reproduce

- Execute the playbook twice

### Expected Results

First time changed, than no change.

### Actual Results

Always "changed"

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
