### ISSUE TITLE
Reconsider the "-f" (force flag) in general.filesystem's swap

### ISSUE THREAD

**Issue by GustavoPeredo** [ansible-collections/community.general#7946]
### Summary

I am trying to format a partition as swap in an Alpine Linux managed system, the command fails because "-f" is not implemented in BusyBox's `mkswap` command.

I believe this feature change would be helpful for the community for the following reasons:
1- Increase compatibility among node systems
2- Prevent the user from making a "stupid" decision, from the manual:

```

-f
Force - go ahead even if the command is stupid. This allows the creation of a swap area larger than the file or partition it resides on.
Without this option mkswap will refuse to erase the first block on a device with a partition table or on whole disk (e.g. /dec/sda).
```

From my knowledge, different than the use case for `-F` in other `mkfs.*` commands (usually for automation), `mkswap` doesn't require the `-f` flag. These are the uses for the force flage from the [source code](https://github.com/util-linux/util-linux/blob/master/disk-utils/mkswap.c):

Erasing the first block on a device:
```c

if (!ctl->force) {
		if (lseek(ctl->fd, 0, SEEK_SET) != 0)
			errx(EXIT_FAILURE, _("unable to rewind swap-device"));

#ifdef HAVE_LIBBLKID
		pr = new_prober(ctl);
		blkid_probe_enable_partitions(pr, 1);
		blkid_probe_enable_superblocks(pr, 0);

		if (blkid_do_fullprobe(pr) == 0 &&
		    blkid_probe_lookup_value(pr, "PTTYPE", &v, NULL) == 0 && v) {
			type = xstrdup(v);
			zap = 0;
		}
#else
		/* don't zap if compiled without libblkid */
		zap = 0;
#endif
```

Requesting more swap space than is available on the device (I'd consider a bad idea to have on by default):
```c
else if (ctl.npages > sz && !ctl.force)
		errx(EXIT_FAILURE,
			_("error: "
			  "size %llu KiB is larger than device size %"PRIu64" KiB"),
			ctl.npages * (ctl.pagesize / 1024), sz * (ctl.pagesize / 1024));

```

### Issue Type

Feature Idea

### Component Name

filesystem

### Additional Information

```yaml (paste below)
---
- name: Install OS
  hosts: install
  remote_user: root
  vars:
    device: "/dev/vda"
  tasks:
    - name: Setup partition for main filesystem
      community.general.parted:
        device: "{{ device }}"
        label: gpt
        number: 1
        state: present
        flags:
          - boot
        part_start: 1MB
        part_end: -4GB

    - name: Setup partition for swap
      community.general.parted:
        device: "{{ device }}"
        label: gpt
        number: 2
        state: present
        flags:
          - swap
        part_start: -4GB

    - name: Format swap
      community.general.filesystem:
        fstype: swap
        dev: "{{ device }}2"
        state: present
        opts: ""
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
