### ISSUE TITLE
zfs module to handle 'inherit' and 'default'

### ISSUE THREAD

**Issue by carpoon** [ansible-collections/community.general#7959]
### Summary

In zfs, different properties can have different values, but there are two special ones, that require special handling, inherit and default.  To achieve idempotency and to have the ability to set all values for zfs properties,  it's required to  handle these special values. 

### Issue Type

Feature Idea

### Component Name

zfs

### Additional Information

# Why is it needed:
 * When a value is set, there's no way to set it back to the default value (default or inherit), you can set it to the same value, as the default, but it won't change with that value
 * we'd like to define many parameters for our zfs file systems and we have many values we'd like to leave as the default

## The goal would be to a be able to write something like this:
```yaml

- name: Create and set up a zfs filesystem
  zfs:
    name: "tank/example"
    state: present
    extra_zfs_properties:
      sync: "!default"
      compression: "!inherit"
```

# Implementation details
 * For the module to be able to identify these special values, the '!' character is added to the values (this is not strictly needed, but in my opinion, with this, it's more distinctive and conveys the special use of these values)
 * To make this more maintainable, the user needs to know, it the zfs property has a default value or it can be inherited

If this behavior is acceptable, I'll create a PR with my modifications. 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/beadm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/beadm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
!component =plugins/modules/zfs.py

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/zfs.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/zfs.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @johanwiren
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by telyn** [comment]
I want this too (and will be working around it in the meantime by writing my own "call zfs inherit when a property is null" task since I don't (currently! hehe) need to return to the default) - but I'm a bit wary about using an "!" as the signifier of a special value: especially given that zfs user properties can be set with the zfs module. 

Bit of a caveat about the rest of this message: I'm a relative newbie to Ansible and though I'm fairly competent at achieving results with it I don't know how closely my nose is calibrated to the general community sense of style smell. So take the opinions below with a pinch of salt :-)

I'm mulling a couple of options for it, and I will write out example Tasks here which should be semantically identical.

Option 1: A couple of extra inputs to the module:
I think this is pretty clear about its intentions, but comes with a caveat of perhaps needing some extra checks: separating the properties into three places maybe makes it easier to accidentally define a property in multiple places - so we've have to define a order of precedence, or make an assertion that there's only one definition per property. Seems like extra work, communication, and potential headache.

```yaml
community.general.zfs:
  name: example/dataset
  extra_zfs_properties:
    compression: "zstd"
  inherit_zfs_properties:
    - "quota"
  default_zfs_properties:
    - "dedup"
```

Option 2: accept an object with a "special" key:
I like this one - still have just one list, the code is pretty clear about what it does. I just think "special" is maybe an odd word, but I couldn't think of a better one.

```yaml
community.general.zfs:
  name: example/dataset
  extra_zfs_properties:
    compression: "zstd"
    quota: { special: "inherit" }
    dedup: { special: "default" }
```

Option 3: accept an object with a "default" or "inherit" key
This is about as good as option 2 to me - we'd have to assert that you don't pass `{ default: true, inherit: true }`, but it seems fairly simple to work with, and you don't have to remember the word "special". I suppose the `true` here is really just like a canonical form, and we could accept any value - all we're concerned about is whether the key is set.

```yaml
community.general.zfs:
  name: example/dataset
  extra_zfs_properties:
    compression: "zstd"
    quota: { default: true }
    dedup: { inherit: true }
```


Option 4: toggleable meaning of None:
It's self-documenting but it has this annoying quality of needing to use two Tasks for the job, and introduces the possibility of maybe unintentionally un-doing work from the previous Task. Just not very neat.

```yaml
community.general.zfs:
  name: example/dataset
  extra_zfs_properties:
    compression: "zstd"
    quota: null
  none_behaviour: inherit

community.general.zfs:
  name: example/dataset
  extra_zfs_properties:
    dedup: null
  none_behaviour: default
```

Option 5: None for inherit, {} for default (or vice-versa)
Honestly, I hate this one-  the code ends up being SO unclear about what it intends/achieves until you go and read the manual for the zfs module with a fine-tooth comb. No thanks.

```yaml
community.general.zfs:
  name: example/dataset
  extra_zfs_properties:
    compression: "zstd"
    quota: null
    dedup: {}
```
