### ISSUE TITLE
Add new filters to calculate the union, intersection and difference of lists by preserving the items order

### ISSUE THREAD

**Issue by cfiehe** [ansible-collections/community.general#7984]
### Summary

The behavioral change in the builtin filters `ansible.builtin.union`,  `ansible.builtin.intersect`, and  `ansible.builtin.difference` introduced in 2.16, many people including myself have to migrate their code in order to stay compatible with the current release: https://github.com/ansible/ansible/issues/82554

Starting from 2.16 all three filters do no longer preserve the items order, so that the result is unpredictable. This is in some case unwanted. It is possible to workaround the problem e.g. by replacing `a | union(b)` with `(a + b) | unique`, but especially in complex statements where the `union` filter is involved and where ordering is important, you must have an eye on the operator precedencies. The whole code rewriting process is error-prone and statements become ugly and hard to read. In those cases, it would be nice to have replacing filters for the `ansible.builtin.union`,  `ansible.builtin.intersect`, and  `ansible.builtin.difference` which behave in the same way as they did before Ansible 2.16.

### Issue Type

Feature Idea

### Component Name

lists_union, lists_intersect, lists_difference

### Additional Information

```yaml (paste below)
---
- name: Filter test
  hosts: all
  become: true
  gather_facts: false
  vars:
    list1: [1, 2, 5, 3, 4, 10]
    list2: [1, 2, 3, 4, 5, 11, 99]
    list3: [1, 2, 3, 4, 5, 10, 99, 101]
  tasks:
    - name: Example for community.general.lists_union
      ansible.builtin.debug:
        msg: "{{ list1 | community.general.lists_union(list2, list3) }}"
    # => [1, 2, 5, 3, 4, 10, 11, 99, 101]

    - name: Example for community.general.lists_intersect
      ansible.builtin.debug:
        msg: "{{ list1 | community.general.lists_intersect(list2, list3) }}"
    # => [1, 2, 5, 3, 4]

    - name: Example for community.general.lists_difference
      ansible.builtin.debug:
        msg: "{{ list1 | community.general.lists_difference(list2, list3) }}"
    # => []
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
