### ISSUE TITLE
consul: Create consule_agent_servce/check to add new service and or checks

### ISSUE THREAD

**Issue by Ilgmi** [ansible-collections/community.general#7987]
### Summary

In the current implementation of the consul module, it uses the [python-consul](https://github.com/python-consul/python-consul/tree/master) library, which is no longer maintained. 

I want to implement two new modules for the agent service and check API. 
It should support all the consul module's features and implement new ones like the Meta field. 

It will use the _ConsulModule  from @apollo13 as a base class. 

### Issue Type

Feature Idea

### Component Name

consul

### Additional Information

```yaml (paste below)
- name: Create a service with name nginx  
  community.general.consul_agent_service:
    name: nginx
    service_port: 80
    address: localhost
    tags:
      - http
    meta:
      nginx_version: 1.25.3
    checks:
      - name: nginx-check2
        check_id: nginx-check2
        service_id: nginx
        interval: 60s
        notes: "My Note"
        http: http://localhost:80/morestatus
    token: "{{ consul_management_token }}"
  register: result
    
- name: Read service with name nginx
  community.general.consul_agent_service:
    name: nginx
    token: "{{ consul_management_token }}"
  register: result

- name: Add a check for service nginx
  community.general.consul_agent_check:
    name: nginx_check
    id: nginx_check
    interval: 30s
    http: http://localhost:80/morestatus
    notes: "Nginx Check"
    token: "{{ consul_management_token }}"
    service_id: nginx
  register: result

- name: Read check with name nginx
  community.general.consul_agent_check:
    name: nginx_check
    token: "{{ consul_management_token }}"
  register: result
  
- name: Remove a service with name nginx
  community.general.consul_agent_service:
    name: nginx
    state: absent
    token: "{{ consul_management_token }}"

    
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
