### ISSUE TITLE
apk module keeps showing changed when installing the same packages twice

### ISSUE THREAD

**Issue by ifalatiksetlog** [ansible-collections/community.general#7990]
### Summary

During molecule testing I got a idempotence error for one of my roles, which installs some requirements for a later step.

### Issue Type

Bug Report

### Component Name

apk

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2  

# /usr/local/lib/python3.11/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nano
```

### OS / Environment

target OS: docker alpine:3.14

### Steps to Reproduce

```yaml
- name: Install requirements
  community.general.apk:
    name: "ca-certificates, less, ncurses-terminfo-base, krb5-libs, libgcc, libintl, libssl1.1, libstdc++, tzdata, userspace-rcu, zlib, icu-libs, tar"
    state: present
    no_cache: true
  become: true
```

### Expected Results

When running the task twice, the state should be OK, not changed,

### Actual Results

output on second execution
```json
{
    "changed": true,
    "msg": "installed  less  ncurses-terminfo-base  krb5-libs  libgcc  libintl  libssl1.1  libstdc++  tzdata  userspace-rcu  zlib  icu-libs  tar package(s)",
    "packages": [],
    "stderr": "",
    "stderr_lines": [],
    "stdout": "fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz\nfetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz\nOK: 97 MiB in 42 packages\n",
    "stdout_lines": [
        "fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz",
        "fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz",
        "OK: 97 MiB in 42 packages"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/apk.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/apk.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @tdtrask
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Maxopoly** [comment]
I was unable to reproduce this using a alpine:3.14 docker container. Using your exact set of packages works fine when running

```
- name: Install requirements
  community.general.apk:
    name: "ca-certificates, less, ncurses-terminfo-base, krb5-libs, libgcc, libintl, libssl1.1, libstdc++, tzdata, userspace-rcu, zlib, icu-libs, tar"
    state: present
    no_cache: true
```

multiple times.

Looking at the output of your call to `apk`, I'd guess that in your case the check for whether a package is installed returns false for all packages except `ca-certificates`. This check is implemented [here](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/apk.py#L273) and works by parsing `/etc/apk/world`. Did your dockerized setup possibly break this file, for example by making it read only?  Could you provide the content of this file after running the module for the first time in your setup?

I submitted my tests (which are using a more general set of packages) as a PR here https://github.com/ansible-collections/community.general/pull/7992
