### ISSUE TITLE
Add the parameter Login Theme

### ISSUE THREAD

**Issue by gavarito** [ansible-collections/community.general#7993]
### Summary

I would like can use the parameter "Login Theme" in keycloak client. I automated the creation of keycloak clients with the ansible module, but there is no option in the module to configure which Login Theme you want to be used in the case of clients used in SSO integration. 

### Issue Type

Feature Idea

### Component Name

keycloak_client

### Additional Information

```yaml (paste below)
- name: Create or update a Keycloak client
  community.general.keycloak_client:
    auth_keycloak_url: https://auth.example.com/auth
    auth_realm: master
    auth_username: USERNAME
    auth_password: PASSWORD
    state: present
    realm: master
    client_id: test
    login_theme: keycloak
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/keycloak_client.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/keycloak_client.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @eikef @mattock @ndclt
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by pixslx** [comment]
Hi @gavarito 

Try this:
```yaml
- name: Create or update a Keycloak client
  community.general.keycloak_client:
    auth_keycloak_url: https://auth.example.com/auth
    auth_realm: master
    auth_username: USERNAME
    auth_password: PASSWORD
    state: present
    realm: master
    client_id: test
    attributes:
      login_theme: keycloak
```
