### ISSUE TITLE
FR | apt_rpm module | Add install from local rpm file

### ISSUE THREAD

**Issue by x09** [ansible-collections/community.general#7997]
### Summary

Default: apt_rpm install package from active repo

```
- name: Install packagename from repo 
  apt_rpm:
          pkg: packagename
          update_cache: yes
```

I suggest adding the ability to install from a local file, like as
```
- name: Install packagename from repo 
  apt_rpm:
          localfile: /path/to/packagename
          update_cache: yes
```
This is equivalent to running the commands

```
apt-get update
apt-get install /path/to/packagename
```

### Issue Type

Feature Idea

### Component Name

apt_rpm

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
