### ISSUE TITLE
Puppet fails with `invalid byte sequence in US-ASCII`

### ISSUE THREAD

**Issue by Knalltuete5000** [ansible-collections/community.general#8000]
### Summary

When executing the puppet agent via ansible on a remote host, the command fails with `invalid byte sequence in US-ASCII`.
Executing the puppet agent on the remote host via a shell the command successfully ends with return code 0.

It looks due to shell environment used by ansible to execute the command the shell is not utf-8 compatible

### Issue Type

Bug Report

### Component Name

puppet

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.6]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

community.general 8.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CALLBACKS_ENABLED = ['ansible.posix.timer', 'ansible.posix.profile_tasks', 'ansible.posix.profile_roles']
COLLECTIONS_PATHS = ['/home/niklas/Documents/inovex/cloud/inovex-cloud-ansible/external/collections']
DEFAULT_FORKS = 30
DEFAULT_STDOUT_CALLBACK = community.general.diy
ENABLE_TASK_DEBUGGER = True
HOST_KEY_CHECKING = False
RETRY_FILES_ENABLED = False
```

### OS / Environment

Local: Ubuntu 23.10
Remote: Ubuntu 22.04

### Steps to Reproduce

Because of the dependency to puppet and the puppet code I cannot give an example to reproduce the bug. The latest puppet 7 version is used as a server and agent

This is the ansible code used to invoke the module
```yaml
- name: puppet run
  community.general.puppet:
    puppetmaster: "{{ ansible_fqdn }}"
    timeout: 60m
    verbose: true
    debug: true
    logdest: all
  register: puppet_agent_result
  until: puppet_agent_result.rc == 0
```

### Expected Results

I expect that the puppet run finishes with return code 0 or 2 (puppet specifies this as success but changes were executed).

### Actual Results

From the puppet logs

```console (paste below)
Error: Could not prefetch <module>: invalid byte sequence in US-ASCII
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
