### ISSUE TITLE
Redfish `GetUpdateStatus` command throws exception for a completed update if there is no response body

### ISSUE THREAD

**Issue by mraineri** [ansible-collections/community.general#8003]
### Summary

In `redfish_info`, the `GetUpdateStatus` command is used to check an update handle for the progress of an update. Under the covers, this is a Redfish-defined task monitor. In most implementations, a user performing a GET on this task monitor will get back a 200 OK with a response body showing messages regarding what was updated in the system.

However, there is at least one implementation that is returning 204 No Content. Technically this is valid; a 204 simply means "everything successful, nothing to report". In this case, the underlying GET handling is throwing an exception because it's always expecting a response body and always tries to unpack data from the response.

### Issue Type

Bug Report

### Component Name

redfish_utils

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rainem1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/rainem1/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/rainem1/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.4.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Ubuntu 23.10

### Steps to Reproduce

Note, this requires a system that returns 204 as the final response when querying the handle referenced by the "update_handle" parameter

```yaml (paste below)
---
- hosts: all
  gather_facts: false
  vars:
    username: REDACTED
    password: REDACTED
    baseuri: REDACTED
    default_uri_timeout: 5
    default_uri_retries: 5
  tasks:
  - name: Get Update Status
    community.general.redfish_info:
      category: Update
      command: GetUpdateStatus
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      update_handle: /redfish/v1/TaskService/Tasks/0/Monitor
    retries: "{{ default_uri_retries }}"
    register: redfish_results
    until: redfish_results.redfish_facts.update_status.status != 'Running'
  - debug:
      var: redfish_results
```

### Expected Results

Did not expect an exception to be thrown... Causes the playbook to not resolve an "status" attribute in "update_status".

### Actual Results

```console (paste below)
[2024-02-20 23:35:18] fatal: [REDACTED -> localhost]: FAILED! => {
[2024-02-20 23:35:18]     "msg": "The conditional check 'redfish_results.redfish_facts.update_status.status != 'Running'' failed. The error was: error while evaluating conditional (redfish_results.redfish_facts.update_status.status != 'Running'): 'dict object' has no attribute 'status'. 'dict object' has no attribute 'status'"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
