### ISSUE TITLE
Add a umask option to community.general.npm

### ISSUE THREAD

**Issue by bnogaro** [ansible-collections/community.general#8006]
### Summary

When globally installing npm packages (`global: true`), if the root user has a restrictive umask (e.g. 027), pacakges are not readable or executable.
It would be nice to have a umask option, in the same fashion as the pip ansible module, for these specific tasks.

### Issue Type

Feature Idea

### Component Name

npm

### Additional Information

The option would simply has to be
```yaml
- name: Globally install npm-groovy-lint
  community.general.npm:
    name: npm-groovy-lint
    global: true
    umask: "022"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
