### ISSUE TITLE
java_cert: Add parameter for certificate data 

### ISSUE THREAD

**Issue by 8ware** [ansible-collections/community.general#8034]
### Summary

I need to ensure that a certain certificate is present in a Java truststore. Currently, I have to upload the certificate file first in order to use the `java_cert` module. Despite the extra step necessary, it makes the check mode less useful since it will fail when the certificate file is not present already.

The `java_keystore` module accepts a [`certificate`-parameter](https://docs.ansible.com/ansible/latest/collections/community/general/java_keystore_module.html#parameter-certificate) which allows to provide the certificate data directly. In the same manner, a `cert_data` parameter would be useful.

### Issue Type

Feature Idea

### Component Name

java_cert

### Additional Information

```yaml
- community.general.java_cert:
    cert_alias: example
    cert_data: "{{ lookup('file', '/path/to/certificate.crt') }}"
    keystore_path: "{{ truststore_path }}"
    keystore_password: "{{ truststore_password }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
