### ISSUE TITLE
 Proxmox inventory plugin: Groups are empty if VMs have more than 1 tag

### ISSUE THREAD

**Issue by zenhighzer** [ansible-collections/community.general#8036]
### Summary

When I try to build my ansible inventory via. proxmox inventory plugin the groups are empty when a machine has more than 1 tag: 

my proxmox-machines and their tags i.e.: 

lb01: loadbalancer, stack
lb02: loadbalaner, stack
k8scp1: controlplane, stack
k8scp2: controlplane, stack
k8scp3: controlplane, stack
k8swk1: worker, stack
k8swk2: worker, stack
k8swk2: worker, stack

My Inventory-Plugin looks like: 

```
plugin: community.general.proxmox
url: https://proxmox:8006/
user: myuser@pam
password: secretpassword
validate_certs: false
want_facts: true
groups:
  k8s_loadbalancer: "'loadbalancer' in (proxmox_tags_parsed|list)"
  k8s_controlplane: "'controlplane' in (proxmox_tags_parsed|list)"
  k8s_worker: "'worker' in (proxmox_tags_parsed|list)" 
  k8s_stack: "'stack' in (proxmox_tags_parsed|list)"
want_proxmox_nodes_ansible_host: true

```

- If I remove the tag "stack" from all machines then inventory plugin creates groups for k8s_loadbalancer, k8s_controlplane and k8s_worker... 

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.16.4]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True


```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/user/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.0.1  

# /home/user/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.3.0  


```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Ubuntu 22.04.4 LTS

### Steps to Reproduce

```yaml (paste below)
plugin: community.general.proxmox
url: https://proxmox:8006/
user: myuser@pam
password: secretpassword
validate_certs: false
want_facts: true
groups:
  k8s_loadbalancer: "'loadbalancer' in (proxmox_tags_parsed|list)"
  k8s_controlplane: "'controlplane' in (proxmox_tags_parsed|list)"
  k8s_worker: "'worker' in (proxmox_tags_parsed|list)" 
  k8s_stack: "'stack' in (proxmox_tags_parsed|list)"
want_proxmox_nodes_ansible_host: true

```

### Expected Results

I expect to have four groups: 

k8s_loadbalancer: lb01, lb02
k8s_controlplane: k8scp1, k8scp2, k8scp3
k8s_worker: k8swk1, k8swk2, k8swk3
k8s_stack: lb01, lb02, k8scp1, k8scp2, k8scp3, k8swk1, k8swk2, k8swk3

### Actual Results

```console (paste below)

$ansible-inventory -i my.proxmox.yml --list 

....  redacted , .... 

         "k8scp1": {
        "proxmox_tags": "controlplane;stack",
                "proxmox_tags_parsed": [
                    "controlplane;stack"
                ],

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/inventory/proxmox.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/inventory/proxmox.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @ilijamt @joshainglis @karmab @krauthosting
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by lyrandy** [comment]
This is a challenge I had to work through as well. I don't have my Proxmox HV working right now, so I can't experiment and see what values we get from the `proxmox_tags_parsed` variable, but from what I recall, the delimeter for multiple tags is a semi-colon. 

So for me, I tagged my VMs with multiple tags (using Terraform with Telmate/proxmox provider actually), and then had to do the following to have my VMs assigned to multiple groups.

I opted to also encode a convention in my tags so that I can have VM tags to signal it should be interpreted as an Ansible group, and tags for other purposes. I don't recall where I found it, but the `+` symbol turns out to be a valid char in tags.

VM Tags
vm-001: "dmz; group+proxy; group+fw"
vm-002: "app; group+app; group+backend"
vm-003: "db; backedup; group+db"

```yaml
keyed_groups:
  - key: proxmox_tags | split(';') |select('match', 'group') | map('regex_replace', '^group\+', '')
    prefix: ''
```
Results in the proxy, fw, app, backend, and db groups being made in Ansible.

In your case, if you don't need to further encode information in your tags like I did, and can consider all tags to be used to infer Ansible groups, perhaps the following (untested) snippet would be helpful.

VM tags
lb01: loadbalancer; stack
lb02: loadbalaner; stack
k8scp1: controlplane; stack
k8scp2: controlplane; stack
k8scp3: controlplane; stack
k8swk1: worker; stack
k8swk2: worker; stack
k8swk2: worker; stack

```yaml
keyed_groups:
  - key: proxmox_tags | split(';') 
    prefix: 'k8s'
    separator: '_'
```

I think this should yield the `k8s_loadbalancer`, `k8s_controlplane`, `k8s_worker`, and `k8s_stack` groups with the proper membership.

Hope this helps!

---
https://pve.proxmox.com/wiki/Graphical_User_Interface#_tags
