### ISSUE TITLE
[plugins/module_utils/ldap.py] LDAP failure details in native string format

### ISSUE THREAD

**Issue by StopMotionCuber** [ansible-collections/community.general#8049]
### Summary

For all LDAP modules, failures include `msg`, `details` and `exception`. While the `details` string is somewhat of a dictionary structure, it is presented as a string. This makes working with this task hard.

My usecase is that I want to provision an LDAP server, providing an initial password which is changed during a run. Therefore I want to change the `changed_when` and `failed_when` and base them off the details of the failure, as wrong credentials would be expected for the second run.

### Issue Type

Feature idea

### Component Name

ldap

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/ruben/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ruben/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801] (/usr/bin/python)
  jinja version = 3.1.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.3.0
```

### Steps to Reproduce

Execute ansible task that fails, e.g.

```
- name: Change admin password
  community.general.ldap_attrs:
    dn: 'olcDatabase=config,cn=config'
    attributes:
      olcRootPW: "secure_password"
    state: exact
    server_uri: "ldap://not_existing"
    bind_dn: "cn=admin,cn=config"
    bind_pw: "init_password"
  register: result

- name: Debug
  ansible.builtin.debug:
    msg: "{{ result.details.result }}"

```

### Expected Results

`result.details.result` should be a number (the LDAP error code)

### Actual Results

`result.details.result` fails in the debug task.

As a workaround I tried using `(result.details | regex_replace(\"'\", '\"') | from_json).result`. But that doesn't work if the error message contains `Can't contact LDAP server` cause the `'` _within_ the string would then also be replaced. In general I do not see a reason why `result.details` is presented as-is and not as a dictionary.

Edit: `result.details` is valid yaml, so parsing via `result.details | from_yaml` works and is a readable workaround.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/doc_fragments/ldap.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/doc_fragments/ldap.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
I don't see how this is a bug. The modules never claim that `details` is something else than a string.

While I agree that it would be nice to have sturctured data available as actual structured data, this would be a feature request, but definitely **not** a bug.

**Comment by StopMotionCuber** [comment]
> I don't see how this is a bug. The modules never claim that `details` is something else than a string.
> 
> While I agree that it would be nice to have sturctured data available as actual structured data, this would be a feature request, but definitely **not** a bug.

I wasn't really sure how to label that, would be fine for me to mark it as feature request (but I don't think I can change the label). In the current state it didn't seem too useful to me

**Comment by felixfontein** [comment]
I've edited the first post and relabelled it.

**Comment by StopMotionCuber** [comment]
As I see changing current behavior _might_ be a breaking change (even though on undocumented behavior), would it be possible adding another return value where that is included as a dict?

Or add all of the values to the return value of the module? That would mean adding
```yaml
ctrls: []
desc: Invalid credentials
msgid: 1
msgtype: 97
result: 49
```
or a subset thereof to the return value. Probably it would also make sense to document these
