### ISSUE TITLE
check_mode of community.general.pacemaker_cluster module

### ISSUE THREAD

**Issue by nagatakiman** [ansible-collections/community.general#8062]
### Summary

I created a playbook to set the cluster state to online or offline using the community.general.pacemaker_cluster module. Even if you run ansible-playbook with the "--check" option, it will be ignored and the cluster state will change.

Is this a bug? Please let me know if there is a workaround.

### Issue Type

Bug Report

### Component Name

community.general.pacemaker_cluster module

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.9]
```

python3.9

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 7.5.2

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

control node:RHEL8
target node:RHEL9

### Steps to Reproduce

```yaml (paste below)
- name: Set cluster
  hosts: target1
  become: true
  gather_facts: false
  tasks:
    - name: Set cluster no.1
      community.general.pacemaker_cluster:
        state: offline
```

### Expected Results

When I run it with the --check option while online, I thought it would remain online, but it changed to offline.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
