### ISSUE TITLE
community.general.archive module inconsistent behaviour

### ISSUE THREAD

**Issue by ojrzenski** [ansible-collections/community.general#8064]
### Summary

I came up with an issue using archive and unarchive modules when creating backups of some configuration files and restoring them. 

The first thing reported here is directly related to unexpected behavior when adding paths using a directory path vs. glob pattern.
In general, fix for that could be hard to implement - convert glob pattern to path. 

The second thing that surprised me is the undocumented and also leading to inconsistent behavior is "[common_path](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/archive.py#L308)" removal from the archive directory structure. 

I do not reckon any archiving tools doing this kind of logic like "common_path removal". 

In my opinion, the best and easiest way to fix that is to make "common_path removal" logic optional.

### Issue Type

Bug Report

### Component Name

community.general.archive

### Ansible Version

ansible [core 2.12.10]
  python version = 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

### Community.general Version

community.general   4.8.1

### OS / Environment

Ubuntu 20.04.3 LTS

### Steps to Reproduce

```yaml
---

- name: "community.general.archive module inconsistent behaviour" 
  gather_facts: false
  connection: local
  hosts: localhost
  tasks:
    # Create example file structure
    - ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "some/dir"
        - "other"

    - ansible.builtin.file:
        path: "some/dir/file.txt"
        state: touch
    
    # Create first archive adding nonexistent directory
    - community.general.archive:
        format: tar
        force_archive: true
        path:
          - "some/dir/file.txt"
          - "other/" # <-- nonexistent directory
        dest: "first.tar"

    # Create second archive using glob pattern
    - community.general.archive:
        format: "tar"
        force_archive: true
        path:
          - "some/dir/file.txt"
          - "other/*" # <-- nonexistent directory
        dest: "second.tar"

    # Unarchive archives and register file contents
    - ansible.builtin.unarchive:
        remote_src: true
        src: "{{ item }}.tar"
        dest: "."
        list_files: true
      register: "contents" 
      loop:
        - "first"
        - "second"

    # Debug results
    - debug: 
        msg: "{{ ','.join(contents.results[0].files) }} == {{ ','.join(contents.results[1].files) }}"
      failed_when: "contents.results[0].files != contents.results[1].files"


```

### Expected Results

I expect that the archive creates a consistent directory structure regardless of way You add paths: directory path or glob patterns.

### Actual Results

```console (paste below)
$ ansible-playbook playbook.yml
...
TASK [debug] *******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "msg": "some/dir/file.txt == file.txt"
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
