### ISSUE TITLE
keycloak_role: fails creating role with special characters in the name

### ISSUE THREAD

**Issue by bluestripe** [ansible-collections/community.general#8117]
### Summary

When trying to create roles with special characters in the name (i.e. `rabbitmq.read:*/*`) and exception occurs during role creation. The naming of the roles seem 'legal' as defining these through the UI works, and export/ import of a realm that includes these roles also works. Roles definitions are part of the rabbitmq oAuth2 tutorial found [here](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/blob/main/conf/keycloak/import/test-realm.json).

### Issue Type

Bug Report

### Component Name

keycloak_role

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.16.4]
  config file = /home/me/src/tools/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/.cache/pypoetry/virtualenvs/tools-pMLCjM1v-py3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /home/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/me/.cache/pypoetry/virtualenvs/tools-pMLCjM1v-py3.11/bin/ansible
  python version = 3.11.8 (main, Mar 19 2024, 09:48:45) [GCC 11.4.0] (/home/me/.cache/pypoetry/virtualenvs/tools-pMLCjM1v-py3.11/bin/python)
  jinja version = 3.1.3
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/me/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.4.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

CONFIG_FILE() = /home/me/src/tools/ansible.cfg
DEFAULT_GATHERING(/home/me/src/tools/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/me/src/tools/ansible.cfg) = ['/home/me/src/tools/environments/dev/hosts']
DEFAULT_REMOTE_PORT(/home/me/src/tools/ansible.cfg) = ****
DEFAULT_REMOTE_USER(/home/me/src/tools/ansible.cfg) = ****
DEFAULT_TIMEOUT(/home/me/src/tools/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/me/src/tools/ansible.cfg) = False
INVENTORY_ENABLED(/home/me/src/tools/ansible.cfg) = ['yaml', 'ini']
RETRY_FILES_ENABLED(/home/me/src/tools/ansible.cfg) = False
```

### OS / Environment

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

### Steps to Reproduce

```yaml (paste below)
---
- name: Create RabbitMQ roles
  hosts: localhost
  connection: local
  vars:
    kc_admin_user: admin
    kc_admin_pass: admin

  tasks:
      - name: Create role / WORKS
        community.general.keycloak_role:
          auth_client_id: admin-cli
          auth_keycloak_url: https://kc.example.com/auth
          auth_realm: master
          auth_username: "{{ kc_admin_user }}"
          auth_password: "{{ kc_admin_pass }}"
          validate_certs: false
          realm: dev-internal
          name: "rabbitmq.tag:management"
          state: present

      - name: Create role / ISSUE
        community.general.keycloak_role:
          auth_client_id: admin-cli
          auth_keycloak_url: https://kc.example.com/auth
          auth_realm: master
          auth_username: "{{ kc_admin_user }}"
          auth_password: "{{ kc_admin_pass }}"
          validate_certs: false
          realm: dev-internal
          name: "rabbitmq.read:*/*"
          state: present
...
```

### Expected Results

I expected all roles to be created without issues. 

### Actual Results

```console (paste below)
PLAY [Create RabbitMQ roles] ********************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [localhost]

TASK [Create role / WORKS] **********************************************************************************************************************************
ok: [localhost]

TASK [Create role / ISSUE] **********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/me/.ansible/tmp/ansible-tmp-1710841486.8631086-16823-69313973162622/AnsiballZ_keycloak_role.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/me/.ansible/tmp/ansible-tmp-1710841486.8631086-16823-69313973162622/AnsiballZ_keycloak_role.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/me/.ansible/tmp/ansible-tmp-1710841486.8631086-16823-69313973162622/AnsiballZ_keycloak_role.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.keycloak_role', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.keycloak_role', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.general.keycloak_role_payload_60_gmljj/ansible_community.general.keycloak_role_payload.zip/ansible_collections/community/general/plugins/modules/keycloak_role.py\", line 439, in <module>\n  File \"/tmp/ansible_community.general.keycloak_role_payload_60_gmljj/ansible_community.general.keycloak_role_payload.zip/ansible_collections/community/general/plugins/modules/keycloak_role.py\", line 357, in main\nTypeError: 'NoneType' object is not subscriptable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

The output above shows that the first role with name `rabbitmq.tag:management` gets created without issues. The role with name `rabbitmq.read:*/*` throws and exception.

Interestingly the roles are actually created in Keycloak, they do seem to have an issue with the user-role mapping in the UI. Re-running the role gives the following results, which is not idempotent (given that the role is actually created despite the exception):

 ```console
PLAY [Create RabbitMQ roles] ********************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [localhost]

TASK [Create role / WORKS] **********************************************************************************************************************************
ok: [localhost]

TASK [Create role / ISSUE] **********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not create role rabbitmq.read:*/* in realm dev-internal: HTTP Error 409: Conflict: {\"errorMessage\":\"Role with name rabbitmq.read:*/* already exists\"}"}

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

### Using the API directly

When you try to create the role directly on the Keycloak API, it works. So the API is OK with this type of name:

```console
MASTER_TOKEN=$(curl --location --request POST "http://dev-auth:8080/realms/master/protocol/openid-connect/token" \
-s \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=admin-cli' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=admin' \
--data-urlencode 'password=admin' | jq -r '.access_token')

curl -v -s -XPOST --location 'http://dev-auth:8080/admin/realms/dev-internal/roles' \
--header 'Authorization: Bearer '"$MASTER_TOKEN" \
--header 'Content-Type: application/json' \
-d '{"name": "rabbitmq.configure:*/*"}' | jq
```

Returns a '201 Created':

```code
*   Trying xxx.xxx.xxx.xxx:8080...
* Connected to dev-auth (xxx.xxx.xxx.xxx) port 8080 (#0)
> POST /admin/realms/dev-internal/roles HTTP/1.1
> Host: dev-auth:8080
> User-Agent: curl/7.88.1
> Accept: */*
> Authorization: Bearer ***
> Content-Type: application/json
> Content-Length: 34
>
} [34 bytes data]
< HTTP/1.1 201 Created
< Location: http://dev-auth:8080/admin/realms/dev-internal/roles/rabbitmq.configure:*/*
< Referrer-Policy: no-referrer
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< content-length: 0
<
* Connection #0 to host dev-auth left intact
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
