### ISSUE TITLE
aix_filesystem: _validate_vg not passing vg name to lsvg_cmd

### ISSUE THREAD

**Issue by amazzatenta** [ansible-collections/community.general#8151]
### Summary

When using the community.general.aix_filesystem module to create a filesystem and passing the vg parameter to the module. The _validate_vg function fails to pass the vg variable to the in line 245

### Issue Type

Bug Report

### Component Name

aix_filesystem

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Sep 22 2023, 17:58:34) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.9)
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.4.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)
tasks:
    - name: Create our filesystem
      community.general.aix_filesystem:
        filesystem: "{{fs_name}}"
        size: "{{fs_size | default('1G')}}"
        vg: "{{fs_vg |default('rootvg')}}"
        state: present
```

### Expected Results

Create a new logical volume on the specified vg.

### Actual Results

```console (paste below)
FAILED! => {"changed": false, "msg": "Failed executing /usr/sbin/lsvg command."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
