### ISSUE TITLE
keycloak_authentication: new auth execution in wrong requirement state

### ISSUE THREAD

**Issue by rafi0101** [ansible-collections/community.general#8160]
### Summary

I have tried to copy an existing authentication flow and add an execution to it. But in my case, all new executions I add have the requirement "DISABLED" no matter what I set as requirement. Only when I run the playbook a second time, the requirement is set/changed to the requirement I configured.

### Issue Type

Bug Report

### Component Name

keycloak_authentication

### Ansible Version

```console (paste below)
ansible [core 2.16.4]
  config file = /home/raphael/git/ansible-spielewiese/ansible.cfg
  configured module search path = ['/home/raphael/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/python_venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/raphael/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/python_venvs/ansible/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/local/python_venvs/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
community.general 8.4.0
```

### OS / Environment

Debian GNU/Linux 12 (bookworm)
Keycloak 23.0.6

### Steps to Reproduce

```yaml (paste below)
- name: "<keycloak> ensure authentication flows are present"
  community.general.keycloak_authentication:
    auth_keycloak_url: "'http://localhost:8080'"
    auth_username: "admin"
    auth_password: "password"
    auth_realm: "master"
    realm: "test"
    alias: "test browser"
    copyFrom: "browser"
    authenticationExecutions:
      - providerId: "auth-recovery-authn-code-form"
        requirement: "ALTERNATIVE"
        flowAlias: "test browser Browser - Conditional OTP"
      - providerId: "reset-password"
        requirement: "REQUIRED"
```
Also same result if now flowAlias is set

### Expected Results

The requirement should be set as configrued in ansible at the first time directly

### Actual Results

![image](https://github.com/ansible-collections/community.general/assets/43086854/a8ca9b04-a6eb-4ebf-abd3-ade57a1923ce)

In ansible diff it is correct, but in end state its wrong

<details>
<summary>Ansible Module Output <--click for more information</summary>

```json
{
    "ansible_loop_var": "item",
    "attempts": 1,
    "changed": true,
    "diff": {
        "after": {
            "alias": "test browser",
            "authenticationExecutions": [
                {
                    "authenticationConfig": null,
                    "displayName": null,
                    "flowAlias": "test browser Browser - Conditional OTP",
                    "index": null,
                    "providerId": "auth-recovery-authn-code-form",
                    "requirement": "ALTERNATIVE",
                    "subFlowType": "basic-flow"
                },
                {
                    "authenticationConfig": null,
                    "displayName": null,
                    "flowAlias": null,
                    "index": null,
                    "providerId": "reset-password",
                    "requirement": "ALTERNATIVE",
                    "subFlowType": "basic-flow"
                }
            ],
            "builtIn": null,
            "copyFrom": "browser",
            "description": null,
            "providerId": null,
            "subflow": null
        },
        "before": ""
    },
    "end_state": {
        "alias": "test browser",
        "authenticationExecutions": [
            ...
            {
                "authenticationFlow": true,
                "configurable": false,
                "description": "Flow to determine if the OTP is required for the authentication",
                "displayName": "test browser Browser - Conditional OTP",
                "flowId": "412f2173-91bd-4ebb-844a-adde296104f6",
                "id": "9aa1e2f6-cf7b-460c-8363-9e100c3d2e4c",
                "index": 1,
                "level": 1,
                "requirement": "CONDITIONAL",
                "requirementChoices": [
                    "REQUIRED",
                    "ALTERNATIVE",
                    "DISABLED",
                    "CONDITIONAL"
                ]
            },
            ...
            {
                "configurable": false,
                "displayName": "Recovery Authentication Code Form",
                "id": "8532d6d9-bef0-4b09-a2d3-453861a2823c",
                "index": 2,
                "level": 2,
                "providerId": "auth-recovery-authn-code-form",
                "requirement": "DISABLED",
                "requirementChoices": [
                    "REQUIRED",
                    "ALTERNATIVE",
                    "DISABLED"
                ]
            },
            {
                "configurable": false,
                "displayName": "Reset Password",
                "id": "934316af-a346-4652-a870-148a54b8ca4b",
                "index": 4,
                "level": 0,
                "providerId": "reset-password",
                "requirement": "DISABLED",
                "requirementChoices": [
                    "REQUIRED",
                    "ALTERNATIVE",
                    "DISABLED"
                ]
            }
        ],
        "builtIn": false,
        "description": "browser based authentication",
        "id": "58dad2cd-43e3-4897-bfc0-174f97230dbd",
        "providerId": "basic-flow",
        "topLevel": true
    },
    "failed": false,
    "flow": {},
    "invocation": {
        "module_args": {
            "alias": "test browser",
            "auth_client_id": "admin-cli",
            "auth_client_secret": null,
            "auth_keycloak_url": "http://localhost:8080",
            "auth_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "auth_realm": "master",
            "auth_username": "admin",
            "authenticationExecutions": [
                {
                    "authenticationConfig": null,
                    "displayName": null,
                    "flowAlias": "test browser Browser - Conditional OTP",
                    "index": null,
                    "providerId": "auth-recovery-authn-code-form",
                    "requirement": "ALTERNATIVE",
                    "subFlowType": "basic-flow"
                },
                {
                    "authenticationConfig": null,
                    "displayName": null,
                    "flowAlias": null,
                    "index": null,
                    "providerId": "reset-password",
                    "requirement": "ALTERNATIVE",
                    "subFlowType": "basic-flow"
                }
            ],
            "connection_timeout": 10,
            "copyFrom": "browser",
            "description": null,
            "force": false,
            "http_agent": "Ansible",
            "providerId": null,
            "realm": "test",
            "state": "present",
            "token": null,
            "validate_certs": true
        }
    },
    "item": {
        "alias": "test browser",
        "authenticationExecutions": [
            {
                "flowAlias": "test browser Browser - Conditional OTP",
                "providerId": "auth-recovery-authn-code-form",
                "requirement": "ALTERNATIVE"
            },
            {
                "providerId": "reset-password",
                "requirement": "ALTERNATIVE"
            }
        ],
        "copyFrom": "browser",
        "realm": "test"
    },
    "msg": ""
}
```

</details>

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/keycloak_authentication.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/keycloak_authentication.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Gaetan2907 @eikef @elfelip @mattock @ndclt
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @thomasbach-dev
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by tukez** [comment]
I tried to copy the browser flow and add my custom authenticator, it changed the "Cookie" step from alternative to required (in addition to incorrectly setting the custom authenticator requirement to disabled):

![copied_flow](https://github.com/user-attachments/assets/259eb797-8b5f-44b8-8690-cb8760b5bb83)

After I ran the ansible task a second time, it also changed the order of the flow:

![updated_flow](https://github.com/user-attachments/assets/849323f7-3288-4f1f-9a77-d436160e9846)

**Comment by dirks** [comment]
Mixed up requirements in the first run and order/indexes in follow up runs here as well. When I noticed, I made the configuration more explicit:

- specified each authenticationExecution and not just the ones in addition to the cloned ones (in my case clone of the browser flow)
- stated the index of each authenticationExecution
- ensured that the implicit order in the authenticationExecutions list is:
  1. all top level executions in order
  2. all second level executions in order
  3.  all third level executions in order 

Did not really seem to help. The order kept on changing in consecutive runs.

I removed the indexes again but  the order was not as intended. I needed a new execution before a cloned one and the implicit list order did not help here. Afterwards I specified only the index of the new execution I needed before the cloned one. Now I get the intended order and it stays that way, but only after the 3rd run.

Despite that the reported state will always be `changed`, but no diff is reported by the task directly with `-D` option. If I register and debug the task output the `after` and `before` of the diff are reported but identical.

<details>
<summary>Snippet of tasks. Click to expand</summary>

```yaml
    - name: Create magic browser authentication flow
      community.general.keycloak_authentication:
     […]
        alias: "Magic browser"
        copyFrom: "browser"
        description: "browser based authentication with magic link"
        authenticationExecutions:
          - displayName: "Cookie"
            providerId: "auth-cookie"
            requirement: "ALTERNATIVE"
            # index: 0
          - displayName: "Kerberos"
            providerId: "auth-spnego"
            requirement: "DISABLED"
            # index: 1
          - displayName: "Identity Provider Redirector"
            providerId: "identity-provider-redirector"
            requirement: "ALTERNATIVE"
            # index: 2
          - displayName: "Magic Link forms"
            requirement: "ALTERNATIVE"
            subFlowType: "basic-flow"
            index: 3
          - displayName: "Magic browser forms"
            requirement: "ALTERNATIVE"
            subFlowType: "basic-flow"
            # index: 4
          - providerId: "auth-username-form"
            requirement: "REQUIRED"
            flowAlias: "Magic Link forms"
            # index: 0
          - providerId: "magic-link"
            requirement: "REQUIRED"
            flowAlias: "Magic Link forms"
            # index: 1
          - displayName: "Username Password Form"
            providerId: "auth-username-password-form"
            flowAlias: "Magic browser forms"
            requirement: "REQUIRED"
            # index: 0
          - displayName: "Magic browser Browser - Conditional OTP"
            flowAlias: "Magic browser forms"
            subFlowType: "basic-flow"
            requirement: "CONDITIONAL"
            # index: 1
          - displayName: "Condition - user configured"
            providerId: "conditional-user-configured"
            flowAlias: "Magic browser Browser - Conditional OTP"
            requirement: "REQUIRED"
            # index: 0
          - displayName: "OTP Form"
            providerId: "auth-otp-form"
            flowAlias: "Magic browser Browser - Conditional OTP"
            requirement: "REQUIRED"
            # index: 1
        state: present
      register: __lf2kc_magic_browser_auth

    - name: Show magic browser auth
      ansible.builtin.debug:
        var: __lf2kc_magic_browser_auth
```

</details>

**Comment by egandro** [comment]
I have the same issue.

Are you guys in for fixing this?

**Comment by hazmat345** [comment]
Just ran into this as well, I'm getting inconsistent results when trying to add executions.

**Comment by egandro** [comment]
I found the issue :)

I tried to just use the REST api and bypass Ansible.

When I add an `auth-username-password-form` step - and - I change this later to REQUIRED (REQUIRED is the only option anyway) it totally screws up the order of the items.

That looks not like some ansible but got me.

```yml
    - name: Add Step "Username Password Form" (pos 0/4/1/0)
      ansible.builtin.uri:
        url: "https://foo.{{ domain_name }}/admin/realms/{{ keycloak_realm }}/authentication/flows/{{ 'foobar ' | urlencode }}{{ workflow_sub_name | urlencode }}/executions/execution"
        method: POST
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body: |-
          {
            "provider":"auth-username-password-form"
          }
        body_format: json
        status_code: 201

    - name: Get all Flows for {{ workflow_name }}
      ansible.builtin.uri:
        url: "https://foo.{{ domain_name }}/admin/realms/{{ keycloak_realm }}/authentication/flows/{{ workflow_name | urlencode }}/executions"
        method: GET
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: flow_response

    - name: subflow_id (pos 9)
      set_fact:
        guid: "{{ flow_response.json[9].id }}"

    # this foots up everything!
    # - name: Update "Username Password Form" to Required
    #   ansible.builtin.uri:
    #     url: "https://foo.{{ domain_name }}/admin/realms/{{ keycloak_realm }}/authentication/flows/{{ workflow_name | urlencode }}/executions"
    #     method: PUT
    #     headers:
    #       Authorization: "Bearer {{ token_response.json.access_token }}"
    #       Content-Type: "application/json"
    #     body: |-
    #       {
    #         "id":"{{ guid }}",
    #         "requirement":"REQUIRED"
    #       }
    #     body_format: json
    #     status_code: 204
```
