### ISSUE TITLE
requested image not found by fingerprint

### ISSUE THREAD

**Issue by Herschdorfer** [ansible-collections/community.general#8161]
### Summary

I'm currently trying to create a LXD container via Ansible on a virtual machine.
The Machine is running Ubuntu 22.04.

I copied the example from https://docs.ansible.com/ansible/latest/collections/community/general/lxd_container_module.html

```yml
# An example for creating container in project other than default
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container in project mytestproject
      community.general.lxd_container:
        name: mycontainer
        ignore_volatile_options: true
        state: started
        source:
          protocol: simplestreams
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/20.04/cloud
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

Now im getting the error:

```
TASK [Create a started container in project mytestproject] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"actions": [], "changed": false, "msg": "Failed getting remote image info: Failed getting image: The requested image couldn't be found for fingerprint \"ubuntu/20.04/cloud\""}
```

when i run the example with the fingerprint, all seems to be ok

```yml
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      community.general.lxd_container:
        name: mycontainer
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          # Provides current (and older) Ubuntu images with listed fingerprints
          server: https://cloud-images.ubuntu.com/releases
          # Protocol used by 'ubuntu' remote (as shown by 'lxc remote list')
          protocol: simplestreams
          # This provides an Ubuntu 14.04 LTS amd64 image from 20150814.
          fingerprint: e9a8bdfab6dc
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

```
PLAY RECAP ********************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### Issue Type

Bug Report

### Component Name

lxd_container

### Ansible Version

```console (paste below)
ansible 2.10.8
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```

### Community.general Version

```console (paste below)
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6  

# /home/xxx/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.5.0  
```

### Configuration

```console (paste below)


```

### OS / Environment

Ubuntu 22.04 LTS

### Steps to Reproduce

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      community.general.lxd_container:
        name: mycontainer
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          # Provides current (and older) Ubuntu images with listed fingerprints
          server: https://cloud-images.ubuntu.com/releases
          # Protocol used by 'ubuntu' remote (as shown by 'lxc remote list')
          protocol: simplestreams
          # This provides an Ubuntu 14.04 LTS amd64 image from 20150814.
          fingerprint: e9a8bdfab6dc
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

### Expected Results

Container gets created

### Actual Results

```console
TASK [Create a started container in project mytestproject] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"actions": [], "changed": false, "msg": "Failed getting remote image info: Failed getting image: The requested image couldn't be found for fingerprint \"ubuntu/20.04/cloud\""}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/lxd_container.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/lxd_container.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Herschdorfer** [comment]
meanwhile i was able to create a container after reading the API specification at: https://documentation.ubuntu.com/lxd/en/latest/howto/instances_create/

I changes the yaml to:

```yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container in project mytestproject
      community.general.lxd_container:
        name: mycontainer
        ignore_volatile_options: true
        state: started
        source:
          protocol: simplestreams
          type: image
          server: https://cloud-images.ubuntu.com/releases
          alias: "22.04"
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

I had to change the alias to the version eg.  "20.04" and changed the server to https://cloud-images.ubuntu.com/releases.

https://discuss.linuxcontainers.org/t/important-notice-for-lxd-users-image-server/18479 mentions that there will be no access anymore for lxd 5.20+ from 15th of March onwards.

Maybe the docs need to be updated.
