### ISSUE TITLE
[ssh_config] Enable value `accept-new` for option `strict_host_key_checking`

### ISSUE THREAD

**Issue by benbouillet** [ansible-collections/community.general#8177]
### Summary

[OpenSSH 7.6](https://www.openssh.com/txt/release-7.6) introduced a new value `accept-new` for `StrictHostKeyChecking` which allows for automatically adding fingerprints for new hosts in `~/.ssh/know_hosts` but still block the connection attempt if the fingerprint changes (eg. MITM attack).

The current accepted value for [`strict_host_key_checking`](https://docs.ansible.com/ansible/latest/collections/community/general/ssh_config_module.html#parameter-strict_host_key_checking) in `community.general.ssh_config` are:
- `yes`
- `no`
- `ask`

Would it be possible to add the value option ?

### Issue Type

Feature Idea

### Component Name

ssh_config

### Additional Information

```yaml (paste below)
- name: Add Router VM host to SSH config
  community.general.ssh_config:
    host: <REDACTED>
    hostname: <REDACTED>
    identity_file: <REDACTED>
    state: present
    add_keys_to_agent: true
    strict_host_key_checking: "accept-new"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
