### ISSUE TITLE
nios module - cannot pass IP list to host object

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.general#819]
_From @razvan-ig on Aug 21, 2020 16:36_

##### SUMMARY
https://docs.ansible.com/ansible/latest/modules/nios_host_record_module.html hints multiple IP addresses can be allocated to a Host entry (which is a supported feature) and indeed it works with something like

```
- name: create A record(s)
  nios_host_record:
    name: "{{ record_name }}"
    comment: "created by ansible"
    ipv4:
      - address: "{{ record_target[0] }}"
      - address: "{{ record_target[1] }}"
    view: "{{ infoblox_grid_view }}"
    state: present
    provider: "{{ nios_provider }}"
  when: (record_target|length==2)
```

my problem is I don't see any way of passing a list/array/yaml to the address field instead of enumerating, any hints?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Infoblox nios module

##### ANSIBLE VERSION
2.8.5

_Copied from original issue: ansible/ansible#71401_

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =plugins/modules/nios_host_record.py

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/nios_host_record.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/nios_host_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by russoz** [comment]
@razvan-ig Is this still an issue for you? If so, would you please care to expand on what exactly the problem is?

Per the docs (in the very link you sent), `ipv4` (which is an alias to `ipv4addrs`) is a `list` of `dict` objects. The `address` field is **not** of a `list` type, it is a `str`, as it is a key of a `dict`. So if you have a *list of addresses* you want to put in there, you will need to manipulate it to become a list of `dict` objects containing an `address` key and each value:
```yaml
- name: prepare IP list
  set_fact:
    ipv4_addrs: "{{ ipv4_addrs|default([]) + {'address': item} }}"
  loop: [ "1.1.1.1", "2.2.2.2", "3.3.3.3" ]
  #
  # after this set_fact:
  # ipv4_addrs == [{"address": "1.1.1.1"}, {"address": "2.2.2.2"}, {"address": "3.3.3.3"}]
  #
- name: create A record(s)
  nios_host_record:
    name: "{{ record_name }}"
    comment: "created by ansible"
    ipv4: "{{ ipv4_addrs }}"
    view: "{{ infoblox_grid_view }}"
    state: present
    provider: "{{ nios_provider }}"
  when: (record_target|length==2)
```
There might be a simpler way to transform `[1,2,3]` into `[{a:1}, {b:2}, {c:3}]`, I just lazily compiled this from the top-googled examples.
