### ISSUE TITLE
[datadog_monitor] - locked parameter is deprecated and replaced by restricted_roles

### ISSUE THREAD

**Issue by greenflowers** [ansible-collections/community.general#8192]
### Summary

The locked parameter is deprecated and replaced by restricted_roles parameter. According to Datadog Support they will remove this API option in the next weeks and return a 400 instead. All projects who use datadog_monitor in the current state, will fail from that day on.

### Issue Type

Feature Idea

### Component Name

datadog_monitor

### Additional Information

```yaml (paste below)
    - name: Create or destroy a Datadog metric monitors
      community.general.datadog_monitor:
        type: "metric alert"
        name: "{{ datadog_monitor_prefix }} {{ datadog_monitor.name }}"
        state: "{{ datadog_monitor_state }}"
        query: "{{ datadog_monitor.query }}"
        notification_message: |
          {{ (datadog_monitor.alert_recipients) | join(' ') }}
        thresholds: "{{ datadog_monitor.thresholds }}"
        evaluation_delay: "{{ datadog_monitor.evaluation_delay }}"
        api_key: "{{ datadog_api_key }}"
        app_key: "{{ datadog_app_key }}"
        tags: "{{ datadog_default_tags }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
