### ISSUE TITLE
opentelemetry: Use nested spans to organize output for role dependencies or include_roles

### ISSUE THREAD

**Issue by monsdar** [ansible-collections/community.general#8219]
### Summary

I am using the community.general.opentelemetry callback plugin to analyze the execution of my playbooks in Jaeger. Within my deployments I use roles that depend on other roles and roles that get included via ansible.builtin.include_role. Currently the execution of a playbook gets displayed in Jaegers timeline view as a sequence of traces.

I'm not 100% sure about the technical feasibility, but I'd like to suggest showing roles that are included by other roles as nested traces. That way when I have a lot of includes I could open/close them and focus on what's really interesting to me.

### Issue Type

Feature Idea

### Component Name

opentelemetry

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/callback/opentelemetry.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/callback/opentelemetry.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @v1v
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by v1v** [comment]
Can you provide a playbook with examples of what you get and want? This would help determine whether it's feasible. 🙇

**Comment by monsdar** [comment]
I've got the following structure:

span_tests.yml
```yaml
- name: Do some tests that use spans
  hosts: all
  tasks:
    - name: PlaybookFoo
      ansible.builtin.pause:
        seconds: 5
    - ansible.builtin.include_role:
        name: child_span
    - name: PlaybookBar
      ansible.builtin.pause:
        seconds: 5
```

roles/child_span/tasks/main.yml:
```yaml
- name: ChildBaz
  ansible.builtin.pause:
    seconds: 5
```

This results in the following Jaeger trace:

![image](https://github.com/ansible-collections/community.general/assets/4217216/d7f61be8-4642-4881-9fb1-9d540825d8eb)

* All tasks are shown as a sequence one after another
* The top-span for the playbook span_tests.yml is collapsible

I'd like to have the tasks from the role as nested into the `include_role`-span. That would allow to collapse the tasks and see how long the include has taken in general.

![image](https://github.com/ansible-collections/community.general/assets/4217216/c6a9ad6f-c251-43dd-a64e-512c6184f7e2)

There are other operations besides `include_role` like `include_tasks`, `include_playbook`and their `import` counterparts. This could even work for role-dependencies.

I think for more complex roles changing to nested spans will make the resulting graphs much better to handle.
