### ISSUE TITLE
Failed to download artifact, HTTP Error 404 

### ISSUE THREAD

**Issue by ambazasador** [ansible-collections/community.general#822]
##### SUMMARY
Hi all!
I'm trying to use maven_artifact for download from private repo, but i got 404. Where i did mistake ?
Nexus tree:
https://sun9-19.userapi.com/fZUvN-GTg0NDUiYqUH7R5rktmbeK_O34D1xbgw/zLtd9f97Exw.jpg

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### STEPS TO REPRODUCE

```yaml
--
- name: download artifact from nexus
  maven_artifact:
    group_id: nuget-hosted
    artifact_id: Foooo
    repository_url: 'http://domain.com:8081/repository'
    version: 2.6.1.202001
    extension: nupkg
    username: user
    password: pass
    dest: "{{ output_dir }}/nupkg/Foooo-2.6.1.202001.nupkg"
```

##### EXPECTED RESULTS
All works

##### ACTUAL RESULTS

```paste below
fatal: [10.0.21.15]: FAILED! => {"changed": false, "msg": "Failed to download artifact nuget-hosted:Foooo:nupkg:2.6.1.202001 because of HTTP Error 404: Not Foundfor URL http://domain.com:8081/repository/nuget-hosted/Foooo/2.6.1.202001/Foooo-2.6.1.202001.nupkg"}
```
