### ISSUE TITLE
Implement parameter 'keep_duplicates' in the filter lists_mergeby.

### ISSUE THREAD

**Issue by dancorrigancnp** [ansible-collections/community.general#8220]
### Summary

lists_mergeby will discard duplicate keys from two lists. 

### Issue Type

Feature Idea

### Component Name

filter lists_mergeby

### Additional Information

```yaml
list1:
  - name: client1
    path: path1

  - name: client1
    path: path2

  - name: client2
    path: path1

list2:
  - name: client1
    foo: foovalue1
    bar: barvalue1

  - name: client2
    foo: foovalue2
    bar: barvalue2

  - name: client3
    foo: foovalue3
    bar: barvalue3
```
The task below
```yaml
- name: Merge 2 lists by attribute name. list_merge='append'
  set_fact:
    my_list: "{{ list1 | community.general.lists_mergeby(list2, list_merge='append', keep_duplicates='true') }}"
```
will give

```yaml
my_list:
  - bar: barvalue1
    foo: foovalue1
    name: client1
    path: path1

  - bar: barvalue1
    foo: foovalue1
    name: client1
    path: path2

  - bar: barvalue2
    foo: foovalue2
    name: client2
    path: path1

  - bar: barvalue3
    foo: foovalue3
    name: client3
   ```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/filter/lists_mergeby.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/filter/lists_mergeby.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @vbotka
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by vbotka** [comment]
The goal of this filter is:

> Merge two or more lists of dictionaries by a given attribute

For example, given the two lists *list1* and *list2* the example below

```yaml
  my_list: "{{ [list1, list2] | community.general.lists_mergeby('name') }}"
```
gives as expected

```yaml
  my_list:
    - {bar: barvalue1, foo: foovalue1, name: client1, path: path2}
    - {bar: barvalue2, foo: foovalue2, name: client2, path: path1}
    - {bar: barvalue3, foo: foovalue3, name: client3}
```

The request to keep duplicates doesn't make sense. What am I missing?

**Comment by vbotka** [comment]
The documentation and testing of the parameters should be updated to:

1) Fail if *index* is missing 

```yaml
r: "{{  list1 | community.general.lists_mergeby(list2) }}"
```
2) Allow merging of a single list 

```yaml
r: "{{  list1 | community.general.lists_mergeby('index') }}"
```

**Comment by dancorrigancnp** [comment]
client1 is in list1 twice, with different paths
```yaml
- name: client1
    path: path1

  - name: client1
    path: path2
```
Your example only shows 3 items returned, and there should be 4 because client1 is in list1 twice.

**Comment by dancorrigancnp** [comment]
I used ChatGPT to achieve what I needed using this custom filter plugin.

`class FilterModule(object):
    def filters(self):
        return {
            'merge_dicts_by_key': self.merge_dicts_by_key
        }

    def merge_dicts_by_key(self, list1, list2, key):
        result = []
        for item1 in list1:
            for item2 in list2:
                if item1[key] == item2[key]:
                    merged_item = item1.copy()
                    merged_item.update(item2)
                    result.append(merged_item)
        return result
`
```yaml
- name: Task
  ansible.builtin.set_fact:
    __combined_list: "{{ list1 | merge_dicts_by_key(list2, 'name') }}"
```

**Comment by vbotka** [comment]
> client1 is in list1 twice, with different paths
> 
> ```yaml
> - name: client1
>   path: path1
> 
> - name: client1
>   path: path2
> ```

The filter *lists_mergeby* merges dictionaries (items of the lists) by common index. Optionally, if an attribute is a list, it can be manipulated (replace (default), keep, append, prepend, append_rp, or prepend_rp). See [ansible.builtin.combine](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/combine_filter.html). Only parameters of *ansible.builtin.combine* apply here.

In your case, put the paths into the lists if you want to merge them

```yaml
  list1:
    - {name: client1, path: [path1]}
    - {name: client1, path: [path2]}
    - {name: client2, path: [path1]}
```

Then, for example, (yes, you can merge a single list)

```yaml
  my_list: "{{ [list1, []] |
               community.general.lists_mergeby('name', list_merge='append') }}"
```

will append the lists

```yaml
  my_list:
    - name: client1
      path: [path1, path2]
    - name: client2
      path: [path1]
```

**Comment by vbotka** [comment]
> Need to get:
> 
> ```yaml
> merged_list:
>   - name: client1
>     path: path1
>     foo: foovalue1
>     bar: barvalue1
> 
>   - name: client1
>     path: path2
>     foo: foovalue1
>     bar: barvalue1
> 
>   - name: client2
>     path: path3
>     foo: foovalue2
>     bar: barvalue2
> ```

The filter *community.general.lists_mergeby* doesn't solve this use case: "Merge default attributes to a list by attribute *name*". For example, the declaration below gives what you want

```yaml
    merged_list: |
      [{% for i in list1 %}
      {{ list2|selectattr('name', 'eq', i.name)|combine(i) }},
      {% endfor %}]
```
A better option is to convert the defaults to a dictionary first

```yaml
    name_defaults: "{{ dict(list2|json_query('[].[name, @]')) }}"
```

This makes the solution more robust

```yaml
    merged_list: |
      [{% for i in list1 %}
      {% if i.name in name_defaults %}
      {{ name_defaults[i.name]|combine(i) }},
      {% endif %}
      {% endfor %}]
````

**Comment by dmnagornyi** [comment]
This works too, but we were hoping to do it in a nice way with a filter.
```yaml
- ansible.builtin.set_fact:
    merged_list: >-
      {{ merged_list | default([]) +
      [{'name': name,
      'path': path,
      'foo': foo,
      'bar': bar}] }}
  loop: "{{ list1 }}"
  vars:
    foo: "{{ list2 | selectattr('name', 'equalto', name) | map(attribute='foo') | first }}"
    bar: "{{ list2 | selectattr('name', 'equalto', name) | map(attribute='bar') | first }}"
  when:
    - list2 | selectattr('name', 'equalto', name) | length > 0
    - list2 | selectattr('name', 'equalto', name) | map(attribute='foo') | length > 0
    - list2 | selectattr('name', 'equalto', name) | map(attribute='bar') | length > 0
```
Anyway, thanks for help!

**Comment by vbotka** [comment]
> we were hoping to do it ... with a filter.

Are you able to describe a consistent use case? Are duplicates allowed in list2?

**Comment by vbotka** [comment]
>   when:
>     - list2 | selectattr('name', 'equalto', name) | length > 0

This will omit list1 item if the name is missing in list2?!

**Comment by dmnagornyi** [comment]
Our use case:
We have one list of clients with nfs paths. There could be same client ,many times but with different path. (~ 500 items) 
Second list is a unique list of same clients, but with the results of different checks. (~ 100 items)
Basically we need to add check results from list2 to each item in list1 mapping by client name.

This works perfect but I don't like to use custom filter: https://github.com/ansible-collections/community.general/issues/8220#issuecomment-2052401243

**Comment by vbotka** [comment]
> There could be the same client many times but with different paths.

Convert attributes *path* to lists and merge list1

```yaml
  update: "{{ [list1|json_query('[].{name:name, path:[path]}'), []] |
              community.general.lists_mergeby('name', list_merge='append') }}"
```

gives

```yaml
  update:
    - name: client1
      path: [path1, path2]
    - name: client2
      path: [path3]
```

> Add ... list2 to each item in list1 mapping by client name

Merge the lists

```yaml
  merged: "{{ [list2, update] |
              community.general.lists_mergeby('name', list_merge='append') }}"
```
gives

```yaml
  merged:
  - bar: b1
    foo: f1
    name: client1
    path:
    - path1
    - path2
  - bar: b2
    foo: f2
    name: client2
    path:
    - path3
  - bar: b3
    foo: f3
    name: client
```
This seems to be the best option.
