### ISSUE TITLE
Ubuntu autoinstall

### ISSUE THREAD

**Issue by magnusolsson80** [ansible-collections/community.general#8272]
### Summary

I want to add meta-data and user-data files for Ubuntu autoinstall. The current module implementation does not support "-" in filenames.  Ubuntu autoinstall is looking for two files, meta-data and user-data.

TASK [Customize ISO file] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to add local file meta-data to ISO with error: ISO9660 filenames must consist of characters A-Z, 0-9, and _"}

### Issue Type

Feature Idea

### Component Name

iso_customize

### Additional Information

```yaml (paste below)
    - name: "Customize ISO file"
      community.general.iso_customize:
        src_iso: "/Downloads/ubuntu-22.04.4-live-server-amd64.iso"
        dest_iso: "/Downloads/ubuntu-22.04-autoinstall.iso"
        add_files:
          - src_file: "meta-data"
            dest_file: "/server/meta-data"
          - src_file: "user-data"
            dest_file: "/server/user-data"
          - src_file: "grub.cfg"
            dest_file: "/boot/grub/grub.cfg"
      register: customize_iso_result
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
