### ISSUE TITLE
homebrew: Task fails on warning message when formula has cask of same name

### ISSUE THREAD

**Issue by kitizz** [ansible-collections/community.general#8274]
### Summary

I'd like to add a `force_formula` parameter to the brew role so that the brew command includes `--formula`.

### Rationale

When trying to install docker with homebrew,
```yml
- name: Install docker via homebrew
  homebrew:
    name: 'docker'
    state: present
```
it fails with the following message:
```
FAILED! => {"changed": false, "msg": "Warning: Treating docker as a formula. For the cask, use homebrew/cask/docker or specify the `--cask` flag."}
```

I can verify that running `brew install docker` on my machine prints the same warning, and returns a non-zero exit code.
But I can avoid this if I run `brew install --formula docker` since it disambiguates the name.

### Issue Type

Feature Idea

### Component Name

homebrew

### Additional Information

```yaml
- name: Install docker via homebrew
  homebrew:
    name: 'docker'
    state: present
    force_formula: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
