### ISSUE TITLE
Parsing Error in ansible community.general.xml module

### ISSUE THREAD

**Issue by blackden** [ansible-collections/community.general#8302]
### Summary

**Title**: Parsing Error in ansible community.general.xml module

**Description**:
When attempting to use the `community.general.xml` module in Ansible to process XML data, the following error occurs:

```
{"changed": false, "msg": "Error while parsing document: xml_string (Invalid bytes in character encoding, line 1, column 3084 (<string>, line 1))"}
```

**Steps to Reproduce**:
1. Run an Ansible playbook using the `community.general.xml` module.
2. Expected Result: Successful processing of XML data.
3. Actual Result: Error parsing XML with mention of invalid bytes in character encoding.

**Runtime Environment**:
- ansible [core 2.15.11]
- python version = 3.9.6
- Operating System: macOS 14.0 23A344

**Additional Information**:
This issue impedes the use of the `community.general.xml` module for XML data manipulation. Kindly investigate this behavior and propose a solution.

### Issue Type

Bug Report

### Component Name

xml

### Ansible Version

```console (paste below)
ansible [core 2.15.11]
  config file = None
  configured module search path = ['/Users/ragnar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ragnar/fedorov_tech/tex/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/ragnar/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ragnar/fedorov_tech/tex/.venv/bin/ansible
  python version = 3.9.6 (default, Aug 11 2023, 19:44:49) [Clang 15.0.0 (clang-1500.0.40.1)] (/Users/ragnar/fedorov_tech/tex/.venv/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```console (paste below)
Collection        Version
----------------- -------
community.general 7.5.2  
```

### Configuration

```console (paste below)
CONFIG_FILE() = None
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) =>
PAGER(env: PAGER) = less
```

### OS / Environment

macOS 14.0

### Steps to Reproduce

```yaml (paste below)
    - name: Get current course
      block:
        - name: Get course info
          ansible.builtin.uri:
            url: https://www.cbr.ru/scripts/XML_daily.asp
            method: POST
            return_content: true
          register: response
        - name: parse xml
          community.general.xml:
            xmlstring: "{{ response.content }}"
            xpath: /ValCurs/Valute[CharCode="EUR"]/Value
            content: text
          register: xmloutput
        - name: Set EUR
          ansible.builtin.set_fact:
            eur: "{{ xmloutput.matches[0].Value | regex_replace(',', '.')  | float | round(2) }}"
        - name: print Eur
          ansible.builtin.debug:
            msg: "{{ eur }}"

```

### Expected Results

1. An HTTP request will be made to the specified URL (`https://www.cbr.ru/scripts/XML_daily.asp`).
2. The received XML response will be successfully processed.
3. The Euro (`EUR`) exchange rate value will be extracted from the XML data.
4. The extracted Euro exchange rate value will be correctly converted to a floating-point format and rounded to two decimal places.
5. Correct display of the Euro exchange rate value in the debug output.

Essentially, the expected outcome involves successfully extracting and displaying the current Euro exchange rate from the XML response in the debug output.

### Actual Results

```console (paste below)
TASK [parse xml] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error while parsing document: xml_string (Invalid bytes in character encoding, line 1, column 3084 (<string>, line 1))"}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/xml.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/xml.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The problem could be that you are putting non-UTF-8 encoded text into a string and passing it as a string to the XML module. This generally destroys the encoding.

Better download the URL to a file and let the XML module work on the file.

**Comment by blackden** [comment]
> The problem could be that you are putting non-UTF-8 encoded text into a string and passing it as a string to the XML module. This generally destroys the encoding.
> 
> 
> 
> Better download the URL to a file and let the XML module work on the file.

I understand your point of view. Indeed, resorting to saving the URL to a file and then processing the XML may be a workaround, but it's not a true solution to the problem. It's important for the XML module to properly handle text with different encodings, as this allows for automation and ensures compatibility with various data sources. It would be wise to investigate any changes in the latest versions of the module and, if possible, understand why it stopped working as expected.

**Comment by felixfontein** [comment]
@blackden It is in fact *impossible* to handle this correctly, since Ansible itself will not allow to pass anything else than UTF-8 encoded data in.

To only way to change that is to add an option which allows the module to base64 decode the input; then you can pass the data with other encoding around in base64 encoded form. That way Ansible won't destroy the data before it is reached by the module.

**Comment by blackden** [comment]
I have found a solution. It involves converting the received data to a string, then transforming it into a dictionary, and finally converting it back to XML.
`response.content | string | ansible.utils.from_xml | ansible.utils.to_xml`

```yaml
- name: parse xml
    community.general.xml:
      xmlstring: "{{ response.content | string | ansible.utils.from_xml | ansible.utils.to_xml }}"
      xpath: /ValCurs/Valute[CharCode="EUR"]/Value
      content: text
    register: xmloutput
```
