### ISSUE TITLE
[PowerDNS] New pdns_record module ?

### ISSUE THREAD

**Issue by lgatellier** [ansible-collections/community.general#8356]
### Summary

I'm currently on refactoring the old `pdns_record` module from @Nosmoht (see [Nosmoht/ansible-module-powerdns][1]) to be compliant with PowerDNS v4 API.

ATM it resides in my corporate Ansible collection. I'm thinking about adding it to `community.general` collection, but I'm not sure if it's the right place.

@felixfontein what do you think about it ? Should I open a PR to add this module to the `community.general` collection ?

[1]: https://github.com/Nosmoht/ansible-module-powerdns/blob/master/powerdns_record.py

### Issue Type

Feature Idea

### Component Name

pdns_record

### Additional Information

```yaml (paste below)
- name: Create a DNS record of type A
  community.general.pdns_record:
      name: myrecord
      type: A
      content: 1.2.3.4
      zone: mycompany.com
      pdns_api_url: 'https://10.11.12.13:443'
      pdns_api_key: 'Sup3rS3cret!'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
