### ISSUE TITLE
Add option to Ansible xml module to preserve empty element tag formatting

### ISSUE THREAD

**Issue by AndriyRu** [ansible-collections/community.general#8361]
### Summary

**Summary**
This feature request proposes adding an option to the Ansible xml module that allows users to preserve the formatting of empty XML element tags (keeping open and close tags) when modifying an XML document.

**Use Case**
Some XML consumers and legacy systems require empty XML elements to maintain the full open and close tag format (<element></element>) rather than being converted to a self-closing tag (<element/>). The current behavior of the Ansible xml module, which relies on the lxml library, is to convert empty elements to self-closing tags by default during serialization.

For example, after using the xml module to modify an unrelated part of an XML document, the original tag:

`<MyTag></MyTag>`

gets serialized as:

`<MyTag/>`

This change in format can lead to issues with systems that expect or require the former format.

**Proposed Solution**
Introduce a new boolean option for the xml module, tentatively named preserve_empty_tags, which when set to True, would keep empty XML elements in their expanded form (with both an opening and a closing tag). This is akin to the short_empty_elements=False parameter available in both Python's ElementTree and lxml.etree.

**Implementation**
This new option could be implemented within the xml module's code where the final tree.write() method is called. It would conditionally include the short_empty_elements=False option based on the value of preserve_empty_tags.

**Benefits**
By enabling users to preserve XML tag formatting, this feature would improve compatibility with various XML parsers and prevent potential issues when interfacing with systems where the formatting of empty tags is significant.

**Additional Context**
The short_empty_elements option is available starting from lxml version 4.4.0, and therefore the xml module can check the installed lxml version before applying this new feature to maintain backward compatibility.

### Issue Type

Feature Idea

### Component Name

xml

### Additional Information

```
- name: Edit xml file
  hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - name: Edit xml file dynamically
      xml:
        path: "/path/to/the/file"
        xpath: /MainSettings/Store/IsOpened
        value: 'false'
        pretty_print: true
        preserve_empty_tags: true
        state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
