### ISSUE TITLE
gitlab: authenticate through api_token specified in python-gitlab configuration files

### ISSUE THREAD

**Issue by antimius** [ansible-collections/community.general#8378]
### Summary

We currently are using python-gitlab in several other python scripts and have set it up to use ~/.python-gitlab.cfg as the central source for our credentials (https://python-gitlab.readthedocs.io/en/stable/cli-usage.html#configuration-files). When using the community.general.gitlab_* modules however I have to specify the api_token explicitly. Would it be possible to try and fall back on default python-gitlab.cfg configuration when credentials are not specified?

### Issue Type

Feature Idea

### Component Name

gitlab_*

### Additional Information

```yaml
- name: Create merge request
  community.general.gitlab_merge_request:
    api_url: "{{ gitlab_url }}"
    project: "{{ gitlab_repository }}"
    source_branch: feat/{{ jira_ticket }}
    target_branch: "{{ gitlab_target_branch }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
