### ISSUE TITLE
git_config: state "absent" ignored if value is present

### ISSUE THREAD

**Issue by pappou99** [ansible-collections/community.general#8436]
### Summary

When value is present, state: absent is doing nothing, but it should:
[From Documentation:](https://docs.ansible.com/ansible/latest/collections/community/general/git_config_module.html#ansible-collections-community-general-git-config-module)
state string Indicates the setting should be set/unset. This parameter has higher precedence than [value]

### Issue Type

Bug Report

### Component Name

git_config

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.11]
  config file = /home/xxx/src/xxx/xxx/xxx/xxx/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/xxx/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 9.0.1  

# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.2  

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```
---
- name: Debug
  hosts: localhost
  tasks:
    - name: "Check version of community.general"
      ansible.builtin.debug:
        msg: "community.general version {{ lookup('community.general.collection_version', 'community.general') }}"


    - name: "Add false git config user.name"
      git_config:
        name: item.name
        value: "fancy_username"
        scope: global
        state: present


    - name: "Add false git config user.email"
      git_config:
        name: item.email
        value: "test@example.org"
        scope: global
        state: present


    - name: "Remove false git config item.name (not working, bacause of 'value')"
      git_config:
        name: item.name
        value: "fancy_username"
        scope: global
        state: absent


    - name: "Remove false git config item.email (not working, bacause of 'value')"
      git_config:
        name: item.email
        value: "test@example.org"
        scope: global
        state: absent


    - name: "Remove false git config item.name (working, bacause soloed 'state: absent')"
      git_config:
        name: item.name
        scope: global
        state: absent


    - name: "Remove false git config item.email (working, bacause soloed 'state: absent')"
      git_config:
        name: item.email
        scope: global
        state: absent


```

### Expected Results

Remove false git config also when value is present (See example playbook in Steps to Reproduce)

### Actual Results

False git config is not removed (See example playbook in Steps to Reproduce)
```
ansible-playbook community_bug.yml 

PLAY [Debug] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Check version of community.general] **********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "community.general version 9.0.1"
}

TASK [Add false git config user.name] **************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Add false git config user.email] *************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Remove false git config item.name (not working, bacause of 'value')] *************************************************************************************************************************************************************
ok: [localhost]

TASK [Remove false git config item.email (not working, bacause of 'value')] ************************************************************************************************************************************************************
ok: [localhost]

TASK [Remove false git config item.name (working, bacause soloed 'state: absent')] *****************************************************************************************************************************************************
changed: [localhost]

TASK [Remove false git config item.email (working, bacause soloed 'state: absent')] ****************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
localhost               : ok=8    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
