### ISSUE TITLE
Add filter remove_keys

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#8442]
### Summary

Create filter remove_keys.

The collection ansible.utils provides the filter [remove_keys](https://github.com/ansible-collections/ansible.utils/blob/main/plugins/filter/remove_keys.py). Unfortunately, it is not working properly. See [remove_keys filter remove empty string from list #247](https://github.com/ansible-collections/ansible.utils/issues/247).

There is already feature request #8438 and PR #8456 to add filter keep_keys. This filter will be an easy complement. The goal is to keep the code simple and test it properly.

### Issue Type

Feature Idea

### Component Name

community.genera.remove_keys

### Additional Information

```yaml
  t: [k0, k1]
  l1:
    - {k0: A, k1: B, k2: C}
    - {k0: D, k1: E, k2: F}
  r1: "{{ l1 | community.general.remove_keys(target=t) }}"
```
gives

```yaml
  r1:
  - k2: C
  - k2: F
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
