### ISSUE TITLE
Add filter replace_keys

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#8445]
### Summary

Create filter replace_keys.

The collection ansible.utils provides the filter replace_keys along  to filters keep_kees and replace_kees. There are already feature requests #8438, #8442, and PR #8456, #8443 to implement filters keep_kees and replace_kees in this collection. See the feature requests for reasons. This filter will be an easy complement. The goal is to keep the code simple, consistent, and maintainable.

### Issue Type

Feature Idea

### Component Name

community.genera.replace_keys

### Additional Information

```yaml
  t:
    - {before: k0, after: a0}
    - {before: k1, after: a1}
  l1:
    - {k0: A, k1: B, k2: C}
    - {k0: D, k1: E, k2: F}
  r1: "{{ l1 | community.general.replace_keys(target=t) }}"
```

gives

```yaml
  r1:
    - {a0: A, a1: B, k2: C}
    - {a0: D, a1: E, k2: F}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
