### ISSUE TITLE
Ssh public Key encoding error ldap_entry

### ISSUE THREAD

**Issue by Aldenan** [ansible-collections/community.general#8469]
### Summary

Hello, 

I'm facing a new issue with the ldap_entry. I'm trying to add an ssh public key for each user, but the module doesn't accept the public key as a valid argument : 
``` yaml
- name: Retrieve LDAP user entries
  hosts: localhost
  vars:
    ssh_public: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMgVEBiCTYCH+SVjhO5KgobxioYJeH5sy3W0TMlbRr209DsYz9yM3Tt2Brto+/isIJmesXzI28aGBH//dZLm2bae+rY9mzfY8/CoV3a2mLmqjwQXAy0gw55frD+C6FHIAAuCKrtMe5BqcX9T6aVYMnXjiLd5tpIweEKFsrQnC6qbZuSb9e/xElzGWASWAoV4IBlT9GqX6DyWXBxqxodOrEkbc7c7QCG9dwQsFVyD+6dVLSSFIXVY86865WH55cQLt8F0qyMYLEdAERMk7uqCeQTvBRAo5qnaFZi6EwOckWaQWz6RUW3xidt8Z1ZeTcBGgqHTXe2DWJrp0cuWYCwsNL rsa-key-20240606"
  gather_facts: no
  
  tasks:
    - name: Add user
      community.general.ldap_entry:
        dn: CN=user6,OU=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX
        objectClass:
          - user
          - posixAccount
          - top
        attributes:
          cn: user6
          gidNumber: 10010
          uidNumber: 10100
          uid: 10100
          loginShell: /usr/sbin/nologin
          homeDirectory: /dir1
          altSecurityIdentitites: "{{ssh_public}}"
        state: present
        server_uri: ldap://example.be:11389
        bind_dn: CN=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX
        bind_pw: "XXXXXXXXXXXX"
```

### Issue Type

Bug Report

### Component Name

ldap_entry

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.1] 
  config file = /home/smals-alade/sftp_code/ansible.cfg
  configured module search path = ['/home/smals-alade/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/smals-alade/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/smals-alade/venvs/ansible/bin/ansible
  python version = 3.6.8 (default, Jan  5 2024, 08:58:17) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/smals-alade/venvs/ansible/lib/python3.6/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.2.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/smals-alade/.vault
```

### OS / Environment

Playbook launched from RHEL8 to Windows Server 2022 (AD LDS)

### Steps to Reproduce

```yaml (paste below)
- name: Retrieve LDAP user entries
  hosts: localhost
  vars:
    ssh_public: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMgVEBiCTYCH+SVjhO5KgobxioYJeH5sy3W0TMlbRr209DsYz9yM3Tt2Brto+/isIJmesXzI28aGBH//dZLm2bae+rY9mzfY8/CoV3a2mLmqjwQXAy0gw55frD+C6FHIAAuCKrtMe5BqcX9T6aVYMnXjiLd5tpIweEKFsrQnC6qbZuSb9e/xElzGWASWAoV4IBlT9GqX6DyWXBxqxodOrEkbc7c7QCG9dwQsFVyD+6dVLSSFIXVY86865WH55cQLt8F0qyMYLEdAERMk7uqCeQTvBRAo5qnaFZi6EwOckWaQWz6RUW3xidt8Z1ZeTcBGgqHTXe2DWJrp0cuWYCwsNL rsa-key-20240606"
  gather_facts: no
  
  tasks:
    - name: Add user
      community.general.ldap_entry:
        dn: CN=user6,OU=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX
        objectClass:
          - user
          - posixAccount
          - top
        attributes:
          cn: user6
          gidNumber: 10010
          uidNumber: 10100
          uid: 10100
          loginShell: /usr/sbin/nologin
          homeDirectory: /dir1
          altSecurityIdentitites: "{{ssh_public}}"
        state: present
        server_uri: ldap://example.be:11389
        bind_dn: CN=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX
        bind_pw: "XXXXXXXXXXXX"
```

### Expected Results

The LDAP object is created in the AD LDS, with all the feed populated correctly including : altSecurityIdentitites: with the public ssh used in the playbook

### Actual Results

```console (paste below)
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.general.ldap_entry_payload_3fvknf8z/ansible_community.general.ldap_entry_payload.zip/ansible_collections/community/general/plugins/modules/ldap_entry.py", line 212, in main
  File "/tmp/ansible_community.general.ldap_entry_payload_3fvknf8z/ansible_community.general.ldap_entry_payload.zip/ansible_collections/community/general/plugins/modules/ldap_entry.py", line 150, in _add
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/ldapobject.py", line 430, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/ldapobject.py", line 416, in add_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/ldapobject.py", line 751, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/ldapobject.py", line 758, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/home/smals-alade/venvs/ansible/lib64/python3.6/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.NO_SUCH_ATTRIBUTE: {'desc': 'No such attribute', 'info': '00000057: LdapErr: DSID-0C0910D5, comment: Error in attribute conversion operation, data 0, v4f7c'}
fatal: [localhost]: FAILED! => {
    "changed": false,
    "details": "{'desc': 'No such attribute', 'info': '00000057: LdapErr: DSID-0C0910D5, comment: Error in attribute conversion operation, data 0, v4f7c'}",
    "invocation": {
        "module_args": {
            "attributes": {
                "altSecurityIdentitites": [
                    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMgVEBiCTYCH+SVjhO5KgobxioYJeH5sy3W0TMlbRr209DsYz9yM3Tt2Brto+/isIJmesXzI28aGBH//dZLm2bae+rY9mzfY8/CoV3a2mLmqjwQXAy0gw55frD+C6FHIAAuCKrtMe5BqcX9T6aVYMnXjiLd5tpIweEKFsrQnC6qbZuSb9e/xElzGWASWAoV4IBlT9GqX6DyWXBxqxodOrEkbc7c7QCG9dwQsFVyD+6dVLSSFIXVY86865WH55cQLt8F0qyMYLEdAERMk7uqCeQTvBRAo5qnaFZi6EwOckWaQWz6RUW3xidt8Z1ZeTcBGgqHTXe2DWJrp0cuWYCwsNL rsa-key-20240606"
                ],
                "cn": "user6",
                "gidNumber": 10010,
                "homeDirectory": "/dir1",
                "loginShell": "/usr/sbin/nologin",
                "objectClass": [
                    "user",
                    "posixAccount",
                    "top"
                ],
                "uid": 10100,
                "uidNumber": 10100
            },
            "bind_dn": "CN=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX",
            "bind_pw": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "dn": "CN=user6,OU=XXXXX,OU=XXXXX,DC=XXXXX,DC=XXXXX",
            "objectClass": [
                "user",
                "posixAccount",
                "top"
            ],
            "referrals_chasing": "anonymous",
            "sasl_class": "external",
            "server_uri": "ldap://example.be:11389",
            "start_tls": false,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "Entry action failed."
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
