### ISSUE TITLE
Flatpak Install specific commit

### ISSUE THREAD

**Issue by darkdecoy** [ansible-collections/community.general#8472]
### Summary

It would be helpful at times to have ansible install and specific commit of a flatpak.

### Issue Type

Feature Idea

### Component Name

flatpak

### Additional Information

```yaml (paste below)
- name: Update the Gnome Calendar flatpak to specific commit 
  community.general.flatpak:
    name: org.gnome.Calendar
    commit: "46d19e841fb6867b6269166182bc97e49fdc746425d2f5895ee1d2c6f42167b2"
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
