### ISSUE TITLE
Parted won't resize in use partition

### ISSUE THREAD

**Issue by Overmorrow1501** [ansible-collections/community.general#8481]
### Summary

When I try to extend a partition in use while using community.general.parted I get errors stating the partition is in use and doesn't let me proceed ending the playbook with errors

### Issue Type

Bug Report

### Component Name

community.general.parted

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/moro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/moro/library/molecule_ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/moro/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/moro/library/molecule_ansible/bin/ansible
  python version = 3.11.9 (main, Apr 18 2024, 16:44:43) [GCC] (/home/moro/library/molecule_ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 9.0.1  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

CONFIG_FILE() = /etc/ansible/ansible.cfg
PAGER(env: PAGER) = less


```

### OS / Environment

Ubuntu 24.04 LTS
KERNEL =  6.8.0-35-generic
parted -3.6-4build1 

### Steps to Reproduce

```yaml (paste below)

vars:

  vm_internal_ls_dict: [
              {
                  "device": "/dev/sda",
                  "fs_type": "xfs",
                  "label": "gpt",
                  "lvm": "no",
                  "mount_point": "/",
                  "part": 2,
                  "part_end": "100%",
                  "resize": true,
                  "resizefs": true
              }
          ]


tasks:
  - name: Check if parted is >= 3.4.64 # https://github.com/ansible-collections/community.general/pull/7304
    ansible.builtin.set_fact:
      parted_is_newest: "{{ ansible_facts['packages']['parted'][0]['version']  is version('3.4.64', '>=') }}"
      

  - name: Create disk partition
    community.general.parted:
      device: "{{ item.device }}"
      number: "{{ item.part }}"
      flags: "{{ item.flags | default(omit) }}"
      label: "{{ item.label | default('msdos') }}"
      state: "present"
      part_start: "{{ item.part_start | default(omit) }}"
      part_end: "{{ item.part_end | default(omit) }}"
      resize: "{{ (item.resize | default(omit)) if parted_is_newest | bool else omit }}"
    loop: "{{ vm_internal_ls_dict }}"
    loop_control:
      label: "{{ item.device }} partition {{ item.part }}"

```

### Expected Results

I'm trying to online resize /dev/sda2 partition, but i get this warning `Warning: Partition /dev/sda2 is being used. Are you sure you want to continue?` which ends in failure.

### Actual Results

```console (paste below)


failed: [ubuntu-plain] (item=/dev/sda partition 2) => {
    "ansible_loop_var": "item",
    "changed": false,
    "err": "Warning: Partition /dev/sda2 is being used. Are you sure you want to continue?\n",
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/sda",
            "flags": null,
            "fs_type": null,
            "label": "gpt",
            "name": null,
            "number": 2,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "resize": true,
            "state": "present",
            "unit": "KiB"
        }
    },
    "item": {
        "device": "/dev/sda",
        "fs_type": "xfs",
        "label": "gpt",
        "lvm": "no",
        "mount_point": "/",
        "part": 2,
        "part_end": "100%",
        "resize": true,
        "resizefs": true
    },
    "msg": "Error while running parted script: /usr/sbin/parted -s -f -m -a optimal /dev/sda -- resizepart 2 100%",
    "out": "",
    "rc": 1
}



```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/parted.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/parted.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @ColOfAbRiX @jake2184 @rosowiecki
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by gianmarco-mameli** [comment]
Hi, any news on this issue? same problem for me

**Comment by friendlypenguin** [comment]
I had this problem while resizing a disk with a gpt partition table and not specifying the label attribute of the parted module (default is msdos and so there was a mismatch).

@Overmorrow1501 when you run parted on the disk (cmdline, not through ansible), does it actually show that it has a gpt partition table?

**Comment by Overmorrow1501** [comment]
> I had this problem while resizing a disk with a gpt partition table and not specifying the label attribute of the parted module (default is msdos and so there was a mismatch).

Yes, I did. As you can see from here:

```yaml 
failed: [ubuntu-plain] (item=/dev/sda partition 2) => {
    "ansible_loop_var": "item",
    "changed": false,
    "err": "Warning: Partition /dev/sda2 is being used. Are you sure you want to continue?\n",
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/sda",
            "flags": null,
            "fs_type": null,
            "label": "gpt",
            "name": null,
            "number": 2,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "resize": true,
            "state": "present",
            "unit": "KiB"
        }
```


> @Overmorrow1501 when you run parted on the disk (cmdline, not through ansible), does it actually show that it has a gpt partition table?

Yes, again.
