### ISSUE TITLE
locale_gen Don't do anything

### ISSUE THREAD

**Issue by samikhelil83** [ansible-collections/community.general#8487]
### Summary

I'm trying to add this locale on Ubuntu 22.04 or Ubuntu 24.04 but nothing happens, the output of the command is always Changed:false.
ansible -m locale_gen -a "name=es_AR.UTF-8 state=present" localhost

### Issue Type

Bug Report

### Component Name

locale_gen

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 1.3.6  

# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 9.0.1
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None

```

### OS / Environment

ubuntu 22.02

### Steps to Reproduce

```yaml (paste below)
# ansible -m locale_gen -a "name=es_AR.UTF-8 state=present" localhost
localhost | SUCCESS => {
    "changed": false,
    "name": "es_AR.UTF-8",
    "ubuntu_mode": true
}




```

### Expected Results
```console (paste below)
# locale -a | grep es_AR 
# es_AR.utf8
```
### Actual Results

```console (paste below)
# locale -a |grep es_AR 
#
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
