### ISSUE TITLE
[nios_zone] Warnings when using zone_format parameter

### ISSUE THREAD

**Issue by donestefan** [ansible-collections/community.general#852]
##### SUMMARY
Using `zone_format: "FORWARD"` in the "nios_zone" module will cause a strange warning:
`[WARNING]: Both option zone_format and its alias zone_format are set.`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_zone

##### ANSIBLE VERSION

```paste below
 ansible 2.9.10
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT

CentOS Linux release 7.8

##### STEPS TO REPRODUCE

```yaml
- name: "create Forward Zone"
  connection: local
  nios_zone:
    provider: "{{ grid_connector }}"
    restart_if_needed: true
    name:                   "{{ zone.fqdn }}"
    ns_group:               "{{ zone.ns_group}}"
    view:                   "{{ zone.view|default('default') }}"
    state:                  "{{ zone.state|default('present') }}"
    zone_format:            "{{ zone.zone_format|default('FORWARD') }}"
```

##### ACTUAL RESULTS

playbook works as expected but gives a strange warning:

```paste below
[WARNING]: Both option zone_format and its alias zone_format are set.
```

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/net_tools/nios/nios_zone.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/nios/nios_zone.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @NilashishC @Qalthos @danielmellado @ganeshrn @justjais @nerzhul @privateip @sganesh-infoblox @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zjpeterson** [comment]
I get warnings like this when I use `nios_fixed_address` as well (on 2.9.15).

Task:
```
- name: make a host record
  nios_fixed_address:
    name: my-record-4.example.com
    ipaddr: 192.168.100.4
    network: 192.168.100.0/24
    mac: 00:00:00:00:00:00
    provider:
      host: nios.example.com
      username: admin
      password: infoblox
      validate_certs: no
```

Output:
```
TASK [make a host record] **************************************************************************************************************
[WARNING]: Both option ipaddr and its alias ipaddr are set.
[WARNING]: Both option mac and its alias mac are set.
[WARNING]: Both option network and its alias network are set.
ok: [localhost]
```

Same behavior, works as expected, but throwing warnings about aliases. Seems to me that aliases are set in the module code when they shouldn't be.
