### ISSUE TITLE
sysrc: start service

### ISSUE THREAD

**Issue by jtagcat** [ansible-collections/community.general#8544]
### Summary

```yaml
- name: Enable nginx
  community.general.sysrc:
    name: nginx_enable
    value: "YES"
```

^ Example does not ensure the service is started. I'd like to see `nginx` as the name, which both enables and (re)starts the service.

### Issue Type

Feature Idea

### Component Name

sysrc

### Additional Information

Alternative:
```yaml
  - name: 'nginx: ensure pkg'
    community.general.pkgng:
      name: nginx
      state: latest
  - name: 'nginx: enable service'
    community.general.sysrc:
      name: nginx_enable
      value: "YES"
  - name: 'nginx: start service'
    shell: service nginx start
    register: result
    changed_when: "result.rc == 0"
    failed_when: 'result.rc != 0 and (result.rc == 1 and not "already running" in result.stderr)'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/sysrc.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/sysrc.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @dlundgren
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by dlundgren** [comment]
Since this module acts as an interface for `sysrc`, I'd have to say this would be beyond the scope of this module. 

This is already supported via the `ansible.builtin.service` module for FreeBSD, and will set `nginx_enable="YES"` in `/etc/rc.conf`:
```
  - name: Ensure nginx is started & enabled
    ansible.builtin.service:
      name: nginx
      enabled: true
      state: started
```

**Comment by jtagcat** [comment]
It seems I missed it indeed. The docs for [`ansible.builtin.service`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html) nor [`community.general.sysrc`](https://docs.ansible.com/ansible/latest/collections/community/general/sysrc_module.html) did mention this. Additionally, [`ansible.builtin.systemd_service`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html) (example, from where I started) doesn't mention the (cross-platform) generic variant.

Should I reopen this as a docs issue?

**Comment by jtagcat** [comment]
Currently, unsure how I would define sysrc variables through the generic interface:

```
  - name: 'wireguard: enable wg0'
    community.general.sysrc:
      name: wireguard_interfaces
      value: "wg0"
```

Though, I am happy to use both `ansible.builtin.service` and `community.general.sysrc`.
