### ISSUE TITLE
dconf: unable to execute with become

### ISSUE THREAD

**Issue by cwchristerw** [ansible-collections/community.general#8574]
### Summary

When I try to use dconf module to change login screen settings in my Linux Mint device, it will execute dconf with wrong user even when become_user is set to lightdm. It's required to set slick greeters settings with dconf using lightdm user. I have tried to use sudosu and sudo become modules neighter of them worked I suspect that dconf isn't compatible with become modules.

### Issue Type

Bug Report

### Component Name

dconf

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.1]
  config file = /home/cwchristerw/Desktop/infra/ansible.cfg
  configured module search path = ['/home/cwchristerw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/cwchristerw/infra/collections:/home/cwchristerw/.ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/opt/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 9.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ACTION_WARNINGS(/home/cwchristerw/Desktop/infra/ansible.cfg) = False
COLLECTIONS_PATHS(/home/cwchristerw/Desktop/infra/ansible.cfg) = ['/home/cwchristerw/Desktop/infra/collections', '/home/cwchristerw/.ansible/collections']
CONFIG_FILE() = /home/cwchristerw/Desktop/infra/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/home/cwchristerw/Desktop/infra/ansible.cfg) = ['/home/cwchristerw/Desktop/infra/plugins/filters']
DEFAULT_FORCE_HANDLERS(/home/cwchristerw/Desktop/infra/ansible.cfg) = True
DEFAULT_FORKS(/home/cwchristerw/Desktop/infra/ansible.cfg) = 50
DEFAULT_GATHERING(/home/cwchristerw/Desktop/infra/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/cwchristerw/Desktop/infra/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/cwchristerw/Desktop/infra/ansible.cfg) = ['/home/cwchristerw/Desktop/infra/inventories/cwchristerw', '/home/cwchristerw/Desktop/infra/inventories/cwinfo', '/home/cwchristerw>
DEFAULT_ROLES_PATH(/home/cwchristerw/Desktop/infra/ansible.cfg) = ['/home/cwchristerw/Desktop/infra/roles']
DEFAULT_TIMEOUT(/home/cwchristerw/Desktop/infra/ansible.cfg) = 3
DISPLAY_SKIPPED_HOSTS(/home/cwchristerw/Desktop/infra/ansible.cfg) = False
HOST_PATTERN_MISMATCH(/home/cwchristerw/Desktop/infra/ansible.cfg) = ignore
INJECT_FACTS_AS_VARS(/home/cwchristerw/Desktop/infra/ansible.cfg) = False
```

### OS / Environment

Linux Mint 21.3

### Steps to Reproduce

```yaml (paste below)
- name: "Workstations : Desktop : Login Screen - Background : Draw"
  community.general.dconf:
    key: "/x/dm/slick-greeter/draw-user-backgrounds"
    value: "true"
    state: present
  become: yes
  become_user: lightdm
  when:
    - ansible_facts.distribution == "Linux Mint"
    - workstations is defined
    - workstations.desktop is defined
    - workstations.desktop.background is defined
```

### Expected Results

```console (paste below)
root@magiclantern:~$ dconf list /x/dm/slick-greeter/

root@magiclantern:~$ sudo su lightdm -s /bin/bash -c "dconf list /x/dm/slick-greeter/"
draw-user-backgrounds
```

### Actual Results

```console (paste below)
root@magiclantern:~$ dconf list /x/dm/slick-greeter/
draw-user-backgrounds

root@magiclantern:~$ sudo su lightdm -s /bin/bash -c "dconf list /x/dm/slick-greeter/"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
