### ISSUE TITLE
Bitwarden report locked status most of the time

### ISSUE THREAD

**Issue by jeankhawand** [ansible-collections/community.general#8593]
### Issue with Bitwarden CLI Behavior in Python Subprocess

When investigating the `bitwarden.py` script, it becomes evident that the vault status is fetched using the following code snippet:

```python
p = Popen([self.cli_path] + args, stdout=PIPE, stderr=PIPE, stdin=PIPE)
out, err = p.communicate(to_bytes(stdin))
```

Despite this approach, the observed output often differs from expectations when compared to running equivalent commands directly in the terminal:

Terminal Command:

```console
bw status --session 'tbnsIErhp5W8eud+5Th0ftGimGOrdGtlgaZA=='
Returns status unlocked
```

Python REPL Command:

```python
from subprocess import Popen, PIPE

try:
    p = Popen(['bw', 'status', '--session', 'tbnsIErhp5W8eud+5Th0ftGimGOrdGtlgaZA=='], stdout=PIPE, stderr=PIPE, stdin=PIPE)
    out, err = p.communicate()
    print(out.decode().strip())
    print(err.decode().strip())
except Exception as e:
    print(f"Exception occurred: {str(e)}")

```
Returns locked, even when the vault is confirmed to be unlocked.

Possible Causes and Considerations:
1. Session Persistence:
Bittwarden CLI sessions might behave differently when initiated from a subprocess compared to a direct terminal session. This can sometimes lead to discrepancies in session state.
2. Concurrency and Limits:
Verify if there are any limitations in the Bitwarden CLI version you are using regarding concurrent sessions or operations. Some versions may impose limits that affect how sessions are managed or authenticated.

Current Status: I am looking into bitwarden/clients status command but still didn't find anything relevant to session

### Issue Type

Bug Report

### Component Name

bitwarden

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.4]
  config file = None
  configured module search path = ['/Users/jeankhawand/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jeankhawand/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Nov  2 2023, 04:39:40) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = False
```

### Community.general Version

```console 
$ ansible-galaxy collection list community.general

# /Users/jeankhawand/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 9.1.0  

# /opt/homebrew/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.4.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

MacOS Sonoma 14.4
bw-cli 2022.11.0
### Steps to Reproduce

```yaml (paste below)
---
- name: Fetch Bitwarden credentials by folder and variable name
  hosts: localhost
  tasks:
    - name: Set BW_SESSION variable
      set_fact:
        bw_session: "tbnsIErhp5W8eud+5Th0ftGimGOrdGtlgaZA=="

    - name: Debug BW_SESSION value
      debug:
        msg: "BW_SESSION is set to '{{ bw_session }}'"

    - name: "Get 'name' field from Bitwarden record 'miniflux'"
      ansible.builtin.debug:
        msg: >-
          {{ lookup('community.general.bitwarden', 'token', field='name', bw_session=bw_session) }}

```

### Expected Results

I should expect getting the entry name

### Actual Results

```console
exception during Jinja2 execution: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/ansible/template/__init__.py", line 865, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeankhawand/.ansible/collections/ansible_collections/community/general/plugins/lookup/bitwarden.py", line 231, in run
    raise AnsibleError("Bitwarden Vault locked. Run 'bw unlock'.")
ansible.errors.AnsibleError: Bitwarden Vault locked. Run 'bw unlock'.
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'community.general.bitwarden'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Bitwarden Vault locked. Run 'bw unlock'.. Bitwarden Vault locked. Run 'bw unlock'."
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
