### ISSUE TITLE
Create a filter and a test to reveal/validate Ansible data types.

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#8594]
### Summary

Advanced filter and test to reveal/validate Ansible data types are missing. Create a filter and test with the functionality similar to [ typing.reveal_type](https://docs.python.org/3/library/typing.html#typing.reveal_type). Especially the composite data types, e.g. *list[int|str],  list[dict], dict[str, int], ...* would simplify data validation and selection.

### Issue Type

Feature Idea

### Component Name

community.general.reveal_ansible_type, community.general.ansible_type

### Additional Information

As a use case, there is an open PR #8571 to keep keys in a list of dictionaries recursively. Given the target and (simplified) data

```yaml
    target: [key, other]
    data:
      - nm: first
        ld:
          - {key: 1, other: other1, foo: bar}
          - {key: 2, other: other2, foo: bar}
      - nm: second
        ld:
          - {key: 3, other: other3, foo: bar}
          - {key: 4, other: other4, foo: bar}
```

the result should be

```yaml
  result:
    - ld:
      - {key: 1, other: other1}
      - {key: 2, other: other2}
    - ld:
      - {key: 3, other: other3}
      - {key: 4, other: other4}
```

Using the proposed test *community.general.ansible_type* the data can be easily selected

```yaml
    sel: "{{ data | map('dict2items') |
             map('selectattr', 'value', 'community.general.ansible_type', 'list[dict]') |
             flatten }}"
```
gives

```yaml
  sel:
    - key: ld
      value:
      - {foo: bar, key: 1, other: other1}
      - {foo: bar, key: 2, other: other2}
    - key: ld
      value:
      - {foo: bar, key: 3, other: other3}
      - {foo: bar, key: 4, other: other4}
```
Then, iterate the list and transform the items. For example

```yaml
    result: |
      {% filter from_yaml %}
      {% for i in sel %}
      - {{ i.key }}: {{ i.value|community.general.keep_keys(target=target) }}
      {% endfor %}
      {% endfilter %}
```
gives the required result

```yaml
  result:
    - ld:
      - {key: 1, other: other1}
      - {key: 2, other: other2}
    - ld:
      - {key: 3, other: other3}
      - {key: 4, other: other4}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
