### ISSUE TITLE
FreeBSD. Add option use_globs to the module pkgng.

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#8632]
### Summary

The utility *pkg* command *upgrade* provides option *-g, --glob*

> Treat the package names as shell glob patterns.

The package can be in the form

> <pkg-origin|pkg-name|pkg-name-version>

The module *community.general.pkgng* shall upgrade a package if *state=latest*. This doesn't work when the package is in the form *pkg-origin*. The reason is the hard-coded option *-g* in *community.general.pkgng*

```yaml
- community.general.pkgng:
    name: security/py-openssl
    state: latest
```

fails because *-g* "*treats the package names ...*" this means the form *pkg-name*

```yaml
fatal: [ca]: FAILED! => changed=false 
  msg: failed to upgrade security/py-openssl
  stderr: |-
    pkg: No packages available to upgrade matching 'security/py-cryptography' have been found in the repositories
  stderr_lines: <omitted>
  stdout: |-
    Updating FreeBSD repository catalogue...
    FreeBSD repository is up to date.
    All repositories are up to date.
  stdout_lines: <omitted>
```
This can be reproduced from the command line on the remote host

```bash
shell> pkg upgrade -n -g security/py-openssl
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to upgrade matching 'security/py-openssl' have been found in the repositories
```

The form *pkg-name* works fine. For example, in the case *py39-openssl* is installed

```bash
shell> pkg info security/py-openssl
py39-openssl-23.2.0,1
Name           : py39-openssl
Version        : 23.2.0,1
Installed on   : Wed Jun 12 13:04:52 2024 CEST
Origin         : security/py-openssl
Architecture   : FreeBSD:14:*
```

the below command finds the latest package *py39-openssl* installed

```bash
shell> pkg upgrade -n -g py39-openssl
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
Your packages are up to date.
```

You can ask *pkg* to upgrade to the latest package in the form *pkg-origin* (without the option *-g*)

```bash
shell> pkg upgrade -n security/py-openssl
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py311-openssl: 23.2.0,1
	py311-setuptools: 63.1.0_1

Number of packages to be installed: 2

The process will require 12 MiB more space.
2 MiB to be downloaded.
```

Conclusion: Make the option '-g, --glob' optional.

### Issue Type

Feature Idea

### Component Name

community.general.pkgng

### Additional Information

```yaml
    - community.general.pkgng:
        name: security/py-openssl
        state: latest
        use_globs: false
      register: result
    - debug:
        var: result
```

gives

```yaml
ok: [ca] => 
  result:
    changed: true
    failed: false
    msg: upgraded 1 package
    stderr: ''
    stderr_lines: []
    stdout: |-
      Updating FreeBSD repository catalogue...
      FreeBSD repository is up to date.
      All repositories are up to date.
      The following 2 package(s) will be affected (of 0 checked):
  
      New packages to be INSTALLED:
              py311-openssl: 23.2.0,1
              py311-setuptools: 63.1.0_1
  
      Number of packages to be installed: 2
  
      The process will require 12 MiB more space.
      2 MiB to be downloaded.
      [1/2] Fetching py311-setuptools-63.1.0_1.pkg: .......... done
      [2/2] Fetching py311-openssl-23.2.0,1.pkg: ....... done
      Checking integrity... done (0 conflicting)
      [1/2] Installing py311-setuptools-63.1.0_1...
      [1/2] Extracting py311-setuptools-63.1.0_1: .......... done
      [2/2] Installing py311-openssl-23.2.0,1...
      [2/2] Extracting py311-openssl-23.2.0,1: .......... done
    stdout_lines:
    - Updating FreeBSD repository catalogue...
    - FreeBSD repository is up to date.
    - All repositories are up to date.
    - 'The following 2 package(s) will be affected (of 0 checked):'
    - ''
    - 'New packages to be INSTALLED:'
    - "\tpy311-openssl: 23.2.0,1"
    - "\tpy311-setuptools: 63.1.0_1"
    - ''
    - 'Number of packages to be installed: 2'
    - ''
    - The process will require 12 MiB more space.
    - 2 MiB to be downloaded.
    - '[1/2] Fetching py311-setuptools-63.1.0_1.pkg: .......... done'
    - '[2/2] Fetching py311-openssl-23.2.0,1.pkg: ....... done'
    - Checking integrity... done (0 conflicting)
    - '[1/2] Installing py311-setuptools-63.1.0_1...'
    - '[1/2] Extracting py311-setuptools-63.1.0_1: .......... done'
    - '[2/2] Installing py311-openssl-23.2.0,1...'
    - '[2/2] Extracting py311-openssl-23.2.0,1: .......... done'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
