### ISSUE TITLE
pipx: Need a way to specify pipx parameters

### ISSUE THREAD

**Issue by sieberst** [ansible-collections/community.general#8656]
### Summary

I want to install two different versions of conan (conan 1.x and conan 2.x) in parallel via pipx by renaming the binary of the conan 2 installation as "conan2". This can be done with the pipx parameter "--suffix 2", but there is currently no way to supply such pipx parameters in the Ansible task. So we need 'pipx_args' similar to the existing 'pip_args'.

### Issue Type

Feature Idea

### Component Name

pipx

### Additional Information

```yaml (paste below)
    - name: Install conan 2 as conan2 with pipx
      community.general.pipx:
        name: conan
        pipx_args: "--suffix 2"

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
