### ISSUE TITLE
ipa_user

### ISSUE THREAD

**Issue by LennertMertens** [ansible-collections/community.general#8673]
### Summary

I am adding users to IDM using the ipa_user module from the community.general collection. It would be very handy if we can add subordinate IDs to the user account with this module as well. Currently I don't see any option to set the subid range with a user. 

### Issue Type

Feature Idea

### Component Name

ipa_user

### Additional Information

```yaml (paste below)
- name: Ensure pinky is present and using one time password and RADIUS authentication
  community.general.ipa_user:
    name: pinky
    state: present
    subids:
      enabled: yes
      start: 1982000 # if range is not defined, the ipa provider will automatically assign a range
      end: 200000
    ipa_host: ipa.example.com
    ipa_user: admin
    ipa_pass: topsecret
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
