### ISSUE TITLE
locale_gen allow configuring multiple locales

### ISSUE THREAD

**Issue by MatthiasKunnen** [ansible-collections/community.general#8677]
### Summary

The [locale_gen](https://docs.ansible.com/ansible/latest/collections/community/general/locale_gen_module.html) module currently allows for a single locale to be configured at a time. Using a `loop` here isn't the most efficient because both the detection of the current state and the generation of the locale after change needs to be run for every locale. If there are no objections, I would like to add the ability to configure multiple at the same time.

Regarding implementation, to avoid breaking changes, I would add a names parameter and keep the existing one. Is the best practice for Ansible?

### Issue Type

Feature Idea

### Component Name

locale_gen

### Additional Information

```yaml
- name: Set and generate locale
  community.general.locale_gen:
    names:
      - de_CH.UTF-8
      - en_US.UTF-8
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
