### ISSUE TITLE
Cannot add SRV records with cloudflare_dns

### ISSUE THREAD

**Issue by saltydk** [ansible-collections/community.general#8679]
### Summary

Adding SRV records appear to be broken, guessing this is related https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#name-related-data-fields-on-srv-dns-records

### Issue Type

Bug Report

### Component Name

cloudflare_dns

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /srv/ansible/venv/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/srv/ansible/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 9.1.0
```

### Steps to Reproduce

```yaml (paste below)
- name: Create an SRV record _foo._tcp.example.net
  community.general.cloudflare_dns:
    domain: example.net
    service: foo
    proto: tcp
    port: 3500
    priority: 10
    weight: 20
    type: SRV
    value: fooserver.example.net
```

### Expected Results

Added SRV record

### Actual Results

```console (paste below)
{"changed": false, "msg": "API bad request; Status: 400; Method: POST: Call: /zones/zoneid/dns_records"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
