### ISSUE TITLE
ZFS tries to change immutable attributes

### ISSUE THREAD

**Issue by Legogris** [ansible-collections/community.general#868]
##### SUMMARY

Module `zfs` tries to set immutable attributes like `volblocksize`. Seems to be a regression, see [ansible/ansible-modules-extras#769](https://github.com/ansible/ansible-modules-extras/issues/769) and [ansible/ansible-modules-extras#1378](https://github.com/ansible/ansible-modules-extras/pull/1378)
##### ISSUE TYPE

    * Bug Report

##### COMPONENT NAME

zfs
##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/.ansible_vault_password.txt
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'k8s', u'host_list', u'script', u'yaml', u'ini', u'constructed']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian GNU/Linux 9.9 (Stretch)
##### STEPS TO REPRODUCE

```yaml
- name: "Create zvol"
  zfs:
    name: mypool/folder/myzvol
    state: present
    extra_zfs_properties:
      volsize: '10G'
      volblocksize: 128K
```

##### EXPECTED RESULTS

Module `zfs` should not try to set immutable attributes like `volblocksize` on existing fileystems/volumes.
##### ACTUAL RESULTS

```
fatal: [nodename]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "createparent": null,
            "extra_zfs_properties": {
                "volblocksize": "128K",
                "volsize": "10G"
            },
            "name": "mypool/folder/myzvol",
            "origin": null,
            "state": "present"
        }
    },
    "msg": "cannot set property for 'mypool/folder/myzvol: 'volblocksize' is readonly\n"
}
```

Similarly with `encryption`:

```yaml
            extra_zfs_properties:
              encryption: aes-256-gcm
              keyformat: passphrase
              keylocation: file:///tmp/zfs-pass
              mountpoint: legacy
```

```
fatal: [barbican]: FAILED! => {"changed": false, "msg": "cannot set property for 'barbican/nixos': 'encryption' is readonly\n"}
```

cf https://github.com/ansible/ansible/issues/58759 https://github.com/ansible/ansible/issues/29422
