### ISSUE TITLE
pipx: Add support for --global parameter

### ISSUE THREAD

**Issue by gaby** [ansible-collections/community.general#8705]
### Summary

Since `pipx` v1.6.0 the `--global`argument was added which helps to execute actions in global scope which exposes the app to all system users. By default the global binary location is set to `/usr/local/bin`. This is great for systems that have multiple users that will use the same CLI applications. For example `ansible` itself.

Note:
- This requires pipx `v1.6.0` or higher.
- This param is also not supported on windows.
Documentation about `--global` is here: https://pipx.pypa.io/stable/installation/#global-installation
Commands that support `--global` can be found here: https://pipx.pypa.io/stable/docs/

### Issue Type

Feature Idea

### Component Name

pipx

### Additional Information

Example
```yaml
    - name: Install ansible as a global package to all users
      community.general.pipx:
        name: ansible
        global: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
