### ISSUE TITLE
Deprecate homebrew_cask?

### ISSUE THREAD

**Issue by johnbyrneio** [ansible-collections/community.general#8709]
### Summary

Since `brew cask` has been deprecated for a few years now. Should the `homebrew_cask` module also be deprecated?

I recently started to automate my macOS setup with Ansible, and was using both the `homebrew` and `hombrew_cask` modules. I used both assuming that `homebrew_cask` was the only way to explicitly request a cask at install and to perform a greedy upgrade.

I just realized that I can do the same with the `homebrew` module by passing `cask` and `greedy` to `install_options` and `upgrade_options`.

Before that realization, I submitted #8708 to fix a bug in `homebrew_cask`, and was considering addressing #7436. Now I'm wondering if it's worth the effort.

Something like this could be easily implemented in the `homebrew` module to make it easier to set the most common cask options:

```
- name: Install Homebrew cask (force cask)
  community.general.homebrew:
    name: iterm2
    force_cask: true
    state: present

- name: Upgrade Homebrew casks (force cask, enable greedy)
  community.general.homebrew:
    upgrade_all: true
    force_cask: true
    greedy: true
```

### Issue Type

Feature Idea

### Component Name

homebrew_cask

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
