### ISSUE TITLE
Cannot limit packages for copr

### ISSUE THREAD

**Issue by ossman** [ansible-collections/community.general#8738]
### Summary

When adding a copr repository, you generally want it for some specific thing. Therefore, it's prudent to limit DNF to only grab those specific packages from that repository and not get surprises in case the repository gets new things in the future.

Right now, that is very annoying with the copr module. It doesn't have that feature, which is fine as you can pair it with a ini_file task right after. However, the copr module resets the configuration and removes those changes every time it is run. So your ansible run is constantly considering those tasks changed.

### Issue Type

Feature Idea

### Component Name

copr

### Additional Information

```yaml (paste below)
- name: add shorewall copr
  community.general.copr:
    name: ufven/epel9-extras
    state: enabled
    chroot: epel-9-x86_64

- name: limit shorewall copr
  ini_file:
    path: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:ufven:epel9-extras.repo
    section: copr:copr.fedorainfracloud.org:ufven:epel9-extras
    option: includepkgs
    value: "shorewall*"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
