### ISSUE TITLE
keycloak_client: token based access issue

### ISSUE THREAD

**Issue by unbreakabl3** [ansible-collections/community.general#8829]
### Summary

Following the documentation [here](https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_client_module.html#ansible-collections-community-general-keycloak-client-module), it is possible to use an access token instead of username and password. No matter what I am doing, I am always getting that error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "parameters are required together: auth_realm, auth_username, auth_password"}
```

It is forcing to provide a username and password. Is there something I am doing wrong?
The task:
```
- name: Create Keycloak Client
  community.general.keycloak_client:
    auth_client_id: "{{ kc_auth_client_id }}"
    auth_keycloak_url: "{{ kc_url }}"
    auth_realm: "{{ kc_auth_realm }}"
    token: "{{ keycloak_jwt_access_token }}"
    state: present
    realm: "{{ kc_auth_realm }}"
    client_id: "{{ kc_client_id }}"
  delegate_to: localhost
```

### Issue Type

Documentation Report

### Component Name

keycloak_client

### Ansible Version

```console (paste below)
$ ansible --version
core 2.17.3
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
# /opt/homebrew/Cellar/ansible/10.3.0/libexec/lib/python3.12/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 9.3.0
```

### OS / Environment

MacOS

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
