### ISSUE TITLE
postgresql_privs always adds USAGE ON TYPES to the default privileges

### ISSUE THREAD

**Issue by gsauthof** [ansible-collections/community.general#884]
##### SUMMARY

When adding a default privilege ON TABLES with postgresql_privs it always adds another default USAGE privilege ON TYPES.

The main point of the `USAGE ON TYPES` privilege is to allow/disallow creating a dependency on types. Thus, it's unfortunate that this module silently and unconditionally adds this grant to the default privileges.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_privs

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /home/gms/program/linode/ansible.cfg
  configured module search path = ['/home/juser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.8 (default, Jul  1 2020, 15:39:07) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 31, ansible-2.9.11-1.fc31.noarch

##### STEPS TO REPRODUCE

```yaml
- name: check privs
  postgresql_privs:
      db: fubardb
      schema: public
      type: default_privs
      objs: TABLES
      privs: SELECT
      target_roles: import_user
      role: frontend_user
  become: yes
  become_user: postgres
```

##### EXPECTED RESULTS

That the postgresql_privs modules executes the following statements, or similar:

```
ALTER DEFAULT PRIVILEGES FOR ROLE "import_user" IN SCHEMA public REVOKE ALL ON TABLES FROM "frontend_user";
ALTER DEFAULT PRIVILEGES FOR ROLE "import_user" IN SCHEMA public GRANT SELECT ON TABLES TO "frontend_user";
```

##### ACTUAL RESULTS

```paste below
ALTER DEFAULT PRIVILEGES FOR ROLE "import_user" IN SCHEMA public REVOKE ALL ON TABLES FROM "frontend_user";
ALTER DEFAULT PRIVILEGES FOR ROLE "import_user" IN SCHEMA public GRANT SELECT ON TABLES TO "frontend_user";
ALTER DEFAULT PRIVILEGES FOR ROLE "import_user" IN SCHEMA public GRANT USAGE ON TYPES TO "frontend_user"
```

Note the appended ALTER statement that adds GRANT USAGE ON TYPES to the default privilege set.

Current main branch currently still has code that unconditionally appends this default privilege:

https://github.com/ansible-collections/community.general/blob/2b0879cdc4db1fba684acfe1f6d447285b8e979b/plugins/modules/database/postgresql/postgresql_privs.py#L896-L903
