### ISSUE TITLE
postgresql_privs commits when nothing changed

### ISSUE THREAD

**Issue by gsauthof** [ansible-collections/community.general#885]
##### SUMMARY

I understand that postgresql_privs checks whether something changed by always executing REVOKE ALL followed by the requested GRANT/REVOKE ALTER statements and then comparing the result sets of selects against some postgres `pg_*` catalog tables before and after.

AFAICS, (if not in check mode) it unconditionally commits the transaction then, even if it detected that nothing has changed (and thus the `changed` module return value is set to `False`).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_privs

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /home/gms/program/linode/ansible.cfg
  configured module search path = ['/home/juser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.8 (default, Jul  1 2020, 15:39:07) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 31, ansible-2.9.11-1.fc31.noarch

##### STEPS TO REPRODUCE

Execute some task that adds privileges two times, such that the second time the task is green (i.e. it reports nothing changed).

For example:

```yaml
- name: check privs
  postgresql_privs:
      db: fubardb
      schema: public
      type: default_privs
      objs: TABLES
      privs: SELECT
      target_roles: import_user
      role: frontend_user
  become: yes
  become_user: postgres
```

##### EXPECTED RESULTS

Transaction is rolled back.

##### ACTUAL RESULTS

Transaction is committed.

```paste below

```

This is the single location where commit is conditionally invoked:

https://github.com/ansible-collections/community.general/blob/2b0879cdc4db1fba684acfe1f6d447285b8e979b/plugins/modules/database/postgresql/postgresql_privs.py#L1105-L1109

Basically I'm proposing to change that to something like this:

```python
    if module.check_mode or changed == False:
        conn.rollback()
    else:
        conn.commit()
    module.exit_json(changed=changed, queries=executed_queries)
```
