### ISSUE TITLE
community.general.snmp_facts support for pysnmp verison older then 4

### ISSUE THREAD

**Issue by zdudic** [ansible-collections/community.general#8852]
### Summary

When using pysnmp v7, the module community.general.snmp_facts fails with the error:  

`ModuleNotFoundError: No module named pysnmp.entity.rfc3413.oneliner`

### Issue Type

Bug Report

### Component Name

snmp_facts

### Ansible Version

```
ansible [core 2.12.10]
python version = 3.10.4 (main, Jan  6 2023, 13:52:42) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11.1.0.1)]
jinja version = 3.1.4
  ```

### Community.general Version

```console (paste below)
$ Collection        Version
----------------- -------
community.general 8.6.0

```

### Configuration

```console (paste below)
COLLECTIONS_PATHS(/z/.ansible.cfg) = ['/z/python']
COLOR_ERROR(/z/.ansible.cfg) = red
COLOR_VERBOSE(/z/.ansible.cfg) = white
COLOR_WARN(/z/.ansible.cfg) = bright purple
DEFAULT_GATHERING(/z/.ansible.cfg) = explicit
DEFAULT_LOAD_CALLBACK_PLUGINS(/z/.ansible.cfg) = True
DEFAULT_LOG_PATH(/z/.ansible.cfg) = /tmp/ansible.log
DEFAULT_ROLES_PATH(/z/.ansible.cfg) = ['/z/ansible-local/oci-misc/roles, /z/roles
DEFAULT_TIMEOUT(/z/.ansible.cfg) = 30
DEPRECATION_WARNINGS(/z/.ansible.cfg) = False
HOST_KEY_CHECKING(/z/.ansible.cfg) = False
INTERPRETER_PYTHON(/z/.ansible.cfg) = auto_silent
INVENTORY_ENABLED(/z/.ansible.cfg) = ['oracle.oci.oci', 'nmap', 'host_list', 'script', 'yaml', 'ini']


```

### OS / Environment

RHEL 7

### Steps to Reproduce

```
- name: Gather SNMP v3 facts
  delegate_to: localhost
  community.general.snmp_facts:
    host: "{{ hostname }}"
    version: v3
    level: authPriv
    integrity: sha
    privacy: aes
    username: "{{ user }}"
    authkey: "{{ authpasswd }}"
    privkey: "{{ privpasswd. }}"
    retries: 2
  
  register: _snmp_facts

```

### Expected Results

I expect above task not to fail.

### Actual Results

It fails with error
```console (paste below)
"ModuleNotFoundError: No module named pysnmp.entity.rfc3413.oneliner".
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
