### ISSUE TITLE
Flush in-process SELinux file context cache

### ISSUE THREAD

**Issue by gsauthof** [ansible-collections/community.general#888]
##### SUMMARY

When multiple Ansible tasks are executed in one process then SELinux file context changes done through the sefcontext module are possibly over-shadowed by stale cache entries because the sefcontext module doesn't flush that matchpathcon in-process cache. 

There may be multiple ways how to get Ansible to execute all playbook tasks in one Python process. One reliable way is to use the Mitogen connection plugin.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

sefcontext

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /home/gms/program/linode/del/ansible.cfg
  configured module search path = ['/home/gms/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.8 (default, Jul  1 2020, 15:39:07) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/juser/del/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/juser/del/ansible.cfg) = ['/home/juser/del/hosts']
DEFAULT_STRATEGY(/home/juser/del/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/juser/del/ansible.cfg) = ['/usr/lib/python3.7/site-packages/ansible_mitogen/plugins/strategy']
INTERPRETER_PYTHON(/home/juser/del/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

Fedora 31, ansible-2.9.11-1.fc31.noarch, python3-mitogen-0.2.9-1.fc31.noarch

##### STEPS TO REPRODUCE

Use the following minimal reproducer example playbook:

```yaml
- name: sefcontext test play
  hosts: all
  gather_facts: no
  tasks:
      - name: add first filecontext
        sefcontext:
            target: '/srv/delme_fst(/.*)?'
            setype: httpd_sys_content_t
            state: present
      - name: apply first default context
        file:
            state: directory
            dest: "/srv/delme_fst"
            owner: root
            group: root
            mode: '0755'
            setype: _default
            seuser: _default

      - name: add filecontext
        sefcontext:
            target: '/srv/delme(/.*)?'
            setype: httpd_sys_content_t
            state: present
      - name: apply default context
        file:
            state: directory
            dest: "/srv/delme"
            owner: root
            group: root
            mode: '0755'
            setype: _default
            seuser: _default

      - name: remove filecontext
        sefcontext:
            target: '/srv/{{ item }}(/.*)?'
            setype: httpd_sys_content_t
            state: absent
        loop:
            - delme_fst
            - delme
      - name: apply default context
        file:
            state: absent
            dest: "/srv/{{ item }}"
        loop:
            - delme_fst
            - delme

```

Make sure that the Mitogen connection plugin is enabled (or use another method where consecutive tasks are executed in the same Python process), e.g. put something like this into your `ansible.cfg`:

```
[defaults]
strategy_plugins = /usr/lib/python3.7/site-packages/ansible_mitogen/plugins/strategy
strategy = mitogen_linear
```

To verify that multiple task are executed in the same process you check for the PIDs in the system log, e.g. with:

```
journalctl SYSLOG_IDENTIFIER=ansible-file + SYSLOG_IDENTIFIER=ansible-sefcontext  -f
```

##### EXPECTED RESULTS

That both directories are created with the `httpd_sys_content_t` file context. That means output for the third and fourth task similar to:

```
TASK [add filecontext] **********************************************
# Addition to semanage file context mappings
+/srv/delme(/.*)?      a      system_u:object_r:httpd_sys_content_t:s0
changed: [example.org]

TASK [apply default context] ***************************************
--- before
+++ after
@@ -1,10 +1,10 @@
 {
     "path": "/srv/delme",
     "secontext": [
-        "unconfined_u",
+        "system_u",
         "object_r",
-        "var_t",
+        "httpd_sys_content_t",
         "s0"
     ],
-    "state": "absent"
+    "state": "directory"
 }

changed: [example.org]
```

##### ACTUAL RESULTS

The second directory is incorrectly labeled according to the newly added file context rule:

```paste below
ASK [add filecontext] ***************************************************
# Addition to semanage file context mappings
+/srv/delme(/.*)?      a      system_u:object_r:httpd_sys_content_t:s0
changed: [example.org]

TASK [apply default context] *******************************************
--- before
+++ after
@@ -1,10 +1,10 @@
 {
     "path": "/srv/delme",
     "secontext": [
-        "unconfined_u",
+        "system_u",
         "object_r",
         "var_t",
         "s0"
     ],
-    "state": "absent"
+    "state": "directory"
 }

changed: [example.org]
```

This is caused by the fact that the file module ends up calling `matchpathcon()` to get the default file context:

https://github.com/ansible/ansible/blob/a10af345a9f7cd79bec495843be7847961f90e23/lib/ansible/module_utils/basic.py#L916

The problem is that `matchpathcon()` [internally caches file context information on first use][1].

Thus, I propose that sefcontext explicitly flushes the matchpathcon cache before returning - if something changed. 

That means something like this

```
    if changed:
        selinux.matchpathcon_fini()
```

right before

https://github.com/ansible-collections/community.general/blob/4c33e2ccb84a0f82dd733b761aac667514af4554/plugins/modules/system/sefcontext.py#L214

and

https://github.com/ansible-collections/community.general/blob/4c33e2ccb84a0f82dd733b761aac667514af4554/plugins/modules/system/sefcontext.py#L245

I've tested this change in my environment and this fixes the issue for me.

I don't think that dropping the cache has negative side-effects - i.e. it should be fast even if you have many file context rules.

[1]: https://manpath.be/f32/3/matchpathcon
