### ISSUE TITLE
flatpak module: incorrect task status reported for updating depending on language

### ISSUE THREAD

**Issue by kevonfernando** [ansible-collections/community.general#8883]
### Summary

Installing/Updating apps with the flatpak module always reports `changed` as task status when language is not english. See [flatpak.py line 250](https://github.com/ansible-collections/community.general/blob/6af74d1ba6a8f5378d4fa775bc474f525599e18f/plugins/modules/flatpak.py#L249)

### Issue Type

Bug Report

### Component Name

flatpak

### Ansible Version

```console (paste below)
$ ansible --version

```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
ansible [core 2.16.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/home/kevonfernando/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /var/home/kevonfernando/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Control node:
- Fedora 40 toolbox container
- Ansible installed from Fedora 40 repos
Target node:
- Fedora Silverblue 40

### Steps to Reproduce

```yaml (paste below)
- name: Install flatpaks from the Flathub remote to the system installation
  community.general.flatpak:
    method: system
    remote: flathub
    name:
      - page.kramo.Cartridges
    state: latest
```

### Expected Results

I expected the reported task status to be `ok` and not `changed`. 

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
