### ISSUE TITLE
pipx upgrade fails with package names containing brackets

### ISSUE THREAD

**Issue by fliespl** [ansible-collections/community.general#8926]
### Summary

fatal: [x]: FAILED! => {"changed": false, "cmd": "/usr/bin/python3 -m pipx upgrade 'glances[all]'", "msg": "Package is not installed. Expected to find\n/root/.local/share/pipx/venvs/glances[all], but it does 
not exist.", "rc": 1, "stderr": "Package is not installed. Expected to find\n/root/.local/share/pipx/venvs/glances[all], but it does not exist.\n", "stderr_lines": ["Package is not installed. Expected to find", "/root/.local/share/pipx/venvs/glances[all], but it does not exist."], "stdout": "", "stdout_lines": []}

### Issue Type

Bug Report

### Component Name

pipx

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.4]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 9.4.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 24.04

### Steps to Reproduce

```yaml (paste below)

- name: Install glances
  community.general.pipx:
    name: "glances[all]"
    state: latest

```

### Expected Results

Successful install

### Actual Results

```console (paste below)

```
FAILED! => {"changed": false, "cmd": "/usr/bin/python3 -m pipx upgrade 'glances[all]'", "msg": "Package is not installed. Expected to find\n/root/.local/share/pipx/venvs/glances[all], but it does 
not exist.", "rc": 1, "stderr": "Package is not installed. Expected to find\n/root/.local/share/pipx/venvs/glances[all], but it does not exist.\n", "stderr_lines": ["Package is not installed. Expected to find", "/root/.local/share/pipx/venvs/glances[all], but it does not exist."], "stdout": "", "stdout_lines": []}

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/pipx.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/pipx.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @russoz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
I think you need to put `glances[all]` into `source`, not `name`. `name` should be the application's name, which is `glances` in your case.

**Comment by fliespl** [comment]
@felixfontein Thank you! 

For others reference - this works:

```
- name: Install glances
  community.general.pipx:
    name: "glances"
    source: 'glances[all]'
    state: latest

- name: Install glances packages
  community.general.pipx:
    name: "glances"
    inject_packages:
      - fastapi
      - uvicorn
      - python-dateutil
      - jinja2
    state: inject
```

This works!
