### ISSUE TITLE
[Feature Request][zypper] Add parameter to list all updateable packages

### ISSUE THREAD

**Issue by seraphyn** [ansible-collections/community.general#8941]
### Summary

I try to list all available updates like in dnf, apt, or yum, but this feature isn't implemented atm.
I helped myself to write this Playbook years ago, but in my opinion this should be an parameter in the module zypper

```
- hosts: sles
  become: true
  become_user: root
  tasks:
          - name: Zypper Update awk to file
            shell:
                " zypper ref && zypper lu | awk '{print $5, $7, $9 }' | sed -e '1,10d' | sed 's/\"//' > /tmp/awklist.txt "
            register: lsout
            tags: lsout

          - name: show awklist
            shell : cat /tmp/awklist.txt
            register: displaylist

          - debug: msg="{{displaylist.stdout_lines}}"
          - 
```
It's not perfect but fits atm

### Issue Type

Feature Idea

### Component Name

zypper

### Additional Information

```
- name: show updateable packages
  community.general.zypper:
    update_cache: yes
    state: installed
    upgrade: no
   ```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
