### ISSUE TITLE
community.general.gitlab_label does not update colors for existing labels

### ISSUE THREAD

**Issue by silvermind** [ansible-collections/community.general#8991]
### Summary

When I try to update an existing gitlab label the change of a color is detected but not applied

### Issue Type

Bug Report

### Component Name

community.general.gitlab_label

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.2]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 9.4.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

### OS / Environment

Ubuntu 22 in WSL

### Steps to Reproduce

```yaml (paste below)
- name: Set or update some labels
  community.general.gitlab_label:
    api_url: https://gitlab.com
    api_token: secret_access_token
    project: "group1/project1"
    labels:
      - name: label_one
        color: "#224488"
    state: present
```

### Expected Results

if the label already exist it should have the color 224488

### Actual Results

```console (paste below)
label color does not change
```

assuming this is due to `color` is missing in the `update_label` method found at https://github.com/ansible-collections/community.general/blob/main/plugins/modules/gitlab_label.py#L266

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
