### ISSUE TITLE
Support same reset actions on Managers as on Systems

### ISSUE THREAD

**Issue by billdodd** [ansible-collections/community.general#901]
##### SUMMARY

The redfish_command.py module supports commands for performing power reset operations (power on, off, reboot, etc.) on a Redfish System. Redfish Managers have the same model for power reset operations as Systems. But the redfish_command.py module currently only supports a single reset option for Managers - GracefulRestart.

This feature request is to support the same power reset actions on Managers as on Systems. 
 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

redfish_command.py

##### ADDITIONAL INFORMATION

Currently, there is no way to issue reset actions like On, ForceOff, GracefulShutdown, and ForceRestart on Redfish Managers. These are actions that BMC operators may need to perform.

Example of plays that can be performed after this feature has been implemented:
```yaml
  - name: Turn manager power off
    community.general.redfish_command:
      category: Manager
      command: PowerForceOff
      resource_id: BMC
```

```yaml
  - name: Turn manager power on
    community.general.redfish_command:
      category: Manager
      command: PowerOn
      resource_id: BMC
```
