### ISSUE TITLE
SELinux restorecon module

### ISSUE THREAD

**Issue by Hipska** [ansible-collections/community.general#9021]
### Summary

It would be nice if there would be a ansible module for the `restorecon` command. It would then be easy to know if the status is changed and also which files changed in the diff.

### Issue Type

Feature Idea

### Component Name

restorecon

### Additional Information

```yaml (paste below)
- name: Restore SELinux context
  community.general.restorecon:
    path: /var/www/html
    recursive: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by NicholasBrodersen** [comment]
I would like to work on implementing this feature.

I have been prototyping the module using the SELinux Python bindings provided by `libselinux`, which is also used by the `seport`, `selogin`, and `sefcontext` modules. I wanted to document the proposed interface and implementation here before preparing the PR so others have an opportunity to comment on the design.

### Proposed Module
I am currently calling the module `community.general.serestorecon`. 
`serestorecon` is being used for the name and not just `restorecon` to maintain a similar naming scheme to other selinux modules.

The proposed options are:
`path`:
  - Path
  - Mandatory
  - The file or directory whose SELinux context should be restored.

`recurse`:
  - Boolean
  - Optional
  - Default: `false`
  - When enabled, the module will will preform the operation recursively on the supplied path.

`exclude_paths`:
  - List[Paths]
  - Optional
  - Can only be used
  - Excluding a directory will also exclude all items in that that directory.

`cross_filesystems`:
  - Boolean
  - Optional
  - Default: `true`
  - When false, recursive traversal will only process paths whose filesystem and/or device ID matches the filesystem containing the initial path.
  - This is documented optional behavior in `restorecon`, and should be provided by this module to give users the capbility if needed.
  - The default is `true` because this what users of the module would expect as the default behavior.

`context`:
  - String
  - Mandatory
  - Options: `type`, `user_role`, 'full'
  - Default: 'type'
  - Controls which portions of the SELinux context are enforced.
  - `restorecon` typically just focuses on setting the selinux type,
    however `restorecon` can also ensure the user context, user role context, and all other selinux metadata is check and restore to what it should be.
  - By default on `restorecon` just operates on the selinux type so that behavior is reflected in the default option.
  - The `user_role` option will ensure the contexts for the user, user role, and type are set to what they should be
  - The `full` option will ensure that all of the selinux metadata is correctly set.

### Return Values
The module will return the paths whose contexts were changed along with their previous and restored contexts.

For example:
```
changed: true
changed_paths:
  - path: /var/www/html
    previous: system_u:object_r:var_t:s0
    restored: system_u:object_r:httpd_sys_content_t:s0

  - path: /var/www/html/index.html
    previous: system_u:object_r:var_t:s0
    restored: system_u:object_r:httpd_sys_content_t:s0
```

If nothing requires modification:
```
changed: false
changed_paths: []
```
### Check Mode
Check mode will be fully supported.
`changed` will indicate whether anything would be changed, and `changed_paths` will contain the paths that would be restored.

For example:
```
changed: true
changed_paths:
  - path: /var/www/html/index.html
    previous: system_u:object_r:var_t:s0
    restored: system_u:object_r:httpd_sys_content_t:s0
```

### Related issues
#4565

As mentioned earlier, I currently have a working prototype of the module, but I wanted to document the proposed public API and implementation strategy here before preparing the full PR.

Feedback is very welcome!

**Comment by Hipska** [comment]
I like it! Just wondering, how would the output when using `--diff` look like?

**Comment by NicholasBrodersen** [comment]
I believe the most readable way to emit output for diff mode is for both `before` and `after` to be lists, with each element being a dictionary contain the keys `path` and `context` like this:
```
diff:
  before:
    - path: /tmp/test/file1
      context: system_u:object_r:var_t:s0
    - path: /tmp/test/file2
      context: system_u:object_r:var_t:s0

  after:
    - path: /tmp/test/file1
      context: system_u:object_r:tmp_t:s0
    - path: /tmp/test/file2
      context: system_u:object_r:tmp_t:s0
```
This is currently what I have as the diff mode output.
