### ISSUE TITLE
git_config: support Windows

### ISSUE THREAD

**Issue by mathstuf** [ansible-collections/community.general#9031]
### Summary

When using `git_config` on a Windows host, the following error is raised:

```
Exception calling \"Create\" with \"1\" argument(s): \"At line:4 char:21_x000D__x000A_</S><S S=\"Error\">+ def _ansiballz_main():
```

and so on with a bunch of "PowerShell trying to read Python code" effects. According to [this article](https://www.ansiblepilot.com/articles/ansible-troubleshooting-module-failure-on-windows-target/) this is because the module in question doesn't consider Windows/PowerShell situations.

### Issue Type

Bug Report

### Component Name

git_config

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.11]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/boeckb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/boeckb/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.6 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
8.6.5
```


### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = nvim
```


### OS / Environment

Fedora 40

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml (paste below)
- name: Set `core.longpaths`                                                                                                                                                                                     
  become: true                                                                                                                                                                                                   
  become_method: runas                                                                                                                                                                                           
  become_flags: logon_flags=with_profile                                                                                                                                                                         
  community.general.git_config:                                                                                                                                                                                  
    name: core.longpaths                                                                                                                                                                                         
    scope: "file"                                                                                                                                                                                                
    file: "c:/Users/{{ gitlab_runner_user }}/.gitconfig"                                                                                                                                                         
    value: "true"                                                                                                                                                                                                
  vars:                                                                                                                                                                                                          
    ansible_become_user: '{{ gitlab_runner_user }}'                                                                                                                                                              
    ansible_become_pass: '{{ windows_svc_user_passwd }}'
```


### Expected Results

The command to work on Windows. Or document that it is unsupported.

### Actual Results

```console (paste below)

```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
