### ISSUE TITLE
groupby_as_dict filter plugin: Support multiple sequences 

### ISSUE THREAD

**Issue by Warkdev** [ansible-collections/community.general#9032]
### Summary

I have an use-case where I want to group a list of dictionaries by a key present in all of them.

I have found the plugin groupby_as_dict which seemed to do what I wanted until I realised it was not.

Basically, I'd provide the following list as input:

```yaml
my_list:
- name: my_name
  interesting_attr: value_1
-  name: other_name
   interesting_attr: value_2
-  name: again_a_name
   interesting_attr: value_1
```

Giving it to the groupby_as_dict filter based on "interesting_attr" would output the following:

```yaml
value_1:
- name: my_name
  interesting_attr: value_1
- name: again_a_name
  interesting_attr: value_1
value_2:
- name: other_name
  interesting_attr: value_2
```

At this moment, the only wait is to loop over the list and abuse the combine filter which isn't a great experience :)

### Issue Type

Feature Idea

### Component Name

groupby_as_dict

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
