### ISSUE TITLE
RAID creation and deletion on Lenovo not working

### ISSUE THREAD

**Issue by 1sttec** [ansible-collections/community.general#9047]
### Summary

The if declarations on lines 3717 and 3779 of community.general/plugins/module_utils/redfish_utils.py, that read "if storage_subsystem_uri.split("/")[-2] == storage_subsystem_id:" is evaluating the -2 index, which on Lenovo returns "Storage" not the ID of the storage controller which is found at index -1.

Consequently the delete and create raid functions result in error "Provided Storage Subsystem ID %s does not exist on the server"

Writing the value of storage_subsystem_uri.split("/")[-2] from redfish_utils.py shows it to be "Storage".

Whereas when getting the the storage subsystem ID using curl you get the following:

```CONSOLE
curl -skL https://[IP ADDRESS]/redfish/v1/Systems/1/Storage -X GET -u "[USERID]:[PASSWORD]" | jq
{
  "@odata.id": "/redfish/v1/Systems/1/Storage",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/1/Storage/RAID_Slot15"
    }
  ],
  [Members@odata.count](mailto:Members@odata.count): 1,
  "@odata.context": "/redfish/v1/$metadata#StorageCollection.StorageCollection",
  "@odata.etag": "\"27b88a53d1772a22538\"",
  "Description": "A collection of storage resource instances",
  "Name": "StorageCollection",
  "@odata.type": "#StorageCollection.StorageCollection"
}
```

### Issue Type

Bug Report

### Component Name

redfish_config

### Ansible Version

```console (paste below)
ansible [core 2.17.4]
  config file = /home/[USERID]/.ansible.cfg
  configured module search path = ['/home/[USERID]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/[USERID]/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/[USERID]/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/[USERID]/.local/bin/ansible
  python version = 3.11.9 (main, Jun 19 2024, 10:02:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
# /home/[UDERID]/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 9.4.0

# /home/[USERID]/.local/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 9.4.0
```

### Configuration

```console (paste below)
COLLECTIONS_PATHS(/home/[USERID]/source/boot-poc/ansible.cfg) = ['/home/[USERID]/.local/lib/python3.11/site-packages/ansible_collections', '/home/>
CONFIG_FILE() = /home/[USERID]/source/boot-poc/ansible.cfg
INVENTORY_UNPARSED_WARNING(/home/[USERID]/source/boot-poc/ansible.cfg) = False
LOCALHOST_WARNING(/home/[USERID]/source/boot-poc/ansible.cfg) = False
```

### OS / Environment

Red Hat Enterprise Linux release 8.7 (Ootpa)

### Steps to Reproduce

```yaml
- name: Create Volume
  community.general.redfish_config:
    category: Systems
    command: CreateVolume
    baseuri: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    storage_subsystem_id: "{{ controllerid }}"
    volume_details:
      Name: "System"
      RAIDType: "RAID1"
      Drives:
        - "/redfish/v1/Systems/{{ systemid }}/Storage/{{ controllerid }}/Drives/{{ sysdiskid1 }}"
        - "/redfish/v1/Systems/{{ systemid }}/Storage/{{controllerid }}/Drives/{{ sysdiskid2 }}"
   ```

### Expected Results

RAID 1 Volume is created using disks 0 & 1 on controller RAID_Slot15

### Actual Results

```console
PLAY [localhost] ********************************************************************************************************************************

TASK [ctest : Create Volume] ********************************************************************************************************************
failed: [localhost] (item=[IP ADDRESS]) => {"ansible_loop_var": "item", "changed": false, "item": "[IP ADDRESS]", "msg": "Provided Storage Subsystem ID RAID_Slot15 does not exist on the server"}

PLAY RECAP **************************************************************************************************************************************
localhost

===
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
