### ISSUE TITLE
Support for more validators in the keycloak_userprofile module.

### ISSUE THREAD

**Issue by mkay-sh** [ansible-collections/community.general#9048]
### Summary

I'm trying to configure the userprofile in keycloak. The validation of the module only allows predefined values, but there are other validators available in our instance. Additionally keycloak extensions could provide more validators. The list should not be static but either allow all values or fetch the available list of validation providers from the server.

### Issue Type

Feature Idea

### Component Name

community.general.keycloak_userprofile

### Additional Information

```yaml (paste below)
community.general.keycloak_userprofile:
    state: present
    config:
      kc_user_profile_config:
        - attributes:
          - name: firstName
            displayName: ${firstName}
            validations:
              length:
                max: 255
              person_name_prohibited_characters: {}
              local_date: {}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
