### ISSUE TITLE
Support for OSService check in consul_agent_check module

### ISSUE THREAD

**Issue by maciej-lech** [ansible-collections/community.general#9083]
### Summary

Hi!

Would be nice to have support for [OSService check](https://developer.hashicorp.com/consul/docs/services/usage/checks#osservice-check).

Best regards,
Maciej

### Issue Type

Feature Idea

### Component Name

consul_agent_check

### Additional Information

```yaml (paste below)
- name: Register systemd check for service 'nginx'
  community.general.consul_agent_check:
    name: nginx_systemd_check
    service_id: nginx
    interval: 60s
    os_service: nginx
    notes: "Nginx Check"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
