### ISSUE TITLE
keycloak_clientscope_type: changes are not detected in check mode 

### ISSUE THREAD

**Issue by witrdotnet** [ansible-collections/community.general#9092]
### Summary

`community.general.keycloak_clientscope_type` module detects and reports changes in non-check mode. Howerver, changes are not detected nor reported in check mode.

### Issue Type

Bug Report

### Component Name

keycloak_clientscope_type

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.5]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/share/virtualenvs/general-YFeQnqo1/lib/python3.11/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.local/share/virtualenvs/general-YFeQnqo1/bin/ansible
  python version = 3.11.9 (main, Oct 31 2024, 23:17:42) [GCC 9.4.0] (~/.local/share/virtualenvs/general-YFeQnqo1/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 9.5.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

### OS / Environment

Observed under Ubuntu 22 and Debian 11.

Python installed with pyenv and ansible executed with pipenv.

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost

  vars:
    url: http://localhost:8080
    admin_realm: master
    admin_user: admin
    admin_password: password
    realm: clientscope-type-realm
    client_id: clientscope-type-client

  tasks:
  - name: adjust client-scope types in client
    community.general.keycloak_clientscope_type:
      auth_keycloak_url: "{{ url }}"
      auth_realm: "{{ admin_realm }}"
      auth_username: "{{ admin_user }}"
      auth_password: "{{ admin_password }}"
      realm: "{{ realm }}"
      client_id: "{{ client_id }}"
      default_clientscopes: ['scope1']
      optional_clientscopes: ['scope2']
```

### Expected Results

Assuming client under test have no scopes, following standard output is expected in **check mode** :

```
TASK [adjust client-scope types in client] ****************************************
--- before
+++ after
@@ -1,4 +1,8 @@
 {
-    "default_clientscopes": [],
-    "optional_clientscopes": []
+    "default_clientscopes": [
+        "scope1"
+    ],
+    "optional_clientscopes": [
+        "scope2"
+    ]
 }

changed: [localhost]
```

### Actual Results

```console (paste below)
TASK [adjust client-scope types in client] ****************************************
ok: [localhost]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
