### ISSUE TITLE
Expose query/lookup as filter

### ISSUE THREAD

**Issue by VannTen** [ansible-collections/community.general#9107]
### Summary

I'm a heavy user of map to apply filter to list of variables, which is often a much more efficient alternatives to ansible loops.
I would like to be able to apply a lookup to a list of variables using map.
This is useful in two kind of situations:

1. you want to pass data to lookup which are truly dynamic (come from the hostvars, or from the playbooks / role author perpective, from the user inventories)
2. Reduce coupling -> See example below.

This is analogous to the use of 'extract' to provide key/index access as a filter, so that I can be used with map.

### Issue Type

Feature Idea

### Component Name

lookup

### Additional Information

```yaml (paste below)
# Consider the following variables defined in differents roles / inventory files
# (the value are unimportant here)
nvidia_k8s_node_taints:
- nvidia.com/gpu=somevalue:NoSchedule
ingress_k8s_node_taints:
- kubernetes.io/node-role=ingress:NoSchedule

# Then a role dedicated to setting taints on kubenetes nodes (well, just one tasks)
- cmd: kubectl taints {{ some_node }} {{ my_taints }}
  vars:
    my_taints: "{{ query('ansible.builtin.varnames', '.+_k8s_node_taints') | map('community.general.query/lookup', 'ansible.builtin.vars') | flatten }}" 
    # feeding a list direcly to the varnames lookup does not work, it complains it's not a string.
    # each place defining taints can't apply them, because we need to have a full view to be able to delete taints which are present on the infra currently but not in the set.
```
The current alternatives is to hardcode each of these variable:
```yaml
  my_taints: "{{ query('ansible.builtin.vars, 'ingress_k8s_node_taints', 'nvidia_k8s_node_taints' , .... }}"
  ```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
