### ISSUE TITLE
dnf_config_manager: incompatibility with DNF5

### ISSUE THREAD

**Issue by hmenke** [ansible-collections/community.general#9127]
### Summary

DNF5 has completely changed the command line interface from DNF4. Among other things, the `--verbose` global option was removed entirely. However, the `dnf_config_manager` component hardcodes not only the path to DNF, but also the `--verbose` option in the call to `repolist`.

https://github.com/ansible-collections/community.general/blob/bafb8aca292dfb365a6386cc52e4de40f8e6bfc6/plugins/modules/dnf_config_manager.py#L129-L135

### Issue Type

Bug Report

### Component Name

dnf_config_manager

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.12]
  config file = /tmp/ansible-test/ansible.cfg
  configured module search path = ['/tmp/ansible-test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /tmp/ansible-test/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/lib/python3.13/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.6.6 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_HOME(/tmp/ansible-test/ansible.cfg) = /tmp/ansible-test/.ansible
ANSIBLE_NOCOWS(/tmp/ansible-test/ansible.cfg) = True
ANSIBLE_PIPELINING(/tmp/ansible-test/ansible.cfg) = True
CONFIG_FILE() = /tmp/ansible-test/ansible.cfg
DEFAULT_HOST_LIST(/tmp/ansible-test/ansible.cfg) = ['/tmp/ansible-test/hosts.yml']
DEFAULT_STDOUT_CALLBACK(/tmp/ansible-test/ansible.cfg) = yaml
EDITOR(env: EDITOR) = emacsclient -c -a "" -t
```

### OS / Environment

Fedora Linux 41 (Workstation Edition)

### Steps to Reproduce

```yaml (paste below)
- name: Enable Cisco OpenH264 repository.
  community.general.dnf_config_manager:
    name: fedora-cisco-openh264
    state: enabled
```

### Expected Results

No error

### Actual Results

```yaml
fatal: [localhost]: FAILED! => changed=false 
  cmd: /usr/bin/dnf repolist --all --verbose
  msg: Unknown argument "--verbose" for command "repolist". Add "--help" for more information about the arguments.
  rc: 2
  stderr: |-
    Unknown argument "--verbose" for command "repolist". Add "--help" for more information about the arguments.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
