### ISSUE TITLE
Add an 'accumulate' filter

### ISSUE THREAD

**Issue by VannTen** [ansible-collections/community.general#9129]
### Summary

I am trying to convert [systemd slice](https://www.freedesktop.org/software/systemd/man/latest/systemd.slice.html) names to the corresponding cgroup trees using ansible filters, which bogs down to:
`my-slice-foo.slice -> /my.slice/my-slice.slice/my-slice-foo.slice`

(slice are always in a hierarchy and include the parent slice in their own name, and this is reflected in the hierarchy).

I had no luck finding a way to achieve this using only variable (and I'd rather not use fact and loops for that) but `accumulate` ( which would be a pass-through to the [matching python function in itertools](https://docs.python.org/3/library/itertools.html#itertools.accumulate) would make that easy.

I do believe that while my usecase in rather specialized, the underlying transformation is a general tool which would be useful for a variety of purpose.

(I implement the PR for that myself btw).

If there is a already available way to this without a new filter / lookup, I'm happy to hear about it :)

### Issue Type

Feature Idea

### Component Name

plugins/filter/

### Additional Information

```yaml
# implementation of the use case mentionned below using hypothetical accumulate:

my_slice: my-slice-foo.slice

slice_parts: "{{ (my_slice | splitext)[0].split('-') | map ('split') }}" -> list of singleton lists containing each one part of the string
cgroups_path_parts: "{{ (slice_parts | accumulate | map('join', '-') | join('.slice/')) + '.slice/' }}"

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
