### ISSUE TITLE
apache2_module fails to disable cgi module

### ISSUE THREAD

**Issue by dhoffend** [ansible-collections/community.general#9140]
### Summary

Trying to disable the cgi module while running in mpm_event module will result in a failure, even when cgi module is already disabled.

Disabling the `cgi` module with `community.general.apache2_module` will fail with the error message `Your MPM seems to be threaded. No automatic actions on module cgi possible.`. Doing the same on the commandline with `a2dismod cgi` will result with the correct messaage `cgi is already disabled`.

In additional, the `ignore_configcheck` parameter gets ignored, cause the cgi detection hits earlier

Code:
* https://github.com/ansible-collections/community.general/blob/main/plugins/modules/apache2_module.py#L285-L287

Possible solutions:
* Check with `a2query -m` if the module in question is already enabled (this is our current workaround)
* Check cgi operation only with `state: present` not `absent` since the problem happens only when enabling cgi module in threaded mode not the other way
* Skip the cgi detection when `ignore_configcheck` is set

### Issue Type

Bug Report

### Component Name

apache2_module

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.12]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 7.5.2  
```
But the bug is also present in the current HEAD of community.general cause all operation on cgi are not allowed when threaded module is detected.

### OS / Environment

Debian 11 and Debian 12

### Steps to Reproduce

```yaml (paste below)
- name: install apache2 will default to mpm_event
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Disabled already disabled cgi module
  community.general.apache2:
    name: cgi
    state: absent
```

### Expected Results

Result should be `OK` not `FAILED` since the module is already disabled

### Actual Results

```console (paste below)
"Your MPM seems to be threaded. No automatic actions on module cgi possible."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/apache2_module.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/apache2_module.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @berendt @n0trax
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
Hi @dhoffend thanks for reporting. 

Just to be on the safe side, could you please repeat the test in the latest (or a more recent) version of the collection? Version 7.x is no longer supported - latest one is 10.x already. Thanks!

**Comment by dhoffend** [comment]
@russoz I can try to setup a test environment, but since I compared the HEAD code and the mentioned line with the one at 7.x I don’t expect many differences. In the head code the module execution stops before doing any other evaluation. I’ll let you know

**Comment by russoz** [comment]
You have clearly dug deeper than me, so I am happy to take your word on it.

**Comment by yaiqsa** [comment]
I can verify that this is still an issue using the `community.general` version 9.5.2

Is there anything I can to to help debug this?

**Comment by russoz** [comment]
Hi @yaiqsa 

Yes, could you please run this with `ansible-playbook -vvvv` and paste the outcome for this one task?

**Comment by dhoffend** [comment]
Sure

Tested using `ansible-core 2.15` and `community.general 10.7.1` on Debian 12 using Fresh Vagrant VM running Debian 12 as well.

The Playbook
```
# vim: ts=2 sw=2 expandtab
---

- name: Install apache2 and disable cgi module
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Install apache2 will default to mpm_event
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Disabled already disabled cgi module
      community.general.apache2_module:
        name: cgi
        state: absent
```

The result
```
fatal: [demo]: FAILED! => 
    changed: false
    invocation:
        module_args:
            force: false
            identifier: null
            ignore_configcheck: false
            name: cgi
            state: absent
            warn_mpm_absent: true
    msg: Your MPM seems to be threaded. No automatic actions on module cgi possible.
```

The full logfile is attached

[ansible-playbook-apache2-cgi.txt](https://github.com/user-attachments/files/21156765/ansible-playbook-apache2-cgi.txt)
