### ISSUE TITLE
gio_mime: gio mime --version check is called incorrectly

### ISSUE THREAD

**Issue by oxivanisher** [ansible-collections/community.general#9158]
### Summary

Since the last change, the module tries to check for the gio version with the command "gio mime --version". But this is failing and should be "gio --version".

### Issue Type

Bug Report

### Component Name

gio_mime

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.13]
  config file = /home/johndoe/ansible/ansible.cfg
  configured module search path = ['/home/johndoe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/johndoe/dev/ansible-venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/johndoe/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/johndoe/dev/ansible-venv/bin/ansible
  python version = 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] (/home/johndoe/dev/ansible-venv/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/johndoe/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.0.1 

# /home/johndoe/dev/ansible-venv/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.6.7
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CACHE_PLUGIN(/home/johndoe/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/home/johndoe/ansible/ansible.cfg) = localhost:6379:0
CACHE_PLUGIN_TIMEOUT(/home/johndoe/ansible/ansible.cfg) = 3600
CONFIG_FILE() = /home/johndoe/ansible/ansible.cfg
DEFAULT_FORKS(/home/johndoe/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/johndoe/ansible/ansible.cfg) = ['/home/oxi/ansible/hosts.yml']
DEFAULT_LOG_PATH(/home/johndoe/ansible/ansible.cfg) = /home/oxi/.ansible/ansible.log
DEFAULT_MANAGED_STR(/home/johndoe/ansible/ansible.cfg) = Ansible managed, do not edit directly: {file} on {host}
DEFAULT_PRIVATE_KEY_FILE(/home/johndoe/ansible/ansible.cfg) = /home/oxi/.ssh/id_thunderbluff_ansible.pub
DEFAULT_STDOUT_CALLBACK(/home/johndoe/ansible/ansible.cfg) = yaml
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/home/johndoe/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/johndoe/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = /usr/bin/vim
```

### OS / Environment

Target OS is a Ubuntu 24.04

### Steps to Reproduce

```yaml (paste below)
---
- name: Set Vivaldi default application
  community.general.gio_mime:
    mime_type: "{{ mimetype }}"
    handler: vivaldi-stable.desktop
  loop: "{{ vivaldi_mimetypes }}"
  loop_control:
    loop_var: mimetype
  become: true
  become_user: "{{ item }}"

---
# defaults file for vivaldi
vivaldi_os_users: ['johndoe']

---
# vars file for vivaldi
vivaldi_mimetypes:
  - text/html
  - x-scheme-handler/http
  - x-scheme-handler/https
  - x-scheme-handler/about
  - x-scheme-handler/unknown
```

### Expected Results

The mime type should be changed.

### Actual Results

```console (paste below)
failed: [hangar52.example.com] (item=x-scheme-handler/unknown) => changed=false 
  ansible_loop_var: mimetype
  cmd: /usr/bin/gio mime --version
  mimetype: x-scheme-handler/unknown
  msg: |-
    gio: Unknown option --version
  
    Usage:
      gio mime MIMETYPE [HANDLER]
  
    Get or set the handler for a mimetype.
  
    If no handler is given, lists registered and recommended applications
    for the mimetype. If a handler is given, it is set as the default
    handler for the mimetype.
  rc: 1
  stderr: |-
    gio: Unknown option --version
  
    Usage:
      gio mime MIMETYPE [HANDLER]
  
    Get or set the handler for a mimetype.
  
    If no handler is given, lists registered and recommended applications
    for the mimetype. If a handler is given, it is set as the default
    handler for the mimetype.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

I am pretty sure the error is in [plugins/module_utils/gio_mime.py#L12](https://github.com/ansible-collections/community.general/blob/54194ccb2427cccf282eea1a20294dd794ce77dc/plugins/module_utils/gio_mime.py#L12). To check the version, gio has to be called without the mime parameter:
```bash
johndoe@hangar52 ~/dev/_Ansible $ gio mime --version
gio: Unknown option --version

Usage:
  gio mime MIMETYPE [HANDLER]

Get or set the handler for a mimetype.

If no handler is given, lists registered and recommended applications
for the mimetype. If a handler is given, it is set as the default
handler for the mimetype.
johndoe@hangar52 ~/dev/_Ansible $ gio --version
2.80.0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
