### ISSUE TITLE
Support `--rootdir` and `--repository` flags for xbps

### ISSUE THREAD

**Issue by ssnailed** [ansible-collections/community.general#9173]
### Summary

When using ansible to provision a new desktop, I currently have to run xbps-install as a shell command to be able to install a new void linux system on a mounted partition. It would be much more pleasant if the xbps module supported this directly.

### Issue Type

Feature Idea

### Component Name

xbps

### Additional Information

It would be nice to do something like this:
```yaml (paste below)
- name: Install a new void system on a mounted partition
  community.general.xbps:
    name: base-system
    state: present
    repository: https://repo-default.voidlinux.org/current
    root: /mnt
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
