### ISSUE TITLE
Enable/disable a site / virtual host on the Apache2 webserver

### ISSUE THREAD

**Issue by Hipska** [ansible-collections/community.general#9209]
### Summary

Similar to the already existing [community.general.apache2_module module](https://docs.ansible.com/ansible/latest/collections/community/general/apache2_module_module.html), a similar one for enabling/disabling specific sites might be useful as well.

### Issue Type

Feature Idea

### Component Name

apache2_site

### Additional Information

```yaml (paste below)
- name: Enable my_cool_site
  community.general.apache2_site:
    state: present
    name: my_cool_site

- name: Disable old site
  community.general.apache2_site:
    state: absent
    name: very_old_site
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
