### ISSUE TITLE
community.general.ldap_entry module not adding new entry even no entry is present in ldap server,

### ISSUE THREAD

**Issue by d0020002** [ansible-collections/community.general#9235]
### Summary

When I am trying to add an entry even if entry is not present, it is still saying not adding with just output "{changed: false, failed: false}

I am using below task to add the entry

    - name: Create LDAP Entry with Attributes
      community.general.ldap_entry:
        dn: "cn={{ ldap_user_cn }},nismapname={{ nismapname }},ou={{ ou }},{{ automount_base_dn }}"
        objectClass:
          - top
          - nisObject
        attributes:
          cn: "{{ ldap_user_cn }}"
          nismapName: "{{ nismapname }}"
          nisMapEntry: "{{ nis_map_entry }}"
        state: present
        bind_dn: "{{ ldap_bind_dn }}"
        bind_pw: "{{ ldap_bind_pw }}"
        server_uri: "ldap://{{ ldap_server }}"
      register: add_entry_result

If i change the state absent, it is working fine for deleting the entries, but it is not able to add new entry

### Issue Type

Bug Report

### Component Name

community.general.ldap_entry module 

### Ansible Version

ansible [core 2.15.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/d/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/d/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/d/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/a-dkushwah/.local/bin/ansible
  python version = 3.9.18 (main, Oct  4 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

Collection        Version
----------------- -------
community.general 10.1.0 

\\

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
default
```

### OS / Environment

RHEL9

### Steps to Reproduce

```yaml (paste below)
    - name: Create LDAP Entry with Attributes
      community.general.ldap_entry:
        dn: "cn={{ ldap_user_cn }},nismapname={{ nismapname }},ou={{ ou }},{{ automount_base_dn }}"
        objectClass:
          - top
          - nisObject
        attributes:
          cn: "{{ ldap_user_cn }}"
          nismapName: "{{ nismapname }}"
          nisMapEntry: "{{ nis_map_entry }}"
        state: present
        bind_dn: "{{ ldap_bind_dn }}"
        bind_pw: "{{ ldap_bind_pw }}"
        server_uri: "ldap://{{ ldap_server }}"
      register: add_entry_result


```

### Expected Results

It should create new entry

### Actual Results

```console (paste below)
TASK [Display Result of Adding LDAP Entry] ******************************************************************************************************
ok: [localhost] => {
    "add_entry_result": {
        "changed": false,
        "failed": false,
    }
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
