### ISSUE TITLE
Add inventory plugin iocage

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#9261]
### Summary

FreeBSD *iocage* Jail manager provides lists of jails. Use it to create dynamic inventory.

### Issue Type

Feature Idea

### Component Name

New inventory plugin *iocage*

### Additional Information

Example of the jail list

```bash
shell> ssh admin@10.1.0.18 iocage list
+------+----------+-------+--------------+------------+
| JID  |   NAME   | STATE |   RELEASE    |    IP4     |
+======+==========+=======+==============+============+
| None | test_101 | down  | 13.4-RELEASE | 10.1.0.101 |
+------+----------+-------+--------------+------------+
| None | test_102 | down  | 13.4-RELEASE | 10.1.0.102 |
+------+----------+-------+--------------+------------+
| None | test_103 | down  | 13.4-RELEASE | 10.1.0.103 |
+------+----------+-------+--------------+------------+
```

Example of the inventory configuration file

```yaml
shell> cat iocage.yml
plugin: community.general.iocage
host: 10.1.0.18
user: admin
groups:
    test: inventory_hostname.startswith('test')
```

The playbook

```yaml
 shell> cat pb-test.yml
- hosts: test

  tasks:

    - debug:
        msg: |
          inventory_hostname: {{ inventory_hostname }}
          {% for var in q('varnames', 'iocage_*') %}
          {{ var }}: {{ lookup('vars', var) }}
          {% endfor %}

    - debug:
        var: groups
      run_once: true
```

gives

```yaml 
shell> ansible-playbook pb-test.yml -i iocage.yml 

PLAY [test] ****************************************************************************************

TASK [debug] ****************************************************************************************
ok: [test_101] => 
  msg: |-
    inventory_hostname: test_101
    iocage_jid: -
    iocage_boot: off
    iocage_state: down
    iocage_type: jail
    iocage_release: 13.4-RELEASE-p2
    iocage_ip4: 10.1.0.101
    iocage_ip6: -
    iocage_template: ansible_client
    iocage_basejail: yes
ok: [test_102] => 
  msg: |-
    inventory_hostname: test_102
    iocage_jid: -
    iocage_boot: off
    iocage_state: down
    iocage_type: jail
    iocage_release: 13.4-RELEASE-p2
    iocage_ip4: 10.1.0.102
    iocage_ip6: -
    iocage_template: ansible_client
    iocage_basejail: yes
ok: [test_103] => 
  msg: |-
    inventory_hostname: test_103
    iocage_jid: -
    iocage_boot: off
    iocage_state: down
    iocage_type: jail
    iocage_release: 13.4-RELEASE-p2
    iocage_ip4: 10.1.0.103
    iocage_ip6: -
    iocage_template: ansible_client
    iocage_basejail: yes

TASK [debug] ****************************************************************************************
ok: [test_101] => 
  groups:
    all:
    - test_101
    - test_102
    - test_103
    test:
    - test_101
    - test_102
    - test_103
    ungrouped: []

PLAY RECAP ****************************************************************************************
test_101                   : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
test_102                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
test_103                   : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
