### ISSUE TITLE
htpasswd: Clarify in docs that module does not update password when crypt_scheme changes

### ISSUE THREAD

**Issue by fxedel** [ansible-collections/community.general#9267]
### Summary

We recently noticed that sites protected with basic auth were very slow to respond. After some research we pinpointed this to using a strong crypt_scheme (sha256_crypt) to hash passwords.

We had hoped to easily resolve this by changing crypt_scheme to apr_md5_crypt (the default). However, after changing this and doing an ansible run all htpasswd files remained unchanged.

Copied from https://github.com/ansible/ansible/issues/66802, but the problem still persists.

Since a fix does not seem to be easily implementable (see comment https://github.com/ansible-collections/community.general/issues/9267#issuecomment-2564844512), please update the documentation to mention this behavior.

### Issue Type

~~Bug Report~~

Documentation update

### Component Name

htpasswd

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.4
  config file = ./ansible.cfg
  configured module search path = ['./.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.pyenv/versions/3.6.6/envs/ansible/lib/python3.6/site-packages/ansible
  executable location = ~/.pyenv/versions/ansible/bin/ansible
  python version = 3.6.6 (default, Aug 29 2018, 17:15:42) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
...
```

### Configuration

```console (paste below)
ANSIBLE_PIPELINING(./ansible.cfg) = True
DEFAULT_FORKS(./ansible.cfg) = 5
DEFAULT_HOST_LIST(./ansible.cfg) = ['./provisioning/hosts']
DEFAULT_ROLES_PATH(./ansible.cfg) = ['./.ansible/roles']
DEFAULT_STDOUT_CALLBACK(./ansible.cfg) = debug
```

### OS / Environment

On the server passlib==1.7.1

### Steps to Reproduce

Start of with a task similar to this:

```yaml (paste below)
  name: Manage htpasswd file
  htpasswd:
    path: "{{ basic_auth_file }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: "{{ item.state|default('present') }}"
    crypt_scheme: sha256_crypt
  with_items: "{{ basic_auth_users }}"
  no_log: True
```

Run ansible.

Then change `crypt_scheme` to `apr_md5_crypt`

Run ansible again.

### Expected Results

I expected the htpasswd files to be updated with the password hashed using the configured crypt_scheme.

### Actual Results

The htpasswd files remain unchanged.

```console (paste below)
Ansible logs: [user] already present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
