### ISSUE TITLE
Need opinion about PR about `prepend_hash` doesn't always work as expected in Slack module

### ISSUE THREAD

**Issue by Aohzan** [ansible-collections/community.general#9269]
### Summary

`prepend_hash: auto` prefix or not the channel put in the channel parameter with a # with this rule `if channel.startswith(('#', '@', 'C0', 'GF', 'G0', 'CP')):` https://github.com/Aohzan/community.general/blob/3a24aa5b6d92589a655e37113653c312d7bf72d8/plugins/modules/slack.py#L322

I have a channel id which starts with `CJ`. I don't know if I should make a PR to add it in the list, or we should no more have a `auto` value because channel_id doesn't always starts with known values ? Otherwise just put in the doc that when you want to edit a message, set `prepend_hash` to  `never` to be sure that no `#` is added.

### Issue Type

Bug Report

### Component Name

slack

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.7]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
10.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

with `previous_slack_task.channel: CJxxxxx
```yaml
        community.general.slack:
          token: "{{ my token }}"
          channel: "{{ previous_slack_task.channel }}"
          msg: "edited message"
          message_id: "{{ previous_slack_task.ts }}"
```

### Expected Results

changed

### Actual Results

```console (paste below)
error: channel_not_found
msg: Slack API error
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
