### ISSUE TITLE
ini_file module will replace all options with no value, if only one option has no value (using allow_no_value: true)

### ISSUE THREAD

**Issue by odinu** [ansible-collections/community.general#9296]
### Summary

I have this task
```
    - name: pacman.conf settings
      ini_file:
        path: /etc/pacman.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        allow_no_value: true
      with_items:
        - { section: options, option: ParallelDownloads, value: 5 }
        - { section: multilib, option: Include, value: /etc/pacman.d/mirrorlist }
        - { section: options, option: Color, value: null }
```

2 options have values, 1 doesn't. When applying, all values get removed.

### Issue Type

Bug Report

### Component Name

ini_file

### Ansible Version

```console (paste below)
$ ansible --version
[DEPRECATION WARNING]: PARAMIKO_LOOK_FOR_KEYS option. Reason: This option was moved to the plugin itself Alternatives: Use the option from the plugin itself. This feature will be removed in version 2.20. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.18.1]
  config file = /home/dncrash/repos/lansible/ansible.cfg
  configured module search path = ['/home/dncrash/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/dncrash/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
[DEPRECATION WARNING]: PARAMIKO_LOOK_FOR_KEYS option. Reason: This option was moved to the plugin itself Alternatives: Use the option from the plugin itself. This feature will be removed in version 2.20. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

# /usr/lib/python3.12/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.1.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml (paste below)
    - name: pacman.conf settings
      ini_file:
        path: /etc/pacman.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        allow_no_value: true
      with_items:
        - { section: options, option: ParallelDownloads, value: 5 }
        - { section: multilib, option: Include, value: /etc/pacman.d/mirrorlist }
        - { section: options, option: Color, value: null }
```

### Expected Results

I expect options with values to be added with their respective values, and options without to work as well, without any value.

### Actual Results

```console (paste below)
TASK [pacman.conf settings] *************************************************************************************************************************************************************************************
--- before: /etc/pacman.conf (content)
+++ after: /etc/pacman.conf (content)
@@ -40,6 +40,7 @@
 # trusts (see pacman-key and its man page), as well as unsigned packages.
 SigLevel    = Required DatabaseOptional
 LocalFileSigLevel = Optional
+ParallelDownloads
 #RemoteFileSigLevel = Required
 
 # NOTE: You must run `pacman-key --init` before first using pacman; the local

changed: [localhost] => (item={'section': 'options', 'option': 'ParallelDownloads', 'value': 5})
--- before: /etc/pacman.conf (content)
+++ after: /etc/pacman.conf (content)
@@ -92,6 +92,7 @@
 
 [multilib]
 Include = /etc/pacman.d/mirrorlist
+Include
 
 # An example of a custom package repository.  See the pacman manpage for
 # tips on creating your own repositories.

changed: [localhost] => (item={'section': 'multilib', 'option': 'Include', 'value': '/etc/pacman.d/mirrorlist'})
--- before: /etc/pacman.conf (content)
+++ after: /etc/pacman.conf (content)
@@ -30,7 +30,7 @@
 
 # Misc options
 #UseSyslog
-#Color
+Color
 #NoProgressBar
 CheckSpace
 #VerbosePkgLists
@@ -40,6 +40,7 @@
 # trusts (see pacman-key and its man page), as well as unsigned packages.
 SigLevel    = Required DatabaseOptional
 LocalFileSigLevel = Optional
+Color
 #RemoteFileSigLevel = Required
 
 # NOTE: You must run `pacman-key --init` before first using pacman; the local

changed: [localhost] => (item={'section': 'options', 'option': 'Color', 'value': None})
```
Options with values are having their values deleted.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
