### ISSUE TITLE
htpasswd does not report changes when updating ownership

### ISSUE THREAD

**Issue by sdm-tim-strong** [ansible-collections/community.general#9485]
### Summary

When updating 'owner' or 'group' properties with community.general.htpasswd, the change is applied correctly to the target host but zero changes are reported.  Any changes to the target host should be reported as a change.

### Issue Type

Bug Report

### Component Name

htpasswd

### Ansible Version

```
ansible [core 2.16.0]
  config file = /etc/ansible/ansible-9.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/venv/ansible-9/lib/python3.10/site-packages/ansible
  ansible collection location = /root/venv/ansible-9/lib/python3.10/site-packages/ansible_collections
  executable location = /root/venv/ansible-9/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/root/venv/ansible-9/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Community.general Version

```
$ Collection        Version
----------------- -------
community.general 10.1.0

```

### Configuration

```

```

### OS / Environment

Ubuntu 22.04 LTS

### Steps to Reproduce

```
- name: Configure htpasswd file
  community.general.htpasswd:
    path: /etc/nginx/htpasswd
    name: "{{ htpasswd_user_name }}"
    password: "{{ htpasswd_user_pass }}"
    owner: root
    group: www-data
    mode: "0640"
```

### Expected Results

Group ownership is updated on the filesystem as expected but no change is reported during the Ansible play.

### Actual Results

```
PLAY RECAP ********************************************************************************************************************************************************************************************************
server-1                 : ok=59   changed=0    unreachable=0    failed=0    skipped=7    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
