### ISSUE TITLE
nmcli: Add support for firewalld Zones

### ISSUE THREAD

**Issue by sullome** [ansible-collections/community.general#949]
##### SUMMARY

It would be nice to have the ability to set `zone` parameter for connections.
This allows Network Manager to automatically add interfaces into firewalld zones.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nmcli
##### ADDITIONAL INFORMATION

What I mean is a possibility to write a task like that:

```yaml
- name: Add interface
  nmcli:
    conn_name: my-eth1
    ifname: eth1
    type: ethernet
    ip4: 192.0.2.100/24
    gw4: 192.0.2.1
    zone: internal
    state: present
```
