### ISSUE TITLE
Add parameter sudo to inventory plugin iocage

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#9572]
### Summary

When DHCP is enabled, for example

```bash
shell> iocage get dhcp test_111
1
```
An unprivileged user can run the command *"iocage list -l"* but the IP4 tab says: *"DHCP (running -- address requires root)"*

```bash
shell> whoami
admin
shell> iocage list -l
+------+----------------+------+-------+------+-----------------+-----------------------------------------+-----+----------------+----------+
| JID  |      NAME      | BOOT | STATE | TYPE |     RELEASE     |                   IP4                   | IP6 |    TEMPLATE    | BASEJAIL |
+======+================+======+=======+======+=================+=========================================+=====+================+==========+
| None | ansible_client | off  | down  | jail | 14.1-RELEASE-p6 | -                                       | -   | -              | yes      |
+------+----------------+------+-------+------+-----------------+-----------------------------------------+-----+----------------+----------+
| 5    | test_111       | off  | up    | jail | 14.1-RELEASE-p6 | DHCP (running -- address requires root) | -   | ansible_client | yes      |
+------+----------------+------+-------+------+-----------------+-----------------------------------------+-----+----------------+----------+
```

As a consequence, the inventory plugin *community.general.iocage*

```yaml
shell> cat iocage.yml 
plugin: community.general.iocage
host: 10.1.0.73
user: admin
```

creates the below inventory

```yaml
shell> ansible-inventory -i iocage.yml --list --yaml
all:
  children:
    ungrouped:
      hosts:
        ansible_client:
          iocage_basejail: 'yes'
          iocage_boot: 'off'
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: '-'
          iocage_ip6: '-'
          iocage_jid: None
          iocage_release: 14.1-RELEASE-p6
          iocage_state: down
          iocage_template: '-'
          iocage_type: jail
        test_111:
          iocage_basejail: 'yes'
          iocage_boot: 'off'
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '5'
          iocage_release: 14.1-RELEASE-p6
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
```

A root account is needed to get the IP4 address

```bash
shell> whoami
root
shell> iocage list -l
+------+----------------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
| JID  |      NAME      | BOOT | STATE | TYPE |     RELEASE     |        IP4         | IP6 |    TEMPLATE    | BASEJAIL |
+======+================+======+=======+======+=================+====================+=====+================+==========+
| None | ansible_client | off  | down  | jail | 14.1-RELEASE-p6 | -                  | -   | -              | yes      |
+------+----------------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
| 5    | test_111       | off  | up    | jail | 14.1-RELEASE-p6 | epair0b|10.1.0.174 | -   | ansible_client | yes      |
+------+----------------+------+-------+------+-----------------+--------------------+-----+----------------+----------+
```

### Issue Type

Feature Idea

### Component Name

plugins/inventory/iocage.py

### Additional Information

Add parameter *sudo*

```yaml
shell> cat iocage.yml 
plugin: community.general.iocage
host: 10.1.0.73
user: admin
sudo: true
```

The inventory plugin *community.general.iocage* gets the IP4 address of the running DHCP jail

```yaml
shell> ansible-inventory -i iocage.yml --list --yaml
all:
  children:
    ungrouped:
      hosts:
        ansible_client:
          iocage_basejail: 'yes'
          iocage_boot: 'off'
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: '-'
          iocage_ip6: '-'
          iocage_jid: None
          iocage_release: 14.1-RELEASE-p6
          iocage_state: down
          iocage_template: '-'
          iocage_type: jail
        test_111:
          iocage_basejail: 'yes'
          iocage_boot: 'off'
          iocage_ip4: 10.1.0.174
          iocage_ip4_dict:
            ip4:
            - ifc: epair0b
              ip: 10.1.0.174
              mask: '-'
            msg: ''
          iocage_ip6: '-'
          iocage_jid: '5'
          iocage_release: 14.1-RELEASE-p6
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
