### ISSUE TITLE
proxmox_kvm: Only show changed when something managed actually changes

### ISSUE THREAD

**Issue by pgporada** [ansible-collections/community.general#9576]
### Summary

When running ansible against my proxmox cluster, every VM managed by `proxmox_kvm` reports changes when realistically none should. I implementing a very janky config diff which shows that unmanageable results from the PVE API affect the `proxmox_kvm` module.

Here's my diff tool
```
- name: Check existing config
  community.general.proxmox_vm_info:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    node: "{{ groups.proxmox_nodes[0] }}"
    name: "{{ hostname }}"
    config: "current"
  register: current_config

# Pending changes indicate that we should restart a VM, but _not always_.
- name: Check for pending changes
  community.general.proxmox_vm_info:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    node: "{{ groups.proxmox_nodes[0] }}"
    name: "{{ hostname }}"
    config: "pending"
  register: pending_config

- name: Diff current vs pending
  ansible.utils.fact_diff:
    before: "{{ current_config | to_nice_yaml }}"
    after: "{{ pending_config | to_nice_yaml }}"
```

Versions of various relevant software I'm using.
```
$ ansible --version
ansible [core 2.14.16]

$ pip list | grep proxmoxer
proxmoxer          2.2.0

$ ansible-galaxy collection list | grep community.general
community.general 10.2.0
```

### Issue Type

Feature Idea

### Component Name

proxmox_kvm

### Additional Information

```
TASK [proxmox/ansible-role-proxmox-manage-vm : Check existing config] ***********************************************************************************************************************
ok: [localhost]

TASK [proxmox/ansible-role-proxmox-manage-vm : Check for pending changes] *******************************************************************************************************************
ok: [localhost]

TASK [proxmox/ansible-role-proxmox-manage-vm : Diff current vs pending] *********************************************************************************************************************
--- before
+++ after
@@ -40,7 +40,7 @@
         vcpus: 4
         vga: serial0
         vmgenid: 2ae6c662-49e7-47fa-b9c0-4397c572854a
-    cpu: 0.00230293270089206
+    cpu: 0
     cpus: 4
     disk: 0
     diskread: 0
@@ -52,7 +52,7 @@
     mem: 177890429
     name: localhost.dev.mybox
     netin: 0
-    netout: 6050
+    netout: 6092
     node: pr0xch0pz
     pid: 616019
     serial: 1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/proxmox_kvm.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/proxmox_kvm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @UnderGreen @helldorado @joshainglis @karmab @krauthosting
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
Hi @pgporada thanks for reporting

Not all values returned by proxmox_vm_info are configurations, some of them are metrics, like `cpu` in your diff. It is obtained from:
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/resources

The documentation of `proxmox_vm_info` could be more clear about this, but the evidence presented does not seem to point to a problem with `proxmox_kvm`.

**Comment by pgporada** [comment]
I came up with this which is good enough for me.
```
- name: Diff original vs new VM config
  ansible.utils.fact_diff:
    # We remove metrics that the Proxmox API returns to proxmoxer because we
    # don't care about the metrics when wanting to understand what actually has
    # changed between the previous and new VM configuration. Lastly, the digest
    # key is superfluous because we'll see the differing object here.
    before: "{{ original_vm_config | ansible.utils.remove_keys(target=['^digest$', '^cpu$', '^mem$', '^netin$', '^netout$', '^uptime$', '^diskread$', '^diskwrite$', '^pid$'], matching_parameter='regex') }}"
    after: "{{ new_vm_config | ansible.utils.remove_keys(target=['^digest$', '^cpu$', '^mem$', '^netin$', '^netout$', '^uptime$', '^diskread$', '^diskwrite$', '^pid$'], matching_parameter='regex') }}"
```
