### ISSUE TITLE
proxmox: error by creating an lxc container when providing public ssh key of the root user

### ISSUE THREAD

**Issue by alexejpissarev** [ansible-collections/community.general#9642]
### Summary

When I try to create a new lxc container with `community.general.proxmox` from the community.general version 8.3.0, it breaks with the error message `'An error occurred: 400 Bad Request: Parameter verification failed. - {''ssh-public-key'': ''property is not defined in schema and the schema does not allow additional properties''}'`

This error occurs only if I provide a public ssh key of the root user with the option `pubkey`:
```
- name: Container exists
  community.general.proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_techuser }}"
    api_token_id: "{{ proxmox_techuser_token_id }}"
    api_token_secret: "{{ proxmox_techuser_token_secret }}"
    cores: "{{ lxc_create_cores }}"
    cpuunits: "{{ lxc_create_cpuunits }}"
    hostname: "{{ lxc_create_hostname }}"
    features: "{{ lxc_create_features }}"
    memory: "{{ lxc_create_memory }}"
    mounts: "{{ lxc_create_mounts }}"
    netif: "{{ lxc_create_network }}"
    onboot: "{{ lxc_create_onboot }}"
    ostemplate: "{{ lxc_create_ostemplate }}"
    password: "{{ lxc_create_root_password }}"
    pool: "{{ lxc_create_pool }}"
    pubkey: "{{ lxc_create_root_pubkey }}"
    storage: "{{ lxc_create_storage }}"
    swap: "{{ lxc_create_swap }}"
    vmid: "{{ lxc_create_id }}"
    state: "present"
  delegate_to: localhost
```

This task works find if I omit `pubkey`
Also it worked with community.general versions prior 8.3.0.

Probably there is a typo in the API call?
I see the parameter `ssh-public-keys` (not `ssh-public-key`) in the [proxmox API](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc)

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.1]
  config file = /builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg
  configured module search path = ['/home/ci-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible-core/lib/python3.13/site-packages/ansible
  ansible collection location = /home/ci-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.1 (main, Dec 25 2024, 01:33:28) [GCC 12.2.0] (/opt/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /home/ci-user/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg
DEFAULT_FORCE_HANDLERS(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = True
DEFAULT_HOST_LIST(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = ['/builds/evita/infrastructure/proxyserver/inventory/infrastructure']
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /builds/evita/infrastructure/proxyserver/ansible.log
DEFAULT_PRIVATE_KEY_FILE(env: ANSIBLE_PRIVATE_KEY_FILE) = /home/ci-user/.ssh/id_ansible
DEFAULT_REMOTE_USER(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = root
DEFAULT_TIMEOUT(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = 180
DEFAULT_VAULT_IDENTITY_LIST(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = ['evita@/mnt/keys/evita_runner_secrets/evita_vault_master', 'rufus@/mnt/keys/rufus_runner_secrets/rufus_vault_master']
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 0
DISPLAY_SKIPPED_HOSTS(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = False
HOST_KEY_CHECKING(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = False
INTERPRETER_PYTHON(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = auto_silent
LOCALHOST_WARNING(/builds/evita/infrastructure/proxyserver/config/ansible_infrastructure.cfg) = False
GALAXY_SERVERS:
```

### OS / Environment

Ubuntu 22.04.5 LTS

### Steps to Reproduce

```yaml (paste below)
- name: Container exists
  community.general.proxmox:
    # node
    node: rufus
    api_host: 192.168.100.1
    api_user: <proxmox tech user>
    api_token_id: <proxmox techuser token id >
    api_token_secret: <proxmox techuser token>
    cores: 1
    cpuunits: 1000
    hostname: "test"
    features: ""
    memory: 512
    mounts: {rootfs: "local-zfs:8"}
    netif: {"net0": "name=eth0,gw=192.168.100.1,ip=192.168.100.184/24,bridge=vmbr100"}
    onboot: true
    ostemplate: "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    password: <root password>
    pool: stvit_machines
    pubkey: <root public ssh key>
    storage: "local-zfs"
    swap: 512
    vmid: 184
    state: "present"
  delegate_to: localhost
register: _results
delegate_to: localhost
until: _results is not failed
retries: 10
delay: 5
```

### Expected Results

- A new lxc container with the proxmox id `184` and hostname is created
- I can login as root via the proxmox console
- The root public ssh key is in the file /root/.ssh/authorized_keys

### Actual Results

```console (paste below)
TASK [evita.proxmox.lxc_create : Container exists] *****************************
fatal: [stvit-proxyserver-test -> localhost]: FAILED! => 
    attempts: 10
    changed: false
    msg: 'An error occurred: 400 Bad Request: Parameter verification failed. - {''ssh-public-key'':
        ''property is not defined in schema and the schema does not allow additional properties''}'
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* `plugins/modules/proxmox`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
@alexejpissarev I think you mean community.general 11.3.0, not 8.3.0.

@Lithimlin d71ba0fae80c4b47074c2472c96a086fa39f595a replaced `ssh-public-keys` with `ssh-public-key`. Was that change intentional?

**Comment by alexejpissarev** [comment]
> [@alexejpissarev](https://github.com/alexejpissarev) I think you mean community.general 11.3.0, not 8.3.0.
> 
> [@Lithimlin](https://github.com/Lithimlin) [d71ba0f](https://github.com/ansible-collections/community.general/commit/d71ba0fae80c4b47074c2472c96a086fa39f595a) replaced `ssh-public-keys` with `ssh-public-key`. Was that change intentional?

@felixfontein : sorry, you are right - I meant not the community.general version 8.3.0 but rather the last released one - 10.3.0

Also I tried to implement a workaround - first create an lxc container (without using the community.general.proxmox option `pubkey`) and then update resp. create the authorized_keys of the root account.
The container was created but `authorized_keys` had not materialized.

**Steps to Reproduce**
```
- name: Container exists
  community.general.proxmox:
    node: rufus
    api_host: 192.168.100.1
    api_user: <proxmox tech user>
    api_token_id: <proxmox techuser token id >
    api_token_secret: <proxmox techuser token>
    cores: 1
    cpuunits: 1000
    hostname: "test"
    features: ""
    memory: 512
    mounts: {rootfs: "local-zfs:8"}
    netif: {"net0": "name=eth0,gw=192.168.100.1,ip=192.168.100.184/24,bridge=vmbr100"}
    onboot: true
    ostemplate: "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    password: <root password>
    pool: stvit_machines
    storage: "local-zfs"
    swap: 512
    vmid: 184
    state: "present"
  delegate_to: localhost
register: _results
delegate_to: localhost
until: _results is not failed
retries: 10
delay: 5

- name: Wait till container is ready
  community.general.proxmox_vm_info:
    node: rufus
    api_host: 192.168.100.1
    api_user: <proxmox tech user>
    api_token_id: <proxmox techuser token id>
    api_token_secret: <proxmox techuser token>
    vmid: 184
  delegate_to: localhost
  register: _results
  until: >
    _results.proxmox_vms is defined and
    (_results.proxmox_vms[0].status == "stopped" or
    _results.proxmox_vms[0].status == "running")
  retries: 10
  delay: 5

- name: Authorized key file exists
  community.general.proxmox:
    vmid: 184
    node: rufus
    api_user: <proxmox tech user>
    api_host: 192.168.100.1
    api_token_id: <proxmox techuser token id>
    api_token_secret: <proxmox techuser token>
    hostname: "test"
    pubkey: <ssh public key>
    update: true
  delegate_to: localhost
```

**Expected Results**
- lxc container 184 is created
- root has got the password <root password>
- file /root/.ssh/authorized_keys is created and contains the public ssh key <ssh public key>
- ansible logs changes by creating of the container and added a public ssh key:
TASK [evita.proxmox.lxc_create : Container exists] *****************************
changed: [test -> localhost]
TASK [evita.proxmox.lxc_create : Wait till container is ready] *****************
ok: [test -> localhost]
TASK [evita.proxmox.lxc_create : Authorized key file exists] ***
changed: [test -> localhost]```
```

**Actual Results**
- lxc container 184 is created
- root has got the password <root password>
- directory /root/.ssh is absent
- ansible only logs a changes by creating of the container:
TASK [evita.proxmox.lxc_create : Container exists] *****************************
changed: [test -> localhost]
TASK [evita.proxmox.lxc_create : Wait till container is ready] *****************
ok: [test -> localhost]
TASK [evita.proxmox.lxc_create : Authorized key file exists] ***
ok: [test -> localhost]```
```

It looks like the option "update" doesn't work this way either, but this seems to be a different issue (if any)
