### ISSUE TITLE
Add parameter hooks to inventory plugin iocage

### ISSUE THREAD

**Issue by vbotka** [ansible-collections/community.general#9650]
### Summary

(Use case: root access on the iocage host is not needed to create inventory.)

The parameter *hooks* is a list of files inside a jail that provide configuration parameters for the inventory. For example,

```yaml
hooks:
  - /var/db/dhclient-hook.address.epair0b
```

may provide the IP address of the interface epair0b, obtained by dhclient. Then, the inventory plugin creates the variable *iocage_hooks*

```yaml
    iocage_hooks:
    - 10.1.0.130
```

This can be used to compose *ansible_host*

```yaml
compose:
  ansible_host: iocage_hooks.0
```

Privilege escalation is not needed if the file * /var/db/dhclient-hook.address.epair0b* is readable by the user logged on to the iocage host.

As a side note: the file in the above example is created by this hook

```sh
shell> cat /etc/dhclient-exit-hooks 
case "$reason" in
    "BOUND"|"REBIND"|"REBOOT"|"RENEW")
    echo $new_ip_address > /var/db/dhclient-hook.address.$interface
    ;;
esac
```

### Issue Type

Feature Idea

### Component Name

plugins/inventory/iocage.py

### Additional Information

Given the jails

```sh
shell> iocage list -lh
38	test_101	off	up	jail	13.4-RELEASE-p2	epair0b|10.1.0.130	-	ansible_client	no
39	test_102	off	up	jail	13.4-RELEASE-p2	epair0b|10.1.0.245	-	ansible_client	no
40	test_103	off	up	jail	13.4-RELEASE-p2	epair0b|10.1.0.180	-	ansible_client	no
```

the configuration

```yaml (paste below)
shell> cat iocage.yml
plugin: community.general.iocage
host: 10.1.0.18
user: admin
hooks:
  - /var/db/dhclient-hook.address.epair0b
compose:
  ansible_host: iocage_hooks.0
groups:
  test_01: inventory_hostname.startswith('test')
```

gives

```yaml
shell> ansible-inventory -i iocage.yml --list --yaml
all:
  children:
    test_01:
      hosts:
        test_101:
          ansible_host: 10.1.0.130
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.130
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '38'
          iocage_release: 13.4-RELEASE-p2
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
        test_102:
          ansible_host: 10.1.0.245
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.245
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '39'
          iocage_release: 13.4-RELEASE-p2
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
        test_103:
          ansible_host: 10.1.0.180
          iocage_basejail: 'no'
          iocage_boot: 'off'
          iocage_hooks:
          - 10.1.0.180
          iocage_ip4: '-'
          iocage_ip4_dict:
            ip4: []
            msg: DHCP (running -- address requires root)
          iocage_ip6: '-'
          iocage_jid: '40'
          iocage_release: 13.4-RELEASE-p2
          iocage_state: up
          iocage_template: ansible_client
          iocage_type: jail
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
