### ISSUE TITLE
Add `FullPowerCycle` to redfish_command Power allowed power commands

### ISSUE THREAD

**Issue by sseekamp** [ansible-collections/community.general#9683]
### Summary

Recently added in:
https://github.com/DMTF/Redfish/pull/6237

Please add FullPowerCycle to the available power commands in the module.

### Issue Type

Feature Idea

### Component Name

redfish_utils, redfish_command

### Additional Information

I would like to be able to:

```
- name: Restart system power gracefully
  community.general.redfish_command:
    category: Systems
    command: PowerFullPowerCycle
    resource_id: 437XR1138R2
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
```

and make use of the new power cycle type

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
