### ISSUE TITLE
ipa_host: Host certificates will be revoked

### ISSUE THREAD

**Issue by sedrubal** [ansible-collections/community.general#9693]
### Summary

We're using the `community.general.ipa_host` module to ensure, a host is present on our freeipa server. In another task, we fetch host certificates from freeipa for that host. However, running the `ipa_host` task again will revoke the host certificate. This seems to have changed in the past.

### Issue Type

Bug Report

### Component Name

ipa_host

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.2]
  config file = $path_to_repo/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.local/bin/ansible
  python version = 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0] (~/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console
$ ansible-galaxy collection list community.general

# ~/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.3.0
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_PIPELINING($path_to_repo/ansible.cfg) = True
CONFIG_FILE() = $path_to_repo/ansible.cfg
DEFAULT_HOST_LIST($path_to_repo/ansible.cfg) = ['$path_to_repo/custom_inventory_script.py>
DEFAULT_LOAD_CALLBACK_PLUGINS($path_to_repo/ansible.cfg) = True
DEFAULT_MANAGED_STR($path_to_repo/ansible.cfg) = Ansible managed. See https://$url_to_repo
DEFAULT_ROLES_PATH($path_to_repo/ansible.cfg) = ['$path_to_repo/roles', '$path_to_repo/roles-in-git-submodule']
DEFAULT_VAULT_ENCRYPT_IDENTITY($path_to_repo/ansible.cfg) = common
DEFAULT_VAULT_IDENTITY_LIST($path_to_repo/ansible.cfg) = ['common@./script-a.sh', 'private@./script-b.sh']
DEFAULT_VAULT_ID_MATCH($path_to_repo/ansible.cfg) = true
DIFF_ALWAYS($path_to_repo/ansible.cfg) = True
EDITOR(env: EDITOR) = nvim
MAX_FILE_SIZE_FOR_DIFF($path_to_repo/ansible.cfg) = 10000

GALAXY_SERVERS:
```

### OS / Environment

Debian 12 (and Ubuntu 22.04)

freeipa-server: 4.12.2

freeipa-client 4.9.11-1

### Steps to Reproduce

```yaml
- name: Ensure host is present in FreeIPA
  community.general.ipa_host:
    name: "{{ inventory_hostname }}"
    description: "{{ description | default('') }}"
    ip_address: "{{ ansible_host }}"
    ns_host_location: ""
    ns_os_version: "{{ ansible_facts['os_family'] }}:{{ ansible_facts['distribution_major_version'] }}"
    ns_hardware_platform: VM
    state: present
    update_dns: true
    random_password: true
    ipa_host: "{{ freeipa_servers | sort | first }}"
    ipa_user: "{{ kinit_user }}"
    ipa_pass: "{{ kinit_password }}"
  register: ipa_host_resp
  delegate_to: localhost
  become: false
```

- after that, download the host certificate manually
- Run this task again

### Expected Results

The manually downloaded certificate should still be valid

### Actual Results

The certificate was revoked during the second run of `community.general.ipa_host`

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
