### ISSUE TITLE
proxmox inventory: refresh_inventory not working with cache enabled

### ISSUE THREAD

**Issue by iqt4** [ansible-collections/community.general#9710]
### Summary

I have a dynamic proxmox inventory with cache enabled.
During a play I create an lxc container with community.general.proxmox module. 
After successfully creating the container I update the inventory with ansible.builtin.meta: refresh_inventory. 
However, the inventory get's updated in the play but not the cache.

### Issue Type

Bug Report

### Component Name

proxmox inventory

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.17.7]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 10.3.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /Users/dirk/Development/Ansible/ansible.cfg
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/dirk/Development/Ansible/ansible.cfg) = ['/Users/dirk/Development/Ansible/plugins/connection']
DEFAULT_HOST_LIST(/Users/dirk/Development/Ansible/ansible.cfg) = ['/Users/dirk/Development/Ansible/inventory']
DEFAULT_VAULT_IDENTITY_LIST(/Users/dirk/Development/Ansible/ansible.cfg) = ['default@files/keychain-client.sh']
```

### OS / Environment

MacOS Sequoia 15.3

### Steps to Reproduce

```yaml (paste below)
proxmox.yml

plugin: community.general.proxmox
# Dynamic Proxmox API URL from files/pve_vars.yml
url: "{% set vars = lookup('ansible.builtin.file', 'pve_vars.yml') | from_yaml %}
  https://{{ vars.pve_api_host }}:{{ vars.pve_api_port | default(8006) }}"

# Set REQUESTS_CA_BUNDLE or disable certificate validation
# validate_certs: false

# Read the credentials for the Proxmox API
# files/pve_vault links to inventory/host_vars/localhost/pve_vault
user: "{{ (lookup('ansible.builtin.unvault', 'pve_vault') | from_yaml)['vault_api_user'] }}"
token_id: "{{ (lookup('ansible.builtin.unvault', 'pve_vault') | from_yaml)['vault_api_token_id'] }}"
token_secret: "{{ (lookup('ansible.builtin.unvault', 'pve_vault') | from_yaml)['vault_api_token_secret'] }}"

# Cache for 1 hour (default)
cache: true
cache_plugin: jsonfile
cache_connection: .cache

Example playbook
- name: Create Debian container on Proxmox VE
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/community.general.proxmox:
      api_user: "{{ pve_api_user }}"
      api_token_id: "{{ pve_api_token_id }}"
      api_token_secret: "{{ pve_api_token_secret }}"
      api_host: "{{ pve_api_host }}"
  tasks:    
    - name: Assign variables
      ansible.builtin.set_fact:
        pve_node: pve-1
        ct_name: debian-t
        ostemplate: qnap:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst
        # proxmox_user: "{{ lookup('env', 'PROXMOX_USER') }}"
      # include_vars:
        # file: /path/to/your/vars_file.yml
    - name: Create Debian container # noqa: args[module]
      community.general.proxmox:
        node: "{{ pve_node }}"
        hostname: "{{ ct_name }}"
        password: "{{ lookup('password', '/dev/null', length=8, chars='ascii_letters', seed=ct_name) }}"
        ostemplate: "{{ ostemplate }}"
        disk: local-zfs:4
        features:
          - "nesting=1"
        cores: 1
        memory: 512
        netif:
          net0: "name=eth0,bridge=vmbr0,tag=1000,ip=dhcp"
        # update: true
        state: present
      notify: Refresh inventory

  handlers:
#    - name: Invalidate cache as a workaround
#      ansible.builtin.file:
#        path: "../.cache"
#        state: absent
#      listen: Refresh inventory
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
      listen: Refresh inventory

  post_tasks:
    - name: Wait for the container to be started # noqa: args[module]
      community.general.proxmox:
        vmid: "{{ hostvars[ct_name].proxmox_vmid }}"
        state: started

```

### Expected Results

If you run this play the first time, the lxc container is set up. The line `vmid: "{{ hostvars[ct_name].proxmox_vmid }}"` does not give an error and the container is started.

The cache should be updated as well and the play runs the second time (without cache update) without error.

### Actual Results

Timestamp (and content) of the cache file under .cache directory does not change. Play gives an error:
```console (paste below)
The task includes an option with an undefined variable.. "hostvars['debian-t']" is undefined 
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/inventory/proxmox.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/inventory/proxmox.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ajpantuso @Thulium-Drake @ilijamt @joshainglis @karmab @krauthosting
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Thulium-Drake** [comment]
As a first question, did you also see this behavior with other dynamic inventory plugins? From what I read in the code, there's no special handling of cached resources (except that the module is compatible with caches).

Also, you can't change the inventory mid-play, same goes with the ```add_host``` module, see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/add_host_module.html (first line of the synopsis), changing hosts is fine, but adding new ones requires a new play from the same playbook.

Which, unless I'm mistaken, should mean that it'll be fixed with this:

```
---
- name: Create Debian container on Proxmox VE
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/community.general.proxmox:
      api_user: "{{ pve_api_user }}"
      api_token_id: "{{ pve_api_token_id }}"
      api_token_secret: "{{ pve_api_token_secret }}"
      api_host: "{{ pve_api_host }}"
  tasks:    
    - name: Assign variables
      ansible.builtin.set_fact:
        pve_node: pve-1
        ct_name: debian-t
        ostemplate: qnap:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst
    - name: Create Debian container # noqa: args[module]
      community.general.proxmox:
        node: "{{ pve_node }}"
        hostname: "{{ ct_name }}"
        password: "{{ lookup('password', '/dev/null', length=8, chars='ascii_letters', seed=ct_name) }}"
        ostemplate: "{{ ostemplate }}"
        disk: local-zfs:4
        features:
          - "nesting=1"
        cores: 1
        memory: 512
        netif:
          net0: "name=eth0,bridge=vmbr0,tag=1000,ip=dhcp"
        # update: true
        state: present
      notify: Refresh inventory

  handlers:
#    - name: Invalidate cache as a workaround
#      ansible.builtin.file:
#        path: "../.cache"
#        state: absent
#      listen: Refresh inventory
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
      listen: Refresh inventory

- name: Wait for containers to start
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for the container to be started # noqa: args[module]
      community.general.proxmox:
        vmid: "{{ hostvars[ct_name].proxmox_vmid }}"
        state: started
```

**Comment by felixfontein** [comment]
Basically you *can* update the inventory, but you cannot change the hosts the current play works on. After using `meta: refresh_inventory` or `ansible.builtin.add_host`, the new host(s) is/are there and you can use it/them, for example with `delegate_to`, and you can see it/them in `groups['name-of-group']`, etc. But the hosts selected for this play are still the same, as selection is made at the beginning of the play, when the host wasn't/weren't there yet.

Here's a simple test with the ini inventory plugin:
```yaml
# Save as test-inventory.yml; also create an empty file test-inventory.ini.
# Run with:
# ansible-playbook test-inventory.yml -i test-inventory.ini

- name: Reset state
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Reset inventory file
      ansible.builtin.copy:
        dest: test-inventory.ini
        content: |
          [group]
          primary ansible_connection=local
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory

- name: Do something
  hosts: group
  gather_facts: false
  tasks:
    - name: Run command only on primary
      ansible.builtin.command:
        cmd: ls
    - name: Update inventory file
      ansible.builtin.copy:
        dest: test-inventory.ini
        content: |
          [group]
          primary ansible_connection=local
          secondary ansible_connection=local
    - name: Show group 'group', should still have one element
      ansible.builtin.debug:
        msg: "{{ groups.group }}"
      delegate_to: secondary
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory
    - name: Show group 'group', should now have two elements
      ansible.builtin.debug:
        msg: "{{ groups.group }}"
      delegate_to: secondary
    - name: Run a command on all hosts, which happens to be only primary
      ansible.builtin.command:
        cmd: ls
    - name: Run a command on all hosts, which happens to be only primary
      ansible.builtin.command:
        cmd: ls
      delegate_to: secondary

- name: Do more
  hosts: group
  gather_facts: false
  tasks:
    - name: Run a command on primary and secondary
      ansible.builtin.command:
        cmd: ls
    - name: Reset inventory file
      ansible.builtin.copy:
        dest: test-inventory.ini
        content: |
          [group]
          primary ansible_connection=local
      run_once: true
```

I also tried this out by removing primary in the updated inventory (commenting out line 30), the result is that basically the middle play stops after the inventory refresh since the host is gone. So while you cannot *add* new hosts, you can *remove* existing ones with immediate effect :) (Just checked that because I was curious, I know this wasn't the question here.)
