### ISSUE TITLE
community.general.dconf cannot properly process tuple and thus input sources return an empty list

### ISSUE THREAD

**Issue by kees-closed** [ansible-collections/community.general#9713]
### Summary

The following value is added to dconf:

```
/org/gnome/desktop/input-sources/sources
  [('xkb', 'us+altgr-intl')]
```

Which can also be set with the command line: `dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'us+altgr-intl')]"`

However, when trying to set this with the Ansible dconf module, I run into this issue. Note the last key/value, which uses the input sources.

```
  - name: Configure GNOME with dconf
    community.general.dconf:
      key: "{{ item.1.key }}"
      value: "{{ item.1.value }}"
    become_user: "{{ item.0.name }}"
    loop: "{{ users | product(tasks) | list }}"
    loop_control:
      label: "{{ item.0.name }}%{{ item.1.key }}"
    when:
      - item.0.name != "root"
      - item.0.state | default(true)
    vars:
      tasks:
        - key: /system/locale/region
          value: "'nl_NL.UTF-8'"
        - key: /org/gnome/nautilus/list-view/default-column-order
          value: "['name', 'size', 'type', 'owner', 'group', 'permissions', 'date_modified']"
        - key: /org/gnome/desktop/input-sources/sources
          value: "[('xkb', 'us+altgr-intl')]"
```

Dconf processes this as:

```
/org/gnome/desktop/input-sources/sources
  [['xkb', 'us+altgr-intl']]
```

Note the nested list, instead of the tuple. The syntax of quoting a list works fine with other values. But when a tuple is involved, things go wrong.

### Issue Type

Bug Report

### Component Name

dconf

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.14]
  config file = /var/home/user/git/ansible/ansible.cfg
  configured module search path = ['/var/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /var/home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.1 (main, Dec  9 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 9.5.3  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /var/home/user/git/ansible/ansible.cfg
DEFAULT_BECOME(/var/home/user/git/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/var/home/user/git/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/var/home/user/git/ansible/ansible.cfg) = sudo
DEFAULT_FORCE_HANDLERS(/var/home/user/git/ansible/ansible.cfg) = True
DEFAULT_FORKS(/var/home/user/git/ansible/ansible.cfg) = 8
DEFAULT_HOST_LIST(/var/home/user/git/ansible/ansible.cfg) = ['/var/home/user/git/ansible/hosts.cfg']
DEFAULT_JINJA2_EXTENSIONS(/var/home/user/git/ansible/ansible.cfg) = jinja2.ext.loopcontrols
DEFAULT_LOAD_CALLBACK_PLUGINS(/var/home/user/git/ansible/ansible.cfg) = True
DEFAULT_MANAGED_STR(/var/home/user/git/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S %z (%Z) by {uid} on {host}
DEFAULT_REMOTE_PORT(/var/home/user/git/ansible/ansible.cfg) = 900
DEFAULT_STDOUT_CALLBACK(/var/home/user/git/ansible/ansible.cfg) = community.general.yaml
DEFAULT_VAULT_PASSWORD_FILE(/var/home/user/git/ansible/ansible.cfg) = /var/home/user/git/ansible/.vault-pass
DIFF_ALWAYS(/var/home/user/git/ansible/ansible.cfg) = True
DIFF_CONTEXT(/var/home/user/git/ansible/ansible.cfg) = 3
EDITOR(env: EDITOR) = /usr/bin/vim
RETRY_FILES_ENABLED(/var/home/user/git/ansible/ansible.cfg) = False

```

### OS / Environment

Fedora 41 Silverblue

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

Run `dconf watch /`

Then run this:

```
  - name: Configure GNOME with dconf
    community.general.dconf:
      key: "{{ item.1.key }}"
      value: "{{ item.1.value }}"
    become_user: "{{ item.0.name }}"
    loop: "{{ users | product(tasks) | list }}"
    loop_control:
      label: "{{ item.0.name }}%{{ item.1.key }}"
    when:
      - item.0.name != "root"
      - item.0.state | default(true)
    vars:
      tasks:
        - key: /system/locale/region
          value: "'nl_NL.UTF-8'"
        - key: /org/gnome/nautilus/list-view/default-column-order
          value: "['name', 'size', 'type', 'owner', 'group', 'permissions', 'date_modified']"
        - key: /org/gnome/desktop/input-sources/sources
          value: "[('xkb', 'us+altgr-intl')]"
```

It will not set the input source, it will be an empty list, because of the nested list, which should be a tuple.

### Actual Results

```console (paste below)
  - key: /org/gnome/desktop/input-sources/sources                                                                                                                                                value: '[(''xkb'', ''us+altgr-intl'')]'   
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
