### ISSUE TITLE
Add `creates` and `when` to `community.general.make`

### ISSUE THREAD

**Issue by Lonerider2010** [ansible-collections/community.general#9732]
### Summary

Base on [this](https://forum.ansible.com/t/get-community-general-make-task-idempotent/40196) discussion, I would like to suggest adding
either `creates` and/or `when` to the `community.general.make` module.
This would support and ease a way to make tasks idempotent that use this module.
In my case the `make` command generates a new file, and as I cannot use `creates`, with each loop of the playbook, the `make` command is executed again and again. 

### Issue Type

Feature Idea

### Component Name

make

### Additional Information

```yaml (paste below)
        - name: Build the BIMP target
          community.general.make:
            chdir: /opt/gimp-plugin-bimp
            creates: /opt/gimp-plugin-bimp/bin/bimp
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/make.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/make.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @LinusU
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by russoz** [comment]
As commented in the forum (link above), I think this can be easily sorted out using `stat` and `when`.

**Comment by LeSpocky** [comment]
> As commented in the forum (link above), I think this can be easily sorted out using `stat` and `when`, it feels like bloating the module more than needed. My $0.02.

I think 'stat' would only be a workaround here, but the actual cause is the module is not idempotent.  Let me explain.

I'm using *community.general.make* to call make for creating 'diff-highlight' on Debian like this:

```yaml
    # not idempotent                                                    
    - name: Ensure git contrib script diff-highlight is in place        
      community.general.make:                                           
        chdir: /usr/share/doc/git/contrib/diff-highlight                
      tags: make                                                        
```

When calling `make` in that directory, the artefact is created once.  As long as dependencies to the relevant make target do not change, `make` itself won't regenerate the artefact.  However the task always reports "changed".  Would be nice if the module would call make all the time, but only report "changed" if make actually changed anything.
