### ISSUE TITLE
hpilo_boot task with the option state: boot_once should not fail if the server is already on

### ISSUE THREAD

**Issue by christian-naenny** [ansible-collections/community.general#9737]
### Summary

In the idea of the idempotency of Ansible plays and tasks, I would like to suggest that the following task should not fail but rather just skip if the server is already on:
```
- name: Power on a server
  community.general.hpilo_boot:
    host: YOUR_ILO_HOST
    login: YOUR_ILO_LOGIN
    password: YOUR_ILO_PASSWORD
    state: boot_once

```
Of course, if the option **force: true** is set, the server should still be rebooted.

### Issue Type

Feature Idea

### Component Name

hpilo_boot

### Additional Information

```yaml (paste below)
- name: Power on a server
  community.general.hpilo_boot:
    host: YOUR_ILO_HOST
    login: YOUR_ILO_LOGIN
    password: YOUR_ILO_PASSWORD
    state: boot_once
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
