### ISSUE TITLE
lvol doesn't recognize opts parameter on lvextend

### ISSUE THREAD

**Issue by rbragasilva** [ansible-collections/community.general#9741]
### Summary

When we use lvol in a logical volume that its striped the module with an error:

"rc": 5,
  "err": "  Please specify number of stripes (-i) and stripesize (-I)\n",
  "msg": "Unable to resize lvname to 629043.2000000001K",

### Issue Type

Bug Report

### Component Name

lvol

### Ansible Version

```console (paste below)
$ ansible --version
2.15.12
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
Collection        Version
----------------- -------
community.general 10.0.1

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

RHEL8

### Steps to Reproduce

```yaml (paste below)
 - name: "Extending  paths over {{ threshold }} percent in {{ increase_percent }} percent"
    when: item | length > 0
    become: yes
    lvol:
      vg: "{{ item.split()[1] }}"
      lv: "{{ item.split()[0] }}"
      size: "+{{ item.split()[2] | int * ( increase_percent / 100.0) }}K"
      resizefs: true
      shrink: false
      force: no
      opts: -i 1
    register: extendpaths
    with_items: "{{ vg_lv_size }}"
    failed_when: extendpaths.failed == "true" 
    changed_when: true
```

### Expected Results

Logical Volume correctly extended 

### Actual Results

```console (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
