### ISSUE TITLE
proxmox  fails to remove non-existing container

### ISSUE THREAD

**Issue by toxic0berliner** [ansible-collections/community.general#9781]
### Summary

seems to me there is an issue with idempotency here, this task 
```
- name: Delete container
      connection: local
      vars: 
        ansible_python_interpreter: "auto_silent"
      community.general.proxmox:
        vmid: "{{ pveid }}"
        api_user: "{{ pveuser }}"
        api_token_id: "{{ pvetokenid }}"
        api_token_secret: "{{ pvetokensecret }}"
        api_host: "{{ pvehost }}"
        purge: true
        state: "absent"
      async: 60
      poll: 5
```
Fails with 
`fatal: [myCT]: FAILED! => {"ansible_job_id": "j448960346785.30435", "changed": false, "finished": 1, "msg": "could not find job", "results_file": "/home/semaphore/.ansible_async/j448960346785.30435", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}` when running it in my semaphore instance
All other tasks work fine and thare is no issue when the CT exists...

I found the j44... file it talks about, here it is  
```
{"changed": false, "vmid": 663, "msg": "VM 663 does not exist",
"invocation": {"module_args":
{"vmid": 663, "api_user": "XXXXXX@YYYYYYY", "api_token_id": "ansible",
"api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"api_host": "mpvehost", "purge": true,
"state": "absent", "validate_certs": false, "ostype": "auto", "storage": "local",
"timeout": 30, "update": false, "force": false,
"unprivileged": true, "proxmox_default_behavior": "no_defaults",
"clone_type": "opportunistic", "api_password": null, "node": null, "pool": null,
"password": null, "hostname": null, "ostemplate": null, "disk": null, "cores": null,
"cpus": null, "memory": null, "swap": null, "netif": null, "mounts": null, "ip_address": null,
"onboot": null, "features": null, "startup": null, "cpuunits": null, "nameserver": null,
"searchdomain": null, "pubkey": null, "description": null, "hookscript": null, "timezone": null, "clone": null, "tags": null}}}
```

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.16.8]
  config file = /tmp/semaphore/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/semaphore/apps/ansible/9.4.0/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/semaphore/apps/ansible/9.4.0/venv/bin/ansible
  python version = 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014] (/opt/semaphore/apps/ansible/9.4.0/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /opt/semaphore/apps/ansible/9.4.0/venv/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.5.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /tmp/semaphore/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/tmp/semaphore/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/tmp/semaphore/ansible.cfg) = yaml
HOST_KEY_CHECKING(/tmp/semaphore/ansible.cfg) = False
```

### OS / Environment

semaphore running in docker on debian host

### Steps to Reproduce

see above

### Expected Results

it should return ok & not changed, the CT is absent aloready, ok it had nothing to do but still, should not fail

### Actual Results

see above

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
