### ISSUE TITLE
community.general.snmp_facts    "msg": "No SNMP response received before timeout"

### ISSUE THREAD

**Issue by feisa** [ansible-collections/community.general#980]
##### SUMMARY
community.general.snmp_facts timeouts with No SNMP response received before timeout. Would be nice to increase the timeout or make the timeout configurable 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
snmp_facts

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
cisco 3850

##### STEPS TO REPRODUCE
```
- name: Gather SNMP Facts 
  community.general.snmp_facts:
    host: "{{ inventory_hostname }}"
    version: v3
    username: snmp
    privacy: aes
    level: authPriv
    integrity: sha
    authkey: "{{ snmpv3 }}"
    privkey: "{{ snmpv3 }}"
  delegate_to: localhost
  no_log: false
  register: snmp_facts
  tags:
    - ios-gather-facts
```
##### ACTUAL RESULTS
```
        }
    },
    "msg": "No SNMP response received before timeout"
}
```
