### ISSUE TITLE
jenkins_node module should support adding remote agent config

### ISSUE THREAD

**Issue by rabin-io** [ansible-collections/community.general#9804]
### Summary

It would be useful if the module can config remote agents as well.

![Image](https://github.com/user-attachments/assets/b2230b8f-f64e-4b3c-9484-b815fec5d671)

```xml
<?xml version="1.1" encoding="UTF-8"?>
<slave>
  <name>my-agent</name>
  <description></description>
  <remoteFS>/home/cnv-qe-jenkins/jenkins</remoteFS>
  <numExecutors>10</numExecutors>
  <mode>EXCLUSIVE</mode>
  <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
  <launcher class="hudson.plugins.sshslaves.SSHLauncher" plugin="ssh-slaves@2.973.v0fa_8c0dea_f9f">
    <host>my-agent</host>
    <port>22</port>
    <credentialsId>ssh-as-cnv-ec2-with-jenkins-ci-private-key</credentialsId>
    <launchTimeoutSeconds>60</launchTimeoutSeconds>
    <maxNumRetries>10</maxNumRetries>
    <retryWaitTime>15</retryWaitTime>
    <sshHostKeyVerificationStrategy class="hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy"/>
    <tcpNoDelay>true</tcpNoDelay>
  </launcher>
  <label>my-agent</label>
  <nodeProperties/>
</slave>
```

### Issue Type

Feature Idea

### Component Name

jenkins_node

### Additional Information

```yaml (paste below)
    - name: Create a Jenkins node
      community.general.jenkins_node:
        name: my-node
        state: present
        labels:
          - my-label
        launcher: ssh
        launcher_params:
          host: my-agent
          credentialsId: ssh-as-cnv-ec2-with-jenkins-ci-private-key
          port: 22
          host_key_verification_strategy: false
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
