### ISSUE TITLE
Parted does not set partition name when flags is null

### ISSUE THREAD

**Issue by rslarson** [ansible-collections/community.general#9820]
### Summary

When creating partitions with the parted module, if I do not set a flag for the partition, the generated script does not create a partition name.

### Issue Type

Bug Report

### Component Name

parted

### Ansible Version

```console (paste below)
# ansible --version
ansible [core 2.18.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console (paste below)
# ansible-galaxy collection list community.general


# /usr/lib/python3.13/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.4.0 
```

### Configuration

```console (paste below)
# ansible-config dump --only-changed
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less

GALAXY_SERVERS:
```

### OS / Environment

Arch Linux
```console
# cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
IMAGE_ID=archlinux
IMAGE_VERSION=2025.03.01
```

### Steps to Reproduce

```yaml (paste below)
- name: Create EFI Partition
  community.general.parted:
    device: '{{ disksetup_boot_drive }}'
    name: esp
    number: 1
    flags:
      - esp
    label: gpt
    part_start: 1MiB
    part_end: 1GiB
    state: present
  register: _efi_cmd

- name: (Debug) Print EFI parted script
  ansible.builtin.debug:
    msg: '{{ _efi_cmd.script }}'

- name: Create root Partition
  community.general.parted:
    device: '{{ disksetup_boot_drive }}'
    name: root
    number: 5
    label: gpt
    part_start: 1GiB
    part_end: 100%
    state: present
  register: _root_cmd

- name: (Debug) Print root parted script
  ansible.builtin.debug:
    msg: '{{ _root_cmd.script }}'
```

### Expected Results

Similar to the ESP parted script, it would set the partition name.

```console
TASK [disksetup : (Debug) Print EFI parted script] ************************************************************************************************************
ok: [localhost] => {
    "msg": "unit KiB mklabel gpt mkpart primary 1MiB 1GiB unit KiB name 1 '\"esp\"' set 1 esp on set 1 boot on"
}
```

### Actual Results

Without a partition flag, the parted module does not set a partition name

```console (paste below)
TASK [disksetup : (Debug) Print root parted script] ***********************************************************************************************************
ok: [localhost] => {
    "msg": "unit KiB mkpart primary 1GiB 100%"
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
