### ISSUE TITLE
consul_token changed state without any changes

### ISSUE THREAD

**Issue by dnsppv** [ansible-collections/community.general#9841]
### Summary

At any run of module consul_token it returns changed state, although there weren't any changes

### Issue Type

Bug Report

### Component Name

consul_token

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.8]
  config file = /home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg
  configured module search path = ['/home/denis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/denis/git/[REDACTED]/devops/ansible/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/denis/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/denis/git/[REDACTED]/devops/ansible/.venv/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/home/denis/git/[REDACTED]/devops/ansible/.venv/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console
$ ansible-galaxy collection list community.general

# /home/denis/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.4.0 

# /home/denis/git/[REDACTED]/devops/ansible/.venv/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 9.5.2  
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
CALLBACKS_ENABLED(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = ['profile_tasks']
CONFIG_FILE() = /home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg
DEFAULT_FORKS(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = smart
DEFAULT_REMOTE_USER(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = ['/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/roles', '/home/denis/.ansible/roles', '/usr/share>
DEFAULT_STDOUT_CALLBACK(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = yaml
DIFF_ALWAYS(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = True
DIFF_CONTEXT(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = 3
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/home/denis/git/[REDACTED]/devops/ansible/tp-ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 22.04.5 LTS

### Steps to Reproduce

1. Run playbook with these tasks, apply changes
```yaml
- name: Create ACL policy
  community.general.consul_policy:
    name: acl-{{ item.key }}
    description: Policy for {{ item.key }} ACL
    token: "{{ consul_server_master_token }}"
    rules: "{{ item.value }}"
  loop: "{{ consul_server_acl_policies | dict2items }}"
  when: node_index == "1"

- name: Create token for ACL policy
  community.general.consul_token:
    accessor_id: "{{ item.value.id }}"
    token: "{{ consul_server_master_token }}"
    secret_id: "{{ item.value.token }}"
    description: Token for {{ item.key }} ACL policy
    policies:
      - name: acl-{{ item.key }}
  loop: "{{ consul_server_acl_tokens | dict2items }}"
  when: node_index == "1"
```
2. Run playbook again without any changes in variables

### Expected Results

```console
TASK [consul_server : Create ACL policy] ***********************************************************************************************************************************************
[REDACTED] (0:00:00.176)       0:00:02.980 ********* 
skipping: ...
...
skipping: ...
ok: ...
ok: ...
ok: ...
ok: ...

TASK [consul_server : Create token for ACL policy] *************************************************************************************************************************************
[REDACTED] (0:00:01.942)       0:00:04.922 ********* 
skipping: ...
...
skipping: ...
ok: ...
ok: ...
ok: ...
ok: ...
```

### Actual Results

```console
TASK [consul_server : Create ACL policy] ***********************************************************************************************************************************************
[REDACTED] (0:00:00.274)       0:00:02.442 ********* 
skipping: ...
...
skipping: ...
ok: ...
ok: ...
ok: ...
ok: ...

TASK [consul_server : Create token for ACL policy] *************************************************************************************************************************************
[REDACTED] (0:00:02.038)       0:00:04.481 ********* 
skipping: ...
...
skipping: ...
--- before
+++ after
@@ -4,7 +4,7 @@
 Description: Token for consul-agent ACL policy
 Hash: [REDACTED]
 Local: false
-ModifyIndex: 92913
+ModifyIndex: 93152
 Policies:
 - ID: 6ef2412e-54cc-d0f7-3d66-896d29ade2b6
   Name: acl-consul-agent

changed: ...
--- before
+++ after
@@ -4,7 +4,7 @@
 Description: Token for vault ACL policy
 Hash: [REDACTED]
 Local: false
-ModifyIndex: 92914
+ModifyIndex: 93153
 Policies:
 - ID: da5c8b96-cd66-be75-b7b0-f8371099b536
   Name: acl-vault

changed: ...
--- before
+++ after
@@ -4,7 +4,7 @@
 Description: Token for prometheus ACL policy
 Hash: [REDACTED]
 Local: false
-ModifyIndex: 92915
+ModifyIndex: 93154
 Policies:
 - ID: 6e8dbad5-87d0-4083-fce5-0da3167fd902
   Name: acl-prometheus

changed: ...
--- before
+++ after
@@ -4,7 +4,7 @@
 Description: Token for consul-backinator ACL policy
 Hash: [REDACTED]
 Local: false
-ModifyIndex: 92917
+ModifyIndex: 93155
 Policies:
 - ID: 5ec90f1e-5e95-151d-2e28-ffe32fbad38a
   Name: acl-consul-backinator

changed: ...
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/consul_token.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/consul_token.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @Ilgmi @apollo13 @sgargan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by dnsppv** [comment]
For those who faced the same issue I made a workaround:
```yaml
---
- name: Create ACL policy
  community.general.consul_policy:
    name: acl-{{ item.key }}
    description: Policy for {{ item.key }} ACL
    token: "{{ consul_server_master_token }}"
    rules: "{{ item.value }}"
  loop: "{{ consul_server_acl_policies | dict2items }}"
  when: node_index == "1"

# Changing secret_id is not possible, need to delete token firstly
- name: Create token for ACL policy
  community.general.consul_token:
    accessor_id: "{{ item.value.id }}"
    token: "{{ consul_server_master_token }}"
    secret_id: "{{ item.value.token }}"
    description: Token for {{ item.key }} ACL policy
    policies:
      - name: acl-{{ item.key }}
  loop: "{{ consul_server_acl_tokens | dict2items }}"
  when: node_index == "1"
  changed_when: false
  register: output

- name: Report token change
  ansible.builtin.debug:
    msg:
      - Token
        id = '{{ item.token.AccessorID }}'
        description = '{{ item.token.Description }}'
        has been changed
  loop: "{{ output.results }}"
  when:
    - node_index == "1"
    - item.diff.before.Hash | default('none', true) != item.diff.after.Hash | default('hash', true)
    - not ansible_check_mode
  changed_when:
    - item.diff.before.Hash | default('none', true) != item.diff.after.Hash | default('hash', true)
```
