### ISSUE TITLE
nagios: improve documentation

### ISSUE THREAD

**Issue by miniwark** [ansible-collections/community.general#9870]
### Summary

The documentation of nagios module docs did not explain anything about the actual Nagios server who need to receive the nagios commands. All examples assume than the managed host is also a nagios server (or as at last than there is a nagios command on the managed host).

This will not work with many managed hosts (for example the one who a `nrpe` demon).

The way to work is probably to add `delegate_to` to the role for example:
```
- name: Schedule downtime for all services on host
  community.general.nagios:
    action: downtime
    minutes: 60
    service: all
    host: "{{ inventory_hostname }}"
    comment: "Mise à jour des applications Cocktail"
  delegate_to: nagios.example.com
```

(with nagios.example.com available via `ssh`)

### Issue Type

Documentation Report

### Component Name

nagios

### Community.general Version

version 10.3.0

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/nagios.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/nagios.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @tbielawa @tgoetheyn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
That usually depends on the software, and how the module can communicate and does communicate with the software. I don't know whether Nagios even has an admin API that can be used from another host.

Regarding the docs: it doesn't have to be added, but it also isn't disallowed. Whether it makes sense probably depends on Nagios.

**Comment by miniwark** [comment]
Hello,

it's was not completely obvious at last for me. If i simply follow one of the examples from the docs:
```
- name: Set 30 minutes of apache downtime
  community.general.nagios:
    action: downtime
    minutes: 30
    service: httpd
    host: '{{ inventory_hostname }}'
```
For example, for managing Apache web server (with a nrpe demon, but without a nagios command line)
I will get the error:
```
“msg”: “unable to locate nagios.cfg”
```
Witch is perfectly normal, because the managed host is of course not a Nagios server.
(My fault was probably of course to expect some sort of magic)

That said, before this module, i never heard nor have the need for the `delegate_to` option.

It's thanks to this forum page than i was able to use the module:
[https://forum.ansible.com/t/nagios-module-scheduling-downtime/30191](https://forum.ansible.com/t/nagios-module-scheduling-downtime/30191)

And i am not the fist one to encounter the issue:
[https://forum.ansible.com/t/using-nagios-module-from-ansible-galaxy-in-awx/36048](https://forum.ansible.com/t/using-nagios-module-from-ansible-galaxy-in-awx/36048)

At last, one example with the `delegate_to` option would be nice.
