### ISSUE TITLE
nmcli not idempotent on german CentOS

### ISSUE THREAD

**Issue by lukashartl** [ansible-collections/community.general#989]
### SUMMARY

When running a simple `nmcli`-Task on a CentOS7 machine that is using the german language pack, the task **always** returns `CHANGED`, although nothing has changed.

This is most likely due to the fact, that the `nmcli` with a german `$LANG` always returns `yes` as `ja` and `ansible` thinks that this means that the values don't match, although `yes` == `ja` in German.

I also provided a fix down below for all the people that might also come across this ~~issue~~ minor inconvenience.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`community.general.nmcli `

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /Users/lukas/Developer/ansible/ansible.cfg
  configured module search path = ['/Users/lukas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lukas/Developer/ansible/venv/lib/python3.8/site-packages/ansible
  executable location = /Users/lukas/Developer/ansible/venv/bin/ansible
  python version = 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/Users/lukas/Developer/ansible/ansible.cfg) = ['/Users/lukas/Developer/ansible/galaxy']
COMMAND_WARNINGS(/Users/lukas/Developer/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/Users/lukas/Developer/ansible/ansible.cfg) = ['/Users/lukas/Developer/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/Users/lukas/Developer/ansible/ansible.cfg) = ['/Users/lukas/Developer/ansible/galaxy', '/Users/lukas/Devel
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/Users/lukas/Developer/ansible/ansible.cfg) = True
DEPRECATION_WARNINGS(/Users/lukas/Developer/ansible/ansible.cfg) = True
DIFF_ALWAYS(/Users/lukas/Developer/ansible/ansible.cfg) = True
DIFF_CONTEXT(/Users/lukas/Developer/ansible/ansible.cfg) = 3
HOST_KEY_CHECKING(/Users/lukas/Developer/ansible/ansible.cfg) = True
SYSTEM_WARNINGS(/Users/lukas/Developer/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

* `macOS 10.15.7` on master
* `CentOS Linux release 7.8.2003 (Core)` on target node
  * with `LANG=de_AT.UTF-8`

##### STEPS TO REPRODUCE

```yaml
    - name: Try nmcli add bond - conn_name only & ip4 gw4 mode
      nmcli:
        type: ethernet
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.ifname }}'
        ip4: '{{ item.ip4 }}'
        gw4: '{{ item.gw4 }}'
        dns4: '{{ item.dns4 }}'
        state: present
      loop: '{{ common_nmcli_connections|default([]) }}'
      notify:
        - restart network
```

##### EXPECTED RESULTS

If nothing has changed, it should report the task as `OK`.

##### ACTUAL RESULTS

```paste below
TASK [common : Try nmcli add bond - conn_name only & ip4 gw4 mode] *************
--- before
+++ after
@@ -1,5 +1,5 @@
 {
-    "autoconnect": "ja",
+    "autoconnect": "yes",
     "ipv4.addresses": "xxxx/32 ...",
     "ipv4.dns": [
         "1.0.0.1",
changed: ...
```

##### POSSIBLE FIX

When I add the `environment` as stated below, it actually makes it idempotent again.

```paste below
    - name: Try nmcli add bond - conn_name only & ip4 gw4 mode
      nmcli:
        type: ethernet
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.ifname }}'
        ip4: '{{ item.ip4 }}'
        gw4: '{{ item.gw4 }}'
        dns4: '{{ item.dns4 }}'
        state: present
      loop: '{{ common_nmcli_connections|default([]) }}'
      notify:
        - restart network
      environment:
        LANG: en_US.utf8
```
