### ISSUE TITLE
remote source for github deploy key

### ISSUE THREAD

**Issue by dolvany** [ansible-collections/community.general#9917]
### Summary

It would be super cool if the github_deploy_key module has a remote_src parameter to grab the ssh key off of a managed node.

### Issue Type

Feature Idea

### Component Name

github_deploy_key

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibullbot** [comment]
Files identified in the description:
* [`plugins/modules/github_deploy_key.py`](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/github_deploy_key.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibullbot** [comment]
cc @bincyber @stpierre
[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by dolvany** [comment]
Or maybe this is workable as a two-step read the key and then use github_deploy_key. Seems like a good use case for the examples.

**Comment by dolvany** [comment]
Yeah, looks like a combo of the ssh keygen module and the deploy key module will get it done.

**Comment by felixfontein** [comment]
That sounds like a good idea. "grab the ssh key off of a managed node" can mean quite a lot of things to different people, it's kind of hard to have a generic mechanism for that which covers most cases. (Download a file from somewhere? Copy an existing SSH key from somewhere? Sniff a host key? Download a key from some other storage?) Using an appropriate module instead in a separate task is likely better :)

**Comment by bcoca** [comment]
I wrote  'onboarding' role in  (job -n) that pulled ssh keys for users in mgmt machine (`slurp`) and used `template` (later switched to `authorized_keys`) to push them to all other machines.  It complimented the  'begone' play/role for HR to run when they needed to ...

In other job, i just created an internal CA and had all hosts check keys against it, so no need to copy keys once the CA trust was setup.

**Comment by dolvany** [comment]
@felixfontein @bcoca here's what I ended up with. Seems to work well. Limited use case--just some VMs I run at home.
```
   - name: Keygen
     community.crypto.openssh_keypair:
      path: .ssh/id_ed25519
      type: ed25519
     register: keygen
   - name: Github deploy key
     community.general.github_deploy_key:
      owner: "dolvany"
      repository: "home"
      name: "{{ inventory_hostname }}"
      token: "{{ lookup('file', '.github_api_key') }}"
      key: "{{ keygen.public_key }}"
```
