### ISSUE TITLE
problem with apache2_module

### ISSUE THREAD

**Issue by xylle** [ansible-collections/community.general#9924]
### Summary

It's impossible to manipulate module state when apache2ctl -M is in error

I'm having problems using apache2_module
My module configuration is wrong. When running apach2ctl -M, I get an error which is normal for the configuration stage.
I want to deactivate the module that generates this error, but it's impossible.

The _module_is_enabled function executes apach2ctl -M, which fails.
Would it be possible, when encountering this problem, to trust the module name used and perform the action (activation or deactivation)?

### Issue Type

Bug Report

### Component Name

apache2_module

### Ansible Version

```console  (paste below)
ansible [core 2.18.3]
  config file = /home/toto/Documents/projets/python/migration_ansible/ansible.cfg
  configured module search path = ['/home/toto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/toto/Documents/projets/python/migration_ansible/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/toto/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/toto/Documents/projets/python/migration_ansible/.venv/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/home/toto/Documents/projets/python/migration_ansible/.venv/bin/python)
  jinja version = 3.1.6
  libyaml = True


```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```

### Configuration

Collection        Version
----------------- -------
community.general 10.4.0 

### OS / Environment

Debian 12

### Steps to Reproduce

```yaml (paste below)
    - name: "Gestion modules Apache"
      community.general.apache2_module:
        name: "{{ apache_module.module }}"
        state: "{{ apache_module.state }}"
        ignore_configcheck: true
      loop:
        - module: php8.2
          state: absent
        - module: rewrite
          state: present
        - module: ssl
          state: present
        - module: wsgi
          state: present
        - module: mpm_event
          state: absent
        - module: mpm_prefork
          state: present
      loop_control:
        loop_var: apache_module

```

### Expected Results

Module activated or deactivated

### Actual Results

```console (paste below)
ok: [test-restauration.example.org] => (item={'module': 'php8.2', 'state': 'absent'})
failed: [test-restauration.example.org] (item={'module': 'rewrite', 'state': 'present'}) => {
    "ansible_loop_var": "apache_module",
    "apache_module": {
        "module": "rewrite",
        "state": "present"
    },
    "changed": false,
    "rc": 0
}

STDOUT:

Module rewrite already enabled



MSG:

Failed to set module rewrite to enabled:
Module rewrite already enabled

Maybe the module identifier (rewrite_module) was guessed incorrectly.Consider setting the "identifier" option.
failed: [test-restauration.example.org] (item={'module': 'ssl', 'state': 'present'}) => {
    "ansible_loop_var": "apache_module",
    "apache_module": {
        "module": "ssl",
        "state": "present"
    },
    "changed": false,
    "rc": 0
}

STDOUT:

Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled



MSG:

Failed to set module ssl to enabled:
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled

Maybe the module identifier (ssl_module) was guessed incorrectly.Consider setting the "identifier" option.
failed: [test-restauration.example.org] (item={'module': 'wsgi', 'state': 'present'}) => {
    "ansible_loop_var": "apache_module",
    "apache_module": {
        "module": "wsgi",
        "state": "present"
    },
    "changed": false,
    "rc": 0
}

STDOUT:

Module wsgi already enabled



MSG:

Failed to set module wsgi to enabled:
Module wsgi already enabled

Maybe the module identifier (wsgi_module) was guessed incorrectly.Consider setting the "identifier" option.
ok: [test-restauration.example.org] => (item={'module': 'mpm_event', 'state': 'absent'})
failed: [test-restauration.example.org] (item={'module': 'mpm_prefork', 'state': 'present'}) => {
    "ansible_loop_var": "apache_module",
    "apache_module": {
        "module": "mpm_prefork",
        "state": "present"
    },
    "changed": false,
    "rc": 0
}

STDOUT:

Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled



MSG:

Failed to set module mpm_prefork to enabled:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled

Maybe the module identifier (mpm_prefork_module) was guessed incorrectly.Consider setting the "identifier" option.

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
