### ISSUE TITLE
github_app_access_token should support least-privilege

### ISSUE THREAD

**Issue by jrobison-sb** [ansible-collections/community.general#9955]
### Summary

The `github_app_access_token` lookup uses an API call to the GitHub API to obtain a token from a GitHub App. Currently it does not support the `permissions` parameter for the API call, which means users cannot request a token with least-privilege.

An optional `permissions` attribute should be added to this lookup plugin, which would map to the `permissions` parameter in the API call to allow users to request a token with least-privilege. https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app

See this GitHub Action which uses the same GitHub API for an example of how they offer least-privilege support: https://github.com/peter-murray/workflow-application-token-action#using-the-github-action-in-a-workflow

### Issue Type

Feature Idea

### Component Name

github_app_access_token

### Additional Information

```yaml (paste below)
- name: Get access token to be used for git checkout with app_id=123456, installation_id=64209
  ansible.builtin.git:
    repo: >-
      https://x-access-token:{{ github_token }}@github.com/hidden_user/super-secret-repo.git
    dest: /srv/checkout
  vars:
    github_token: >-
      {{ lookup('community.general.github_app_access_token', key_path='/home/to_your/key',
                app_id='123456', installation_id='64209', permissions='contents:read') }}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
