### ISSUE TITLE
community.general.dnsmadeeasy - Always updates existing A record

### ISSUE THREAD

**Issue by pmannozg** [ansible-collections/community.general#9956]
### Summary

Hello,
When using the community.general.dnsmadeeasy module it seems to update existing A records if found.  However, I would like to add multiple A records for DNS RR.  This does not seem possible with the module, but is possible using the API.

Use case is for dynamic instances rolling up via an auto-scaling group, I want them to add their A record upon startup so they end up in the DNS RR pool of instances.  When doing so via an ansible playbook on the host that gets executed during startup, the existing A record gets updated and there is no way to tell the module to always create a new record, and not update the existing (that I can see).  Please correct me if I'm wrong.  

### Issue Type

Feature Idea

### Component Name

community.general.dnsmadeeasy

### Additional Information

```yaml (paste below)
    - name: Create A record in DNS Made Easy
      community.general.dnsmadeeasy:
        account_key: "{{ dnsme_api_key }}"
        account_secret: "{{ dnsme_secret_key }}"
        domain: <domain_id>
        state: present
        record_name: myhost
        record_type: A
        record_value: "{{ ansible_facts.ec2_public_ipv4 }}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
