### ISSUE TITLE
Not possible to pin multiple packages

### ISSUE THREAD

**Issue by judaly** [ansible-collections/community.general#9958]
### Summary

On the page https://docs.ansible.com/ansible/latest/collections/community/general/dnf_versionlock_module.html#ansible-collections-community-general-dnf-versionlock-module
- name: Prevent multiple packages from being updated
  community.general.dnf_versionlock:
    name:
      - nginx
      - haproxy
    state: present
is shown
But when i attempted to run this with only two in the list; grafana and prometheus, it only pinned grafana
Running with ansible version 2.18.4

### Issue Type

Bug Report

### Component Name

community.general.dnf_versionlock

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.4]
  config file = /home/dalyj/work/monitoring-management/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/root/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.6
  libyaml = True


```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```
# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 6.6.2  

# /home/dalyj/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.4.0 

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Rocky version 9

### Steps to Reproduce

```yaml (paste below)


  - name: install  python3-dnf-plugin-versionlock
    ansible.builtin.dnf:
      name:  python3-dnf-plugin-versionlock
      state: present
        #
  - name: ping the version of grafana and prometheus (Prevent multiple packages from being updated)
    community.general.dnf_versionlock:
      name:
        - grafana
        - prometheus
      state: present

```

### Expected Results

I expected to see grafana and prometheus in the list but only got grafana

### Actual Results

```console (paste below)
[root@grafana ~]# cat  /etc/yum/pluginconf.d/versionlock.list

# Added lock on Wed Apr  2 11:30:24 2025
grafana-0:11.5.2-1.*

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
