### ISSUE TITLE
add skip rpm post-install errors feature (zypper return code 107) to zypper module

### ISSUE THREAD

**Issue by mk2km** [ansible-collections/community.general#9972]
### Summary

Add skip rpm post-install errors feature (zypper return code 107) to the zypper module, allowing it to return **changed**, e.g.:

```yaml
- name: install post_error rpm with skip_post_errors == true
  zypper:
    name: "{{ remote_tmp_dir | expanduser }}/zypper2/rpm-build/noarch/post_error-1-0.noarch.rpm"
    disable_gpg_check: true
    skip_post_errors: true
```

```bash
TASK [zypper : install post_error rpm with skip_post_errors] *******************
changed: [testhost] => {"changed": true, "cmd": <skipped>
```

instead of **fatal**, e.g:

```yaml
- name: install post_error rpm with skip_post_errors == false
  zypper:
    name: "{{ remote_tmp_dir | expanduser }}/zypper2/rpm-build/noarch/post_error-1-0.noarch.rpm"
    disable_gpg_check: true
    skip_post_errors: false # default
```

```bash
TASK [zypper : install post_error rpm without skip_post_errors] ****************
fatal: [testhost]: FAILED! => {"changed": false, "cmd": <skipped>
```

The main idea of this to handle [zypper 107 return code](https://en.opensuse.org/SDB:Zypper_manual#EXIT_CODES):

> 107 - ZYPPER_EXIT_INF_RPM_SCRIPT_FAILED
> Installation basically succeeded, but some of the packages %post install scripts returned an error. **These packages were successfully unpacked to disk and are registered** in the rpm database, but due to the failed install script they may not work as expected. The failed scripts output might reveal what actually went wrong. Any scripts output is also logged to /var/log/zypp/history.

Reasons for the **skip_post_errors** flag:
- **It doesn’t change the module’s default behavior**.
- In two sequential zypper runs with an rpm that has a post-install error, the error is fatal only on the first run. On the second run, the rpm is already installed, so the issue may go unnoticed unless handled on the first run.
- Sometimes, the rpm post-install can just be skipped (e.g., if you have your own configuration script for the rpm).
- For testing purposes, if you build your own RPM and it may have post-install errors, but you only need to unpack it.
- If you have a list of rpms, a post-install error in one of them will not break the installation of the others (and the affected rpms will still be unpacked and registered).

### Issue Type

Feature Idea

### Component Name

zypper

### Additional Information

```yaml (paste below)
- name: install post_error rpm with skip_post_errors
  zypper:
    name: "{{ remote_tmp_dir | expanduser }}/zypper2/rpm-build/noarch/post_error-1-0.noarch.rpm"
    disable_gpg_check: true
    skip_post_errors: true
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
